$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "安全认证 ", 
"url" : "sil2_certification_disclaimer.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 安全认证 ", 
"snippet" : "请注意，以下页面中的文档仅供参考。有关安全或认证的限制和信息，请参阅您正在编程的设备制造商提供的安全文档。...", 
"body" : "请注意，以下页面中的文档仅供参考。有关安全或认证的限制和信息，请参阅您正在编程的设备制造商提供的安全文档。 " }, 
{ "title" : "CODESYS Safety SIL2 ", 
"url" : "_sil2_start_page.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ CODESYS Safety SIL2 ", 
"snippet" : "CODESYS Safety SIL2 是一个组件 CODESYS Development System 。 SIL 代表 IEC 61508 规定的“安全完整性级别”，描述了控制器安全相关功能的安全相关要求。 和 CODESYS Safety SIL2 ，您可以配置和操作 SIL2 控制器。它允许您使用预先认证的安全软件组件为移动应用创建和编程您自己的 SIL2 控制器。...", 
"body" : "CODESYS Safety SIL2 是一个组件 CODESYS Development System 。 SIL 代表 IEC 61508 规定的“安全完整性级别”，描述了控制器安全相关功能的安全相关要求。 和 CODESYS Safety SIL2 ，您可以配置和操作 SIL2 控制器。它允许您使用预先认证的安全软件组件为移动应用创建和编程您自己的 SIL2 控制器。 " }, 
{ "title" : "有关安全 SIL2 PLC 操作的基本信息 ", 
"url" : "sil2_overview.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 有关安全 SIL2 PLC 操作的基本信息 ", 
"snippet" : "这 CODESYS Safety SIL2 包扩展了 CODESYS 带有附加命令的编程系统 进入调试模式 （在里面 SIL2 菜单）和通用编辑器中的附加子对话框。 以下章节提供了一些基本信息，以帮助您更轻松地使用安全 SIL2 PLC。 登录类型：设备登录和应用登录 每个 CODESYS V3 运行时系统的不同之处在于以下登录类型： 设备登录 设备登录是第一级登录。它只显示运行时系统的基本状态，表示在设备树中选择的设备是否连接到相应的运行时系统。 未连接： 连接的： 应用登录 执行应用程序登录时，安全 SIL2 扩展程序检查当前活动的应用程序是否可以这样做，以及在 PLC 的当前安全 SIL...", 
"body" : "这 CODESYS Safety SIL2 包扩展了 CODESYS 带有附加命令的编程系统 进入调试模式 （在里面 SIL2 菜单）和通用编辑器中的附加子对话框。 以下章节提供了一些基本信息，以帮助您更轻松地使用安全 SIL2 PLC。 登录类型：设备登录和应用登录 每个 CODESYS V3 运行时系统的不同之处在于以下登录类型： 设备登录 设备登录是第一级登录。它只显示运行时系统的基本状态，表示在设备树中选择的设备是否连接到相应的运行时系统。 未连接： 连接的： 应用登录 执行应用程序登录时，安全 SIL2 扩展程序检查当前活动的应用程序是否可以这样做，以及在 PLC 的当前安全 SIL2 操作模式中是否允许这样做。只有在以下情况下才可以进行应用程序登录： “安全运行”模式：活动应用程序已下载并作为“安全加载”启动应用程序运行。这可以在应用程序登录之前通过将 PLC 的代码校验和与活动应用程序进行比较在“安全”编辑器对话框中进行检查。只有当这些校验和匹配时才能登录。校验和的显示可以通过关闭并重新打开设备编辑器或单击 刷新 按钮。 “DEBUG”模式：对应用程序登录没有限制 " }, 
{ "title" : "安全 SIL2 控制器的操作模式 ", 
"url" : "sil2_overview.html#UUID-93a9551b-409a-5184-bf63-602780885415_id_b82a56e6818206c0a8640e011b6a17_id_4ec1a850e6969c58c0a8640e016c51c5", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 有关安全 SIL2 PLC 操作的基本信息 \/ 安全 SIL2 控制器的操作模式 ", 
"snippet" : "对于 Safety SIL2 runtime 系统，控制器有两种运行模式，显示在状态栏中： ：“安全运行”模式 在此模式下，应用程序的可能操作受到限制：仅允许对应用程序进行读取访问，例如监视应用程序中的变量。检测到影响设备的命令。 ： “调试模式 在这种模式下，对 PLC 上运行的应用程序的访问没有任何限制。仅在“调试”模式下才允许下载应用程序（例如，由于应用程序登录而隐式执行）以及对该应用程序的其他写入访问。 PLC的运行方式不能随意控制。 PLC 的“安全运行”模式只能通过下载安全启动应用程序并重新启动硬件来实现。但是，您可以通过以下方式切换到“DEBUG”模式 进入调试模式 命令。 注意...", 
"body" : "对于 Safety SIL2 runtime 系统，控制器有两种运行模式，显示在状态栏中： ：“安全运行”模式 在此模式下，应用程序的可能操作受到限制：仅允许对应用程序进行读取访问，例如监视应用程序中的变量。检测到影响设备的命令。 ： “调试模式 在这种模式下，对 PLC 上运行的应用程序的访问没有任何限制。仅在“调试”模式下才允许下载应用程序（例如，由于应用程序登录而隐式执行）以及对该应用程序的其他写入访问。 PLC的运行方式不能随意控制。 PLC 的“安全运行”模式只能通过下载安全启动应用程序并重新启动硬件来实现。但是，您可以通过以下方式切换到“DEBUG”模式 进入调试模式 命令。 注意：此行为的详细信息在不同设备上可能有所不同。 " }, 
{ "title" : "设备编辑器 - 安全 ", 
"url" : "sil2_device_editor_safety.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 设备编辑器 - 安全 ", 
"snippet" : "通用设备编辑器的此子对话框用于获取和检查设备和活动应用程序的 SIL2 相关信息。此外，还显示 PLC 的安全日志条目。 设备编辑器中的安全对话框 要更新和查看安全 PLC 上的安全 SIL2 记录器的消息，请选择 自动刷新 选项或单击 刷新 按钮即时刷新。...", 
"body" : "通用设备编辑器的此子对话框用于获取和检查设备和活动应用程序的 SIL2 相关信息。此外，还显示 PLC 的安全日志条目。 设备编辑器中的安全对话框 要更新和查看安全 PLC 上的安全 SIL2 记录器的消息，请选择 自动刷新 选项或单击 刷新 按钮即时刷新。 " }, 
{ "title" : "进入调试模式 ", 
"url" : "sil2_enter_debug_mode.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 进入调试模式 ", 
"snippet" : "命令类别 SIL2 此命令将 Safety SIL2 PLC 的操作模式从 SAFE RUN 到 DEBUG .只有在执行了设备登录或应用程序登录后，该命令才可用。 为了便于处理，SIL2 菜单中提供了“连接到 [设备]”和“从 [设备] 断开连接”命令。 有关特殊登录类型的更多信息，请参阅： 有关安全 SIL2 PLC 操作的基本信息...", 
"body" : "命令类别 SIL2 此命令将 Safety SIL2 PLC 的操作模式从 SAFE RUN 到 DEBUG .只有在执行了设备登录或应用程序登录后，该命令才可用。 为了便于处理，SIL2 菜单中提供了“连接到 [设备]”和“从 [设备] 断开连接”命令。 有关特殊登录类型的更多信息，请参阅： 有关安全 SIL2 PLC 操作的基本信息" }, 
{ "title" : "复合安全PLC ", 
"url" : "sil2_f_compound_safety_plc.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "复合安全 PLC 概述 ", 
"url" : "sil2_compound_safety_plc.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ 复合安全 PLC 概述 ", 
"snippet" : "CODESYS Safety SIL2 延长 CODESYS 具有 “复合安全 PLC” 功能的编程系统。复合安全 PLC 包括安全应用程序和标准应用程序，可以并行运行。 具有复合安全 PLC 的设备树 复合安全 PLC 在以下方面与传统的安全 SIL2 PLC 基本不同： 结构：SIL2 控制器和逻辑父 PLC 下方的一个或多个标准 PLC 复合安全 PLC 的处理 CODESYS 项目不同于标准 PLC 的处理（创建新项目\/扫描 PLC 等的第一步） 有关更多信息，请参阅： 复合安全 PLC 的处理使用复合安全 PLC 处理 EVC\/EVL 有关更多信息 交换变量连接 ， 看： EVC，交...", 
"body" : "CODESYS Safety SIL2 延长 CODESYS 具有 “复合安全 PLC” 功能的编程系统。复合安全 PLC 包括安全应用程序和标准应用程序，可以并行运行。 具有复合安全 PLC 的设备树 复合安全 PLC 在以下方面与传统的安全 SIL2 PLC 基本不同： 结构：SIL2 控制器和逻辑父 PLC 下方的一个或多个标准 PLC 复合安全 PLC 的处理 CODESYS 项目不同于标准 PLC 的处理（创建新项目\/扫描 PLC 等的第一步） 有关更多信息，请参阅： 复合安全 PLC 的处理使用复合安全 PLC 处理 EVC\/EVL 有关更多信息 交换变量连接 ， 看： EVC，交换变量连接有关更多信息 交换变量列表 ， 看： EVL，交换变量列表同步安全应用程序和标准应用程序的任务 如果必须同步处理安全应用程序和标准应用程序的任务，则可以通过事件来同步它们。有两种选择： 如果控制器制造商为标准应用程序提供可以与安全应用程序任务同步的外部事件，则标准应用程序的任务可以定义为“外部事件任务”。这使得时间行为具有确定性。 与此无关，简单的“事件任务”也可以在标准应用程序中使用，它使用通过 EVC 提供的安全应用程序的事件变量。因为“事件任务”不会在事件设置后立即启动，所以计时行为是不确定的。 " }, 
{ "title" : "EVC，交换变量连接 ", 
"url" : "sil2_evc_overview.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC，交换变量连接 ", 
"snippet" : "这种机制简化了复合安全 PLC 中安全应用程序和标准应用程序之间的数据交换。 这 EVC 机制使用编辑器来支持从安全应用程序中选择应在标准应用程序中使用的变量。 EVC 编辑器 然后所选变量在标准应用程序中可用，并且可以像常规变量一样使用。 safe_Counter := EVC.POU.safeCounter unsafe_Counter := EVC.EVL.unsafeCounter; 这 EVC 允许交换变量： 在使用的全局变量列表 (GVL) 中，交换变量列表 ( EVL) 和安全应用程序 (PRG) 使用常规数据类型以及自定义数据类型 在 EVL 之外的 EVC 中选择的变量可以理...", 
"body" : "这种机制简化了复合安全 PLC 中安全应用程序和标准应用程序之间的数据交换。 这 EVC 机制使用编辑器来支持从安全应用程序中选择应在标准应用程序中使用的变量。 EVC 编辑器 然后所选变量在标准应用程序中可用，并且可以像常规变量一样使用。 safe_Counter := EVC.POU.safeCounter\nunsafe_Counter := EVC.EVL.unsafeCounter; 这 EVC 允许交换变量： 在使用的全局变量列表 (GVL) 中，交换变量列表 ( EVL) 和安全应用程序 (PRG) 使用常规数据类型以及自定义数据类型 在 EVL 之外的 EVC 中选择的变量可以理解为探针，可以在现有的安全应用程序中使用它来分析值而无需任何干预。 例子 测量点 S_xActive 可通过标准应用程序中的 EVC 获得，并可用于读取。 EVL 中的选定变量可以写入标准应用程序中。 EVC.EVL.xEnable := xCAN_In_ONSWITCH; 这样的变量也可以在安全应用中用作不安全输入（例如，以受控方式关闭机器）。 例子 通常，这适用于通过 EVC 提供的变量 EVL 中的变量可以毫无问题地从标准应用程序中写入和读取。 可以从标准应用程序中毫无问题地读取 EVL 之外的变量。但是，由于可能存在的内存保护，写访问可能导致安全应用程序处于安全状态。 " }, 
{ "title" : "使用 EVC 的限制 ", 
"url" : "sil2_evc_overview.html#UUID-f5592a42-311d-5f8e-30fb-8ed5334ce144_id_ba397a3a2408c0a8640e017ffb72_id_722186757a8b6ee2c0a8640e0064605c", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC，交换变量连接 \/ 使用 EVC 的限制 ", 
"snippet" : "功能块只提供接口变量。这包括在 FB 的声明部分中声明的所有变量。这意味着属性、转换、动作和方法不能在标准应用程序中使用。 通过 EVC 可用的功能模块不得由标准应用程序调用。 非法调用示例： 允许调用的示例：...", 
"body" : "功能块只提供接口变量。这包括在 FB 的声明部分中声明的所有变量。这意味着属性、转换、动作和方法不能在标准应用程序中使用。 通过 EVC 可用的功能模块不得由标准应用程序调用。 非法调用示例： 允许调用的示例： " }, 
{ "title" : "评论 ", 
"url" : "sil2_evc_overview.html#UUID-f5592a42-311d-5f8e-30fb-8ed5334ce144_id_ba397a3a2408c0a8640e017ffb72_id_8e8702507a8b6ee2c0a8640e01cdbaa1", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC，交换变量连接 \/ 评论 ", 
"snippet" : "通过 EVC 提供的所有变量都是安全应用实际变量的“参考”（定义为“REFERENCE TO”）。这意味着，例如，ADR 运算符不能用于这些变量。 根据所使用的控制器，可能无法保证通过 EVC 提供的变量的值是一致的。在交换除 LINT、ULINT 和 LWORD 之外的简单单个数据类型时，这不是问题。在交换相关数据时，必须以其他方式确保一致性（例如，使用适当的读\/写标志）。...", 
"body" : "通过 EVC 提供的所有变量都是安全应用实际变量的“参考”（定义为“REFERENCE TO”）。这意味着，例如，ADR 运算符不能用于这些变量。 根据所使用的控制器，可能无法保证通过 EVC 提供的变量的值是一致的。在交换除 LINT、ULINT 和 LWORD 之外的简单单个数据类型时，这不是问题。在交换相关数据时，必须以其他方式确保一致性（例如，使用适当的读\/写标志）。 " }, 
{ "title" : "EVC 状态检查 ", 
"url" : "sil2_evc_overview.html#UUID-f5592a42-311d-5f8e-30fb-8ed5334ce144_id_ba397a3a2408c0a8640e017ffb72_id_87bbcbacda9bf6bfc0a8640e01bb7195", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC，交换变量连接 \/ EVC 状态检查 ", 
"snippet" : "EVC 在安全应用程序和标准应用程序之间建立连接。 EVC 提供了一种机制，以便可以在运行时识别 EVC 提供的变量是否仍然引用安全应用程序的关联变量。...", 
"body" : "EVC 在安全应用程序和标准应用程序之间建立连接。 EVC 提供了一种机制，以便可以在运行时识别 EVC 提供的变量是否仍然引用安全应用程序的关联变量。 " }, 
{ "title" : "EVL，交换变量列表 ", 
"url" : "sil2_evl_overview.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVL，交换变量列表 ", 
"snippet" : "这个对象 EVL 是一种特殊类型的全局变量列表 (GVL)，可用于在复合安全 PLC 中的安全控制器和非安全 PLC 之间交换不安全数据。 可以像在传统 GVL 中一样在此处声明变量。但是，EVL 中的所有变量都是在“不安全数据区”(16#0800) 中创建的。这允许从不安全的应用程序对这些变量进行写访问。 有关使用的更多信息，请参阅： 复合安全 PLC 概述 和 复合安全 PLC 的处理...", 
"body" : "这个对象 EVL 是一种特殊类型的全局变量列表 (GVL)，可用于在复合安全 PLC 中的安全控制器和非安全 PLC 之间交换不安全数据。 可以像在传统 GVL 中一样在此处声明变量。但是，EVL 中的所有变量都是在“不安全数据区”(16#0800) 中创建的。这允许从不安全的应用程序对这些变量进行写访问。 有关使用的更多信息，请参阅： 复合安全 PLC 概述 和 复合安全 PLC 的处理" }, 
{ "title" : "复合安全 PLC 的处理 ", 
"url" : "sil2_handling_compound_safety_plc.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ 复合安全 PLC 的处理 ", 
"snippet" : "由于复合安全 PLC 由一些安全控制器和标准控制器之间的结构化关系组成，因此需要对一些标准用例进行特殊处理： 创建新项目的第一步 设备更新 设备搜索\/与 PLC 通信 还请查看设备制造商的 OEM 文档，了解有关该制造商的复合安全 PLC 的特殊处理或要求的任何说明。 设备搜索\/通讯 在标准复合安全 PLC 中，设备搜索和通信的处理与标准 PLC 略有不同。 复合安全 PLC 的设备搜索 复合安全 PLC 有一个根 PLC，只有它能够并负责执行设备搜索。要浏览复合安全 PLC，请使用选项卡 通讯设置 根 PLC（类似于标准 CODESYS -PLC）。 注意：在子设备中有选项卡 通讯设置 不是...", 
"body" : "由于复合安全 PLC 由一些安全控制器和标准控制器之间的结构化关系组成，因此需要对一些标准用例进行特殊处理： 创建新项目的第一步 设备更新 设备搜索\/与 PLC 通信 还请查看设备制造商的 OEM 文档，了解有关该制造商的复合安全 PLC 的特殊处理或要求的任何说明。 设备搜索\/通讯 在标准复合安全 PLC 中，设备搜索和通信的处理与标准 PLC 略有不同。 复合安全 PLC 的设备搜索 复合安全 PLC 有一个根 PLC，只有它能够并负责执行设备搜索。要浏览复合安全 PLC，请使用选项卡 通讯设置 根 PLC（类似于标准 CODESYS -PLC）。 注意：在子设备中有选项卡 通讯设置 不是。 如果设备搜索成功并且为根 PLC 设置了“活动路径”，那么您将在查看中看到一条消息 消息 ，确认子设备的通信设置已在后台自动进行。 连接到 PLC 复合安全 PLC 的子设备是独立的 PLC，但它们的通信设置或 EVL\/EVC 除外。 这意味着：“应用程序下载”、“启动应用程序”、“进入调试模式”等在线服务是特定于所选子设备的（通过“活动应用程序”）。 示例：子设备 A 上的应用程序下载仅由子设备 A 处理，依此类推。子设备B的应用不受影响。 " }, 
{ "title" : "创建新项目的第一步 ", 
"url" : "sil2_handling_compound_safety_plc.html#UUID-5833a7d5-4cf3-d8a3-87b9-888fec250d75_id_fed4697da228692c0a8640e00769870_id_ae4cd1a5c1a211e49fb2f0cd9625ba85", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ 复合安全 PLC 的处理 \/ 创建新项目的第一步 ", 
"snippet" : "的默认助手 CODESYS 用于创建标准项目支持自动创建复合安全 PLC CODESYS -项目不。所以第一步如下： 插入一个空格 CODESYS - 项目。 在视图中 设备 添加新设备：右键单击根节点并选择 添加设备 从上下文菜单中。 在对话中 添加设备 为 Compound Safety PLC 选择正确的设备并使用 添加设备 . 复合安全 PLC 出现在视图中 设备 ： 具有复合安全 PLC 的设备树...", 
"body" : "的默认助手 CODESYS 用于创建标准项目支持自动创建复合安全 PLC CODESYS -项目不。所以第一步如下： 插入一个空格 CODESYS - 项目。 在视图中 设备 添加新设备：右键单击根节点并选择 添加设备 从上下文菜单中。 在对话中 添加设备 为 Compound Safety PLC 选择正确的设备并使用 添加设备 . 复合安全 PLC 出现在视图中 设备 ： 具有复合安全 PLC 的设备树 " }, 
{ "title" : "设备更新 ", 
"url" : "sil2_handling_compound_safety_plc.html#UUID-5833a7d5-4cf3-d8a3-87b9-888fec250d75_id_fed4697da228692c0a8640e00769870_id_09389718da39f58fc0a8640e006cea49", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ 复合安全 PLC 的处理 \/ 设备更新 ", 
"snippet" : "复合安全 PLC 可以由多个设备组成，参见上图。因此，如果要更新复合安全 PLC 的所有部分，请使用命令 更新设备 对于每个相关的设备。请参阅以下推荐步骤： 为您要更新的设备安装所有 OEM 提供的设备描述，这些设备是 Compound Safety PLC 的一部分。 更新根 PLC 设备。 更新根 PLC 下的所有设备。...", 
"body" : "复合安全 PLC 可以由多个设备组成，参见上图。因此，如果要更新复合安全 PLC 的所有部分，请使用命令 更新设备 对于每个相关的设备。请参阅以下推荐步骤： 为您要更新的设备安装所有 OEM 提供的设备描述，这些设备是 Compound Safety PLC 的一部分。 更新根 PLC 设备。 更新根 PLC 下的所有设备。 " }, 
{ "title" : "EVC\/EVL的处理 ", 
"url" : "sil2_handling_evc_and_evl.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC\/EVL的处理 ", 
"snippet" : "EVC 编辑器 当您打开 EVC 对象时，您将获得 EVC 编辑器。在此您配置安全子设备的应用程序的哪些变量应该在 EVC 对象所属的应用程序中可用。 EVC 示例 如果安全子设备的应用程序不是最新的（如果自上次成功生成代码后应用程序已更改），则 EVC 编辑器会显示以下类型的警告： Sichere Applikation wurde geändert und ist nicht aktuell. Führen Sie erst den Befehl „Erstellen” aus, um Variablen auswählen zu können. 如果要直接为安全应用程序生成代码，可以单击...", 
"body" : "EVC 编辑器 当您打开 EVC 对象时，您将获得 EVC 编辑器。在此您配置安全子设备的应用程序的哪些变量应该在 EVC 对象所属的应用程序中可用。 EVC 示例 如果安全子设备的应用程序不是最新的（如果自上次成功生成代码后应用程序已更改），则 EVC 编辑器会显示以下类型的警告： Sichere Applikation wurde geändert und ist nicht aktuell. Führen Sie erst den Befehl „Erstellen” aus, um Variablen auswählen zu können. 如果要直接为安全应用程序生成代码，可以单击按钮 创建 （建造）使用。之后，警告应该消失。 在 Safety Sub 设备的安全应用程序中找到的所有变量都以结构化的方式显示在 EVC 编辑器中。如果要访问单个变量，请单击相应的复选框。检查的变量是可访问的。要删除访问权限，请再次单击该复选框。 您可以使用命名空间“访问应用程序（EVC 所在的）中的所有可访问变量 EVC “ 使用权。 使用通过 EVC 对象发布的变量的代码示例 IF NOT EVC.GUIDS.xError AND EVC.GUIDS.xGuidValid THEN\n EVC.EVL.nonsafeVAr := 1;\n iVar := EVC.PLC_PRG.iVar;\nEND_IF 要检查 EVC 的状态，您应该使用隐式成员 GUIDS 应用程序中的 EVC 命名空间。隐式 GVL EVC.GUIDS 提供两个状态变量。这允许您监控所使用的 EVC 变量的一致性。 当前，您应该检查两个成员以确保该机制正常工作： EVC.GUIDS.xError TRUE ，当 EVC 机制内发生错误时 在这种情况下，停止访问由 EVC 机制提供\/发布的变量。您可能会使安全应用程序崩溃。 FALSE , 如果机制运行正确并且没有发生错误 您可以访问在 EVC 命名空间中发布的变量。 EVC.GUIDS.xGuidValid 显示 EVC 链接到的安全应用程序是否与项目中配置的完全相同（匹配 GUID） 如果这个变量是 FALSE ，然后停止访问由 EVC 机制提供\/发布的变量。您可能会使安全应用程序崩溃。 仅在以下情况下访问 EVC 命名空间中的变量 xError = FALSE 和 xGuidValid = TRUE .否则，安全子设备中的安全应用程序的安全功能可能会受到影响。 " }, 
{ "title" : "在复合安全 PLC 中使用 EVC\/EVL ", 
"url" : "sil2_handling_evc_and_evl.html#UUID-a9991460-b367-d17a-fe2b-56610984b3f0_id_ac33da33df83c0a8640e004c95e6_id_0fe14866da3a0b5dc0a8640e00d965e0", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC\/EVL的处理 \/ 在复合安全 PLC 中使用 EVC\/EVL ", 
"snippet" : "EVC（交换变量连接）可以在一个或多个非安全子设备中使用，以便能够访问安全子设备的（安全和非安全）变量。 示例：使用带 EVC\/EVL 的复合安全 PLC 的项目设备树...", 
"body" : "EVC（交换变量连接）可以在一个或多个非安全子设备中使用，以便能够访问安全子设备的（安全和非安全）变量。 示例：使用带 EVC\/EVL 的复合安全 PLC 的项目设备树 " }, 
{ "title" : "将 EVC 添加到非安全子设备 ", 
"url" : "sil2_handling_evc_and_evl.html#UUID-a9991460-b367-d17a-fe2b-56610984b3f0_id_ac33da33df83c0a8640e004c95e6_id_ef31789cda3a0b5dc0a8640e00ecfe86", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ EVC\/EVL的处理 \/ 将 EVC 添加到非安全子设备 ", 
"snippet" : "您可以像其他“POU”对象一样将 EVC（交换变量连接）添加到应用程序：使用命令和对话框 添加对象 并选择 EVC . EVC 对象的名称不能更改。一个应用程序中只能有 1 个 EVC 对象。...", 
"body" : "您可以像其他“POU”对象一样将 EVC（交换变量连接）添加到应用程序：使用命令和对话框 添加对象 并选择 EVC . EVC 对象的名称不能更改。一个应用程序中只能有 1 个 EVC 对象。 " }, 
{ "title" : "动态内存管理 ", 
"url" : "sil2_compound_editor_device_variant.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 复合安全PLC \/ 动态内存管理 ", 
"snippet" : "存储的动态管理在选项卡中完成 设备变体 复合安全控制器。它用于提供不同的设备变体，这些变体的安全和不安全代码的大小不同。可以在选项卡中选择这些设备变体之一并将其传输到项目或加载到控制器上。 标签 设备变体 PLC 配置 设备变体 配置文件中定义的设备变体列表 如果您选择设备变体，则会显示相应的图像和描述，前提是图像和描述已存储在文件中。 采纳项目 在设备树中，从属控件采用并显示设备变体。 如果配置未更改，则该按钮显示为灰色。 控制住 为所选配置存储的文件被加载到控制器上。 如果未存储文件或配置未更改，则该按钮显示为灰色。...", 
"body" : "存储的动态管理在选项卡中完成 设备变体 复合安全控制器。它用于提供不同的设备变体，这些变体的安全和不安全代码的大小不同。可以在选项卡中选择这些设备变体之一并将其传输到项目或加载到控制器上。 标签 设备变体 PLC 配置 设备变体 配置文件中定义的设备变体列表 如果您选择设备变体，则会显示相应的图像和描述，前提是图像和描述已存储在文件中。 采纳项目 在设备树中，从属控件采用并显示设备变体。 如果配置未更改，则该按钮显示为灰色。 控制住 为所选配置存储的文件被加载到控制器上。 如果未存储文件或配置未更改，则该按钮显示为灰色。 " }, 
{ "title" : "非安全相关计划（NonSafe PRGs） ", 
"url" : "sil2_nonsafe_prg.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 非安全相关计划（NonSafe PRGs） ", 
"snippet" : "从编译器和运行时版本 V3.5.4.0 开始，安全 SIL2 应用程序中的 PRG 也可能包含与安全无关的代码。默认情况下，所有 PRG 都包含与安全相关的代码。这由黄色图标表示 在 POU 的默认图标旁边。 与安全相关的 PRG 的应用 如果满足上述编译器版本和运行时系统版本的要求，则有 特性 - PRG 的对话框它自己的选项卡 SIL2 属性 带有复选框 安全相关 PRG , 与财产 包含与安全相关的代码 可以停用 PRG 的。通过上下文菜单命令打开 PRG 的属性对话框 特性 . 如果 PRG 不包含与安全相关的代码，也会用灰色符号直观地表示出来 标记在 POU 的标准图标旁边。 具有安...", 
"body" : "从编译器和运行时版本 V3.5.4.0 开始，安全 SIL2 应用程序中的 PRG 也可能包含与安全无关的代码。默认情况下，所有 PRG 都包含与安全相关的代码。这由黄色图标表示 在 POU 的默认图标旁边。 与安全相关的 PRG 的应用 如果满足上述编译器版本和运行时系统版本的要求，则有 特性 - PRG 的对话框它自己的选项卡 SIL2 属性 带有复选框 安全相关 PRG , 与财产 包含与安全相关的代码 可以停用 PRG 的。通过上下文菜单命令打开 PRG 的属性对话框 特性 . 如果 PRG 不包含与安全相关的代码，也会用灰色符号直观地表示出来 标记在 POU 的标准图标旁边。 具有安全相关 PRG 和非安全相关 PRG 的设备树 " }, 
{ "title" : "使用非安全相关程序的注意事项 ", 
"url" : "sil2_nonsafe_prg.html#UUID-e2494c7a-3141-29c3-bb90-db72dc6ae08a_id_b48c277ec88830c0a8640e003c64a6_id_90dec05affc84095c0a8640e01387d16", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 非安全相关计划（NonSafe PRGs） \/ 使用非安全相关程序的注意事项 ", 
"snippet" : "以下注释描述了非安全相关程序的推荐使用。此外，必须遵守控制器制造商的手册。 一般的 非安全相关 PRG 主要用于在一般安全关键应用程序中执行单个非安全相关部分功能。 这些非安全相关的 PRG 不得对安全相关的部分产生任何影响。安全数据不受干扰是通过内存保护实现的。 POU 不得插入非安全相关 PRG（例如方法、操作）下方。 非安全相关的 PRG 不得在 POU 池中声明。共享 POU 应在库中进行管理。...", 
"body" : "以下注释描述了非安全相关程序的推荐使用。此外，必须遵守控制器制造商的手册。 一般的 非安全相关 PRG 主要用于在一般安全关键应用程序中执行单个非安全相关部分功能。 这些非安全相关的 PRG 不得对安全相关的部分产生任何影响。安全数据不受干扰是通过内存保护实现的。 POU 不得插入非安全相关 PRG（例如方法、操作）下方。 非安全相关的 PRG 不得在 POU 池中声明。共享 POU 应在库中进行管理。 " }, 
{ "title" : "数据访问和调用层次结构 ", 
"url" : "sil2_nonsafe_prg.html#UUID-e2494c7a-3141-29c3-bb90-db72dc6ae08a_id_b48c277ec88830c0a8640e003c64a6_id_7552df24ffe664f8c0a8640e00825549", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 非安全相关计划（NonSafe PRGs） \/ 数据访问和调用层次结构 ", 
"snippet" : "本地和全球数据 来自 POU 的本地数据的位置取决于类型： 功能 局部变量在栈中 FB实例 FB 的局部变量位于 FB 实例中。 对于全局数据，可以观察到以下 POU 类型： GVL（以及 EVL） 全局变量（标准数据类型、FB 实例、DUT） PRG 全局变量（标准数据类型、FB 实例、DUT） 下表显示了通常允许哪些数据访问： 上下文\\访问类型 安全相关数据 非安全相关数据 读 写 读 写 安全相关代码 好的 好的 好的 好的 非安全相关代码 好的 不允许 好的 好的 调用层次结构 使用与安全无关的 PRG（调用这些 POU 或从这些 POU 调用）受到特定限制，因为未经授权的访问可能导致...", 
"body" : "本地和全球数据 来自 POU 的本地数据的位置取决于类型： 功能 局部变量在栈中 FB实例 FB 的局部变量位于 FB 实例中。 对于全局数据，可以观察到以下 POU 类型： GVL（以及 EVL） 全局变量（标准数据类型、FB 实例、DUT） PRG 全局变量（标准数据类型、FB 实例、DUT） 下表显示了通常允许哪些数据访问： 上下文\\访问类型 安全相关数据 非安全相关数据 读 写 读 写 安全相关代码 好的 好的 好的 好的 非安全相关代码 好的 不允许 好的 好的 调用层次结构 使用与安全无关的 PRG（调用这些 POU 或从这些 POU 调用）受到特定限制，因为未经授权的访问可能导致 PLC 处于安全状态。 调用层次结构 呼叫\/呼叫 安全 PRG 功能（安全可用） 安全 FB 实例 非安全 PRG 功能（非安全可用） 非安全 FB 实例 安全 PRG 好的 好的 好的 不好 不好 不好 功能（安全可用） 好的 好的 好的 不好 不好 不好 安全 FB 实例 好的 好的 好的 不好 不好 不好 非安全 PRG 不好 不好 不好 好的 好的 好的 功能（非安全可用） 不好 不好 不好 好的 好的 好的 非安全 FB 实例 不好 不好 不好 好的 好的 好的 FB 实例通常被认为与安全相关。例外情况如下： FB 在非安全 PRG 中实例化。 FB 在 EVL 中实例化。 FB 实例通过“属性位置”移动。 FB 声明位于非安全相关库中。 示例 1 标准库 (Safe) 中的 TON 在 PRG (Safe) 中实例化。 结果：TON 实例位于安全内存中。 示例 2 标准库 (Safe) 中的 TON 在 NonSafe PRG 中实例化。 结果：TON 实例位于非安全内存中。 示例 3 Util 库 (NonSafe) 中的 PD 在 PRG (Safe) 中实例化。 结果：PD 实例位于非安全内存中。 不允许在安全 PRG 中使用来自非安全库的 POU。 示例 4 Util 库 (NonSafe) 中的 PD 在 NonSafe PRG 中实例化。 结果：PD 实例位于非安全内存中。 " }, 
{ "title" : "参考：属性编译指示 ", 
"url" : "_sil2_reference_pragmas.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 参考：属性编译指示 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "属性：location ", 
"url" : "_sil2_pragma_attribute_location.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 参考：属性编译指示 \/ 属性：location ", 
"snippet" : "location 强制将 POU (PRG) 存储在非安全存储区域中 句法 ： {attribute 'location':=16#800} 插入位置：程序声明部分上方第一行（PRG） 当 PRG POU 被标记为时，pragma 属性会自动插入 nonSafe 。这导致PRG的所有数据都被存储在“非安全存储区”中。 POU 不再受到不受干扰的保护。 非安全区域在运行时系统中定义为 SysMemItf 与接口 DA_NONSAFETY 。 #define DA_NONSAFETY 0x0800 有关更多信息，请参阅： 非安全相关计划（NonSafe PRGs）...", 
"body" : "location 强制将 POU (PRG) 存储在非安全存储区域中 句法 ： {attribute 'location':=16#800} 插入位置：程序声明部分上方第一行（PRG） 当 PRG POU 被标记为时，pragma 属性会自动插入 nonSafe 。这导致PRG的所有数据都被存储在“非安全存储区”中。 POU 不再受到不受干扰的保护。 非安全区域在运行时系统中定义为 SysMemItf 与接口 DA_NONSAFETY 。 #define DA_NONSAFETY 0x0800\n 有关更多信息，请参阅： 非安全相关计划（NonSafe PRGs）" }, 
{ "title" : "属性：sil2context ", 
"url" : "_sil2_pragma_attribute_sil2context.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 参考：属性编译指示 \/ 属性：sil2context ", 
"snippet" : "sil2context 该属性是必需的 不安全 IO 驱动程序库能够在安全上下文中执行 IO 驱动程序实例的初始化。 句法 ： {attribute 'sil2context':='safe'} 插入位置：库 POU 声明部分上方的第一行 分类与 safe 导致标有此属性的 POU 部分在安全上下文中执行。 这是必需的 CODESYS Safety SIL2 系统，例如，用于某些非安全IO驱动程序库的初始化。 POU 的标记部分在安全上下文中执行，因此可以对安全 IO 配置进行写访问。 但是，使用此属性调用并在 CODESYS Safety SIL2 系统必须以安全为导向的方式开发，并且还必须...", 
"body" : "sil2context 该属性是必需的 不安全 IO 驱动程序库能够在安全上下文中执行 IO 驱动程序实例的初始化。 句法 ： {attribute 'sil2context':='safe'} 插入位置：库 POU 声明部分上方的第一行 分类与 safe 导致标有此属性的 POU 部分在安全上下文中执行。 这是必需的 CODESYS Safety SIL2 系统，例如，用于某些非安全IO驱动程序库的初始化。 POU 的标记部分在安全上下文中执行，因此可以对安全 IO 配置进行写访问。 但是，使用此属性调用并在 CODESYS Safety SIL2 系统必须以安全为导向的方式开发，并且还必须满足以下标准： 根据 McCabe 确定圈复杂度。确定的值必须小于 5。 调用的函数少于 3 个。这些函数位于“SIL2”属性设置为 TRUE 的库中，或者满足与测试函数相同的标准。 验证是否符合[H2]扩展级别用户手册的规则 " }, 
{ "title" : "库：PLCopen Safety FBs ", 
"url" : "sil3_safetyplcopen_library_overview.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs ", 
"snippet" : "此处描的标识述的库: PLCopen Safety FBs, 3.5.18.0 依据：PLCopen TC5：“安全软件，第 1 部分：概念和功能块”，1.0 版，2006 年 1 月 PLCopen 功能块（以 SF_ 为前缀）由 PLCopen 组织连同其成员和处理安全相关方面的外部组织一起定义。这些功能块经过认证，因此可以减少开发、验证和接受安全应用程序的时间和成本。类似于逻辑布线，块可以通过逻辑操作相互链接。因此，可以快速创建安全应用程序的重要组件，而无需太多编程工作。 有关详细描述各个 PLCopen FB 的信息，请参阅认证时最新的 PLCopen“技术委员会 5 – 安全软件”规...", 
"body" : "此处描的标识述的库: PLCopen Safety FBs, 3.5.18.0 依据：PLCopen TC5：“安全软件，第 1 部分：概念和功能块”，1.0 版，2006 年 1 月 PLCopen 功能块（以 SF_ 为前缀）由 PLCopen 组织连同其成员和处理安全相关方面的外部组织一起定义。这些功能块经过认证，因此可以减少开发、验证和接受安全应用程序的时间和成本。类似于逻辑布线，块可以通过逻辑操作相互链接。因此，可以快速创建安全应用程序的重要组件，而无需太多编程工作。 有关详细描述各个 PLCopen FB 的信息，请参阅认证时最新的 PLCopen“技术委员会 5 – 安全软件”规范版本。 使用 PLCopen 功能块时，用户必须确保在应用程序中每个循环至少调用一次功能块。 SafetyPLCopen 库的功能块 SF_AntivalentSF_EquivalentSF_EmergencyStopSF_ResetButtonSF_EDM (External Device Monitoring)" }, 
{ "title" : "安全相关功能块的一般规则 ", 
"url" : "plcopen_fbspecrules.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 ", 
"snippet" : "这些编程规则对应于 PLCopen 的“安全相关功能块的通用规则”。它们适用于符合 PLCopen 的功能块。...", 
"body" : "这些编程规则对应于 PLCopen 的“安全相关功能块的通用规则”。它们适用于符合 PLCopen 的功能块。 " }, 
{ "title" : "功能块特定规则 ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_d64187671211d9a4c0a8640e0070923d_id_8b9479d9124693e5c0a8640e009f28ee", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 功能块特定规则 ", 
"snippet" : "使用 PLCopen 功能块时，用户必须确保在应用程序中每个循环至少调用一次功能块。 默认信号 所有与安全相关的布尔 I\/O 信号都具有默认安全值 FALSE . 信号电平 的价值 SAFEBOOL 仅适用于以下情况： 0 ：对应于系统输出定义的安全性 1 ：表示系统的安全方面运行正常，例如，可以正常运行 这反映了 IEC 61131 环境的功能，例如默认值的规则以及所有输出都设置为 0 万一出现错误。 缺少 I\/O 参数 允许缺少参数。应用默认值。这些默认值在任何情况下都不会导致不安全状态。默认值，包括它们的属性 ( Variable 订单 Constant )，在相关的 FB 规范中指定。...", 
"body" : "使用 PLCopen 功能块时，用户必须确保在应用程序中每个循环至少调用一次功能块。 默认信号 所有与安全相关的布尔 I\/O 信号都具有默认安全值 FALSE . 信号电平 的价值 SAFEBOOL 仅适用于以下情况： 0 ：对应于系统输出定义的安全性 1 ：表示系统的安全方面运行正常，例如，可以正常运行 这反映了 IEC 61131 环境的功能，例如默认值的规则以及所有输出都设置为 0 万一出现错误。 缺少 I\/O 参数 允许缺少参数。应用默认值。这些默认值在任何情况下都不会导致不安全状态。默认值，包括它们的属性 ( Variable 订单 Constant )，在相关的 FB 规范中指定。 启动行为 最初，输出设置为默认值。第一次调用功能块后，输出有效。有一致的启动行为（冷启动）。 时序图 时序图（如 FB 所示）仅供说明之用。它们并不代表确切的时序行为。确切的时序行为取决于实现。 错误处理和诊断 所有与安全相关的功能块都有两个与错误相关的输出： Error 和 DiagCode .这些是为用户应用程序级别的诊断目的而提供的，而不是用于系统或硬件级别的诊断。 安全相关环境的规则是安全相关功能的切换具有最高优先级。此外，无论是在功能程序中还是在操作界面中，后续切换都必须有足够的时间进行诊断。 " }, 
{ "title" : "通用输入参数 ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_section-idm43298843133984", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 通用输入参数 ", 
"snippet" : "姓名 数据类型 描述 Activate BOOL 用于激活 FB 的变量或常量 初始值为 FALSE 该参数可以连接到变量，该变量表示相关安全设备的状态（激活或非激活）。这可确保在禁用设备时不会生成不相关的诊断信息。 FALSE ：所有输出变量都设置为初始值。 如果没有连接设备，则静态 TRUE 必须分配信号。 S_ <安全相关输入名称> SAFExxxx 每一个 SAFExxxx 类型输入名称以 S_ . 只能分配变量。 S_StartReset SAFEBOOL 变量或常数 FALSE （初始值）：自动启动禁用；通过输入手动启动 Reset TRUE : 安全控制器启动时自动复位（热或冷）...", 
"body" : "姓名 数据类型 描述 Activate BOOL 用于激活 FB 的变量或常量 初始值为 FALSE 该参数可以连接到变量，该变量表示相关安全设备的状态（激活或非激活）。这可确保在禁用设备时不会生成不相关的诊断信息。 FALSE ：所有输出变量都设置为初始值。 如果没有连接设备，则静态 TRUE 必须分配信号。 S_ <安全相关输入名称> SAFExxxx 每一个 SAFExxxx 类型输入名称以 S_ . 只能分配变量。 S_StartReset SAFEBOOL 变量或常数 FALSE （初始值）：自动启动禁用；通过输入手动启动 Reset TRUE : 安全控制器启动时自动复位（热或冷） 注意 安全说明 . S_AutoReset SAFEBOOL 变量或常数 FALSE （初始值）：自动重启关闭；通过输入手动启动 Reset 当紧急停止开关解锁时。 TRUE ：紧急停止开关解锁时自动重启。 注意 安全说明 . Reset BOOL 多变的。初始值为 FALSE 根据功能，此输入可用于不同目的。 状态机的重置，以及耦合错误和状态消息，如通过 DiagCode ，当错误原因已消除时。此复位行为被设计为错误复位。 由操作员手动复位重启联锁。此复位设计为功能复位。 其他 FB 特定的复位功能 此功能仅在信号变化时有效 FALSE 到 TRUE .一个静态的 TRUE 信号不会引起更多动作，但在某些功能块中可能会被检测为错误。 注意 安全须知 . 必须在每个功能块中描述适当的含义。 " }, 
{ "title" : "安全说明 S_StartReset ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_d64187671211d9a4c0a8640e0070923d_id_97a0f28f254a20b7c0a86597009a651e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 安全说明 S_StartReset ", 
"snippet" : "S_StartReset 仅当确保在安全控制器启动时不会发生危险时，才应激活该自动启动。因此，使用功能块的“自动启动”特性需要实施其他系统或应用措施。这必须确保不会发生意外（或意外）启动。 如果输入链接到一个变量（而不是 FALSE )，然后必须为其定义额外的验证措施。...", 
"body" : "S_StartReset 仅当确保在安全控制器启动时不会发生危险时，才应激活该自动启动。因此，使用功能块的“自动启动”特性需要实施其他系统或应用措施。这必须确保不会发生意外（或意外）启动。 如果输入链接到一个变量（而不是 FALSE )，然后必须为其定义额外的验证措施。 " }, 
{ "title" : "安全说明 S_AutoReset ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_d64187671211d9a4c0a8640e0070923d_id_b69d0699254a2083c0a8659700dc7b4e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 安全说明 S_AutoReset ", 
"snippet" : "只有当通过释放紧急停止按钮确保机器不会重新启动时，才应激活自动重新启动。因此，使用功能块的“自动重启”特性需要实施其他系统或应用措施。这必须确保不会发生机器的意外（或意外）重启。 如果输入链接到一个变量（而不是 FALSE )，然后必须为其定义额外的验证措施。...", 
"body" : "只有当通过释放紧急停止按钮确保机器不会重新启动时，才应激活自动重新启动。因此，使用功能块的“自动重启”特性需要实施其他系统或应用措施。这必须确保不会发生机器的意外（或意外）重启。 如果输入链接到一个变量（而不是 FALSE )，然后必须为其定义额外的验证措施。 " }, 
{ "title" : "安全须知 Reset ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_d64187671211d9a4c0a8640e0070923d_id_b595e1d2ea0bb966c0a8640e00c3b47a", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 安全须知 Reset ", 
"snippet" : "一种 SAFEBOOL 必须连接而不是 BOOL 根据安全要求。另请参阅：功能块： SF_ResetButton....", 
"body" : "一种 SAFEBOOL 必须连接而不是 BOOL 根据安全要求。另请参阅：功能块： SF_ResetButton. " }, 
{ "title" : "一般输出参数 ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_section-idm43298843605226", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 一般输出参数 ", 
"snippet" : "姓名 数据类型 描述 Ready BOOL TRUE ：表示功能块已激活且输出结果有效（与安全继电器的“POWER”LED 相同）。 FALSE ：功能块未激活，程序未执行。在调试模式或激活\/停用附加功能块时很有用。也可用于功能程序中的进一步处理。 S_ <安全相关输出名称> SAFExxxx 每一个 SAFExxxx 数据类型输出名称以 S_ . SafetyDemand BOOL 指示 FB 处于活动状态并且需要主要安全功能（例如与安全功能相关）的输出。不考虑其他与安全相关的输入参数（例如 SafetyActive 和 EDM ）。安全回路未闭合，相关安全输出需要安全状态。没有错误。 TR...", 
"body" : "姓名 数据类型 描述 Ready BOOL TRUE ：表示功能块已激活且输出结果有效（与安全继电器的“POWER”LED 相同）。 FALSE ：功能块未激活，程序未执行。在调试模式或激活\/停用附加功能块时很有用。也可用于功能程序中的进一步处理。 S_ <安全相关输出名称> SAFExxxx 每一个 SAFExxxx 数据类型输出名称以 S_ . SafetyDemand BOOL 指示 FB 处于活动状态并且需要主要安全功能（例如与安全功能相关）的输出。不考虑其他与安全相关的输入参数（例如 SafetyActive 和 EDM ）。安全回路未闭合，相关安全输出需要安全状态。没有错误。 TRUE : 安全需求 FALSE : 没有安全要求 ResetRequest BOOL 可用于指示操作员按下复位功能以继续的输出 TRUE ：请求操作员重置 FALSE ：未请求操作员重置 Error BOOL 错误标志（与安全继电器的“K1\/K2”LED 相同） TRUE : TRUE 时，表示发生了错误，FB 处于错误状态。相关的错误状态反映在 DiagCode 输出。 FALSE : 表示没有错误，FB 处于其他状态。这再次反映在 DiagCode . 在调试模式以及功能程序中的进一步处理中很有用。 DiagCode WORD 诊断寄存器 FB的所有状态（ Active , Not Active ， 和 Error ) 由该寄存器表示。此信息以十六进制格式编码，以便表示超过 16 个代码。同时只表示一个一致的代码。如果出现多个错误，则 DiagCode 输出指示第一个检测到的错误。 在调试模式以及功能程序中的进一步处理中很有用。 " }, 
{ "title" : "诊断代码 ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_section-idm43298843812030", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 诊断代码 ", 
"snippet" : "透明且独特的诊断概念构成了所有功能块的基础。因此，可以确保无论供应商的实施如何，用户都可以使用统一的诊断信息，其形式为 DiagCode .如果不存在错误，则指示功能块（状态机）的内部状态。通过二进制输出（ Error ）。有关内部或外部功能块错误的详细信息可以通过以下方式获得 DiagCode .功能块必须通过不同的复位输入进行复位。 通用诊断代码 DiagCode 描述 0000_0000_0000_0000 斌 0000 十六进制 FB 未激活。此代码表示空闲状态。对于一个通用示例，I\/O 设置可以是： Activate = FALSE S_In = FALSE 或者 TRUE Read...", 
"body" : "透明且独特的诊断概念构成了所有功能块的基础。因此，可以确保无论供应商的实施如何，用户都可以使用统一的诊断信息，其形式为 DiagCode .如果不存在错误，则指示功能块（状态机）的内部状态。通过二进制输出（ Error ）。有关内部或外部功能块错误的详细信息可以通过以下方式获得 DiagCode .功能块必须通过不同的复位输入进行复位。 通用诊断代码 DiagCode 描述 0000_0000_0000_0000 斌 0000 十六进制 FB 未激活。此代码表示空闲状态。对于一个通用示例，I\/O 设置可以是： Activate = FALSE S_In = FALSE 或者 TRUE Ready = FALSE Error = FALSE S_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE 1000_0000_0000_0000 斌 8000 十六进制 FB 在没有错误或任何其他将安全输出设置为 FALSE .这是默认的操作状态，其中 S_Out 安全输出 = TRUE 在正常操作中。对于一个通用示例，I\/O 设置可以是： Activate = TRUE S_In = TRUE Ready = TRUE Error = FALSE S_Out = TRUE SafetyDemand = FALSE ResetRequest = FALSE 1000_0100_0000_0001 斌 8401 十六进制 FB 已检测到激活，现在 FB 已激活，但 S_Out 安全输出设置为 FALSE .此代码表示操作模式的 Init 状态。对于一个通用示例，I\/O 设置可以是： Activate = TRUE S_In = TRUE Ready = TRUE Error = FALSE S_Out = FALSE SafetyDemand = FALSE ResetRequest = TRUE 1000_1000_0000_0010 斌 8802 十六进制 激活的 FB 检测到安全需求，例如 S_In = FALSE .安全输出被禁用（ S_Out = FALSE ）。对于一个通用示例，I\/O 设置可以是： Activate = TRUE S_IN = FALSE Ready = TRUE Error = FALSE S_Out = FALSE SafetyDemand = TRUE ResetRequest = FALSE 1000_0100_0000_0011 斌 8403 十六进制 已激活 FB 的安全输出已被安全要求禁用。安全需求现在被撤回，但安全输出仍然存在 FALSE 直到检测到复位条件。这是一种运行状态，其中 S_Out 安全输出 = FALSE .对于一个通用示例，I\/O 设置可以是： Activate = TRUE S_In = FALSE => TRUE （继续静态 TRUE ) Ready = TRUE Error = FALSE S_Out = FALSE SafetyDemand = TRUE ==> FALSE ResetRequest = FALSE ==> TRUE 系统或设备特定代码 DiagCode 描述 0xxx_xxxx_xxxx_xxxx 斌 X = 系统或设备特定消息。此信息包含系统或设备的诊断信息，并直接映射到 DiagCode 输出。 笔记： 0000 十六进制 被预定了。 " }, 
{ "title" : "通用状态图 ", 
"url" : "plcopen_fbspecrules.html#UUID-5f6ae436-cedd-f768-bd19-89fee51150c6_d64187671211d9a4c0a8640e0070923d_id_ad66950e0f6a49ccc0a8640e005c60c9", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ 安全相关功能块的一般规则 \/ 通用状态图 ", 
"snippet" : "安全 FB 的通用状态图 通用状态图说明： 显示状态和转换的一般概述。一些转换在这里没有命名。这意味着它们是特定于 FB 的，并使用相关 FB 进行描述。 该图显示了三个区域： 在顶部，FB 未激活。它处于安全状态（安全输出为 FALSE ）。 中间，FB是活跃的。它处于安全状态（安全输出是 FALSE ）。 在底部，FB处于正常状态。安全输出是 TRUE . 状态图中的第一条水平线显示从非活动 FB 到活动 FB 的转换。 第二条水平线显示了 FB 从非安全状态到安全状态的转换。 可能的并行转换的优先级由数字表示（ 0 = 最高优先级）。 状态气泡包含状态名称和十六进制 DiagCode。 ...", 
"body" : "安全 FB 的通用状态图 通用状态图说明： 显示状态和转换的一般概述。一些转换在这里没有命名。这意味着它们是特定于 FB 的，并使用相关 FB 进行描述。 该图显示了三个区域： 在顶部，FB 未激活。它处于安全状态（安全输出为 FALSE ）。 中间，FB是活跃的。它处于安全状态（安全输出是 FALSE ）。 在底部，FB处于正常状态。安全输出是 TRUE . 状态图中的第一条水平线显示从非活动 FB 到活动 FB 的转换。 第二条水平线显示了 FB 从非安全状态到安全状态的转换。 可能的并行转换的优先级由数字表示（ 0 = 最高优先级）。 状态气泡包含状态名称和十六进制 DiagCode。 条件 OR , AND ， 和 XOR 用作逻辑运算符和 NOT 用作否定。 在 FB 描述中，起始状态为 Idle ，通过转换到操作状态 Init 状态。 从任何状态的转变由于 Activate = FALSE 直接更改为 Idle 状态 （ 0 = 保留的最高优先级 Activate = FALSE ）。为了更清楚起见，这些转换并未在每个状态图中显示。但它们作为每个状态图的脚注被提及。 为清楚起见，状态图中未描述输出设置。包含 FB 输出状态的显式真值表是每个 FB 规范的一部分。此外，还描述了 FB 特定的错误和状态代码。 过渡的注意事项 8xx0 到 0000 ：某些应用程序（如印刷机）需要在没有任何风险的情况下完成其周期。在这种情况下，可以延迟过渡。 FB 特定的错误代码 DiagCode 州名 状态描述和输出设置 Cxxx Error Ready = TRUE S_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE FB 特定状态码（无错误） DiagCode 州名 状态描述和输出设置 0000 Idle Ready = FALSE S_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = FALSE 8xxx 初始化状态和操作模式的所有状态，其中 S_Out = FALSE Ready = TRUE S_Out = FALSE SafetyDemand = 取决于 ResetRequest = 取决于 Error = FALSE 8000 操作模式的所有状态，其中 S_Out = TRUE Ready = TRUE S_Out = TRUE ResetDemand = FALSE ResetRequest = FALSE Error = FALSE " }, 
{ "title" : "SF_Equivalent ", 
"url" : "sil3_plcopen_fb_equivalent.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "适用的安全标准 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_158483660ee14c8cc0a8640e013306da", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 适用的安全标准 ", 
"snippet" : "SF_Equivalent 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。...", 
"body" : "SF_Equivalent 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。 " }, 
{ "title" : "接口说明 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_aa34bc1d0f2b767bc0a8640e001d251c", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 接口说明 ", 
"snippet" : "该功能块将两个等效的 SAFEBOOL 输入（两者 NO 或者 NC ) 为一 SAFEBOOL 输出具有差异时间监控。该 FB 不应该单独使用，因为它没有重启联锁。需要将输出连接到其他安全相关功能。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_ChannelA SAFEBOOL FALSE 多变的 输入 A 用于逻辑连接 FALSE ： 接触 A 打开 TRUE ： 接触 A 关闭 S_ChannelB SAFEBOOL FALSE 多变的 输入 B 用于逻辑连接 FALSE ： 接触 B 打开 TRUE ： 接触 ...", 
"body" : "该功能块将两个等效的 SAFEBOOL 输入（两者 NO 或者 NC ) 为一 SAFEBOOL 输出具有差异时间监控。该 FB 不应该单独使用，因为它没有重启联锁。需要将输出连接到其他安全相关功能。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_ChannelA SAFEBOOL FALSE 多变的 输入 A 用于逻辑连接 FALSE ： 接触 A 打开 TRUE ： 接触 A 关闭 S_ChannelB SAFEBOOL FALSE 多变的 输入 B 用于逻辑连接 FALSE ： 接触 B 打开 TRUE ： 接触 B 关闭 DiscrepancyTime TIME T#0ms 持续的 两个输入的差异状态的最大监控时间 必须遵守警告说明“DiscrepancyTime”。 DiscrepancyTime 适用于扩展级别的开发人员： DiscrepancyTime 输入必须用一个常数值激活。因此，不得更改调用的值。 VAR_OUTPUT 姓名 数据类型 初始值 说明，参数值 Ready BOOL FALSE 看 一般输出参数 S_EquivalentOut SAFEBOOL FALSE 安全相关输出 FALSE : 一个输入信号的最小值是 FALSE 或监控时间之外的状态变化 TRUE ：两个输入信号都“激活”并且状态在监控时间内发生变化。 SafetyDemand BOOL FALSE 看 一般输出参数 Error BOOL FALSE 看 一般输出参数 DiagCode WORD 16#0000 看 诊断代码 对于某些（较低）级别的安全要求，可以允许使用 BOOL 作为输入和 SAFEBOOL 作为输出。但是，这必须通过应用程序的 FMEA 进行评估。在图书馆里，应该区分 SAFEBOOL 和 BOOL 版本。 功能块： SF_Equivalent " }, 
{ "title" : "功能说明 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_dc445d623efe40c4c0a8640e00e4663f", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 功能说明 ", 
"snippet" : "该功能块将两个等效的 SAFEBOOL 输入（两者 NO 或者 NC ) 为一 SAFEBOOL 输出具有差异时间监控。两个渠道相互依存。功能块输出显示两个通道的评估结果。 Wenn sich das Signal eines Kanals 从 TRUE 到 FALSE ，输出立即切换到 FALSE 出于安全原因。 差异时间监控：差异时间是两个输入可能具有不同状态而功能块未检测到错误的最长时间。当输入状态发生变化时，差异时间监控开始。一旦差异时间过去，当两个输入具有不同的状态时，功能块会检测到错误。 两个输入必须对称切换。这意味着对两个输入进行监视以从 TRUE 到 FALSE 以及从 FAL...", 
"body" : "该功能块将两个等效的 SAFEBOOL 输入（两者 NO 或者 NC ) 为一 SAFEBOOL 输出具有差异时间监控。两个渠道相互依存。功能块输出显示两个通道的评估结果。 Wenn sich das Signal eines Kanals 从 TRUE 到 FALSE ，输出立即切换到 FALSE 出于安全原因。 差异时间监控：差异时间是两个输入可能具有不同状态而功能块未检测到错误的最长时间。当输入状态发生变化时，差异时间监控开始。一旦差异时间过去，当两个输入具有不同的状态时，功能块会检测到错误。 两个输入必须对称切换。这意味着对两个输入进行监视以从 TRUE 到 FALSE 以及从 FALSE 到 TRUE . 输入输出逻辑表 输入 输出 Activate S_ChannelA S_ChannelB DiscrepancyTime Ready S_EquivalentOut SafetyDemand Error DiagCode FALSE FALSE TRUE 没有开始 FALSE FALSE FALSE FALSE 0000 TRUE FALSE FALSE 没有开始 TRUE FALSE TRUE FALSE 8801 TRUE TRUE FALSE 开始 TRUE FALSE TRUE FALSE 8802 TRUE TRUE FALSE -> TRUE 开始 TRUE TRUE FALSE FALSE 8000 TRUE TRUE TRUE 没有开始 TRUE TRUE FALSE FALSE 8000 TRUE TRUE TRUE -> FALSE 开始 TRUE FALSE TRUE FALSE 8806 TRUE TRUE -> FALSE FALSE 开始 TRUE FALSE TRUE FALSE 8801 TRUE FALSE FALSE 没有开始 TRUE FALSE TRUE FALSE 8801 TRUE FALSE FALSE -> TRUE 开始 TRUE FALSE TRUE FALSE 8804 TRUE FALSE -> TRUE TRUE 开始 TRUE TRUE FALSE FALSE 8000 在逻辑表中，箭头 -> 代表转换。 TRUE -> FALSE 表示变量 jas 的值从 TRUE 到 FALSE . " }, 
{ "title" : "状态图 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_e677b29e0f2b767cc0a8640e0173bc14", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 状态图 ", 
"snippet" : "状态图： SF_Equivalent 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。...", 
"body" : "状态图： SF_Equivalent 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。 " }, 
{ "title" : "典型时序图 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_section-idm4563031952337632993177070072", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 典型时序图 ", 
"snippet" : "时序图1： SF_Equivalent 时序图2： SF_Equivalent...", 
"body" : "时序图1： SF_Equivalent 时序图2： SF_Equivalent " }, 
{ "title" : "错误检测 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_095bbe2e0f6a49cbc0a8640e01c50f13", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 错误检测 ", 
"snippet" : "功能块监控通道之间的差异时间 S_ChannelA 和渠道 S_ChannelB , 当切换到 TRUE 以及切换到 FALSE ....", 
"body" : "功能块监控通道之间的差异时间 S_ChannelA 和渠道 S_ChannelB , 当切换到 TRUE 以及切换到 FALSE . " }, 
{ "title" : "错误行为 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_83000ad10f6a49cbc0a8640e019e5f90", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ 错误行为 ", 
"snippet" : "输出 S_EquivalentOut 设定为 FALSE . Error 设定为 TRUE . DiagCode 表示错误状态。没有复位定义为与错误复位相结合的输入。只要一组输入值正确 S_EquivalentOut 存在， Error 是 FALSE 再次。...", 
"body" : "输出 S_EquivalentOut 设定为 FALSE . Error 设定为 TRUE . DiagCode 表示错误状态。没有复位定义为与错误复位相结合的输入。只要一组输入值正确 S_EquivalentOut 存在， Error 是 FALSE 再次。 " }, 
{ "title" : "FB 特定错误和状态代码 ", 
"url" : "sil3_plcopen_fb_equivalent.html#UUID-1507c7d3-c782-21e2-27a7-512f2f57374c_de69ef0e9e6473c0a8640e0120d624_id_ad66950e0f6a49ccc0a8640e005c60c9", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Equivalent \/ FB 特定错误和状态代码 ", 
"snippet" : "FB 特定的错误代码 DiagCode 州名 状态说明及输出设定 16#C010 Error 1 状态中经过的时间差异 16#8802 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C020 Error 2 状态中经过的时间差异 16#8804 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C030 Error 3 状态中经过的时间差异 16#8806 Ready = TRUE S_Equiv...", 
"body" : "FB 特定的错误代码 DiagCode 州名 状态说明及输出设定 16#C010 Error 1 状态中经过的时间差异 16#8802 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C020 Error 2 状态中经过的时间差异 16#8804 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C030 Error 3 状态中经过的时间差异 16#8806 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = FALSE Error = TRUE FB 特定状态代码 DiagCode 州名 状态说明及输出设定 16#0000 Idle 功能块未激活（初始状态）。 Ready = FALSE S_EquivalentOut =FALSE SafetyDemand = FALSE Error = FALSE 16#8801 Init FB 已检测到激活，现在 FB 已激活。 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = TRUE Error = FALSE 16#8000 Safety Output Enabled 输入切换到 TRUE 在等效模式下。 Ready = TRUE S_EquivalentOut = TRUE SafetyDemand = FALSE Error = FALSE 16#8802 Wait for Channel B S_ChannelA 已切换到 TRUE – 等待 S_ChannelB ;差异计时器启动。 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = TRUE Error = FALSE 16#8804 Wait for Channel A S_ChannelB 已切换到 TRUE – 等待 S_ChannelA ;差异计时器启动。 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = TRUE Error = FALSE 16#8806 From Active Wait 已切换到一个频道 FALSE ;等待切换到另一个频道 FALSE , 差异计时器启动。 Ready = TRUE S_EquivalentOut = FALSE SafetyDemand = TRUE Error = FALSE " }, 
{ "title" : "SF_Antivalent ", 
"url" : "sil3_plcopen_fb_antivalent.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "适用的安全标准 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_50394b5514848640c0a8640e01132c0e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 适用的安全标准 ", 
"snippet" : "SF_Antivalent 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。...", 
"body" : "SF_Antivalent 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。 " }, 
{ "title" : "接口说明 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_d99d631214848644c0a8640e01486937", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 接口说明 ", 
"snippet" : "该功能块将两个反价 SAFEBOOL 输入（ NO\/NC 对）到一个 SAFEBOOL 输出具有差异时间监控。该 FB 不应该单独使用，因为它没有重启联锁。需要将输出连接到其他安全相关功能。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_ChannelNC SAFEBOOL FALSE 多变的 NC 代表 Normally Closed . NC 连接输入 FALSE ：常闭触点打开 TRUE ：常闭触点闭合 S_ChannelNO SAFEBOOL TRUE 多变的 NO 代表常开 NO 连接输入 FALSE ：常开触...", 
"body" : "该功能块将两个反价 SAFEBOOL 输入（ NO\/NC 对）到一个 SAFEBOOL 输出具有差异时间监控。该 FB 不应该单独使用，因为它没有重启联锁。需要将输出连接到其他安全相关功能。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_ChannelNC SAFEBOOL FALSE 多变的 NC 代表 Normally Closed . NC 连接输入 FALSE ：常闭触点打开 TRUE ：常闭触点闭合 S_ChannelNO SAFEBOOL TRUE 多变的 NO 代表常开 NO 连接输入 FALSE ：常开触点 TRUE ：常开触点闭合 DiscrepancyTime TIME T#0ms 持续的 两个输入的差异状态的最大监控时间 必须遵守警告说明“DiscrepancyTime”。 DiscrepancyTime 适用于扩展级别的开发人员： DiscrepancyTime 输入必须用一个常数值激活。因此，不得更改调用的值。 VAR_OUTPUT 姓名 数据类型 初始值 说明，参数值 Ready BOOL FALSE 看 一般输出参数 S_AntivalentOut SAFEBOOL FALSE 安全相关输出 FALSE ：至少有一个输入信号“未激活”或监控时间之外的状态变化 TRUE ：两个输入信号都“激活”并且状态在监控时间内发生变化。 SafetyDemand BOOL FALSE 看 一般输出参数 Error BOOL FALSE 看 一般输出参数 DiagCode WORD 16#0000 看 诊断代码 “反相”是指正常工作时，两个输入同时处于相反的状态。这有时被称为“互补”或“非等效”。 对于某些（较低）级别的安全要求，可以允许使用 BOOL 作为输入和 SAFEBOOL 作为输出。但是，这必须通过应用程序的 FMEA 进行评估。在图书馆里，应该区分 SAFEBOOL 和 BOOL 版本。 功能块： SF_Antivalent " }, 
{ "title" : "功能说明 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_2654bc8d3e8dfbc2c0a8640e006a4078", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 功能说明 ", 
"snippet" : "该功能块将两个反价 SAFEBOOL 输入到一个 SAFEBOOL 输出具有差异时间监控。两个输入是相互依赖的。功能块输出显示两个通道的评估结果。 如果 S_AntivalentOut = TRUE 并且与安全相关的输入之一发生变化，然后输出立即切换到 FALSE . 差异时间监控：差异时间是两个输入可能具有相同状态而功能块未检测到错误的最长时间。当输入状态发生变化时，差异时间监控开始。一旦差异时间过去，当两个输入具有相同的值时，功能块将检测到错误。 两个输入必须对称切换。这意味着对两个输入进行监视以从 TRUE 到 FALSE 以及从 FALSE 到 TRUE . 输入输出逻辑表 输入 输出...", 
"body" : "该功能块将两个反价 SAFEBOOL 输入到一个 SAFEBOOL 输出具有差异时间监控。两个输入是相互依赖的。功能块输出显示两个通道的评估结果。 如果 S_AntivalentOut = TRUE 并且与安全相关的输入之一发生变化，然后输出立即切换到 FALSE . 差异时间监控：差异时间是两个输入可能具有相同状态而功能块未检测到错误的最长时间。当输入状态发生变化时，差异时间监控开始。一旦差异时间过去，当两个输入具有相同的值时，功能块将检测到错误。 两个输入必须对称切换。这意味着对两个输入进行监视以从 TRUE 到 FALSE 以及从 FALSE 到 TRUE . 输入输出逻辑表 输入 输出 Activate S_ChannelNC S_ChannelNO DiscrepancyTime Ready S_AntivalentOut SafetyDemand Error DiagCode FALSE FALSE TRUE 没有开始 FALSE FALSE FALSE FALSE 16#0000 TRUE FALSE TRUE 没有开始 TRUE FALSE TRUE FALSE 16#8801 TRUE FALSE -> TRUE TRUE 开始 TRUE FALSE TRUE FALSE 16#8802 TRUE TRUE TRUE -> FALSE 开始 TRUE TRUE FALSE FALSE 16#8000 TRUE TRUE FALSE 没有开始 TRUE TRUE FALSE FALSE 16#8000 TRUE TRUE FALSE -> TRUE 开始 TRUE FALSE TRUE FALSE 16#8806 TRUE TRUE -> FALSE TRUE 开始 TRUE FALSE TRUE FALSE 16#8801 TRUE FALSE TRUE 没有开始 TRUE FALSE TRUE FALSE 16#8801 TRUE FALSE TRUE -> FALSE 开始 TRUE FALSE TRUE FALSE 16#8804 TRUE FALSE -> TRUE FALSE 开始 TRUE TRUE FALSE FALSE 16#8000 TRUE TRUE -> FALSE FALSE 开始 TRUE FALSE TRUE FALSE 16#8806 TRUE FALSE FALSE -> TRUE 开始 TRUE FALSE TRUE FALSE 16#8801 在逻辑表中，箭头 -> 代表转换。 TRUE -> FALSE 表示变量 jas 的值从 TRUE 到 FALSE . " }, 
{ "title" : "状态图 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_272080c228454ed1c0a8640e01ff3877", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 状态图 ", 
"snippet" : "状态图： SF_Antivalent 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。...", 
"body" : "状态图： SF_Antivalent 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。 " }, 
{ "title" : "典型时序图 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_841e89c023bf8691c0a8640e01f2c59c", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 典型时序图 ", 
"snippet" : "时序图1： SF_Antivalent 时序图2： SF_Antivalent...", 
"body" : "时序图1： SF_Antivalent 时序图2： SF_Antivalent " }, 
{ "title" : "错误检测 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_6a49fd6423bf8691c0a8640e0169e649", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 错误检测 ", 
"snippet" : "功能块监控通道之间的差异时间 NO 和频道 NC ....", 
"body" : "功能块监控通道之间的差异时间 NO 和频道 NC . " }, 
{ "title" : "错误行为 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_5cb72b9223bf8692c0a8640e01b19833", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 错误行为 ", 
"snippet" : "输出 S_AntivalentOut 设定为 FALSE . Error 设定为 TRUE . DiagCode 表示错误状态。没有将复位定义为与错误复位相结合的输入。只要一组输入值正确 S_AntivalentOut 存在， Error 是 FALSE 再次。...", 
"body" : "输出 S_AntivalentOut 设定为 FALSE . Error 设定为 TRUE . DiagCode 表示错误状态。没有将复位定义为与错误复位相结合的输入。只要一组输入值正确 S_AntivalentOut 存在， Error 是 FALSE 再次。 " }, 
{ "title" : "功能块特定的错误和状态代码 ", 
"url" : "sil3_plcopen_fb_antivalent.html#UUID-0eb04847-5281-87e5-f777-bfe82823b317_a593613e514bac0a8640e01c294bc_id_ad66950e0f6a49ccc0a8640e005c60c9", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_Antivalent \/ 功能块特定的错误和状态代码 ", 
"snippet" : "FB 特定的错误代码 DiagCode 州名 状态描述和输出设置 16#C010 Error 1 状态下的差异时间已过 16#8802 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C020 Error 2 状态下的差异时间已过 16#8804 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C030 Error 3 状态下的差异时间已过 16#8806 Ready = TRUE S_Antiv...", 
"body" : "FB 特定的错误代码 DiagCode 州名 状态描述和输出设置 16#C010 Error 1 状态下的差异时间已过 16#8802 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C020 Error 2 状态下的差异时间已过 16#8804 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = FALSE Error = TRUE 16#C030 Error 3 状态下的差异时间已过 16#8806 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = FALSE Error = TRUE FB 特定的状态码 DiagCode 州名 状态描述和输出设置 16#0000 Idle 功能块未激活（初始状态）。 Ready = FALSE S_AntivalentOut = FALSE SafetyDemand = FALSE Error = FALSE 16#8801 Init FB 已检测到激活，现在 FB 已激活。 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = TRUE Error = FALSE 16#8000 Safety Output Enabled 输入切换到 TRUE 处于反价模式。 Ready = TRUE S_AntivalentOut = TRUE SafetyDemand = FALSE Error = FALSE 16#8802 Wait for NO ChannelNC 已切换到 TRUE – 等待 ChannelNO 切换到 FALSE ;差异计时器启动。 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = TRUE Error = FALSE 16#8804 Wait for NC ChannelNO 已切换到 FALSE – 等待 ChannelNC 切换到 TRUE ;差异计时器启动。 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = TRUE Error = FALSE 16#8006 From Active Wait 一个通道已切换到非活动状态；等待第二个通道也切换到非活动状态。 Ready = TRUE S_AntivalentOut = FALSE SafetyDemand = TRUE Error = FALSE " }, 
{ "title" : "SF_EDM (External Device Monitoring) ", 
"url" : "sf_edm_fb.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "适用的安全标准 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_76f4d27cd81479b0c0a8640e005bde6a", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 适用的安全标准 ", 
"snippet" : "SF_EDM 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。...", 
"body" : "SF_EDM 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。 " }, 
{ "title" : "接口说明 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_4ec12369d84f211ec0a8640e014661bd", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 接口说明 ", 
"snippet" : "此功能块应用输入信号 ( S_OutControl ）到输出信号（ S_EDM_Out ）。功能块监控两个输入是否在定义的时间内关闭（ MonitoringTime ）。如果它们没有在规定的时间内关闭， S_EDM_OUT 设定为 FALSE . 这 SF_EDM （外部设备监控） FB 监控执行器的初始状态和开关状态，例如由安全输出设备控制的开关放大器。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_OutControl SAFEBOOL FALSE 多变的 前面的安全 FB 的控制信号。 来自 PLCopen 库的典...", 
"body" : "此功能块应用输入信号 ( S_OutControl ）到输出信号（ S_EDM_Out ）。功能块监控两个输入是否在定义的时间内关闭（ MonitoringTime ）。如果它们没有在规定的时间内关闭， S_EDM_OUT 设定为 FALSE . 这 SF_EDM （外部设备监控） FB 监控执行器的初始状态和开关状态，例如由安全输出设备控制的开关放大器。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_OutControl SAFEBOOL FALSE 多变的 前面的安全 FB 的控制信号。 来自 PLCopen 库的典型功能块信号（例如 SF_OutControl , SF_TwoHandControlTypeII ) FALSE ：禁用安全输出（ S_EDM_Out ) TRUE ：启用安全输出（ S_EDM_Out ) S_EDM1 SAFEBOOL FALSE 多变的 第一个连接的执行器（开关放大器）的反馈信号。 FALSE ：第一个连接的执行器的开关状态。 TRUE ：第一个连接的执行器的初始状态。 S_EDM2 SAFEBOOL FALSE 多变的 第二个连接的执行器（开关放大器）的反馈信号。 根据安装的执行器、反馈信号和目标安全级别之间的接线，可能只使用组合输入。在这种情况下，用户必须使用图形连接来跨接 EDM1 和 EDM2 参数。 S_EDM1 和 S_EDM2 然后由相同的信号控制。 FALSE ：第二个连接的执行器的开关状态。 TRUE ：第二个连接的执行器的初始状态 MonitoringTime TIME #0ms 持续的 连接和监控的执行器的最大响应时间。 警示性说明 MonitoringTime 必须遵守。 Reset BOOL FALSE 看 通用输入参数 MonitoringTime 适用于扩展级别的开发人员： MonitoringTime 输入必须用一个常数值激活。不得更改调用的值。 VAR_OUTPUT 姓名 数据类型 初始值 说明，参数值 Ready BOOL FALSE 看 一般输出参数 S_EDM_Out SAFEBOOL FALSE 控制执行器。结果由反馈信号监控 S_EDMx . FALSE ：禁用连接的执行器 TRUE ：启用连接的执行器 SafetyDemand BOOL FALSE 看 一般输出参数 ResetRequest BOOL FALSE 看 一般输出参数 Error BOOL FALSE 看 一般输出参数 DiagCode WORD 16#0000 看 诊断代码 功能块： SF_EDM " }, 
{ "title" : "功能说明 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_2d9888c13ef8014cc0a8640e00128d1e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 功能说明 ", 
"snippet" : "这 SF_EDM FB 控制安全输出并监控受控执行器。 该功能块通过反馈信号（ S_EDM1 和 S_EDM2 ) 在执行器由 FB 启用之前。 功能块监控执行器的开关状态（ MonitoringTime ) 在 FB 启用执行器之后。 必须使用两个单一反馈信号来准确诊断连接的执行器。来自两个连接的执行器的公共反馈信号必须用于连接的执行器的受限但简单的诊断功能。在这种情况下，用户必须将此公共信号连接到 S_EDM1 和 S_EDM2 参数。 S_EDM1 和 S_EDM2 然后由相同的信号控制。 安全功能中使用的开关装置应从风险分析中指定的类别中选择。 可选启动禁止 块激活时的启动禁止 这 S...", 
"body" : "这 SF_EDM FB 控制安全输出并监控受控执行器。 该功能块通过反馈信号（ S_EDM1 和 S_EDM2 ) 在执行器由 FB 启用之前。 功能块监控执行器的开关状态（ MonitoringTime ) 在 FB 启用执行器之后。 必须使用两个单一反馈信号来准确诊断连接的执行器。来自两个连接的执行器的公共反馈信号必须用于连接的执行器的受限但简单的诊断功能。在这种情况下，用户必须将此公共信号连接到 S_EDM1 和 S_EDM2 参数。 S_EDM1 和 S_EDM2 然后由相同的信号控制。 安全功能中使用的开关装置应从风险分析中指定的类别中选择。 可选启动禁止 块激活时的启动禁止 这 S_StartReset 只有在确保安全控制器启动时不会发生危险情况的情况下，才能激活输入。 " }, 
{ "title" : "状态图 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_caec1646dd39d5e3c0a8640e01ec96c8", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 状态图 ", 
"snippet" : "状态图： SF_EDM 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。...", 
"body" : "状态图： SF_EDM 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。 " }, 
{ "title" : "典型时序图 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_60b773bbdd39d5e3c0a8640e00cb806c", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 典型时序图 ", 
"snippet" : "典型时序图 SF_EDM , S_StartReset = FALSE...", 
"body" : "典型时序图 SF_EDM , S_StartReset = FALSE " }, 
{ "title" : "错误检测 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_b2fd02e2dd39d5e4c0a8640e00e4ad2d", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 错误检测 ", 
"snippet" : "以下条件强制转换到错误状态： 无效的静态 Reset 过程中的信号 过程中的 EDM 信号无效 这 S_OutControl 和 Reset 由于编程错误，输入被错误地互连。...", 
"body" : "以下条件强制转换到错误状态： 无效的静态 Reset 过程中的信号 过程中的 EDM 信号无效 这 S_OutControl 和 Reset 由于编程错误，输入被错误地互连。 " }, 
{ "title" : "错误行为 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_5cb72b9223bf8692c0a8640e01b19833", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 错误行为 ", 
"snippet" : "在错误状态下，输出如下： 这 S_EDM_Out 设定为 FALSE 并保持在这种安全状态。 EDM 错误消息必须始终由上升触发复位 Reset . 可以通过设置重置重置错误消息 Reset 到 FALSE . 功能块激活后，可选的启动禁止可以通过上升沿复位 Reset 输入。...", 
"body" : "在错误状态下，输出如下： 这 S_EDM_Out 设定为 FALSE 并保持在这种安全状态。 EDM 错误消息必须始终由上升触发复位 Reset . 可以通过设置重置重置错误消息 Reset 到 FALSE . 功能块激活后，可选的启动禁止可以通过上升沿复位 Reset 输入。 " }, 
{ "title" : "功能块特定的错误和状态代码 ", 
"url" : "sf_edm_fb.html#UUID-b0dd0316-01d4-1661-651b-a6b61bb0f213_d28e32d81479b1c0a8640e001c2a5f_id_ad66950e0f6a49ccc0a8640e005c60c9", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EDM (External Device Monitoring) \/ 功能块特定的错误和状态代码 ", 
"snippet" : "FB 特定的错误代码 DiagCode 州名 状态说明及输出设定 16#C001 Reset Error 1 状态下的静态复位信号 16#8401 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C011 Reset Error 21 静态复位信号或相同的信号 EDM1 和 Reset （上升触发器在 Reset 和 EDM1 同时）在状态 16#C010 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE...", 
"body" : "FB 特定的错误代码 DiagCode 州名 状态说明及输出设定 16#C001 Reset Error 1 状态下的静态复位信号 16#8401 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C011 Reset Error 21 静态复位信号或相同的信号 EDM1 和 Reset （上升触发器在 Reset 和 EDM1 同时）在状态 16#C010 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C021 Reset Error 22 静态复位信号或相同的信号 EDM2 和 Reset （上升触发器在 Reset 和 EDM2 同时）在状态 16#C020 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C031 Reset Error 23 静态复位信号或相同的信号 EDM1 , EDM2 ， 和 Reset （上升触发器在 Reset , EDM1 ， 和 EDM2 同时）在状态 16#C030 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C041 Reset Error 31 静态复位信号或相同的信号 EDM1 和 Reset （上升触发器在 Reset 和 EDM1 同时）在状态 16#C040 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C051 Reset Error 32 静态复位信号或相同的信号 EDM2 和 Reset （上升触发器在 Reset 和 EDM2 同时）在状态 16#C050 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C061 Reset Error 33 静态复位信号或相同的信号 EDM1 , EDM2 ， 和 Reset （上升触发器在 Reset , EDM1, 和 EDM2 同时）在状态 16#C060 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C071 Reset Error 41 状态下的静态复位信号 16#C070 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C081 Reset Error 42 状态下的静态复位信号 16#C080 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C091 Reset Error 43 状态下的静态复位信号 16#C090 . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C010 EDM Error 11 信号在 EDM1 在初始执行器状态下无效。在状态 16#8810 ， 这 EDM1 信号是 FALSE 启用时 S_OutControl . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = R (*) Error = TRUE 16#C020 EDM Error 12 信号在 EDM2 在初始执行器状态下无效。在状态 16#8810 ， 这 EDM2 信号是 FALSE 启用时 S_OutControl . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = R (*) Error = TRUE 16#C030 EDM Error 13 信号在 EDM1 和 EDM2 在初始执行器状态下无效。在状态 16#8810 ， 这 EDM1 和 EDM2 信号是 FALSE 启用时 S_OutControl . Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE 16#C040 EDM Error 21 信号在 EDM1 在初始执行器状态下无效。在状态 16#8810 ， 这 EDM1 信号是 FALSE 并且监控时间已经过去。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = R (*) Error = TRUE 16#C050 EDM Error 22 信号在 EDM2 在初始执行器状态下无效。在状态 16#8810 ， 这 EDM2 信号是 FALSE 并且监控时间已经过去。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = R (*) Error = TRUE 16#C060 EDM Error 23 信号在 EDM1 和 EDM2 在初始执行器状态下无效。在状态 16#8810 ， 这 EDM1 和 EDM2 信号是 FALSE 并且监控时间已经过去。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = R (*) Error = TRUE 16#C070 EDM Error 31 信号在 EDM1 在执行器切换状态下无效。在状态 16#8000 ， 这 EDM1 信号是 TRUE 并且监控时间已经过去。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = TRUE Error = TRUE 16#C080 EDM Error 32 信号在 EDM2 在执行器切换状态下无效。在状态 16#8000 ， 这 EDM2 信号是 TRUE 并且监控时间已经过去。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = TRUE Error = TRUE 16#C090 EDM Error 33 信号在 EDM1 和 EDM2 在执行器切换状态下无效。在状态 16#8000 ， 这 EDM1 和 EDM2 信号是 FALSE 并且监控时间已经过去。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = TRUE Error = TRUE 16#C100 Init Error 类似的信号 S_OutControl 和 Reset ( R_TRIG 在同一周期）检测到（可能是编程错误）。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE (*)\nIF EDM_1 = TRUE AND EDM_2 = TRUE THEN\t\n R:= TRUE;\nELSE\t\n R:= FALSE;\nEND_IF\n FB 特定的状态码 DiagCode 州名 状态描述和输出设置 16#0000 Idle 功能块未激活（初始状态）。 Ready = FALSE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = FALSE 16#8401 Init 块激活启动禁止处于活动状态。需要重置。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = FALSE ResetRequest = TRUE Error = FALSE 16#8810 Output Disable EDM 控制未激活。进入状态时定时器启动。 Ready = TRUE S_EDM_Out = FALSE SafetyDemand = TRUE ResetRequest = FALSE Error = FALSE 16#8000 Output Enable EDM 控制处于活动状态。进入状态时定时器启动。 Ready = TRUE S_EDM_Out = TRUE SafetyDemand = FALSE ResetRequest = FALSE Error = FALSE " }, 
{ "title" : "SF_EmergencyStop ", 
"url" : "sil3_plcopen_fb_estop.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "适用的安全标准 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_66471085339c226cc0a8640e01dcda6e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 适用的安全标准 ", 
"snippet" : "SF_EmergencyStop 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。...", 
"body" : "SF_EmergencyStop 是经过认证的 PLCopen 功能块。有关应用标准的详细信息，请参阅：“PLCopen – Technical Committee 5 – Safety Software” 用户必须满足标准中列出的要求。 " }, 
{ "title" : "接口说明 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_826620d73833b2adc0a8640e0170bcf5", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 接口说明 ", 
"snippet" : "该功能块是用于监控紧急停止按钮的安全相关功能块。 SF_EmergencyStop 可用于紧急关闭功能（停止类别 0），或 - 通过额外的外围支持 - 作为紧急停止（停止类别 1 或 2）。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_EStopIn SAFEBOOL FALSE 安全需求输入 多变的 FALSE ：对安全相关响应的需求（例如，紧急停止按钮被接合） TRUE ：没有安全相关响应的需求（例如，紧急停止按钮未使用） S_StartReset SAFEBOOL FALSE 看 通用输入参数 S_AutoRes...", 
"body" : "该功能块是用于监控紧急停止按钮的安全相关功能块。 SF_EmergencyStop 可用于紧急关闭功能（停止类别 0），或 - 通过额外的外围支持 - 作为紧急停止（停止类别 1 或 2）。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 Activate BOOL FALSE 看 通用输入参数 S_EStopIn SAFEBOOL FALSE 安全需求输入 多变的 FALSE ：对安全相关响应的需求（例如，紧急停止按钮被接合） TRUE ：没有安全相关响应的需求（例如，紧急停止按钮未使用） S_StartReset SAFEBOOL FALSE 看 通用输入参数 S_AutoReset SAFEBOOL FALSE 看 通用输入参数 Reset BOOL FALSE 看 通用输入参数 VAR_OUTPUT 姓名 数据类型 初始值 说明，参数值 Ready BOOL FALSE 看 一般输出参数 S_EStopOut SAFEBOOL FALSE 安全相关响应的输出 FALSE ：安全输出禁用 对安全相关响应的需求（例如，紧急停止按钮已接合、需要复位或内部错误激活） TRUE ：启用安全输出 无需安全相关响应（例如，紧急停止按钮未启用；内部错误未激活）。 SafetyDemand BOOL FALSE 看 一般输出参数 ResetRequest BOOL FALSE 看 一般输出参数 Error BOOL FALSE 看 一般输出参数 DiagCode WORD 16#0000 看 诊断代码 功能块：SF_EmergencyStop " }, 
{ "title" : "功能说明 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_6b33567f3efcfde6c0a8640e014c192e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 功能说明 ", 
"snippet" : "这 S_EStopOut 使能信号复位到 FALSE 尽快 S_EStopIn 输入设置为 FALSE .这 S_EStopOut 使能信号复位到 TRUE 只有当 S_EStopIn 输入设置为 TRUE 并发生复位。使能复位取决于定义的 S_StartReset , S_AutoReset ， 和 Reset . 如果 S_AutoReset = TRUE ：确认是自动的。 如果 S_AutoRest = FALSE ：必须使用复位输入的上升触发来确认启用。 如果 S_StartReset = TRUE ：第一次启动安全控制器时自动进行确认。 如果 S_StartReset = FALSE...", 
"body" : "这 S_EStopOut 使能信号复位到 FALSE 尽快 S_EStopIn 输入设置为 FALSE .这 S_EStopOut 使能信号复位到 TRUE 只有当 S_EStopIn 输入设置为 TRUE 并发生复位。使能复位取决于定义的 S_StartReset , S_AutoReset ， 和 Reset . 如果 S_AutoReset = TRUE ：确认是自动的。 如果 S_AutoRest = FALSE ：必须使用复位输入的上升触发来确认启用。 如果 S_StartReset = TRUE ：第一次启动安全控制器时自动进行确认。 如果 S_StartReset = FALSE ：必须使用复位输入的上升触发来确认启用。 这 S_StartReset 和 S_AutoReset 只有在确保安全控制器启动时不会发生危险情况的情况下，才能激活输入。 SF_EmergencyStop 可用于监控单通道和双通道紧急停止按钮。例如，对于双通道应用，附加的 SF_Equivalent 功能块可用于检测是否已超过接触同步。符合 EN ISO 13849-1 的类别分类将取决于所使用的最终元素。 这 SF_EmergencyStop 自动检测静电 TRUE 在重置。进一步的错误检测，例如断线或短路，取决于所使用的专用硬件。 " }, 
{ "title" : "状态图 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_62036cb53833b2aec0a8640e00ab70a7", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 状态图 ", 
"snippet" : "状态图： SF_EmergencyStop 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。...", 
"body" : "状态图： SF_EmergencyStop 从任何状态过渡到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转换具有最高优先级。 " }, 
{ "title" : "典型时序图 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_section-idm4628919353521632993308247477", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 典型时序图 ", 
"snippet" : "时序图 SF_EmergencyStop ： S_StartReset = FALSE ; S_AutoReset = FALSE ;启动、复位、正常运行、安全需求、重启 SF_EmergencyStop 的时序图：S_StartReset = TRUE，S_AutoReset = FALSE；启动、正常运行、安全需求、重启 SF_EmergencyStop 的时序图：S_StartReset = FALSE、S_AutoReset = TRUE、启动、正常运行、安全要求、重启...", 
"body" : "时序图 SF_EmergencyStop ： S_StartReset = FALSE ; S_AutoReset = FALSE ;启动、复位、正常运行、安全需求、重启 SF_EmergencyStop 的时序图：S_StartReset = TRUE，S_AutoReset = FALSE；启动、正常运行、安全需求、重启 SF_EmergencyStop 的时序图：S_StartReset = FALSE、S_AutoReset = TRUE、启动、正常运行、安全要求、重启 " }, 
{ "title" : "错误检测 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_5ee9c22a3833b2aec0a8640e009605f8", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 错误检测 ", 
"snippet" : "功能块检测静态 TRUE 信号在 Reset 输入。...", 
"body" : "功能块检测静态 TRUE 信号在 Reset 输入。 " }, 
{ "title" : "错误行为 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_e4abd0cd3850efabc0a8640e00520eeb", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 错误行为 ", 
"snippet" : "S_EStopOut 设定为 FALSE .如果是静电 TRUE 信号在 ResetIn 输入， DiagCode 输出指示相关的错误代码和 Error 输出设置为 TRUE . 要离开错误状态， Reset 必须设置为 FALSE ....", 
"body" : "S_EStopOut 设定为 FALSE .如果是静电 TRUE 信号在 ResetIn 输入， DiagCode 输出指示相关的错误代码和 Error 输出设置为 TRUE . 要离开错误状态， Reset 必须设置为 FALSE . " }, 
{ "title" : "功能块特定的错误和状态代码 ", 
"url" : "sil3_plcopen_fb_estop.html#UUID-194a7bdf-b6ea-f735-1869-7f34a5253d4e_f366eae03371c52bc0a8640e01bae728_id_ad66950e0f6a49ccc0a8640e005c60c9", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_EmergencyStop \/ 功能块特定的错误和状态代码 ", 
"snippet" : "FB 特定的错误代码 DiagCode 州名 状态描述和输出设置 C001 Reset Error 1 Reset = TRUE 在等待的时候 S_EStopIn = TRUE . Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE C011 Reset Error 2 Reset = TRUE 在等待的时候 S_EStopIn = TRUE . Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetReques...", 
"body" : "FB 特定的错误代码 DiagCode 州名 状态描述和输出设置 C001 Reset Error 1 Reset = TRUE 在等待的时候 S_EStopIn = TRUE . Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE C011 Reset Error 2 Reset = TRUE 在等待的时候 S_EStopIn = TRUE . Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = TRUE FB 特定状态码（无错误） DiagCode 州名 状态描述和输出设置 0000 Idle 功能块未激活（初始状态）。 Ready = FALSE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = FALSE 8001 Init 激活是 TRUE .功能块已启用。检查是否 S_StartReset 是必须的。 Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = FALSE Error = FALSE 8802 Wait for S_EstopIn 1 激活是 TRUE .检查是否 Reset = FALSE 并等待 S_EStopIn = TRUE . Ready = TRUE S_EStopOut = FALSE SafetyDemand = TRUE ResetRequest = FALSE Error = FALSE 8402 Wait for Reset 1 激活是真的。 S_EStopIn = TRUE .等待上升触发 Reset . Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = TRUE Error = FALSE 8804 Wait for S_EStopIn2 激活是 TRUE .检测到安全需求。检查是否 Reset = FALSE 并等待 S_EStopIn = TRUE . Ready = TRUE S_EStopOut = FALSE SafetyDemand = TRUE ResetRequest = FALSE Error = FALSE 8404 Wait for Reset 2 激活是 TRUE . S_EStopIn = TRUE .检查是否 S_AutoReset 或等待上升触发 Reset . Ready = TRUE S_EStopOut = FALSE SafetyDemand = FALSE ResetRequest = TRUE Error = FALSE 8000 Safety Output Enabled 激活是 TRUE . S_EStop = TRUE .功能模式与 S_EStopOut = TRUE . Ready = TRUE S_EStopOut = TRUE SafetyDemand = FALSE ResetRequest = FALSE Error = FALSE " }, 
{ "title" : "SF_ResetButton ", 
"url" : "sf_antivalent_fb.html", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "适用的安全标准 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_50394b5514848640c0a8640e01132c0e", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 适用的安全标准 ", 
"snippet" : "SF_ResetButton 是经过认证的 PLCopen 功能块。有关所应用标准的详细信息，请参阅：“PLCopen – 技术委员会 5 – 安全软件” 用户必须满足标准中列出的要求。...", 
"body" : "SF_ResetButton 是经过认证的 PLCopen 功能块。有关所应用标准的详细信息，请参阅：“PLCopen – 技术委员会 5 – 安全软件” 用户必须满足标准中列出的要求。 " }, 
{ "title" : "接口说明 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_d99d631214848644c0a8640e01486937", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 接口说明 ", 
"snippet" : "该功能块向所有具有复位输入和上升沿检测的功能块添加了后沿功能。这可用于遵守 EN ISO 13849-1:2015。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 ResetRequested BOOL TRUE 输入应连接到 ResetRequest 成对FB的输出 TRUE : 请求重置 FALSE ：无复位请求\/无监控 ResetIn ResetIn BOOL FALSE 多变的。 复位按钮的输入 FALSE ：复位按钮释放 TRUE ：由操作员启动的复位按钮。 TrailingMinimum TIME T#350ms 持续的;在尾随模式下有效 必须启动复位开关的最短时间。如...", 
"body" : "该功能块向所有具有复位输入和上升沿检测的功能块添加了后沿功能。这可用于遵守 EN ISO 13849-1:2015。 VAR_INPUT 姓名 数据类型 初始值 说明，参数值 ResetRequested BOOL TRUE 输入应连接到 ResetRequest 成对FB的输出 TRUE : 请求重置 FALSE ：无复位请求\/无监控 ResetIn ResetIn BOOL FALSE 多变的。 复位按钮的输入 FALSE ：复位按钮释放 TRUE ：由操作员启动的复位按钮。 TrailingMinimum TIME T#350ms 持续的;在尾随模式下有效 必须启动复位开关的最短时间。如果按下复位按钮的时间短于该时间，则忽略复位。 典型值：350 ms 绝对最小值：100 ms 最小值：2 个 PLC 循环 TrailingMaximum TIME T#2s 持续的;在尾随模式下有效 可以启动复位开关的最长时间。如果按下复位按钮的时间超过此时间，则忽略复位。 典型值：2 s 这 ResetOut 输出是上升沿（ R_TRIG ）一个 FB 周期长度的脉冲，可连接到任何具有复位输入的 FB，因此符合 PLCopen 安全 FB 版本 1.0。 这 ResetRequested 输入连接到 ResetRequest 相关FB的输出。这样可以控制需要检查重置按钮的时间间隔。 这个FB使用 S_AutoReset 。 VAR_OUTPUT 姓名 数据类型 初始值 说明，参数值 Ready BOOL FALSE 看 一般输出参数 ResetOut BOOL FALSE 用于启动复位程序的脉冲 该脉冲在下降沿之后产生。 脉冲输出先上升沿。至少 1 个周期 Error BOOL FALSE 看 一般输出参数 DiagCode WORD 16#0000 看 诊断代码 功能块：SF_ResetButton " }, 
{ "title" : "功能说明 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_2654bc8d3e8dfbc2c0a8640e006a4078", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 功能说明 ", 
"snippet" : "有关功能描述，请参见 ISO 13849-1:2015，第 5.6 节“重置行为”。 输入输出逻辑表 输入 输出 Reset Requested ResetIn TrailingMinimum TrailingMaximum Ready ResetOut Error DiagCode FALSE --- --- --- FALSE FALSE FALSE 16#0000 TRUE FALSE > = 100 ms TrailingMaximum>=TrailingMinimum TRUE FALSE FALSE 16#8001 TRUE FALSE -> TRUE 看门狗已启动 TRUE FA...", 
"body" : "有关功能描述，请参见 ISO 13849-1:2015，第 5.6 节“重置行为”。 输入输出逻辑表 输入 输出 Reset Requested ResetIn TrailingMinimum TrailingMaximum Ready ResetOut Error DiagCode FALSE --- --- --- FALSE FALSE FALSE 16#0000 TRUE FALSE > = 100 ms TrailingMaximum>=TrailingMinimum TRUE FALSE FALSE 16#8001 TRUE FALSE -> TRUE 看门狗已启动 TRUE FALSE FALSE 16#8004 TRUE TRUE TrailingMinimum <经过时间< TrailingMaximum TRUE FALSE FALSE 16#8000 TRUE TRUE TrailingMinimum <经过时间< TrailingMaximum TRUE TRUE FALSE 16#8000 下一次调用时，会自动转换为 16#8000 到 16#83E2 。 16#83E2 在逻辑表中，箭头->代表转换。 TRUE -> FALSE 表示变量的值已更改为 TRUE 到 FALSE 。 " }, 
{ "title" : "状态图 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_272080c228454ed1c0a8640e01ff3877", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 状态图 ", 
"snippet" : "状态图：SF_ResetButton 注：从任意状态到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转变具有最高优先级。...", 
"body" : "状态图：SF_ResetButton 注：从任意状态到 Idle 状态由于 Activate = FALSE 未显示。然而，这些转变具有最高优先级。 " }, 
{ "title" : "典型时序图 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_841e89c023bf8691c0a8640e01f2c59c", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 典型时序图 ", 
"snippet" : "SF_ResetButton 的时序图...", 
"body" : "SF_ResetButton 的时序图 " }, 
{ "title" : "错误检测 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_6a49fd6423bf8691c0a8640e0169e649", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 错误检测 ", 
"snippet" : "如果输入 ResetIn = TRUE 什么时候 ResetRequested = TRUE , 产生错误。 如果输入 ResetRequested = TRUE 和 ResetIn = TRUE 和时间输入 TrailingMinimum 未达到或输入 TrailingMaximum 超过，检测到错误。...", 
"body" : "如果输入 ResetIn = TRUE 什么时候 ResetRequested = TRUE , 产生错误。 如果输入 ResetRequested = TRUE 和 ResetIn = TRUE 和时间输入 TrailingMinimum 未达到或输入 TrailingMaximum 超过，检测到错误。 " }, 
{ "title" : "错误行为 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_5cb72b9223bf8692c0a8640e01b19833", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ 错误行为 ", 
"snippet" : "如果是静电 TRUE 信号在 ResetIn 输入， DiagCode 输出指示相关的错误代码和 Error 输出设置为 TRUE ....", 
"body" : "如果是静电 TRUE 信号在 ResetIn 输入， DiagCode 输出指示相关的错误代码和 Error 输出设置为 TRUE . " }, 
{ "title" : "FB 特定错误和状态代码 ", 
"url" : "sf_antivalent_fb.html#UUID-3a3c4724-cf31-2d61-118e-ac800e72196c_a593613e514bac0a8640e01c294bc_id_ad66950e0f6a49ccc0a8640e005c60c9", 
"breadcrumbs" : "CODESYS Safety SIL2 \/ 库：PLCopen Safety FBs \/ SF_ResetButton \/ FB 特定错误和状态代码 ", 
"snippet" : "FB 特定的错误代码 DiagCode 州名 状态说明及输出设定 16#C000 Parameter Error TrailingMinimum > TrailingMaximum 或者 TrailingMinimum < 100 msec Ready = TRUE ResetOut = FALSE Error = TRUE 16#C001 Reset Error ResetIn = TRUE 在等待的时候 NOT ResetIn Ready = TRUE ResetOut = FALSE Error = TRUE 16#C3E0 Error Trailing Maximum Trailing...", 
"body" : "FB 特定的错误代码 DiagCode 州名 状态说明及输出设定 16#C000 Parameter Error TrailingMinimum > TrailingMaximum 或者 TrailingMinimum < 100 msec Ready = TRUE ResetOut = FALSE Error = TRUE 16#C001 Reset Error ResetIn = TRUE 在等待的时候 NOT ResetIn Ready = TRUE ResetOut = FALSE Error = TRUE 16#C3E0 Error Trailing Maximum TrailingMaximum 检测前已过 F_TRIG 在 ResetIn .等待 R_TRIG 在 ResetIn Ready = TRUE ResetOut = FALSE Error = TRUE 16#C3F0 Error Trailing Minimum F_TRIG 在 ResetIn 之前检测到 TrailingMinimum 已经过去。等待 R_TRIG 在 ResetIn . Ready = TRUE ResetOut = FALSE Error = TRUE FB 特定状态代码 DiagCode 州名 状态说明及输出设定 16#0000 Idle 功能块未激活（初始状态） Ready = FALSE ResetOut = FALSE Error = FALSE 16#83E2 Wait for R_TRIG 功能块已启用。等待 R_TRIG 在 ResetIn Ready = TRUE ResetOut = FALSE Error = FALSE 16#83F2 Wait for F_TRI ResetIn = TRUE .等待 F_TRIG 在 ResetIn Ready = TRUE ResetOut = FALSE Error = FALSE 16#8000 Reset Detected 检测到有效的复位行为。状态至少一个周期有效，会自动转移到 83E2 . Ready = TRUE ResetOut = TRUE Error = FALSE " }
]
$(document).trigger('search.ready');
});