$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS SoftMotion Stäubli Support ", 
"url" : "_smstbli_start_page.html", 
"breadcrumbs" : "CODESYS SoftMotion Stäubli Support \/ CODESYS SoftMotion Stäubli Support ", 
"snippet" : "限制 CODESYS EtherCAT 版本 4.10.0.0 包含 “从设备加载 PDO 信息” 功能的已知问题，这会使其无法正常使用 CODESYS SoftMotion Stäubli Support 包裹。 请使用较早版本或较新版本的 CODESYS EtherCAT 取而代之。 这个 CODESYS SoftMotion Stäubli Support 插件使控制成为可能 Stäubli 来自 TS2 和 TX2 系列的机器人通过 UniVal 驱动器接口 CODESYS SoftMotion 。以合适的设备描述和运动学变换的形式为机器人提供支持 要求 该控制器具有实时功能并支持 E...", 
"body" : "限制 CODESYS EtherCAT 版本 4.10.0.0 包含 “从设备加载 PDO 信息” 功能的已知问题，这会使其无法正常使用 CODESYS SoftMotion Stäubli Support 包裹。 请使用较早版本或较新版本的 CODESYS EtherCAT 取而代之。 这个 CODESYS SoftMotion Stäubli Support 插件使控制成为可能 Stäubli 来自 TS2 和 TX2 系列的机器人通过 UniVal 驱动器接口 CODESYS SoftMotion 。以合适的设备描述和运动学变换的形式为机器人提供支持 要求 该控制器具有实时功能并支持 EtherCAT 。 这个 CODESYS SoftMotion 软件包已安装。 A Stäubli CS9 控制器可用。 你可以下载 CODESYS SoftMotion Stäubli Support 来自 CODESYS 国际商店 或者 CODESYS 商店北美 。您还可以在那里找到该产品的数据表。 " }, 
{ "title" : "机器人模型 ", 
"url" : "_smstbli_start_page.html#UUID-4cb6a3d0-e63a-1bf9-f7a7-5ecc9915cfe0_section-idm235098272785514", 
"breadcrumbs" : "CODESYS SoftMotion Stäubli Support \/ CODESYS SoftMotion Stäubli Support \/ 机器人模型 ", 
"snippet" : "该插件支持以下机器人模型。 ts2_40-S1-D25-L200-ceiling-R4-V8 ts2_40-S1-D25-L200-floor-R4-V7 ts2_40-S1-D25-L400-ceiling-R1-V9 ts2_40-S1-D25-L400-floor-R1-V8 ts2_60-S1-D25-L200-ceiling-R4-V7 ts2_60-S1-D25-L200-floor-R4-V7 ts2_60-S1-D25-L400-ceiling-R1-V8 ts2_60-S1-D25-L400-floor-R1-V8 ts2_80-S1-D25-L200-ceiling-R4-...", 
"body" : "该插件支持以下机器人模型。 ts2_40-S1-D25-L200-ceiling-R4-V8 ts2_40-S1-D25-L200-floor-R4-V7 ts2_40-S1-D25-L400-ceiling-R1-V9 ts2_40-S1-D25-L400-floor-R1-V8 ts2_60-S1-D25-L200-ceiling-R4-V7 ts2_60-S1-D25-L200-floor-R4-V7 ts2_60-S1-D25-L400-ceiling-R1-V8 ts2_60-S1-D25-L400-floor-R1-V8 ts2_80-S1-D25-L200-ceiling-R4-V7 ts2_80-S1-D25-L200-floor-R4-V7 ts2_80-S1-D25-L400-ceiling-R1-V8 ts2_80-S1-D25-L400-floor-R1-V8 ts2_100-S1-D25-L200-ceiling-R4-V7 ts2_100-S1-D25-L200-floor-R4-V7 ts2_100-S1-D25-L400-ceiling-R1-V9 ts2_100-S1-D25-L400-floor-R1-V9 tx2_40-S3-R2 tx2_60l-S2-R2 tx2_60-S2-R3 tx2_90l-S2-R4 tx2_90-S2-R3 tx2_90xl-S2-R4-V1 tx2_140-S3-R1 tx2_160l-S3-R1 tx2_160-S3-R1 tx2_200l-S3-R1-V6 tx2_200-S3-R1-V6 " }, 
{ "title" : "用法 ", 
"url" : "_smstbli_using_roboter.html", 
"breadcrumbs" : "CODESYS SoftMotion Stäubli Support \/ 用法 ", 
"snippet" : "限制 CODESYS EtherCAT 版本 4.10.0.0 包含 “从设备加载 PDO 信息” 功能的已知问题，这会使其无法正常使用 CODESYS SoftMotion Stäubli Support 包裹。 请使用较早版本或较新版本的 CODESYS EtherCAT 取而代之。 以下说明描述了的配置 Stäubli 里面的机器人 CODESYS Development System 开发环境。 用你的控制器创建一个新的标准项目： 选择您选择的实现语言。 为您的控制器选择设备描述。 添加 EtherCAT 驱动器： 在设备树中，打开的快捷菜单 Device 节点，然后选择 添加设备 命...", 
"body" : "限制 CODESYS EtherCAT 版本 4.10.0.0 包含 “从设备加载 PDO 信息” 功能的已知问题，这会使其无法正常使用 CODESYS SoftMotion Stäubli Support 包裹。 请使用较早版本或较新版本的 CODESYS EtherCAT 取而代之。 以下说明描述了的配置 Stäubli 里面的机器人 CODESYS Development System 开发环境。 用你的控制器创建一个新的标准项目： 选择您选择的实现语言。 为您的控制器选择设备描述。 添加 EtherCAT 驱动器： 在设备树中，打开的快捷菜单 Device 节点，然后选择 添加设备 命令。 对话框打开。 在下面 现场总线 → EtherCAT → 大师 ，选择现场总线 EtherCAT Master SoftMotion 。点击 添加设备 命令确认选择，但保持对话框处于打开状态。 新节点 EtherCAT_Master_SoftMotion 显示在设备树中。 在项目树中单击此节点。 选项的变化是 添加设备 对话框。 选择你的 Stäubli 机器人。你可以在下面找到 现场总线 → EtherCAT → 奴隶 → 史陶比尔机器人 。点击 添加设备 确认您的选择，然后关闭对话框。 在下面 EtherCAT_Master_SoftMotion 节点，已经为机器人创建了另一个节点，为其驱动器创建了更多节点。 启用专家设置 EtherCAT 机器人的节点： 在设备树中，在 EtherCAT_Master_SoftMotion 节点，双击机器人。 编辑器打开。 启用 专家设置 选项在那里。 有关更多信息，请参阅以下内容： 选项卡：EtherCAT 从机 — 常规 检查您的设备上是否已经配置了 I\/O Stäubli CS 9 控制器。 如果未配置 I\/O，则需要禁用机器人的产品 ID 检查。 这个 Stäubli 在不配置 I\/O 时，CS9 控制器的产品 ID 与配置 I\/O 时具有不同的产品 ID。 在设备树中，在 EtherCAT_Master_SoftMotion 节点，双击机器人节点。 编辑器打开。 在 启动检查 组，禁用 检查产品 ID 选项。 以下配置用于 ts2_100_S1_D25_L200_ceiling_R4 机器人。 如果已经配置了 I\/O，则无需执行任何其他操作。转到下一步。 将 PDO 配置转移到项目： 在下面 EtherCAT_Master_SoftMotion 节点，打开机器人的编辑器。 打开 专家过程数据 选项卡并禁用 PDO 配置 中的选项 下载 组。 以下配置用于 ts2_100_S1_D25_L200_ceiling_R4 机器人。 登录控制器，启动应用程序，然后等待 EtherCAT 线程已启动。 现在点击 从设备加载 PDO 信息 按钮。 机器人的PDO配置将应用于该项目。 注销控制器。 添加 Staubli_Transformation 项目库。 打开项目的库管理器。 在左上角，单击 添加库 按钮。 对话框打开。 在搜索栏中，输入文本 “Staubli_Transformation”，然后添加你找到的库。 插入轴组。 在设备树中，选择 Application 节点并打开快捷菜单。点击 添加对象 → 轴心集团 命令。 这个 添加轴组 对话框打开。 输入您选择的名称，然后单击 添加 按钮进行确认。 在应用程序下方插入一个轴组。轴组配置器打开 点击 选择运动学 按钮。 这个 选择运动学 对话框打开，其中包含所有可用运动学配置及其描述的列表。 从此列表中选择您的机器人类型。 在 映射到坐标轴 参数组，将轴映射到步骤 2 中添加的驱动器。 对于驱动器 Stäubli 机器人，一些输入字段是故意隐藏的。这些已经预先配置好了。例如，这些字段包括轴的动态极限或其缩放的输入字段。 " }
]
$(document).trigger('search.ready');
});