// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFocus() {
  return window['go']['main']['App']['GetFocus']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetWorkingDirectory() {
  return window['go']['main']['App']['GetWorkingDirectory']();
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}

export function SetFocus(arg1, arg2) {
  return window['go']['main']['App']['SetFocus'](arg1, arg2);
}
