// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFocus():Promise<main.FocusState>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetStatus():Promise<main.Status>;

export function GetWorkingDirectory():Promise<string>;

export function SendPrompt(arg1:string):Promise<void>;

export function SetFocus(arg1:string,arg2:number):Promise<Record<string, any>>;
