$(document).ready(function () {indexDict['it'] = [{ "title" : "CODESYS IO-Link ", 
"url" : "_iolk_start_page.html", 
"breadcrumbs" : "CODESYS IO-Link \/ CODESYS IO-Link ", 
"snippet" : "Vedere la descrizione generale per informazioni sulle seguenti schede dell'editor del dispositivo. Scheda '<nome dispositivo> Mapping I\/O' Scheda '<nome dispositivo> Oggetti IEC' Scheda '<nome dispositivo> Parametri' Scheda '<nome dispositivo> Stato' Scheda 'Informazioni <nome dispositivo>' Solo in ...", 
"body" : "Vedere la descrizione generale per informazioni sulle seguenti schede dell'editor del dispositivo. Scheda '<nome dispositivo> Mapping I\/O' Scheda '<nome dispositivo> Oggetti IEC' Scheda '<nome dispositivo> Parametri' Scheda '<nome dispositivo> Stato' Scheda 'Informazioni <nome dispositivo>' Solo in caso di funzioni speciali è disponibile un'ulteriore pagina di aiuto separata per l'editor del dispositivo pertinente. Se la scheda \"Parametri <nome dispositivo>\" non viene visualizzata, selezionare il Mostra editor di configurazione del dispositivo generico opzione nel CODESYS opzioni, nel Editor di dispositivi categoria. IO-Link è un sistema di comunicazione per il collegamento di sensori e attuatori intelligenti a un sistema di automazione. Un sistema IO-Link è costituito da un master IO-Link che fornisce l'interfaccia al controllore sovraordinato (PLC) e uno o più dispositivi IO-Link (sensori e attuatori). I file di descrizione del dispositivo IODD associati devono essere installati nel repository del dispositivo prima che i moduli IO-Link siano disponibili nella finestra di dialogo \"Imposta dispositivo\". Per ulteriori informazioni, vedere: Comando \"Collega dispositivo\". e Comando 'Device Repository' Per informazioni più generali sul supporto del bus di campo in  CODESYS , Vedere: Supporto bus di campo " }, 
{ "title" : "Scheda: IO-Link – Informazioni sul dispositivo IO-Link ", 
"url" : "_iolk_edt_device_info.html", 
"breadcrumbs" : "CODESYS IO-Link \/ Scheda: IO-Link – Informazioni sul dispositivo IO-Link ", 
"snippet" : "Oggetto: Master IO-Link La scheda del modulo IO-Link mostra diverse informazioni sul prodotto e sul fornitore del dispositivo....", 
"body" : "Oggetto: Master IO-Link La scheda del modulo IO-Link mostra diverse informazioni sul prodotto e sul fornitore del dispositivo. " }, 
{ "title" : "Scheda: IO-Link – Parametri ", 
"url" : "_iolk_edt_parameter.html", 
"breadcrumbs" : "CODESYS IO-Link \/ Scheda: IO-Link – Parametri ", 
"snippet" : "Oggetto: Master IO-Link La scheda può essere utilizzata per leggere i parametri dal dispositivo IO-Link, per modificarli e quindi per riscriverli nel dispositivo. La gamma di funzioni dipende dalla descrizione del dispositivo. I comandi dei pulsanti sono disponibili anche nel menu contestuale della ...", 
"body" : "Oggetto: Master IO-Link La scheda può essere utilizzata per leggere i parametri dal dispositivo IO-Link, per modificarli e quindi per riscriverli nel dispositivo. La gamma di funzioni dipende dalla descrizione del dispositivo. I comandi dei pulsanti sono disponibili anche nel menu contestuale della riga selezionata nella tabella parametri. Ruolo utente Specialista Manutenzione Osservatore A seconda del ruolo utente selezionato, nella tabella vengono visualizzati più o meno dettagli dei parametri. Menù di identificazione Informazioni sull'identificazione del dispositivo Menù parametri Visualizza tutti i parametri del dispositivo Menù diagnostico Visualizza i messaggi di errore di un modulo (ad esempio, errore di tensione) Menù di osservazione Visualizza i messaggi di osservazione (ad esempio \"sensore sporco\") Imposta su Predefinito Reimposta i valori online dei parametri sui valori predefiniti come definito nella descrizione del dispositivo Leggi questa pagina Legge i valori attualmente visualizzati dei parametri dal dispositivo e li aggiorna nella tabella Scrivi questa pagina Scrive i valori attualmente visualizzati dei parametri nel dispositivo IO-Link Salva i valori online Applica il correntemente visualizzato Valore in linea al Valore colonna Ripristina i valori Applica i valori di Valore colonna al Valore in linea colonna La tabella elenca diversi parametri (nome) e dettagli dei parametri a seconda del ruolo utente impostato e del menu selezionato. Nome Nome parametro Valore Il valore del parametro attualmente valido viene visualizzato in Valore colonna. Valore in linea Il Valore in linea viene visualizzata solo se il dispositivo supporta un download di parametri e se i parametri visualizzati nell'editor di configurazione sono disponibili anche sul dispositivo. È possibile modificare i valori dei parametri in questa colonna e trasferirli al dispositivo con il Scrivi questa pagina comando senza modificare il progetto e senza la necessità di scaricare una nuova applicazione. Con il Salva i valori online comando, è possibile salvare il valore online corrente come a Valore . r\/w Autorizzazioni sui valori dei parametri ( ro : sola lettura; rw : leggere e scrivere) " }
]
$(document).trigger('search.ready');
});