import { createContext, useContext, createSignal, onMount, onCleanup, ParentProps } from "solid-js"

// Wails bindings - will be generated by wails dev/build
declare global {
  interface Window {
    go: {
      main: {
        App: {
          GetStatus(): Promise<UrpStatus>
          GetSessions(): Promise<UrpSession[]>
          GetFocus(): Promise<FocusState | null>
          SetFocus(target: string, depth: number): Promise<{ success: boolean; entities: number; rendered: string }>
          SendPrompt(prompt: string): Promise<void>
          GetWorkingDirectory(): Promise<string>
        }
      }
    }
    runtime: {
      EventsOn(eventName: string, callback: (data: any) => void): () => void
    }
  }
}

export interface FocusState {
  target: string
  depth: number
}

export interface UrpStatus {
  graphConnected: boolean
  project: string
  eventCount: number
  workers: number
  focus: FocusState | null
  ctx: {
    tokens: number
    files: number
  }
  memgraphUrl: string
}

export interface UrpSession {
  id: string
  title: string
  updatedAt: number
  messages: number
}

interface StreamChunk {
  type: "start" | "chunk" | "done" | "error"
  content?: string
  data?: any
}

interface UrpContextType {
  status: () => UrpStatus
  sessions: () => UrpSession[]
  loading: () => boolean
  error: () => string | null
  streamingContent: () => string
  sendPrompt: (prompt: string) => Promise<void>
  sendPromptStream: (prompt: string, onChunk: (content: string) => void) => Promise<void>
  refresh: () => Promise<void>
  setFocus: (target: string, depth: number) => Promise<void>
}

const defaultStatus: UrpStatus = {
  graphConnected: false,
  project: "unknown",
  eventCount: 0,
  workers: 0,
  focus: null,
  ctx: { tokens: 0, files: 0 },
  memgraphUrl: "bolt://localhost:7687"
}

const UrpContext = createContext<UrpContextType>()

export function UrpProvider(props: ParentProps) {
  const [status, setStatus] = createSignal<UrpStatus>(defaultStatus)
  const [sessions, setSessions] = createSignal<UrpSession[]>([])
  const [loading, setLoading] = createSignal(true)
  const [error, setError] = createSignal<string | null>(null)
  const [streamingContent, setStreamingContent] = createSignal("")

  async function fetchStatus() {
    try {
      const data = await window.go.main.App.GetStatus()
      setStatus(data)
      setError(null)
    } catch (e) {
      setError("Cannot connect to URP")
      setStatus(prev => ({ ...prev, graphConnected: false }))
    }
  }

  async function fetchSessions() {
    try {
      const data = await window.go.main.App.GetSessions()
      setSessions(data || [])
    } catch (e) {
      // Silent fail for sessions
    }
  }

  async function sendPromptBasic(prompt: string) {
    setLoading(true)
    try {
      await window.go.main.App.SendPrompt(prompt)
      await refresh()
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error")
    } finally {
      setLoading(false)
    }
  }

  async function sendPromptStream(prompt: string, onChunk: (content: string) => void) {
    setLoading(true)
    setStreamingContent("")
    setError(null)

    return new Promise<void>((resolve, reject) => {
      const cleanup = window.runtime.EventsOn("stream", (event: StreamChunk) => {
        if (event.type === "chunk" && event.content) {
          setStreamingContent(prev => prev + event.content + "\n")
          onChunk(event.content)
        } else if (event.type === "error") {
          setError(event.data?.message || "Stream error")
          setLoading(false)
          cleanup()
          reject(new Error(event.data?.message || "Stream error"))
        } else if (event.type === "done") {
          setLoading(false)
          cleanup()
          refresh().then(resolve)
        }
      })

      // Start the prompt
      window.go.main.App.SendPrompt(prompt).catch(e => {
        setError(e instanceof Error ? e.message : "Unknown error")
        setLoading(false)
        cleanup()
        reject(e)
      })
    })
  }

  async function setFocusTarget(target: string, depth: number) {
    setLoading(true)
    try {
      await window.go.main.App.SetFocus(target, depth)
      await refresh()
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error")
    } finally {
      setLoading(false)
    }
  }

  async function refresh() {
    await Promise.all([fetchStatus(), fetchSessions()])
    setLoading(false)
  }

  onMount(() => {
    refresh()
    // Poll status every 5 seconds
    const interval = setInterval(fetchStatus, 5000)
    onCleanup(() => clearInterval(interval))
  })

  const value: UrpContextType = {
    status,
    sessions,
    loading,
    error,
    streamingContent,
    sendPrompt: sendPromptBasic,
    sendPromptStream,
    refresh,
    setFocus: setFocusTarget
  }

  return (
    <UrpContext.Provider value={value}>
      {props.children}
    </UrpContext.Provider>
  )
}

export function useUrp() {
  const ctx = useContext(UrpContext)
  if (!ctx) throw new Error("useUrp must be used within UrpProvider")
  return ctx
}
