$(document).ready(function () {indexDict['fr'] = [{ "title" : "CODESYS Ethernet Adapter ", 
"url" : "_enad_start_page.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ CODESYS Ethernet Adapter ", 
"snippet" : "Voir la description générale pour plus d'informations sur les onglets suivants de l'éditeur d'appareil. Onglet '<nom de l'appareil> Mappage d'E\/S' Onglet '<nom de l'appareil> Objets CEI' Onglet '<nom de l'appareil> Paramètres' Onglet '<nom de l'appareil> État' Onglet '<nom de l'appareil> Information...", 
"body" : "Voir la description générale pour plus d'informations sur les onglets suivants de l'éditeur d'appareil. Onglet '<nom de l'appareil> Mappage d'E\/S' Onglet '<nom de l'appareil> Objets CEI' Onglet '<nom de l'appareil> Paramètres' Onglet '<nom de l'appareil> État' Onglet '<nom de l'appareil> Informations' Une page d'aide séparée supplémentaire pour l'éditeur d'appareil concerné n'est disponible que dans le cas de fonctions spéciales. Si l'onglet \"<nom de l'appareil> Paramètres\" n'est pas affiché, alors sélectionnez le Afficher les éditeurs de configuration de périphérique génériques possibilité dans le CODESYS option, dans le Éditeur d'appareil Catégorie. Pour des informations plus générales sur la prise en charge des bus de terrain dans CODESYS , voir: Prise en charge du bus de terrain le CODESYS L'adaptateur Ethernet est utilisé comme nœud parent pour les périphériques qui utilisent des protocoles basés sur Ethernet. CODESYS prend actuellement en charge EtherNet\/IP, Modbus et PROFINET IO. Tout d'abord, vous insérez l'adaptateur Ethernet sous le contrôleur. Ensuite, vous ajoutez le bus de terrain basé sur Ethernet sous l'adaptateur. " }, 
{ "title" : "Languette: EtherNet Adapter - Général ", 
"url" : "_enad_edt_general.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Languette: EtherNet Adapter - Général ", 
"snippet" : "Objet : Adaptateur Ethernet Cet onglet définit les interfaces réseau. Interface réseau : Ouvre le Adaptateurs réseau dialogue. Les adaptateurs Ethernet peuvent être sélectionnés ici, qui sont disponibles sur le système cible défini. adresse IP Masque de sous-réseau Passerelle par défaut Paramètres d...", 
"body" : "Objet : Adaptateur Ethernet Cet onglet définit les interfaces réseau. Interface réseau : Ouvre le Adaptateurs réseau dialogue. Les adaptateurs Ethernet peuvent être sélectionnés ici, qui sont disponibles sur le système cible défini. adresse IP Masque de sous-réseau Passerelle par défaut Paramètres de l'interface réseau sélectionnée Ajuster les paramètres du système d'exploitation Vous devez à nouveau confirmer cette option. Remarque : Les paramètres du système cible seront écrasés par les valeurs ci-dessus. Les paramètres IP du système d'exploitation peuvent être modifiés par le CODESYS système d'exécution uniquement si cela est autorisé dans le fichier de configuration ( *.cfg ) du temps d'exécution. Les entrées suivantes sont nécessaires pour cela : [SysSocket] Adapter.0.Name=\"<adapter name>\" (Exemple: \"LAN connection 4\" ) Adapter.0.EnableSetIpAndMask=1 Paramètres API redondants (API 2) Lors de l'utilisation d'une paire de contrôleurs CODESYS redondants, ces paramètres sont utilisés sur \"l'automate de secours\" ( PLC ID = 2 ) pour la carte réseau. Interface réseau : Ouvre le Adaptateurs réseau dialogue. Les adaptateurs Ethernet peuvent être sélectionnés ici, qui sont disponibles sur le système cible défini. adresse IP Masque de sous-réseau Passerelle par défaut Paramètres de l'interface réseau sélectionnée Les paramètres de l'automate redondant ne sont disponibles que si vous avez inséré le Redundancy Configuration objet sous votre application. " }, 
{ "title" : "Boîte de dialogue : Adaptateurs réseau ", 
"url" : "_enad_edt_general.html#UUID-68dc7536-40d9-f126-1da8-b5aefc635b70_id_eb69772dd959aeac0a8640e01875adb_id_98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Languette: EtherNet Adapter - Général \/ Boîte de dialogue : Adaptateurs réseau ", 
"snippet" : "Interfaces Affiche un aperçu de tous les adaptateurs réseau disponibles. adresse IP Masque de sous-réseau Passerelle par défaut Ces paramètres sont issus du système d'exploitation et ne peuvent pas être modifiés. Adresse Mac Adresse MAC de l'adaptateur Ethernet...", 
"body" : "Interfaces Affiche un aperçu de tous les adaptateurs réseau disponibles. adresse IP Masque de sous-réseau Passerelle par défaut Ces paramètres sont issus du système d'exploitation et ne peuvent pas être modifiés. Adresse Mac Adresse MAC de l'adaptateur Ethernet " }
]
$(document).trigger('search.ready');
});