$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "代码系统跟踪 ", 
"url" : "_trace_start_page.html", 
"breadcrumbs" : "代码系统跟踪 \/ 代码系统跟踪 ", 
"snippet" : "与一个 Trace 您可以按照与数字采样示波器类似的方式跟踪控制器上的变量值曲线。数据及其时间进程可以显示在跟踪编辑器中。 跟踪示例项目...", 
"body" : "与一个 Trace 您可以按照与数字采样示波器类似的方式跟踪控制器上的变量值曲线。数据及其时间进程可以显示在跟踪编辑器中。 跟踪示例项目 " }, 
{ "title" : "使用跟踪脚本接口 ", 
"url" : "_trace_script_use_scripting_interface.html", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 ", 
"snippet" : "这个 CODESYS Trace 插件提供了脚本接口。您将在下面找到如何使用此接口的示例。...", 
"body" : "这个 CODESYS Trace 插件提供了脚本接口。您将在下面找到如何使用此接口的示例。 " }, 
{ "title" : "创建跟踪 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-698d46a3-837f-222a-2594-c7b891d9d1f4", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 创建跟踪 ", 
"snippet" : "# a new trace can be created using the toplevel trace api myApplication = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\")[0] traceObject = trace.create(myApplication, \"MyTraceName\") traceObject.task_name = \"Task\" # a task with the name \"Task\" should already exist here. If it does not exi...", 
"body" : "# a new trace can be created using the toplevel trace api\nmyApplication = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\")[0]\ntraceObject = trace.create(myApplication, \"MyTraceName\")\ntraceObject.task_name = \"Task\" # a task with the name \"Task\" should already exist here. If it does not exist, this assignment throws an ValueError. # the task of the trace can be set during creation\nmyApplication = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\")[0]\ntraceObjectWithTaskSet = trace.create(myApplication, \"NameOfMySecondTrace\", \"MainTask\")\nassert traceObjectWithTaskSet.task_name == \"MainTask\" " }, 
{ "title" : "查找和验证现有痕迹 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-4f30c66c-f683-740b-5346-2912ac88f465", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 查找和验证现有痕迹 ", 
"snippet" : "# finding an existing trace can be done via the project.find method foundObjects = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\") expectedTraceObject = foundObjects[0] assert expectedTraceObject.is_trace_object, \"Could not find trace object with the expected name\" # .is...", 
"body" : "# finding an existing trace can be done via the project.find method\nfoundObjects = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\")\nexpectedTraceObject = foundObjects[0]\nassert expectedTraceObject.is_trace_object, \"Could not find trace object with the expected name\" # .is_trace_object is False for all other objects of type IScriptObject " }, 
{ "title" : "添加和更改跟踪变量 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-8bd43b1c-6343-ac35-d7f3-df547d6050cc", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 添加和更改跟踪变量 ", 
"snippet" : "myTrace = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\")[0] # add_variable() is a convenience method to add a new ScriptTraceVariable and set its properties during creation addedVariable = myTrace.add_trace_variable(variableName=\"PLC_PRG.a1\", graphColor= 0xff000000, gra...", 
"body" : "myTrace = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\")[0]\n\n# add_variable() is a convenience method to add a new ScriptTraceVariable and set its properties during creation\naddedVariable = myTrace.add_trace_variable(variableName=\"PLC_PRG.a1\",\n graphColor= 0xff000000,\n graphType=GraphType.LINES,\n activateMaxWarning=True,\n maxWarningArea=9.0,\n maxColor= 0xffff0000)\n\naddedVariable.enabled = False\n\nfor i in range(2,11):\n newVariable = myTrace.variable_list.add()\n newVariable.variable_name = \"PLC_PRG.a\"+str(i)\n newVariable.graph_type = GraphType.LINES_CROSSES\n\nassert len(myTrace.variable_list) == 10 " }, 
{ "title" : "更改 ScriptTrace 变量列表 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-b1ed5b03-c620-077c-2f62-acfd84e810f5", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改 ScriptTrace 变量列表 ", 
"snippet" : "移除特定的 ScriptTrace 变量 以下代码片段查找具有指定名称的变量并将其从 ScriptTrace 变量列表。 def remove_variable_by_name(traceObject, variableName): index_to_remove = -1 for variable in traceObject.variable_list: if variable.variable_name == variableName: index_to_remove = traceObject.variable_list.index_of(variable) break if inde...", 
"body" : "移除特定的 ScriptTrace 变量 以下代码片段查找具有指定名称的变量并将其从 ScriptTrace 变量列表。 def remove_variable_by_name(traceObject, variableName):\n index_to_remove = -1\n for variable in traceObject.variable_list:\n if variable.variable_name == variableName:\n index_to_remove = traceObject.variable_list.index_of(variable)\n break\n if index_to_remove != -1:\n traceObject.variable_list.remove(index_to_remove) " }, 
{ "title" : "更改录制设置 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-c9a5ef6d-6d81-7926-9538-b2249d53bb6a", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改录制设置 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设置跟踪记录的分辨率 (ms\/µs) ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737059980421", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改录制设置 \/ 设置跟踪记录的分辨率 (ms\/µs) ", 
"snippet" : "以下代码片段基于 ??? 片段。 traceObject.resolution = Resolution.MicroSeconds # Use Resolution.MilliSeconds if you want to have a trace recording based on milliseconds...", 
"body" : "以下代码片段基于 ??? 片段。 traceObject.resolution = Resolution.MicroSeconds\n# Use Resolution.MilliSeconds if you want to have a trace recording based on milliseconds " }, 
{ "title" : "设置录制条件 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737059249726", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改录制设置 \/ 设置录制条件 ", 
"snippet" : "以下代码片段基于 ??? 片段。 traceObject.record_condition = \"PLC_PRG.bDoRecord\"...", 
"body" : "以下代码片段基于 ??? 片段。 traceObject.record_condition = \"PLC_PRG.bDoRecord\" " }, 
{ "title" : "设置评论 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737061351582", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改录制设置 \/ 设置评论 ", 
"snippet" : "以下代码片段基于 ??? 片段。 traceObject.comment = \"This trace records the ...\"...", 
"body" : "以下代码片段基于 ??? 片段。 traceObject.comment = \"This trace records the ...\" " }, 
{ "title" : "设置自动启动选项 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737062520065", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改录制设置 \/ 设置自动启动选项 ", 
"snippet" : "以下代码片段基于 ??? 片段。 traceObject.auto_start = True...", 
"body" : "以下代码片段基于 ??? 片段。 traceObject.auto_start = True " }, 
{ "title" : "将选项设置为仅每隔 n 个周期录制一次 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737065791034", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 更改录制设置 \/ 将选项设置为仅每隔 n 个周期录制一次 ", 
"snippet" : "以下代码片段基于 ??? 片段。 traceObject.every_n_cycles = 10...", 
"body" : "以下代码片段基于 ??? 片段。 traceObject.every_n_cycles = 10 " }, 
{ "title" : "图表及其变量 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-d5a33595-77ec-1fc8-237c-1153a9fda9ec", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 图表及其变量 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "创建一个 ScriptTrace 包含所有内容的图表 ScriptTrace 变量 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737073150269", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 图表及其变量 \/ 创建一个 ScriptTrace 包含所有内容的图表 ScriptTrace 变量 ", 
"snippet" : "以下脚本显示如何创建简单图及其变量。 # first we need a ScriptTraceObject and some ScriptTraceVariables traceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0] assert traceObject.is_trace_object for i in range(5): traceObject.add_trace_variable(variableName=\"PLC_PRG.a\"+str(i)) # create one S...", 
"body" : "以下脚本显示如何创建简单图及其变量。 # first we need a ScriptTraceObject and some ScriptTraceVariables\ntraceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0]\nassert traceObject.is_trace_object\nfor i in range(5):\n traceObject.add_trace_variable(variableName=\"PLC_PRG.a\"+str(i))\n\n# create one ScriptTraceDiagram and add all ScriptTraceVariables to it\ntraceDiagram = traceObject.diagrams.add()\nfor traceVar in traceObject.variable_list:\n traceDiagram.add_diagram_variable(traceVar) " }, 
{ "title" : "创建一个 ScriptTrace per 的图表 ScriptTrace 变量 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737077515554", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 图表及其变量 \/ 创建一个 ScriptTrace per 的图表 ScriptTrace 变量 ", 
"snippet" : "以下 Python 方法需要一个 ScriptTrace 对象，然后为其添加一个图表 ScriptTrace 变量。 def one_diagram_per_variable(traceObject): assert traceObject.is_trace_object for traceVar in traceObject.variable_list: diagram = traceObject.diagrams.add(traceVar) diagram.name = traceVar.variable_name...", 
"body" : "以下 Python 方法需要一个 ScriptTrace 对象，然后为其添加一个图表 ScriptTrace 变量。 def one_diagram_per_variable(traceObject):\n assert traceObject.is_trace_object\n for traceVar in traceObject.variable_list:\n diagram = traceObject.diagrams.add(traceVar)\n diagram.name = traceVar.variable_name " }, 
{ "title" : "复制 a 的设置 ScriptTrace 示意图 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-8a9f24ff-4056-39eb-4996-c2e4c45b98e2", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 复制 a 的设置 ScriptTrace 示意图 ", 
"snippet" : "以下脚本显示如何修改和复制的设置 ScriptTrace 图表。 # we assume, that the traceObject already has multiple diagrams traceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0] assert traceObject.is_trace_object # apply settings for the first diagram traceObject.diagrams[0].y_axis.mode = AxisScal...", 
"body" : "以下脚本显示如何修改和复制的设置 ScriptTrace 图表。 # we assume, that the traceObject already has multiple diagrams\ntraceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0]\nassert traceObject.is_trace_object\n\n# apply settings for the first diagram\ntraceObject.diagrams[0].y_axis.mode = AxisScaleMode.FixedLength\ntraceObject.diagrams[0].y_axis.range = 10.0\ntraceObject.diagrams[0].y_axis.color = 0xffee0000\ntraceObject.diagrams[0].y_axis.draw_grid = True\ntraceObject.diagrams[0].y_axis.grid_color = 0xffee0000\ntraceObject.diagrams[0].tickmark_fixed_spacing = True\ntraceObject.diagrams[0].tickmark_fixed_distance = 5.0\ntraceObject.diagrams[0].tickmark_fixed_subdivisions = 4\n\n# copy the settings from the first diagrams to all other diagrams\nfor i in range(1,len(traceObject.diagrams))    \n traceObject.diagrams[i].y_axis.copy_from(traceObject.diagrams[0]) " }, 
{ "title" : "在线处理追踪 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-b432ef0d-fb60-07d4-552a-2c91ddb4f1f7", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 在线处理追踪 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "下载并开始追踪 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737089222798", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 在线处理追踪 \/ 下载并开始追踪 ", 
"snippet" : "以下代码片段找到 Trace 的踪迹 Application 应用程序，下载并启动它。 proj = projects.open(r\"<Path to the project file>\") app = proj.find(\"Device\", \"PLC Logic\", \"Application\")[0] with online.create_online_application(app) as onlineapp: traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] onlineapp.login(...", 
"body" : "以下代码片段找到 Trace 的踪迹 Application 应用程序，下载并启动它。 proj = projects.open(r\"<Path to the project file>\")\napp = proj.find(\"Device\", \"PLC Logic\", \"Application\")[0]\nwith online.create_online_application(app) as onlineapp:\n traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\n onlineapp.login(OnlineChangeOption.Never, True)\n onlineapp.start()\n editor = traceObject.open_editor()\n editor.download()\n editor.start() " }, 
{ "title" : "将跟踪记录保存在文件中 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737181972189", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 在线处理追踪 \/ 将跟踪记录保存在文件中 ", 
"snippet" : "以下代码片段基于 下载并开始追踪 片段。跟踪必须先停止，然后才能保存。这可以通过达到触发条件来完成，也可以通过显式调用 stop() 。 # We assume, that we have an already running trace editor.stop() editor.save(r\"<File path to csv file>\")...", 
"body" : "以下代码片段基于 下载并开始追踪 片段。跟踪必须先停止，然后才能保存。这可以通过达到触发条件来完成，也可以通过显式调用 stop() 。 # We assume, that we have an already running trace\neditor.stop()\neditor.save(r\"<File path to csv file>\") " }, 
{ "title" : "查询各种信息以进行跟踪记录 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737189210837", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 在线处理追踪 \/ 查询各种信息以进行跟踪记录 ", 
"snippet" : "以下代码片段基于 下载并开始追踪 片段。 # We assume, that we have an already running trace print(\"Packet State: {}\".format(editor.get_packet_state())) print(\"Trace started at {} (absolute timestamp)\".format(editor.get_trace_start_timetamp()))...", 
"body" : "以下代码片段基于 下载并开始追踪 片段。 # We assume, that we have an already running trace\nprint(\"Packet State: {}\".format(editor.get_packet_state()))\nprint(\"Trace started at {} (absolute timestamp)\".format(editor.get_trace_start_timetamp())) " }, 
{ "title" : "触发器处理 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-223bf514-9693-ae47-273f-2222b07b3394", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 触发器处理 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "配置一个 BOOL 触发 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737222218896", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 触发器处理 \/ 配置一个 BOOL 触发 ", 
"snippet" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] traceObject.trigger_variable = \"PLC_PRG.bVar\" traceObject.trigger_edge = TriggerEdge.Positive traceObject.post_trigger_samples = 20 # The trigger level is only needed for numeric trigger variables. It is a good coding style to...", 
"body" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\ntraceObject.trigger_variable = \"PLC_PRG.bVar\"\ntraceObject.trigger_edge = TriggerEdge.Positive\ntraceObject.post_trigger_samples = 20\n\n# The trigger level is only needed for numeric trigger variables. It is a good coding style to set the trigger explicitly to \"None\"\ntraceObject.trigger_level = None " }, 
{ "title" : "配置数字触发器 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737226322301", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 触发器处理 \/ 配置数字触发器 ", 
"snippet" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] traceObject.trigger_variable = \"PLC_PRG.iTemperature\" traceObject.trigger_edge = TriggerEdge.PositivetraceObject.post_trigger_samples = 20 # In case of a trigger variable of REAL or LREAL type it is also possible to specify fl...", 
"body" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\ntraceObject.trigger_variable = \"PLC_PRG.iTemperature\"\ntraceObject.trigger_edge = TriggerEdge.PositivetraceObject.post_trigger_samples = 20\n\n# In case of a trigger variable of REAL or LREAL type it is also possible to specify floating point trigger levels, e.g. 80.5\ntraceObject.trigger_level = 80 " }, 
{ "title" : "等待触发器并保存记录的数据 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737227937476", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 触发器处理 \/ 等待触发器并保存记录的数据 ", 
"snippet" : "以下代码片段基于 “配置 BOOL -triggers” 和 “配置*触发器” 片段。 triggerstate = editor.get_trigger_state() while triggerstate != TriggerState.TriggerReached: system.delay(200) triggerstate = editor.get_trigger_state() editor.save(r\"<File path to csv file>\")...", 
"body" : "以下代码片段基于 “配置 BOOL -triggers” 和 “配置*触发器” 片段。 triggerstate = editor.get_trigger_state()\nwhile triggerstate != TriggerState.TriggerReached:\n system.delay(200)\n triggerstate = editor.get_trigger_state()\n editor.save(r\"<File path to csv file>\") " }, 
{ "title" : "到达触发器后查询时间戳信息 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737235318186", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 触发器处理 \/ 到达触发器后查询时间戳信息 ", 
"snippet" : "以下代码片段基于 “配置 BOOL -Trigger” 和 “配置 * 触发器” 片段。 print(\"Trigger reached at {} (absolute timestamp)\".format(editor.get_trigger_timetamp())) print(\"Trigger reached at {}\".format(editor.get_trigger_startdate())) print(\"Trace was running {}ms until trigger has been reached\".format(editor.get_trigger_timetam...", 
"body" : "以下代码片段基于 “配置 BOOL -Trigger” 和 “配置 * 触发器” 片段。 print(\"Trigger reached at {} (absolute timestamp)\".format(editor.get_trigger_timetamp()))\nprint(\"Trigger reached at {}\".format(editor.get_trigger_startdate()))\nprint(\"Trace was running {}ms until trigger has been reached\".format(editor.get_trigger_timetamp() - editor.get_trace_start_timetamp())) " }, 
{ "title" : "到达触发器后恢复跟踪记录 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737241377252", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 触发器处理 \/ 到达触发器后恢复跟踪记录 ", 
"snippet" : "以下代码片段基于 “配置 BOOL -Trigger” 和 “配置 * 触发器” 片段。 editor.reset_trigger()...", 
"body" : "以下代码片段基于 “配置 BOOL -Trigger” 和 “配置 * 触发器” 片段。 editor.reset_trigger() " }, 
{ "title" : "设备跟踪 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-fb2803e2-9aa1-edc1-bfbe-5d0d052f53f0", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 设备跟踪 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "创建一个 DeviceTrace ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737244690592", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 设备跟踪 \/ 创建一个 DeviceTrace ", 
"snippet" : "myDevice = projects.primary.find(\"Device\")[0] devicetrace = trace.create(myDevice, \"DeviceTrace\")...", 
"body" : "myDevice = projects.primary.find(\"Device\")[0]\ndevicetrace = trace.create(myDevice, \"DeviceTrace\") " }, 
{ "title" : "查询设备当前的跟踪记录 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737246350891", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 设备跟踪 \/ 查询设备当前的跟踪记录 ", 
"snippet" : "以下代码片段基于 创建一个 片段。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0] # for application traces the result of get_online_traces contains only the traces of the application # traceObject = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] editor = traceObject.open_edi...", 
"body" : "以下代码片段基于 创建一个 片段。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0]\n\n# for application traces the result of get_online_traces contains only the traces of the application\n# traceObject = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\neditor = traceObject.open_editor()\nfor tracepacket in editor.get_online_traces():\n print(tracepacket) " }, 
{ "title" : "将现有录音下载到 DeviceTrace ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737250094566", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 设备跟踪 \/ 将现有录音下载到 DeviceTrace ", 
"snippet" : "以下代码片段基于 创建一个 片段。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0] editor = traceObject.open_editor() editor.upload_to_device_trace(\"CpuCoreLoad\")...", 
"body" : "以下代码片段基于 创建一个 片段。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0]\neditor = traceObject.open_editor()\neditor.upload_to_device_trace(\"CpuCoreLoad\") " }, 
{ "title" : "什么不适用于 DeviceTrace ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737269513402", 
"breadcrumbs" : "代码系统跟踪 \/ 使用跟踪脚本接口 \/ 设备跟踪 \/ 什么不适用于 DeviceTrace ", 
"snippet" : "访问权限 traceobject.variable_list 使用创建跟踪变量 traceobject.add_variable()) 访问权限  traceobject.diagrams...", 
"body" : "访问权限 traceobject.variable_list 使用创建跟踪变量 traceobject.add_variable()) 访问权限  traceobject.diagrams " }, 
{ "title" : "跟踪数据采样 ", 
"url" : "_cds_f_data_acquiring_with_trace.html", 
"breadcrumbs" : "代码系统跟踪 \/ 跟踪数据采样 ", 
"snippet" : "你可以使用一个 痕迹 以类似于数字采样示波器的方式跟踪控制器上变量的值曲线。在带有跟踪的应用程序运行时，所有语句都在任务周期内首先执行。然后，数据采样从包含时间戳的值存储开始。这些时间戳是相对的，指的是数据采样的开始时间。数据产生一个离散的时间信号和 CODESYS 在跟踪编辑器中显示其过程。 “样本”（数据记录）由值和时间戳组成。运行时系统将样本写入具有可定义大小的缓冲区。 CODESYS 请求数据，将其保存在跟踪编辑器缓冲区中，并将其作为时间函数显示在跟踪图中。您可以持续监控已配置变量的值曲线，因为 CODESYS 显示最新数据。 您可以为数据采样提供触发器。释放触发后，数据采样停止，数据...", 
"body" : "你可以使用一个 痕迹 以类似于数字采样示波器的方式跟踪控制器上变量的值曲线。在带有跟踪的应用程序运行时，所有语句都在任务周期内首先执行。然后，数据采样从包含时间戳的值存储开始。这些时间戳是相对的，指的是数据采样的开始时间。数据产生一个离散的时间信号和 CODESYS 在跟踪编辑器中显示其过程。 “样本”（数据记录）由值和时间戳组成。运行时系统将样本写入具有可定义大小的缓冲区。 CODESYS 请求数据，将其保存在跟踪编辑器缓冲区中，并将其作为时间函数显示在跟踪图中。您可以持续监控已配置变量的值曲线，因为 CODESYS 显示最新数据。 您可以为数据采样提供触发器。释放触发后，数据采样停止，数据显示在触发时间前后。 轨迹的配置和显示可以在 CODESYS 通过跟踪编辑器中的跟踪对象进行项目。有以下两种对象类型： 痕迹 ：插入到设备树中的 IEC 应用程序下方。这种对象始终包含严格的特定于应用程序的跟踪配置。您可以将此跟踪配置下载到控制器并使用应用程序运行它。 设备跟踪 ：插入到设备树中的设备对象下方。如果 PLC 支持“跟踪管理器”，那么您可以使用一个或多个 设备跟踪 对象来访问在控制器上运行的一个或多个跟踪。这些可以是特定于应用程序或特定于控制器的跟踪。例如，控制器可以支持用于记录处理器负载的跟踪。菜单命令允许从 CODESYS 项目到设备中的跟踪管理器。 可以通过库中的函数从 IEC 代码访问跟踪管理器 CmpTraceMgr.library .有关详细信息，请参阅库文档。 带有跟踪的运行数据采样会导致 IEC 任务的循环时间显着增加。 退出设备后，带有跟踪的数据采样也会继续运行。 " }, 
{ "title" : "运行时系统组件 CmpTraceMgr，跟踪管理器 ", 
"url" : "_cds_f_data_acquiring_with_trace.html#UUID-1a20cc11-9b69-5f7f-6e67-22845545c8e9_section-idm4654689515584032658315282356", 
"breadcrumbs" : "代码系统跟踪 \/ 跟踪数据采样 \/ 运行时系统组件 CmpTraceMgr，跟踪管理器 ", 
"snippet" : "带有跟踪管理器的运行时系统的设备描述包括 tracemanager 进入 TargetSettings 部分。 在这种情况下， CODESYS 将应用程序下载到 PLC 时仅传输跟踪配置。当您启动跟踪时，应用程序通过跟踪管理器解释 RTS 上的配置，执行数据采样，并在控制器上缓冲数据集。 这 CmpTraceMgr 与使用 IEC 代码进行数据采样相比，运行时系统组件提供了扩展功能。 因此，数据采样可能如下： 控制器上的参数（例如，处理器负载（cpuload、plcload），或者CPU或电池的温度曲线） 每个处理器核心的处理器负载 (cpuload) 的测量对于多核控制器来说很有趣。 设备信...", 
"body" : "带有跟踪管理器的运行时系统的设备描述包括 tracemanager 进入 TargetSettings 部分。 在这种情况下， CODESYS 将应用程序下载到 PLC 时仅传输跟踪配置。当您启动跟踪时，应用程序通过跟踪管理器解释 RTS 上的配置，执行数据采样，并在控制器上缓冲数据集。 这 CmpTraceMgr 与使用 IEC 代码进行数据采样相比，运行时系统组件提供了扩展功能。 因此，数据采样可能如下： 控制器上的参数（例如，处理器负载（cpuload、plcload），或者CPU或电池的温度曲线） 每个处理器核心的处理器负载 (cpuload) 的测量对于多核控制器来说很有趣。 设备信号（例如，驱动器的当前路径） 另一个运行时系统组件的系统变量 您可以在 跟踪配置 的对话框 变量设置 . 可以在 DeviceTrace 对象的跟踪编辑器中显示在控制器上运行的跟踪。 " }, 
{ "title" : "触发后数据采样 ", 
"url" : "_cds_f_data_acquiring_with_trace.html#UUID-1a20cc11-9b69-5f7f-6e67-22845545c8e9_section-idm453808684926243265831687739", 
"breadcrumbs" : "代码系统跟踪 \/ 跟踪数据采样 \/ 触发后数据采样 ", 
"snippet" : "要监视依赖于事件或条件的数据，您可以释放依赖于触发器的数据采样。在运行时，应用程序检查事件是否发生或条件是否满足，然后相应地缓冲数据。 跟踪配置允许通过以下方式触发： 映射事件的触发器变量 作为表达式的条件 触发变量和条件的组合...", 
"body" : "要监视依赖于事件或条件的数据，您可以释放依赖于触发器的数据采样。在运行时，应用程序检查事件是否发生或条件是否满足，然后相应地缓冲数据。 跟踪配置允许通过以下方式触发： 映射事件的触发器变量 作为表达式的条件 触发变量和条件的组合 " }, 
{ "title" : "将样本保存到文件 ", 
"url" : "_cds_f_data_acquiring_with_trace.html#UUID-1a20cc11-9b69-5f7f-6e67-22845545c8e9_section-idm4654689527510432658318271731", 
"breadcrumbs" : "代码系统跟踪 \/ 跟踪数据采样 \/ 将样本保存到文件 ", 
"snippet" : "您可以将开发系统中的示例保存到文件中。该文件还可以包含跟踪配置。 可能的文件格式 文件扩展名 文件类型 描述 *.trace ： 跟踪文件 包含 XML 格式的示例和跟踪配置 您可以执行 负载跟踪 命令在离线时将文件加载到跟踪编辑器并在没有 PLC 的情况下分析样品。 *.txt 文本文件 包含 ASCII 格式的样本 您可以使用外部工具编辑文件。 *.trace.csv 跟踪转储 CSV 格式的文件包括跟踪配置和可选示例 您可以通过单击创建文件 导出符号跟踪配置 .您可以将文件传输到 PLC 并将其加载到应用程序中。然后，执行 负载跟踪 命令在 CODESYS 在跟踪编辑器中显示它。 您也可...", 
"body" : "您可以将开发系统中的示例保存到文件中。该文件还可以包含跟踪配置。 可能的文件格式 文件扩展名 文件类型 描述 *.trace ： 跟踪文件 包含 XML 格式的示例和跟踪配置 您可以执行 负载跟踪 命令在离线时将文件加载到跟踪编辑器并在没有 PLC 的情况下分析样品。 *.txt 文本文件 包含 ASCII 格式的样本 您可以使用外部工具编辑文件。 *.trace.csv 跟踪转储 CSV 格式的文件包括跟踪配置和可选示例 您可以通过单击创建文件 导出符号跟踪配置 .您可以将文件传输到 PLC 并将其加载到应用程序中。然后，执行 负载跟踪 命令在 CODESYS 在跟踪编辑器中显示它。 您也可以点击 跟踪 → 保存跟踪 并选择 *.trace.csv 文件格式。您可以将文件传输到 PLC 并使用 HMI 加载它以进行分析。 *.traceconfig 符号跟踪配置 包含跟踪配置 CSV 格式 您可以通过单击创建文件 导出符号跟踪配置 .这 CmpTraceMgr 运行时系统组件可以读取该文件。 有关更多信息，请参阅： 跟踪" }, 
{ "title" : "入门 ", 
"url" : "_cds_trace_getting_started.html", 
"breadcrumbs" : "代码系统跟踪 \/ 入门 ", 
"snippet" : "程序 PLC_PRG PROGRAM PLC_PRG VAR iVar : INT; rSin : REAL; rVar : REAL; END_VAR iVar := iVar + 1; iVar := iVar MOD 33; rVar := rVar + 0.1; rSin := 30 * SIN(rVar); 要求：应用程序正在运行 PLC_PRG PLC 上的程序。 在设备树中，选择应用程序并单击 项目 → 添加对象 添加一个新的跟踪对象。 相应的跟踪编辑器将打开，其中包含 痕迹 菜单。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。 选择一个任务来运行跟踪功能。通常这与在 P...", 
"body" : "程序 PLC_PRG PROGRAM PLC_PRG\nVAR\n iVar : INT;\n rSin : REAL;\n rVar : REAL;\nEND_VAR\n\niVar := iVar + 1;\niVar := iVar MOD 33;\n\nrVar := rVar + 0.1;\nrSin := 30 * SIN(rVar); 要求：应用程序正在运行 PLC_PRG PLC 上的程序。 在设备树中，选择应用程序并单击 项目 → 添加对象 添加一个新的跟踪对象。 相应的跟踪编辑器将打开，其中包含 痕迹 菜单。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。 选择一个任务来运行跟踪功能。通常这与在 PLC_PRG 中运行的任务相同。 点击 添加变量 将条目添加到跟踪配置的树视图并分配 IEC 变量。 例子： PLC_PRG.rSin 点击 跟踪 → 下载跟踪 . CODESYS 将跟踪配置下载到控制器。应用程序开始数据采样并将数据传输到 CODESYS .然后它们在跟踪图中显示为图形。提供了用于浏览样本和控制数据采样的命令。 " }, 
{ "title" : "例子 ", 
"url" : "_cds_trace_getting_started.html#UUID-aa78deb4-8651-3794-2c7e-8126bafa7518_id_b64f3dddb917bc0a8640e01d1209e_id_1ecec4e8ed18f2ddc0a8655f018aaa35", 
"breadcrumbs" : "代码系统跟踪 \/ 入门 \/ 例子 ", 
"snippet" : "跟踪 IEC 变量的正弦值历史 PLC_PRG.rSin 这 PLC_PRG 程序正在控制器上运行。当您按照“入门”的说明进行操作时， CODESYS 显示以下跟踪图。 (1): 配置 (2): 添加变量...", 
"body" : "跟踪 IEC 变量的正弦值历史 PLC_PRG.rSin 这 PLC_PRG 程序正在控制器上运行。当您按照“入门”的说明进行操作时， CODESYS 显示以下跟踪图。 (1): 配置 (2): 添加变量 " }, 
{ "title" : "创建跟踪配置 ", 
"url" : "_cds_trace_configuring.html", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 ", 
"snippet" : "对于完整的跟踪配置，请至少指定一个任务和一个变量。为了触发数据采样，激活触发选项并选择触发变量或指定记录条件。 在运行时编辑跟踪配置 要求：应用程序正在控制器上运行，并且已加载跟踪配置。 双击跟踪记录树中的变量。 这 跟踪配置 对话框打开。 例如，更改颜色。 变量在受影响的图表中以新颜色显示，而不会中断应用程序的执行。 如果您更改基本设置，例如跟踪变量，则必须再次将跟踪配置下载到控制器。...", 
"body" : "对于完整的跟踪配置，请至少指定一个任务和一个变量。为了触发数据采样，激活触发选项并选择触发变量或指定记录条件。 在运行时编辑跟踪配置 要求：应用程序正在控制器上运行，并且已加载跟踪配置。 双击跟踪记录树中的变量。 这 跟踪配置 对话框打开。 例如，更改颜色。 变量在受影响的图表中以新颜色显示，而不会中断应用程序的执行。 如果您更改基本设置，例如跟踪变量，则必须再次将跟踪配置下载到控制器。 " }, 
{ "title" : "分配任务 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_ea9cb39d8cc911e3bb368b4e89ceab52", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 分配任务 ", 
"snippet" : "在此任务中，数据采样在运行时执行。通常在写入变量的地方选择相同的任务。 双击跟踪对象。 跟踪编辑器将打开，其中包含 痕迹 菜单。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。在里面 追踪记录 树视图，顶部的项目被选中，并且 记录设置 子对话框显示在右侧。 在里面 任务 列表框，单击 象征。 列表框将打开，其中包含整个应用程序中可用的所有任务。 为跟踪选择一个任务。...", 
"body" : "在此任务中，数据采样在运行时执行。通常在写入变量的地方选择相同的任务。 双击跟踪对象。 跟踪编辑器将打开，其中包含 痕迹 菜单。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。在里面 追踪记录 树视图，顶部的项目被选中，并且 记录设置 子对话框显示在右侧。 在里面 任务 列表框，单击 象征。 列表框将打开，其中包含整个应用程序中可用的所有任务。 为跟踪选择一个任务。 " }, 
{ "title" : "配置跟踪变量 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_8fd85a9b8cca11e3bb368b4e89ceab52", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 配置跟踪变量 ", 
"snippet" : "双击跟踪对象。 跟踪编辑器打开。的命令 痕迹 菜单可用。 点击 添加变量 . 这 跟踪配置 对话框打开。这 变量设置 子对话框显示在右侧。 在输入框的 多变的 设置，点击 并且在 输入助手 对话框选择一个跟踪变量。 该变量配置用于数据采样。跟踪记录树和显示树由变量扩展。 点击 添加变量 关联。 跟踪记录树和显示树接收一个新变量。变量的设置在右侧可用。 选择一个跟踪变量。 点击 行 退出对话框。 这些变量是跟踪变量，并显示在跟踪变量列表中。...", 
"body" : "双击跟踪对象。 跟踪编辑器打开。的命令 痕迹 菜单可用。 点击 添加变量 . 这 跟踪配置 对话框打开。这 变量设置 子对话框显示在右侧。 在输入框的 多变的 设置，点击 并且在 输入助手 对话框选择一个跟踪变量。 该变量配置用于数据采样。跟踪记录树和显示树由变量扩展。 点击 添加变量 关联。 跟踪记录树和显示树接收一个新变量。变量的设置在右侧可用。 选择一个跟踪变量。 点击 行 退出对话框。 这些变量是跟踪变量，并显示在跟踪变量列表中。 " }, 
{ "title" : "删除跟踪变量 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_a2de7471341611e4aaeacbabfc46bd6b", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 删除跟踪变量 ", 
"snippet" : "双击跟踪对象。 单击跟踪记录树中的变量。 点击 删除变量 或按 德尔 . 点击 行 退出对话框。 该变量将从跟踪变量列表中删除。...", 
"body" : "双击跟踪对象。 单击跟踪记录树中的变量。 点击 删除变量 或按 德尔 . 点击 行 退出对话框。 该变量将从跟踪变量列表中删除。 " }, 
{ "title" : "跟踪参数 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_24994be39fc411e4ac0cf998f94f5673", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 跟踪参数 ", 
"snippet" : "双击跟踪对象。 点击 添加变量 . 这 跟踪配置 对话框打开。这 变量设置 子对话框显示在右侧。 点击 （在右侧 多变的 设置，在输入字段的左侧）。 选择 范围 列表框中的选项。 点击 并从 输入助手 对话。 配置参数的显示方式。 点击 行 退出对话框。 该参数将被跟踪并显示在跟踪变量列表中。...", 
"body" : "双击跟踪对象。 点击 添加变量 . 这 跟踪配置 对话框打开。这 变量设置 子对话框显示在右侧。 点击 （在右侧 多变的 设置，在输入字段的左侧）。 选择 范围 列表框中的选项。 点击 并从 输入助手 对话。 配置参数的显示方式。 点击 行 退出对话框。 该参数将被跟踪并显示在跟踪变量列表中。 " }, 
{ "title" : "配置触发器 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_f9249f7c1ba811e49e4c9341d3e603a5", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 配置触发器 ", 
"snippet" : "双击跟踪对象。 跟踪编辑器打开，其中包含可用的命令 痕迹 菜单。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。这 记录设置 子对话框显示在右侧。 选择 启用触发器 复选框。 选择要执行趋势记录的任务。 从变量中选择一个 触发变量 场地。 点击 行 退出对话框。 将触发数据采样。 触发时间在运行时在图表中显示为黑线。 下载应用程序并启动它。 点击 跟踪 → 跟踪下载 . 已加载跟踪配置。触发后，运行时系统保存跟踪变量的值图。数据显示在跟踪编辑器中。触发时间在图中显示为黑线。...", 
"body" : "双击跟踪对象。 跟踪编辑器打开，其中包含可用的命令 痕迹 菜单。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。这 记录设置 子对话框显示在右侧。 选择 启用触发器 复选框。 选择要执行趋势记录的任务。 从变量中选择一个 触发变量 场地。 点击 行 退出对话框。 将触发数据采样。 触发时间在运行时在图表中显示为黑线。 下载应用程序并启动它。 点击 跟踪 → 跟踪下载 . 已加载跟踪配置。触发后，运行时系统保存跟踪变量的值图。数据显示在跟踪编辑器中。触发时间在图中显示为黑线。 " }, 
{ "title" : "配置时间轴的显示 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_b54f86141bac11e49e4c9341d3e603a5", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 配置时间轴的显示 ", 
"snippet" : "双击跟踪对象。 点击 配置 配置树上方的链接。 这 跟踪配置 对话框打开。 选择 时间轴 在显示树中（下面 演示文稿（图表） ）。 时间轴的显示设置如右图所示。 编辑预设并单击 预览 关联。 更改显示在坐标系预览中。 点击 Y轴 在显示树中。这 Y轴 项目在每个配置的图表下方。因此，为每个图表设置了数值轴的显示。 这 显示设置 所选轴的子对话框显示在右侧。 更改预设值。 更改将应用在坐标系预览中。 点击确定退出 跟踪配置 对话。 显示更改在受影响的图表中可见。...", 
"body" : "双击跟踪对象。 点击 配置 配置树上方的链接。 这 跟踪配置 对话框打开。 选择 时间轴 在显示树中（下面 演示文稿（图表） ）。 时间轴的显示设置如右图所示。 编辑预设并单击 预览 关联。 更改显示在坐标系预览中。 点击 Y轴 在显示树中。这 Y轴 项目在每个配置的图表下方。因此，为每个图表设置了数值轴的显示。 这 显示设置 所选轴的子对话框显示在右侧。 更改预设值。 更改将应用在坐标系预览中。 点击确定退出 跟踪配置 对话。 显示更改在受影响的图表中可见。 " }, 
{ "title" : "配置跟踪变量的显示 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_df387bd88cca11e3bb368b4e89ceab52", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 配置跟踪变量的显示 ", 
"snippet" : "双击跟踪对象。 点击 配置 关联。 这 跟踪配置 对话框打开。 在下面选择一个变量 追踪记录 . 这 变量设置 所选变量的子对话框显示在右侧。 更改设置，例如 线型 . 点击 行 退出对话框。 显示更改在受影响的图表中可见。...", 
"body" : "双击跟踪对象。 点击 配置 关联。 这 跟踪配置 对话框打开。 在下面选择一个变量 追踪记录 . 这 变量设置 所选变量的子对话框显示在右侧。 更改设置，例如 线型 . 点击 行 退出对话框。 显示更改在受影响的图表中可见。 " }, 
{ "title" : "在运行时配置数据缓冲区 ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_30b2fca40b4611e48be4a888be20ac74", 
"breadcrumbs" : "代码系统跟踪 \/ 创建跟踪配置 \/ 在运行时配置数据缓冲区 ", 
"snippet" : "双击跟踪对象。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。这 记录设置 子对话框显示在右侧。 点击 先进的 . 这 高级跟踪设置 对话框打开。 更改设置 每第 n 个周期测量一次 或者 推荐的运行时缓冲区大小（样本） . 点击 行 退出对话框。 缓冲区设置被重新配置。它在下次将跟踪配置加载到 RTS 后应用。...", 
"body" : "双击跟踪对象。 点击 跟踪 → 配置 . 这 跟踪配置 对话框打开。这 记录设置 子对话框显示在右侧。 点击 先进的 . 这 高级跟踪设置 对话框打开。 更改设置 每第 n 个周期测量一次 或者 推荐的运行时缓冲区大小（样本） . 点击 行 退出对话框。 缓冲区设置被重新配置。它在下次将跟踪配置加载到 RTS 后应用。 " }, 
{ "title" : "控制数据采样 ", 
"url" : "_cds_trace_controlling_the_data_acquiring.html", 
"breadcrumbs" : "代码系统跟踪 \/ 控制数据采样 ", 
"snippet" : "使用菜单命令控制数据的记录方式。 要求：应用程序已加载到运行时系统并配置了跟踪。 菜单命令 追踪 → 下载跟踪 追踪 → 开始跟踪 追踪 → 停止跟踪 追踪 → 重置触发器...", 
"body" : "使用菜单命令控制数据的记录方式。 要求：应用程序已加载到运行时系统并配置了跟踪。 菜单命令 追踪 → 下载跟踪 追踪 → 开始跟踪 追踪 → 停止跟踪 追踪 → 重置触发器 " }, 
{ "title" : "访问控制器上的所有跟踪 ", 
"url" : "_cds_trace_accessing_them_all_on_the_control.html", 
"breadcrumbs" : "代码系统跟踪 \/ 访问控制器上的所有跟踪 ", 
"snippet" : "如果控制器支持运行时组件 CmpTraceMgr （跟踪管理器），然后您可以从一个 CODESYS 在控制器上运行的项目。除了捕获 IEC 变量值的应用相关跟踪之外，这些跟踪也可以是严格的控制器特定跟踪（例如，用于记录设备信号值或 CPU 负载）。 对于要在项目中显示的控制器上运行的每个跟踪，您必须插入一个单独的 设备跟踪 设备树中的对象。 为了在此对象中显示来自设备的跟踪，必须正确配置与 PLC 的连接（ 通讯设置 ）。然后使用以下菜单命令之一： 追踪 → 上传跟踪 ：建立与 PLC 的连接并打开 在线列表 用于从控制器中选择轨迹的对话框 追踪 → 在线列表 ：仅在线模式下可用；也打开了 在...", 
"body" : "如果控制器支持运行时组件 CmpTraceMgr （跟踪管理器），然后您可以从一个 CODESYS 在控制器上运行的项目。除了捕获 IEC 变量值的应用相关跟踪之外，这些跟踪也可以是严格的控制器特定跟踪（例如，用于记录设备信号值或 CPU 负载）。 对于要在项目中显示的控制器上运行的每个跟踪，您必须插入一个单独的 设备跟踪 设备树中的对象。 为了在此对象中显示来自设备的跟踪，必须正确配置与 PLC 的连接（ 通讯设置 ）。然后使用以下菜单命令之一： 追踪 → 上传跟踪 ：建立与 PLC 的连接并打开 在线列表 用于从控制器中选择轨迹的对话框 追踪 → 在线列表 ：仅在线模式下可用；也打开了 在线列表 对话 现在从控制器上传的跟踪可以在 DeviceTrace 对象的编辑器中启动和跟踪。演示文稿的配置（颜色、标签等）与项目中配置的应用程序变量的跟踪相同。 关闭 DeviceTrace 编辑器会终止与控制器的连接。 请注意，与控制器的连接也会在最后一次打开时终止 设备跟踪 编辑器已关闭。为了在项目中再次显示设备跟踪，您必须将它们重新加载到 设备跟踪 对象。 目前，关闭编辑器也是故意终止与控制器的连接的推荐方式。注销是不够的。 使用 DeviceTrace 对象显示 CPU 负载 CODESYS 项目（示例） 要求：PLC 设备支持跟踪管理器。对于此处描述的示例，这是 CODESYS Control Win .该设备提供单个 CPU 负载的跟踪（ CpuLoad )，以及运行时造成的 CPU 负载痕迹 ( PlcLoad ）。使用多核功能时，项目中可能显示的 CPU 负载可能会有所帮助。 在项目中，定义 通讯设置 为控制器。 在设备树中选择 PLC 条目并添加一个 设备跟踪 目的。 改名 设备跟踪 到“Trace_PlcLoad”（ 特性 ）。 在跟踪编辑器中设置焦点并单击 跟踪 → 上传跟踪 . 与控制器的连接已建立，并且 在线列表 对话框打开。 在对话框中，选择 加载程序 输入并点击 上传 .单击确定关闭对话框。 跟踪编辑器中打开多个跟踪视图以显示运行时的 CPU 负载。这些是单个 CPU 的轨迹和平均值的轨迹。每个都显示以下文本：“未记录样本。” 点击 跟踪 → 开始跟踪 . 显示四个参数的跟踪记录。 如果您还想显示 CpuLoad 每个 CPU 及其在项目中的平均值，然后插入另一个 设备跟踪 对象进入设备树。例如，将其命名为“Trace_CpuLoad”。加载并启动跟踪 处理器负载 在如上所述的编辑器中。 现在您可以监控项目中的所有跟踪： 如果要更改演示文稿的外观，请单击 配置 在相应的跟踪编辑器窗口中访问配置对话框。您可以按照与在项目中创建的 IEC 变量跟踪相同的方式使用这些对话框（变量分配除外）。 要断开与控制器的连接，请关闭所有打开的 DeviceTrace 编辑器窗口。如果您已登录到设备，则注销足以终止连接。 " }, 
{ "title" : "导航到跟踪数据 ", 
"url" : "_cds_trace_navigating_in_the_data.html", 
"breadcrumbs" : "代码系统跟踪 \/ 导航到跟踪数据 ", 
"snippet" : "使用菜单命令导航跟踪图中的数据。 要求：应用程序处于在线模式。 菜单命令 追踪 → 光标 追踪 → 鼠标缩放 追踪 → 重置视图 追踪 → 自动调整 追踪 → 压缩 追踪 → 拉紧 追踪 → 转换为单通道 追踪 → 转换为多通道...", 
"body" : "使用菜单命令导航跟踪图中的数据。 要求：应用程序处于在线模式。 菜单命令 追踪 → 光标 追踪 → 鼠标缩放 追踪 → 重置视图 追踪 → 自动调整 追踪 → 压缩 追踪 → 拉紧 追踪 → 转换为单通道 追踪 → 转换为多通道 " }, 
{ "title" : "管理跟踪 ", 
"url" : "_cds_trace_managing_data.html", 
"breadcrumbs" : "代码系统跟踪 \/ 管理跟踪 ", 
"snippet" : "使用菜单命令以各种格式加载和保存轨迹。 菜单命令 追踪 → 保存跟踪 追踪 → 负载跟踪 追踪 → 导出符号跟踪配置...", 
"body" : "使用菜单命令以各种格式加载和保存轨迹。 菜单命令 追踪 → 保存跟踪 追踪 → 负载跟踪 追踪 → 导出符号跟踪配置 " }, 
{ "title" : "显示统计信息 ", 
"url" : "_cds_trace_displaying_statistic.html", 
"breadcrumbs" : "代码系统跟踪 \/ 显示统计信息 ", 
"snippet" : "CODESYS 使用将数据保存到剪贴板的选项评估并显示采样数据。点击 追踪 → 统计数据 ....", 
"body" : "CODESYS 使用将数据保存到剪贴板的选项评估并显示采样数据。点击 追踪 → 统计数据 . " }, 
{ "title" : "参考：用户界面 ", 
"url" : "_trace_reference_user_interface.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对象 ", 
"url" : "_trace_objects.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对象：跟踪 ", 
"url" : "_cds_obj_trace.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 \/ 对象：跟踪 ", 
"snippet" : "跟踪 象征： 类型的对象 痕迹 用于在一个或多个图表中配置和显示特定于应用程序的跟踪数据。在应用程序运行时，跟踪变量的值曲线，您可以在跟踪编辑器中的 CODESYS 在此期间，记录在控制器上。要求是已将跟踪配置传输到控制器，并且已开始跟踪记录。采样数据传输到开发系统并根据配置以图表形式显示。您可以在跟踪时浏览数据。 欲了解更多信息，请参阅： 跟踪数据采样如果控制器支持跟踪管理器，那么您可以使用 ' 设备跟踪 ' 跟踪管理器中的对象类型，用于访问控制器上运行的所有跟踪。 双击跟踪对象打开跟踪编辑器。相应的工具栏包含最重要的跟踪命令。跟踪变量列表显示其值曲线被记录的变量。 (1)：轨迹编辑器的工具...", 
"body" : "跟踪 象征： 类型的对象 痕迹 用于在一个或多个图表中配置和显示特定于应用程序的跟踪数据。在应用程序运行时，跟踪变量的值曲线，您可以在跟踪编辑器中的 CODESYS 在此期间，记录在控制器上。要求是已将跟踪配置传输到控制器，并且已开始跟踪记录。采样数据传输到开发系统并根据配置以图表形式显示。您可以在跟踪时浏览数据。 欲了解更多信息，请参阅： 跟踪数据采样如果控制器支持跟踪管理器，那么您可以使用 ' 设备跟踪 ' 跟踪管理器中的对象类型，用于访问控制器上运行的所有跟踪。 双击跟踪对象打开跟踪编辑器。相应的工具栏包含最重要的跟踪命令。跟踪变量列表显示其值曲线被记录的变量。 (1)：轨迹编辑器的工具栏 (2)：轨迹编辑器 (3)：跟踪变量列表 (4)：trace配置的链接 配置 添加变量 " }, 
{ "title" : "轨迹编辑器的工具栏 ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_9c96894e3a54c71fc0a8653601c0734d", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 \/ 对象：跟踪 \/ 轨迹编辑器的工具栏 ", 
"snippet" : "： 下载跟踪： 开始跟踪： 停止追踪： 重置触发器： 用鼠标缩放 ： 重置视图： 自动缩放： 光标： 压缩： 拉紧...", 
"body" : "： 下载跟踪： 开始跟踪： 停止追踪： 重置触发器： 用鼠标缩放 ： 重置视图： 自动缩放： 光标： 压缩： 拉紧" }, 
{ "title" : "跟踪编辑器 ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_1e6f1b31635a8e3ac0a8640e016cc6dd", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 \/ 对象：跟踪 \/ 跟踪编辑器 ", 
"snippet" : "在应用程序运行时，跟踪组件的运行时系统缓冲区被记录的样本填充。数据被传输到开发系统并存储在其跟踪编辑器缓冲区中。跟踪编辑器访问此数据并将其显示在图表中随着时间的推移。当您关闭跟踪编辑器时，跟踪编辑器缓冲区将再次被释放。 有关更多信息，请参阅： 控制数据采样使用菜单命令来控制跟踪。此外，您可以使用菜单命令、键盘快捷键和鼠标输入来浏览数据。 有关更多信息，请参阅： 导航到跟踪数据...", 
"body" : "在应用程序运行时，跟踪组件的运行时系统缓冲区被记录的样本填充。数据被传输到开发系统并存储在其跟踪编辑器缓冲区中。跟踪编辑器访问此数据并将其显示在图表中随着时间的推移。当您关闭跟踪编辑器时，跟踪编辑器缓冲区将再次被释放。 有关更多信息，请参阅： 控制数据采样使用菜单命令来控制跟踪。此外，您可以使用菜单命令、键盘快捷键和鼠标输入来浏览数据。 有关更多信息，请参阅： 导航到跟踪数据" }, 
{ "title" : "跟踪变量列表 ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_330149a30c689227c0a864631a27b88d", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 \/ 对象：跟踪 \/ 跟踪变量列表 ", 
"snippet" : "跟踪变量列表提供了当前跟踪配置的概览。在列表中，具有相应跟踪变量的所有图表都显示在表格中。双击跟踪变量时， 跟踪配置 对话框也会打开变量设置。 列表框通过 隐藏实例路径 命令。 隐藏实例路径 在列表中显示变量名 ：具有完整实例路径的变量名 例子： PLC_PRG.iCounter 图表 图表的表格显示 姓名 带有相应变量的图表列表 图表 <n> : 显示图表。 通过单击所选名称可以更改图表名称。 <变量> ：显示变量。 可以通过在行编辑器中单击所选名称来更改变量名称。 当您选择一个 图表 <n> 在表格中，相应的图表也在编辑器中被选中。这也适用于相反的方式。 光标 <n> 光标位置的 Y 值 ...", 
"body" : "跟踪变量列表提供了当前跟踪配置的概览。在列表中，具有相应跟踪变量的所有图表都显示在表格中。双击跟踪变量时， 跟踪配置 对话框也会打开变量设置。 列表框通过 隐藏实例路径 命令。 隐藏实例路径 在列表中显示变量名 ：具有完整实例路径的变量名 例子： PLC_PRG.iCounter 图表 图表的表格显示 姓名 带有相应变量的图表列表 图表 <n> : 显示图表。 通过单击所选名称可以更改图表名称。 <变量> ：显示变量。 可以通过在行编辑器中单击所选名称来更改变量名称。 当您选择一个 图表 <n> 在表格中，相应的图表也在编辑器中被选中。这也适用于相反的方式。 光标 <n> 光标位置的 Y 值 三角洲 Y 值的增量来自 光标 2 到 光标 1 多选 通过多选，您可以使用数字键盘键 * 和 \/ 展开和折叠选定的图表。 您可以拖动图表和变量对其进行排序或将它们移动到其他图表。当。。。的时候 Ctrl 键被按下，变量被复制。这在在线模式下也是可能的。 跟踪变量列表中的上下文菜单 添加变量 添加一个新的跟踪变量并打开 跟踪配置 带有变量设置的对话框 在输入框中选择一个变量 多变的 设置跟踪其价值曲线。 可见的 在相应图表中切换图表（值曲线或轨迹变量）的可见性： ： 可见的 : 隐藏 当通过多选在跟踪变量列表中选择多个图表或变量时，可以切换这些图表的可见性。 显示模式 打开 跟踪配置 对话 选择一个配置项 追踪记录 树视图或 演示文稿（图表） . 配置 打开 跟踪配置 对话 这 变量设置 显示在右侧。 " }, 
{ "title" : "在跟踪图中导航 ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_816e2c47117e11e49907a46cfb48b36f", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 \/ 对象：跟踪 \/ 在跟踪图中导航 ", 
"snippet" : "用鼠标输入 用户用鼠标输入 用户输入期间的鼠标光标符号 影响 沿 X 轴拖动图形。 沿时间轴（X 轴）同时滚动所有图表的轨迹图 按住 Ctrl 键并沿 Y 轴拖动图形。 沿 Y 轴滚动选定图表的跟踪图 向后滚动鼠标滚轮。 压缩时间轴（如 象征） 向前滚动鼠标滚轮。 拉伸时间轴（如 象征） 按住 Ctrl 键并向后滚动鼠标滚轮。 压缩 Y 轴 按住 Ctrl 键并向前滚动鼠标滚轮。 拉伸 Y 轴 要求：激活一个或两个跟踪游标。 将跟踪光标的三角形沿时间轴拖动到另一个位置。 同时刷新跟踪变量列表中的 Y 值 第一个值：左侧光标位置的 Y 值 第二个值：右光标位置的Y值 第三个值：两个值之间的差异 ...", 
"body" : "用鼠标输入 用户用鼠标输入 用户输入期间的鼠标光标符号 影响 沿 X 轴拖动图形。 沿时间轴（X 轴）同时滚动所有图表的轨迹图 按住 Ctrl 键并沿 Y 轴拖动图形。 沿 Y 轴滚动选定图表的跟踪图 向后滚动鼠标滚轮。 压缩时间轴（如 象征） 向前滚动鼠标滚轮。 拉伸时间轴（如 象征） 按住 Ctrl 键并向后滚动鼠标滚轮。 压缩 Y 轴 按住 Ctrl 键并向前滚动鼠标滚轮。 拉伸 Y 轴 要求：激活一个或两个跟踪游标。 将跟踪光标的三角形沿时间轴拖动到另一个位置。 同时刷新跟踪变量列表中的 Y 值 第一个值：左侧光标位置的 Y 值 第二个值：右光标位置的Y值 第三个值：两个值之间的差异 要求： 鼠标缩放 被激活（ ）。 拉伸一个矩形。 将所有图表的轨迹图缩放到矩形 使用键盘快捷键 键盘快捷键 影响 要求：未激活跟踪光标模式。 向左箭头 向右箭头 沿时间轴同时滚动所有图表的轨迹图 向上箭头 向下箭头 沿 Y 轴滚动选定图表的跟踪图 要求：激活一个或两个跟踪游标。 Alt + 向左箭头 Alt + 向右箭头 沿时间轴同时滚动所有图表的轨迹图 - 压缩时间轴（如 象征） + 拉伸 X 轴（如 象征） Ctrl + - 压缩所选图表的 Y 轴 Ctrl + + 拉伸选定图表的 Y 轴 标签 选择下一个较低的图表 要求：激活一个或两个跟踪游标。 向左箭头 向右箭头 移动黑色轨迹光标 要求：激活了两个跟踪游标。 转移 + 向左箭头 转移 + 向右箭头 移动灰色轨迹光标 " }, 
{ "title" : "对象：设备跟踪 ", 
"url" : "_cds_obj_devicetrace.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对象 \/ 对象：设备跟踪 ", 
"snippet" : "DeviceTrace 象征： 一种 设备跟踪 对象在一个或多个图表中显示跟踪数据，与 痕迹 目的。 不同的是，一个 设备跟踪 直接地 访问 在控制器上运行的跟踪。该对象被插入到设备树中的设备下方。因此，对应用程序中的应用程序没有直接依赖关系 CODESYS 项目。 您可以使用 DeviceTrace 在可视化中显示“多核”控制器的处理器负载。有关“多核”的更多信息，请参阅： 多核 有关编辑器及其操作的更多信息，请参阅帮助页面 痕迹 目的。...", 
"body" : "DeviceTrace 象征： 一种 设备跟踪 对象在一个或多个图表中显示跟踪数据，与 痕迹 目的。 不同的是，一个 设备跟踪 直接地 访问 在控制器上运行的跟踪。该对象被插入到设备树中的设备下方。因此，对应用程序中的应用程序没有直接依赖关系 CODESYS 项目。 您可以使用 DeviceTrace 在可视化中显示“多核”控制器的处理器负载。有关“多核”的更多信息，请参阅： 多核 有关编辑器及其操作的更多信息，请参阅帮助页面 痕迹 目的。 " }, 
{ "title" : "对话框 ", 
"url" : "_trace_dialogs.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对话框：跟踪配置 ", 
"url" : "_cds_dlg_trace_configuration.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 ", 
"snippet" : "跟踪配置 象征： 功能 ：该对话框包含跟踪配置 数据采样 。 称呼 跟踪 → 配置 命令;上下文菜单 配置 跟踪编辑器中的链接 添加变量 跟踪编辑器中的链接 要求 ：跟踪对象的编辑器已打开且处于活动状态。 有关更多信息，请参阅： 创建跟踪配置...", 
"body" : "跟踪配置 象征： 功能 ：该对话框包含跟踪配置 数据采样 。 称呼 跟踪 → 配置 命令;上下文菜单 配置 跟踪编辑器中的链接 添加变量 跟踪编辑器中的链接 要求 ：跟踪对象的编辑器已打开且处于活动状态。 有关更多信息，请参阅： 创建跟踪配置" }, 
{ "title" : "追踪记录 树视图 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_2d26d5993a2511e7a72e97101ee2f5a3", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 \/ 追踪记录 树视图 ", 
"snippet" : "树视图列出了被跟踪的变量并允许访问变量设置。 选定的跟踪名称 这 记录设置 子对话框显示在右侧。 选定的跟踪变量 这 变量设置 子对话框显示在右侧。 上下文菜单命令 ： 添加变量 添加一个新的跟踪变量 这 变量设置 子对话框在右侧打开，它已部分配置。在输入框中选择一个变量 多变的 设置跟踪其价值曲线。 分配给图表 列出当前未显示所选变量的图表（在右侧的子菜单中） 选择一个图表以在其中显示变量。 在树视图中选择变量时，该命令可用。 提示：当命令被禁用时，变量已经显示在所有图表中。 启用 默认启用 禁用的变量显示为灰色。它们既不显示也不记录。...", 
"body" : "树视图列出了被跟踪的变量并允许访问变量设置。 选定的跟踪名称 这 记录设置 子对话框显示在右侧。 选定的跟踪变量 这 变量设置 子对话框显示在右侧。 上下文菜单命令 ： 添加变量 添加一个新的跟踪变量 这 变量设置 子对话框在右侧打开，它已部分配置。在输入框中选择一个变量 多变的 设置跟踪其价值曲线。 分配给图表 列出当前未显示所选变量的图表（在右侧的子菜单中） 选择一个图表以在其中显示变量。 在树视图中选择变量时，该命令可用。 提示：当命令被禁用时，变量已经显示在所有图表中。 启用 默认启用 禁用的变量显示为灰色。它们既不显示也不记录。 " }, 
{ "title" : "演示文稿（图表） 树视图 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_e90b0fb3635a8e3bc0a8640e00f68bf2", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 \/ 演示文稿（图表） 树视图 ", 
"snippet" : "树视图列出了在跟踪编辑器中显示的图表，并允许访问它们的显示模式。 选定节点： 时间轴 这 显示模式 时间轴的子对话框显示在右侧。您可以指定时间轴显示。见下文。 所选图表名称 图表坐标系的设置和预览显示在右侧。见下文。 选定节点： Y轴 这 显示模式 子对话框显示在右侧。您可以指定轴显示。见下文。 显示变量 选定的跟踪变量 这 变量设置 子对话框显示在右侧。您可以配置跟踪变量。见下文。 注意：这些是相同的设置，可以在 追踪记录 树视图。 上下文菜单命令 ： 添加图表 在下面添加一个新图表并将其显示在 演示文稿（图表） 树视图 ： 添加新变量 添加一个新的跟踪变量 这 变量设置 子对话框在右侧打开...", 
"body" : "树视图列出了在跟踪编辑器中显示的图表，并允许访问它们的显示模式。 选定节点： 时间轴 这 显示模式 时间轴的子对话框显示在右侧。您可以指定时间轴显示。见下文。 所选图表名称 图表坐标系的设置和预览显示在右侧。见下文。 选定节点： Y轴 这 显示模式 子对话框显示在右侧。您可以指定轴显示。见下文。 显示变量 选定的跟踪变量 这 变量设置 子对话框显示在右侧。您可以配置跟踪变量。见下文。 注意：这些是相同的设置，可以在 追踪记录 树视图。 上下文菜单命令 ： 添加图表 在下面添加一个新图表并将其显示在 演示文稿（图表） 树视图 ： 添加新变量 添加一个新的跟踪变量 这 变量设置 子对话框在右侧打开，它已部分配置。在输入框中选择一个变量 多变的 设置跟踪其价值曲线。指定其显示。此外，变量被分配给选定的图表。 添加现有变量 列出当前未显示所选图表的所有跟踪变量（在右侧的子菜单中） 选择一个变量以便在所选图表中显示它。 提示：禁用该命令时，所有跟踪变量都已显示在所选图表中。 " }, 
{ "title" : "记录设置 子对话框 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_565148569fb211e4ac0cf998f94f5673", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 \/ 记录设置 子对话框 ", 
"snippet" : "要求：选择最上面的节点 追踪记录 树视图。 启用触发器 ：启用触发。只有在发送触发信号时，跟踪数据才会在运行时缓冲。您确定触发信号如何在 触发变量 , 触发参数 , 触发边沿 , 后触发（示例） ， 和 触发电平 设置。 : 连续显示当前数据集 触发变量 用作触发器的信号 需要完整的实例路径。 有效的触发信号是 IEC 变量、属性、引用、指针、应用程序的数组元素或表达式。允许的类型都是基于 IEC 的类型 除了 STRING , WSTRING ， 和 ARRAY .当基类型不是时允许枚举 STRING , WSTRING ， 或者 ARRAY .指针的内容不是有效信号。 当运行时系统使用 C...", 
"body" : "要求：选择最上面的节点 追踪记录 树视图。 启用触发器 ：启用触发。只有在发送触发信号时，跟踪数据才会在运行时缓冲。您确定触发信号如何在 触发变量 , 触发参数 , 触发边沿 , 后触发（示例） ， 和 触发电平 设置。 : 连续显示当前数据集 触发变量 用作触发器的信号 需要完整的实例路径。 有效的触发信号是 IEC 变量、属性、引用、指针、应用程序的数组元素或表达式。允许的类型都是基于 IEC 的类型 除了 STRING , WSTRING ， 和 ARRAY .当基类型不是时允许枚举 STRING , WSTRING ， 或者 ARRAY .指针的内容不是有效信号。 当运行时系统使用 CmpTraceMgr 组件，一个属性，它链接到 'monitoring' 然后可以将属性作为变量进行采样。 触发参数 用作触发器的系统参数 这 输入助手 对话框列出了所有有效的系统参数 参数 的类别 类别 标签。 允许选择 触发变量 或者 触发参数 触发边沿 定义触发的边缘检测 ： 积极的 对于布尔触发变量，触发发生在值从 FALSE 到 TRUE . 对于模拟触发变量，触发发生在定义的值 触发电平 “从下面”到达。 ： 消极的 对于布尔触发变量，触发发生在值从 TRUE 到 FALSE . 对于模拟触发变量，触发发生在定义的值 触发电平 “从上面”到达。 ： 两个都 对于布尔型触发变量，当值改变时触发。 对于模拟触发变量，触发发生在定义的值 触发电平 到达了。 后触发（示例） 触发后缓冲的每个跟踪变量的样本数 默认： 50 取值范围： 0 到 2 32 -1 触发电平 为了开始触发而达到的值 任务 记录数据的任务 记录条件 在运行时，应用程序检查记录条件。如果满足，则缓存跟踪数据。 记录数据采样条件 CmpTraceMgr 运行时系统组件 作为仅包含允许的运算符和操作数的表达式 允许的也可以嵌套的运算符：（逻辑） AND , NOT 和 OR , 和比较运算符 < , <= , > , >= , = 和 <> 允许的操作数：对跟踪有效的变量 作为变量 允许类型： BOOL , 位访问, 属性 条件满足 TRUE 或者 1 .指针的内容是不允许的。 使用 IEC 代码记录数据样本的条件 作为返回布尔值的表达式 评论 注释（例如，来自记录条件） 解决 每个数据集记录的时间戳的度量单位 多发性硬化症 : 时间戳（以毫秒为单位） 微秒 : 1 ms 或更短的任务循环时间的时间戳（以微秒为单位） 自动重启 ：将跟踪配置和运行时缓冲区的最后内容持久保存到目标设备 设备重启后，如果触发尚未发生，则自动开始跟踪。 先进的 打开 高级跟踪设置 对话 有关更多信息，请参阅： 高级趋势设置" }, 
{ "title" : "变量设置 子对话框 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_1ca9d7ba3a3511e7a72e97101ee2f5a3", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 \/ 变量设置 子对话框 ", 
"snippet" : "要求：在 追踪记录 或者 演示文稿（图表） 树视图。 多变的 有效变量变量；使用完整实例路径记录的值 有效的 IEC 变量 财产 参考 指针的内容 数组元素 允许的数据类型 基于IEC的类型 除了 STRING , WSTRING ， 或者 ARRAY 基类型不是时的枚举 STRING , WSTRING ， 或者 ARRAY 当运行时系统使用 CmpTraceMgr 组件，一个属性，它链接到 'monitoring' 然后可以将属性记录为变量。 参数 记录数据的参数 要求：运行时系统 CmpTraceMgr 零件 这 输入助手 对话框列出了所有有效的系统参数 参数 的类别 类别 标签。 允许...", 
"body" : "要求：在 追踪记录 或者 演示文稿（图表） 树视图。 多变的 有效变量变量；使用完整实例路径记录的值 有效的 IEC 变量 财产 参考 指针的内容 数组元素 允许的数据类型 基于IEC的类型 除了 STRING , WSTRING ， 或者 ARRAY 基类型不是时的枚举 STRING , WSTRING ， 或者 ARRAY 当运行时系统使用 CmpTraceMgr 组件，一个属性，它链接到 'monitoring' 然后可以将属性记录为变量。 参数 记录数据的参数 要求：运行时系统 CmpTraceMgr 零件 这 输入助手 对话框列出了所有有效的系统参数 参数 的类别 类别 标签。 允许在之间切换 多变的 和 范围 颜色 跟踪图中变量的颜色 线型 显示为折线图 线 ：这些值连接起来形成一条线。 步 ：值以楼梯的形式连接。 没有任何 : 值没有关联。 点类型 显示为散点图 点 ：值显示为一个点。 叉 ：数值显示为十字。 没有任何 ：不显示值。 激活最低警告 : 低于下限时发出警告 临界下限 如果跟踪变量的值低于限制，则变量以警告颜色显示。 颜色 值低于限制时的警告颜色 激活最大警告 : 超过上限时发出警告 临界上限 如果跟踪变量的值超过上限，则变量以警告颜色显示。 颜色 值超过限制时的警告颜色 " }, 
{ "title" : "显示模式 子对话框 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_67f1bc9d70b311e4ba1694269eca8f43", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 \/ 显示模式 子对话框 ", 
"snippet" : "要求：在 演示文稿（图表） 树视图。 显示模式 缩放 汽车 自动缩放时间轴 固定长度 时间轴段 长度 持续的 固定的 时间轴段从 最低限度 到 最大限度 最低限度 字面量、变量（整数数据类型）或常量变量（整数数据类型） 它包含段的初始值。要求： 显示模式 是 固定的 . 例子： 20,PLC_PRG.iLimit_Min, GVL.c_iLimit_Min 注意：变量必须有一个初始值。这对于离线显示和缩放细分很重要。 例子： iLimit_Min : INT := 20 最大限度 字面量、变量（整数数据类型）或常量变量（整数数据类型） 它包含段的结束值。 要求： 显示模式 是 固定的 . 例子...", 
"body" : "要求：在 演示文稿（图表） 树视图。 显示模式 缩放 汽车 自动缩放时间轴 固定长度 时间轴段 长度 持续的 固定的 时间轴段从 最低限度 到 最大限度 最低限度 字面量、变量（整数数据类型）或常量变量（整数数据类型） 它包含段的初始值。要求： 显示模式 是 固定的 . 例子： 20,PLC_PRG.iLimit_Min, GVL.c_iLimit_Min 注意：变量必须有一个初始值。这对于离线显示和缩放细分很重要。 例子： iLimit_Min : INT := 20 最大限度 字面量、变量（整数数据类型）或常量变量（整数数据类型） 它包含段的结束值。 要求： 显示模式 是 固定的 . 例子： 80,PLC_PRG.iLimit_Max, GVL.c_iLimit_Max 注意：变量必须有一个初始值。这对于离线显示和缩放细分很重要。 例子： iLimit_Max : INT := 80 长度 段的恒定长度 初始值会自动调整。 网格 : X 方向网格线图 从颜色列表框中选择网格线颜色。 刻度线 固定间距 : 显示刻度线 距离 和 细分 距离 刻度线之间的距离 细分 两个刻度线之间的细分数 字体 用于时间轴的字体 预览 关联 显示图表的预览 " }, 
{ "title" : "图表预览 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_8a982960451f11e7a93feabaeb321a5e", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：跟踪配置 \/ 图表预览 ", 
"snippet" : "要求：在图表中选择了一个图表 演示文稿（图表） 树视图。 背景颜色 图表的背景颜色 这 符号打开颜色列表框。 选择背景色 所选图表的背景颜色 添加变量 关联 添加一个新的跟踪变量（在 追踪记录 树视图） 删除变量 关联 删除选定的跟踪变量（在 追踪记录 树视图） 添加图表 关联 添加一个新图表（在 推介会 树视图） 删除图表 关联 删除选定的图表（在 推介会 树视图） 重置显示设置 关联 将所选图表或 Y 轴的显示设置重置为默认值 行 应用配置更改并保存跟踪配置...", 
"body" : "要求：在图表中选择了一个图表 演示文稿（图表） 树视图。 背景颜色 图表的背景颜色 这 符号打开颜色列表框。 选择背景色 所选图表的背景颜色 添加变量 关联 添加一个新的跟踪变量（在 追踪记录 树视图） 删除变量 关联 删除选定的跟踪变量（在 追踪记录 树视图） 添加图表 关联 添加一个新图表（在 推介会 树视图） 删除图表 关联 删除选定的图表（在 推介会 树视图） 重置显示设置 关联 将所选图表或 Y 轴的显示设置重置为默认值 行 应用配置更改并保存跟踪配置 " }, 
{ "title" : "对话框：高级趋势设置 ", 
"url" : "_cds_dlg_trace_advanced_settings.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 对话框 \/ 对话框：高级趋势设置 ", 
"snippet" : "高级趋势设置 功能 ：对话框提供数据采样的高级设置。 称呼 ： 跟踪配置 对话， 记录设置 子对话框， 先进的 按钮 要求 ：跟踪编辑器已打开且处于活动状态。这 跟踪配置 对话框打开，并且选择了跟踪记录树的顶部节点，以便 记录设置 子对话框可用。 对于值的计算，您必须在 跟踪配置 对话。 用户界面的选项 描述 在每个选项的右侧显示计算结果 每第 n 个周期测量一次 每 n 个任务周期的数据采样 默认： 1 ;然后应用程序在每个任务周期中执行数据采样。 采样间隔是根据指定的值自动计算的 每第 n 个周期测量一次 选项 例子： 100ms 推荐的运行时缓冲区大小（样本） 自动计算，因此建议应用程序...", 
"body" : "高级趋势设置 功能 ：对话框提供数据采样的高级设置。 称呼 ： 跟踪配置 对话， 记录设置 子对话框， 先进的 按钮 要求 ：跟踪编辑器已打开且处于活动状态。这 跟踪配置 对话框打开，并且选择了跟踪记录树的顶部节点，以便 记录设置 子对话框可用。 对于值的计算，您必须在 跟踪配置 对话。 用户界面的选项 描述 在每个选项的右侧显示计算结果 每第 n 个周期测量一次 每 n 个任务周期的数据采样 默认： 1 ;然后应用程序在每个任务周期中执行数据采样。 采样间隔是根据指定的值自动计算的 每第 n 个周期测量一次 选项 例子： 100ms 推荐的运行时缓冲区大小（样本） 自动计算，因此建议应用程序可以在运行时存储每个跟踪变量的样本数量 此值确定运行时系统中的最大环形缓冲区大小。这个缓冲区大小是根据任务循环时间和 每第 n 个周期测量一次 选项，并显示。 此缓冲区大小用于 覆盖运行时缓冲区大小 选项是 禁用 . 应用程序在运行时系统上采样数据的最大时间间隔长度 例子： 2s 注意：只有当跟踪配置的设置在 跟踪配置 对话框，因此任务循环时间是已知的。 覆盖运行时缓冲区大小 ：允许输入字段为您指定自己定义的缓冲区大小 在运行时，使用您在此处指定的值，而不是显示在 推荐的运行时缓冲区大小（样本） 选项。 例子： 100 至少 10 ：应用程序使用这个值，而不是计算的值 CODESYS 来自 推荐的运行时缓冲区大小（样本） 选项。 应用程序在运行时系统上采样数据而不覆盖它的最大时间间隔长度 例子： 6s 每个变量的跟踪编辑器缓冲区大小（样本） 跟踪编辑器中每个变量可以存储的值的数量 例子： 10000 轨迹编辑器中显示的最大时间段由数据采样的最大数量和采样间隔决定。您最多可以在跟踪编辑器中回滚这段时间。 例子 列 (1) 通知您有关样本的数量。它旁边的列 (2) 显示了计算得出的时间间隔。 示例中显示的信息意味着在运行时系统中每个任务周期抽取一个样本，并连续缓存在环形缓冲区中，该缓冲区最多可容纳 201 个样本。启用的 覆盖运行时缓冲区大小 选项的效果是，由于环形缓冲区，第一个缓存值在 100 个样本后首先被覆盖。在此期间，跟踪编辑器中连续显示 10000 个样本，因此可以在 1 分钟和近 40 秒的时间间隔内显示值曲线。 有关更多信息，请参阅： 创建跟踪配置" }, 
{ "title" : "菜单命令 ", 
"url" : "_trace_menu_commands.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令：添加变量 ", 
"url" : "_cds_cmd_trace_add_variable.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：添加变量 ", 
"snippet" : "添加变量 功能 ：该命令将跟踪变量添加到配置中。 称呼 ： 菜单 痕迹 一个新变量显示在跟踪配置的树视图中。关联的变量配置出现在右侧下方 变量设置 . 有关更多信息，请参阅： 创建跟踪配置...", 
"body" : "添加变量 功能 ：该命令将跟踪变量添加到配置中。 称呼 ： 菜单 痕迹 一个新变量显示在跟踪配置的树视图中。关联的变量配置出现在右侧下方 变量设置 . 有关更多信息，请参阅： 创建跟踪配置" }, 
{ "title" : "命令：下载跟踪 ", 
"url" : "_cds_cmd_trace_download.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：下载跟踪 ", 
"snippet" : "下载跟踪 象征： 功能 ：该命令将跟踪配置传输到控制器到分配的应用程序，开始数据采集。记录的数据被传回开发系统。然后跟踪图显示当前样本并运行。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：当关联应用程序在线时，该命令可用。 有关更多信息，请参阅： 控制数据采样...", 
"body" : "下载跟踪 象征： 功能 ：该命令将跟踪配置传输到控制器到分配的应用程序，开始数据采集。记录的数据被传回开发系统。然后跟踪图显示当前样本并运行。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：当关联应用程序在线时，该命令可用。 有关更多信息，请参阅： 控制数据采样" }, 
{ "title" : "命令：开始跟踪 ", 
"url" : "_cds_cmd_trace_start.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：开始跟踪 ", 
"snippet" : "开始跟踪 象征： 功能 ：命令停止时开始在控制器上执行数据采集。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：分配的应用程序正在运行时系统上运行，并且已加载跟踪配置。 有关更多信息，请参阅： 控制数据采样...", 
"body" : "开始跟踪 象征： 功能 ：命令停止时开始在控制器上执行数据采集。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：分配的应用程序正在运行时系统上运行，并且已加载跟踪配置。 有关更多信息，请参阅： 控制数据采样" }, 
{ "title" : "命令：停止跟踪 ", 
"url" : "_cds_cmd_trace_stop.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：停止跟踪 ", 
"snippet" : "停止追踪 象征： 功能 ：该命令停止轨迹的数据采集。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：分配的应用程序在运行时系统上运行并执行跟踪。 有关更多信息，请参阅： 控制数据采样...", 
"body" : "停止追踪 象征： 功能 ：该命令停止轨迹的数据采集。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：分配的应用程序在运行时系统上运行并执行跟踪。 有关更多信息，请参阅： 控制数据采样" }, 
{ "title" : "命令：重置触发器 ", 
"url" : "_cds_cmd_trace_reset_trigger.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：重置触发器 ", 
"snippet" : "重置触发器 象征： 功能 ：该命令在触发数据采集后重置跟踪配置。然后应用程序可以获取新数据并再次对触发器做出反应。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：触发一次触发器后，数据完全在开发系统的缓冲区中。 有关更多信息，请参阅： 控制数据采样...", 
"body" : "重置触发器 象征： 功能 ：该命令在触发数据采集后重置跟踪配置。然后应用程序可以获取新数据并再次对触发器做出反应。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：触发一次触发器后，数据完全在开发系统的缓冲区中。 有关更多信息，请参阅： 控制数据采样" }, 
{ "title" : "命令：光标 ", 
"url" : "_cds_cmd_trace_cursor.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：光标 ", 
"snippet" : "光标 象征： 功能 ： 该命令的工作方式如下： 它在跟踪图中插入一个跟踪光标，如果 不 存在跟踪光标。 它将第二个跟踪光标插入到跟踪图中，如果 1 存在跟踪光标。 它删除跟踪光标时 2 存在跟踪游标。 称呼 ： 菜单 痕迹 ， 上下文菜单 轨迹光标是一个黑色的小三角形，带有平行于 Y 轴的垂直黑线。...", 
"body" : "光标 象征： 功能 ： 该命令的工作方式如下： 它在跟踪图中插入一个跟踪光标，如果 不 存在跟踪光标。 它将第二个跟踪光标插入到跟踪图中，如果 1 存在跟踪光标。 它删除跟踪光标时 2 存在跟踪游标。 称呼 ： 菜单 痕迹 ， 上下文菜单 轨迹光标是一个黑色的小三角形，带有平行于 Y 轴的垂直黑线。 " }, 
{ "title" : "没有跟踪光标的跟踪图 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_3bb4368090b42c23c0a8640e00510814", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：光标 \/ 没有跟踪光标的跟踪图 ", 
"snippet" : "在这种状态下，您可以使用光标（即鼠标指针）运行跟踪图。您用光标关注的 X 值在状态栏中以标准化符号输出。例子： 时间：1m23s456ms 值：1...", 
"body" : "在这种状态下，您可以使用光标（即鼠标指针）运行跟踪图。您用光标关注的 X 值在状态栏中以标准化符号输出。例子： 时间：1m23s456ms 值：1 " }, 
{ "title" : "带有跟踪光标的跟踪图 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_4e02c9b290b42c23c0a8640e01e9fd26", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：光标 \/ 带有跟踪光标的跟踪图 ", 
"snippet" : "CODESYS 输出状态栏中跟踪光标标记的时间点和 Y 值。例子： 时间：1m23s456ms...", 
"body" : "CODESYS 输出状态栏中跟踪光标标记的时间点和 Y 值。例子： 时间：1m23s456ms " }, 
{ "title" : "带有 2 个跟踪光标的跟踪图 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_53d5619790b42c23c0a8640e009c07ca", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：光标 \/ 带有 2 个跟踪光标的跟踪图 ", 
"snippet" : "CODESYS 输出状态栏中 2 个轨迹光标所标记的 2 个时间点和时间间隔。例子： 时间：1m23s456ms - 时间：1m24s456ms (∆ 1s) ....", 
"body" : "CODESYS 输出状态栏中 2 个轨迹光标所标记的 2 个时间点和时间间隔。例子： 时间：1m23s456ms - 时间：1m24s456ms (∆ 1s) . " }, 
{ "title" : "跟踪图中的用户输入 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_725ebfbf07220da4c0a8640e012a61b4", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：光标 \/ 跟踪图中的用户输入 ", 
"snippet" : "如果有 1 或 2 个轨迹光标，您可以沿 X 轴移动它们。 用户使用鼠标输入 象征 影响 将跟踪光标三角形拖到不同的位置。 只要按下鼠标按钮，光标就可以自由移动。当前 Y 值始终显示在状态栏中。只要松开鼠标按钮，光标就会捕捉到最近的测量点。 使用键盘快捷键的用户输入 影响 左箭头 向右的箭头 CODESYS 将黑色轨迹光标移动到下一个测量点。 切换 + 左箭头 切换 + 向右的箭头 CODESYS 将灰色轨迹光标移动到下一个测量点。 有关更多信息，请参阅： 导航到跟踪数据...", 
"body" : "如果有 1 或 2 个轨迹光标，您可以沿 X 轴移动它们。 用户使用鼠标输入 象征 影响 将跟踪光标三角形拖到不同的位置。 只要按下鼠标按钮，光标就可以自由移动。当前 Y 值始终显示在状态栏中。只要松开鼠标按钮，光标就会捕捉到最近的测量点。 使用键盘快捷键的用户输入 影响 左箭头 向右的箭头 CODESYS 将黑色轨迹光标移动到下一个测量点。 切换 + 左箭头 切换 + 向右的箭头 CODESYS 将灰色轨迹光标移动到下一个测量点。 有关更多信息，请参阅： 导航到跟踪数据" }, 
{ "title" : "命令：用鼠标缩放 ", 
"url" : "_cds_cmd_trace_mouse_zooming.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：用鼠标缩放 ", 
"snippet" : "用鼠标缩放 象征： （命令禁用） 象征： （命令启用） 功能 ：该命令启用或禁用跟踪图中的鼠标缩放。 称呼 ： 菜单 痕迹 ， 上下文菜单...", 
"body" : "用鼠标缩放 象征： （命令禁用） 象征： （命令启用） 功能 ：该命令启用或禁用跟踪图中的鼠标缩放。 称呼 ： 菜单 痕迹 ， 上下文菜单 " }, 
{ "title" : "跟踪图中的用户输入 ", 
"url" : "_cds_cmd_trace_mouse_zooming.html#UUID-168f2e36-4edc-93e4-08cc-43a7cdc175b0_id_d2d238b90e93c0a8640e00458ec9_id_80aeaddbce7e5d84c0a8640e0036c6d9", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：用鼠标缩放 \/ 跟踪图中的用户输入 ", 
"snippet" : "如果该命令被激活，您可以用鼠标打开一个矩形。当您释放鼠标按钮时，矩形被放大并且数据被放大。 有关更多信息，请参阅： 导航到跟踪数据...", 
"body" : "如果该命令被激活，您可以用鼠标打开一个矩形。当您释放鼠标按钮时，矩形被放大并且数据被放大。 有关更多信息，请参阅： 导航到跟踪数据" }, 
{ "title" : "命令：重置视图 ", 
"url" : "_cds_cmd_trace_reset_view.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：重置视图 ", 
"snippet" : "重置视图 象征： 功能 ：该命令将跟踪图中的显示重置为默认值。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：您可以通过缩放、滚动或命令在轨迹图中显示 自动缩放 改变了。 有关更多信息，请参阅： 自动缩放...", 
"body" : "重置视图 象征： 功能 ：该命令将跟踪图中的显示重置为默认值。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：您可以通过缩放、滚动或命令在轨迹图中显示 自动缩放 改变了。 有关更多信息，请参阅： 自动缩放" }, 
{ "title" : "命令：自动缩放 ", 
"url" : "_cds_cmd_trace_auto_fit.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：自动缩放 ", 
"snippet" : "自动缩放 象征： 功能 ：该命令缩放轨迹图的 y 轴，以使所有图形都以最佳方式显示，并且 y 值适合图表的可见区域。该命令同时影响单通道和多通道显示。 称呼 : 痕迹 菜单;上下文菜单 要求 ：跟踪正在运行。为此，您之前创建了一条轨迹，为 Y 轴指定了一个固定比例，并执行了 下载跟踪 命令。 该命令可以切换。当您单击菜单中启用的命令时，自动调整到 Y 轴的显示变回之前配置的固定显示。 功能 ：该命令缩放轨迹图的 y 轴，以使所有图形都以最佳方式显示，并且 y 值适合图表的可见区域。该命令同时影响单通道和多通道显示。...", 
"body" : "自动缩放 象征： 功能 ：该命令缩放轨迹图的 y 轴，以使所有图形都以最佳方式显示，并且 y 值适合图表的可见区域。该命令同时影响单通道和多通道显示。 称呼 : 痕迹 菜单;上下文菜单 要求 ：跟踪正在运行。为此，您之前创建了一条轨迹，为 Y 轴指定了一个固定比例，并执行了 下载跟踪 命令。 该命令可以切换。当您单击菜单中启用的命令时，自动调整到 Y 轴的显示变回之前配置的固定显示。 功能 ：该命令缩放轨迹图的 y 轴，以使所有图形都以最佳方式显示，并且 y 值适合图表的可见区域。该命令同时影响单通道和多通道显示。 " }, 
{ "title" : "单通道显示中的跟踪 ", 
"url" : "_cds_cmd_trace_auto_fit.html#UUID-d4fafa55-c8c6-3865-1d6d-31d31577c463_id_c7d5cbf38bedbacc0a8640e0100667c_id_4c29461991206663c0a8640e01dfc836", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：自动缩放 \/ 单通道显示中的跟踪 ", 
"snippet" : "如果所有迹线变量都显示在一个图表中，则迹线为单通道表示。...", 
"body" : "如果所有迹线变量都显示在一个图表中，则迹线为单通道表示。 " }, 
{ "title" : "多通道显示中的跟踪 ", 
"url" : "_cds_cmd_trace_auto_fit.html#UUID-d4fafa55-c8c6-3865-1d6d-31d31577c463_id_c7d5cbf38bedbacc0a8640e0100667c_id_6dbf5d2c071fc814c0a8640e01ac9307", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：自动缩放 \/ 多通道显示中的跟踪 ", 
"snippet" : "如果迹线变量显示在多个图表中，则迹线采用多通道表示。 有关更多信息，请参阅： 跟踪配置 和 导航到跟踪数据...", 
"body" : "如果迹线变量显示在多个图表中，则迹线采用多通道表示。 有关更多信息，请参阅： 跟踪配置 和 导航到跟踪数据" }, 
{ "title" : "命令：压缩 ", 
"url" : "_cds_cmd_trace_compress.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：压缩 ", 
"snippet" : "压缩 象征： 功能 ：该命令通过将显示的时间范围增加一个固定百分比来压缩跟踪图。 称呼 ： 菜单 痕迹 ， 上下文菜单 有关更多信息，请参阅： 拉紧 和 导航到跟踪数据...", 
"body" : "压缩 象征： 功能 ：该命令通过将显示的时间范围增加一个固定百分比来压缩跟踪图。 称呼 ： 菜单 痕迹 ， 上下文菜单 有关更多信息，请参阅： 拉紧 和 导航到跟踪数据" }, 
{ "title" : "命令：伸展 ", 
"url" : "_cds_cmd_trace_stretch.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：伸展 ", 
"snippet" : "拉紧 象征： 功能 ：该命令通过将显示的时间范围缩小一个固定百分比来拉伸跟踪图。 称呼 ： 菜单 痕迹 ， 上下文菜单 有关更多信息，请参阅： 导航到跟踪数据...", 
"body" : "拉紧 象征： 功能 ：该命令通过将显示的时间范围缩小一个固定百分比来拉伸跟踪图。 称呼 ： 菜单 痕迹 ， 上下文菜单 有关更多信息，请参阅： 导航到跟踪数据" }, 
{ "title" : "命令：在线列表 ", 
"url" : "_cds_cmd_trace_online_list.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：在线列表 ", 
"snippet" : "在线列表 功能 ：命令打开对话框 在线列表 .如果只是一个跟踪编辑器 设备跟踪 对象处于活动状态时，控制器上运行的所有跟踪都显示在树视图中。如果与应用程序相关的跟踪对象的跟踪编辑器当前处于活动状态，则如果它在控制器上运行，则仅显示此跟踪。 称呼 ： 菜单 痕迹 , 跟踪编辑器的上下文菜单 要求 ：运行时系统使用组件 CmpTraceMgr .属于该设备的应用程序处于在线模式。 关闭 设备跟踪 -Editor 终止与控制器的连接。 请注意，随着最后打开的关闭 设备跟踪 -Editor 也会终止与控制器的连接！要在项目中再次显示设备轨迹，您必须在 设备跟踪 - 加载对象。 关闭编辑器目前也是有意识...", 
"body" : "在线列表 功能 ：命令打开对话框 在线列表 .如果只是一个跟踪编辑器 设备跟踪 对象处于活动状态时，控制器上运行的所有跟踪都显示在树视图中。如果与应用程序相关的跟踪对象的跟踪编辑器当前处于活动状态，则如果它在控制器上运行，则仅显示此跟踪。 称呼 ： 菜单 痕迹 , 跟踪编辑器的上下文菜单 要求 ：运行时系统使用组件 CmpTraceMgr .属于该设备的应用程序处于在线模式。 关闭 设备跟踪 -Editor 终止与控制器的连接。 请注意，随着最后打开的关闭 设备跟踪 -Editor 也会终止与控制器的连接！要在项目中再次显示设备轨迹，您必须在 设备跟踪 - 加载对象。 关闭编辑器目前也是有意识地结束与控制器的连接的推荐过程。注销是不够的。 " }, 
{ "title" : "对话：在线列表 ", 
"url" : "_cds_cmd_trace_online_list.html#UUID-ce19611c-72af-217d-a4a2-3770090dbf4b_id_d2f3bea38c0e862c0a8640e01adb3d6_id_0387599e07259231c0a8640e01b92b5a", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：在线列表 \/ 对话：在线列表 ", 
"snippet" : "从 LZS 中删除 停止并从正在运行的应用程序中删除选定的跟踪 上传 该命令在跟踪编辑器中可见 设备跟踪 已加载。一个 设备跟踪 是在控制器上运行的跟踪：在设备树中，可以使用 设备跟踪 - 对象可以直接在设备下方表示。 当您选择该命令时，在树视图中选择的跟踪将从运行时系统加载到跟踪编辑器中。项目中的任何现有配置都将被覆盖。例如，设备可以提供处理器利用率数据的跟踪（ cpuload , plcload )，然后您可以在跟踪编辑器中使用 CODESYS 可以追踪。 要在项目中显示的每个设备跟踪都有一个单独的跟踪 设备跟踪 - 设备树中需要的对象。 有关更多信息，请参阅： 访问控制器上的所有跟踪 和...", 
"body" : "从 LZS 中删除 停止并从正在运行的应用程序中删除选定的跟踪 上传 该命令在跟踪编辑器中可见 设备跟踪 已加载。一个 设备跟踪 是在控制器上运行的跟踪：在设备树中，可以使用 设备跟踪 - 对象可以直接在设备下方表示。 当您选择该命令时，在树视图中选择的跟踪将从运行时系统加载到跟踪编辑器中。项目中的任何现有配置都将被覆盖。例如，设备可以提供处理器利用率数据的跟踪（ cpuload , plcload )，然后您可以在跟踪编辑器中使用 CODESYS 可以追踪。 要在项目中显示的每个设备跟踪都有一个单独的跟踪 设备跟踪 - 设备树中需要的对象。 有关更多信息，请参阅： 访问控制器上的所有跟踪 和 DeviceTrace" }, 
{ "title" : "命令：上传跟踪 ", 
"url" : "_cds_cmd_trace_upload.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：上传跟踪 ", 
"snippet" : "上传跟踪 功能 ：该命令首先建立与 PLC 设备的连接（如果该设备不存在）。然后他打开对话框 在线列表 带有当前在控制器上运行的跟踪列表。然后使用对话框中可用的命令运行选定的跟踪 上传 加载到跟踪编辑器中。 称呼 ： 菜单 痕迹 , 跟踪编辑器的上下文菜单 要求 : 一个编辑 设备跟踪 对象已打开。运行时系统使用组件 CmpTraceMgr （跟踪管理器）。运行时系统上至少有一个应用程序正在运行。在里面 CODESYS 项目中，PLC 的通讯设置已正确配置。 关闭 设备跟踪 -Editor 终止与控制器的连接。 请注意，最后一次打开时，与控制器的连接也会终止 设备跟踪 编辑器已关闭。为了在项目...", 
"body" : "上传跟踪 功能 ：该命令首先建立与 PLC 设备的连接（如果该设备不存在）。然后他打开对话框 在线列表 带有当前在控制器上运行的跟踪列表。然后使用对话框中可用的命令运行选定的跟踪 上传 加载到跟踪编辑器中。 称呼 ： 菜单 痕迹 , 跟踪编辑器的上下文菜单 要求 : 一个编辑 设备跟踪 对象已打开。运行时系统使用组件 CmpTraceMgr （跟踪管理器）。运行时系统上至少有一个应用程序正在运行。在里面 CODESYS 项目中，PLC 的通讯设置已正确配置。 关闭 设备跟踪 -Editor 终止与控制器的连接。 请注意，最后一次打开时，与控制器的连接也会终止 设备跟踪 编辑器已关闭。为了在项目中再次显示设备迹线，您需要将它们重新加载到 设备跟踪 对象。 目前，关闭编辑器也是推荐的方法来故意终止与控制器的连接。注销对此还不够。 有关更多信息，请参阅： 访问控制器上的所有跟踪" }, 
{ "title" : "命令：配置 ", 
"url" : "_cds_cmd_trace_configuration.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：配置 ", 
"snippet" : "配置 功能 ：命令打开对话框 跟踪配置 ，它允许配置数据收集。 称呼 ： 菜单 痕迹 ， 上下文菜单 有关更多信息，请参阅： 跟踪配置...", 
"body" : "配置 功能 ：命令打开对话框 跟踪配置 ，它允许配置数据收集。 称呼 ： 菜单 痕迹 ， 上下文菜单 有关更多信息，请参阅： 跟踪配置" }, 
{ "title" : "命令：负载跟踪 ", 
"url" : "_cds_cmd_trace_load.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：负载跟踪 ", 
"snippet" : "负载跟踪 功能 ：该命令允许加载包含保存在开发系统文件系统中的配置和数据的文件。对话 负载跟踪 出现。 称呼 ： 菜单 痕迹 ， 上下文菜单...", 
"body" : "负载跟踪 功能 ：该命令允许加载包含保存在开发系统文件系统中的配置和数据的文件。对话 负载跟踪 出现。 称呼 ： 菜单 痕迹 ， 上下文菜单 " }, 
{ "title" : "对话：负载跟踪 ", 
"url" : "_cds_cmd_trace_load.html#UUID-e47e8db6-406e-9b94-bae0-f820c9689058_id_b399f38c246edc0a8640e00a7659a_id_26f9ba38ce7e8813c0a8640e00e3eaf1", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：负载跟踪 \/ 对话：负载跟踪 ", 
"snippet" : "文件名 正在加载的文件的名称 文件类型 文件格式 *.trace ： 跟踪文件 ，其中包含跟踪配置和示例 *.csv ：包含跟踪配置的 CSV 文件格式的文本文件 有关更多信息，请参阅： 管理跟踪...", 
"body" : "文件名 正在加载的文件的名称 文件类型 文件格式 *.trace ： 跟踪文件 ，其中包含跟踪配置和示例 *.csv ：包含跟踪配置的 CSV 文件格式的文本文件 有关更多信息，请参阅： 管理跟踪" }, 
{ "title" : "命令：保存跟踪 ", 
"url" : "_cds_cmd_trace_save.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：保存跟踪 ", 
"snippet" : "保存跟踪 功能 ：该命令允许将数据保存到开发系统上的文件中。根据文件格式，还会保存配置。对话 保存跟踪 出现。 称呼 ： 菜单 痕迹 ， 上下文菜单...", 
"body" : "保存跟踪 功能 ：该命令允许将数据保存到开发系统上的文件中。根据文件格式，还会保存配置。对话 保存跟踪 出现。 称呼 ： 菜单 痕迹 ， 上下文菜单 " }, 
{ "title" : "对话框：保存跟踪 ", 
"url" : "_cds_cmd_trace_save.html#UUID-d3c7c9ff-690d-2549-e2d2-897be7c0f07e_id_adda054938c2b695c0a8640e00c67eff_id_67a9c8bece907839c0a8640e0039fb47", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：保存跟踪 \/ 对话框：保存跟踪 ", 
"snippet" : "文件名 跟踪文件名和位置 文件类型 文件类型 *.trace ： 跟踪文件 ，其中包含数据和配置 您可以使用命令创建这样的文件 负载跟踪 在跟踪编辑器中离线加载。 *.txt ： 文本文件 ，其中包含收集的数据 您可以使用支持 CSV 格式的工具加载和处理此类文件。 您无法将它们离线加载到跟踪编辑器中，因为跟踪编辑器无法读取此格式。 *.trace.csv 跟踪 csv 文件（仅数据） ，其中包含收集的数据 为每个跟踪变量提供地址信息。生成的文件可以读入运行时系统。数据已导入，但由于未保存变量地址，因此无法启动跟踪。 有关更多信息，请参阅： 管理跟踪...", 
"body" : "文件名 跟踪文件名和位置 文件类型 文件类型 *.trace ： 跟踪文件 ，其中包含数据和配置 您可以使用命令创建这样的文件 负载跟踪 在跟踪编辑器中离线加载。 *.txt ： 文本文件 ，其中包含收集的数据 您可以使用支持 CSV 格式的工具加载和处理此类文件。 您无法将它们离线加载到跟踪编辑器中，因为跟踪编辑器无法读取此格式。 *.trace.csv 跟踪 csv 文件（仅数据） ，其中包含收集的数据 为每个跟踪变量提供地址信息。生成的文件可以读入运行时系统。数据已导入，但由于未保存变量地址，因此无法启动跟踪。 有关更多信息，请参阅： 管理跟踪" }, 
{ "title" : "命令：导出符号跟踪配置 ", 
"url" : "_cds_cmd_trace_export_symbolic_trace_config.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：导出符号跟踪配置 ", 
"snippet" : "导出符号跟踪配置 功能 ：该命令将跟踪配置导出为具有格式的文件 *.traceconfig . 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：原始应用程序包含一个符号配置，它将配置的跟踪变量定义为符号。因此，对记录其数据的 IEC 变量的访问是象征性的，并使跟踪配置能够用于各种类似的应用程序。...", 
"body" : "导出符号跟踪配置 功能 ：该命令将跟踪配置导出为具有格式的文件 *.traceconfig . 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：原始应用程序包含一个符号配置，它将配置的跟踪变量定义为符号。因此，对记录其数据的 IEC 变量的访问是象征性的，并使跟踪配置能够用于各种类似的应用程序。 " }, 
{ "title" : "使用配置文件 ", 
"url" : "_cds_cmd_trace_export_symbolic_trace_config.html#UUID-19273690-813e-4c38-271a-86ac0cece2ec_id_b493e438c3b197c0a8640e00f0260c_id_16116f1397ea11e482dcec1a7d15e9dd", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：导出符号跟踪配置 \/ 使用配置文件 ", 
"snippet" : "您可以将此文件传输到任何运行时系统。在运行时，它的运行时系统组件 CmpTraceMgr 访问它并基于它进行数据收集。除了配置数据之外，配置文件还包含有关应用程序上下文的信息。 配置文件定义了以下上下文： 应用名称 跟踪名称 任务名称 在运行时执行的应用程序必须满足以下条件： 该应用程序与原始应用程序具有相同的名称。 应用程序中配置的跟踪与源应用程序中配置的跟踪具有相同的名称。 运行数据收集的任务与源应用程序中配置的任务同名。 配置加载不是自动的，您必须指挥它。 您可以执行以下操作： 您可以使用库接口通过 IEC 代码以编程方式访问跟踪管理器。 您向跟踪管理器注册配置文件。然后跟踪管理器在应用...", 
"body" : "您可以将此文件传输到任何运行时系统。在运行时，它的运行时系统组件 CmpTraceMgr 访问它并基于它进行数据收集。除了配置数据之外，配置文件还包含有关应用程序上下文的信息。 配置文件定义了以下上下文： 应用名称 跟踪名称 任务名称 在运行时执行的应用程序必须满足以下条件： 该应用程序与原始应用程序具有相同的名称。 应用程序中配置的跟踪与源应用程序中配置的跟踪具有相同的名称。 运行数据收集的任务与源应用程序中配置的任务同名。 配置加载不是自动的，您必须指挥它。 您可以执行以下操作： 您可以使用库接口通过 IEC 代码以编程方式访问跟踪管理器。 您向跟踪管理器注册配置文件。然后跟踪管理器在应用程序启动时加载配置文件。 有关跟踪管理器功能的更多信息，请参见 “跟踪管理器运行时系统组件说明” . " }, 
{ "title" : "配置文件示例 ", 
"url" : "_cds_cmd_trace_export_symbolic_trace_config.html#UUID-19273690-813e-4c38-271a-86ac0cece2ec_id_b493e438c3b197c0a8640e00f0260c_id_d27cec580724ef6fc0a8640e00c884c4", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：导出符号跟踪配置 \/ 配置文件示例 ", 
"snippet" : "配置文件 Trace_Trigger.traceconfig [key]; [value] Version; 0x03050000 Name; Application.Trace_Trigger ApplicationName; Application ApplicationDataGuid; 00000000-0000-0000-0000-000000000000 IecTaskName; MainTask Comment; Trigger.Flags; 5 Trigger.Edge; 2 Trigger.Position; 0 Trigger.UpdatesAfterTrigger; 50...", 
"body" : "配置文件 Trace_Trigger.traceconfig [key]; [value]\nVersion; 0x03050000\nName; Application.Trace_Trigger\nApplicationName; Application\nApplicationDataGuid; 00000000-0000-0000-0000-000000000000\nIecTaskName; MainTask\nComment;\nTrigger.Flags; 5\nTrigger.Edge; 2\nTrigger.Position; 0\nTrigger.UpdatesAfterTrigger; 50\nTrigger.Variable.Name; PLC_PRG.B.OUT\nTrigger.Variable.AddrFlags; 0x00000101\nTrigger.Variable.Class; 0\nTrigger.Variable.Size; 1\nTrigger.Level;\nCondition.Name;\nCondition.AddrFlags; 0x00000000\nCondition.Class; 0\nCondition.Size; 0\nEveryNCycles; 1\nBufferEntries; 100\nFlags; 16\n0.Variable; PLC_PRG.S5.OUT\n0.Address.AddrFlags; 0x00000101\n0.Class; 7\n0.Size; 2\n0.GraphColor; 4278190335\n0.GraphType; 3\n0.MinWarningColor; 4278190080\n0.MaxWarningColor; 4294901760\n0.CriticalLowerLimit; 0\n0.CriticalUpperLimit; 0\n0.ActivateMinWarning; 0\n0.ActivateMaxWarning; 0\n0.YAxis; 0\n0.Data;\n1.Variable; PLC_PRG.B.OUT\n1.Address.AddrFlags; 0x00000101\n1.Class; 0\n1.Size; 1\n1.GraphColor; 4278222848\n1.GraphType; 1\n1.MinWarningColor; 4278190080\n1.MaxWarningColor; 4294901760\n1.CriticalLowerLimit; 0\n1.CriticalUpperLimit; 0\n1.ActivateMinWarning; 0\n1.ActivateMaxWarning; 0\n1.YAxis; 0\n1.Data; " }, 
{ "title" : "命令：统计 ", 
"url" : "_cds_cmd_trace_statistics.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：统计 ", 
"snippet" : "统计数据 功能 ：命令打开对话框 跟踪统计 ，它显示每个跟踪变量的统计信息。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：跟踪编辑器包含示例。...", 
"body" : "统计数据 功能 ：命令打开对话框 跟踪统计 ，它显示每个跟踪变量的统计信息。 称呼 ： 菜单 痕迹 ， 上下文菜单 要求 ：跟踪编辑器包含示例。 " }, 
{ "title" : "对话框：跟踪统计信息 ", 
"url" : "_cds_cmd_trace_statistics.html#UUID-94109e40-6e95-52d2-5a16-fea5d8126e79_id_e33f54672d980a83c0a8640e00b10ad6_id_0387599e07259231c0a8640e01b92b5a", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：统计 \/ 对话框：跟踪统计信息 ", 
"snippet" : "分析的时间段及其持续时间在标题中给出。 该表包含每个信号的一行。 信号 跟踪变量名称 例子： PLC_PRG.S1 指数 信号顺序的基于 0 的索引 N 计算所依据的测量值数量 分钟 最小值 平均 平均 中位数 按大小对值进行排序时位于中间的值 有效值 均方根 标准差 标准差 最大限度 最大值 不可缺少的 不可缺少的 最小 Δt [s] 连续值的时间间隔的最小值 平均Δt [s] 连续值的时间间隔的平均值 中值 Δt [s] 连续值的时间间隔的中位数 标准差Δt [s] 连续值时间间隔的标准差 最大Δt [s] 连续值的时间间隔的最大值 单击特定列中的表头 CODESYS 按列对表格进行排序，...", 
"body" : "分析的时间段及其持续时间在标题中给出。 该表包含每个信号的一行。 信号 跟踪变量名称 例子： PLC_PRG.S1 指数 信号顺序的基于 0 的索引 N 计算所依据的测量值数量 分钟 最小值 平均 平均 中位数 按大小对值进行排序时位于中间的值 有效值 均方根 标准差 标准差 最大限度 最大值 不可缺少的 不可缺少的 最小 Δt [s] 连续值的时间间隔的最小值 平均Δt [s] 连续值的时间间隔的平均值 中值 Δt [s] 连续值的时间间隔的中位数 标准差Δt [s] 连续值时间间隔的标准差 最大Δt [s] 连续值的时间间隔的最大值 单击特定列中的表头 CODESYS 按列对表格进行排序，将顺序从升序更改为降序，反之亦然。 默认值：表格按列升序 指数 排序。因此，信号按照它们在信号树中出现的相同顺序进行排序。 在行中单击 该行被选中。你可以跟我来 切换 + 箭 选择其他行并再次取消选择它们。 控制 + C CODESYS 将选定的行作为文本复制到剪贴板。各个列的值用制表符分隔，行用控制字符 铬 或者 如果 分开。 要求：您选择了一行或多行。 欲了解更多信息，请参阅： 跟踪数据采样" }, 
{ "title" : "命令：将所有变量移动到单个图表 ", 
"url" : "_trace_cmd_move_all_variables_to_individual_diagrams.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：将所有变量移动到单个图表 ", 
"snippet" : "将所有变量移至单个图表 功能 ：此命令使得在一个图表中一起显示的变量分别显示在单独的图表中。 称呼 ： 痕迹 菜单；上下文菜单...", 
"body" : "将所有变量移至单个图表 功能 ：此命令使得在一个图表中一起显示的变量分别显示在单独的图表中。 称呼 ： 痕迹 菜单；上下文菜单 " }, 
{ "title" : "变量在单独的图表中单独显示 ", 
"url" : "_trace_cmd_move_all_variables_to_individual_diagrams.html#UUID-b7f34b19-d3a2-7fbd-613f-d026d48b35fd_id_f7ca90b1752d0c0a8646378d1567c_id_56c6a1781bacfff0c0a86463414b8c43", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：将所有变量移动到单个图表 \/ 变量在单独的图表中单独显示 ", 
"snippet" : "有关详细信息，请参阅：For more information, see: 导航到跟踪数据 和 跟踪配置...", 
"body" : "有关详细信息，请参阅：For more information, see: 导航到跟踪数据 和 跟踪配置" }, 
{ "title" : "命令：将所有变量移至第一个图表 ", 
"url" : "_trace_cmd_move_all_variables_to_first_diagram.html", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：将所有变量移至第一个图表 ", 
"snippet" : "将所有变量移至第一个图表 功能 ：此命令使得在一个图中单独显示的变量在第一个图中一起显示。 称呼 ： 痕迹 菜单；上下文菜单...", 
"body" : "将所有变量移至第一个图表 功能 ：此命令使得在一个图中单独显示的变量在第一个图中一起显示。 称呼 ： 痕迹 菜单；上下文菜单 " }, 
{ "title" : "变量在一个图表中一起显示 ", 
"url" : "_trace_cmd_move_all_variables_to_first_diagram.html#UUID-309629ae-966c-e6d9-be01-d05f9c097269_id_adcc80b17bb78c0a86463003afb08_id_cdb4c9e31bac8664c0a864632f0c6643", 
"breadcrumbs" : "代码系统跟踪 \/ 参考：用户界面 \/ 菜单命令 \/ 命令：将所有变量移至第一个图表 \/ 变量在一个图表中一起显示 ", 
"snippet" : "有关详细信息，请参阅：For more information, see: 导航到跟踪数据 和 跟踪配置...", 
"body" : "有关详细信息，请参阅：For more information, see: 导航到跟踪数据 和 跟踪配置" }
]
$(document).trigger('search.ready');
});