$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS CANbus ", 
"url" : "_can_start_page.html", 
"breadcrumbs" : "CODESYS CANbus \/ CODESYS CANbus ", 
"snippet" : "CODESYS 支持以下基于 CAN 的现场总线： CANopen J1939 有关现场总线支持的更多一般信息，请参见 CODESYS ， 看： 现场总线支持...", 
"body" : "CODESYS 支持以下基于 CAN 的现场总线： CANopen J1939 有关现场总线支持的更多一般信息，请参见 CODESYS ， 看： 现场总线支持 " }, 
{ "title" : "CANopen ", 
"url" : "_can_start_page.html#UUID-7a2a4063-c968-a417-14b0-3c9c78ae54f3_id_a8144375e62110c4c0a86463209f3ab7-id-ecc2ffc7098bf830c0a864637ea29463", 
"breadcrumbs" : "CODESYS CANbus \/ CODESYS CANbus \/ CANopen ", 
"snippet" : "CANopen 是一种用于流程自动化的协议。 CANopen 网络由一个管理器和充当主机和从机的设备组成。在这种情况下，设备可以模块化或非模块化构造。 而且， CODESYS 区分远程设备和本地设备。 CANopen 远程设备 ： 在 CODESYS ，CANopen 远程设备是插入在项目设备树中 CANopen 管理器（主）下方的从设备。 CANopen 本地设备 ： 在 CODESYS CANopen 本地设备是从设备，直接插入项目设备树中 CAN 总线节点的下方。结果， CODESYS 运行时可用作 CANopen 从站。 你可以下载 CODESYS CANopen Manager SL...", 
"body" : "CANopen 是一种用于流程自动化的协议。 CANopen 网络由一个管理器和充当主机和从机的设备组成。在这种情况下，设备可以模块化或非模块化构造。 而且， CODESYS 区分远程设备和本地设备。 CANopen 远程设备 ： 在 CODESYS ，CANopen 远程设备是插入在项目设备树中 CANopen 管理器（主）下方的从设备。 CANopen 本地设备 ： 在 CODESYS CANopen 本地设备是从设备，直接插入项目设备树中 CAN 总线节点的下方。结果， CODESYS 运行时可用作 CANopen 从站。 你可以下载 CODESYS CANopen Manager SL 在里面 CODESYS 商店 .您还可以在此处找到产品的数据表。 CANopen 示例项目 " }, 
{ "title" : "J1939 ", 
"url" : "_can_start_page.html#UUID-7a2a4063-c968-a417-14b0-3c9c78ae54f3_id_a8144375e62110c4c0a86463209f3ab7-id-268fb433098bf830c0a86463236ab064", 
"breadcrumbs" : "CODESYS CANbus \/ CODESYS CANbus \/ J1939 ", 
"snippet" : "网络协议 SAE 1939 也使用 CAN 作为物理传输层。该协议用于在商用车辆中传输控制器信息和诊断数据。 你可以下载 CODESYS J1939 Manager SL 在里面 CODESYS 商店 .您还可以在此处找到产品的数据表。...", 
"body" : "网络协议 SAE 1939 也使用 CAN 作为物理传输层。该协议用于在商用车辆中传输控制器信息和诊断数据。 你可以下载 CODESYS J1939 Manager SL 在里面 CODESYS 商店 .您还可以在此处找到产品的数据表。 " }, 
{ "title" : "配置 ", 
"url" : "_can_f_canbus_configuration.html", 
"breadcrumbs" : "CODESYS CANbus \/ 配置 ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 " }, 
{ "title" : "选项卡：CANbus – 常规 ", 
"url" : "_can_edt_canbus_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ 配置 \/ 选项卡：CANbus – 常规 ", 
"snippet" : "一般的 网络 通过 CAN 总线接口链接的 CAN 网络的编号。允许的值：0 到 100。 波特率 在总线上传输数据的波特率（以比特\/秒为单位）。默认值来自 CAN 总线设备的设备描述文件 (*.devdesc)。您可以从列表框中选择波特率或直接在输入字段中输入。...", 
"body" : "一般的 网络 通过 CAN 总线接口链接的 CAN 网络的编号。允许的值：0 到 100。 波特率 在总线上传输数据的波特率（以比特\/秒为单位）。默认值来自 CAN 总线设备的设备描述文件 (*.devdesc)。您可以从列表框中选择波特率或直接在输入字段中输入。 " }, 
{ "title" : "选项卡：CANbus – NetX 配置 ", 
"url" : "_can_edt_canbus_netx_configuration.html", 
"breadcrumbs" : "CODESYS CANbus \/ 配置 \/ 选项卡：CANbus – NetX 配置 ", 
"snippet" : "作为通用 CAN 总线节点的替代方案，可以将 CAN 总线节点 (NetX) 添加到 NetX 现场总线的设备树中。为该节点提供了 NetX 配置对话框，用于选择 NetX 芯片（适配器插槽）和该芯片上的通信通道。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 NetX 设置 投币口 使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：默认情况下启用此选项。当它被停用时，系统会提示用户是否应该在下载或重...", 
"body" : "作为通用 CAN 总线节点的替代方案，可以将 CAN 总线节点 (NetX) 添加到 NetX 现场总线的设备树中。为该节点提供了 NetX 配置对话框，用于选择 NetX 芯片（适配器插槽）和该芯片上的通信通道。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 NetX 设置 投币口 使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：默认情况下启用此选项。当它被停用时，系统会提示用户是否应该在下载或重置时重新初始化总线。 注意：重新初始化会中断总线，并可能导致机器出现意外行为。 对于 NetX CAN，该选项被禁用。 " }, 
{ "title" : "职能 ", 
"url" : "_can_f_canbus_functions.html", 
"breadcrumbs" : "CODESYS CANbus \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "可以生 ", 
"url" : "_can_f_canbus_functions.html#UUID-2d2d9de7-12d6-74e9-de2f-9ac626632b88_section-idm4506522742524832570199555089", 
"breadcrumbs" : "CODESYS CANbus \/ 职能 \/ 可以生 ", 
"snippet" : "CODESYS 提供通过应用程序发送和接收 CAN 消息的能力。设备树中不需要任何设备来执行此操作。访问也可以与 CAN 堆栈并行执行。 基本上有两种选择： 通过 CANbus API 访问：您将在 CODESYS 商店 或者 CODESYS 美国商店 . 目标群体：应用程序程序员 通过图书馆访问 CAA Can Low Level Extern 目标群体：图书馆开发人员和专家 提示：您可以通过用例库插入 CAN L2 所需的所有库 CANbus ....", 
"body" : "CODESYS 提供通过应用程序发送和接收 CAN 消息的能力。设备树中不需要任何设备来执行此操作。访问也可以与 CAN 堆栈并行执行。 基本上有两种选择： 通过 CANbus API 访问：您将在 CODESYS 商店 或者 CODESYS 美国商店 . 目标群体：应用程序程序员 通过图书馆访问 CAA Can Low Level Extern 目标群体：图书馆开发人员和专家 提示：您可以通过用例库插入 CAN L2 所需的所有库 CANbus . " }, 
{ "title" : "重新配置 – CANbus ", 
"url" : "_can_f_canbus_functions.html#UUID-2d2d9de7-12d6-74e9-de2f-9ac626632b88_section-idm43264465111320", 
"breadcrumbs" : "CODESYS CANbus \/ 职能 \/ 重新配置 – CANbus ", 
"snippet" : "“重新配置”功能允许将最初下载到控制器的 CAN 总线配置动态调整到运行时的应用程序。 带功能块 DED.Reconfigure ，在启用通用设备诊断时可用 ( PLC 设置： )，您可以在运行时执行以下操作。 更改网络 ID ( CANbus_Diag.SetNetId (METH) 方法） 更改波特率 ( CANbus_Diag.SetBaudrate (METH) 方法）...", 
"body" : "“重新配置”功能允许将最初下载到控制器的 CAN 总线配置动态调整到运行时的应用程序。 带功能块 DED.Reconfigure ，在启用通用设备诊断时可用 ( PLC 设置： )，您可以在运行时执行以下操作。 更改网络 ID ( CANbus_Diag.SetNetId (METH) 方法） 更改波特率 ( CANbus_Diag.SetBaudrate (METH) 方法） " }, 
{ "title" : "诊断 ", 
"url" : "_can_f_canbus_diagnosis.html", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 ", 
"snippet" : "本章描述了 CAN 出现问题时的一般诊断 – 无论使用何种现场总线堆栈。大多数问题都可以追溯到不正确的接线或有故障的总线设备或 CAN 驱动程序。因此建议参考 硬件故障诊断 章节以及相应 CAN 控制器的诊断计数器。...", 
"body" : "本章描述了 CAN 出现问题时的一般诊断 – 无论使用何种现场总线堆栈。大多数问题都可以追溯到不正确的接线或有故障的总线设备或 CAN 驱动程序。因此建议参考 硬件故障诊断 章节以及相应 CAN 控制器的诊断计数器。 " }, 
{ "title" : "CANbus 诊断 ", 
"url" : "_can_f_canbus_diagnosis2.html", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ CANbus 诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "硬件故障诊断 ", 
"url" : "_can_f_canbus_diagnosis2.html#UUID-7e738421-21dd-2b6a-953c-bf3c2b9199c1_section-idm460850454796963257014143003", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ CANbus 诊断 \/ 硬件故障诊断 ", 
"snippet" : "大多数 CAN 问题可追溯到错误接线或有故障的 CAN 设备。潜在错误包括以下内容： 终端电阻缺失或尺寸不正确 总线必须在开始和结束时使用 120 Ω 终端电阻精确终止。 不同的波特率 所有用户都必须使用相同的波特率。 CANLow、CANHigh、CANGround、V+之间短路 CANLow 和 CANHigh 互换 CANHigh和CANLow的不同长度 CANHigh 和 CANLow 不是双绞线。结果，可以更容易地中断信号。 CANGround 的不同接地源 CAN总线电缆两侧接地 当 CAN 总线电缆的屏蔽两端都接地时，会形成接地回路，从而导致中断。 总线电缆太长 最大总线长度取决...", 
"body" : "大多数 CAN 问题可追溯到错误接线或有故障的 CAN 设备。潜在错误包括以下内容： 终端电阻缺失或尺寸不正确 总线必须在开始和结束时使用 120 Ω 终端电阻精确终止。 不同的波特率 所有用户都必须使用相同的波特率。 CANLow、CANHigh、CANGround、V+之间短路 CANLow 和 CANHigh 互换 CANHigh和CANLow的不同长度 CANHigh 和 CANLow 不是双绞线。结果，可以更容易地中断信号。 CANGround 的不同接地源 CAN总线电缆两侧接地 当 CAN 总线电缆的屏蔽两端都接地时，会形成接地回路，从而导致中断。 总线电缆太长 最大总线长度取决于设置的波特率（见表格）。 比特率 电缆长度 10 kbps 6.7公里 20 kbps 3.3公里 50 kbps 1.0公里 125 kbps 500米 250 kbps 250米 500 kbps 125米 1 Mbps 25米 " }, 
{ "title" : "检测硬件故障 ", 
"url" : "_can_f_canbus_diagnosis2.html#UUID-7e738421-21dd-2b6a-953c-bf3c2b9199c1_section-idm43257014307780", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ CANbus 诊断 \/ 检测硬件故障 ", 
"snippet" : "检查终端电阻 终端电阻用于使节点的阻抗适应所使用的传输电缆的阻抗。当阻抗不匹配时，传输的信号不会被负载完全吸收，部分会反射回传输电缆。如果源、传输电缆和负载的阻抗相同，则可以消除这些反射。在此测试中，测量 CAN 数据对电缆和连接的终端电阻的串联电阻。 关闭所有 CAN 节点的电源。 测量网络中间和末端CAN_H和CAN_L之间的电阻。 测量值应在 50 Ω 和 70 Ω 之间。该值应该在网络中的所有位置都相同。 如果该值小于 50 Ω，请确保以下几点： CAN_H 和 CAN_L 电缆之间没有短路。 存在的终端电阻不超过两个。 节点没有有缺陷的收发器。 如果该值大于 70 Ω，请确保以下事项...", 
"body" : "检查终端电阻 终端电阻用于使节点的阻抗适应所使用的传输电缆的阻抗。当阻抗不匹配时，传输的信号不会被负载完全吸收，部分会反射回传输电缆。如果源、传输电缆和负载的阻抗相同，则可以消除这些反射。在此测试中，测量 CAN 数据对电缆和连接的终端电阻的串联电阻。 关闭所有 CAN 节点的电源。 测量网络中间和末端CAN_H和CAN_L之间的电阻。 测量值应在 50 Ω 和 70 Ω 之间。该值应该在网络中的所有位置都相同。 如果该值小于 50 Ω，请确保以下几点： CAN_H 和 CAN_L 电缆之间没有短路。 存在的终端电阻不超过两个。 节点没有有缺陷的收发器。 如果该值大于 70 Ω，请确保以下事项： CAN_H 和 CAN_L 电缆的接线不存在开路。 总线系统有两个终端电阻，每个 120 Ω – 每端一个。 CAN_H\/CAN_L 电压 每个节点都包含一个发送不同信号的 CAN 收发器。当网络通信空闲时，电压 CAN_H 和 CAN_L 约为 2.5 V。有故障的收发器会导致开路电压变化并中断网络通信。 关闭所有 CAN 节点的电源。 停止所有网络通信。 测量 CAN_H 和 GND 之间的直流电流。 测量值应在 2.0 V 和 4.0 V 之间。如果小于 2.0 V 或大于 4.0 V，则可能是一个或多个节点的收发器出现故障。 在电压低于 2.0 V 时，您需要检查 CAN_H 和 CAN_L 电缆的导通性。 在电压大于 4.0 V 时，您需要检查是否过压。 地面 CAN 网络的屏蔽层可能仅在一处接地。该测试表明屏蔽是否在多个位置接地。 将屏蔽层与地面分开。 测量屏蔽层与地之间的直流电阻。 将屏蔽层接地。 电阻应大于 1 MΩ。如果它较低，那么您需要寻找额外的屏蔽接地。 CAN收发器电阻检查 CAN 收发器有一个控制 CAN_H 的电路和另一个控制 CAN_L 的电路。经验表明，一个或两个电路的电气损坏会增加这些电路中的漏电流。 使用电阻测量仪测量泄漏电流。 将节点与网络分开。让节点没有任何电流。 测量 CAN_H 和 CAN_GND 之间的直流电阻。 测量 CAN_L 和 CAN_GND 之间的直流电阻。 通常电阻应在 1 MΩ 和 4 MΩ 之间或更高。如果低于此范围，则 CAN 收发器可能有故障。 " }, 
{ "title" : "CAN控制器的错误处理 ", 
"url" : "_can_f_canbus_diagnosis2.html#UUID-7e738421-21dd-2b6a-953c-bf3c2b9199c1_section-idm4567920396942432570144948023", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ CANbus 诊断 \/ CAN控制器的错误处理 ", 
"snippet" : "错误处理集成到 CAN 协议中，对 CAN 系统的性能极为重要。错误处理旨在检测 CAN 消息中的错误，以便发送方可以重新发送失败的消息。每个 CAN 控制器都试图检测消息中的错误。当发现错误时，检测节点会发送错误标志，从而中断总线流量。其他节点将检测由错误标志引起的错误（如果它们尚未检测到原始错误）。他们将采取适当的措施并拒绝当前消息。 这些计数器以及总线状态通常在诊断 CAN 错误时提供对错误原因的初步了解。该信息可在 CODESYS 通过用户界面和应用程序。...", 
"body" : "错误处理集成到 CAN 协议中，对 CAN 系统的性能极为重要。错误处理旨在检测 CAN 消息中的错误，以便发送方可以重新发送失败的消息。每个 CAN 控制器都试图检测消息中的错误。当发现错误时，检测节点会发送错误标志，从而中断总线流量。其他节点将检测由错误标志引起的错误（如果它们尚未检测到原始错误）。他们将采取适当的措施并拒绝当前消息。 这些计数器以及总线状态通常在诊断 CAN 错误时提供对错误原因的初步了解。该信息可在 CODESYS 通过用户界面和应用程序。 " }, 
{ "title" : "应用中的诊断 ", 
"url" : "_can_canbus_diagnosis_application.html", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 应用中的诊断 ", 
"snippet" : "CAN 总线的状态可以通过 CAA 设备诊断接口查询。这是通过功能块完成的 CANbus_Diag 从图书馆 CANbusDevice .该功能块是为 CAN 总线隐式创建的，可以使用设备树中的设备名称进行寻址。 对于这个函数， 设备诊断 必须启用。 图书馆 CAA Can Low Level Extern 提供芯片级的总线诊断。在具有基于 CAN 的现场总线堆栈的应用程序中，通常不需要读取此内容。这些功能通常由现场总线堆栈使用，并以合适的方式提供给应用程序（参见相应现场总线的章节）。因此，大多数情况下，只有在检查非常特殊的错误或编写 CAN 原始应用程序时才需要这些功能。 大多数诊断信息也显...", 
"body" : "CAN 总线的状态可以通过 CAA 设备诊断接口查询。这是通过功能块完成的 CANbus_Diag 从图书馆 CANbusDevice .该功能块是为 CAN 总线隐式创建的，可以使用设备树中的设备名称进行寻址。 对于这个函数， 设备诊断 必须启用。 图书馆 CAA Can Low Level Extern 提供芯片级的总线诊断。在具有基于 CAN 的现场总线堆栈的应用程序中，通常不需要读取此内容。这些功能通常由现场总线堆栈使用，并以合适的方式提供给应用程序（参见相应现场总线的章节）。因此，大多数情况下，只有在检查非常特殊的错误或编写 CAN 原始应用程序时才需要这些功能。 大多数诊断信息也显示在记录器和 CANbus 的状态页面上。 " }, 
{ "title" : "用户界面中的诊断 ", 
"url" : "_can_f_canbus_diagnosis_ui.html", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 用户界面中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设备树 ", 
"url" : "_can_f_canbus_diagnosis_ui.html#UUID-c7a66aad-bbd2-481f-3711-be1617950367_section-idm43257005043230", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 用户界面中的诊断 \/ 设备树 ", 
"snippet" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色三角形）：硬错误，例如设备不正确\/丢失或连接中断。 诊断标志（红色感叹号）：表示诊断条目当前可用于该设备。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。...", 
"body" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色三角形）：硬错误，例如设备不正确\/丢失或连接中断。 诊断标志（红色感叹号）：表示诊断条目当前可用于该设备。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。 " }, 
{ "title" : "状态页面 ", 
"url" : "_can_f_canbus_diagnosis_ui.html#UUID-c7a66aad-bbd2-481f-3711-be1617950367_section-idm43257005150700", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 用户界面中的诊断 \/ 状态页面 ", 
"snippet" : "CAN 总线状态页面显示总线状态、诊断信息和各种参数的状态。在此页面上，您可以检查消息是否已发送和接收或丢失。此外，您可以查看驱动程序是否可以打开（ 驱动程序实例 > 0, 最后驱动程序打开错误 ）。...", 
"body" : "CAN 总线状态页面显示总线状态、诊断信息和各种参数的状态。在此页面上，您可以检查消息是否已发送和接收或丢失。此外，您可以查看驱动程序是否可以打开（ 驱动程序实例 > 0, 最后驱动程序打开错误 ）。 " }, 
{ "title" : "记录器页面 ", 
"url" : "_can_f_canbus_diagnosis_ui.html#UUID-c7a66aad-bbd2-481f-3711-be1617950367_section-idm43257005247310", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 用户界面中的诊断 \/ 记录器页面 ", 
"snippet" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。此视图仅显示由相应设备创建的条目。...", 
"body" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。此视图仅显示由相应设备创建的条目。 " }, 
{ "title" : "故障排除 ", 
"url" : "_can_canbus_diagnosis_trouble_shooting.html", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 故障排除 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "总线 ", 
"url" : "_can_canbus_diagnosis_trouble_shooting.html#UUID-3e2619e3-c9f8-1410-5ebc-278391a86c97_id_d8448d6e6348d4cc0a8646347895676-id-bfade9ddc5dc434fc0a86463543065b1", 
"breadcrumbs" : "CODESYS CANbus \/ 诊断 \/ 故障排除 \/ 总线 ", 
"snippet" : "问题 可能的解决方案 CANbus 在应用程序下载后直接在设备树中显示为红色。 检查 CAN 总线的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 驱动无法打开： 网络 ID 设置过大。 在 CAN 总线中，设置了一个没有驱动程序实例的网络 ID。如果控制器只有两个 CAN 接口，则网络 ID 的有效值只有 0 和 1。 驱动程序组件未在运行时加载。 检查 CAN 驱动组件是否已正确加载（参见记录器和“运行时配置”一章）。 内存不足。 打开 CAN 驱动程序需要内存。可用的内存可能太少。 发生总线错误： CAN 芯片发出总线错误信号。 有关更多信息，请参阅： 硬件故障诊断 CAN...", 
"body" : "问题 可能的解决方案 CANbus 在应用程序下载后直接在设备树中显示为红色。 检查 CAN 总线的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 驱动无法打开： 网络 ID 设置过大。 在 CAN 总线中，设置了一个没有驱动程序实例的网络 ID。如果控制器只有两个 CAN 接口，则网络 ID 的有效值只有 0 和 1。 驱动程序组件未在运行时加载。 检查 CAN 驱动组件是否已正确加载（参见记录器和“运行时配置”一章）。 内存不足。 打开 CAN 驱动程序需要内存。可用的内存可能太少。 发生总线错误： CAN 芯片发出总线错误信号。 有关更多信息，请参阅： 硬件故障诊断 CAN 总线在红色和绿色之间切换或在运行模式下保持红色。 检查 CAN 总线的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 发生总线错误。 CAN 芯片发出总线错误信号。请参阅“硬件故障诊断”一章。 CAN 总线有一个红色感叹号。 检查 CAN 总线的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 公交车警告正在排队。 CAN 芯片发出总线警告信号。总线订阅者可以发送和接收消息，但这可能会导致意外行为，因为 CAN 报文可能会丢失。 检查电缆。 有关更多信息，请参阅： 硬件故障诊断 CAN 总线有一个灰色的感叹号。 检查 CAN 总线的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 过去发生的错误已被更正。例如，这可能是 CANLow 和 CANHigh 之间的临时短路。可以在状态页面上通过单击确认错误 确认 按钮或 CAN 总线上下文菜单中的命令。 " }, 
{ "title" : "库：CANbus ", 
"url" : "_can_canbus_libraries.html", 
"breadcrumbs" : "CODESYS CANbus \/ 库：CANbus ", 
"snippet" : "CANbus设备 CAA CAN 低级外部 CAA CAN 低电平阻抗 CANbus 用例库...", 
"body" : "CANbus设备 CAA CAN 低级外部 CAA CAN 低电平阻抗 CANbus 用例库 " }, 
{ "title" : "运行时配置 ", 
"url" : "_can_f_canbus_runtime.html", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "安装 PCAN USB 适配器 ", 
"url" : "_can_f_canbus_runtime.html#UUID-a1406f7b-cf41-572d-78b8-cdd18e4e910c_section-idm4613673094668832570205959287", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 \/ 安装 PCAN USB 适配器 ", 
"snippet" : "组件 CmpPCANBasicDrv 基于 PCAN Basic API，支持 USB 加密狗和其他硬件。更多信息请参见公司主页“PEAK System”。 仅针对 PCAN Basic API 实现了对 PCAN Basic API 的支持 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Ga...", 
"body" : "组件 CmpPCANBasicDrv 基于 PCAN Basic API，支持 USB 加密狗和其他硬件。更多信息请参见公司主页“PEAK System”。 仅针对 PCAN Basic API 实现了对 PCAN Basic API 的支持 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Gateway V3 , 然后打开 Gateway.cfg . 将以下行添加到该部分 [ComponentManager] ： Component.X=CmpPCANBasicDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 启动运行时系统。 CODESYS 在 PLC 记录器中显示检测到的 PCAN 硬件和相应的 CAN 网络号。 输入 CAN 网络号 网络 CANbus 的 一般的 标签。 " }, 
{ "title" : "安装 Sontheim USB 适配器 ", 
"url" : "_can_f_canbus_runtime.html#UUID-a1406f7b-cf41-572d-78b8-cdd18e4e910c_section-idm4613673489152032570208577596", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 \/ 安装 Sontheim USB 适配器 ", 
"snippet" : "CmpCANFoxDrv 组件基于 Sontheim MT API，支持 USB 加密狗和其他硬件。更多信息请参见“Sontheim Industrie Elektronik GmbH”公司主页。 对 MT API 的支持仅适用于 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Gateway ...", 
"body" : "CmpCANFoxDrv 组件基于 Sontheim MT API，支持 USB 加密狗和其他硬件。更多信息请参见“Sontheim Industrie Elektronik GmbH”公司主页。 对 MT API 的支持仅适用于 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Gateway V3 , 然后打开 Gateway.cfg . 将以下行添加到该部分 [ComponentManager] ： Component.X=CmpCANFoxDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 启动运行时系统。 CODESYS 在 PLC 记录器中显示检测到的 MT API 硬件（例如：CANfox）和相应的 CAN 网络号。 输入 CAN 网络号 网络 CANbus 的 一般的 标签。 " }, 
{ "title" : "安装 Ixxat USB 适配器 ", 
"url" : "_can_f_canbus_runtime.html#UUID-a1406f7b-cf41-572d-78b8-cdd18e4e910c_section-idm4613673204236832570210249075", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 \/ 安装 Ixxat USB 适配器 ", 
"snippet" : "CmpIxxatCANDrv 组件基于支持 USB 加密狗和其他硬件的 Ixxat VCI V4 API。更多信息请参见“HMS Industrial Networks”公司主页。 仅针对 Ixxat VCI V4 API 实施支持 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Gateway...", 
"body" : "CmpIxxatCANDrv 组件基于支持 USB 加密狗和其他硬件的 Ixxat VCI V4 API。更多信息请参见“HMS Industrial Networks”公司主页。 仅针对 Ixxat VCI V4 API 实施支持 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Gateway V3 , 然后打开 Gateway.cfg . 将以下行添加到该部分 [ComponentManager] ： Component.X=CmpIxxatCANDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 启动运行时系统。 CODESYS 在 PLC 记录器中显示检测到的 Ixxat 硬件和相应的 CAN 网络编号。 输入 CAN 网络号 网络 CANbus 的 一般的 标签。 " }, 
{ "title" : "安装 Kvaser USB 适配器 ", 
"url" : "_can_f_canbus_runtime.html#UUID-a1406f7b-cf41-572d-78b8-cdd18e4e910c_section-idm4587237127579232570211920393", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 \/ 安装 Kvaser USB 适配器 ", 
"snippet" : "CmpKvaserCANDrv 组件基于 Kvaser CANBus-API (CANlib)，它支持 USB 加密狗和其他硬件。见Kvaser公司主页（ www.kvaser.com ) 了解更多信息。 对 Kvaser API 的支持仅适用于 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS ...", 
"body" : "CmpKvaserCANDrv 组件基于 Kvaser CANBus-API (CANlib)，它支持 USB 加密狗和其他硬件。见Kvaser公司主页（ www.kvaser.com ) 了解更多信息。 对 Kvaser API 的支持仅适用于 CODESYS Control Win 和 CODESYS Gateway V3 . 为此，请按照以下步骤操作： 从制造商网站下载驱动程序并将其安装在 Windows 操作系统上。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 如果你想使用 CODESYS Gateway V3 , 然后打开 Gateway.cfg . 将以下行添加到该部分 [ComponentManager] ： Component.X=CmpKvaserCANDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 启动运行时系统。 CODESYS 在 PLC 记录器中显示检测到的 Kvaser 硬件和相应的 CAN 网络号。 输入 CAN 网络号 网络 CANbus 的 一般的 标签。 " }, 
{ "title" : "安装 SJA1000 控制器 ", 
"url" : "_can_f_canbus_runtime.html#UUID-a1406f7b-cf41-572d-78b8-cdd18e4e910c_section-idm4613673488225632570214103835", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 \/ 安装 SJA1000 控制器 ", 
"snippet" : "这 CODESYS Control Win 运行时系统支持基于 CAN 控制器 SJA1000 的通用驱动程序“CmpSJACanDrv”。 安装适配器后，必须从“W2K_XP_Drivers”目录（在 RTE 安装目录中）安装相应的驱动程序。 为此，请按照以下步骤操作： 打开 RTE 配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\Gateway PLC . 将以下行添加到该部分 [ComponentManager] ： Component.X=CmpSJACanDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，...", 
"body" : "这 CODESYS Control Win 运行时系统支持基于 CAN 控制器 SJA1000 的通用驱动程序“CmpSJACanDrv”。 安装适配器后，必须从“W2K_XP_Drivers”目录（在 RTE 安装目录中）安装相应的驱动程序。 为此，请按照以下步骤操作： 打开 RTE 配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\Gateway PLC . 将以下行添加到该部分 [ComponentManager] ： Component.X=CmpSJACanDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 有关参数的详细说明，请参见文档“CODESYSControlRTEV3_Manual.pdf”。 RTE 设置也可以在 RTE 配置对话框中进行编辑。 " }, 
{ "title" : "安装 EtherCAT\/CAN 网关 EL6751 ", 
"url" : "_can_f_canbus_runtime.html#UUID-a1406f7b-cf41-572d-78b8-cdd18e4e910c_section-idm43315260968352", 
"breadcrumbs" : "CODESYS CANbus \/ 运行时配置 \/ 安装 EtherCAT\/CAN 网关 EL6751 ", 
"snippet" : "该功能仅适用于 CANopen Master\/Slave EL6751 终端，不适用于 CANopen Slave EL6751-0010 终端。 为此，请按照以下步骤操作： 安装 EtherCAT 包裹。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 将以下行添加到该部分 [ComponentManager] ： Component.X= CmpEL6751CanDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 在项目中，插入 E...", 
"body" : "该功能仅适用于 CANopen Master\/Slave EL6751 终端，不适用于 CANopen Slave EL6751-0010 终端。 为此，请按照以下步骤操作： 安装 EtherCAT 包裹。 打开PLC配置文件 CODESYSControl.cfg 在文本编辑器中。该文件位于 CODESYS 安装目录 \\GatewayPLC . 将以下行添加到该部分 [ComponentManager] ： Component.X= CmpEL6751CanDrv . 检查组件编号 X (X=1,2,3, ...) 是否是连续的，没有任何缺失的编号。 保存更改并关闭编辑器。 在项目中，插入 EtherCAT 掌握。 运行设备扫描 EtherCAT 掌握。如果硬件对您不可用，那么您也可以手动插入设备描述。 CODESYS 找到 EL6751 终端。 选择 CAN 微型驱动程序设备描述。 不要选择 Beckhoff 的原始设备描述。相反，需要 CAN 微型驱动程序设备描述。此设备说明随 EtherCAT 包裹。 消息数表示每个周期可以接收或发送的 CAN 消息的最大数量（这意味着有多少消息通过隧道传输） EtherCAT 每帧）。 插入扫描的设备。 现在您可以在 CANbus 节点下方插入基于 CAN 的堆栈，例如 CANopenManager、CANopenDevice 或 J1939Manager。然后你可以像往常一样使用它们。在 CANbus 节点中，您只能更改波特率。网络 ID 在运行时自动分配。或者，您也可以通过 CL2 或 CAN-API 寻址 CAN。 您可以通过相应的功能块获取打开驱动程序的网络ID。 你应该设置 EtherCAT 总线任务，使其足够快。例如，如果您想以 4ms 的间隔发送或接收 CAN 报文，则应将总线周期任务设置为至少 4ms（或更快更好），以便能够保持发送间隔。 " }, 
{ "title" : "CANopen 管理器（主站） ", 
"url" : "_can_f_canopen_manager.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "一般的 ", 
"url" : "_can_f_canopen_manager_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 一般的 ", 
"snippet" : "CANopen 管理器是 CAN 总线主控器，插入到 CAN 总线节点下方的 CAN 总线配置中。 CODESYS 提供以下 CANopen 主站： CANopen 管理器 (1) CANopen 管理器 SIL2 (2) CANopen Manager SoftMotion：可插入SoftMotion控制器下方；包含适用于通过 CANbus 进行运动操作的预设。 在 CODESYS , CANopen 远程设备是您插入项目设备树中 CANopen 管理器下方的从设备。模块化和非模块化从站之间存在区别： 模块化从站 ：您可以在模块化从站下方插入 CANopen 模块（子模块）。这些模块提供了一...", 
"body" : "CANopen 管理器是 CAN 总线主控器，插入到 CAN 总线节点下方的 CAN 总线配置中。 CODESYS 提供以下 CANopen 主站： CANopen 管理器 (1) CANopen 管理器 SIL2 (2) CANopen Manager SoftMotion：可插入SoftMotion控制器下方；包含适用于通过 CANbus 进行运动操作的预设。 在 CODESYS , CANopen 远程设备是您插入项目设备树中 CANopen 管理器下方的从设备。模块化和非模块化从站之间存在区别： 模块化从站 ：您可以在模块化从站下方插入 CANopen 模块（子模块）。这些模块提供了一个 I\/O 映射 标签来“映射”他们的输入和输出。模块化从站也可以有固定的 I\/O。然后这些设备还提供 I\/O 映射 标签。模块化设备提供 自动配置 PDO 映射 选项，我们推荐用于标准应用程序。您可以在 CANopen 远程设备 对话框，在 一般的 标签。 非模块化从站 ：您不能在非模块化设备下方插入额外的模块。这些设备的输入和输出被“映射”在 I\/O 映射 对话。自动映射在这里是不可能的。 " }, 
{ "title" : "配置 ", 
"url" : "_can_f_canopen_manager_configuration.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 " }, 
{ "title" : "选项卡：CANopen 管理器 – 常规 ", 
"url" : "_can_edt_canopen_manager_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 管理器 – 常规 ", 
"snippet" : "一般的 节点 ID 节点号将 CANopen 管理器标识为唯一的（值范围：1...127）。 检查并修复配置 打开同名对话框。详情见下文。 自动启动 CANopen 管理器 ：在所有需要的从站都准备好后，CANopen 管理器自动启动（切换到操作模式）。 ：必须从应用程序启动 CANopen 管理器。这 CiA405.NMT 功能块可用于执行此操作。 提示：只要 CANopen 管理器不处于 OPERATIONAL 模式，就不会发送 PDO（刷新输出）。 轮询可选从站 ：当从站在引导过程中没有响应时，CANopen 管理器每秒都会询问它，直到它响应为止。 不断轮询从站会增加总线循环时间，这可能...", 
"body" : "一般的 节点 ID 节点号将 CANopen 管理器标识为唯一的（值范围：1...127）。 检查并修复配置 打开同名对话框。详情见下文。 自动启动 CANopen 管理器 ：在所有需要的从站都准备好后，CANopen 管理器自动启动（切换到操作模式）。 ：必须从应用程序启动 CANopen 管理器。这 CiA405.NMT 功能块可用于执行此操作。 提示：只要 CANopen 管理器不处于 OPERATIONAL 模式，就不会发送 PDO（刷新输出）。 轮询可选从站 ：当从站在引导过程中没有响应时，CANopen 管理器每秒都会询问它，直到它响应为止。 不断轮询从站会增加总线循环时间，这可能会干扰应用程序（尤其是运动应用程序）。您可以停用轮询以避免此行为。如果轮询被禁用，则在发送启动消息时会再次检测到从站。 启动奴隶 ： CANopen 管理器负责启动从站。 ：您必须从应用程序启动从站。使用 CiA405 NMT 功能块来执行此操作。 NMT 全部启动（如果可能） : 如果 启动奴隶 选项被激活，然后 CANopen 管理器使用“NMT Start All”命令启动所有从站。只要可选从站尚未准备好启动，就不会执行“NMT Start All”命令。在这种情况下，CANopen 管理器单独启动每个从站。 “NMT Start All”命令只能在没有可选从站的项目中得到保证。 NMT 错误行为 重启从机 .如果在从站监控期间发生错误（NMT 错误事件），则从站会通过堆栈自动重启（NMT 复位 + SDO 配置 + NMT 启动）。 停止奴隶 .如果在从站监视期间发生错误（NMT 错误事件），则从站停止。然后您必须使用 CiA405 NMT 功能块从应用程序中复位从站。 守护 使用心跳消息是另一种监控方法。它可以从主节点和从节点执行，而不是节点保护。通常，主站向从站发送心跳消息。 启用心跳产生 主机发送心跳。他们定义了时间间隔 制作人时间 .当给从机提供心跳功能时，会为主机创建一个来自从机的心跳消费条目。然后应用 Node-ID 和 master 的 1.5 倍心跳间隔。 ：为从站启用节点保护。从站的 EDS 文件中的设置用于此目的。如果无法使用那里的值，则使用默认值。请注意，CANopen 从站设备也可以配置为心跳生产者。 节点 ID 总线上心跳生产者的唯一标识（1-127） 生产者时间（毫秒） 连续心跳之间的间隔长度（以毫秒为单位） 冗余节点 ID 要求：一个 冗余配置 对象被插入到应用程序下方。 总线上冗余心跳生产者的唯一标识（1-127） 冗余等待时间 (µs) 要求：一个 冗余配置 对象插入到应用程序下方。 被动控制器等待主动控制器心跳的持续时间。如果超过了这个时间，那么被动控制器就会扮演主动角色。 同步 启用同步制作 ：CANopen 管理器发送 SYNC 报文（默认禁用） 同步 PDO 在 SYNC 报文之后直接发送。 COB-ID（十六进制） SYNC 报文的 CAN-ID。可能值的范围：[1...2047]。 周期（微秒） 发送 SYNC 电报的间隔长度（以微秒为单位） 窗口长度 (µs) 同步 PDO 的时间范围的长度（以微秒为单位） 启用同步消费 :（默认禁用）。另一个设备必须生成 CANopen 管理器接收的 SYNC 报文。 如果为 CANopen 管理器启用了 SYNC 生成，则不允许您选择 启用同步制作 所有其他总线设备的选项。 时间 启用 TIME 生产 :（默认禁用）。 CANopen 管理器发送 TIME 消息。 COB-ID（十六进制） (Communication Object Identifier)：标识消息的时间戳。默认值：[0...2047]，预设 16#100 生产者时间（毫秒） ： 发送时间戳的时间间隔（以毫秒为单位）。该值必须是任务循环时间的倍数。可能的值 [0, 65535] 运行时必须支持“高分辨率时间戳”。如果不是，则显示错误消息。 " }, 
{ "title" : "对话框：检查并修复配置 ", 
"url" : "_can_edt_canopen_manager_general.html#UUID-816f1134-3c06-5152-cb5e-ffd3d63b9ea5_id_e533e26901eac0a8640e00fc1613-id-e444138f292a11e5a277db1995079930", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 管理器 – 常规 \/ 对话框：检查并修复配置 ", 
"snippet" : "当您在 CANopen 管理器下方插入多个设备时，错误消息可能会报告多个分配的节点 ID 或无效的 COB-ID。这 检查并修复配置 按钮打开一个对话框来解决这些冲突。 对于与节点 ID 或 PDO COB-ID 的冲突，您可以单击 编辑冲突 打开包含详细信息的对话框。 节点 ID 和 COB-ID 冲突 节点数加倍 具有相同 ID 的所有设备的列表。在该领域 节点 ID 列，您可以为受影响的设备输入新的节点号。 PDO COB-ID 的错误和重复分配 可能不允许从设备描述文件中自动生成的 COB-ID。所有不正确的条目都与各自的设备名称、节点 ID 和索引一起列出。纠正无效 COB-ID 的...", 
"body" : "当您在 CANopen 管理器下方插入多个设备时，错误消息可能会报告多个分配的节点 ID 或无效的 COB-ID。这 检查并修复配置 按钮打开一个对话框来解决这些冲突。 对于与节点 ID 或 PDO COB-ID 的冲突，您可以单击 编辑冲突 打开包含详细信息的对话框。 节点 ID 和 COB-ID 冲突 节点数加倍 具有相同 ID 的所有设备的列表。在该领域 节点 ID 列，您可以为受影响的设备输入新的节点号。 PDO COB-ID 的错误和重复分配 可能不允许从设备描述文件中自动生成的 COB-ID。所有不正确的条目都与各自的设备名称、节点 ID 和索引一起列出。纠正无效 COB-ID 的三个选项： 更正显示的计算 COB-ID 的公式，以便生成有效的 COB-ID。您可以更改相应表格元素中的公式。 通过单击相应的按钮接受 COB-ID 的自动建议。 通过单击接受所有自动建议 使用建议的 COB-ID 按钮。 更正的条目会自动从显示的列表中删除。 您可以使用 自动修复 .该命令将所有时序值修改为兼容值。 （时间应该是任务时间的倍数。） " }, 
{ "title" : "选项卡：CANopen 远程设备 - 常规 ", 
"url" : "_can_edt_canopen_remote_device_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 远程设备 - 常规 ", 
"snippet" : "CANopen 从站的一般设置在 CANopen 远程设备（从站）的此对话框中定义。 一般的 节点 ID 节点号唯一标识 CANopen 远程设备。它对应于设备（硬件）上设置的数字（1 到 127 之间的值）。您必须以十进制形式提供节点 ID。 专家设置 ：显示由设备的设备描述（EDS 文件）预定义的所有设置。 SDO 通道 (...) 单击此按钮可打开一个对话框，用于激活 EDS 文件中预定义的 SDO 通道。服务数据对象 (SDO) 允许访问 CANopen 对象目录中的所有条目。 SDO 在两个设备（SDO 服务器和客户端通道）之间创建对等通信通道。 可选设备 ：从站是可选的，不需要启动...", 
"body" : "CANopen 从站的一般设置在 CANopen 远程设备（从站）的此对话框中定义。 一般的 节点 ID 节点号唯一标识 CANopen 远程设备。它对应于设备（硬件）上设置的数字（1 到 127 之间的值）。您必须以十进制形式提供节点 ID。 专家设置 ：显示由设备的设备描述（EDS 文件）预定义的所有设置。 SDO 通道 (...) 单击此按钮可打开一个对话框，用于激活 EDS 文件中预定义的 SDO 通道。服务数据对象 (SDO) 允许访问 CANopen 对象目录中的所有条目。 SDO 在两个设备（SDO 服务器和客户端通道）之间创建对等通信通道。 可选设备 ：从站是可选的，不需要启动 CAN 网络。 同步制作 仅当 启用同步制作 选项在 CANopen 管理器中被清除。 ：I\/O 传输在总线上同步。从站作为同步生产者工作。同步间隔的参数在 CANopen 管理器的设置中定义。 无初始化 此选项适用于已经以有效配置开始的不可配置从站。 ：主机不向从机发送配置 SDO 或 NMT 启动命令。 PDO 通信和监控（心跳、节点保护）在配置器中配置后执行。 如果从机没有自动启动，则用户可以使用 CiA405 NMT 功能块向从机发送 NMT 启动命令。 默认设置 此选项的可用性取决于设备描述文件的内容。 ：默认激活。从节点在配置加载到设备之前或始终在配置从节点时重置为默认参数。可以设置哪些参数是设备特定的。具体任务是从列表框的子索引中执行的。 子：001 : 所有参数都被重置。 子：002 ：通讯参数（索引 1000h–1FFFh 制造商特定的通讯参数）被复位。 子：003 : 应用参数（索引 6000h–9FFFh 制造商特定的应用参数）被重置。 子：004 – 子：127 : 制造商特定的、单独的参数选择被重置。 子：128 – 子254 : 留作将来使用 自动配置 PDO 映射 . 此选项仅适用于模块化设备。 ：PDO 映射是根据设备描述中的定义自动生成的，然后无法在两个映射对话框中更改。如果自动生成的映射与您的应用程序不匹配，那么您可以停用该选项并手动配置映射。我们建议为标准应用程序激活此选项。 节点保护 节点保护是一种过时的监控方法，不应再使用，因为它使用 RTR 帧。您应该始终尽可能使用心跳。在某些例外情况下，例如对于较旧的从站，您只能使用节点保护。 启用节点保护 ：CANopen 管理器向从站发送消息 保护时间（毫秒） 间隔。如果从机没有响应给定的 保护 COB-ID （通信对象标识符），然后 CANopen 管理器重新发送此消息的次数与定义 寿命因素 或直到从机响应。 如果从机没有响应，则将其标记为“不可用”。 保护时间（毫秒） 发送消息的间隔（默认：200 毫秒） 寿命因素 当从机没有响应时，根据 寿命因素 时间乘以 守卫时间 . 启用心跳产生 ：模块在给定的时间间隔内发送心跳 生产者时间（毫秒） . 生产者时间（毫秒） ： 只要没有特殊条目或设备描述文件中的条目为 0，默认设置为 200。 心跳消耗（...） 打开一个 心跳消耗属性 对话。在那里你激活你想看的奴隶。 在 EDS 文件中定义了要监控的可能从站的数量。为此，您必须选中“启用”复选框并在从站的节点 ID 和所需的值输入 心跳时间 字段（以毫秒为单位）。然后从站监视从受影响的从站（由节点 ID 定义）发送的心跳。当不再接收到心跳时，从站关闭 I\/O。 当一个从站正在监控时，一个绿色的复选标记会显示在 心跳消耗 按钮。 笔记 ：当您插入具有心跳功能的设备时，其心跳设置会自动与主站（CANopen 管理器）协调一致。 紧急情况 激活紧急情况 ：发生内部错误时，从站发送带有唯一 COB-ID 的紧急消息。您可以使用库中的功能块来阅读这些消息 CAA Can Low Level Extern ( RECV_EMCY_DEF , RECV_EMCY ）。 COB-ID EMCY 消息的 CAN ID。可能值的范围：[1...2047]。 时间 此功能的可用性取决于设备描述。 启用 TIME 生产 ：设备发送 TIME 消息。 COB-ID（十六进制） (Communication Object Identifier)：标识消息的时间戳。 启用耗时 ：设备处理 TIME 消息。 启动时检查 从 CANopen 从站（0x1018 身份对象）的固件中读取相应的信息，并与 EDS 文件中的信息进行比较。在不一致的情况下，停止配置并且不启动从站。 供应商编号 ：在启动时检查供应商 ID 产品编号 ：启动时检查产品编号 修订号 : 启动时检查版本号 " }, 
{ "title" : "选项卡：CANopen 设备 – PDO ", 
"url" : "_can_edt_canopen_device_pdos.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 设备 – PDO ", 
"snippet" : "对象：CANopen 远程设备、CANopen 本地设备 此对话框仅在版本 V3.5.6.0 或更高版本的 CANopen 从站的设备编辑器中可用。它显示所有 PDO 及其默认设置。在此对话框中，您可以添加新对象以及删除或编辑现有对象。 在左侧，有从站从主站接收的 PDO。在右侧，有从站发送给主站的 PDO。 添加 PDO 打开 选择 PDO 显示所有可用 PDO 的对话框。在此对话框中，选择要添加到的 PDO 接收 PDO 或者 发送 PDO . 添加映射 打开 从对象目录中选择项目 对话。那里列出了可以添加到 PDO 映射的对象。 编辑 选择PDO时， PDO 属性 对话框打开。 选择PD...", 
"body" : "对象：CANopen 远程设备、CANopen 本地设备 此对话框仅在版本 V3.5.6.0 或更高版本的 CANopen 从站的设备编辑器中可用。它显示所有 PDO 及其默认设置。在此对话框中，您可以添加新对象以及删除或编辑现有对象。 在左侧，有从站从主站接收的 PDO。在右侧，有从站发送给主站的 PDO。 添加 PDO 打开 选择 PDO 显示所有可用 PDO 的对话框。在此对话框中，选择要添加到的 PDO 接收 PDO 或者 发送 PDO . 添加映射 打开 从对象目录中选择项目 对话。那里列出了可以添加到 PDO 映射的对象。 编辑 选择PDO时， PDO 属性 对话框打开。 选择PDO映射时， 从对象目录中选择项目 对话框打开。 删除 从列表中删除选定的对象 提升 将选定对象向上移动一行。 下移 将选定对象向下移动一行。 " }, 
{ "title" : "对话框：PDO 属性 ", 
"url" : "_can_edt_canopen_device_pdos.html#UUID-cddcb61f-bf3f-83bd-0cac-dbedbbd21e7f_id_c45dd0c9e26ba3ecc0a8640e016944ea-id-c4e82b9414c0f026c0a8640e00f1a2da", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 设备 – PDO \/ 对话框：PDO 属性 ", 
"snippet" : "COB-ID 每个 PDO 消息都必须有一个 COB-ID（通信对象标识符）。您可以输入显式值（例如：16#201）或公式（例如：$NODEID+16#200）。 RTR 远程传输请求。此选项仅适用于传输 PDO。 ：您可以使用 RTR 帧从外部询问 PDO。 抑制时间 (x 100µs) 仅当设备支持此功能时，您才能编辑此字段。禁止时间是特定 PDO 的两条消息之间的最短时间。您可以使用此设置来防止在编辑 PDO 的值时过于频繁地发送它们。默认值：“0”。可能的值：0–65535。 传输类型 非循环 - 同步 ：当发生变化时，PDO 是同步传输的，但不是周期性的。 （默认） 循环 - 同步 ...", 
"body" : "COB-ID 每个 PDO 消息都必须有一个 COB-ID（通信对象标识符）。您可以输入显式值（例如：16#201）或公式（例如：$NODEID+16#200）。 RTR 远程传输请求。此选项仅适用于传输 PDO。 ：您可以使用 RTR 帧从外部询问 PDO。 抑制时间 (x 100µs) 仅当设备支持此功能时，您才能编辑此字段。禁止时间是特定 PDO 的两条消息之间的最短时间。您可以使用此设置来防止在编辑 PDO 的值时过于频繁地发送它们。默认值：“0”。可能的值：0–65535。 传输类型 非循环 - 同步 ：当发生变化时，PDO 是同步传输的，但不是周期性的。 （默认） 循环 - 同步 : PDO 每第 n 个同步发送一次。 同步 - 仅 RTR ：仅适用于传输 PDO。在同步消息之后，更新 PDO，但不发送。传输仅通过显式请求（远程传输请求）。 异步 - 仅 RTR ：仅适用于传输 PDO。 PDO 仅通过显式请求（远程传输请求）进行更新和传输。 异步 - 特定于制造商 : PDO 仅在特定事件之后传输。 异步 - 设备配置文件 ：根据 CiA 设备配置文件传输 PDO。 同步数 对于传输类型 循环 - 同步 只要。 指示传输 PDO 的时间间隔。该值是 周期（微秒） CANopen 管理器。默认值：1。可能的值：1–240。 示例：同步数 = 4，周期周期 = 1000 µs → 传输间隔 = 4000 µs 事件时间（x 1ms） 仅适用于传输类型 异步 - 特定于制造商 和 异步 - 设备配置文件 . 仅当设备支持此功能时，您才能编辑此字段。在此处指定 PDO 的两次传输之间的时间跨度（以毫秒为单位）。默认值：“0”。可能的值：0–65535。 CANopen 管理器处理 ： 默认设置 : CANopen 管理器不再处理 PDO。它不再被发送或接收。 " }, 
{ "title" : "对话框：从对象目录中选择项目 ", 
"url" : "_can_edt_canopen_device_pdos.html#UUID-cddcb61f-bf3f-83bd-0cac-dbedbbd21e7f_id_c45dd0c9e26ba3ecc0a8640e016944ea-id-0417cab97b9c11e4b88187ab7ade6762", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 设备 – PDO \/ 对话框：从对象目录中选择项目 ", 
"snippet" : "对于模块化从站，您必须清除 自动配置 PDO 映射 能够手动配置映射的选项。 该表显示了设备 EDS 文件中的所有对象目录条目。对于接收 PDO， CODESYS 此处仅提供具有写权限的对象（标志 = w）；对于传输 PDO，读取权限。 名称 PDO 的 COB-ID 或在设备描述和对象目录中使用的“映射”对象的名称。 指数 对象的索引 子索引 对象的子索引 访问类型 RW ：读\/写 反渗透 ： 只读 WO : 只写 RWW ：每个 SDO 读\/写；每个 PDO 的写权限（==> RPDO，从主机的角度输出，从从机的角度输入）。 RWR ：每个 SDO 读\/写；每个 PDO 的读取权限（==>...", 
"body" : "对于模块化从站，您必须清除 自动配置 PDO 映射 能够手动配置映射的选项。 该表显示了设备 EDS 文件中的所有对象目录条目。对于接收 PDO， CODESYS 此处仅提供具有写权限的对象（标志 = w）；对于传输 PDO，读取权限。 名称 PDO 的 COB-ID 或在设备描述和对象目录中使用的“映射”对象的名称。 指数 对象的索引 子索引 对象的子索引 访问类型 RW ：读\/写 反渗透 ： 只读 WO : 只写 RWW ：每个 SDO 读\/写；每个 PDO 的写权限（==> RPDO，从主机的角度输出，从从机的角度输入）。 RWR ：每个 SDO 读\/写；每个 PDO 的读取权限（==> TPDO，从主机的角度输入，从从机的角度输出）。 常数=常数 类型 对象的数据类型 默认值 对象的默认值 位长 物体长度 " }, 
{ "title" : "选项卡：CANopen 远程设备 – SDO ", 
"url" : "_can_edt_canopen_remote_device_sdos.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 远程设备 – SDO ", 
"snippet" : "在 CAN 总线初始化期间， CODESYS 通过使用 SDO（服务数据对象）传输当前配置设置。 在此选项卡上，您可以配置必要的 SDO。组态必要的 SDO 并确定对象的传输顺序以及在发生传输错误时采取的措施。 此列表中的对象顺序对应于 SDO 到模块的传输顺序。 如果 专家设置 当前设备未激活选项，则此处仅显示用户定义的 SDO。 添加 SDO 打开 从对象目录中选择项目 显示所有可用 SDO 的对话框。所选对象插入到所选对象之后。 编辑 打开 从对象目录中选择项目 对话框并标记相应的对象。您可以修改对象参数或将对象替换为另一个对象。 删除 从列表中删除选定的对象 提升 将选定对象向上移动一...", 
"body" : "在 CAN 总线初始化期间， CODESYS 通过使用 SDO（服务数据对象）传输当前配置设置。 在此选项卡上，您可以配置必要的 SDO。组态必要的 SDO 并确定对象的传输顺序以及在发生传输错误时采取的措施。 此列表中的对象顺序对应于 SDO 到模块的传输顺序。 如果 专家设置 当前设备未激活选项，则此处仅显示用户定义的 SDO。 添加 SDO 打开 从对象目录中选择项目 显示所有可用 SDO 的对话框。所选对象插入到所选对象之后。 编辑 打开 从对象目录中选择项目 对话框并标记相应的对象。您可以修改对象参数或将对象替换为另一个对象。 删除 从列表中删除选定的对象 提升 将选定对象向上移动一行。 下移 将选定对象向下移动一行。 错误中止 ：如果检测到此 SDO 错误，则堆栈停止当前从机的配置阶段。从站保持在 PREOPERATIONAL 模式。 出错时跳转到行 ：使用您在 下一行 柱子。 下一行 检测到错误时继续处理的行号 SDO 超时（毫秒） SDO 传输超时。如果从机在这段时间内没有响应 SDO 请求，则超时取消传输。 创建所有 SDO ：为从索引 16#2000 开始的所有可写对象创建一个 SDO，在 EDS 中给出了默认值。只有专家才能使用此选项。应将其停用以进行标准使用。 编写完整的 PDO 配置 ：此选项强制写入所有 PDO 配置对象。这样，您可以确保项目中的设置与从站的设置相对应。 : PDO 未明确禁用。要求是 默认设置 选项在从站的通用设置中被激活，并且 PDO 在 EDS 中也被禁用。如果 EDS 中的默认值与从属固件的默认设置不匹配，则此过程可能会导致问题。在这种情况下，您应该激活此选项。 " }, 
{ "title" : "对话框：从对象目录中选择项目 ", 
"url" : "_can_edt_canopen_remote_device_sdos.html#UUID-cbe05b26-6f5b-27de-9514-096fcab96ed6_id_fba0cb81e26bcabec0a8640e01305569-id-0417cab97b9c11e4b88187ab7ade6762", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 远程设备 – SDO \/ 对话框：从对象目录中选择项目 ", 
"snippet" : "该表显示了设备 EDS 文件中每个可写且不大于 4 字节的 SDO 的所有对象目录条目。在 SDO 对话框中添加 SDO 以供选择之前，您可以在表格下方的字段中修改其参数。这样，您还可以通过输入新的索引\/子索引值来创建在 EDS 文件中不可写的 SDO。 名称 PDO 的 COB-ID 或在设备描述和对象目录中使用的“映射”对象的名称。 指数 对象的索引 子索引 对象的子索引 访问类型 RW ：读\/写 WO : 只写 RWW ：每个 SDO 读\/写；每个 PDO 的写权限（==> RPDO，从主机的角度输出，从从机的角度输入）。 RWR ：每个 SDO 读\/写；每个 PDO 的读取权限（==>...", 
"body" : "该表显示了设备 EDS 文件中每个可写且不大于 4 字节的 SDO 的所有对象目录条目。在 SDO 对话框中添加 SDO 以供选择之前，您可以在表格下方的字段中修改其参数。这样，您还可以通过输入新的索引\/子索引值来创建在 EDS 文件中不可写的 SDO。 名称 PDO 的 COB-ID 或在设备描述和对象目录中使用的“映射”对象的名称。 指数 对象的索引 子索引 对象的子索引 访问类型 RW ：读\/写 WO : 只写 RWW ：每个 SDO 读\/写；每个 PDO 的写权限（==> RPDO，从主机的角度输出，从从机的角度输入）。 RWR ：每个 SDO 读\/写；每个 PDO 的读取权限（==> TPDO，从主机的角度输入，从从机的角度输出）。 类型 对象的数据类型 默认值 对象的默认值 位长 物体长度 价值 " }, 
{ "title" : "选项卡：CANopen 远程设备 – SRDO CRC ", 
"url" : "_can_edt_canopen_remote_device_srdo_crc.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 远程设备 – SRDO CRC ", 
"snippet" : "此对话框仅适用于 CANopen 安全从站。它概述了当前配置的发送和接收 SRDO 以及确定的校验和 (CRC)。验证结果显示在这里。 忽略不匹配 : 错误仍然存在，但不再评估。 验证结果 CRC 正常 CRC 不匹配。期望值：16#xxxx ：当 SRDO 的配置发生更改时，会发生 CFC 不匹配。计算值不再与设定值匹配，必须修复。 修复所有 CRC 不匹配 所有不匹配都会自动修复。 CRC 值已更正。 CRC不匹配可以如下处理： 选择 忽略不匹配 复选框。 的执行 修复所有 CRC 不匹配 命令 手动修改 CRC（例如，通过使用硬件制造商提供的工具计算 CRC）。 使用 CANopen 管...", 
"body" : "此对话框仅适用于 CANopen 安全从站。它概述了当前配置的发送和接收 SRDO 以及确定的校验和 (CRC)。验证结果显示在这里。 忽略不匹配 : 错误仍然存在，但不再评估。 验证结果 CRC 正常 CRC 不匹配。期望值：16#xxxx ：当 SRDO 的配置发生更改时，会发生 CFC 不匹配。计算值不再与设定值匹配，必须修复。 修复所有 CRC 不匹配 所有不匹配都会自动修复。 CRC 值已更正。 CRC不匹配可以如下处理： 选择 忽略不匹配 复选框。 的执行 修复所有 CRC 不匹配 命令 手动修改 CRC（例如，通过使用硬件制造商提供的工具计算 CRC）。 使用 CANopen 管理器 SIL2 中的“检查和修复配置”命令进行自动修复。 " }, 
{ "title" : "选项卡：CANopen 远程设备 – SRDO ", 
"url" : "_can_edt_canopen_remote_device_srdos.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 远程设备 – SRDO ", 
"snippet" : "在对话框中，定义面向安全的数据对象 (SRDO)。接收 SRDO 定义在左侧，发送 SRDO 定义在右侧。 通常，每个 SRDO 包含两个对象：具有偶数 COB-ID 的正常对象和具有奇数 COB-ID 的逆对象。然后最大可能的数据大小为 8 个字节。 添加 SRDO 打开 选择 SRDO 带有 SRDO 列表的对话框。此信息在 EDS 文件中定义。 添加映射 如果选择了 SRDO，则可以添加映射。该命令打开“SRDO 映射”对话框。 调整 更改选定对象的属性。这也可以通过双击对象来实现。 激活 SRDO 的数据传输。 当鼠标指针位于名称上时，SRDO 的参数将显示为工具提示。 对话框：SRD...", 
"body" : "在对话框中，定义面向安全的数据对象 (SRDO)。接收 SRDO 定义在左侧，发送 SRDO 定义在右侧。 通常，每个 SRDO 包含两个对象：具有偶数 COB-ID 的正常对象和具有奇数 COB-ID 的逆对象。然后最大可能的数据大小为 8 个字节。 添加 SRDO 打开 选择 SRDO 带有 SRDO 列表的对话框。此信息在 EDS 文件中定义。 添加映射 如果选择了 SRDO，则可以添加映射。该命令打开“SRDO 映射”对话框。 调整 更改选定对象的属性。这也可以通过双击对象来实现。 激活 SRDO 的数据传输。 当鼠标指针位于名称上时，SRDO 的参数将显示为工具提示。 对话框：SRDO 属性 双击 SRDO 将打开对话框。 当鼠标指针位于名称上时，有关参数的更多信息将显示为工具提示。 " }, 
{ "title" : "对话框：SRDO 映射 ", 
"url" : "_can_edt_canopen_remote_device_srdos.html#UUID-3b3f78d3-4121-3e18-96d0-c1160be8d1b4_id_c3278e26d5d2cc0a8640e0088a81c-id-0f18548089bf4207c0a8640e0075a528", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 配置 \/ 选项卡：CANopen 远程设备 – SRDO \/ 对话框：SRDO 映射 ", 
"snippet" : "此对话框定义从纯数据对象到反向数据对象的分配。 双击纯数据对象的空白行会打开对象目录中的元素列表。通过点击 行 ，普通数据对象被应用到映射对话框。然后 CODESYS 尝试自动确定反向数据对象并将其应用于映射。 CODESYS 检查正常和反向数据对象的数据类型和数据长度是否匹配。结果显示在对话框的底部。...", 
"body" : "此对话框定义从纯数据对象到反向数据对象的分配。 双击纯数据对象的空白行会打开对象目录中的元素列表。通过点击 行 ，普通数据对象被应用到映射对话框。然后 CODESYS 尝试自动确定反向数据对象并将其应用于映射。 CODESYS 检查正常和反向数据对象的数据类型和数据长度是否匹配。结果显示在对话框的底部。 " }, 
{ "title" : "职能 ", 
"url" : "_can_f_canopen_manager_functions.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 安全 ", 
"url" : "_can_f_canopen_manager_functions.html#UUID-4da19cc3-24e9-db96-4f52-ef6df874dbe4_section-idm4587237183204832570300999956", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 \/ CANopen 安全 ", 
"snippet" : "CANopen Safety 作为欧洲标准 (EN 50325-5) 发布。这意味着可以通过满足 SIL3 应用要求的 CAN 网络传输数据。这种面向安全的数据传输可以与现有的 CANopen 数据传输并行进行。 CODESYS CANopen Safety 支持符合 SIL2 的安全要求。 除了用于数据传输的传统 CANopen 服务（例如 SDO 和 PDO）之外，还为带有 SRDO 服务（安全相关数据对象）的安全扩展定义了用于这种数据传输的特殊服务。关于通信的配置和类型，它类似于 PDO，但定义了其他属性。 为了使用 CANopen 安全，CANopen 管理器 SIL2 被插入到设备树...", 
"body" : "CANopen Safety 作为欧洲标准 (EN 50325-5) 发布。这意味着可以通过满足 SIL3 应用要求的 CAN 网络传输数据。这种面向安全的数据传输可以与现有的 CANopen 数据传输并行进行。 CODESYS CANopen Safety 支持符合 SIL2 的安全要求。 除了用于数据传输的传统 CANopen 服务（例如 SDO 和 PDO）之外，还为带有 SRDO 服务（安全相关数据对象）的安全扩展定义了用于这种数据传输的特殊服务。关于通信的配置和类型，它类似于 PDO，但定义了其他属性。 为了使用 CANopen 安全，CANopen 管理器 SIL2 被插入到设备树中，而不是 CANopen 管理器中。可以在此管理器下方插入安全设备（黄色设备图标）和不安全设备（灰色设备图标）。因此，不安全和安全的 CAN 用户可以并行运行。除了通常的配置页面外，安全订阅者还有安全特定页面。可以在其中配置 SRDO（安全 PDO）及其 CRC。除了通常的不安全设备实例外，还会为每个安全设备（CANopen 管理器和从站）生成一个带有前缀“S_”的附加实例。这提供了特定于安全的诊断功能。 使用 CANopen 管理器 SIL2 需要 SIL2 CODESYS Runtime 以及特别适配的 CAN 微型驱动程序和 CODESYS SIL2 插件。所需的库和设备已包含在标准安装中。 " }, 
{ "title" : "冗余 ", 
"url" : "_can_f_canopen_manager_functions.html#UUID-4da19cc3-24e9-db96-4f52-ef6df874dbe4_section-idm4623547410147232570302809819", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 \/ 冗余 ", 
"snippet" : "随着 CODESYS 冗余工具包，两个 CANopen 管理器可用于冗余配置。在这种情况下，被动控制器监视主动控制器的活动，并在检测到通信故障时接管主动角色。监控是通过两种并行机制完成的： 监测 CODESYS 冗余工具包（主要通过以太网） 监控 CANopen 管理器心跳。所需的超时在 CANopen 管理器的配置器中设置。 这 ” CODESYS “冗余”功能需要“冗余工具包”插件。此外，您必须在设备树中组态冗余。 有关更多信息，请参阅： CODESYS 冗余...", 
"body" : "随着 CODESYS 冗余工具包，两个 CANopen 管理器可用于冗余配置。在这种情况下，被动控制器监视主动控制器的活动，并在检测到通信故障时接管主动角色。监控是通过两种并行机制完成的： 监测 CODESYS 冗余工具包（主要通过以太网） 监控 CANopen 管理器心跳。所需的超时在 CANopen 管理器的配置器中设置。 这 ” CODESYS “冗余”功能需要“冗余工具包”插件。此外，您必须在设备树中组态冗余。 有关更多信息，请参阅： CODESYS 冗余 " }, 
{ "title" : "重新配置 – CANopen 管理器 ", 
"url" : "_can_f_canopen_manager_functions.html#UUID-4da19cc3-24e9-db96-4f52-ef6df874dbe4_section-idm4587237072230432570304734973", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 \/ 重新配置 – CANopen 管理器 ", 
"snippet" : "使用“重新配置”功能，您可以在应用程序运行时动态调整最初下载到控制器的 CAN 总线配置。 带功能块 DED.Reconfigure ，在启用通用设备诊断时可用 ( PLC 设置： )，您可以在运行时执行以下操作。 单个设备的激活和停用 启用和停用整个总线组 有关在 CANbus 级别上重新配置的更多信息，请参阅本章 重新配置 – CANbus。...", 
"body" : "使用“重新配置”功能，您可以在应用程序运行时动态调整最初下载到控制器的 CAN 总线配置。 带功能块 DED.Reconfigure ，在启用通用设备诊断时可用 ( PLC 设置： )，您可以在运行时执行以下操作。 单个设备的激活和停用 启用和停用整个总线组 有关在 CANbus 级别上重新配置的更多信息，请参阅本章 重新配置 – CANbus。 " }, 
{ "title" : "命令：扫描设备 ", 
"url" : "_can_f_canopen_manager_functions.html#UUID-4da19cc3-24e9-db96-4f52-ef6df874dbe4_section-idm4587237186384032570306850009", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 \/ 命令：扫描设备 ", 
"snippet" : "功能 ：该命令建立与硬件的临时连接并检测网络中的设备。然后您可以将扫描的设备应用到项目的设备树中。 称呼 ： 项目 菜单;设备树中设备对象的上下文菜单 要求 ：与控制器的通信设置正确。网关和 PLC 启动。设备支持扫描功能。 以下设备提供扫描功能：EtherCAT Master、EtherNet\/IP Scanner (IEC)、Sercos Master、CANopen Manager、CANopen Manager SIL2、Profinet Controller 和 Profibus DP Master。 如果扫描功能在 PLC 中永久实现，您可以立即执行设备扫描。在库中实现扫描功能时，...", 
"body" : "功能 ：该命令建立与硬件的临时连接并检测网络中的设备。然后您可以将扫描的设备应用到项目的设备树中。 称呼 ： 项目 菜单;设备树中设备对象的上下文菜单 要求 ：与控制器的通信设置正确。网关和 PLC 启动。设备支持扫描功能。 以下设备提供扫描功能：EtherCAT Master、EtherNet\/IP Scanner (IEC)、Sercos Master、CANopen Manager、CANopen Manager SIL2、Profinet Controller 和 Profibus DP Master。 如果扫描功能在 PLC 中永久实现，您可以立即执行设备扫描。在库中实现扫描功能时，只需登录一次即可将库下载到控制器。 该命令适用于在设备树中选择的主控制器。例如，一个已经插入的 PROFINET 可以选择控制器和用于确定分配给它的 I\/O 设备和 I\/O 模块的命令。 执行扫描操作后， 扫描设备 对话框打开并显示扫描的设备。 " }, 
{ "title" : "“扫描设备”对话框 ", 
"url" : "_can_f_canopen_manager_functions.html#UUID-4da19cc3-24e9-db96-4f52-ef6df874dbe4_UUID-87d819e6-40ac-9a7c-b963-a6e4714caeeb", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 \/ 命令：扫描设备 \/ “扫描设备”对话框 ", 
"snippet" : "扫描的设备 设备名称、设备类型、地址、站名等 扫描设备的数据取决于网络类型。 当您更改扫描设备列表中的值时，该值以斜体显示。这表明新值在编辑器中已更改 CODESYS ，但不在设备中。当您将值下载到设备时，它会正常显示。 指示项目和扫描设备之间差异的值以橙色显示。 如果扫描设备有多个设备描述可用，则名称以粗体显示。对于不同的现场总线，匹配设备描述的选择是不同的。更多详细信息，请参见相应的现场总线章节。 如果找不到设备描述，则会显示以下消息：“注意！在存储库中找不到设备。”根据总线系统，会显示附加信息，例如供应商编号和产品编号。如果没有安装的设备描述，则无法将设备插入到项目中。 显示与项目的差异...", 
"body" : "扫描的设备 设备名称、设备类型、地址、站名等 扫描设备的数据取决于网络类型。 当您更改扫描设备列表中的值时，该值以斜体显示。这表明新值在编辑器中已更改 CODESYS ，但不在设备中。当您将值下载到设备时，它会正常显示。 指示项目和扫描设备之间差异的值以橙色显示。 如果扫描设备有多个设备描述可用，则名称以粗体显示。对于不同的现场总线，匹配设备描述的选择是不同的。更多详细信息，请参见相应的现场总线章节。 如果找不到设备描述，则会显示以下消息：“注意！在存储库中找不到设备。”根据总线系统，会显示附加信息，例如供应商编号和产品编号。如果没有安装的设备描述，则无法将设备插入到项目中。 显示与项目的差异 ：对话框中的表格还显示了其他配置的设备（在项目的设备树中）。 ：表格显示所有扫描的设备。未显示配置的设备。 扫描设备 开始新的搜索。 将所有设备复制到项目 在表中选择的设备被插入到项目的设备树中。如果未选择任何内容，则显示所有扫描的设备。 如果你使用 将所有设备复制到项目 要将设备树中可用的设备插入设备树，则应注意以下几点： 处理数据 和 <...> I\/O 映射 现有设备的选项卡可能会被最近插入的设备的数据覆盖。 配置的设备 对话框的这一部分仅在您选择 显示与项目的差异 选项。 扫描设备和配置设备之间的差异是用颜色编码的。两侧显示为绿色的设备相同。以红色显示的设备仅在扫描或配置的设备视图中可用。 如果您在两个视图中都选择了一个设备，则扫描的设备将插入到所选配置设备的上方。 如果您在两个视图中都选择了一个设备，则扫描的设备将插入到所选配置设备的下方。 如果您在两个视图中都选择了一个设备，则配置的设备将替换为选定的扫描设备。 所有扫描的设备都被复制到项目中。 删除选定的已配置设备。 " }, 
{ "title" : "CANopenManager 的总线循环行为 ", 
"url" : "_can_f_canopen_manager_functions.html#UUID-4da19cc3-24e9-db96-4f52-ef6df874dbe4_section-idm43257031180150", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 职能 \/ CANopenManager 的总线循环行为 ", 
"snippet" : "0：发送\/接收同步 PDO 1：接收异步 PDO 2：IEC 任务 3：将输出写入输出缓冲区 有关更多信息，请参阅： 任务配置...", 
"body" : "0：发送\/接收同步 PDO 1：接收异步 PDO 2：IEC 任务 3：将输出写入输出缓冲区 有关更多信息，请参阅： 任务配置 " }, 
{ "title" : "诊断 ", 
"url" : "_can_f_canopen_manager_diagnosis.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 诊断 ", 
"url" : "_can_f_canopen_manager_diagnosis2.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ CANopen 诊断 ", 
"snippet" : "本章介绍 CANopen 协议提供的诊断选项。...", 
"body" : "本章介绍 CANopen 协议提供的诊断选项。 " }, 
{ "title" : "CANopen 状态 ", 
"url" : "_can_f_canopen_manager_diagnosis2.html#UUID-20f9f788-7f7d-253b-e12f-08e680a8a911_section-idm4587237114625632570325335855", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ CANopen 诊断 \/ CANopen 状态 ", 
"snippet" : "CANopen 网络由 NMT 主站（网络管理）和 NMT 从站组成。在这种情况下，NMT 主机控制所有设备并可以更改它们的通信状态。 CANopen 设备处于以下四种可能状态之一： 初始化：开启后，节点经过这个状态。此时，设备应用程序和设备通信（比特率和节点地址）被初始化。之后，节点独立切换到“预操作”状态。 预操作：可以通过 SDO 与节点通信。但是，节点不能执行 PDO 通信。 运行：CANopen 节点完全运行。它可以独立发送和接收过程数据。 已停止：节点与网络完全分离。无法进行 SDO 或 PDO 通信。节点只能通过相应的网络命令（例如：启动节点）才能更改为另一种网络状态。...", 
"body" : "CANopen 网络由 NMT 主站（网络管理）和 NMT 从站组成。在这种情况下，NMT 主机控制所有设备并可以更改它们的通信状态。 CANopen 设备处于以下四种可能状态之一： 初始化：开启后，节点经过这个状态。此时，设备应用程序和设备通信（比特率和节点地址）被初始化。之后，节点独立切换到“预操作”状态。 预操作：可以通过 SDO 与节点通信。但是，节点不能执行 PDO 通信。 运行：CANopen 节点完全运行。它可以独立发送和接收过程数据。 已停止：节点与网络完全分离。无法进行 SDO 或 PDO 通信。节点只能通过相应的网络命令（例如：启动节点）才能更改为另一种网络状态。 " }, 
{ "title" : "错误寄存器 ", 
"url" : "_can_f_canopen_manager_diagnosis2.html#UUID-20f9f788-7f7d-253b-e12f-08e680a8a911_section-idm4623547498555232570327788434", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ CANopen 诊断 \/ 错误寄存器 ", 
"snippet" : "根据 CiA 301，每个 CANopen 设备都有一个错误寄存器（对象 16#1001）。该寄存器可通过 SDO 读取，并在出现错误时提供有关错误的附加信息。 错误寄存器中只需要位 0（一般错误）。其他位是可选的，并非由每个从站设置。一旦设备检测到任何错误，至少会设置该对象的第 0 位。 错误寄存器 少量 描述 0 一般错误 1 当前的 2 电压 3 温度 4 通讯错误（溢出错误状态） 5 特定于设备配置文件 6 保留（始终为 0） 7 特定于制造商...", 
"body" : "根据 CiA 301，每个 CANopen 设备都有一个错误寄存器（对象 16#1001）。该寄存器可通过 SDO 读取，并在出现错误时提供有关错误的附加信息。 错误寄存器中只需要位 0（一般错误）。其他位是可选的，并非由每个从站设置。一旦设备检测到任何错误，至少会设置该对象的第 0 位。 错误寄存器 少量 描述 0 一般错误 1 当前的 2 电压 3 温度 4 通讯错误（溢出错误状态） 5 特定于设备配置文件 6 保留（始终为 0） 7 特定于制造商 " }, 
{ "title" : "紧急和预定义错误字段 (EMCY) ", 
"url" : "_can_f_canopen_manager_diagnosis2.html#UUID-20f9f788-7f7d-253b-e12f-08e680a8a911_section-idm4623547543233632570329234005", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ CANopen 诊断 \/ 紧急和预定义错误字段 (EMCY) ", 
"snippet" : "CANopen 定义了可选的紧急 (EMCY) 协议来指示错误。紧急情况是根据带有 CAN-ID 16#80 + NODE-ID 的预定义连接集传输的 CAN 消息。 电报具有以下结构： 紧急消息的长度始终为 8 个字节。相应的紧急错误代码 (EEC) 在前两个字节中传输。其后是错误寄存器 0x1011（ER：错误寄存器）和 5 个制造商特定字节（MEF：制造商特定错误字段）的当前值。 错误代码的相应解释必须从制造商手册中获取。并非所有从站都支持紧急协议，必须由 CANopen 管理器进行相应配置。 可通过 SDO 从对象 16#1003 中读取已发生紧急情况的历史记录（错误历史记录）。这里，...", 
"body" : "CANopen 定义了可选的紧急 (EMCY) 协议来指示错误。紧急情况是根据带有 CAN-ID 16#80 + NODE-ID 的预定义连接集传输的 CAN 消息。 电报具有以下结构： 紧急消息的长度始终为 8 个字节。相应的紧急错误代码 (EEC) 在前两个字节中传输。其后是错误寄存器 0x1011（ER：错误寄存器）和 5 个制造商特定字节（MEF：制造商特定错误字段）的当前值。 错误代码的相应解释必须从制造商手册中获取。并非所有从站都支持紧急协议，必须由 CANopen 管理器进行相应配置。 可通过 SDO 从对象 16#1003 中读取已发生紧急情况的历史记录（错误历史记录）。这里，子索引 0 包含存储错误的数量，以下子对象包含传输的紧急情况的数据内容。 有关更多信息，请参阅： 预定义的错误字段和错误寄存器 " }, 
{ "title" : "监控机制：心跳和节点保护 ", 
"url" : "_can_f_canopen_manager_diagnosis2.html#UUID-20f9f788-7f7d-253b-e12f-08e680a8a911_section-idm4613673131235232570331473483", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ CANopen 诊断 \/ 监控机制：心跳和节点保护 ", 
"snippet" : "如果 CAN 节点不连续发送消息（循环 PDO），则需要对其进行监控。为此，提供了“心跳”和“节点保护”机制，它们可以交替使用。 节点保护：使用此协议，消息（CAN 远程帧）由 NMT 主站发送到现有的 CANopen 从站。从站必须在特定时间内响应这些消息。如果没有响应，则由 NMT 主机注册。因为通常应避免 CAN 远程帧，所以最好通过心跳进行监控。 心跳：心跳协议随 CANopen 4.0 版本发布，是首选的监控方式。在这里，每个节点独立地以循环间隔发送消息。该消息可以被网络中的任何其他用户监视。...", 
"body" : "如果 CAN 节点不连续发送消息（循环 PDO），则需要对其进行监控。为此，提供了“心跳”和“节点保护”机制，它们可以交替使用。 节点保护：使用此协议，消息（CAN 远程帧）由 NMT 主站发送到现有的 CANopen 从站。从站必须在特定时间内响应这些消息。如果没有响应，则由 NMT 主机注册。因为通常应避免 CAN 远程帧，所以最好通过心跳进行监控。 心跳：心跳协议随 CANopen 4.0 版本发布，是首选的监控方式。在这里，每个节点独立地以循环间隔发送消息。该消息可以被网络中的任何其他用户监视。 " }, 
{ "title" : "应用中的诊断 ", 
"url" : "_can_f_canopen_manager_diagnosis_application.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 应用中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 状态 ", 
"url" : "_can_f_canopen_manager_diagnosis_application.html#UUID-401eda1b-8775-dd7a-8663-010e22d41fbc_section-idm4506522862032032570266114426", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 应用中的诊断 \/ CANopen 状态 ", 
"snippet" : "可以通过三种不同方式在应用程序中查询设备的 CANopen 状态： GET_STATE 功能块（ 民航局中央情报局 405 图书馆） <name in device tree>.CANopenState 财产 （ 3S CANopenStack 图书馆） <name in device tree>.GetDeviceState 方法 （ CAA 设备诊断 图书馆） 该方法不返回 CANopen 状态，而是返回设备是否正在运行的信息。之间的映射表 CANopenState 和 DEVICE_STATE 可以在图书馆文档中找到 CANopenStack . CANopen 管理器还具有询问是否所有...", 
"body" : "可以通过三种不同方式在应用程序中查询设备的 CANopen 状态： GET_STATE 功能块（ 民航局中央情报局 405 图书馆） <name in device tree>.CANopenState 财产 （ 3S CANopenStack 图书馆） <name in device tree>.GetDeviceState 方法 （ CAA 设备诊断 图书馆） 该方法不返回 CANopen 状态，而是返回设备是否正在运行的信息。之间的映射表 CANopenState 和 DEVICE_STATE 可以在图书馆文档中找到 CANopenStack . CANopen 管理器还具有询问是否所有必需和可选从站都在 OPERATIONAL 状态。请注意，如果条件适用，这些属性仅在配置阶段后设置一次。如果从属服务器随后发生故障，则这些属性将保持相应设置。 此外，还可以通过功能块设置 CANopen 状态 NMT （图书馆 民航局中央情报局 405 ) 或方法 <name in device tree>.SetCommunicationState ( CAA 设备诊断 图书馆）。 " }, 
{ "title" : "CANopen 内核状态 ", 
"url" : "_can_f_canopen_manager_diagnosis_application.html#UUID-401eda1b-8775-dd7a-8663-010e22d41fbc_section-idm4506522859841632570268680266", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 应用中的诊断 \/ CANopen 内核状态 ", 
"snippet" : "CANopen 内核状态的询问可用于检测总线错误、配置错误或监控错误。 国家可以通过财产进行讯问 <name of CANopen Manager in device tree>.KernelState 或功能块 GET_CANOPEN_KERNEL_STATE ( 民航局中央情报局 405 图书馆）。...", 
"body" : "CANopen 内核状态的询问可用于检测总线错误、配置错误或监控错误。 国家可以通过财产进行讯问 <name of CANopen Manager in device tree>.KernelState 或功能块 GET_CANOPEN_KERNEL_STATE ( 民航局中央情报局 405 图书馆）。 " }, 
{ "title" : "紧急情况 ", 
"url" : "_can_f_canopen_manager_diagnosis_application.html#UUID-401eda1b-8775-dd7a-8663-010e22d41fbc_section-idm4613673171972832570269997686", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 应用中的诊断 \/ 紧急情况 ", 
"snippet" : "您可以通过 CIA405 功能块接收紧急电报。 RECV_EMCY ：接收母线所有设备的所有紧急情况 RECV_EMCY_DEV ：接收特定设备的紧急情况...", 
"body" : "您可以通过 CIA405 功能块接收紧急电报。 RECV_EMCY ：接收母线所有设备的所有紧急情况 RECV_EMCY_DEV ：接收特定设备的紧急情况 " }, 
{ "title" : "预定义的错误字段和错误寄存器 ", 
"url" : "_can_f_canopen_manager_diagnosis_application.html#UUID-401eda1b-8775-dd7a-8663-010e22d41fbc_section-idm43264460491268", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 应用中的诊断 \/ 预定义的错误字段和错误寄存器 ", 
"snippet" : "从站的对象目录的对象可以用 SDO_READ4 和 SDO_READ_DATA CiA405 功能块。...", 
"body" : "从站的对象目录的对象可以用 SDO_READ4 和 SDO_READ_DATA CiA405 功能块。 " }, 
{ "title" : "安全诊断 ", 
"url" : "_can_f_canopen_manager_diagnosis_application.html#UUID-401eda1b-8775-dd7a-8663-010e22d41fbc_section-idm4587237144556832570272642438", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 应用中的诊断 \/ 安全诊断 ", 
"snippet" : "在安全的情况下，隐式创建的带有前缀“S_”的功能块提供相应的诊断输出。使用这些功能块，您可以定义与从站的 SRDO 通信是否处于活动状态或是否已达到安全状态。 此外，该功能块还提供输入以确认单个从站的错误以及暂时停用 SRDO 通信。 有关更多信息，请参阅： CANopenManagerSIL2 和 CANRemoteDeviceSafe (FB)...", 
"body" : "在安全的情况下，隐式创建的带有前缀“S_”的功能块提供相应的诊断输出。使用这些功能块，您可以定义与从站的 SRDO 通信是否处于活动状态或是否已达到安全状态。 此外，该功能块还提供输入以确认单个从站的错误以及暂时停用 SRDO 通信。 有关更多信息，请参阅： CANopenManagerSIL2 和 CANRemoteDeviceSafe (FB) " }, 
{ "title" : "用户界面中的诊断 ", 
"url" : "_can_f_canopen_manager_diagnosis_ui.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 用户界面中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 管理器（主站）设备树 ", 
"url" : "_can_f_canopen_manager_diagnosis_ui.html#UUID-9cf006ca-c2e2-a8b8-0e3b-71d97a29431c_section-idm43257027618782", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 用户界面中的诊断 \/ CANopen 管理器（主站）设备树 ", 
"snippet" : "在在线模式下，设备树允许精确定位待定诊断。 设备处于运行状态时的绿色符号。 错误标志（红色三角形）：硬错误，例如设备未运行（例如：找不到 CAN 驱动程序、连接中断或缺少模块） 橙色三角形：设备处于状态 PREOPERATIONAL 诊断标志（红色感叹号）：表示诊断条目当前可用于该设备。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。...", 
"body" : "在在线模式下，设备树允许精确定位待定诊断。 设备处于运行状态时的绿色符号。 错误标志（红色三角形）：硬错误，例如设备未运行（例如：找不到 CAN 驱动程序、连接中断或缺少模块） 橙色三角形：设备处于状态 PREOPERATIONAL 诊断标志（红色感叹号）：表示诊断条目当前可用于该设备。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。 " }, 
{ "title" : "CANopen 管理器（主站）状态页面 ", 
"url" : "_can_f_canopen_manager_diagnosis_ui.html#UUID-9cf006ca-c2e2-a8b8-0e3b-71d97a29431c_section-idm43257027682820", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 用户界面中的诊断 \/ CANopen 管理器（主站）状态页面 ", 
"snippet" : "状态页面显示 CANopen 状态以及紧急情况和其他错误。...", 
"body" : "状态页面显示 CANopen 状态以及紧急情况和其他错误。 " }, 
{ "title" : "CANopen 管理器（主）记录器页面 ", 
"url" : "_can_f_canopen_manager_diagnosis_ui.html#UUID-9cf006ca-c2e2-a8b8-0e3b-71d97a29431c_section-idm43257027844428", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 用户界面中的诊断 \/ CANopen 管理器（主）记录器页面 ", 
"snippet" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。 这仅显示由相应设备创建的条目，例如 CANopen 状态的更改、紧急消息、SDO 错误和监控错误。...", 
"body" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。 这仅显示由相应设备创建的条目，例如 CANopen 状态的更改、紧急消息、SDO 错误和监控错误。 " }, 
{ "title" : "故障排除 ", 
"url" : "_can_canopen_manager_trouble_shooting.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 诊断 \/ 故障排除 ", 
"snippet" : "CANopen 管理器（主站） 问题 可能的解决方案 CAN 总线节点为红色或带有红色感叹号。 请参阅 CAN 总线的一般故障排除。 CANopen 管理器为红色或带有红色感叹号。 检查 CANopen 管理器的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 您没有许可证或演示许可证已过期。 可用内存太少。 CANopen 管理器有一个橙色三角形。 CANopen 管理器处于 PREOPERATIONAL 状态。 可能的原因： 并非所有强制从站都处于 OPERATIONAL 状态。 将设备配置器中的不可用设备标记为可选。 在 CANopen Manager 配置器中未选择“Aut...", 
"body" : "CANopen 管理器（主站） 问题 可能的解决方案 CAN 总线节点为红色或带有红色感叹号。 请参阅 CAN 总线的一般故障排除。 CANopen 管理器为红色或带有红色感叹号。 检查 CANopen 管理器的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 您没有许可证或演示许可证已过期。 可用内存太少。 CANopen 管理器有一个橙色三角形。 CANopen 管理器处于 PREOPERATIONAL 状态。 可能的原因： 并非所有强制从站都处于 OPERATIONAL 状态。 将设备配置器中的不可用设备标记为可选。 在 CANopen Manager 配置器中未选择“Autostart CANopen Manager”选项。 您必须通过功能块在应用程序中手动启动 CANopen 管理器 CiA405.NMT . 奴隶有一个橙色三角形。 从站不处于 OPERATIONAL 状态。 I\/O 通信尚未开始。您可以在状态页面上查看当前状态。 您可以通过功能块在应用程序中手动启动从站 CiA405.NMT . 奴隶有一个红色的感叹号。 从站报告了紧急情况（例如，由于电缆损坏）或发生了配置错误（SDO 在配置阶段中止）。 检查 CANopen 管理器的状态页面和记录器页面。您将在此处找到更多信息。 有关紧急情况的更多信息，请参阅从站手册。 配置错误的可能原因： EDS 文件与设备不匹配或包含错误。 联系制造商。 对于模块化设备：设备树中模块的顺序或类型与物理构造不匹配。 在 CANopen Manager 设备上执行设备扫描并比较配置。 奴隶有一个灰色的感叹号。 过去发生了一个错误，在此期间已更正。您可以检查这是哪个错误的记录器页面。您可以通过单击确认灰色感叹号 确认 状态页面上的按钮或设备上下文菜单中的命令。 从机的输入和输出不工作。 可能的原因： CANopen 管理器可能尚未处于 OPERATIONAL 状态（无绿色图标）。 CANopen 管理器只能在 OPERATIONAL 状态下编辑 PDO。只有当所有必需的 CANopen 订阅者都处于 OPERATIONAL 状态时，CANopen 管理器才会达到此状态。此外， 自动启动 CANopen 管理器 选项必须在 CANopen 管理器配置器中设置，或者 CANopen 管理器必须通过功能块 CiA405.NMT 手动启动。 受影响的从站尚未处于 OPERATIONAL 状态（无绿色图标）或发生配置错误（SDO 在配置阶段中止）。 您可以在相应从站的记录器和状态页面上读取可能的配置错误。 如果 启动奴隶 CANopen Manager 配置器中的选项被禁用，然后您必须通过功能块手动启动从站 CiA405.NMT 以便包括 I\/O 数据流量。如果 自动启动 CANopen 管理器 选项被禁用，那么您还必须手动启动管理器。 从站的模拟输入不起作用。 可能的原因： 对于输入，从机中不产生中断。例如，在模拟输入的情况下，当关联 PDO 设置为传输类型“异步”（254 或 255）而不是 活动时间 已定义。 为此提供了三种解决方案。 将 PDO 设置为同步并激活 同步制作 在 CANopen 管理器中。 设置 活动时间 PDO 的值 > 0 在 SDO 页面上，插入对象 16#6423sub0（模拟输入全局中断使能）并将值设置为 1 一个奴隶偶尔退出（变成红色然后又变成绿色）。 可能的原因： 总线循环任务中存在循环时间异常值。 在任务监视器中，检查总线循环任务的最小和最大时间。 在应用程序中，搜索产生这些循环时间异常值的应用程序代码：优化代码或将其移至另一个任务。 句柄泄漏是由错误的驱动程序或 CL2 层的错误使用引起的。 存在物理错误。 请参阅基于 CAN 的现场总线的故障排除。 " }, 
{ "title" : "库：CANopen 管理器（主） ", 
"url" : "_can_canopen_manager_libraries.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 管理器（主站） \/ 库：CANopen 管理器（主） ", 
"snippet" : "民航局中央情报局 405 3S CANopenStack 3S CANopen 安全...", 
"body" : "民航局中央情报局 405 3S CANopenStack 3S CANopen 安全 " }, 
{ "title" : "CANopen 本地设备（从站） ", 
"url" : "_can_f_canopen_local_device.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "一般的 ", 
"url" : "_can_f_canopen_local_device_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 一般的 ", 
"snippet" : "在 CODESYS , CANopen 本地设备是您插入到项目设备树中 CAN 总线节点正下方的从设备。结果， CODESYS 运行时充当 CANopen 从站。 (1) CANbus 节点 (2) CANopen 本地设备...", 
"body" : "在 CODESYS , CANopen 本地设备是您插入到项目设备树中 CAN 总线节点正下方的从设备。结果， CODESYS 运行时充当 CANopen 从站。 (1) CANbus 节点 (2) CANopen 本地设备 " }, 
{ "title" : "配置 ", 
"url" : "_can_f_canopen_local_device_configuration.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 " }, 
{ "title" : "选项卡：CANopen 本地设备 - 常规 ", 
"url" : "_can_edt_canopen_local_device_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 - 常规 ", 
"snippet" : "一般的 节点 ID 节点号将 CANopen 从站标识为唯一的（值范围：1...127）。 设备配置文件 用于实现 CANopen 从站的设备配置文件。如果对象目录的数据库 (*.CODB) 可用，则在 对象目录 对话框适用于设备配置文件 ID。设备配置文件 ID 在 CIA 规范中定义。 编辑 I\/O 区域 CANopen 从站的输入和输出由 I\/O 区域表示。 I\/O 区域是相同数据类型的输入和输出的集合。 为每个 I\/O 自动创建一个 I\/O 通道和一个映射变量。映射变量允许在应用程序中读取或写入 I\/O。 这 编辑 I\/O 区域 按钮打开一个对话框，用于定义 I\/O 区域和从站的相应对...", 
"body" : "一般的 节点 ID 节点号将 CANopen 从站标识为唯一的（值范围：1...127）。 设备配置文件 用于实现 CANopen 从站的设备配置文件。如果对象目录的数据库 (*.CODB) 可用，则在 对象目录 对话框适用于设备配置文件 ID。设备配置文件 ID 在 CIA 规范中定义。 编辑 I\/O 区域 CANopen 从站的输入和输出由 I\/O 区域表示。 I\/O 区域是相同数据类型的输入和输出的集合。 为每个 I\/O 自动创建一个 I\/O 通道和一个映射变量。映射变量允许在应用程序中读取或写入 I\/O。 这 编辑 I\/O 区域 按钮打开一个对话框，用于定义 I\/O 区域和从站的相应对象目录索引。 I\/O 区域的可能数量和大小取决于未使用的 PDO 的数量。 目前的数量 使用的 TxPDO 和 使用的 RxPDO 始终显示在表格下方。对于 CANopen 本地设备版本 3.5.4.0 及更高版本，最多可以有 512 个 PDO（Tx 和 Rx）（旧版本最多只能有 16 个 PDO）。 编辑 SDO 参数区 打开 编辑 SDO 参数区 对话。有关详细信息，请参阅对话框的说明。 编辑安全 I\/O 区域 该按钮仅适用于 CANopen 安全从站。 打开 编辑安全 I\/O 区域 用于定义安全 I\/O 区域的对话框 使用此命令，可以轻松定义安全 I\/O 区域，因为相应的 SRDO 和映射是自动生成的。 EDS 文件 供应商名称 一般信息保存在 EDS 文件中 产品名称 设备的标识符 这些信息是客观的 0x1008 。 供应商编号 设备的标识符 这些信息是客观的 0x1018 。 产品编号 修订号 安装到设备存储库 如果已安装具有相同设备标识的设备，则会询问您是否应覆盖该设备。如果设备作为 CANopen 远程设备插入到 CANopen 管理器下方，则会要求您自动更新设备。 导出 EDS 文件 EDS 文件根据 CiA 306 标准创建并存储在本地计算机上。 这样，EDS文件就可以在外部配置文件中使用了。 " }, 
{ "title" : "对话框：编辑 I\/O 区域 ", 
"url" : "_can_edt_canopen_local_device_general.html#UUID-84d84dea-d98c-daca-bceb-5498dbb7d70c_id_cde69e0f958b8697c0a8640e0153197a-id-5ff9d431ec1d47a0c0a8640e01f5cbdf", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 - 常规 \/ 对话框：编辑 I\/O 区域 ", 
"snippet" : "该对话框显示从站当前有效的 I\/O 区域。 添加区域 打开 添加 I\/O 范围 对话 如果您已经使用了所有 PDO，则无法修改此对话框。 使用的 TxPDO 当前使用的 TxPDO 数量\/最大可能的 TxPDO 使用的 RxPDO 当前使用的 RxPDO 数量\/最大可能的 RxPDO “添加 I\/O 范围”对话框 输入输出方向 输入或输出 范围名称 系统会自动输入唯一的默认名称，但可以更改。 对象索引 分配给新对象的从站对象目录中的索引 数数 I\/O 数量。可能的值取决于数据类型和当前未使用的 PDO 数量。 类型 可能的数据类型列表框 强制新的 PDO （默认） 每个新的 I\/O 区域都映射...", 
"body" : "该对话框显示从站当前有效的 I\/O 区域。 添加区域 打开 添加 I\/O 范围 对话 如果您已经使用了所有 PDO，则无法修改此对话框。 使用的 TxPDO 当前使用的 TxPDO 数量\/最大可能的 TxPDO 使用的 RxPDO 当前使用的 RxPDO 数量\/最大可能的 RxPDO “添加 I\/O 范围”对话框 输入输出方向 输入或输出 范围名称 系统会自动输入唯一的默认名称，但可以更改。 对象索引 分配给新对象的从站对象目录中的索引 数数 I\/O 数量。可能的值取决于数据类型和当前未使用的 PDO 数量。 类型 可能的数据类型列表框 强制新的 PDO （默认） 每个新的 I\/O 区域都映射到一个新的 PDO，即使可用的 PDO 映射未满。 ：在创建新 PDO 之前，当前 PDO 映射已完全填充（如果可能）。 行 激活新的 I\/O 区域。 创建输入\/输出通道和映射变量。在设备的对象目录中，每个 I\/O 区域都有自己的索引（输出范围：0x3000 – 0x30FF，输入范围：0x3800 – 0x38FF），并且 I\/O 区域中的每个 I\/O 都收到一个子索引。 创建 I\/O 区域时，会自动生成 PDO（RxPDO 从 0x1400 开始，TxPDO 从 0x1800 开始）。如果 强制新的 PDO 选项被选中（见上文），然后 I\/O 将自动映射到这些新的 PDO。 " }, 
{ "title" : "对话框：编辑 SDO 参数区 ", 
"url" : "_can_edt_canopen_local_device_general.html#UUID-84d84dea-d98c-daca-bceb-5498dbb7d70c_id_cde69e0f958b8697c0a8640e0153197a-id-9108da6dfb69fa05c0a864632a70c934", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 - 常规 \/ 对话框：编辑 SDO 参数区 ", 
"snippet" : "您可以定义 SDO 可以读取或写入的读\/写参数（SDO 参数）。为此，您必须定义参数区域，每个区域都是相同数据类型的参数的集合。为每个 SDO 自动创建一个 I\/O 通道和一个映射变量。映射变量允许通过应用程序读取和写入 I\/O。在设备的对象目录中，每个 SDO 参数区都显示有自己的索引，参数区内的每个 SDO 参数都显示有子索引： SDO 写参数范围：0x5000–0x50FF SDO 读取参数范围：0x5800–0x58FF 该对话框显示当前有效的参数区域及其对象目录索引。 添加区域 打开 添加参数范围 对话 “添加参数范围”对话框 该对话框允许您轻松添加 I\/O。 SDO 访问类型 只读...", 
"body" : "您可以定义 SDO 可以读取或写入的读\/写参数（SDO 参数）。为此，您必须定义参数区域，每个区域都是相同数据类型的参数的集合。为每个 SDO 自动创建一个 I\/O 通道和一个映射变量。映射变量允许通过应用程序读取和写入 I\/O。在设备的对象目录中，每个 SDO 参数区都显示有自己的索引，参数区内的每个 SDO 参数都显示有子索引： SDO 写参数范围：0x5000–0x50FF SDO 读取参数范围：0x5800–0x58FF 该对话框显示当前有效的参数区域及其对象目录索引。 添加区域 打开 添加参数范围 对话 “添加参数范围”对话框 该对话框允许您轻松添加 I\/O。 SDO 访问类型 只读 或者 读\/写 范围名称 系统会自动输入一个唯一名称。 （此名称可以修改。） 对象索引 分配给新对象的从站对象目录中的索引 数数 参数数量 类型 可能的数据类型列表框 " }, 
{ "title" : "对话框：编辑安全 I\/O 区域 ", 
"url" : "_can_edt_canopen_local_device_general.html#UUID-84d84dea-d98c-daca-bceb-5498dbb7d70c_id_cde69e0f958b8697c0a8640e0153197a-id-83009ab6fb69fa05c0a8646358d0bd17", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 - 常规 \/ 对话框：编辑安全 I\/O 区域 ", 
"snippet" : "该对话框显示从站当前有效的安全 I\/O 区域。 I\/O 概述 添加区域 打开 添加安全 I\/O 范围 对话 删除区域 删除选定的安全 I\/O 区域 使用的 SRDO <当前使用的 SRDO 数量> \/<最大可能的 SRDO> (64) . “添加安全 I\/O 范围”对话框 输入输出方向 发送 ：安全输入区 发送 SRDO 及其映射是自动生成的。 收到 : 安全输出区 接收 SRDO 及其映射是自动生成的。 范围名称 名称是自动定义的，例如 Safety_Digital_Inputs1 , 可以修改。 普通对象索引 从站对象目录中普通数据对象的索引 逆对象索引 从站对象目录中反向数据对象的索引 ...", 
"body" : "该对话框显示从站当前有效的安全 I\/O 区域。 I\/O 概述 添加区域 打开 添加安全 I\/O 范围 对话 删除区域 删除选定的安全 I\/O 区域 使用的 SRDO <当前使用的 SRDO 数量> \/<最大可能的 SRDO> (64) . “添加安全 I\/O 范围”对话框 输入输出方向 发送 ：安全输入区 发送 SRDO 及其映射是自动生成的。 收到 : 安全输出区 接收 SRDO 及其映射是自动生成的。 范围名称 名称是自动定义的，例如 Safety_Digital_Inputs1 , 可以修改。 普通对象索引 从站对象目录中普通数据对象的索引 逆对象索引 从站对象目录中反向数据对象的索引 数数 安全 I\/O 的数量。可能的值取决于数据类型和当前未使用的 SRDO 数量。 类型 选择 SAFE 数据类型 SAFEREAL 和 SAFELREAL 目前不支持。 强制新的 SRDO ： 默认设置 每个新的安全 I\/O 区域都映射到一个新的 SRDO，即使可用的 SRDO 映射未满。 ：在创建新的 SRDO 之前，当前的 SRDO 映射已完全填充（如果可能）。 行 激活新的安全 I\/O 区域。 SRDO 和相应的映射是自动生成的。在设备的对象目录中，每个 I\/O 区域都有自己的索引（输出范围：0x3000 – 0x30FF，输入范围：0x3800 – 0x38FF），并且 I\/O 区域中的每个 I\/O 都收到一个子索引。 " }, 
{ "title" : "选项卡：CANopen 本地设备 – 对象目录 ", 
"url" : "_can_edt_canopen_local_device_object_directory.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 – 对象目录 ", 
"snippet" : "此对话框仅在版本 V3.5.6.0 或更高版本的 CANopen 设备的设备编辑器中可用。它显示了对象目录的所有对象及其参数。在此对话框中，您可以添加新对象以及删除或编辑现有对象。 添加对象 打开 添加对象 对话框，显示属于设备配置文件的所有对象。在对话框中，您可以选择要添加到对象目录的对象。 添加子对象 选择结构化对象时可用。该命令打开 添加子对象 用于定义子对象的对话框。在这里您提供 开始子索引 和 数数 的对象。 删除 从列表中删除选定的条目 克隆 复制选定的对象。该命令打开一个对话框，用于定义开始索引和克隆对象的数量。 从 EDS 导入 从现有 EDS 文件导入数据 所选对象的属性显示...", 
"body" : "此对话框仅在版本 V3.5.6.0 或更高版本的 CANopen 设备的设备编辑器中可用。它显示了对象目录的所有对象及其参数。在此对话框中，您可以添加新对象以及删除或编辑现有对象。 添加对象 打开 添加对象 对话框，显示属于设备配置文件的所有对象。在对话框中，您可以选择要添加到对象目录的对象。 添加子对象 选择结构化对象时可用。该命令打开 添加子对象 用于定义子对象的对话框。在这里您提供 开始子索引 和 数数 的对象。 删除 从列表中删除选定的条目 克隆 复制选定的对象。该命令打开一个对话框，用于定义开始索引和克隆对象的数量。 从 EDS 导入 从现有 EDS 文件导入数据 所选对象的属性显示在选项卡的右侧。选择几个对象时， CODESYS 仅显示共享属性。您可以在此视图中编辑这些属性的值。 上限和下限的值仅作为 EDS 文件的信息提供。这些值不是堆栈的进程。应用程序必须使用对象目录接口监视限制。 " }, 
{ "title" : "选项卡：CANopen 本地设备 – PDO ", 
"url" : "_can_edt_canopen_local_device_pdos.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 – PDO ", 
"snippet" : "对象：CANopen 远程设备、CANopen 本地设备 此对话框在版本 V3.5.6.0 或更高版本的 CANopen 本地从站的设备编辑器中可用。它显示所有 PDO 及其默认设置。该对话框提供了一个简单的编辑器，用于创建和编辑对象目录中的对象，这是从站的 PDO 行为所必需的。您可以在此处设置从站唤醒时使用的默认值。主设备可以在运行时重新配置默认值。 该数据通过 EDS 导出导出到 EDS 文件。 在左侧，有从站从主站接收的 PDO。在右侧，有从站发送给主站的 PDO。 添加 PDO 打开 选择 PDO 显示所有可用 PDO 的对话框。在此对话框中，选择要添加到的 PDO 接收 PDO 或...", 
"body" : "对象：CANopen 远程设备、CANopen 本地设备 此对话框在版本 V3.5.6.0 或更高版本的 CANopen 本地从站的设备编辑器中可用。它显示所有 PDO 及其默认设置。该对话框提供了一个简单的编辑器，用于创建和编辑对象目录中的对象，这是从站的 PDO 行为所必需的。您可以在此处设置从站唤醒时使用的默认值。主设备可以在运行时重新配置默认值。 该数据通过 EDS 导出导出到 EDS 文件。 在左侧，有从站从主站接收的 PDO。在右侧，有从站发送给主站的 PDO。 添加 PDO 打开 选择 PDO 显示所有可用 PDO 的对话框。在此对话框中，选择要添加到的 PDO 接收 PDO 或者 发送 PDO . 添加映射 打开 从对象目录中选择项目 对话。那里列出了可以添加到 PDO 映射的对象。 编辑 选择PDO时， PDO 属性 对话框打开。 选择PDO映射时， 从对象目录中选择项目 对话框打开。 删除 从列表中删除选定的对象 提升 将选定对象向上移动一行。 下移 将选定对象向下移动一行。 " }, 
{ "title" : "对话框：PDO 属性 ", 
"url" : "_can_edt_canopen_local_device_pdos.html#UUID-d6f7a804-79fa-2441-04aa-25f05c12beb8_id_c23eb8cb25be9c86c0a86463028f1ec2-id-c4e82b9414c0f026c0a8640e00f1a2da", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 – PDO \/ 对话框：PDO 属性 ", 
"snippet" : "COB-ID 每个 PDO 消息都必须有一个 COB-ID（通信对象标识符）。您可以输入显式值（例如：16#201）或公式（例如：$NODEID+16#200）。 RTR 远程传输请求。此选项仅适用于传输 PDO。 ：您可以使用 RTR 帧从外部询问 PDO。 传输类型 非循环 - 同步（类型 0） ：当发生变化时，PDO 是同步传输的，而不是周期性传输的。 （默认） 循环 - 同步（1-240 型） : PDO 每第 n 个同步发送一次。 同步 – 仅 RTR（252 型） ：仅适用于传输 PDO。在同步消息之后，更新 PDO，但不发送。传输仅通过显式请求（远程传输请求）。 异步 — 仅限 ...", 
"body" : "COB-ID 每个 PDO 消息都必须有一个 COB-ID（通信对象标识符）。您可以输入显式值（例如：16#201）或公式（例如：$NODEID+16#200）。 RTR 远程传输请求。此选项仅适用于传输 PDO。 ：您可以使用 RTR 帧从外部询问 PDO。 传输类型 非循环 - 同步（类型 0） ：当发生变化时，PDO 是同步传输的，而不是周期性传输的。 （默认） 循环 - 同步（1-240 型） : PDO 每第 n 个同步发送一次。 同步 – 仅 RTR（252 型） ：仅适用于传输 PDO。在同步消息之后，更新 PDO，但不发送。传输仅通过显式请求（远程传输请求）。 异步 — 仅限 RTR（类型 253） ：仅适用于传输 PDO。PDO 仅通过明确请求（远程传输请求）传输 异步 - 制造商特定（254 型） : PDO 仅在特定事件之后传输。 异步 – 特定于设备配置文件（255 型） ：根据 CiA 设备配置文件传输 PDO。 同步数 对于传输类型 循环 - 同步 只要 指示传输 PDO 的时间间隔。该值是 周期（微秒） CANopen 管理器。默认值：1。可能的值：1–240。 示例：同步数 = 4，周期周期 = 1000 µs → 传输间隔 = 4000 µs。 支持禁止时间 ：从机支持禁止时间。 抑制时间 禁止时间的默认值 支持活动时间 ：从站支持事件时间。 活动时间 事件时间的默认值 " }, 
{ "title" : "对话框：选择 PDO 映射 ", 
"url" : "_can_edt_canopen_local_device_pdos.html#UUID-d6f7a804-79fa-2441-04aa-25f05c12beb8_id_c23eb8cb25be9c86c0a86463028f1ec2-id-0417cab97b9c11e4b88187ab7ade6762", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 本地设备 – PDO \/ 对话框：选择 PDO 映射 ", 
"snippet" : "该表显示了对象目录中所有“可映射”对象的过滤视图。 指数 对象的索引 名称 PDO 的 COB-ID 或在设备描述和对象目录中使用的“映射”对象的名称。 类型 对象的数据类型 默认值 对象的默认值 访问类型 RW ：读\/写 反渗透 ： 只读 WO : 只写 RWW ：每个 SDO 读\/写；每个 PDO 的写权限（==> RPDO，从主机的角度输出，从从机的角度输入）。 RWR ：每个 SDO 读\/写；每个 PDO 的读取权限（==> TPDO，从主机的角度输入，从从机的角度输出）。 常数=常数...", 
"body" : "该表显示了对象目录中所有“可映射”对象的过滤视图。 指数 对象的索引 名称 PDO 的 COB-ID 或在设备描述和对象目录中使用的“映射”对象的名称。 类型 对象的数据类型 默认值 对象的默认值 访问类型 RW ：读\/写 反渗透 ： 只读 WO : 只写 RWW ：每个 SDO 读\/写；每个 PDO 的写权限（==> RPDO，从主机的角度输出，从从机的角度输入）。 RWR ：每个 SDO 读\/写；每个 PDO 的读取权限（==> TPDO，从主机的角度输入，从从机的角度输出）。 常数=常数 " }, 
{ "title" : "选项卡：CANopen 安全从站 – SRDO ", 
"url" : "_can_edt_canopen_local_device_srdos.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 安全从站 – SRDO ", 
"snippet" : "除了定义安全相关数据对象 (SRDO) 之外，该选项卡还用于显示 SRDO 和专家。整个 CAN 网络中最多可以有 64 个 SRDO。这 接收 SRDO（主设备 => 从设备） 显示在左侧和 发送 SRDO（从设备 => 主设备） 显示在右侧。 基本上，每个 SRDO 由两个 CAN 报文组成：一个包含数据的 COB-ID 不均匀的电报，以及一个包含偶数 COB-ID 和位反转数据的电报。然后最大可能的数据大小为 8 个字节。 添加 SRDO 打开 选择 SRDO 对话。该对话框显示标准中定义的 SRDO。 在此对话框中选择一个 SRDO 并确认后，该 SRDO 将显示在 SRDO 标签。 ...", 
"body" : "除了定义安全相关数据对象 (SRDO) 之外，该选项卡还用于显示 SRDO 和专家。整个 CAN 网络中最多可以有 64 个 SRDO。这 接收 SRDO（主设备 => 从设备） 显示在左侧和 发送 SRDO（从设备 => 主设备） 显示在右侧。 基本上，每个 SRDO 由两个 CAN 报文组成：一个包含数据的 COB-ID 不均匀的电报，以及一个包含偶数 COB-ID 和位反转数据的电报。然后最大可能的数据大小为 8 个字节。 添加 SRDO 打开 选择 SRDO 对话。该对话框显示标准中定义的 SRDO。 在此对话框中选择一个 SRDO 并确认后，该 SRDO 将显示在 SRDO 标签。 添加映射 要求：选择了一个 SRDO。 该命令打开 SRDO 映射 添加映射的对话框。相应的对象必须已经添加到 对象目录 . 编辑 如果选择了 SRDO，则 SRDO 属性 对话框打开。 如果选择了映射，则 SRDO 映射 对话框打开。 删除 删除选定的行。 名称 SRDO 的名称和映射 ：SRDO默认激活。 : ：默认情况下，SRDO 处于禁用状态。 当鼠标指针位于名称上时，SRDO 的参数将显示为工具提示。 " }, 
{ "title" : "对话框：SRDO 映射 ", 
"url" : "_can_edt_canopen_local_device_srdos.html#UUID-fac9112d-f2d9-93c8-a2c2-8676ca4af3fb_id_d4c97bfff64bda7c0a8646357f9eee7-id-0f18548089bf4207c0a8640e0075a528", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 安全从站 – SRDO \/ 对话框：SRDO 映射 ", 
"snippet" : "在对话框中，为反向数据对象定义了纯数据对象的映射和分配。 普通数据对象 双击它下面的行打开 选择 SRDO 映射 从对象目录中显示适用元素的对话框。 在对话框中选择纯数据类型时 选择 SRDO 映射 并点击 行 ，数据对象被添加到 SRDO 映射 对话。 反向数据对象 双击它下面的行打开 选择 SRDO 映射 对话。 在对话框中选择反向数据类型时 选择 SRDO 映射 并点击 行 ，数据对象被添加到 SRDO 映射 对话。 CODESYS 自动检查纯数据对象和逆数据对象的数据类型和数据长度是否匹配。结果显示在对话框的底部。...", 
"body" : "在对话框中，为反向数据对象定义了纯数据对象的映射和分配。 普通数据对象 双击它下面的行打开 选择 SRDO 映射 从对象目录中显示适用元素的对话框。 在对话框中选择纯数据类型时 选择 SRDO 映射 并点击 行 ，数据对象被添加到 SRDO 映射 对话。 反向数据对象 双击它下面的行打开 选择 SRDO 映射 对话。 在对话框中选择反向数据类型时 选择 SRDO 映射 并点击 行 ，数据对象被添加到 SRDO 映射 对话。 CODESYS 自动检查纯数据对象和逆数据对象的数据类型和数据长度是否匹配。结果显示在对话框的底部。 " }, 
{ "title" : "对话框：SRDO 属性 ", 
"url" : "_can_edt_canopen_local_device_srdos.html#UUID-fac9112d-f2d9-93c8-a2c2-8676ca4af3fb_id_d4c97bfff64bda7c0a8646357f9eee7-id-95e791ea1458e034c0a864633a1b8f8c", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen 安全从站 – SRDO \/ 对话框：SRDO 属性 ", 
"snippet" : "称呼 : 双击 SRDO SRDO 标签。 COB-ID 1： 包含数据的 CAN 报文的 COB-ID。 注意：为了符合标准，应指定一个不均匀的 COB-ID 或 0。 输入字段的工具提示显示有关 COB-ID 的信息。 COB-ID 2： 包含反向数据的 CAN 报文的 COB-ID。 注意：为了符合标准，应指定偶数 COB-ID 或 0。 输入字段的工具提示显示有关 COB-ID 的信息。...", 
"body" : "称呼 : 双击 SRDO SRDO 标签。 COB-ID 1： 包含数据的 CAN 报文的 COB-ID。 注意：为了符合标准，应指定一个不均匀的 COB-ID 或 0。 输入字段的工具提示显示有关 COB-ID 的信息。 COB-ID 2： 包含反向数据的 CAN 报文的 COB-ID。 注意：为了符合标准，应指定偶数 COB-ID 或 0。 输入字段的工具提示显示有关 COB-ID 的信息。 " }, 
{ "title" : "选项卡：CANopen – 安全从站 – I\/O 映射 ", 
"url" : "_can_edt_canopen_local_device_safety_io_mapping.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 配置 \/ 选项卡：CANopen – 安全从站 – I\/O 映射 ", 
"snippet" : "对象：CANopen 安全设备（从站） 该选项卡对应于 CANopen 安全从站 – SRDO 选项卡，除了 SRDO 的所有映射（所有安全映射）都显示在此选项卡上。...", 
"body" : "对象：CANopen 安全设备（从站） 该选项卡对应于 CANopen 安全从站 – SRDO 选项卡，除了 SRDO 的所有映射（所有安全映射）都显示在此选项卡上。 " }, 
{ "title" : "职能 ", 
"url" : "_can_f_canopen_local_device_functions.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 安全 ", 
"url" : "_can_f_canopen_local_device_functions.html#UUID-36687d99-cc05-5612-e048-aba357281f45_section-idm4623547520654432570344028781", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 职能 \/ CANopen 安全 ", 
"snippet" : "CANopen Safety 作为欧洲标准 (EN 50325-5) 发布。这意味着可以通过满足 SIL3 应用要求的 CAN 网络传输数据。这种面向安全的数据传输可以与现有的 CANopen 数据传输并行进行。 CODESYS CANopen Safety 支持符合 SIL2 的安全要求。 除了用于数据传输的传统 CANopen 服务（例如 SDO 和 PDO）之外，还为带有 SRDO 服务（安全相关数据对象）的安全扩展定义了用于这种数据传输的特殊服务。关于通信的配置和类型，它类似于 PDO，但定义了其他属性。 要使用 CANopen Safety，将 CANopen 设备 SIL2 插入设...", 
"body" : "CANopen Safety 作为欧洲标准 (EN 50325-5) 发布。这意味着可以通过满足 SIL3 应用要求的 CAN 网络传输数据。这种面向安全的数据传输可以与现有的 CANopen 数据传输并行进行。 CODESYS CANopen Safety 支持符合 SIL2 的安全要求。 除了用于数据传输的传统 CANopen 服务（例如 SDO 和 PDO）之外，还为带有 SRDO 服务（安全相关数据对象）的安全扩展定义了用于这种数据传输的特殊服务。关于通信的配置和类型，它类似于 PDO，但定义了其他属性。 要使用 CANopen Safety，将 CANopen 设备 SIL2 插入设备树中，而不是 CANopen 设备。安全的 CANopen 设备具有 安全特定页面 除了通常的配置页面。可以在其中配置 SRDO（安全 PDO）。除了通常的不安全设备实例外，还会为每个安全设备（CANopen 设备）生成一个带有前缀“S_”的附加实例。这提供了特定于安全的诊断功能。 使用 CANopen 设备 SIL2 需要 SIL2 CODESYS Runtime 以及经过特别适配的 CAN 微型驱动程序和 CODESYS SIL2 插件。所需的库和设备已包含在标准安装中。 " }, 
{ "title" : "重新配置 – CANopen 本地设备（从站） ", 
"url" : "_can_f_canopen_local_device_functions.html#UUID-36687d99-cc05-5612-e048-aba357281f45_section-idm4506522906022432570345301931", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 职能 \/ 重新配置 – CANopen 本地设备（从站） ", 
"snippet" : "使用“重新配置”功能，您可以在应用程序运行时动态调整最初下载到控制器的 CAN 总线配置。 带功能块 DED.Reconfigure ，在启用通用设备诊断时可用 ( PLC 设置： )，您可以在运行时执行以下操作。 单个设备的激活和停用 有关更多信息，请参阅： 重新配置 – CANbus...", 
"body" : "使用“重新配置”功能，您可以在应用程序运行时动态调整最初下载到控制器的 CAN 总线配置。 带功能块 DED.Reconfigure ，在启用通用设备诊断时可用 ( PLC 设置： )，您可以在运行时执行以下操作。 单个设备的激活和停用 有关更多信息，请参阅： 重新配置 – CANbus" }, 
{ "title" : "CANopen 设备的总线周期行为 ", 
"url" : "_can_f_canopen_local_device_functions.html#UUID-36687d99-cc05-5612-e048-aba357281f45_section-idm43257034723426", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 职能 \/ CANopen 设备的总线周期行为 ", 
"snippet" : "0：发送\/接收同步 PDO 1：接收异步 PDO 2：IEC 任务 3：将输出写入输出缓冲区 4：发送异步 PDO 有关更多信息，请参阅： 任务配置...", 
"body" : "0：发送\/接收同步 PDO 1：接收异步 PDO 2：IEC 任务 3：将输出写入输出缓冲区 4：发送异步 PDO 有关更多信息，请参阅： 任务配置 " }, 
{ "title" : "诊断 ", 
"url" : "_can_f_canopen_local_device_diagnosis.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 诊断 ", 
"url" : "_can_f_canopen_local_device_canopen_diagnosis.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ CANopen 诊断 ", 
"snippet" : "本章介绍 CANopen 协议提供的诊断选项。...", 
"body" : "本章介绍 CANopen 协议提供的诊断选项。 " }, 
{ "title" : "CANopen 状态 ", 
"url" : "_can_f_canopen_local_device_canopen_diagnosis.html#UUID-119322f2-78ea-5be8-0df0-246cda46c36c_section-idm458723619644003257141490146", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ CANopen 诊断 \/ CANopen 状态 ", 
"snippet" : "CANopen 网络由 NMT 主站（网络管理）和 NMT 从站组成。在这种情况下，NMT 主机控制所有设备并可以更改它们的通信状态。 CANopen 设备处于以下四种可能状态之一： 初始化：开启后，节点经过这个状态。此时，设备应用程序和设备通信（比特率和节点地址）被初始化。之后，节点独立切换到“预操作”状态。 预操作：可以通过 SDO 与节点通信。但是，节点不能执行 PDO 通信。 运行：CANopen 节点完全运行。它可以独立发送和接收过程数据。 已停止：节点与网络完全分离。无法进行 SDO 或 PDO 通信。节点只能通过相应的网络命令（例如：启动节点）才能更改为另一种网络状态。...", 
"body" : "CANopen 网络由 NMT 主站（网络管理）和 NMT 从站组成。在这种情况下，NMT 主机控制所有设备并可以更改它们的通信状态。 CANopen 设备处于以下四种可能状态之一： 初始化：开启后，节点经过这个状态。此时，设备应用程序和设备通信（比特率和节点地址）被初始化。之后，节点独立切换到“预操作”状态。 预操作：可以通过 SDO 与节点通信。但是，节点不能执行 PDO 通信。 运行：CANopen 节点完全运行。它可以独立发送和接收过程数据。 已停止：节点与网络完全分离。无法进行 SDO 或 PDO 通信。节点只能通过相应的网络命令（例如：启动节点）才能更改为另一种网络状态。 " }, 
{ "title" : "错误寄存器 ", 
"url" : "_can_f_canopen_local_device_canopen_diagnosis.html#UUID-119322f2-78ea-5be8-0df0-246cda46c36c_section-idm4660739080796832571416798055", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ CANopen 诊断 \/ 错误寄存器 ", 
"snippet" : "根据 CiA 301，每个 CANopen 设备都有一个错误寄存器（对象 16#1001）。该寄存器可通过 SDO 读取，并在出现错误时提供有关错误的附加信息。 错误寄存器中只需要位 0（一般错误）。其他位是可选的，并非由每个从站设置。一旦设备检测到任何错误，至少会设置该对象的第 0 位。 错误寄存器 少量 描述 0 一般错误 1 当前的 2 电压 3 温度 4 通讯错误（溢出错误状态） 5 特定于设备配置文件 6 保留（始终为 0） 7 特定于制造商...", 
"body" : "根据 CiA 301，每个 CANopen 设备都有一个错误寄存器（对象 16#1001）。该寄存器可通过 SDO 读取，并在出现错误时提供有关错误的附加信息。 错误寄存器中只需要位 0（一般错误）。其他位是可选的，并非由每个从站设置。一旦设备检测到任何错误，至少会设置该对象的第 0 位。 错误寄存器 少量 描述 0 一般错误 1 当前的 2 电压 3 温度 4 通讯错误（溢出错误状态） 5 特定于设备配置文件 6 保留（始终为 0） 7 特定于制造商 " }, 
{ "title" : "紧急和预定义错误字段 (EMCY) ", 
"url" : "_can_f_canopen_local_device_canopen_diagnosis.html#UUID-119322f2-78ea-5be8-0df0-246cda46c36c_section-idm4567920696288032571418596272", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ CANopen 诊断 \/ 紧急和预定义错误字段 (EMCY) ", 
"snippet" : "CANopen 定义了可选的紧急 (EMCY) 协议来指示错误。紧急情况是根据带有 CAN-ID 16#80 + NODE-ID 的预定义连接集传输的 CAN 消息。 电报具有以下结构： 紧急消息的长度始终为 8 个字节。相应的紧急错误代码 (EEC) 在前两个字节中传输。其后是错误寄存器 0x1011（ER：错误寄存器）和 5 个制造商特定字节（MEF：制造商特定错误字段）的当前值。 错误代码的相应解释必须从制造商手册中获取。并非所有从站都支持紧急协议，必须由 CANopen 管理器进行相应配置。 可通过 SDO 从对象 16#1003 中读取已发生紧急情况的历史记录（错误历史记录）。这里，...", 
"body" : "CANopen 定义了可选的紧急 (EMCY) 协议来指示错误。紧急情况是根据带有 CAN-ID 16#80 + NODE-ID 的预定义连接集传输的 CAN 消息。 电报具有以下结构： 紧急消息的长度始终为 8 个字节。相应的紧急错误代码 (EEC) 在前两个字节中传输。其后是错误寄存器 0x1011（ER：错误寄存器）和 5 个制造商特定字节（MEF：制造商特定错误字段）的当前值。 错误代码的相应解释必须从制造商手册中获取。并非所有从站都支持紧急协议，必须由 CANopen 管理器进行相应配置。 可通过 SDO 从对象 16#1003 中读取已发生紧急情况的历史记录（错误历史记录）。这里，子索引 0 包含存储错误的数量，以下子对象包含传输的紧急情况的数据内容。 " }, 
{ "title" : "监控机制：心跳和节点保护 ", 
"url" : "_can_f_canopen_local_device_canopen_diagnosis.html#UUID-119322f2-78ea-5be8-0df0-246cda46c36c_section-idm4587237084881632571421607217", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ CANopen 诊断 \/ 监控机制：心跳和节点保护 ", 
"snippet" : "如果 CAN 节点不连续发送消息（循环 PDO），则需要对其进行监控。为此，提供了“心跳”和“节点保护”机制，它们可以交替使用。 节点保护：使用此协议，消息（CAN 远程帧）由 NMT 主站发送到现有的 CANopen 从站。从站必须在特定时间内响应这些消息。如果没有响应，则由 NMT 主机注册。因为通常应避免 CAN 远程帧，所以最好通过心跳进行监控。 心跳：心跳协议随 CANopen 4.0 版本发布，是首选的监控方式。在这里，每个节点独立地以循环间隔发送消息。该消息可以被网络中的任何其他用户监视。...", 
"body" : "如果 CAN 节点不连续发送消息（循环 PDO），则需要对其进行监控。为此，提供了“心跳”和“节点保护”机制，它们可以交替使用。 节点保护：使用此协议，消息（CAN 远程帧）由 NMT 主站发送到现有的 CANopen 从站。从站必须在特定时间内响应这些消息。如果没有响应，则由 NMT 主机注册。因为通常应避免 CAN 远程帧，所以最好通过心跳进行监控。 心跳：心跳协议随 CANopen 4.0 版本发布，是首选的监控方式。在这里，每个节点独立地以循环间隔发送消息。该消息可以被网络中的任何其他用户监视。 " }, 
{ "title" : "应用中的诊断 ", 
"url" : "_can_f_canopen_local_device_application.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 应用中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 状态 ", 
"url" : "_can_f_canopen_local_device_application.html#UUID-be3d5b07-d3ba-d230-d7a1-215464f6b8aa_section-idm4613673047425632571425924546", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 应用中的诊断 \/ CANopen 状态 ", 
"snippet" : "您可以在应用程序中以两种不同的方式询问本地 CANopen 从站的状态： <name in device tree>.State 财产 （ 3S CANopen设备 图书馆） <name in device tree>.GetDeviceState 方法 （ CAA 设备诊断 图书馆） 该方法不返回 CANopen 状态，而是返回设备是否正在运行的信息。 CANopenState 和 DEVICE_STATE 之间的映射表在库文档中找到 CANopenSlaveStack . 此外，还可以设置 CANopen 状态。为此，可以使用以下方法： PowerDown PowerUp Reset Re...", 
"body" : "您可以在应用程序中以两种不同的方式询问本地 CANopen 从站的状态： <name in device tree>.State 财产 （ 3S CANopen设备 图书馆） <name in device tree>.GetDeviceState 方法 （ CAA 设备诊断 图书馆） 该方法不返回 CANopen 状态，而是返回设备是否正在运行的信息。 CANopenState 和 DEVICE_STATE 之间的映射表在库文档中找到 CANopenSlaveStack . 此外，还可以设置 CANopen 状态。为此，可以使用以下方法： PowerDown PowerUp Reset ResetCommunication SwitchToOp SwitchToPreop SwitchToStopped " }, 
{ "title" : "访问本地对象目录 ", 
"url" : "_can_f_canopen_local_device_application.html#UUID-be3d5b07-d3ba-d230-d7a1-215464f6b8aa_section-idm4660665603568032571426928215", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 应用中的诊断 \/ 访问本地对象目录 ", 
"snippet" : "CANopen 从站提供访问本地对象目录（属性 ObjectDictionary）的接口。有了这个，您可以通过应用程序读取任何对象，例如，访问错误寄存器或预定义的错误字段。...", 
"body" : "CANopen 从站提供访问本地对象目录（属性 ObjectDictionary）的接口。有了这个，您可以通过应用程序读取任何对象，例如，访问错误寄存器或预定义的错误字段。 " }, 
{ "title" : "安全诊断 ", 
"url" : "_can_f_canopen_local_device_application.html#UUID-be3d5b07-d3ba-d230-d7a1-215464f6b8aa_section-idm466066533066883257142779333", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 应用中的诊断 \/ 安全诊断 ", 
"snippet" : "在安全的情况下，隐式创建的带有前缀“S_”的功能块提供相应的诊断输出。使用这些功能块，您可以定义与从站的 SRDO 通信是否处于活动状态或是否已达到安全状态。 此外，该功能块还提供输入以确认单个从站的错误以及暂时停用 SRDO 通信。 有关更多信息，请参阅： CANRemoteDeviceSafe 和 CANopenManagerSIL2 (FB)...", 
"body" : "在安全的情况下，隐式创建的带有前缀“S_”的功能块提供相应的诊断输出。使用这些功能块，您可以定义与从站的 SRDO 通信是否处于活动状态或是否已达到安全状态。 此外，该功能块还提供输入以确认单个从站的错误以及暂时停用 SRDO 通信。 有关更多信息，请参阅： CANRemoteDeviceSafe 和 CANopenManagerSIL2 (FB) " }, 
{ "title" : "用户界面中的诊断 ", 
"url" : "_can_f_canopen_local_device_ui.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 用户界面中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设备树 ", 
"url" : "_can_f_canopen_local_device_ui.html#UUID-42f89909-8b6f-a097-71a2-1ecd7d9211d3_section-idm4613673049073632571430759536", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 用户界面中的诊断 \/ 设备树 ", 
"snippet" : "在在线模式下，设备树允许精确定位待定诊断。 设备处于运行状态时的绿色符号。 错误标志（红色三角形）：如果设备未运行（例如：找不到 CAN 驱动程序）。 橙色三角形：设备处于状态 PREOPERATIONAL . 诊断标志（红色感叹号）：如果紧急错误处于活动状态或存在配置错误，但从机处于运行状态。有关错误的更多信息显示在状态页面上 ( 状态 选项卡）。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。...", 
"body" : "在在线模式下，设备树允许精确定位待定诊断。 设备处于运行状态时的绿色符号。 错误标志（红色三角形）：如果设备未运行（例如：找不到 CAN 驱动程序）。 橙色三角形：设备处于状态 PREOPERATIONAL . 诊断标志（红色感叹号）：如果紧急错误处于活动状态或存在配置错误，但从机处于运行状态。有关错误的更多信息显示在状态页面上 ( 状态 选项卡）。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。 " }, 
{ "title" : "状态页面 ", 
"url" : "_can_f_canopen_local_device_ui.html#UUID-42f89909-8b6f-a097-71a2-1ecd7d9211d3_section-idm4590836384897632571431674865", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 用户界面中的诊断 \/ 状态页面 ", 
"snippet" : "这个 状态 选项卡显示 CANopen 状态以及紧急情况和其他错误。...", 
"body" : "这个 状态 选项卡显示 CANopen 状态以及紧急情况和其他错误。 " }, 
{ "title" : "记录器页面 ", 
"url" : "_can_f_canopen_local_device_ui.html#UUID-42f89909-8b6f-a097-71a2-1ecd7d9211d3_section-idm4587237183576032571432538707", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 用户界面中的诊断 \/ 记录器页面 ", 
"snippet" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。 这仅显示由相应设备创建的条目，例如 CANopen 状态的更改、紧急消息、SDO 错误和监控错误。...", 
"body" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。 这仅显示由相应设备创建的条目，例如 CANopen 状态的更改、紧急消息、SDO 错误和监控错误。 " }, 
{ "title" : "故障排除 ", 
"url" : "_can_canopen_local_device_trouble_shooting.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 故障排除 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CANopen 本地设备（从站） ", 
"url" : "_can_canopen_local_device_trouble_shooting.html#UUID-ededd32e-c54c-684d-e991-7e089c25431c_id_f68c954ea173591c0a864637aa14c86-id-ea016e90c6330978c0a8646347219753", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 诊断 \/ 故障排除 \/ CANopen 本地设备（从站） ", 
"snippet" : "问题 可能的解决方案 CAN 总线节点为红色或带有红色感叹号。 请参阅 CAN 总线的一般故障排除。 CANopen 设备为红色或带有红色感叹号。 检查 CANopen 管理器的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 您没有许可证或演示许可证已过期。 可用内存太少。 CANopen 设备有一个橙色三角形。 CANopen 设备处于 PREOPERATIONAL 状态。 可能的原因： CAN 网络中的 CANopen 管理器尚未启动设备。 发生了监控错误，并且 CANopen 管理器从那时起没有启动设备。 配置阶段出现错误。 CANopen 设备偶尔退出（变为橙色，然后再次...", 
"body" : "问题 可能的解决方案 CAN 总线节点为红色或带有红色感叹号。 请参阅 CAN 总线的一般故障排除。 CANopen 设备为红色或带有红色感叹号。 检查 CANopen 管理器的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 您没有许可证或演示许可证已过期。 可用内存太少。 CANopen 设备有一个橙色三角形。 CANopen 设备处于 PREOPERATIONAL 状态。 可能的原因： CAN 网络中的 CANopen 管理器尚未启动设备。 发生了监控错误，并且 CANopen 管理器从那时起没有启动设备。 配置阶段出现错误。 CANopen 设备偶尔退出（变为橙色，然后再次变为绿色）。 可能的原因： 总线循环任务中的循环时间异常值： 在任务监视器中，检查总线循环任务的最小和最大时间。 在应用程序中，搜索产生这些循环时间异常值的应用程序代码：优化代码或将其移至另一个任务。 句柄泄漏是由错误的驱动程序或 CL2 层的错误使用引起的。 硬件故障 请参阅基于 CAN 的现场总线的故障排除。 " }, 
{ "title" : "库：重新配置 – CANopen 本地设备（从站） ", 
"url" : "_can_canopen_local_device_libraries.html", 
"breadcrumbs" : "CODESYS CANbus \/ CANopen 本地设备（从站） \/ 库：重新配置 – CANopen 本地设备（从站） ", 
"snippet" : "3S CANopenSlave 堆栈 3S CANopen安全从站...", 
"body" : "3S CANopenSlave 堆栈 3S CANopen安全从站 " }, 
{ "title" : "J1939 ", 
"url" : "_can_f_j1939.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 ", 
"snippet" : "J1939 是基于 CAN 的协议（CAN 代表“控制器区域网络”）。它是为重型货车电子控制单元 (ECU) 之间的串行数据传输而开发的。这 CODESYS 插件“DeviceEditorJ1939”提供了根据 SAE J1939 标准配置 J1939 设备的对话框。...", 
"body" : "J1939 是基于 CAN 的协议（CAN 代表“控制器区域网络”）。它是为重型货车电子控制单元 (ECU) 之间的串行数据传输而开发的。这 CODESYS 插件“DeviceEditorJ1939”提供了根据 SAE J1939 标准配置 J1939 设备的对话框。 " }, 
{ "title" : "一般的 ", 
"url" : "_can_f_j1939_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 一般的 ", 
"snippet" : "J1939 管理器插入到 CAN 总线节点下方的设备树中。它提供了 J1939 参数组和信号数据库。 ECU 插入在 J1939 管理器下方。 这 扫描设备 命令不适用于 J1939。 (1) CANopen Manager (2): J1939-Manager (3) J1939-ECU...", 
"body" : "J1939 管理器插入到 CAN 总线节点下方的设备树中。它提供了 J1939 参数组和信号数据库。 ECU 插入在 J1939 管理器下方。 这 扫描设备 命令不适用于 J1939。 (1) CANopen Manager (2): J1939-Manager (3) J1939-ECU " }, 
{ "title" : "配置 ", 
"url" : "_can_f_j1939_configuration.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 " }, 
{ "title" : "标签：J1939 经理 – 常规 ", 
"url" : "_can_edt_j1939_manager_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 标签：J1939 经理 – 常规 ", 
"snippet" : "在 CODESYS 版本 3.5 SP17 和 CODESYS J1939 Manager SL 版本 4.0.0.0，J1939 配置器不再提供参数组\/信号数据库。不再支持旧数据库。 但是，您可以在 J1939 Manager 中后安装 DBC 数据库。可以从 CSS Electronics 购买数据库： https:\/\/www.csselectronics.com\/screen\/product\/j1939-dbc-file-pgn-spn 如果不安装数据库，也可以手动配置参数组和信号 用户自定义 标签。 数据库 列出已安装数据库的名称（DBC 或 DB 格式） 安装 打开文件管理器以选择 ...", 
"body" : "在 CODESYS 版本 3.5 SP17 和 CODESYS J1939 Manager SL 版本 4.0.0.0，J1939 配置器不再提供参数组\/信号数据库。不再支持旧数据库。 但是，您可以在 J1939 Manager 中后安装 DBC 数据库。可以从 CSS Electronics 购买数据库： https:\/\/www.csselectronics.com\/screen\/product\/j1939-dbc-file-pgn-spn 如果不安装数据库，也可以手动配置参数组和信号 用户自定义 标签。 数据库 列出已安装数据库的名称（DBC 或 DB 格式） 安装 打开文件管理器以选择 J1939 文件（DBC 或 DB 格式）。 J1939 文件通常存储在 C:\\ProgramData\\ CODESYS \\J1939 Databases . 卸载 卸载选定的数据库 设为默认 将数据库设置为默认数据库。然后将此数据库设置为默认值 添加参数组 和 添加信号 对话框。 " }, 
{ "title" : "标签：J1939-ECU – 常规 ", 
"url" : "_can_edt_j1939_ecu_general.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 标签：J1939-ECU – 常规 ", 
"snippet" : "在 J1939 ECU 编辑器的这个对话框中，可以显示和修改 J1939 ECU 的一般参数。 一般的 首选地址 ECU 的地址。如果网络中存在多个具有相同地址的 ECU，则所有受影响的 ECU 都会获得一个新地址。要求是 ECU 允许地址更改（ 任意地址能力 ）。 本地设备 ：您可以配置任意数量的本地 ECU。那么每个本地 ECU 都是 J1939 网络中自己的 ECU 实例。对于本地设备，额外的 接收信号 (P2P) 提供对话框来配置接收到的信号。 ECU 名称 名称（64 位）：16# 包含有关后续参数的完整信息的十六进制 64 位代码。每次修改此代码时，相应的参数也会被修改。另一个方向...", 
"body" : "在 J1939 ECU 编辑器的这个对话框中，可以显示和修改 J1939 ECU 的一般参数。 一般的 首选地址 ECU 的地址。如果网络中存在多个具有相同地址的 ECU，则所有受影响的 ECU 都会获得一个新地址。要求是 ECU 允许地址更改（ 任意地址能力 ）。 本地设备 ：您可以配置任意数量的本地 ECU。那么每个本地 ECU 都是 J1939 网络中自己的 ECU 实例。对于本地设备，额外的 接收信号 (P2P) 提供对话框来配置接收到的信号。 ECU 名称 名称（64 位）：16# 包含有关后续参数的完整信息的十六进制 64 位代码。每次修改此代码时，相应的参数也会被修改。另一个方向也是如此。 任意地址能力 ：当 ECU 检测到地址冲突时，它会独立尝试设置另一个地址。 产业集团 根据 SAE J1939 定义的行业组列表。 车辆系统实例 该参数取决于 车载系统 . 4 位值为每个实例分配一个数字 车载系统 . 车载系统 该值在 SAE J1939 标准中定义。 预订的 始终停用并为未来的 SAE 定义保留 功能 该参数由 SAE 定义和分配。值范围为 0–255，但并非所有值都已分配。 大于或等于 127 的值的解释取决于 行业 选择。例如，值“133”表示“农林设备”行业中的“产品流”。如果选择“建筑设备” 行业 ，则相同的值表示“土地平整系统显示”。 如果该值小于 128 (0–127)，则不依赖于其他参数。 函数实例 该参数与 功能 场地。一个 J1939 网络可以由多个具有相同功能的 ECU 组成 功能 . 5位 函数实例 为每个实例分配一个编号 功能 ，其中 0 分配给第一个实例。 ECU 实例 一个 J1939 网络可以包含多个具有相同任务的 ECU。例如，车辆可以有两个相同的 ECU，其中一个测量车速，另一个测量拖车速度。 制造商代码 11 位制造商代码由 SAE 分配，表示制造 ECU 的公司。此代码在 SAE J1939 文档中定义。 身份号码 21 位标识号由制造商分配，应用于确保产品线中的唯一名称。制造商还可以在标识号中添加更多信息，例如序列号和制造日期。 通讯看门狗 启用通信看门狗 ：堆栈检查ECU是否在指定的范围内传输数据 看门狗时间 .如果这没有发生，则设备被归类为“不可用”并在设备树中以红色突出显示。 " }, 
{ "title" : "选项卡：J1939-ECU – TX 信号 ", 
"url" : "_can_edt_j1939_ecu_txsignals.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 选项卡：J1939-ECU – TX 信号 ", 
"snippet" : "此对话框显示传输到所有其他 ECU（广播）或特定 ECU (P2P) 的参数组。在此对话框中，您可以激活和停用各个组并修改其参数。您还可以将新组或信号添加到列表中。 启用 ：传输参数组。 ：对于本地设备，该参数组不被传输。对于远程设备，PLC 不处理该参数组。 类型 播送 ：参数组传输到所有 ECU。 点对点 P2P ：参数组被传输到特定的 ECU。 添加 PG 打开 添加参数组 对话。 添加信号 打开 添加信号 对话框。仅当您选择了参数组或参数组的信号时，此按钮才可用。 数据布局编辑器 打开 数据布局编辑器 对话。 仅当您选择了参数组或参数组的信号时，此按钮才可用。...", 
"body" : "此对话框显示传输到所有其他 ECU（广播）或特定 ECU (P2P) 的参数组。在此对话框中，您可以激活和停用各个组并修改其参数。您还可以将新组或信号添加到列表中。 启用 ：传输参数组。 ：对于本地设备，该参数组不被传输。对于远程设备，PLC 不处理该参数组。 类型 播送 ：参数组传输到所有 ECU。 点对点 P2P ：参数组被传输到特定的 ECU。 添加 PG 打开 添加参数组 对话。 添加信号 打开 添加信号 对话框。仅当您选择了参数组或参数组的信号时，此按钮才可用。 数据布局编辑器 打开 数据布局编辑器 对话。 仅当您选择了参数组或参数组的信号时，此按钮才可用。 " }, 
{ "title" : "参数组属性 ", 
"url" : "_can_edt_j1939_ecu_txsignals.html#UUID-832b5cd9-77fe-99c3-7d67-76b34162616a_id_aeff9131e30ef712c0a8640e01d79012-id-fb72162c8c56b62ec0a8640e009f9f83", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 选项卡：J1939-ECU – TX 信号 \/ 参数组属性 ", 
"snippet" : "一般的 PGN 这 “参数组编号” 是用于寻址参数组的唯一编号。 名称 参数组名称 描述 参数组说明 长度 消息数据的长度（0..1785字节） 由于数组的最大长度为 8 个字节，因此超过 8 个字节的消息将作为多包传输。 传输设置 这些设置仅针对本地设备的 TX 参数组提供。 优先事项 参数组的优先级（0..7） 优先级 0 最高，优先级 7 最低。 目标地址 只有 P2P 参数组需要目标地址。 传输方式 确定传输参数组的时间（对于本地设备）。 模式改变 : 信号值变化时发送 PG。 循环的 ： PG 在指定数量的 PLC 循环后传输（参见循环时间系数）。 根据要求 : PG 根据其他设备的...", 
"body" : "一般的 PGN 这 “参数组编号” 是用于寻址参数组的唯一编号。 名称 参数组名称 描述 参数组说明 长度 消息数据的长度（0..1785字节） 由于数组的最大长度为 8 个字节，因此超过 8 个字节的消息将作为多包传输。 传输设置 这些设置仅针对本地设备的 TX 参数组提供。 优先事项 参数组的优先级（0..7） 优先级 0 最高，优先级 7 最低。 目标地址 只有 P2P 参数组需要目标地址。 传输方式 确定传输参数组的时间（对于本地设备）。 模式改变 : 信号值变化时发送 PG。 循环的 ： PG 在指定数量的 PLC 循环后传输（参见循环时间系数）。 根据要求 : PG 根据其他设备的请求传输。 应用程序控制 : 应用程序触发时发送 PG。 周期时间因素 传输参数组之前的 PLC 循环数。 仅适用于循环传输。 " }, 
{ "title" : "信号参数 ", 
"url" : "_can_edt_j1939_ecu_txsignals.html#UUID-832b5cd9-77fe-99c3-7d67-76b34162616a_id_aeff9131e30ef712c0a8640e01d79012-id-17cc94463bec8cc3c0a8640e0098a621", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 选项卡：J1939-ECU – TX 信号 \/ 信号参数 ", 
"snippet" : "一般的 SPN 可疑参数编号 SAE 为参数组中的特定参数分配的编号之一。 名称 参数名称 描述 参数说明 长度（位） 信号的长度（以位为单位：1..14280） 字节位置 (0..1784) 参数组中的起始字节（0..1784） 位位置 (0..7) 起始字节的位位置（0..7） 转换 转换 TRUE ：该值是通过缩放和偏移计算得出的。 RAW 数据类型 原始数据的格式： 未签名 \/ 签 \/ 漂浮 \/ 双倍的 字节顺序 小端序 或者 大端字节序 原始信号的 缩放 因子（对于 转换 = TRUE ） 抵消 偏移（用于 转换 = TRUE ） 最小值 转换后信号的预期最小值（仅供参考） 最大值 ...", 
"body" : "一般的 SPN 可疑参数编号 SAE 为参数组中的特定参数分配的编号之一。 名称 参数名称 描述 参数说明 长度（位） 信号的长度（以位为单位：1..14280） 字节位置 (0..1784) 参数组中的起始字节（0..1784） 位位置 (0..7) 起始字节的位位置（0..7） 转换 转换 TRUE ：该值是通过缩放和偏移计算得出的。 RAW 数据类型 原始数据的格式： 未签名 \/ 签 \/ 漂浮 \/ 双倍的 字节顺序 小端序 或者 大端字节序 原始信号的 缩放 因子（对于 转换 = TRUE ） 抵消 偏移（用于 转换 = TRUE ） 最小值 转换后信号的预期最小值（仅供参考） 最大值 转换后信号的预期最大值（仅供参考） 单元 转换信号的单位 ICE 数据类型 I\/O 通道的结果数据类型 " }, 
{ "title" : "选项卡：J1939-ECU – P2P RX 信号 ", 
"url" : "_can_edt_j1939_ecu_rxsignals.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 选项卡：J1939-ECU – P2P RX 信号 ", 
"snippet" : "此对话框仅适用于本地 ECU。它显示了应该由其他 ECU 接收的所有 PG（参数组）。在此对话框中，可以激活和禁用各个组以及修改它们的参数。新的组或信号也可以添加到列表中。 该对话框的命令和参数同上 发射信号 标签。...", 
"body" : "此对话框仅适用于本地 ECU。它显示了应该由其他 ECU 接收的所有 PG（参数组）。在此对话框中，可以激活和禁用各个组以及修改它们的参数。新的组或信号也可以添加到列表中。 该对话框的命令和参数同上 发射信号 标签。 " }, 
{ "title" : "对话框：添加参数组 ", 
"url" : "_can_dlg_j1939_add_parameter_group.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 对话框：添加参数组 ", 
"snippet" : "在 CODESYS 对于 3.5 SP17 及更高版本，J1939 配置器不再提供参数组\/信号数据库。不再支持旧数据库。 但是，您可以在 J1939 Manager 中后安装 DBC 数据库。可以从 CSS Electronics 购买数据库： https:\/\/www.csselectronics.com\/screen\/product\/j1939-dbc-file-pgn-spn 如果不安装数据库，也可以手动配置参数组和信号 用户自定义 标签。 数据库 CODESYS 在此选项卡上显示数据库的所有参数。 寻找 过滤PGN列表的字符串 重启 重置过滤器以显示完整列表 筛选 仅显示所选类型的 PG...", 
"body" : "在 CODESYS 对于 3.5 SP17 及更高版本，J1939 配置器不再提供参数组\/信号数据库。不再支持旧数据库。 但是，您可以在 J1939 Manager 中后安装 DBC 数据库。可以从 CSS Electronics 购买数据库： https:\/\/www.csselectronics.com\/screen\/product\/j1939-dbc-file-pgn-spn 如果不安装数据库，也可以手动配置参数组和信号 用户自定义 标签。 数据库 CODESYS 在此选项卡上显示数据库的所有参数。 寻找 过滤PGN列表的字符串 重启 重置过滤器以显示完整列表 筛选 仅显示所选类型的 PG。 添加 PG 将选定的参数组添加到 TX 信号列表。可以选择多个参数组。 用户自定义 在此选项卡上，您可以创建用户定义的参数组。 PGN（18 位） 根据四个后续参数计算的 PG (0...262143) 的唯一编号。您可以直接在字段中输入此值。 PDU 特定（位 0–7） 价值的评估取决于价值 PDU格式 . 如果 PDU格式 介于 0 和 239 之间，则消息是可寻址的，并且该字段包含目标地址。 如果 PDU格式 介于 240 和 255 之间，则该消息是广播消息，并且该字段包含组扩展。 PDU 格式（位 8-15） 协议数据单元 格式决定了消息是可以使用目标地址传输还是始终作为广播消息传输。 数据页（位 16） 选择 PDU 格式的页面（目前总是 0 ）。 扩展数据页（位 17） 未使用：用于未来扩展。 名称 新参数组的名称。 长度（字节） 参数组的长度（以字节为单位） 优先事项 参数组的优先级 (0..7)。优先级 0 最高，7 最低。 描述 参数组说明 " }, 
{ "title" : "对话框：添加信号 ", 
"url" : "_can_dlg_j1939_add_signal.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 对话框：添加信号 ", 
"snippet" : "在 CODESYS 对于 3.5 SP17 及更高版本，J1939 配置器不再提供参数组\/信号数据库。不再支持旧数据库。 但是，您可以在 J1939 Manager 中后安装 DBC 数据库。可以从 CSS Electronics 购买数据库： https:\/\/www.csselectronics.com\/screen\/product\/j1939-dbc-file-pgn-spn 如果不安装数据库，也可以手动配置参数组和信号 用户自定义 标签。 数据库 信号的添加方式与参数组的添加方式相同。 用户自定义 SPN 可疑参数编号 名称 新信号的名称 长度（位） 信号长度 描述 新信号说明 转换 :...", 
"body" : "在 CODESYS 对于 3.5 SP17 及更高版本，J1939 配置器不再提供参数组\/信号数据库。不再支持旧数据库。 但是，您可以在 J1939 Manager 中后安装 DBC 数据库。可以从 CSS Electronics 购买数据库： https:\/\/www.csselectronics.com\/screen\/product\/j1939-dbc-file-pgn-spn 如果不安装数据库，也可以手动配置参数组和信号 用户自定义 标签。 数据库 信号的添加方式与参数组的添加方式相同。 用户自定义 SPN 可疑参数编号 名称 新信号的名称 长度（位） 信号长度 描述 新信号说明 转换 : 值被缩放。 单元 信号值的单位（仅供参考）。 原始数据类型 无符号\/有符号\/浮点数\/双精度 字节顺序 小端或大端 缩放 因子（如果 转换 已激活） 抵消 偏移量（如果 转换 已激活） " }, 
{ "title" : "对话框：数据布局编辑器 ", 
"url" : "_can_dlg_j1939_-data_layout_editor.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 配置 \/ 对话框：数据布局编辑器 ", 
"snippet" : "参数组数据布局的图形表示 对于每个信号，数据区域的位置以不同的颜色图形显示。 重叠区域以阴影显示，以便于识别。 图形表示应该可以帮助您概览数据的布局。 您可以移动数据范围的起点和终点来改变信号的长度或参数组内的信号位置。 由于编辑器不是模态的，因此您可以更改信号配置（ 选项卡：J1939-ECU – TX 信号) 而无需关闭编辑器。 为了分析和解释 CAN 消息的数据内容，您还可以在在线模式下以只读方式打开编辑器。 在更改信号配置时，请保持数据布局编辑器打开。更改会立即应用并显示。 编辑器中的图形符号 箭 当将光标指向箭头时，光标的显示会发生变化，并且可以移动数据范围的末尾。 酒吧 当将光标指...", 
"body" : "参数组数据布局的图形表示 对于每个信号，数据区域的位置以不同的颜色图形显示。 重叠区域以阴影显示，以便于识别。 图形表示应该可以帮助您概览数据的布局。 您可以移动数据范围的起点和终点来改变信号的长度或参数组内的信号位置。 由于编辑器不是模态的，因此您可以更改信号配置（ 选项卡：J1939-ECU – TX 信号) 而无需关闭编辑器。 为了分析和解释 CAN 消息的数据内容，您还可以在在线模式下以只读方式打开编辑器。 在更改信号配置时，请保持数据布局编辑器打开。更改会立即应用并显示。 编辑器中的图形符号 箭 当将光标指向箭头时，光标的显示会发生变化，并且可以移动数据范围的末尾。 酒吧 当将光标指向该栏时，光标的显示会发生变化，并且您可以移动数据范围的起点。 例子 " }, 
{ "title" : "职能 ", 
"url" : "_can_f_j1939_functions.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "重新配置 – J1939 ", 
"url" : "_can_f_j1939_functions.html#UUID-ba6489a4-02dc-4a9c-9fe6-7e5613c83626_section-idm4567920323704032571436888426", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 职能 \/ 重新配置 – J1939 ", 
"snippet" : "使用“重新配置”功能，您可以在应用程序运行时动态调整最初下载到控制器的 J1939 配置。 随着 DED.Reconfigure 功能块，在启用通用设备诊断时可用（ PLC 设置： )，您可以在运行时执行以下操作。 单个设备的激活和停用 启用和停用整个总线链 有关 CANbus 级别重新配置的更多信息，请参见“重新配置 – CANbus”一章。...", 
"body" : "使用“重新配置”功能，您可以在应用程序运行时动态调整最初下载到控制器的 J1939 配置。 随着 DED.Reconfigure 功能块，在启用通用设备诊断时可用（ PLC 设置： )，您可以在运行时执行以下操作。 单个设备的激活和停用 启用和停用整个总线链 有关 CANbus 级别重新配置的更多信息，请参见“重新配置 – CANbus”一章。 " }, 
{ "title" : "总线循环任务 ", 
"url" : "_can_f_j1939_functions.html#UUID-ba6489a4-02dc-4a9c-9fe6-7e5613c83626_section-idm43257143978048", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 职能 \/ 总线循环任务 ", 
"snippet" : "(1) 接收单包裹 PG (2) IEC 任务 (3) 将输出写入输出缓冲区 (4) 接收多包 PG，发送 PG 有关更多信息，请参阅： 任务配置...", 
"body" : "(1) 接收单包裹 PG (2) IEC 任务 (3) 将输出写入输出缓冲区 (4) 接收多包 PG，发送 PG 有关更多信息，请参阅： 任务配置 " }, 
{ "title" : "命令：导入 DBC 文件 ", 
"url" : "_can_f_j1939_functions.html#UUID-ba6489a4-02dc-4a9c-9fe6-7e5613c83626_section-idm4613673164707232571437968327", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 职能 \/ 命令：导入 DBC 文件 ", 
"snippet" : "功能 ：该命令导入 DBC 文件并插入 J1939 管理器下方文件中描述的 ECU 设备。然后文件的内容显示在 DBC 内容选择 对话框，帮助您选择要导入的内容。 称呼 ：设备树中 J1939 管理器（设备对象）的上下文菜单 要求 : DBC 文件存在。...", 
"body" : "功能 ：该命令导入 DBC 文件并插入 J1939 管理器下方文件中描述的 ECU 设备。然后文件的内容显示在 DBC 内容选择 对话框，帮助您选择要导入的内容。 称呼 ：设备树中 J1939 管理器（设备对象）的上下文菜单 要求 : DBC 文件存在。 " }, 
{ "title" : "DBC 文件的通信描述 ", 
"url" : "_can_f_j1939_functions.html#UUID-ba6489a4-02dc-4a9c-9fe6-7e5613c83626_section-idm43257144225922", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 职能 \/ 命令：导入 DBC 文件 \/ DBC 文件的通信描述 ", 
"snippet" : "DBC 是由 Vector Informatik GmbH 开发的专有数据格式。数据格式映射 J1939 通信关系，以便导入 CODESYS ....", 
"body" : "DBC 是由 Vector Informatik GmbH 开发的专有数据格式。数据格式映射 J1939 通信关系，以便导入 CODESYS . " }, 
{ "title" : "对话框：DBC 内容选择 ", 
"url" : "_can_f_j1939_functions.html#UUID-ba6489a4-02dc-4a9c-9fe6-7e5613c83626_section-idm43257144277062", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 职能 \/ 命令：导入 DBC 文件 \/ 对话框：DBC 内容选择 ", 
"snippet" : "进口 : ECU是进口的。 名称 ECU 名称（来自 DBC 文件） 描述 ECU 描述（来自 DBC 文件） 本地ECU : ECU 作为本地 ECU 导入。 : ECU 作为远程 ECU 导入。 启用信号转换 ：对ECU的所有信号启用信号转换。 行 在 J1939 管理器下方插入选定的 ECU。 注意：设备树中的 ECU 名称与 DBC 文件中的名称相对应。 但是，现有的 ECU 不会被覆盖。要导入的 ECU 具有唯一的名称。 例子...", 
"body" : "进口 : ECU是进口的。 名称 ECU 名称（来自 DBC 文件） 描述 ECU 描述（来自 DBC 文件） 本地ECU : ECU 作为本地 ECU 导入。 : ECU 作为远程 ECU 导入。 启用信号转换 ：对ECU的所有信号启用信号转换。 行 在 J1939 管理器下方插入选定的 ECU。 注意：设备树中的 ECU 名称与 DBC 文件中的名称相对应。 但是，现有的 ECU 不会被覆盖。要导入的 ECU 具有唯一的名称。 例子 " }, 
{ "title" : "诊断 ", 
"url" : "_can_f_j1939_diagnosis.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 ", 
"snippet" : "控制设备可以独立发送诊断消息 (DM)。最重要的诊断信息是 DM1 和 DM2。 DM1 包含当前激活的故障诊断代码 (DTC) 列表。 DM2 包含过去不再有效的故障诊断代码 (DTC) 列表。 DTC 描述了系统中的缺陷属性。首先，代码描述了一个处于异常状态的可疑参数号（SPN）。 DTC 是统一的结构，由以下元素组成： 可疑参数编号 (SPN) 故障模式标识符 (FMI) 出现计数器 (OC) SPN 转换方法 (CM)...", 
"body" : "控制设备可以独立发送诊断消息 (DM)。最重要的诊断信息是 DM1 和 DM2。 DM1 包含当前激活的故障诊断代码 (DTC) 列表。 DM2 包含过去不再有效的故障诊断代码 (DTC) 列表。 DTC 描述了系统中的缺陷属性。首先，代码描述了一个处于异常状态的可疑参数号（SPN）。 DTC 是统一的结构，由以下元素组成： 可疑参数编号 (SPN) 故障模式标识符 (FMI) 出现计数器 (OC) SPN 转换方法 (CM) " }, 
{ "title" : "应用中的诊断 ", 
"url" : "_can_f_j1939_diagnosis_application.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 应用中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "ECU 状态 ", 
"url" : "_can_f_j1939_diagnosis_application.html#UUID-0105525e-766a-4ebb-1bf9-ffcc72c729e2_section-idm4608504434480032570177847946", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 应用中的诊断 \/ ECU 状态 ", 
"snippet" : "可以通过三种不同的方式在应用程序中询问设备的 ECU 状态： <name in device tree>.State 财产 （ IoDrvJ1939 图书馆） <name in device tree>.GetDeviceState 方法 （ CAA 设备诊断 图书馆） 该方法不返回特定的 J1939 状态，而是返回设备是否正在运行的信息。之间的映射表 ECUSTATE 和 DEVICE_STATE 可以在图书馆文档中找到 IoDrvJ1939 . 对于远程 ECU： 因为J1939协议没有定义监控机制，所以默认不显示ECU故障。但是，您可以选择 启用通信看门狗 在 J1939 ECU 配置器...", 
"body" : "可以通过三种不同的方式在应用程序中询问设备的 ECU 状态： <name in device tree>.State 财产 （ IoDrvJ1939 图书馆） <name in device tree>.GetDeviceState 方法 （ CAA 设备诊断 图书馆） 该方法不返回特定的 J1939 状态，而是返回设备是否正在运行的信息。之间的映射表 ECUSTATE 和 DEVICE_STATE 可以在图书馆文档中找到 IoDrvJ1939 . 对于远程 ECU： 因为J1939协议没有定义监控机制，所以默认不显示ECU故障。但是，您可以选择 启用通信看门狗 在 J1939 ECU 配置器中并设置适当的 看门狗时间 .如果在此期间没有接收到设备的参数组（必须在配置器中定义），则认为 ECU 不存在，并通过 state 属性相应地指示。然而，为此，必须在配置器中定义一个参数组。在设备手册中，您可以阅读设备发送参数组以设置正确时间的间隔。示例：如果 ECU 在 1s 间隔内发送 PG，则 看门狗时间 可设置为 > 1s。 " }, 
{ "title" : "诊断信息 DM1 和 DM2 ", 
"url" : "_can_f_j1939_diagnosis_application.html#UUID-0105525e-766a-4ebb-1bf9-ffcc72c729e2_section-idm4608504576603232570180049153", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 应用中的诊断 \/ 诊断信息 DM1 和 DM2 ", 
"snippet" : "对于 DM1 和 DM2 消息，用于接收（在远程 ECU 的情况下）和发送（在本地 ECU 的情况下）的功能块在 IoDrvJ1939 图书馆。 DM1_Read DM2_Read DM1_Write DM2_Write...", 
"body" : "对于 DM1 和 DM2 消息，用于接收（在远程 ECU 的情况下）和发送（在本地 ECU 的情况下）的功能块在 IoDrvJ1939 图书馆。 DM1_Read DM2_Read DM1_Write DM2_Write " }, 
{ "title" : "观察单个参数组 ", 
"url" : "_can_f_j1939_diagnosis_application.html#UUID-0105525e-766a-4ebb-1bf9-ffcc72c729e2_section-idm4613673461222432570181431693", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 应用中的诊断 \/ 观察单个参数组 ", 
"snippet" : "由于全局通信看门狗监控设备的所有参数组，因此可能无法检测到单个参数组的故障。在这些情况下，观察单个参数组是有意义的。带功能块 接收看门狗 ，您可以检查是否定期收到参数组。功能块需要功能块的实例 接收参数组 作为将要观看的各个PGN传送到的输入。 功能块的输出 ReceiveWatchdog 显示当前周期是否接收到参数组，是否存在超时。...", 
"body" : "由于全局通信看门狗监控设备的所有参数组，因此可能无法检测到单个参数组的故障。在这些情况下，观察单个参数组是有意义的。带功能块 接收看门狗 ，您可以检查是否定期收到参数组。功能块需要功能块的实例 接收参数组 作为将要观看的各个PGN传送到的输入。 功能块的输出 ReceiveWatchdog 显示当前周期是否接收到参数组，是否存在超时。 " }, 
{ "title" : "用户界面中的诊断 ", 
"url" : "_can_f_j1939_diagnosis_ui.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 用户界面中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设备树 ", 
"url" : "_can_f_j1939_diagnosis_ui.html#UUID-5c014b5a-2657-98e3-48ae-3c74164d75e3_section-idm43257017146608", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 用户界面中的诊断 \/ 设备树 ", 
"snippet" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色三角形）：硬错误，例如不正确\/丢失的 ECU 或连接中断。 注意：该标志仅在活动通信看门狗的情况下设置。 诊断标志（红色感叹号）：表示已收到 DM1。有关详细信息，请参阅状态页面。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。...", 
"body" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色三角形）：硬错误，例如不正确\/丢失的 ECU 或连接中断。 注意：该标志仅在活动通信看门狗的情况下设置。 诊断标志（红色感叹号）：表示已收到 DM1。有关详细信息，请参阅状态页面。 错误清除标志（灰色感叹号）：表示先前未决的错误已被纠正。 " }, 
{ "title" : "地位 ", 
"url" : "_can_f_j1939_diagnosis_ui.html#UUID-5c014b5a-2657-98e3-48ae-3c74164d75e3_section-idm43257017308842", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 用户界面中的诊断 \/ 地位 ", 
"snippet" : "状态页面显示 J1939 状态以及有关最后收到的 DM1 消息的信息。...", 
"body" : "状态页面显示 J1939 状态以及有关最后收到的 DM1 消息的信息。 " }, 
{ "title" : "记录器 ", 
"url" : "_can_f_j1939_diagnosis_ui.html#UUID-5c014b5a-2657-98e3-48ae-3c74164d75e3_section-idm43257017431294", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 用户界面中的诊断 \/ 记录器 ", 
"snippet" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。 这仅显示由相应设备创建的条目，例如 J1939 状态的更改、DM1 消息和监控错误。...", 
"body" : "过滤后的视图 PLC记录仪 显示在控制器级别和设备级别。 这仅显示由相应设备创建的条目，例如 J1939 状态的更改、DM1 消息和监控错误。 " }, 
{ "title" : "故障排除 ", 
"url" : "_can_j1939_trouble_shooting.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 故障排除 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "J1939 ", 
"url" : "_can_j1939_trouble_shooting.html#UUID-ae5b818f-fce3-e0a5-fe01-6ae9a1bdabee_id_bae00ea44c035c0a864637aa14c86-id-1d7f4eb2c6330978c0a8646377a18168", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 诊断 \/ 故障排除 \/ J1939 ", 
"snippet" : "问题 可能的解决方案 CAN 总线节点为红色或带有红色感叹号。 请参阅 CAN 总线的一般故障排除。 J1939 管理器为红色或带有红色感叹号。 检查 J1939 Manager 的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 您没有许可证或演示许可证已过期。 可用内存太少。 ECU 有一个红色感叹号。 设备报告诊断代码 (DM1)。 检查 J1939 Manager 的状态页面和记录器页面。您将在此处找到更多信息。 奴隶有一个灰色的感叹号。 过去发生了一个错误，在此期间已更正。您可以检查这是哪个错误的记录器页面。您可以通过单击确认灰色感叹号 确认 状态页面上的按钮或设备上下文...", 
"body" : "问题 可能的解决方案 CAN 总线节点为红色或带有红色感叹号。 请参阅 CAN 总线的一般故障排除。 J1939 管理器为红色或带有红色感叹号。 检查 J1939 Manager 的状态页面和记录器页面。您将在此处找到更多信息。 可能的原因： 您没有许可证或演示许可证已过期。 可用内存太少。 ECU 有一个红色感叹号。 设备报告诊断代码 (DM1)。 检查 J1939 Manager 的状态页面和记录器页面。您将在此处找到更多信息。 奴隶有一个灰色的感叹号。 过去发生了一个错误，在此期间已更正。您可以检查这是哪个错误的记录器页面。您可以通过单击确认灰色感叹号 确认 状态页面上的按钮或设备上下文菜单中的命令。 我的 ECU 的输入和输出不起作用。 可能的原因： ECU 的地址不正确或配置了不正确的参数组。 ECU 偶尔退出（变为红色，然后再次变为绿色）。 可能的原因： 这 通讯看门狗 设置不合适。 在任务监视器中，检查总线循环任务的最小和最大时间。 在应用程序中，搜索产生这些循环时间异常值的应用程序代码：优化代码或将其移至另一个任务。 总线循环任务中存在循环时间异常值。 句柄泄漏是由错误的驱动程序或 CL2 层的错误使用引起的。 存在硬件错误。 请参阅有关对基于 CAN 的现场总线进行故障排除的章节。 " }, 
{ "title" : "库：J1939 ", 
"url" : "_can_j1939_libraries.html", 
"breadcrumbs" : "CODESYS CANbus \/ J1939 \/ 库：J1939 ", 
"snippet" : "IoDrvJ1939...", 
"body" : "IoDrvJ1939 " }
]
$(document).trigger('search.ready');
});