$(document).ready(function () {indexDict['es'] = [{ "title" : "CODESYS Ethernet Adapter ", 
"url" : "_enad_start_page.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ CODESYS Ethernet Adapter ", 
"snippet" : "Consulte la descripción general para obtener información sobre las siguientes pestañas del editor de dispositivos. Pestaña '<nombre del dispositivo> Asignación de E\/S' Pestaña '<nombre del dispositivo> Objetos IEC' Pestaña '<nombre del dispositivo> Parámetros' Pestaña '<nombre del dispositivo> Estad...", 
"body" : "Consulte la descripción general para obtener información sobre las siguientes pestañas del editor de dispositivos. Pestaña '<nombre del dispositivo> Asignación de E\/S' Pestaña '<nombre del dispositivo> Objetos IEC' Pestaña '<nombre del dispositivo> Parámetros' Pestaña '<nombre del dispositivo> Estado' Pestaña '<nombre del dispositivo> Información' Una página de ayuda separada adicional para el editor de dispositivos relevante está disponible solo en el caso de características especiales. Si no se muestra la pestaña \"<nombre del dispositivo> Parámetros\", seleccione el Mostrar editores de configuración de dispositivos genéricos opción en el CODESYS opciones, en el editor de dispositivos categoría. Para obtener más información general sobre el soporte de bus de campo en CODESYS , ver: Soporte de bus de campo El CODESYS El adaptador Ethernet se utiliza como nodo principal para dispositivos que utilizan protocolos basados en Ethernet. CODESYS actualmente es compatible con EtherNet\/IP, Modbus y PROFINET IO. Primero, inserta el adaptador Ethernet debajo del controlador. Luego agrega el bus de campo basado en Ethernet debajo del adaptador. " }, 
{ "title" : "Pestaña: EtherNet Adapter – Generalidades ", 
"url" : "_enad_edt_general.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Pestaña: EtherNet Adapter – Generalidades ", 
"snippet" : "Objeto: Adaptador Ethernet Esta pestaña define las interfaces de red. Interfaz de red : abre el Adaptadores de red diálogo. Aquí se pueden seleccionar los adaptadores Ethernet, que están disponibles en el sistema de destino establecido. dirección IP Máscara de subred Puerta de enlace predeterminada ...", 
"body" : "Objeto: Adaptador Ethernet Esta pestaña define las interfaces de red. Interfaz de red : abre el Adaptadores de red diálogo. Aquí se pueden seleccionar los adaptadores Ethernet, que están disponibles en el sistema de destino establecido. dirección IP Máscara de subred Puerta de enlace predeterminada Configuración de la interfaz de red seleccionada Ajustar la configuración del sistema operativo Tienes que confirmar esta opción de nuevo. Nota: Los valores anteriores sobrescribirán la configuración del sistema de destino. La configuración IP del sistema operativo se puede cambiar mediante el CODESYS sistema de tiempo de ejecución solo si está permitido en el archivo de configuración ( *.cfg ) del tiempo de ejecución. Para ello se requieren las siguientes entradas: [SysSocket] Adapter.0.Name=\"<adapter name>\" (ejemplo: \"LAN connection 4\" ) Adapter.0.EnableSetIpAndMask=1 Configuración de PLC redundante (PLC 2) Cuando se usa un par de controladores CODESYS redundantes, esta configuración se usa en el \"PLC de respaldo\" ( PLC ID = 2 ) para el adaptador de red. Interfaz de red : abre el Adaptadores de red diálogo. Aquí se pueden seleccionar los adaptadores Ethernet, que están disponibles en el sistema de destino establecido. dirección IP Máscara de subred Puerta de enlace predeterminada Configuración de la interfaz de red seleccionada Los ajustes para el PLC redundante solo están disponibles cuando ha insertado el Redundancy Configuration objeto debajo de su aplicación. " }, 
{ "title" : "Diálogo: Adaptadores de red ", 
"url" : "_enad_edt_general.html#UUID-68dc7536-40d9-f126-1da8-b5aefc635b70_id_eb69772dd959aeac0a8640e01875adb_id_98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Pestaña: EtherNet Adapter – Generalidades \/ Diálogo: Adaptadores de red ", 
"snippet" : "Interfaces Muestra una descripción general de todos los adaptadores de red disponibles. dirección IP Máscara de subred Puerta de enlace predeterminada Estos parámetros se toman del sistema operativo y no se pueden modificar. Dirección MAC Dirección MAC del adaptador Ethernet...", 
"body" : "Interfaces Muestra una descripción general de todos los adaptadores de red disponibles. dirección IP Máscara de subred Puerta de enlace predeterminada Estos parámetros se toman del sistema operativo y no se pueden modificar. Dirección MAC Dirección MAC del adaptador Ethernet " }
]
$(document).trigger('search.ready');
});