$(document).ready(function () {indexDict['es'] = [{ "title" : "CODESYS POU Visu Generator ", 
"url" : "_pvg_start_page.html", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator ", 
"snippet" : "CODESYS POU Visu Generator es un complemento para CODESYS Development System . Con este complemento, puede generar visualizaciones basadas en POU programadas en SFC o LD2. Puedes usar el CODESYS Installer para instalar y actualizar el CODESYS POU Visu Generator complemento....", 
"body" : "CODESYS POU Visu Generator es un complemento para CODESYS Development System . Con este complemento, puede generar visualizaciones basadas en POU programadas en SFC o LD2. Puedes usar el CODESYS Installer para instalar y actualizar el CODESYS POU Visu Generator complemento. " }, 
{ "title" : "Creación de una visualización para una POU en SFC o LD2 ", 
"url" : "_pvg_start_page.html#UUID-22a83d9d-042d-8266-f215-334a372e3950", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator \/ Creación de una visualización para una POU en SFC o LD2 ", 
"snippet" : "Para POU ( PROGRAM o FUNCTION_BLOCK ) programado en el Gráfico de funciones secuenciales (SFC) o Diagrama de escalera (LD2) lenguaje de implementación, puede crear un objeto de visualización que muestre un diagrama de bloques adecuado. Si desea tener este tipo de visualización, entonces el Genere vi...", 
"body" : "Para POU ( PROGRAM o FUNCTION_BLOCK ) programado en el Gráfico de funciones secuenciales (SFC) o Diagrama de escalera (LD2) lenguaje de implementación, puede crear un objeto de visualización que muestre un diagrama de bloques adecuado. Si desea tener este tipo de visualización, entonces el Genere visualizaciones SFC\/LD El comando puede ayudarlo con esto. " }, 
{ "title" : "Generar una visualización a partir de una POU SFC ", 
"url" : "_pvg_start_page.html#UUID-d0409bfc-911d-4924-b44d-a70354f5bf71", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator \/ Creación de una visualización para una POU en SFC o LD2 \/ Generar una visualización a partir de una POU SFC ", 
"snippet" : "Solo es posible con objetos LD2 Solo puede crear visualizaciones para las POU en Escalera (LD2) lenguaje de implementación. Para visualizar una POU en LD , primero conviértalo a LD2 usando el Convertir en nueva escalera comando. Después de eso, puede generar una visualización de LD2 a partir de esto...", 
"body" : "Solo es posible con objetos LD2 Solo puede crear visualizaciones para las POU en Escalera (LD2) lenguaje de implementación. Para visualizar una POU en LD , primero conviértalo a LD2 usando el Convertir en nueva escalera comando. Después de eso, puede generar una visualización de LD2 a partir de esto Para obtener más información, consulte: Comando: Convertir en un nuevo plan de contactos " }, 
{ "title" : "Generar una visualización a partir de una POU SFC ", 
"url" : "_pvg_start_page.html#UUID-dec8ea49-3386-d969-6220-015bdafe3329", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator \/ Creación de una visualización para una POU en SFC o LD2 \/ Generar una visualización a partir de una POU SFC ", 
"snippet" : "Configure el SFCCurrentStep marca para cada objeto SFC en su cuadro de diálogo de propiedades en Configuración de SFC pestaña. De lo contrario, se producirán errores de compilación. Si el código SFC contiene macros, se genera una visualización independiente para cada macro. Esta visualización se pue...", 
"body" : "Configure el SFCCurrentStep marca para cada objeto SFC en su cuadro de diálogo de propiedades en Configuración de SFC pestaña. De lo contrario, se producirán errores de compilación. Si el código SFC contiene macros, se genera una visualización independiente para cada macro. Esta visualización se puede seleccionar haciendo clic en ella. Ejemplo Visualización SFC generada Para obtener más información, consulte: Cuadro de diálogo: Propiedades: configuración de AS " }, 
{ "title" : "Referencia: Command ", 
"url" : "_pvg_ref_command.html", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ Referencia: Command ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Comando: Generar visualizaciones SFC\/LD ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ Referencia: Command \/ Comando: Generar visualizaciones SFC\/LD ", 
"snippet" : "Generar visualizaciones SFC\/LD Este comando está disponible cuando ha instalado el CODESYS POU Visu Generator complemento. Símbolo: Función : Si su aplicación contiene POU (PRG) o bloques de funciones (FB) en el lenguaje de implementación Gráfico de funciones secuenciales (SFC) o Escalera (LD2) y, a...", 
"body" : "Generar visualizaciones SFC\/LD Este comando está disponible cuando ha instalado el CODESYS POU Visu Generator complemento. Símbolo: Función : Si su aplicación contiene POU (PRG) o bloques de funciones (FB) en el lenguaje de implementación Gráfico de funciones secuenciales (SFC) o Escalera (LD2) y, a continuación, se generan las visualizaciones correspondientes. Llamar : Proyecto menú Requisito : El CODESYS POU Visu Generator el paquete está instalado. Tras ejecutar el comando, los objetos generados se almacenan en POU vista. Ahora puede usar estos objetos como visualizaciones de plantilla e incrustarlos en sus propias visualizaciones mediante Marco elemento o un Pestañas elemento. La visualización recién generada puede ejecutarse en paralelo a la aplicación por separado sin un sistema de desarrollo. Visualiza el estado en línea de la aplicación y muestra el paso actual del programa resaltado en color. " }, 
{ "title" : "Resultado con Ladder (LD2) ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html#UUID-81bba28f-b37d-08c9-6ce1-3152446df276_section-idm234680336828288", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ Referencia: Command \/ Comando: Generar visualizaciones SFC\/LD \/ Resultado con Ladder (LD2) ", 
"snippet" : "Para los POU del PROGRAMA, las visualizaciones recién generadas se muestran en la vista POU en el formato <nombre FB> _LD_VISU . Para los sub-POU, las visualizaciones recién generadas se muestran en la vista POU , en la carpeta LD-Visus con el formato <nombre del POU> <nombre del sub-POU> _LD_VISU ....", 
"body" : "Para los POU del PROGRAMA, las visualizaciones recién generadas se muestran en la vista POU en el formato <nombre FB> _LD_VISU . Para los sub-POU, las visualizaciones recién generadas se muestran en la vista POU , en la carpeta LD-Visus con el formato <nombre del POU> <nombre del sub-POU> _LD_VISU . Los subPOU son bloques de funciones, acciones, propiedades, métodos o transiciones. " }, 
{ "title" : "Resultado con SFC ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html#UUID-81bba28f-b37d-08c9-6ce1-3152446df276_section-idm234680344022971", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ Referencia: Command \/ Comando: Generar visualizaciones SFC\/LD \/ Resultado con SFC ", 
"snippet" : "Para las POU de PROGRAMA y los bloques de funciones, las visualizaciones recién generadas se muestran en el POU ver en el formato <nombre del POU> _SFC_FRAME . Ejemplo: PLC_PRG_SFC_FRAME Puede usar un elemento de marco para integrar las visualizaciones con la extensión de nombre _SFC_FRAME . Si la v...", 
"body" : "Para las POU de PROGRAMA y los bloques de funciones, las visualizaciones recién generadas se muestran en el POU ver en el formato <nombre del POU> _SFC_FRAME . Ejemplo: PLC_PRG_SFC_FRAME Puede usar un elemento de marco para integrar las visualizaciones con la extensión de nombre _SFC_FRAME . Si la visualización se generó a partir de un bloque de funciones, entonces la instancia del bloque fb se declara automáticamente en el editor de la interfaz. Los índices, tales como iCurrentIndex son internos y se configuran automáticamente. Para los sub-POU, las visualizaciones recién generadas se muestran en la vista POU , en la carpeta SFC-SubVisus , con el formato <nombre del POU> _SFC_VISU <nombre del sub-POU>. Los sub-POU son bloques de funciones, acciones, propiedades, métodos o transiciones. Ejemplo: POU_1_SFC_VISU , POU_1_SFC_VISU_Step0_to_Init " }, 
{ "title" : "Lo que aún tienes que hacer ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html#UUID-81bba28f-b37d-08c9-6ce1-3152446df276_section-idm234680345033667", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ Referencia: Command \/ Comando: Generar visualizaciones SFC\/LD \/ Lo que aún tienes que hacer ", 
"snippet" : "Para los bloques de funciones SFC\/LD, debe transferir la instancia correspondiente. Esto no es necesario para los programas SFC\/LD porque las variables se utilizan directamente....", 
"body" : "Para los bloques de funciones SFC\/LD, debe transferir la instancia correspondiente. Esto no es necesario para los programas SFC\/LD porque las variables se utilizan directamente. " }
]
$(document).trigger('search.ready');
});