$(document).ready(function () {indexDict['en-US'] = [{ "title" : "CODESYS Ethernet Adapter ", 
"url" : "_enad_start_page.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ CODESYS Ethernet Adapter ", 
"snippet" : "See the general description for information about the following tabs of the device editor. Tab: <device name> I\/O Mapping Tab: <device name> IEC Objects Tab: <device name> Parameters Tab: <device name> Status Tab: <device name> Information An additional separate help page for the relevant device edi...", 
"body" : "See the general description for information about the following tabs of the device editor. Tab: <device name> I\/O Mapping Tab: <device name> IEC Objects Tab: <device name> Parameters Tab: <device name> Status Tab: <device name> Information An additional separate help page for the relevant device editor is available only in the case of special features. If the \"<device name> Parameters\" tab is not displayed, then select the Show generic device configuration views option in the CODESYS options, in the Device editor category. For more general information on fieldbus support in CODESYS , see: Fieldbus Support The CODESYS Ethernet adapter is used as a parent node for devices that use Ethernet-based protocols. CODESYS currently supports EtherNet\/IP, Modbus, and PROFINET IO. First, you insert the Ethernet adapter below the controller. Then you add the Ethernet-based fieldbus below the adapter. " }, 
{ "title" : "Tab: EtherNet Adapter – General ", 
"url" : "_enad_edt_general.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Tab: EtherNet Adapter – General ", 
"snippet" : "Object: Ethernet Adapter You define the network interface on this tab. Network interface : Opens the Network Adapters dialog. The Ethernet adapters can be selected here, which are available on the set target system. IP address Subnet mask Default gateway Settings of the selected network interface Ad...", 
"body" : "Object: Ethernet Adapter You define the network interface on this tab. Network interface : Opens the Network Adapters dialog. The Ethernet adapters can be selected here, which are available on the set target system. IP address Subnet mask Default gateway Settings of the selected network interface Adjust operating system settings You need to confirm this option again. Note: The settings on the target system will be overwritten by the values above. The IP settings of the operating system can be changed by the CODESYS runtime system only if this is permitted in the configuration file ( *.cfg ) of the runtime. The following entries are required for this: [SysSocket] Adapter.0.Name=\"<adapter name>\" (example: \"LAN connection 4\" ) Adapter.0.EnableSetIpAndMask=1 Redundant PLC Settings (PLC 2) When using a pair of redundant CODESYS controllers, these settings are used on the \"backup PLC\" ( PLC ID = 2 ) for the network adapter. Network interface : Opens the Network Adapters dialog. The Ethernet adapters can be selected here, which are available on the set target system. IP address Subnet mask Default gateway Settings of the selected network interface The settings for the redundant PLC are available only when you have inserted the Redundancy Configuration object below your application. " }, 
{ "title" : "Dialog: Network Adapters ", 
"url" : "_enad_edt_general.html#UUID-68dc7536-40d9-f126-1da8-b5aefc635b70_id_eb69772dd959aeac0a8640e01875adb_id_98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Tab: EtherNet Adapter – General \/ Dialog: Network Adapters ", 
"snippet" : "Interfaces Shows an overview of all available network adapters. IP address Subnet mask Default gateway These parameters are taken from the operating system and cannot be modified. MAC address MAC address of the Ethernet adapter...", 
"body" : "Interfaces Shows an overview of all available network adapters. IP address Subnet mask Default gateway These parameters are taken from the operating system and cannot be modified. MAC address MAC address of the Ethernet adapter " }
]
$(document).trigger('search.ready');
});