$(document).ready(function () {indexDict['fr'] = [{ "title" : "CODESYS IO-Link ", 
"url" : "_iolk_start_page.html", 
"breadcrumbs" : "CODESYS IO-Link \/ CODESYS IO-Link ", 
"snippet" : "Voir la description générale pour plus d'informations sur les onglets suivants de l'éditeur d'appareil. Onglet '<nom de l'appareil> Mappage d'E\/S' Onglet '<nom de l'appareil> Objets CEI' Onglet '<nom de l'appareil> Paramètres' Onglet '<nom de l'appareil> État' Onglet '<nom de l'appareil> Information...", 
"body" : "Voir la description générale pour plus d'informations sur les onglets suivants de l'éditeur d'appareil. Onglet '<nom de l'appareil> Mappage d'E\/S' Onglet '<nom de l'appareil> Objets CEI' Onglet '<nom de l'appareil> Paramètres' Onglet '<nom de l'appareil> État' Onglet '<nom de l'appareil> Informations' Une page d'aide séparée supplémentaire pour l'éditeur d'appareil concerné n'est disponible que dans le cas de fonctions spéciales. Si l'onglet \"<nom de l'appareil> Paramètres\" n'est pas affiché, alors sélectionnez le Afficher les éditeurs de configuration de périphérique génériques possibilité dans le CODESYS option, dans le Éditeur d'appareil Catégorie. IO-Link est un système de communication pour la connexion de capteurs et d'actionneurs intelligents à un système d'automatisation. Un système IO-Link se compose d'un maître IO-Link qui fournit l'interface avec l'automate supérieur (API) et d'un ou plusieurs appareils IO-Link (capteurs et actionneurs). Les fichiers de description d'appareil IODD associés doivent être installés dans le référentiel d'appareils avant que les modules IO-Link ne soient disponibles dans la boîte de dialogue 'Set device'. Pour plus d'informations, consultez : Commande \"Brancher l'appareil\" et Commande 'Référentiel de périphériques' Pour des informations plus générales sur la prise en charge des bus de terrain dans  CODESYS , voir: Prise en charge du bus de terrain " }, 
{ "title" : "Onglet : IO-Link – Infos sur l'appareil IO-Link ", 
"url" : "_iolk_edt_device_info.html", 
"breadcrumbs" : "CODESYS IO-Link \/ Onglet : IO-Link – Infos sur l'appareil IO-Link ", 
"snippet" : "Objet : Maître IO-Link L'onglet du module IO-Link affiche diverses informations sur le produit et le fournisseur de l'appareil....", 
"body" : "Objet : Maître IO-Link L'onglet du module IO-Link affiche diverses informations sur le produit et le fournisseur de l'appareil. " }, 
{ "title" : "Onglet : IO-Link – Paramètres ", 
"url" : "_iolk_edt_parameter.html", 
"breadcrumbs" : "CODESYS IO-Link \/ Onglet : IO-Link – Paramètres ", 
"snippet" : "Objet : Maître IO-Link L'onglet permet de lire les paramètres du périphérique IO-Link, de les modifier puis de les réécrire dans le périphérique. L'étendue des fonctions dépend de la description de l'appareil. Les commandes des boutons sont également disponibles dans le menu contextuel de la ligne s...", 
"body" : "Objet : Maître IO-Link L'onglet permet de lire les paramètres du périphérique IO-Link, de les modifier puis de les réécrire dans le périphérique. L'étendue des fonctions dépend de la description de l'appareil. Les commandes des boutons sont également disponibles dans le menu contextuel de la ligne sélectionnée dans le tableau des paramètres. Rôle d'utilisateur Spécialiste Maintenance Observateur Selon le rôle d'utilisateur sélectionné, plus ou moins de détails sur les paramètres sont affichés dans le tableau. Menu d'identification Informations sur l'identification de l'appareil Menu paramètres Affiche tous les paramètres de l'appareil Menu diagnostique Affiche les messages d'erreur d'un module (par exemple, erreur de tension) Menu observation Affiche les messages d'observation (par exemple, \"capteur sale\") Définir par défaut Réinitialise les valeurs en ligne des paramètres aux valeurs par défaut telles que définies dans la description de l'appareil Lire cette page Lit les valeurs actuellement affichées des paramètres de l'appareil et les actualise dans le tableau Ecrire cette page Écrit les valeurs actuellement affichées des paramètres sur le périphérique IO-Link Enregistrer les valeurs en ligne Applique la valeur actuellement affichée Valeur en ligne au Évaluer colonne Restaurer les valeurs Applique les valeurs du Évaluer colonne à la Valeur en ligne colonne Le tableau répertorie les différents paramètres (nom) et les détails des paramètres en fonction du rôle utilisateur défini et du menu sélectionné. Nom Le nom du paramètre Évaluer La valeur de paramètre actuellement valide est affichée dans Évaluer colonne. Valeur en ligne La Valeur en ligne La colonne s'affiche uniquement si l'appareil prend en charge un téléchargement de paramètres et si les paramètres affichés dans l'éditeur de configuration sont également disponibles sur l'appareil. Vous pouvez modifier les valeurs des paramètres dans cette colonne et les transmettre à l'appareil avec le Ecrire cette page commande sans modifier le projet et sans avoir besoin de télécharger une nouvelle application. Avec le Enregistrer les valeurs en ligne commande, vous pouvez enregistrer la valeur en ligne actuelle en tant que Évaluer . r\/w Autorisations sur les valeurs des paramètres ( ro : lecture seulement; rw : lire et écrire) " }
]
$(document).trigger('search.ready');
});