$(document).ready(function () {indexDict['it'] = [{ "title" : "CODESYS File-Based Storage ", 
"url" : "_fbstrge_start_page.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ CODESYS File-Based Storage ", 
"snippet" : "Pre-rilascio La versione 0.9.0.0 è la pre-release di un prodotto futuro. La pre-release è funzionante, ma potrebbe contenere errori, funzioni incomplete o modifiche nelle versioni future. La compatibilità con le versioni future non è garantita. Si sottolinea espressamente che incompatibilità, modifi...", 
"body" : "Pre-rilascio La versione 0.9.0.0 è la pre-release di un prodotto futuro. La pre-release è funzionante, ma potrebbe contenere errori, funzioni incomplete o modifiche nelle versioni future. La compatibilità con le versioni future non è garantita. Si sottolinea espressamente che incompatibilità, modifiche funzionali o perdita di funzionalità sono possibili nelle versioni future. Si esclude qualsiasi rivendicazione relativa a correzioni di bug, adattamenti, aggiornamenti o supporto per questa pre-release. CODESYS File-Based Storage fornisce un formato di archiviazione del progetto alternativo per CODESYS Development System (V3). A differenza del normale archivio binario di progetti, i progetti vengono archiviati in formato testo in una struttura di cartelle simile all'albero dei progetti. Gli oggetti che non supportano questo formato vengono archiviati in formato XML, come in precedenza. Puoi scaricare il CODESYS File-Based Storage da Negozio CODESYS Internazionale O Negozio CODESYS Nord America Lì troverete anche la scheda tecnica del prodotto. IL Libro bianco: CODESYS File-Based Storage 0.9.0.0 è disponibile per la versione 0.9.0.0. " }, 
{ "title" : "Introduzione ", 
"url" : "_fbstrge_introduction.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Introduzione ", 
"snippet" : "Il normale CODESYS Il repository del progetto crea un singolo file binario il cui contenuto non può essere letto o creato da altri strumenti. CODESYS File-Based Storage , d'altra parte, fornisce un altro formato di archiviazione basato su testo. Per ogni oggetto nell'albero del progetto vengono crea...", 
"body" : "Il normale CODESYS Il repository del progetto crea un singolo file binario il cui contenuto non può essere letto o creato da altri strumenti. CODESYS File-Based Storage , d'altra parte, fornisce un altro formato di archiviazione basato su testo. Per ogni oggetto nell'albero del progetto vengono creati uno o più file di testo, che possono essere letti o persino creati da altri editor di testo. Quando si creano progetti da altri strumenti, è necessario notare che CODESYS La versione 3 non consente incongruenze nel progetto. I progetti con stato non valido potrebbero non essere aperti o visualizzati. Il formato di esportazione basato su XML viene utilizzato per i tipi di oggetti per i quali non esiste (ancora) un formato adatto. CODESYS File-Based Storage porta con sé una serie di nuovi comandi che possono essere utilizzati per lavorare con progetti o librerie basati su file. " }, 
{ "title" : "Riferimento ", 
"url" : "_fbstrge_reference.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Comandi ", 
"url" : "_fbstrge_struct_reference_commands.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento \/ Comandi ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Comando: Nuova cartella di progetto ", 
"url" : "_fbstrge_cmd_new_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento \/ Comandi \/ Comando: Nuova cartella di progetto ", 
"snippet" : "Nuova cartella di progetto Funzione : Il comando apre il Nuovo progetto finestra di dialogo per la creazione di un nuovo progetto e crea una cartella <project name>.fbsproj per questo progetto nella posizione di archiviazione del progetto. Il .auxiliaries E .sidecars le cartelle vengono create inter...", 
"body" : "Nuova cartella di progetto Funzione : Il comando apre il Nuovo progetto finestra di dialogo per la creazione di un nuovo progetto e crea una cartella <project name>.fbsproj per questo progetto nella posizione di archiviazione del progetto. Il .auxiliaries E .sidecars le cartelle vengono create internamente nella cartella del progetto. Chiamata : FBS menu " }, 
{ "title" : "Comando: Apri cartella progetto ", 
"url" : "_fbstrge_cmd_open_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento \/ Comandi \/ Comando: Apri cartella progetto ", 
"snippet" : "Apri cartella progetto Funzione : Il comando apre Esplora file per selezionare la cartella del progetto. Chiamata : FBS menu...", 
"body" : "Apri cartella progetto Funzione : Il comando apre Esplora file per selezionare la cartella del progetto. Chiamata : FBS menu " }, 
{ "title" : "Comando: Converti progetto ", 
"url" : "_fbstrge_cmd_convert_project.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento \/ Comandi \/ Comando: Converti progetto ", 
"snippet" : "Converti progetto Funzione : Il comando converte un CODESYS progetto nel . fbsproj formato. Per fare ciò, apri prima il Sfogliare finestra di dialogo per selezionare la cartella in cui verrà memorizzato il progetto convertito. Quindi il Convertire il progetto in un archivio basato su file Si apre un...", 
"body" : "Converti progetto Funzione : Il comando converte un CODESYS progetto nel . fbsproj formato. Per fare ciò, apri prima il Sfogliare finestra di dialogo per selezionare la cartella in cui verrà memorizzato il progetto convertito. Quindi il Convertire il progetto in un archivio basato su file Si apre una finestra di dialogo. Questa finestra di dialogo mostra gli oggetti e i dispositivi del progetto che verranno convertiti nel formato di archiviazione basato su file e verifica se la conversione è possibile senza errori. Gli oggetti e i dispositivi per i quali sono presenti avvisi o per i quali la conversione non è possibile senza errori vengono visualizzati sul lato destro della finestra di dialogo. Vengono inoltre visualizzati il messaggio di avviso o di errore corrispondente e un pulsante di correzione. Chiamata : FBS menu Dialogo: Convertire il progetto in un archivio basato su file Zona sinistra Dispositivi CODESYS progetto nel Dispositivi visualizzazione POU CODESYS progetto in POU visualizzazione Zona giusta Oggetto Oggetto per il quale si verifica un errore durante la conversione o per il quale è presente un avviso Errore Visualizzazione di errori e avvisi Gli avvisi sono solo a scopo informativo. Esempio: è attiva una gestione utenti. Questa informazione andrà persa durante la conversione. Degli errori impediscono la conversione. Possibili errori: La descrizione del dispositivo non è installata Nel CODESYS albero del progetto ( Dispositivi visualizzare o POU visualizzazione), ci sono due cartelle con lo stesso nome allo stesso livello. Il nome dell'oggetto è più lungo di 255 caratteri. Ci sono 2 proprietà per la cartella. Sarebbe sufficiente che esistesse una sola proprietà. Aggiustare Pulsante per correggere rapidamente l'errore. La possibilità di una correzione rapida dipende dall'errore in questione. " }, 
{ "title" : "Comando: Progetti recenti ", 
"url" : "_fbstrge_cmd_recent_projects.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento \/ Comandi \/ Comando: Progetti recenti ", 
"snippet" : "Progetti recenti Funzione : Il comando visualizza i progetti recenti in *.fbsproj formato. Fare clic sul progetto corrispondente per aprirlo. Chiamata : FBS menu...", 
"body" : "Progetti recenti Funzione : Il comando visualizza i progetti recenti in *.fbsproj formato. Fare clic sul progetto corrispondente per aprirlo. Chiamata : FBS menu " }, 
{ "title" : "Comando: Apri cartella in Esplora file ", 
"url" : "_fbstrge_cmd_open_folder_in_file_explorer.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Riferimento \/ Comandi \/ Comando: Apri cartella in Esplora file ", 
"snippet" : "Apri cartella in Esplora file Funzione : Il comando apre la cartella del progetto *.fbsproj del progetto aperto in Esplora file. Chiamata : FBS menu...", 
"body" : "Apri cartella in Esplora file Funzione : Il comando apre la cartella del progetto *.fbsproj del progetto aperto in Esplora file. Chiamata : FBS menu " }
]
$(document).trigger('search.ready');
});