$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS Simulation Interface ", 
"url" : "_simitf_start_page.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ CODESYS Simulation Interface ", 
"snippet" : "这个 CODESYS Simulation Interface 是 IEC 61131-3 编程工具的附加组件 CODESYS Development System 用于控制器和自动化技术。 售前赛 0.9.0.0 版本是即将推出的产品的预发行版。售前赛不适用于生产性用途。它可供感兴趣的客户或仿真工具提供商在产品首次发布（版本 1.0.0.0）之前评估仿真接口。 售前赛将 不是 可通过以下方式获得 CODESYS Store International 。请联系 sales@codesys.com 如果你想评估 CODESYS Simulation Interface 。...", 
"body" : "这个 CODESYS Simulation Interface 是 IEC 61131-3 编程工具的附加组件 CODESYS Development System 用于控制器和自动化技术。 售前赛 0.9.0.0 版本是即将推出的产品的预发行版。售前赛不适用于生产性用途。它可供感兴趣的客户或仿真工具提供商在产品首次发布（版本 1.0.0.0）之前评估仿真接口。\n售前赛将 不是 可通过以下方式获得 CODESYS Store International 。请联系 sales@codesys.com 如果你想评估 CODESYS Simulation Interface 。 " }, 
{ "title" : "导言 ", 
"url" : "_simitf_intorduction.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 导言 ", 
"snippet" : "这个 CODESYS 仿真接口需要三个子系统才能实现完全集成的系统。 模拟经纪商 仿真接口 仿真演示器，前提是系统本应运行用于演示目的。 或者（作为仿真演示器的替代品）来自第三方供应商的仿真工具。 仿真接口生成 OPC 信息模型并将其加载到经纪人上。该经纪商托管OPC信息模型，并允许仿真工具通过OPC UA客户端\/服务器对其进行读取。利用这些信息，仿真工具能够创建用于 OPC PubSub 通信的远程站...", 
"body" : "这个 CODESYS 仿真接口需要三个子系统才能实现完全集成的系统。 模拟经纪商 仿真接口 仿真演示器，前提是系统本应运行用于演示目的。 或者（作为仿真演示器的替代品）来自第三方供应商的仿真工具。 仿真接口生成 OPC 信息模型并将其加载到经纪人上。该经纪商托管OPC信息模型，并允许仿真工具通过OPC UA客户端\/服务器对其进行读取。利用这些信息，仿真工具能够创建用于 OPC PubSub 通信的远程站 " }, 
{ "title" : "模拟经纪商 ", 
"url" : "_simitf_intorduction.html#UUID-af54d22d-76ba-7559-d5ee-0e5ca76c551d", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 导言 \/ 模拟经纪商 ", 
"snippet" : "代理是使用模拟接口生成的。它作为单独的 IEC 应用程序提供，并作为 OPC UA 服务器在单独的服务器上执行 CODESYS 运行时间。 该子系统允许用户监视和控制通过仿真接口模拟的应用程序。代理运行的设备或运行时也被称为 “模拟经纪人” 或 “模拟经纪人”。该子系统是其中的一部分 CODESYS Simulation Interface 附加组件。...", 
"body" : "代理是使用模拟接口生成的。它作为单独的 IEC 应用程序提供，并作为 OPC UA 服务器在单独的服务器上执行 CODESYS 运行时间。 该子系统允许用户监视和控制通过仿真接口模拟的应用程序。代理运行的设备或运行时也被称为 “模拟经纪人” 或 “模拟经纪人”。该子系统是其中的一部分 CODESYS Simulation Interface 附加组件。 " }, 
{ "title" : "仿真接口 ", 
"url" : "_simitf_intorduction.html#UUID-8873f5f3-8ecf-aa27-263e-142938ac8674", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 导言 \/ 仿真接口 ", 
"snippet" : "添加 仿真接口 在您的应用程序下方指向您的项目，配置仿真接口，然后启动应用程序。通过这种方式，所有 I\/O 均已解耦，应用程序连接到仿真工具或仿真演示器 基本上，如果 模拟已启用 选项已设置，应用程序（或最终与该应用程序相关的输入\/输出）通过 OPC UA PubSub 与仿真进行通信。未启用此选项时，应用程序通过现场总线与真实环境通信 仿真界面可帮助您通过 OPC UA 客户端\/服务器使用仿真工具（或其他 UA 客户端）查找仿真应用程序。您可以通过在另一个服务器上部署和执行仿真代理来获得支持 CODESYS 运行时环境。 运行仿真接口的设备或运行时也称为 “仿真目标” 或 “SIM 目标”。...", 
"body" : "添加 仿真接口 在您的应用程序下方指向您的项目，配置仿真接口，然后启动应用程序。通过这种方式，所有 I\/O 均已解耦，应用程序连接到仿真工具或仿真演示器 基本上，如果 模拟已启用 选项已设置，应用程序（或最终与该应用程序相关的输入\/输出）通过 OPC UA PubSub 与仿真进行通信。未启用此选项时，应用程序通过现场总线与真实环境通信 仿真界面可帮助您通过 OPC UA 客户端\/服务器使用仿真工具（或其他 UA 客户端）查找仿真应用程序。您可以通过在另一个服务器上部署和执行仿真代理来获得支持 CODESYS 运行时环境。 运行仿真接口的设备或运行时也称为 “仿真目标” 或 “SIM 目标”。该子系统是其中的一部分 CODESYS Simulation Interface 附加组件。 有关更多信息，请参阅： 对象： " }, 
{ "title" : "仿真演示器 ", 
"url" : "_simitf_intorduction.html#UUID-63d1789b-b9d8-10c6-e65a-e82ea895537c", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 导言 \/ 仿真演示器 ", 
"snippet" : "对于作为仿真工具开发人员或供应商并希望在自己的产品和仿真工具中实现 PubSub 通信的客户来说，仿真演示器是一种参考实现。 仿真演示器是如何执行序列化和反序列化的实际演示。 子系统是 不是 的一部分 CODESYS Simulation Interface 附加组件。你得到的工具是 CODESYS Simulation Interface Example 包裹。 版本 0.9.0.0 将无法通过以下方式提供 CODESYS Installer 。该产品可以向销售部门索取。 已知限制 无法重新连接 CODESYS Simulation Demonstrator 预发行版本 0.9.0.0 中实...", 
"body" : "对于作为仿真工具开发人员或供应商并希望在自己的产品和仿真工具中实现 PubSub 通信的客户来说，仿真演示器是一种参考实现。 仿真演示器是如何执行序列化和反序列化的实际演示。 子系统是 不是 的一部分 CODESYS Simulation Interface 附加组件。你得到的工具是 CODESYS Simulation Interface Example 包裹。 版本 0.9.0.0 将无法通过以下方式提供 CODESYS Installer 。该产品可以向销售部门索取。 已知限制 无法重新连接 CODESYS Simulation Demonstrator 预发行版本 0.9.0.0 中实现仿真目标的工具。可能的解决方法：使用选择同一个经纪商 选择经纪人设备 ， 连接 命令。 这个问题需要在 OPC 基金会的 OPC UA 堆栈中修复 (#2929)。参见： https:\/\/github.com\/OPCFoundation\/UA-.NETStandard\/issues\/2929 " }, 
{ "title" : "设置 ", 
"url" : "_simitf_settings.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 设置 ", 
"snippet" : "首先配置仿真接口。 当您在上启用模拟时 配置 选项卡中，仿真应用程序连接到仿真工具。 模拟已启用 该选项被禁用，应用程序使用物理现场总线。 有关更多信息，请参阅： 选项卡： ， 选项卡：...", 
"body" : "首先配置仿真接口。 当您在上启用模拟时 配置 选项卡中，仿真应用程序连接到仿真工具。 模拟已启用 该选项被禁用，应用程序使用物理现场总线。 有关更多信息，请参阅： 选项卡： ， 选项卡： " }, 
{ "title" : "使用仿真接口 ", 
"url" : "_simitf_use_the_sim_interface.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 使用仿真接口 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "准备工作 ", 
"url" : "_simitf_use_the_sim_interface.html#UUID-11fcc5e9-f7fe-dcee-a616-ddc58e0f84db", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 使用仿真接口 \/ 准备工作 ", 
"snippet" : "在开始使用仿真接口时，使用两个配置本地环境会很有帮助 CODESYS 控制器。 最简单的方法是下载两个 CODESYS Control Win SL 控制器来自 CODESYS Store International 。您将在以下位置找到产品和产品数据表 CODESYS 国际商店 或者在 CODESYS 商店北美 。ZIP 文件包含 64 位和 32 位版本的 CODESYS Control Win SL 。 安装软件包 安装 CODESYS Simulation Interface 您的附加组件 CODESYS 编程工具。 安装 CODESYS Simulation Interface Ex...", 
"body" : "在开始使用仿真接口时，使用两个配置本地环境会很有帮助 CODESYS 控制器。 最简单的方法是下载两个 CODESYS Control Win SL 控制器来自 CODESYS Store International 。您将在以下位置找到产品和产品数据表 CODESYS 国际商店 或者在 CODESYS 商店北美 。ZIP 文件包含 64 位和 32 位版本的 CODESYS Control Win SL 。 安装软件包 安装 CODESYS Simulation Interface 您的附加组件 CODESYS 编程工具。 安装 CODESYS Simulation Interface Example 包。 这个 CODESYS Simulation Demonstrator 附加组件是软件包的一部分。 安装并打开 SimulationInterfaceExample.projectarchive 示例项目。 安装两个运行时系统。 使用打开标准项目 CODESYS Control Win 32 位设备。启动网关和设备。 在 设备 查看，双击此设备。 设备编辑器打开。 点击 扫描网络 按钮。 这个 CODESYS Control Win 显示 32 位运行时环境。 选择设备并照常进行配置。 设备已连接。 选择该命令 更改运行时安全策略 然后点击 是的 确认下一个对话框。 通信设置 配置设备用户管理。 在 更改运行时安全策略 对话框中，从中设置设备用户管理 强制用户管理 到 可选的用户管理 。 启用 允许匿名登录 选项，然后单击 好吧 确认设置。 点击 设备 按钮，然后选择 重命名活动设备 命令并在下一个对话框中重命名活动设备。 指定新设备名称（例如： SimBroker ）。 将设备更新为设备描述 CODESYS Control Win x64 。 重复步骤 3，但将设备重命名为 SimTarget 。 准备好了。 " }, 
{ "title" : "简单的例子 ", 
"url" : "_simitf_use_the_sim_interface.html#UUID-1abd1d51-840b-821b-1318-dc0fea54f94f", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 使用仿真接口 \/ 简单的例子 ", 
"snippet" : "为了让您熟悉仿真界面，我们逐步开发了一个简单的示例。想象一台机器，其 I\/O 数据通过现场总线交换。 PROFIBUS 用作现场总线。 创建新的标准项目并选择 64 位设备 CODESYS Control Win 作为仿真目标的设备类型。 双击该设备。 设备编辑器打开。 配置以下内容： 添加以太网适配器。 添加一个 PROFINET 控制器。 添加 8 位输入。 添加 8 位输出。 在中声明两个字节变量 PLC_PRG 并在应用程序代码中使用变量。 byIn ， byOut 将变量分配给输入和输出。 生成代码。 在最佳情况下，编译执行时不会出现错误。 现在，您有了以下设备树： 这是我们要模拟的...", 
"body" : "为了让您熟悉仿真界面，我们逐步开发了一个简单的示例。想象一台机器，其 I\/O 数据通过现场总线交换。 PROFIBUS 用作现场总线。 创建新的标准项目并选择 64 位设备 CODESYS Control Win 作为仿真目标的设备类型。 双击该设备。 设备编辑器打开。 配置以下内容： 添加以太网适配器。 添加一个 PROFINET 控制器。 添加 8 位输入。 添加 8 位输出。 在中声明两个字节变量 PLC_PRG 并在应用程序代码中使用变量。 byIn ， byOut 将变量分配给输入和输出。 生成代码。 在最佳情况下，编译执行时不会出现错误。 现在，您有了以下设备树： 这是我们要模拟的应用程序。 使用以下步骤添加仿真接口。您可以对其进行配置以模拟应用程序。 选择应用程序，然后选择 添加对象 → 仿真接口 快捷菜单中的命令。 在下一个对话框中，单击 添加 命令。 已添加仿真接口，现在可以对其进行配置。 对于这些第一步，保持默认值不变，仅调整设备的 IP 地址。指定本地地址（例如：192.168.178.47 在 配置 选项卡，设置 仿真选项 设置为 仅映射了 I\/O 信号 。 选择 模拟已启用 选项。 切换到 模拟经纪商 选项卡。 点击 选择经纪人设备 按钮。 选择 Gateway-1 然后单击 扫描网络 按钮。 这个 SimBroker 和 SimTarget 显示设备。 选择 SimBroker 设备。 点击 更新经纪人 按钮。 等到消息出现 模拟经纪人已成功更新 显示出来。 登录到 SimTarget 设备。 现在，软件还可以扫描该信息模型，以获取有关现有仿真目标和所用信息模型的信息。这个 CODESYS Simulation Interface Example 插件演示了这一点。你所需要做的就是安装并运行 CODESYS Simulation Demonstrator.msi 文件。 点击 浏览 按钮搜索目的地。它应该显示为 ISim_Target_xxx_xxx_xxx_xxx 正如你在下面看到的。下图还显示了其用法 仿真接口 对象和 仿真演示器 。 Application_PLC_PRG_byOut 是由出版商撰写的，价值观 Application_PLC_PRG_byIn 已由仿真演示者通过 OPC UA PubSub 订阅。 " }, 
{ "title" : "开发人员信息 ", 
"url" : "_simitf_information_for_developers.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 ", 
"snippet" : "出于开发目的，必须了解两种主要协议用于通信。 第一个协议是 OPC UA 客户端\/服务器。经纪人和仿真工具使用该协议来共享信息模型。因此，仿真工具（客户端）通过OPC UA客户端\/服务器读取信息模型，并设置了与所描述的OPC UA发布\/订阅通信相反的 对于上面的示例，这意味着开发的仿真工具中需要发布者和订阅者才能获得有效的通信架构：a PublisherSet 用 Publisher0 还有一个 SubscriberSet 用 Subscriber0 。 如果你想获取的源代码 CODESYS Simulation Demonstrator ，将请求发送至 技术支持 。...", 
"body" : "出于开发目的，必须了解两种主要协议用于通信。 第一个协议是 OPC UA 客户端\/服务器。经纪人和仿真工具使用该协议来共享信息模型。因此，仿真工具（客户端）通过OPC UA客户端\/服务器读取信息模型，并设置了与所描述的OPC UA发布\/订阅通信相反的 对于上面的示例，这意味着开发的仿真工具中需要发布者和订阅者才能获得有效的通信架构：a PublisherSet 用 Publisher0 还有一个 SubscriberSet 用 Subscriber0 。 如果你想获取的源代码 CODESYS Simulation Demonstrator ，将请求发送至 技术支持 。 " }, 
{ "title" : "有关 C# 源代码的信息 ", 
"url" : "_simitf_information_on_csharp_source.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ 有关 C# 源代码的信息 ", 
"snippet" : "源代码不包含在示例包中。 对于仿真工具的开发人员来说，以下信息既有趣又重要。 仿真演示器使用开源 OPC UA 堆栈。 有关更多信息，请参阅： OPCFoundation\/UA-.NETStandard 各个类的功能如下所述。...", 
"body" : "源代码不包含在示例包中。 对于仿真工具的开发人员来说，以下信息既有趣又重要。 仿真演示器使用开源 OPC UA 堆栈。 有关更多信息，请参阅： OPCFoundation\/UA-.NETStandard 各个类的功能如下所述。 " }, 
{ "title" : "MainWindow.xaml.cs ", 
"url" : "_simitf_information_on_csharp_source.html#UUID-043180a5-86fa-9f2a-0dbd-f0da3a1ac489_section-idm234825454321504", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ 有关 C# 源代码的信息 \/ MainWindow.xaml.cs ", 
"snippet" : "这个类是顶级类（顶层类）。 browseButton_Click 启动目标搜索操作。见下文 Simitf.cs > 第一步。 对话框打开并显示所有可用目标。见下文。第二步是选择目标。 btnStartConnection_Click 启动与所选目标的连接。参见 PubSubConfigurator.cs 下面。 PubSubApplication_DataReceived 在收到新的订阅数据时调用。 DispatcherTimer_Tick : 对发布\/订阅数据进行解码或编码。...", 
"body" : "这个类是顶级类（顶层类）。 browseButton_Click 启动目标搜索操作。见下文 Simitf.cs > 第一步。 对话框打开并显示所有可用目标。见下文。第二步是选择目标。 btnStartConnection_Click 启动与所选目标的连接。参见 PubSubConfigurator.cs 下面。 PubSubApplication_DataReceived 在收到新的订阅数据时调用。 DispatcherTimer_Tick : 对发布\/订阅数据进行解码或编码。 " }, 
{ "title" : "SimItf.cs ", 
"url" : "_simitf_information_on_csharp_source.html#UUID-043180a5-86fa-9f2a-0dbd-f0da3a1ac489_section-idm234825461659681", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ 有关 C# 源代码的信息 \/ SimItf.cs ", 
"snippet" : "该类包含用于搜索代理以获取有关现有仿真目标的信息的代码。 搜索分两步完成： 第一步 构造函数读取的命名空间索引 CODESYS 仿真接口。 然后构造函数从代理读取所有可用的仿真接口目标（ 目标 财产）。 第二步 这个 Set Target 公共方法可用于选择一个可用的仿真接口目标。 将在所选目标中详细搜索所有发布者、订阅者和所需的数据记录。 可以通过属性读取搜索到的信息（参见代码）。...", 
"body" : "该类包含用于搜索代理以获取有关现有仿真目标的信息的代码。 搜索分两步完成： 第一步 构造函数读取的命名空间索引 CODESYS 仿真接口。 然后构造函数从代理读取所有可用的仿真接口目标（ 目标 财产）。 第二步 这个 Set Target 公共方法可用于选择一个可用的仿真接口目标。 将在所选目标中详细搜索所有发布者、订阅者和所需的数据记录。 可以通过属性读取搜索到的信息（参见代码）。 " }, 
{ "title" : "PubSubConfigurator.cs ", 
"url" : "_simitf_information_on_csharp_source.html#UUID-043180a5-86fa-9f2a-0dbd-f0da3a1ac489_section-idm23482546491366", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ 有关 C# 源代码的信息 \/ PubSubConfigurator.cs ", 
"snippet" : "该类接管所选目标的发布\/订阅配置。 致电 Create 方法并转发来自的发布\/订阅信息 SimItf.cs 。...", 
"body" : "该类接管所选目标的发布\/订阅配置。 致电 Create 方法并转发来自的发布\/订阅信息 SimItf.cs 。 " }, 
{ "title" : "OPC PubSub ", 
"url" : "_simitf_opc_pubsub.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ OPC PubSub ", 
"snippet" : "基于UADP协议的应用程序的基础是通过UADP一致地传输数据结构（即通过UDP\/IP进行OPC编码的帧）。 由于必须保持一致性，因此数据结构必须适合 UDP 帧（1500 字节）。 而且由于空间有限，通过 UADP 进行传输必须尽可能高效。 只有 RawData Field Encoding 支持。（这样可以节省空间。） 只有 DataSetMessages 类型的 Data Key Frame 支持。（实时数据的周期性交换） 结构 — 即值序列 ( DataSetField ) 及其类型 ( DataSetMessage ) — 在运营期间保持不变，并由出版商和订阅者事先同意。（操作期间无需...", 
"body" : "基于UADP协议的应用程序的基础是通过UADP一致地传输数据结构（即通过UDP\/IP进行OPC编码的帧）。 由于必须保持一致性，因此数据结构必须适合 UDP 帧（1500 字节）。 而且由于空间有限，通过 UADP 进行传输必须尽可能高效。 只有 RawData Field Encoding 支持。（这样可以节省空间。） 只有 DataSetMessages 类型的 Data Key Frame 支持。（实时数据的周期性交换） 结构 — 即值序列 ( DataSetField ) 及其类型 ( DataSetMessage ) — 在运营期间保持不变，并由出版商和订阅者事先同意。（操作期间无需传输任何元数据。） 下表将帮助您了解所使用的参数： 这个 GroupVersion 参数由 Subscriber 检查收到的结构是否与预期的结构相对应。订阅者可以使用 SequenceNumber 用于识别消息是否丢失的参数。 这个 DataSetMessages 参数的结构如下。从 IEC 到 OPC UA，发布商的数据结构以 1:1 编码 下表说明了所使用的参数。 这个 DataSetMessage 参数，它包含 DataSetMessage 标题和个人 DataSetFields 数据 (= Data Key Frame )，插入在 NetworkMessage 标题。 A DataSetField 由基本数据类型的值组成： OPC UA 规范的第 14 部分指出： 这个 FieldCount 如果是，则必须省略参数 RwaData Field Encoding 选项设置在 EncodingFlags 的旗帜 DataSetMessage 标题（ DataSetFlags1 ）。 这个 FieldCount 因此，未在 “数据关键帧” 中编码。这意味着 1500 字节-15 字节 = 1485 字节的用户数据仍然可用于通过 UADP 传输数据结构 OPC UA 规范的第 14 部分指出： 这个 FieldCount 如果是，则会被忽略 RawDate Encodings 设置在 EncodingFlags 的 DataSetMessage 标题（ DataSetFalgs1 ）。 这个 FieldCount 因此，未在数据关键帧中编码。这意味着 1500 字节-15 字节 = 1485 字节的用户数据仍然可用于通过 UADP 传输数据结构 PubSub 组件概述 " }, 
{ "title" : "技术基础知识 ", 
"url" : "_simitf_technical_basics.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ 技术基础知识 ", 
"snippet" : "二进制数据编码和标题布局的技术基础知识 机器对机器通信是机器间通信的主要应用领域 CODESYS 图书馆 OPC UA PubSub SL 。OPC基金会在 [A6] C.2中提供了 “UADP周期固定” 配置文件，用于以实时为导向 出版商 PubSub 发布商 UADP 定期固定设置 发布商支持以下编码 NetworkMessages 和 DataSetMessages 的消息 UADP Message 具有固定布局的周期性数据的标题。 订阅者 PubSub 订阅者 UADP 定期固定设置 订阅者支持解码 NetworkMessages 和 DataSetMessages 的消息 UADP ...", 
"body" : "二进制数据编码和标题布局的技术基础知识 机器对机器通信是机器间通信的主要应用领域 CODESYS 图书馆 OPC UA PubSub SL 。OPC基金会在 [A6] C.2中提供了 “UADP周期固定” 配置文件，用于以实时为导向 出版商 PubSub 发布商 UADP 定期固定设置 发布商支持以下编码 NetworkMessages 和 DataSetMessages 的消息 UADP Message 具有固定布局的周期性数据的标题。 订阅者 PubSub 订阅者 UADP 定期固定设置 订阅者支持解码 NetworkMessages 和 DataSetMessages 的消息 UADP Message 具有固定布局的周期性数据的标题。 由于空间和传输时间有限，因此通过 UADP 进行数据编码和传输必须尽可能高效。目的是创建满足高效传输要求的发布\/订阅系统的配置。这意味着尽可能少的元数据，每条网络消息的用户数据尽可能多。当实现 [A6] C.2 中的规格时，可以很好地实现这些目标 OPC 基金会需要以下属性才能实现发布\/订阅，这些属性遵循 UADP-Periodic-Fixed 个人资料: OPC UA 二进制数据编码 固定的消息布局 UADP-Periodic-Fixed 标题布局 [A6] C.2 出版商和订阅者应提前了解他们所支持的结构。 " }, 
{ "title" : "OPC UA Binary Data Encoding ", 
"url" : "_simitf_opc_ua_binary_data_encoding.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ OPC UA Binary Data Encoding ", 
"snippet" : "这个 OPC UA Binary Data Encoding 是一种数据格式，专为满足 OPC UA 应用程序的性能要求而开发。这种格式主要是为快速编码和解码而设计的，因此还考虑了线路上编码数据的大小 OPC UA 二进制数据编码基于几种原始数据类型，具有明确定义的编码规则，可以按顺序写入二进制流或从二进制流读取。 通过顺序写入每个字段的编码形式来对结构进行编码。如果特定字段也是一个结构，则在下一个字段写入包含结构之前，其字段的值将按顺序写入 必须将所有字段写入数据流，即使它们包含零值。每种原始类型的编码表示如何对该类型的零值或默认值进行编码 OPC UA 二进制数据编码不包含任何类型或字段名...", 
"body" : "这个 OPC UA Binary Data Encoding 是一种数据格式，专为满足 OPC UA 应用程序的性能要求而开发。这种格式主要是为快速编码和解码而设计的，因此还考虑了线路上编码数据的大小 OPC UA 二进制数据编码基于几种原始数据类型，具有明确定义的编码规则，可以按顺序写入二进制流或从二进制流读取。 通过顺序写入每个字段的编码形式来对结构进行编码。如果特定字段也是一个结构，则在下一个字段写入包含结构之前，其字段的值将按顺序写入 必须将所有字段写入数据流，即使它们包含零值。每种原始类型的编码表示如何对该类型的零值或默认值进行编码 OPC UA 二进制数据编码不包含任何类型或字段名称信息，因为所有 OPC UA 应用程序都需要事先知道它们支持哪些服务和结构。 [P6] 5.2.1： “条款 OPC UA Binary Data Encoding 和 Raw Data Field Encoding 具有相同的含义，并根据引用的来源进行相应的使用。 映射基本数据类型 IEC 61131-3 [P6] 5.2.1 OPC 美国 参考文献 BOOL 布尔值 1 Boolean [P6] 5.2.2.1 BYTE 字节 3 Byte CHAR 单字节字符 3 Byte DATE 日期（仅限） 13 DateTime DINT 双整数 6 Int32 DT 一天中的日期和时间 [s] 13 DateTime [P6] 5.2.2.5 DWORD 长度为 32 的位串 7 UInt32 INT 整数 4 Int16 [P6] 5.2.2.1 LDATE 长日期 [ns] 8 Int64 LDT 一天中的日期和时间 [ns] 8 Int64 LINT 长整数 8 Int64 LREAL 长浮点数 11 Double LTIME 持续时间 [ns] 8 Int64 LTOD 一天中的时间 [ns] 8 Int64 LWORD 长度为 64 的位串 9 UInt64 REAL 浮点数 10 Float [P6] 5.2.2.3 SINT 短整数 2 SByte STRING 编码：Windows-1252 12 String [P6] 5.2.2.4 TIME 持续时间 [ms] 8 Int64 TOD 一天中的时间 [ms] 7 UInt32 UDINT 19 StatusCode [P6] 5.2.2.11 UDINT VersionTime [P4] 7.38 UDINT 无符号双整数 7 UInt32 UINT 无符号整数 5 UInt16 ULINT 无符号 Iong 整数 9 UInt64 USINT 无符号短整数 3 Byte WCHAR 双字节字符 5 UInt16 WORD 长度为 16 的位串 5 UInt16 WSTRING 编码：UCS-2 12 String " }, 
{ "title" : "字符串 ", 
"url" : "_simitf_opc_ua_binary_data_encoding.html#UUID-bb341947-7839-531b-1454-a1d942c90ddc_section-idm234825522855678", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ OPC UA Binary Data Encoding \/ 字符串 ", 
"snippet" : "由于 OPC UA 字符串的 UTF 8 编码，无法事先确定其长度。这取决于所使用的字符。因此，定义时必须指定最大长度 DataSetField 这种数据类型。剩余空间用 0 值字节填充。字符串的最大长度 ( maxStringLength ) 在 [P14] 6.2.2.1.3 中进行了描述 FieldMetaData 。...", 
"body" : "由于 OPC UA 字符串的 UTF 8 编码，无法事先确定其长度。这取决于所使用的字符。因此，定义时必须指定最大长度 DataSetField 这种数据类型。剩余空间用 0 值字节填充。字符串的最大长度 ( maxStringLength ) 在 [P14] 6.2.2.1.3 中进行了描述 FieldMetaData 。 " }, 
{ "title" : "StatusCode ", 
"url" : "_simitf_opc_ua_binary_data_encoding.html#UUID-bb341947-7839-531b-1454-a1d942c90ddc_section-idm234825523271513", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ OPC UA Binary Data Encoding \/ StatusCode ", 
"snippet" : "变量 StatusCode 被编码为 UInt32 。...", 
"body" : "变量 StatusCode 被编码为 UInt32 。 " }, 
{ "title" : "VersionTime ", 
"url" : "_simitf_opc_ua_binary_data_encoding.html#UUID-bb341947-7839-531b-1454-a1d942c90ddc_section-idm234825523466288", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 开发人员信息 \/ OPC UA Binary Data Encoding \/ VersionTime ", 
"snippet" : "变量 VersionTime 被编码为 UInt32 。它以秒为单位显示了自 2000 年以来的时间。纪元日期是世界标准时间 2000 年 1 月 1 日午夜（00:00）。它用作基于上次修改时间的版本号。如果版本已更新，则新值必须大于先前的值。值 0 用于表示没有可用的版本信息。...", 
"body" : "变量 VersionTime 被编码为 UInt32 。它以秒为单位显示了自 2000 年以来的时间。纪元日期是世界标准时间 2000 年 1 月 1 日午夜（00:00）。它用作基于上次修改时间的版本号。如果版本已更新，则新值必须大于先前的值。值 0 用于表示没有可用的版本信息。 " }, 
{ "title" : "参考 ", 
"url" : "_simitf_ref.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 参考 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对象： 仿真接口 ", 
"url" : "_simitf_ref_object_simulation_interface.html", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 参考 \/ 对象： 仿真接口 ", 
"snippet" : "这个 仿真接口 对象位于应用程序下方。它为仿真接口和仿真代理提供配置器...", 
"body" : "这个 仿真接口 对象位于应用程序下方。它为仿真接口和仿真代理提供配置器 " }, 
{ "title" : "选项卡： 配置 ", 
"url" : "_simitf_ref_object_simulation_interface.html#UUID-fa9b466a-c433-1b37-c434-4e996e66915b", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 参考 \/ 对象： 仿真接口 \/ 选项卡： 配置 ", 
"snippet" : "模拟已启用 ：应用程序连接到仿真工具。（因此，物理 I\/O 是解耦的。) ：应用程序使用物理 I\/O。 仿真选项 整个 I\/O 映像 发送和接收整个 I\/O 映像。它与 I\/O 是否映射无关。 仅映射了 I\/O 信号 仅发送和接收分配的 I\/O 信号。 IP 设置 Publisher Multicast\/Unicast IP 用于发布 I\/O 映射输出的 IP 地址 确保此地址范围与共享环境中的其他 IT\/OT 系统不匹配。 Subscriber Multicast IP 订阅 I\/O 映射输入时使用的 IP 地址 确保此地址范围与共享环境中的其他 IT\/OT 系统不匹配。 使用设备 IP 进...", 
"body" : "模拟已启用 ：应用程序连接到仿真工具。（因此，物理 I\/O 是解耦的。) ：应用程序使用物理 I\/O。 仿真选项 整个 I\/O 映像 发送和接收整个 I\/O 映像。它与 I\/O 是否映射无关。 仅映射了 I\/O 信号 仅发送和接收分配的 I\/O 信号。 IP 设置 Publisher Multicast\/Unicast IP 用于发布 I\/O 映射输出的 IP 地址 确保此地址范围与共享环境中的其他 IT\/OT 系统不匹配。 Subscriber Multicast IP 订阅 I\/O 映射输入时使用的 IP 地址 确保此地址范围与共享环境中的其他 IT\/OT 系统不匹配。 使用设备 IP 进行单播 运行应用程序的设备的 IP 地址 启动端口 通信端口 默认值：4840 发送\/接收设置 Tx Publisher ID 通过 pub\/sub 进行通信的 ID 默认值：10 Tx Writer Group Start ID 通过 pub\/sub 进行通信的 ID 默认值：10 Rx Publisher ID 通过 pub\/sub 进行通信的 ID 默认值：20 Rx Writer Group Start ID 通过 pub\/sub 进行通信的 ID 默认值：20 所有设置都有工具提示。将鼠标指针移到设置名称上时，会出现工具提示。 " }, 
{ "title" : "选项卡： 状态 ", 
"url" : "_simitf_ref_object_simulation_interface.html#UUID-a691adfa-f347-5480-5f88-f80afe35e418", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 参考 \/ 对象： 仿真接口 \/ 选项卡： 状态 ", 
"snippet" : "此页面用于诊断目的。它显示有关单个任务的发送和读取状态的信息。...", 
"body" : "此页面用于诊断目的。它显示有关单个任务的发送和读取状态的信息。 " }, 
{ "title" : "选项卡： 模拟经纪商 ", 
"url" : "_simitf_ref_object_simulation_interface.html#UUID-f5ac9339-10b2-87e5-ef5a-2757b5bd0b4a", 
"breadcrumbs" : "CODESYS Simulation Interface \/ 参考 \/ 对象： 仿真接口 \/ 选项卡： 模拟经纪商 ", 
"snippet" : "仿真代理包含一个 OPC UA 服务器，其仿真模型为 OPC UA PubSubsub-Configuration。而且它可以管理多个设备的配置。 按钮： 选择经纪人设备 打开 选择设备 对话框。 从列表中选择所需的控制器。经纪人应用程序可以在任何标准上运行 CODESYS 控制器。 注意：所选运行时系统必须提供 OPC UA 服务器。 注意：代理设备的设备描述必须安装在您的设备存储库中 CODESYS Development System 。 按钮： 更新经纪人 创建或更新模拟代理的应用程序 创建的经纪人应用程序将添加到现有的经纪人设置中。如果没有可用的代理设置，则会自动创建、下载并启动新的...", 
"body" : "仿真代理包含一个 OPC UA 服务器，其仿真模型为 OPC UA PubSubsub-Configuration。而且它可以管理多个设备的配置。 按钮： 选择经纪人设备 打开 选择设备 对话框。 从列表中选择所需的控制器。经纪人应用程序可以在任何标准上运行 CODESYS 控制器。 注意：所选运行时系统必须提供 OPC UA 服务器。 注意：代理设备的设备描述必须安装在您的设备存储库中 CODESYS Development System 。 按钮： 更新经纪人 创建或更新模拟代理的应用程序 创建的经纪人应用程序将添加到现有的经纪人设置中。如果没有可用的代理设置，则会自动创建、下载并启动新的代理设置。 经纪人通信设置 设备名称 示例： SimBroker 设备地址 示例： 0001 序列号 目标 ID 示例：0000 0004 目标类型 示例： 4096 目标供应商 示例： CODESYS 目标版本 示例： 3.5.21.0 " }
]
$(document).trigger('search.ready');
});