$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS POU Visu Generator ", 
"url" : "_pvg_start_page.html", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator ", 
"snippet" : "CODESYS POU Visu Generator 是的附加组件 CODESYS Development System 。 使用此插件，您可以根据在 SFC 或 LD2 中编程的 POU 生成可视化效果。 你可以使用 CODESYS Installer 安装和更新 CODESYS POU Visu Generator 附加组件。...", 
"body" : "CODESYS POU Visu Generator 是的附加组件 CODESYS Development System 。 使用此插件，您可以根据在 SFC 或 LD2 中编程的 POU 生成可视化效果。 你可以使用 CODESYS Installer 安装和更新 CODESYS POU Visu Generator 附加组件。 " }, 
{ "title" : "在 SFC 或 LD2 中为 POU 创建可视化 ", 
"url" : "_pvg_start_page.html#UUID-22a83d9d-042d-8266-f215-334a372e3950", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator \/ 在 SFC 或 LD2 中为 POU 创建可视化 ", 
"snippet" : "对于 POU ( PROGRAM 或者 FUNCTION_BLOCK ) 编程在 顺序功能图 (SFC) 或者 梯形图 (LD2) 实现语言，你可以创建一个可视化对象来显示合适的方框图。 如果你想实现这样的可视化，那么 生成 SFC\/LD 可视化效果 命令可以帮助你解决这个问题。...", 
"body" : "对于 POU ( PROGRAM 或者 FUNCTION_BLOCK ) 编程在 顺序功能图 (SFC) 或者 梯形图 (LD2) 实现语言，你可以创建一个可视化对象来显示合适的方框图。 如果你想实现这样的可视化，那么 生成 SFC\/LD 可视化效果 命令可以帮助你解决这个问题。 " }, 
{ "title" : "从 SFC POU 生成可视化 ", 
"url" : "_pvg_start_page.html#UUID-d0409bfc-911d-4924-b44d-a70354f5bf71", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator \/ 在 SFC 或 LD2 中为 POU 创建可视化 \/ 从 SFC POU 生成可视化 ", 
"snippet" : "只有 LD2 对象才有可能 您只能在 POU 中创建 POU 的可视化效果 梯子 (LD2) 实现语言。为了在 POU 中可视化 LD ，首先使用将其转换为 LD2 转换为新阶梯 命令。之后，您可以从中生成 LD2 可视化 有关详细信息，请参阅：For more information, see: 命令：转换为新梯子...", 
"body" : "只有 LD2 对象才有可能 您只能在 POU 中创建 POU 的可视化效果 梯子 (LD2) 实现语言。为了在 POU 中可视化 LD ，首先使用将其转换为 LD2 转换为新阶梯 命令。之后，您可以从中生成 LD2 可视化 有关详细信息，请参阅：For more information, see: 命令：转换为新梯子 " }, 
{ "title" : "从 SFC POU 生成可视化 ", 
"url" : "_pvg_start_page.html#UUID-dec8ea49-3386-d969-6220-015bdafe3329", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ CODESYS POU Visu Generator \/ 在 SFC 或 LD2 中为 POU 创建可视化 \/ 从 SFC POU 生成可视化 ", 
"snippet" : "设置 SFCCurrentStep 在每个 SFC 对象的属性对话框中标记每个 SFC 对象 SFC 设置 选项卡。否则会出现编译错误。 如果 SFC 代码包含宏，则会为每个宏生成单独的可视化效果。单击此可视化项即可将其选中。 例子 生成的 SFC 可视化 有关详细信息，请参阅：For more information, see: 对话框：属性：SFC 设置...", 
"body" : "设置 SFCCurrentStep 在每个 SFC 对象的属性对话框中标记每个 SFC 对象 SFC 设置 选项卡。否则会出现编译错误。 如果 SFC 代码包含宏，则会为每个宏生成单独的可视化效果。单击此可视化项即可将其选中。 例子 生成的 SFC 可视化 有关详细信息，请参阅：For more information, see: 对话框：属性：SFC 设置 " }, 
{ "title" : "参考：命令 ", 
"url" : "_pvg_ref_command.html", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ 参考：命令 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令：生成 SFC\/LD 可视化 ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ 参考：命令 \/ 命令：生成 SFC\/LD 可视化 ", 
"snippet" : "生成 SFC\/LD 可视化 安装后，即可使用此命令 CODESYS POU Visu Generator 附加组件。 象征： 函数 ：如果您的应用程序在实现语言中包含 POU (PRG) 或功能块 (FB) 顺序 功能图 (SFC) 或者 梯子 (LD2) ，然后生成匹配的可视化效果。 打电话 : 项目 菜单 要求 : 那个 CODESYS POU Visu Generator 软件包已安装。 执行命令后，生成的对象存储在 程序组织单元 观点。现在，您可以将这些对象用作模板可视化效果，并使用以下方法将它们嵌入到自己的可视化中 框架 元素或 选项卡 元素。 新生成的可视化可以单独与应用程序并行运...", 
"body" : "生成 SFC\/LD 可视化 安装后，即可使用此命令 CODESYS POU Visu Generator 附加组件。 象征： 函数 ：如果您的应用程序在实现语言中包含 POU (PRG) 或功能块 (FB) 顺序 功能图 (SFC) 或者 梯子 (LD2) ，然后生成匹配的可视化效果。 打电话 : 项目 菜单 要求 : 那个 CODESYS POU Visu Generator 软件包已安装。 执行命令后，生成的对象存储在 程序组织单元 观点。现在，您可以将这些对象用作模板可视化效果，并使用以下方法将它们嵌入到自己的可视化中 框架 元素或 选项卡 元素。 新生成的可视化可以单独与应用程序并行运行，无需开发系统。它可视化应用程序的在线状态，并以彩色突出显示当前程序步骤 " }, 
{ "title" : "使用梯子得出的结果 (LD2) ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html#UUID-81bba28f-b37d-08c9-6ce1-3152446df276_section-idm234680336828288", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ 参考：命令 \/ 命令：生成 SFC\/LD 可视化 \/ 使用梯子得出的结果 (LD2) ", 
"snippet" : "对于程序POU，新生成的可视化结果将以 <FB名称> _LD_VISU 格式显示在 程序组织单元 视图中。 对于子POU，新生成的可视化文件将显示在e 程序组织单元 视图的 LD-Visus 文件夹下，格式为<POU名称> <子POU名称> _LD_VISU 。 子POU 是功能块、动作、属性、方法或过渡。...", 
"body" : "对于程序POU，新生成的可视化结果将以 <FB名称> _LD_VISU 格式显示在 程序组织单元 视图中。 对于子POU，新生成的可视化文件将显示在e 程序组织单元 视图的 LD-Visus 文件夹下，格式为<POU名称> <子POU名称> _LD_VISU 。 子POU 是功能块、动作、属性、方法或过渡。 " }, 
{ "title" : "SFC 的结果 ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html#UUID-81bba28f-b37d-08c9-6ce1-3152446df276_section-idm234680344022971", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ 参考：命令 \/ 命令：生成 SFC\/LD 可视化 \/ SFC 的结果 ", 
"snippet" : "对于 PROGRAM POU 和功能块，新生成的可视化显示在 程序组织单元 以 <POU名称> _SFC_FRAME 格式查看。示例： PLC_PRG_SFC_FRAME 您可以使用框架元素将可视化效果与扩展名为 _SFC_FRAME 集成在一起。如果可视化是从功能块生成的，则函数块实例 fb 在界面编辑器中自动声明。诸如此类的指数 iCurrentIndex 是内部的，是自动设置的。 对于子POU，新生成的可视化文件将显示在 程序组织单元 视图的 SFC-SubVisus 文件夹下，格式为 <POU名称> _SFC_VISU <子POU名称> 。 子POU 是功能块、动作、属性、方法或过渡。...", 
"body" : "对于 PROGRAM POU 和功能块，新生成的可视化显示在 程序组织单元 以 <POU名称> _SFC_FRAME 格式查看。示例： PLC_PRG_SFC_FRAME 您可以使用框架元素将可视化效果与扩展名为 _SFC_FRAME 集成在一起。如果可视化是从功能块生成的，则函数块实例 fb 在界面编辑器中自动声明。诸如此类的指数 iCurrentIndex 是内部的，是自动设置的。 对于子POU，新生成的可视化文件将显示在 程序组织单元 视图的 SFC-SubVisus 文件夹下，格式为 <POU名称> _SFC_VISU <子POU名称> 。 子POU 是功能块、动作、属性、方法或过渡。示例： POU_1_SFC_VISU ， POU_1_SFC_VISU_Step0_to_Init " }, 
{ "title" : "你还需要做什么 ", 
"url" : "_pvg_generate_sfc_ld_visualizations.html#UUID-81bba28f-b37d-08c9-6ce1-3152446df276_section-idm234680345033667", 
"breadcrumbs" : "CODESYS POU Visu Generator \/ 参考：命令 \/ 命令：生成 SFC\/LD 可视化 \/ 你还需要做什么 ", 
"snippet" : "对于 SFC\/LD 功能块，您需要传输相应的实例。 这不是 SFC\/LD 程序所必需的，因为变量是直接使用的。...", 
"body" : "对于 SFC\/LD 功能块，您需要传输相应的实例。 这不是 SFC\/LD 程序所必需的，因为变量是直接使用的。 " }
]
$(document).trigger('search.ready');
});