$(document).ready(function () {indexDict['it'] = [{ "title" : "CODESYS Ethernet Adapter ", 
"url" : "_enad_start_page.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ CODESYS Ethernet Adapter ", 
"snippet" : "Vedere la descrizione generale per informazioni sulle seguenti schede dell'editor del dispositivo. Scheda '<nome dispositivo> Mapping I\/O' Scheda '<nome dispositivo> Oggetti IEC' Scheda '<nome dispositivo> Parametri' Scheda '<nome dispositivo> Stato' Scheda 'Informazioni <nome dispositivo>' Solo in ...", 
"body" : "Vedere la descrizione generale per informazioni sulle seguenti schede dell'editor del dispositivo. Scheda '<nome dispositivo> Mapping I\/O' Scheda '<nome dispositivo> Oggetti IEC' Scheda '<nome dispositivo> Parametri' Scheda '<nome dispositivo> Stato' Scheda 'Informazioni <nome dispositivo>' Solo in caso di funzioni speciali è disponibile un'ulteriore pagina di aiuto separata per l'editor del dispositivo pertinente. Se la scheda \"Parametri <nome dispositivo>\" non viene visualizzata, selezionare il Mostra editor di configurazione del dispositivo generico opzione nel CODESYS opzioni, nel Editor di dispositivi categoria. Per informazioni più generali sul supporto del bus di campo in CODESYS , Vedere: Supporto bus di campo Il CODESYS L'adattatore Ethernet viene utilizzato come nodo padre per i dispositivi che utilizzano protocolli basati su Ethernet. CODESYS attualmente supporta EtherNet\/IP, Modbus e PROFINET IO. Innanzitutto, inserisci l'adattatore Ethernet sotto il controller. Quindi aggiungere il bus di campo basato su Ethernet sotto l'adattatore. " }, 
{ "title" : "Scheda: EtherNet Adapter – Generale ", 
"url" : "_enad_edt_general.html", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Scheda: EtherNet Adapter – Generale ", 
"snippet" : "Oggetto: Adattatore Ethernet Questa scheda definisce le interfacce di rete. Interfaccia di rete : Apre il Schede di rete dialogo. Qui è possibile selezionare gli adattatori Ethernet disponibili sul sistema di destinazione impostato. indirizzo IP Maschera di sottorete Gateway predefinito Impostazioni...", 
"body" : "Oggetto: Adattatore Ethernet Questa scheda definisce le interfacce di rete. Interfaccia di rete : Apre il Schede di rete dialogo. Qui è possibile selezionare gli adattatori Ethernet disponibili sul sistema di destinazione impostato. indirizzo IP Maschera di sottorete Gateway predefinito Impostazioni dell'interfaccia di rete selezionata Regola le impostazioni del sistema operativo Devi confermare di nuovo questa opzione. Nota: le impostazioni sul sistema di destinazione verranno sovrascritte dai valori precedenti. Le impostazioni IP del sistema operativo possono essere modificate da CODESYS runtime solo se consentito nel file di configurazione ( *.cfg ) del tempo di esecuzione. Per questo sono necessarie le seguenti voci: [SysSocket] Adapter.0.Name=\"<adapter name>\" (esempio: \"LAN connection 4\" ) Adapter.0.EnableSetIpAndMask=1 Impostazioni PLC ridondanti (PLC 2) Quando si utilizza una coppia di controller CODESYS ridondanti, queste impostazioni vengono utilizzate sul \"PLC di backup\" ( PLC ID = 2 ) per la scheda di rete. Interfaccia di rete : Apre il Adattatori di rete dialogo. Qui è possibile selezionare gli adattatori Ethernet disponibili sul sistema di destinazione impostato. indirizzo IP Maschera di sottorete Gateway predefinito Impostazioni dell'interfaccia di rete selezionata Le impostazioni per il PLC ridondante sono disponibili solo dopo aver inserito il file Redundancy Configuration oggetto sotto la tua applicazione. " }, 
{ "title" : "Finestra di dialogo: Schede di rete ", 
"url" : "_enad_edt_general.html#UUID-68dc7536-40d9-f126-1da8-b5aefc635b70_id_eb69772dd959aeac0a8640e01875adb_id_98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS Ethernet Adapter \/ Scheda: EtherNet Adapter – Generale \/ Finestra di dialogo: Schede di rete ", 
"snippet" : "Interfacce Mostra una panoramica di tutte le schede di rete disponibili. indirizzo IP Maschera di sottorete Gateway predefinito Questi parametri sono presi dal sistema operativo e non possono essere modificati. Indirizzo MAC Indirizzo MAC dell'adattatore Ethernet...", 
"body" : "Interfacce Mostra una panoramica di tutte le schede di rete disponibili. indirizzo IP Maschera di sottorete Gateway predefinito Questi parametri sono presi dal sistema operativo e non possono essere modificati. Indirizzo MAC Indirizzo MAC dell'adattatore Ethernet " }
]
$(document).trigger('search.ready');
});