$(document).ready(function () {indexDict['es'] = [{ "title" : "CODESYS File-Based Storage ", 
"url" : "_fbstrge_start_page.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ CODESYS File-Based Storage ", 
"snippet" : "Prelanzamiento La versión 0.9.0.0 es la versión preliminar de un producto futuro. Esta versión preliminar es funcional, pero puede contener errores, funciones incompletas o cambios en versiones futuras. No se garantiza la compatibilidad con versiones futuras. Cabe destacar que es posible que se prod...", 
"body" : "Prelanzamiento La versión 0.9.0.0 es la versión preliminar de un producto futuro. Esta versión preliminar es funcional, pero puede contener errores, funciones incompletas o cambios en versiones futuras. No se garantiza la compatibilidad con versiones futuras. Cabe destacar que es posible que se produzcan incompatibilidades, cambios funcionales o la pérdida de funciones en versiones futuras. No se garantiza la corrección de errores, adaptaciones, actualizaciones ni soporte para esta versión preliminar. CODESYS File-Based Storage proporciona un formato de almacenamiento de proyectos alternativo para CODESYS Development System (V3). A diferencia del almacenamiento binario normal de proyectos, los proyectos se almacenan en formato texto en una estructura de carpetas similar a la del árbol de proyectos. Los objetos que no admiten este formato se almacenan en formato XML como antes Puedes descargar el CODESYS File-Based Storage desde CODESYS Store International o CODESYS Store Norteamérica . Allí también encontrará la hoja de datos del producto. El Informe técnico: Almacenamiento basado en archivos CODESYS 0.9.0.0 está disponible para la versión 0.9.0.0. " }, 
{ "title" : "Introducción ", 
"url" : "_fbstrge_introduction.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Introducción ", 
"snippet" : "Lo normal CODESYS El repositorio del proyecto crea un único archivo binario cuyo contenido no puede ser leído ni creado por otras herramientas. CODESYS File-Based Storage , por otro lado, proporciona otro formato de almacenamiento basado en texto. Se crean uno o más archivos de texto para cada objet...", 
"body" : "Lo normal CODESYS El repositorio del proyecto crea un único archivo binario cuyo contenido no puede ser leído ni creado por otras herramientas. CODESYS File-Based Storage , por otro lado, proporciona otro formato de almacenamiento basado en texto. Se crean uno o más archivos de texto para cada objeto del árbol del proyecto, y otros editores de texto pueden leer o incluso crear estos archivos de texto Al crear proyectos a partir de otras herramientas, hay que tener en cuenta que CODESYS La V3 no permite inconsistencias en el proyecto. Es posible que los proyectos con un estado no válido no se puedan abrir El formato de exportación basado en XML se usa para tipos de objetos para los que (todavía) no existe un formato adecuado. CODESYS File-Based Storage trae consigo un conjunto de nuevos comandos que se pueden usar para trabajar con bibliotecas o proyectos basados en archivos. " }, 
{ "title" : "Referencia ", 
"url" : "_fbstrge_reference.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Comandos ", 
"url" : "_fbstrge_struct_reference_commands.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia \/ Comandos ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Comando: Nueva carpeta de proyecto ", 
"url" : "_fbstrge_cmd_new_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia \/ Comandos \/ Comando: Nueva carpeta de proyecto ", 
"snippet" : "Nueva carpeta de proyecto Function : The command opens the New Project dialog for creating a new project and creates a folder <project name>.fbsproj for this project in the storage location of the project. The .auxiliaries and .sidecars folders are created internally in the project folder. Llamar : ...", 
"body" : "Nueva carpeta de proyecto Function : The command opens the New Project dialog for creating a new project and creates a folder <project name>.fbsproj for this project in the storage location of the project. The .auxiliaries and .sidecars folders are created internally in the project folder. Llamar : FBS menú " }, 
{ "title" : "Comando: Abrir carpeta de proyectos ", 
"url" : "_fbstrge_cmd_open_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia \/ Comandos \/ Comando: Abrir carpeta de proyectos ", 
"snippet" : "Abrir carpeta de proyecto Función : El comando abre el explorador de archivos para seleccionar la carpeta del proyecto. Llamar : FBS menú...", 
"body" : "Abrir carpeta de proyecto Función : El comando abre el explorador de archivos para seleccionar la carpeta del proyecto. Llamar : FBS menú " }, 
{ "title" : "Comando: Convertir proyecto ", 
"url" : "_fbstrge_cmd_convert_project.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia \/ Comandos \/ Comando: Convertir proyecto ", 
"snippet" : "Convertir proyecto Función : El comando convierte un CODESYS proyecto en .fbsproj formato. Para ello, primero abre el Navega cuadro de diálogo para seleccionar la carpeta en la que se almacenará el proyecto convertido. A continuación, el Convierta el proyecto en almacenamiento basado en archivos abr...", 
"body" : "Convertir proyecto Función : El comando convierte un CODESYS proyecto en .fbsproj formato. Para ello, primero abre el Navega cuadro de diálogo para seleccionar la carpeta en la que se almacenará el proyecto convertido. A continuación, el Convierta el proyecto en almacenamiento basado en archivos abre el cuadro de diálogo. Este cuadro de diálogo muestra los objetos y dispositivos del proyecto que se convertirán al formato de almacenamiento basado en archivos y comprueba si la conversión es posible sin errores. Los objetos y dispositivos para los que hay advertencias o cuya conversión no es posible sin errores aparecen en la parte derecha del cuadro de diálogo. También se muestran el mensaje de advertencia o error correspondiente y un botón de corrección. Llamar : FBS menú Diálogo: Convertir proyecto a almacenamiento basado en archivos Zona izquierda Dispositivos CODESYS proyecto en el Dispositivos ver POU CODESYS proyecto en POU vista Zona derecha Objeto Objeto para el que se produce un error durante la conversión o para el que hay una advertencia Error Visualización de errores y advertencias Las advertencias son solo informativas. Ejemplo: Hay una gestión de usuarios activa. Esta se perderá durante la conversión. Los errores impiden la conversión. Posibles errores: La descripción del dispositivo no está instalada En el CODESYS árbol del proyecto ( Dispositivos ver o POU vista), hay dos carpetas con el mismo nombre en el mismo nivel. El nombre del objeto tiene más de 255 caracteres. Hay 2 propiedades para la carpeta. Sería suficiente si existiera una propiedad. Arreglar Botón para corregir rápidamente el error. La posibilidad de una solución rápida depende del error en cuestión. " }, 
{ "title" : "Comando: Proyectos recientes ", 
"url" : "_fbstrge_cmd_recent_projects.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia \/ Comandos \/ Comando: Proyectos recientes ", 
"snippet" : "Proyectos recientes Función : El comando muestra los proyectos recientes en *.fbsproj Formato. Haga clic en el proyecto correspondiente para abrirlo. Llamar : FBS menú...", 
"body" : "Proyectos recientes Función : El comando muestra los proyectos recientes en *.fbsproj Formato. Haga clic en el proyecto correspondiente para abrirlo. Llamar : FBS menú " }, 
{ "title" : "Comando: Abrir carpeta en el Explorador de archivos ", 
"url" : "_fbstrge_cmd_open_folder_in_file_explorer.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Referencia \/ Comandos \/ Comando: Abrir carpeta en el Explorador de archivos ", 
"snippet" : "Abrir carpeta en el explorador de archivos Función : El comando abre la carpeta del proyecto. *.fbsproj del proyecto abierto en el explorador de archivos. Llamar : FBS menú...", 
"body" : "Abrir carpeta en el explorador de archivos Función : El comando abre la carpeta del proyecto. *.fbsproj del proyecto abierto en el explorador de archivos. Llamar : FBS menú " }
]
$(document).trigger('search.ready');
});