$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS Modbus ", 
"url" : "_mod_start_page.html", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般描述。 选项卡：<设备名称> I\/O映射 选项卡：<设备名称> IEC对象 选项卡：<设备名称>参数 选项卡：<设备名称>状态 选项卡：<设备名称>信息 仅在具有特殊功能的情况下，才会提供相关设备编辑器的额外单独帮助页面。 如果未显示“<设备名称> 参数”选项卡，则选择 显示通用设备配置视图 选项 CODESYS 选项，在 设备编辑器 类别。 Modbus 网络由一个 Modbus 客户端和一个或多个 Modbus 服务器组成。一个客户端下最多可连接 64 个服务器。Modbus 设备可以通过端口或以太网连接。 Modbus 设备，通过串行端口连接，...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般描述。 选项卡：<设备名称> I\/O映射 选项卡：<设备名称> IEC对象 选项卡：<设备名称>参数 选项卡：<设备名称>状态 选项卡：<设备名称>信息 仅在具有特殊功能的情况下，才会提供相关设备编辑器的额外单独帮助页面。 如果未显示“<设备名称> 参数”选项卡，则选择 显示通用设备配置视图 选项 CODESYS 选项，在 设备编辑器 类别。 Modbus 网络由一个 Modbus 客户端和一个或多个 Modbus 服务器组成。一个客户端下最多可连接 64 个服务器。Modbus 设备可以通过端口或以太网连接。 Modbus 设备，通过串行端口连接，使用 Modbus COM端口 设备。 （1）： CODESYS 运行时充当 Modbus 客户端。 （2）： CODESYS 运行时充当 Modbus 服务器。下文中，此 Modbus 服务器称为“Modbus 设备”。 对于 Modbus 串行，支持操作类型“Modbus RTU(R)”。 Modbus 设备，使用以太网网络连接 以太网适配器 设备。 （3）： CODESYS 运行时充当 Modbus 客户端。 Modbus TCP服务器还可以充当串行 Modbus 服务器的网关。 （4）： CODESYS 运行时充当 Modbus 服务器。 您可以在 Modbus 配置页面中配置通信参数，然后创建 Modbus 通道。Modbus 通道包含单个 Modbus 命令（读\/写数据）以及相应的 I\/O 通道。 " }, 
{ "title" : "支持的功能代码 ", 
"url" : "_mod_start_page.html#UUID-813fc252-d8a4-c4f6-a12e-b9258895f3b0_section-idm4569237926579232594448346888", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus \/ 支持的功能代码 ", 
"snippet" : "如果没有特定的PLC限制，那么客户端一般支持以下功能码： FC01 Read Coils FC02 Read Discrete Inputs FC03 Read Holding Registers FC04 Read Input Registers FC05 Write Single Coil FC15 Write Multiple Coils FC06 Write Single Register FC16 Write Multiple Registers FC23 Read\/Write Multiple Registers...", 
"body" : "如果没有特定的PLC限制，那么客户端一般支持以下功能码： FC01 Read Coils FC02 Read Discrete Inputs FC03 Read Holding Registers FC04 Read Input Registers FC05 Write Single Coil FC15 Write Multiple Coils FC06 Write Single Register FC16 Write Multiple Registers FC23 Read\/Write Multiple Registers " }, 
{ "title" : "从应用程序访问 Modbus 设备 ", 
"url" : "_mod_start_page.html#UUID-813fc252-d8a4-c4f6-a12e-b9258895f3b0_section-idm4679053088411232594449280385", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus \/ 从应用程序访问 Modbus 设备 ", 
"snippet" : "如果您在设备树中插入 Modbus 设备，则会自动创建相应功能块的实例。实例的变量名称与设备树中的设备名称相对应。使用此功能块，您可以从应用程序访问 Modbus 设备的功能。例如，通过此功能块的输出，您可以查询上一个 Modbus 命令的状态（无论成功与否）。 您将在 <设备名称> IEC对象 相应设备编辑器的选项卡。另请参阅此对话框的说明。 对于 Modbus 客户端（RTU(R)\/TCP） 除了配置器中定义的 Modbus 命令（以及隐式生成的 I\/O映射）之外，还可以使用块执行编程的 Modbus 请求 ModbusRequest 。...", 
"body" : "如果您在设备树中插入 Modbus 设备，则会自动创建相应功能块的实例。实例的变量名称与设备树中的设备名称相对应。使用此功能块，您可以从应用程序访问 Modbus 设备的功能。例如，通过此功能块的输出，您可以查询上一个 Modbus 命令的状态（无论成功与否）。 您将在 <设备名称> IEC对象 相应设备编辑器的选项卡。另请参阅此对话框的说明。 对于 Modbus 客户端（RTU(R)\/TCP） 除了配置器中定义的 Modbus 命令（以及隐式生成的 I\/O映射）之外，还可以使用块执行编程的 Modbus 请求 ModbusRequest 。 " }, 
{ "title" : "", 
"url" : "_mod_start_page.html#UUID-813fc252-d8a4-c4f6-a12e-b9258895f3b0_section-idm4638279676419234110046706628", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus \/ ", 
"snippet" : "有关现场总线支持的更多常规信息， CODESYS ，请参阅以下内容： 现场总线支持 Modbus 示例程序...", 
"body" : "有关现场总线支持的更多常规信息， CODESYS ，请参阅以下内容： 现场总线支持 Modbus 示例程序 " }, 
{ "title" : "客户 ", 
"url" : "_mod_f_master.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "配置 ", 
"url" : "_mod_f_master_configuration.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "选项卡：Modbus 串行端口–通用 ", 
"url" : "_mod_edt_com_port.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡：Modbus 串行端口–通用 ", 
"snippet" : "Modbus 串行端口配置器中的选项卡包括通过串行端口进行通信的基本设置。 端口，配置 COM端口 串口端口 波特率 端口参数 奇偶校验 数据位 停止位...", 
"body" : "Modbus 串行端口配置器中的选项卡包括通过串行端口进行通信的基本设置。 端口，配置 COM端口 串口端口 波特率 端口参数 奇偶校验 数据位 停止位 " }, 
{ "title" : "选项卡：Modbus 串行客户端 -通用 ", 
"url" : "_mod_edt_master_com.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡：Modbus 串行客户端 -通用 ", 
"snippet" : "该选项卡包括 Modbus 通信的基本设置。 Modbus RTU\/ASCII 传输模式 RTU(R) ：以二进制形式传输 ASCII ：以 ASCII 码传输（目前并非所有驱动程序都支持） 响应超时(ms) 客户端等待服务器节点响应的时间间隔。如果节点在此时间范围内未响应，则会向隐式服务器功能块发出错误。为该时间范围指定的值也是每个节点的默认值。对于每个节点，您仍然可以在其服务器配置中设置特定值。 帧间隔时间(ms) 帧之间的时间是客户端在上一个响应（以及超时）和下一个请求之间的发送暂停时间。使用此参数可以降低通信中断的可能性。 自动重启通信 ：发生通信错误后， CODESYS 自动确认错误...", 
"body" : "该选项卡包括 Modbus 通信的基本设置。 Modbus RTU\/ASCII 传输模式 RTU(R) ：以二进制形式传输 ASCII ：以 ASCII 码传输（目前并非所有驱动程序都支持） 响应超时(ms) 客户端等待服务器节点响应的时间间隔。如果节点在此时间范围内未响应，则会向隐式服务器功能块发出错误。为该时间范围指定的值也是每个节点的默认值。对于每个节点，您仍然可以在其服务器配置中设置特定值。 帧间隔时间(ms) 帧之间的时间是客户端在上一个响应（以及超时）和下一个请求之间的发送暂停时间。使用此参数可以降低通信中断的可能性。 自动重启通信 ：发生通信错误后， CODESYS 自动确认错误并尝试继续执行Modbus命令。 ：必须在服务器功能块中明确确认错误。 " }, 
{ "title" : "选项卡： Modbus TCP客户端 –通用 ", 
"url" : "_mod_edt_master_tcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡： Modbus TCP客户端 –通用 ", 
"snippet" : "该选项卡包含网络中网络通信的基本设置。 Modbus TCP 响应超时（毫秒） 客户端等待服务器节点响应的时间间隔（以毫秒为单位）。如果节点在此时间范围内未响应，则会向隐式服务器功能块发出错误。指定的时间范围值也是每个节点的默认值。对于每个节点，您仍然可以在其Modbus TCP服务器配置中设置特定值。 自动重连 ：客户端始终尝试自动重新建立中断的连接。此时，会自动确认服务器的错误。如果发生 TCP 错误，也会自动确认服务器子设备的错误。...", 
"body" : "该选项卡包含网络中网络通信的基本设置。 Modbus TCP 响应超时（毫秒） 客户端等待服务器节点响应的时间间隔（以毫秒为单位）。如果节点在此时间范围内未响应，则会向隐式服务器功能块发出错误。指定的时间范围值也是每个节点的默认值。对于每个节点，您仍然可以在其Modbus TCP服务器配置中设置特定值。 自动重连 ：客户端始终尝试自动重新建立中断的连接。此时，会自动确认服务器的错误。如果发生 TCP 错误，也会自动确认服务器子设备的错误。 " }, 
{ "title" : "选项卡：Modbus 串行服务器 –通用 ", 
"url" : "_mod_edt_slave_com.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡：Modbus 串行服务器 –通用 ", 
"snippet" : "该选项卡包括通过串行端口进行通信的基本设置。 Modbus RTU\/ASCII 服务器地址[1..247] 串行 Modbus 设备的地址（值介于 1 和 247 之间） 响应超时(ms) 客户端等待服务器节点响应的时间间隔。该时间间隔专门针对此服务器节点配置，并覆盖相应客户端的常规响应超时设置。...", 
"body" : "该选项卡包括通过串行端口进行通信的基本设置。 Modbus RTU\/ASCII 服务器地址[1..247] 串行 Modbus 设备的地址（值介于 1 和 247 之间） 响应超时(ms) 客户端等待服务器节点响应的时间间隔。该时间间隔专门针对此服务器节点配置，并覆盖相应客户端的常规响应超时设置。 " }, 
{ "title" : "选项卡： Modbus TCP服务器 –通用 ", 
"url" : "_mod_edt_slave_tcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡： Modbus TCP服务器 –通用 ", 
"snippet" : "该选项卡包含网络中网络通信的基本设置。 Modbus TCP 服务器IP地址 响应超时(ms) 客户端等待此服务器响应的时间间隔。该时间间隔专门为此服务器节点配置，并覆盖相应客户端的常规响应超时设置。 端口 服务器的端口号 (TCP\/IP)。Modbus 默认端口为 502 以下参数仅在设备描述中定义时才可用。 启用备用IP ：解锁第二个连接的 IP 地址和其他配置选项 第二个服务器IP地址 第二个连接的 IP 地址 最喜欢的台词 没有任何 ：当活动连接终止时，驱动程序会尝试切换到非活动连接（如果可能）。当原始连接恢复时，不会切换回非活动连接。 1号线 ， 2号线 ：指定的连接具有优先权。这意...", 
"body" : "该选项卡包含网络中网络通信的基本设置。 Modbus TCP 服务器IP地址 响应超时(ms) 客户端等待此服务器响应的时间间隔。该时间间隔专门为此服务器节点配置，并覆盖相应客户端的常规响应超时设置。 端口 服务器的端口号 (TCP\/IP)。Modbus 默认端口为 502 以下参数仅在设备描述中定义时才可用。 启用备用IP ：解锁第二个连接的 IP 地址和其他配置选项 第二个服务器IP地址 第二个连接的 IP 地址 最喜欢的台词 没有任何 ：当活动连接终止时，驱动程序会尝试切换到非活动连接（如果可能）。当原始连接恢复时，不会切换回非活动连接。 1号线 ， 2号线 ：指定的连接具有优先权。这意味着，在连接断开后，系统会每隔一定时间间隔尝试切换回此线路。这些时间间隔可以通过库参数进行配置。 保持双线连接 ：非活动线路上的连接也会保持。通过发送读取命令定期检查连接是否可用。这些间隔可以通过库参数配置。 ：只维持活动连接，即换线时必须先建立连接。 当前活动线路和 CommunicationState 非活动线路可以通过读取 usiActiveLine 和 ComStateBackup Modbus TCP服务器隐式生成的 FB 实例的输出。 可以在运行时使用以下方式更改通信设置： 方法：UpdateCommunicationSettings方法。该方法适用于此 Modbus 服务器隐式生成的 FB。 当 启用备用IP 选项被选中时， 方法：UpdateCommunicationSettings方法没有效果。 " }, 
{ "title" : "选项卡： Modbus服务器通道 ", 
"url" : "_mod_edt_slave_com_channel.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡： Modbus服务器通道 ", 
"snippet" : "您可以使用此选项卡来定义服务器通道。 每个通道代表一个 Modbus 请求。 添加通道 打开 Modbus通道 对话框。您可以在此处为当前 Modbus 服务器创建新通道。在 Modbus 服务器的设备描述文件中，您可以预定义单个 Modbus 寄存器或整个通道的描述。...", 
"body" : "您可以使用此选项卡来定义服务器通道。 每个通道代表一个 Modbus 请求。 添加通道 打开 Modbus通道 对话框。您可以在此处为当前 Modbus 服务器创建新通道。在 Modbus 服务器的设备描述文件中，您可以预定义单个 Modbus 寄存器或整个通道的描述。 " }, 
{ "title" : "对话框： Modbus通道 ", 
"url" : "_mod_edt_slave_com_channel.html#UUID-99c4b381-a91c-94f1-fef0-ddac4ca2760a_id_e8de9c86ef0c4970c0a8640e0169f254_id_f91c8836fa101007c0a8640e0143e473", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡： Modbus服务器通道 \/ 对话框： Modbus通道 ", 
"snippet" : "通道 姓名 包含频道名称的字符串 访问类型 Read Coils（功能代码 01） Read Discrete Inputs（功能代码 02） Read Holding Registers（功能代码03） Read Input Registers（功能代码04） Read Single Coil（功能代码05） Write Single Register（功能代码06） Write Multiple Coils（功能代码 15） Write Multiple Registers（功能代码 16） Read\/Write Multiple Registers（功能代码 23） 触发器 循环 ：该请...", 
"body" : "通道 姓名 包含频道名称的字符串 访问类型 Read Coils（功能代码 01） Read Discrete Inputs（功能代码 02） Read Holding Registers（功能代码03） Read Input Registers（功能代码04） Read Single Coil（功能代码05） Write Single Register（功能代码06） Write Multiple Coils（功能代码 15） Write Multiple Registers（功能代码 16） Read\/Write Multiple Registers（功能代码 23） 触发器 循环 ：该请求定期发生。 上升沿 ：该请求是对布尔触发器变量上升沿的响应。触发器变量定义在 I\/O映射 选项卡。 应用 ：Modbus 请求由 PLC 应用程序触发。这是通过 功能块： ModbusChannel，包含在相应的 I\/O 驱动程序库中。该功能块提供对此命令执行的完整控制和信息，例如启动时间、处理时间和结果。 循环时间（毫秒） 对于触发器= 循环 ：请求间隔 注意：请求间隔应与应用程序的周期时间相同或其倍数。 评论 频道描述 读寄存器 偏移 读取开始的起始地址（值范围 0–65535） 长度 需要读取的寄存器数量（用于字访问）或需要读取的离散输入数量（用于位访问） 错误处理 定义发生通信错误时数据应如何处理 保留最后一个值 设置为零 写寄存器 偏移 待写入寄存器的编号（值范围0–65535） 长度 需要写入的寄存器数量（=字） 该参数的取值范围由功能码决定。 读取线圈和离散输入\/将线圈写入重叠寄存器存储器 这 CODESYS MODBUS I\/O 驱动程序允许读取线圈和离散输入，以及将线圈写入重叠寄存器内存（ 离散点区域 如果未选中复选框，则读取或写入的前 8 位与相应寄存器的高字节对齐（%IB0），而读取或写入的后 8 位与相应寄存器的低字节对齐（LSB 在前）。 例子 在以下示例中，第一行定义了一个组合读\/写操作（功能代码 23）。它从偏移量为 0 的保持寄存器中读取一个字。 16#0001 并将两个字写入偏移寄存器 16#0003 。一旦触发器变量在 I\/O映射 标签显示上升沿。 " }, 
{ "title" : "选项卡： Modbus服务器初始化 ", 
"url" : "_mod_edt_slave_com_init.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡： Modbus服务器初始化 ", 
"snippet" : "您可以使用此选项卡来定义初始化命令。 启动总线或激活服务器（设置服务器实例的“Enabled”标志）时，初始化命令执行一次。 设置或编辑服务器初始值时，相应的对话框中提供以下参数： 上移 下移 通道的顺序也决定了初始化的顺序。 新的 打开 初始值 对话框。初始化命令已定义。...", 
"body" : "您可以使用此选项卡来定义初始化命令。 启动总线或激活服务器（设置服务器实例的“Enabled”标志）时，初始化命令执行一次。 设置或编辑服务器初始值时，相应的对话框中提供以下参数： 上移 下移 通道的顺序也决定了初始化的顺序。 新的 打开 初始值 对话框。初始化命令已定义。 " }, 
{ "title" : "对话框：初始值 ", 
"url" : "_mod_edt_slave_com_init.html#UUID-858dc378-b63e-7e25-35e5-9fca05de0cb5_id_fa026065ef0c7c92c0a8640e000566e4_id_24182416aaae11e393b286effee11a64", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 配置 \/ 选项卡： Modbus服务器初始化 \/ 对话框：初始值 ", 
"snippet" : "访问类型 Write Single Coil（功能代码05） Write Single Register（功能代码06） Write Multiple Coils（功能代码 15） Write Multiple Registers（功能代码 16） 寄存器偏移 待写入寄存器的编号（值范围0–65535） 长度 需要写入的寄存器数量（=字） 该参数的取值范围由功能码决定。 初始化 寄存器的初始值 评论 数据简短描述...", 
"body" : "访问类型 Write Single Coil（功能代码05） Write Single Register（功能代码06） Write Multiple Coils（功能代码 15） Write Multiple Registers（功能代码 16） 寄存器偏移 待写入寄存器的编号（值范围0–65535） 长度 需要写入的寄存器数量（=字） 该参数的取值范围由功能码决定。 初始化 寄存器的初始值 评论 数据简短描述 " }, 
{ "title" : "功能 ", 
"url" : "_mod_client_functions.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 功能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "TCP客户端冗余 ", 
"url" : "_mod_client_redundancy.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 功能 \/ TCP客户端冗余 ", 
"snippet" : "为了提高系统的可用性，您可以使用带有冗余Modbus TCP客户端的第二个控制器，并结合 CODESYS Redundancy 。 这 CODESYS Redundancy 充当“后端”，同步两个控制器上的应用程序。原生Modbus系统冗余（SR）确保与现场设备的数据交换顺畅。 Modbus TCP客户端 CODESYS Redundancy 通过 冗余管理器 功能块来自 IoDrvModbusTCP 图书馆。...", 
"body" : "为了提高系统的可用性，您可以使用带有冗余Modbus TCP客户端的第二个控制器，并结合 CODESYS Redundancy 。 这 CODESYS Redundancy 充当“后端”，同步两个控制器上的应用程序。原生Modbus系统冗余（SR）确保与现场设备的数据交换顺畅。 Modbus TCP客户端 CODESYS Redundancy 通过 冗余管理器 功能块来自 IoDrvModbusTCP 图书馆。 " }, 
{ "title" : "用法 ", 
"url" : "_mod_client_redundancy.html#UUID-0812546d-012d-898c-c88e-3b900f1eda1d_section-idm4520238175380833428668771124", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 功能 \/ TCP客户端冗余 \/ 用法 ", 
"snippet" : "对于使用的每个 TCP 客户端，您需要创建一个 RedundancyManager 功能块中非同步数据区域，例如全局变量列表。此外，还需要添加 DataSyncAlways 运行时系统配置文件中的条目（ *.cfg ) 以便在每个周期开始时同步数据。 [CmpRedundancy] DataSyncAlways=1...", 
"body" : "对于使用的每个 TCP 客户端，您需要创建一个 RedundancyManager 功能块中非同步数据区域，例如全局变量列表。此外，还需要添加 DataSyncAlways 运行时系统配置文件中的条目（ *.cfg ) 以便在每个周期开始时同步数据。 [CmpRedundancy]\nDataSyncAlways=1 " }, 
{ "title" : "行为 ", 
"url" : "_mod_client_redundancy.html#UUID-0812546d-012d-898c-c88e-3b900f1eda1d_section-idm4512096403710433428678152475", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 功能 \/ TCP客户端冗余 \/ 行为 ", 
"snippet" : "即使 RedundancyManager 使用功能块时，不执行切换或同步操作 CODESYS Modbus . Modbus 通信仅对相应控制器的冗余状态做出反应。 当两个控制器之间现有的冗余链路运行时，Modbus 通信仅通过主控制器运行。当主控制器切换时，当前从属控制器的 Modbus 通信将终止，并在当前主控制器上建立。 当系统初始启动时没有冗余链路，Modbus 通信仅通过 ID 为 1 的控制器建立。 如果在运行模式下冗余链路丢失，则两个控制器上的 Modbus 通信都将处于活动状态。此功能块无法处理由此导致的任何问题，例如重复通信。...", 
"body" : "即使 RedundancyManager 使用功能块时，不执行切换或同步操作 CODESYS Modbus . Modbus 通信仅对相应控制器的冗余状态做出反应。 当两个控制器之间现有的冗余链路运行时，Modbus 通信仅通过主控制器运行。当主控制器切换时，当前从属控制器的 Modbus 通信将终止，并在当前主控制器上建立。 当系统初始启动时没有冗余链路，Modbus 通信仅通过 ID 为 1 的控制器建立。 如果在运行模式下冗余链路丢失，则两个控制器上的 Modbus 通信都将处于活动状态。此功能块无法处理由此导致的任何问题，例如重复通信。 " }, 
{ "title" : "图书馆 ", 
"url" : "_mod_f_master_libraries.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "功能块： IoDrvModbusComPort ", 
"url" : "_mod_lib_iodrvmodbuscomport.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： IoDrvModbusComPort ", 
"snippet" : "图书馆： IoDrvModbus 该块是为设备树中的每个串行 Modbus 客户端生成的。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xStop Bool FALSE 如果 TRUE ，则每个对服务器的新请求都会被停止。如果 FALSE ，该过程继续。 xAcknowledge Bool FALSE 立即关闭并打开上升沿的COM端口 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 uiNumberOfCommunicatingSlaves int 0 显示通信服务器的数量 xAllSlavesOk Bool FALSE TRUE 如果所有服务器都通信。 FALSE ...", 
"body" : "图书馆： IoDrvModbus 该块是为设备树中的每个串行 Modbus 客户端生成的。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xStop Bool FALSE 如果 TRUE ，则每个对服务器的新请求都会被停止。如果 FALSE ，该过程继续。 xAcknowledge Bool FALSE 立即关闭并打开上升沿的COM端口 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 uiNumberOfCommunicatingSlaves int 0 显示通信服务器的数量 xAllSlavesOk Bool FALSE TRUE 如果所有服务器都通信。 FALSE 如果某些服务器出现错误。 " }, 
{ "title" : "功能块： IoDrvModbusTCP ", 
"url" : "_mod_lib_iodrvmodbustcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： IoDrvModbusTCP ", 
"snippet" : "图书馆： IoDrvModbusTCP 该块是为设备树中的每个 Modbus 客户端 TCP 生成的。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xStop Bool FALSE 停止所有 TCP\/IP 通信 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xSlaveError Bool FALSE 表示服务器 FB 存在错误。 uiConnectedSlaves UINT 0 通过 TCP\/IP 连接的服务器数量...", 
"body" : "图书馆： IoDrvModbusTCP 该块是为设备树中的每个 Modbus 客户端 TCP 生成的。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xStop Bool FALSE 停止所有 TCP\/IP 通信 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xSlaveError Bool FALSE 表示服务器 FB 存在错误。 uiConnectedSlaves UINT 0 通过 TCP\/IP 连接的服务器数量 " }, 
{ "title" : "功能块： ModbusRequest ", 
"url" : "_mod_lib_modbusrequest.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： ModbusRequest ", 
"snippet" : "图书馆： IoDrvModbusTCP 除了在 Modbus服务器通道 选项卡中，此功能块允许在应用程序中动态执行其他命令。但是，对于这些通过编程创建的命令，没有 I\/O映射，只有以下类型的输入\/输出数据范围 ARRAY OF BYTE 或者 ARRAY OF WORD 。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 Slave ModbusTCPSlave xExecute BOOL 上升沿：动作开始。 下降沿：如果在功能块结束操作之前发生下降沿，则输出将复位。输出将照常运行，并且仅在操作结束或中止时复位（ xAbort )，或者发生错误。在这种情况下，相应的输出值（ xDon...", 
"body" : "图书馆： IoDrvModbusTCP 除了在 Modbus服务器通道 选项卡中，此功能块允许在应用程序中动态执行其他命令。但是，对于这些通过编程创建的命令，没有 I\/O映射，只有以下类型的输入\/输出数据范围 ARRAY OF BYTE 或者 ARRAY OF WORD 。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 Slave ModbusTCPSlave xExecute BOOL 上升沿：动作开始。 下降沿：如果在功能块结束操作之前发生下降沿，则输出将复位。输出将照常运行，并且仅在操作结束或中止时复位（ xAbort )，或者发生错误。在这种情况下，相应的输出值（ xDone ， xError ， iError ) 在输出端存在恰好一个周期。 xAbort BOOL TRUE ：操作立即中止，所有输出均设置为其初始值。 usiUnitID UINT 16#FF 单元 ID 仅用于转发（网关）到 Modbus 串行总线。 对于 TCP\/IP 协议，MODBUS 服务器通过 IP 地址寻址。在这种情况下，不使用 MODBUS 单元 ID（必须使用值 0xFF）。 对于串行连接，Modbus 设备的单元 ID 寻址范围为 1 至 247（0 用于广播地址）。 ModbusCommand ModbusCommand 要执行的 Modbus 命令。支持位和字访问的功能块。 pSendData POINTER TO BYTE 指向包含发送到服务器的数据的缓冲区的指针。 对于寄存器访问，缓冲区的类型为 Array[0..ModbusCommand.uiWriteLen - 1] OF WORD 。对于位访问，缓冲区的类型为 ARRAY[0..ModbusCommand.uiWriteLen \/ 8] OF BYTE 。 pRecvData POINTER TO BYTE 指向缓冲区的指针，服务器接收到的数据写入该缓冲区。 对于寄存器访问，缓冲区的类型为 ARRAY[0..ModbusCommand.uiReadLen - 1] OF WORD 。对于位访问，缓冲区的类型为 ARRAY[0..ModbusCommand.uiReadLen \/ 8] OF BYTE 。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xDone BOOL FALSE TRUE 如果请求成功结束 xBusy BOOL FALSE TRUE 请求正在处理中 xError BOOL FALSE TRUE 如果请求因错误而结束 xAborted BOOL FALSE TRUE 当用户中止请求时 ModbusError MB_ErrorCodes 当前错误；定义在 MB_ErrorCodes 枚举。 " }, 
{ "title" : "功能块： ModbusSlaveComPort ", 
"url" : "_mod_lib_modbusslavecomport.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： ModbusSlaveComPort ", 
"snippet" : "图书馆： IoDrvModbus 此功能块针对设备树中的每个串行 Modbus 服务器生成。此功能块表示与单个 Modbus 串行服务器的逻辑连接。为此设备定义的通道在后台处理。此功能块的输入和输出为用户提供状态信息，并允许确认发生的错误（以便继续处理）。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xTrigger Bool FALSE 触发所有已配置的 Modbus 通道的上升沿传输 xReset Bool FALSE 重新启动通信并重置 xError 和 byModbusError xAcknowledge Bool FALSE 重新启动通信并且不重置 xError 和 b...", 
"body" : "图书馆： IoDrvModbus 此功能块针对设备树中的每个串行 Modbus 服务器生成。此功能块表示与单个 Modbus 串行服务器的逻辑连接。为此设备定义的通道在后台处理。此功能块的输入和输出为用户提供状态信息，并允许确认发生的错误（以便继续处理）。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xTrigger Bool FALSE 触发所有已配置的 Modbus 通道的上升沿传输 xReset Bool FALSE 重新启动通信并重置 xError 和 byModbusError xAcknowledge Bool FALSE 重新启动通信并且不重置 xError 和 byModbusError 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xInitDone Bool FALSE 所有初始化命令均已重置。 xError Bool FALSE TRUE 如果发生任何错误。与该服务器的通信将中断。 byModbusError MB_ErrorCodes 0 当前错误定义在 MB_ErrorCodes 枚举 " }, 
{ "title" : "功能块： ModbusTCPSlave ", 
"url" : "_mod_lib_modbustcpslave.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： ModbusTCPSlave ", 
"snippet" : "图书馆： IoDrvModbusTCP 此块针对设备树中的每个 Modbus 服务器 TCP 生成。此功能块表示与单个Modbus TCP服务器的 TCP\/IP 连接。为此设备定义的通道在后台处理。此块的输入和输出为用户提供状态信息，并允许用户确认发生的错误（以便继续处理）。 Enable 属性用于启动和停止通信。 这 Enable 属性仅在 启用设备诊断 选项被选中 PLC 设置 选项卡。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xConfirmError Bool FALSE 该过程随着上升沿继续进行。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xIni...", 
"body" : "图书馆： IoDrvModbusTCP 此块针对设备树中的每个 Modbus 服务器 TCP 生成。此功能块表示与单个Modbus TCP服务器的 TCP\/IP 连接。为此设备定义的通道在后台处理。此块的输入和输出为用户提供状态信息，并允许用户确认发生的错误（以便继续处理）。 Enable 属性用于启动和停止通信。 这 Enable 属性仅在 启用设备诊断 选项被选中 PLC 设置 选项卡。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 xConfirmError Bool FALSE 该过程随着上升沿继续进行。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xInitDone Bool FALSE 显示通信服务器的数量 xBusy Bool FALSE TRUE 正在处理请求时 xDone Bool FALSE TRUE 如果请求成功结束 xError Bool FALSE TRUE 如果请求因错误而结束 byModbusError MB_ErrorCodes 指定枚举中定义的当前错误 MB_ErrorCodes ComSettings ModbusTCPCommSettings 当前配置的通信设置 xConfirmError Bool False 该过程随着上升沿继续进行。 " }, 
{ "title" : "方法：UpdateCommunicationSettings ", 
"url" : "_mod_lib_modbustcpslave.html#UUID-5feb1626-d39e-e3de-4fd6-695c4e431625_section-idm43285377749268", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： ModbusTCPSlave \/ 方法：UpdateCommunicationSettings ", 
"snippet" : "仅当服务器设置为“停止”时，才可以更新通信参数。 Enable 属性用于停止和启动服务器。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 ipAdress ARRAY [0..3] OF BYTE 服务器的IP地址 uiPort UINT 服务器端口 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 UpdateCommunicationSettings UDINT 如果存在 TCP 连接，则会导致错误（返回值 != 0）...", 
"body" : "仅当服务器设置为“停止”时，才可以更新通信参数。 Enable 属性用于停止和启动服务器。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 ipAdress ARRAY [0..3] OF BYTE 服务器的IP地址 uiPort UINT 服务器端口 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 UpdateCommunicationSettings UDINT 如果存在 TCP 连接，则会导致错误（返回值 != 0） " }, 
{ "title" : "功能块： ModbusChannel ", 
"url" : "_mod_lib_modbuschannel.html", 
"breadcrumbs" : "CODESYS Modbus \/ 客户 \/ 图书馆 \/ 功能块： ModbusChannel ", 
"snippet" : "图书馆： IoDrvModbus 此功能块启动单个配置的 Modbus 通道的执行。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 Slave ModbusSlaveComPort xExecute BOOL 上升沿：动作开始。 下降沿：如果在功能块结束操作之前发生下降沿，则输出将复位。输出将照常运行，并且仅在操作结束或中止时复位（ xAbort )，或者发生错误。在这种情况下，相应的输出值（ xDone ， xError ， iError ) 在输出端存在恰好一个周期。 xAbort BOOL TRUE ：操作立即中止，所有输出均设置为其初始值。 iChannelIndex IN...", 
"body" : "图书馆： IoDrvModbus 此功能块启动单个配置的 Modbus 通道的执行。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 Slave ModbusSlaveComPort xExecute BOOL 上升沿：动作开始。 下降沿：如果在功能块结束操作之前发生下降沿，则输出将复位。输出将照常运行，并且仅在操作结束或中止时复位（ xAbort )，或者发生错误。在这种情况下，相应的输出值（ xDone ， xError ， iError ) 在输出端存在恰好一个周期。 xAbort BOOL TRUE ：操作立即中止，所有输出均设置为其初始值。 iChannelIndex INT 要执行的通道索引。无效的索引会导致 xError = TRUE （没有 Modbus 特定的错误代码）。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xDone BOOL FALSE TRUE 如果请求成功结束 xBusy BOOL FALSE TRUE 请求正在处理中 xError BOOL FALSE TRUE 如果请求因错误而结束 xAborted BOOL FALSE TRUE 当用户中止请求时 ModbusError MB_ErrorCodes 当前错误；定义在 MB_ErrorCodes 枚举。 " }, 
{ "title" : "设备 ", 
"url" : "_mod_f_slave_device.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "配置 ", 
"url" : "_mod_f_device_configuration.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 配置 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "选项卡：Modbus 串行设备 –通用 ", 
"url" : "_mod_edt_slave_device_com.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 配置 \/ 选项卡：Modbus 串行设备 –通用 ", 
"snippet" : "该选项卡包含网络中网络通信的基本设置。 单元 服务器的单元 看门狗 ：激活看门狗功能。 当 Modbus 设备未收到来自客户端的任何有效查询时，传入数据（保持寄存器\/%I 范围）将设置为零。 保持寄存器(%IW) 保持寄存器的数量：可能值：1–4096。最大数量可在设备描述中限制。 可写 ： ：对于保持寄存器，将生成可写 I\/O 映射（%QW 地址），而不是只读 I\/O 映射（%IW 地址）。这允许 Modbus 设备应用程序（= 服务器应用程序）通过常规 I\/O映射来设置保持寄存器。 输入寄存器(%QW) 输入寄存器的数量：可能值：1–4096。最大数量可在设备描述中限制。 输入\/输出组件大...", 
"body" : "该选项卡包含网络中网络通信的基本设置。 单元 服务器的单元 看门狗 ：激活看门狗功能。 当 Modbus 设备未收到来自客户端的任何有效查询时，传入数据（保持寄存器\/%I 范围）将设置为零。 保持寄存器(%IW) 保持寄存器的数量：可能值：1–4096。最大数量可在设备描述中限制。 可写 ： ：对于保持寄存器，将生成可写 I\/O 映射（%QW 地址），而不是只读 I\/O 映射（%IW 地址）。这允许 Modbus 设备应用程序（= 服务器应用程序）通过常规 I\/O映射来设置保持寄存器。 输入寄存器(%QW) 输入寄存器的数量：可能值：1–4096。最大数量可在设备描述中限制。 输入\/输出组件大小的变化会直接影响 I\/O映射中可配置参数的数量。 Modbus 为 I\/O 数据定义了一个包含四个区域的数据模型。 线圈：输出类型 BIT 离散输入：输入类型 BYTE 保持寄存器：输出类型 WORD （16位） 输入寄存器：输入类型 WORD （16位） 与所有现场总线一样，Modbus 也包含输入和输出，但从“主机”的角度来看。这些数据区具有制造商定义的任意数量的逻辑起始偏移量。Modbus 数据区背后的 I\/O 数据可以重叠，也可以相互独立。 有关 Modbus 数据模型的详细信息，请参阅第 4.3 章和第 4.4 章中的 Modbus 协议规范（ www.modbus.org ）。 在 CODESYS Modbus 设备、输入寄存器和离散量输入，以及保持寄存器和线圈，都映射到相同的 I\/O 数据。当它们通过不同的逻辑起始偏移量进行寻址时，情况也是如此。 起始地址 线圈 定义各个 Modbus 数据区的起始地址 离散输入 保持寄存器 输入寄存器 " }, 
{ "title" : "选项卡： Modbus TCP服务器设备 –通用 ", 
"url" : "_mod_edt_slave_device_tcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 配置 \/ 选项卡： Modbus TCP服务器设备 –通用 ", 
"snippet" : "该选项卡包含网络中网络通信的基本设置。 配置参数 看门狗 ：激活看门狗功能。 当 Modbus 设备未收到来自客户端的任何有效查询时，传入数据（保持寄存器\/%I 范围）将设置为零。 关闭 TCP 套接字 ：如果启用看门狗并且超过设定的时间，则TCP套接字将被关闭。 服务器端口 服务器的端口号 绑定到适配器 此选项与具有多个以太网适配器的系统相关。 ：Modbus 服务器的服务器套接字与指定以太网适配器的 IP 地址绑定。仅接收发送到此 IP 地址的 Modbus 请求。 ：Modbus 服务器的服务器套接字未绑定到 IP 地址。系统（在 Modbus端口）接收到所有 Modbus 请求后，系统...", 
"body" : "该选项卡包含网络中网络通信的基本设置。 配置参数 看门狗 ：激活看门狗功能。 当 Modbus 设备未收到来自客户端的任何有效查询时，传入数据（保持寄存器\/%I 范围）将设置为零。 关闭 TCP 套接字 ：如果启用看门狗并且超过设定的时间，则TCP套接字将被关闭。 服务器端口 服务器的端口号 绑定到适配器 此选项与具有多个以太网适配器的系统相关。 ：Modbus 服务器的服务器套接字与指定以太网适配器的 IP 地址绑定。仅接收发送到此 IP 地址的 Modbus 请求。 ：Modbus 服务器的服务器套接字未绑定到 IP 地址。系统（在 Modbus端口）接收到所有 Modbus 请求后，系统都会进行处理。 保持寄存器(%IW) 保持寄存器的数量：可能值：1–4096。最大数量可在设备描述中限制。 可写 ： ：对于保持寄存器，将生成可写 I\/O 映射（%QW 地址），而不是只读 I\/O 映射（%IW 地址）。这允许 Modbus 设备应用程序（= 服务器应用程序）通过常规 I\/O映射来设置保持寄存器。 输入寄存器(%QW) 输入寄存器的数量：可能值：1–4096。最大数量可在设备描述中限制。 离散点区域 Modbus 线圈和离散量输入拥有各自的数据区。默认情况下，寄存器访问和位访问使用相同的 Modbus 数据。 线圈 Modbus线圈数量 离散输入 Modbus离散输入数量 输入\/输出组件大小的变化会直接影响 I\/O映射中可配置参数的数量。 数据模型 Modbus 为 I\/O 数据定义了一个包含四个区域的数据模型。 线圈：BIT 类型的输出 离散输入：BYTE 类型的输入 保持寄存器：WORD 类型输出（16 位） 输入寄存器：WORD 类型输入（16 位） 与所有现场总线一样，Modbus 也包含输入和输出，但从“主机”的角度来看。这些数据区具有制造商定义的任意数量的逻辑起始偏移量。Modbus 数据区背后的 I\/O 数据可以重叠，也可以相互独立。 有关 Modbus 数据模型的详细信息，请参阅第 4.3 章和第 4.4 章中的 Modbus 协议规范（ www.modbus.org ）。 在 CODESYS Modbus 设备、输入寄存器和离散量输入，以及保持寄存器和线圈，都映射到相同的 I\/O 数据。当它们通过不同的逻辑起始偏移量进行寻址时，情况也是如此。 线圈 定义各个 Modbus 数据区的起始地址 离散输入 保持寄存器 输入寄存器 保持和输入寄存器数据区域覆盖 ：通过保持和输入寄存器覆盖过程图像。 例如，当使用服务器应用程序写入保持寄存器时，这是必需的。 " }, 
{ "title" : "选项卡： Modbus TCP服务器设备 –串口网关 ", 
"url" : "_mod_edt_slave_serial_gateway.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 配置 \/ 选项卡： Modbus TCP服务器设备 –串口网关 ", 
"snippet" : "此功能不包含在Modbus TCP服务器的标准许可证范围内。Modbus 串行客户端也需要获得许可证。 该选项卡包含将设备扩展为串行Modbus TCP\/ RTU(R)网关的设置。Modbus Modbus TCP服务器随后将 TCP 客户端的请求转发到连接到 PLC 本地COM端口的 Modbus RTU(R)服务器。 串口网关激活 ：设备中的 TCP\/ RTU(R)网关功能已启用。 COM端口 使用的COM端口号 波特率 传输速率（波特）...", 
"body" : "此功能不包含在Modbus TCP服务器的标准许可证范围内。Modbus 串行客户端也需要获得许可证。 该选项卡包含将设备扩展为串行Modbus TCP\/ RTU(R)网关的设置。Modbus Modbus TCP服务器随后将 TCP 客户端的请求转发到连接到 PLC 本地COM端口的 Modbus RTU(R)服务器。 串口网关激活 ：设备中的 TCP\/ RTU(R)网关功能已启用。 COM端口 使用的COM端口号 波特率 传输速率（波特） " }, 
{ "title" : "图书馆 ", 
"url" : "_mod_f_device_libraries.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 图书馆 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "功能块：IoDrvModbusSerialSlave ", 
"url" : "_mod_lib_iodrvmodbusserialslave.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 图书馆 \/ 功能块：IoDrvModbusSerialSlave ", 
"snippet" : "图书馆： IoDrvModbusSerialSlave 该块是为设备树中的每个串行 Modbus 服务器设备生成的。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xInternalError Bool FALSE 不可恢复的内部错误（例如，如果 mem-aloc 或缺少许可证）...", 
"body" : "图书馆： IoDrvModbusSerialSlave 该块是为设备树中的每个串行 Modbus 服务器设备生成的。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xInternalError Bool FALSE 不可恢复的内部错误（例如，如果 mem-aloc 或缺少许可证） " }, 
{ "title" : "功能块： IoDrvModbusTCPSlave ", 
"url" : "_mod_lib_iodrvmodbustcpslave.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 图书馆 \/ 功能块： IoDrvModbusTCPSlave ", 
"snippet" : "图书馆： IoDrvModbusTCPSlave 该块是为设备树中的每个Modbus TCP服务器设备生成的。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xInternalError Bool FALSE 不可恢复的内部错误（例如，如果 mem-aloc 或缺少许可证） uiClientConnections Bool FALSE 当前已建立的客户端连接数（TCP\/IP）...", 
"body" : "图书馆： IoDrvModbusTCPSlave 该块是为设备树中的每个Modbus TCP服务器设备生成的。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xInternalError Bool FALSE 不可恢复的内部错误（例如，如果 mem-aloc 或缺少许可证） uiClientConnections Bool FALSE 当前已建立的客户端连接数（TCP\/IP） " }, 
{ "title" : "功能块： ModbusServer ", 
"url" : "_mod_lib_modbusserver.html", 
"breadcrumbs" : "CODESYS Modbus \/ 设备 \/ 图书馆 \/ 功能块： ModbusServer ", 
"snippet" : "图书馆： ModbusTCP Server 该功能块通过Modbus TCP处理最多 16 个并行客户端连接请求。Modbus 请求在映射输入和保持寄存器的数据范围内工作。 支持以下 Modbus 功能代码： 0x01 Read Coils 0x02 Read Discrete Inputs 0x03 Read Holding Registers 0x04 Read Input Registers 0x05 Write Single Coil 0x06 Write Single Register 0x0F Write Multiple Coils 0x10 Write Multiple Reg...", 
"body" : "图书馆： ModbusTCP Server 该功能块通过Modbus TCP处理最多 16 个并行客户端连接请求。Modbus 请求在映射输入和保持寄存器的数据范围内工作。 支持以下 Modbus 功能代码： 0x01 Read Coils 0x02 Read Discrete Inputs 0x03 Read Holding Registers 0x04 Read Input Registers 0x05 Write Single Coil 0x06 Write Single Register 0x0F Write Multiple Coils 0x10 Write Multiple Registers 0x17 Read\/Write Multiple Registers ModbusServer功能块使用已在Modbus TCP服务器的设备编辑器选项卡上配置的参数。 输入（VAR_INPUT） 姓名 数据类型 初始值 描述 wPort WORD 502 服务器端口（TCP\/IP协议栈）502为Modbus默认 pInputData POINTER TO WORD 指向 WORD ；指向 Modbus 输入寄存器的映射 uiInputDataSize UINT 1024 输入数据数组的长度（ WORD 每个寄存器）；默认值：1024 pOutputData POINTER TO WORD 指向 WORD ；指向 Modbus保持寄存器的映射 uiOutputDataSize UINT 输出数据数组的长度（ WORD 每个寄存器） tTimeout UDINT 超时（毫秒）。如果不为零，且在超时之前没有发生 Modbus 写入错误，则输出数据设置为零。 xEnable BOOL FALSE 开始请求处理的标志 xReset BOOL FALSE 重新启动与服务器的正常通信；重置上升沿的状态字和错误位 InterfaceName WSTRING(255) 以太网接口的名称（可选）。指定后，Modbus 服务器将绑定到此接口的 IP 地址。 输出（VAR_OUTPUT） 姓名 数据类型 初始值 描述 xBusy BOOL FALSE TRUE 请求正在处理中 xError BOOL FALSE 有关发现的错误的信息 byClientConnections BYTE 0 连接数 xTimeout BOOL 超时已过。保持寄存器和线圈已设置为零。 " }
]
$(document).trigger('search.ready');
});