$(document).ready(function () {indexDict['es'] = [{ "title" : "CODESYS IO-Link ", 
"url" : "_iolk_start_page.html", 
"breadcrumbs" : "CODESYS IO-Link \/ CODESYS IO-Link ", 
"snippet" : "Consulte la descripción general para obtener información sobre las siguientes pestañas del editor de dispositivos. Pestaña '<nombre del dispositivo> Asignación de E\/S' Pestaña '<nombre del dispositivo> Objetos IEC' Pestaña '<nombre del dispositivo> Parámetros' Pestaña '<nombre del dispositivo> Estad...", 
"body" : "Consulte la descripción general para obtener información sobre las siguientes pestañas del editor de dispositivos. Pestaña '<nombre del dispositivo> Asignación de E\/S' Pestaña '<nombre del dispositivo> Objetos IEC' Pestaña '<nombre del dispositivo> Parámetros' Pestaña '<nombre del dispositivo> Estado' Pestaña '<nombre del dispositivo> Información' Una página de ayuda separada adicional para el editor de dispositivos relevante está disponible solo en el caso de características especiales. Si no se muestra la pestaña \"<nombre del dispositivo> Parámetros\", seleccione el Mostrar editores de configuración de dispositivos genéricos opción en el CODESYS opciones, en el editor de dispositivos categoría. IO-Link es un sistema de comunicación para vincular sensores y actuadores inteligentes a un sistema de automatización. Un sistema IO-Link consta de un maestro IO-Link que proporciona la interfaz para el controlador superior (PLC) y uno o más dispositivos IO-Link (sensores y actuadores). Los archivos de descripción de dispositivos IODD asociados deben instalarse en el repositorio de dispositivos antes de que los módulos IO-Link estén disponibles en el cuadro de diálogo 'Establecer dispositivo'. Para más información, ver: Comando 'Conectar dispositivo' y Comando 'Repositorio de dispositivos' Para obtener más información general sobre el soporte de bus de campo en  CODESYS , ver: Soporte de bus de campo " }, 
{ "title" : "Pestaña: IO-Link – Información del dispositivo IO-Link ", 
"url" : "_iolk_edt_device_info.html", 
"breadcrumbs" : "CODESYS IO-Link \/ Pestaña: IO-Link – Información del dispositivo IO-Link ", 
"snippet" : "Objeto: Maestro IO-Link La pestaña del módulo IO-Link muestra diversa información sobre el producto y el proveedor del dispositivo....", 
"body" : "Objeto: Maestro IO-Link La pestaña del módulo IO-Link muestra diversa información sobre el producto y el proveedor del dispositivo. " }, 
{ "title" : "Pestaña: IO-Link – Parámetros ", 
"url" : "_iolk_edt_parameter.html", 
"breadcrumbs" : "CODESYS IO-Link \/ Pestaña: IO-Link – Parámetros ", 
"snippet" : "Objeto: Maestro IO-Link La pestaña se puede utilizar para leer los parámetros del dispositivo IO-Link, modificarlos y luego volver a escribirlos en el dispositivo. La gama de funciones depende de la descripción del dispositivo. Los comandos de los botones también están disponibles en el menú context...", 
"body" : "Objeto: Maestro IO-Link La pestaña se puede utilizar para leer los parámetros del dispositivo IO-Link, modificarlos y luego volver a escribirlos en el dispositivo. La gama de funciones depende de la descripción del dispositivo. Los comandos de los botones también están disponibles en el menú contextual de la fila seleccionada en la tabla de parámetros. Rol del usuario Especialista Mantenimiento Observador Dependiendo de la función de usuario seleccionada, se muestran más o menos detalles de los parámetros en la tabla. Menú de identificación : Información sobre la identificación del dispositivo Menú de parámetros : Muestra todos los parámetros del dispositivo. Menú de diagnóstico Muestra mensajes de error de un módulo (por ejemplo, error de voltaje) Menú de observación : Muestra mensajes de observación (por ejemplo, \"sensor sucio\") Establecer en valores predeterminados Restablece los valores en línea de los parámetros a los valores predeterminados como se define en la descripción del dispositivo Leer esta página Lee los valores mostrados actualmente de los parámetros del dispositivo y los actualiza en la tabla Escribe esta página Escribe los valores mostrados actualmente de los parámetros en el dispositivo IO-Link Guardar valores en línea Aplica lo que se muestra actualmente Valor en línea hacia Valor columna Restaurar valores Aplica los valores de la Valor columna a la Valor en línea columna La tabla enumera diferentes parámetros (nombre) y detalles de parámetros según el rol de usuario establecido y el menú seleccionado. Nombre Nombre del parámetro Valor El valor del parámetro actualmente válido se muestra en la Valor columna. Valor en línea los Valor en línea La columna se muestra solo si el dispositivo admite la descarga de parámetros y si los parámetros que se muestran en el editor de configuración también están disponibles en el dispositivo. Puede cambiar los valores de los parámetros en esta columna y transferirlos al dispositivo con el Escribe esta página comando sin modificar el proyecto y sin necesidad de descargar una nueva aplicación. Con el Guardar valores en línea comando, puede guardar el valor en línea actual como un Valor . r\/w Permisos sobre los valores de los parámetros ( ro : solo lectura; rw : Lee y escribe) " }
]
$(document).trigger('search.ready');
});