$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS SVN ", 
"url" : "_svn_start_page.html", 
"breadcrumbs" : "CODESYS SVN \/ CODESYS SVN ", 
"snippet" : "CODESYS SVN 允许您的发展 CODESYS 受 Apache™ Subversion® 版本控制的项目。 CODESYS SVN 提供集成在 SVN 客户端 CODESYS .您项目的对象在中央 SVN 存储库中进行版本控制。 通常，SVN 存储库应在服务器配置中创建并位于服务器上。出于测试目的，您可以创建一个本地 SVN 存储库，您可以通过以下方式访问该存储库 file:\/\/ . CODESYS SVN 需要获得许可并支付费用，并且是产品的一部分 CODESYS Professional Developer Edition 。 您可以使用该产品 CODESYS Profession...", 
"body" : "CODESYS SVN 允许您的发展 CODESYS 受 Apache™ Subversion® 版本控制的项目。 CODESYS SVN 提供集成在 SVN 客户端 CODESYS .您项目的对象在中央 SVN 存储库中进行版本控制。 通常，SVN 存储库应在服务器配置中创建并位于服务器上。出于测试目的，您可以创建一个本地 SVN 存储库，您可以通过以下方式访问该存储库 file:\/\/ . CODESYS SVN 需要获得许可并支付费用，并且是产品的一部分 CODESYS Professional Developer Edition 。 您可以使用该产品 CODESYS Professional Developer Edition 在里面 CODESYS 国际商店 或在 CODESYS 北美商店 下载。您还可以在那里找到该产品的数据表。 " }, 
{ "title" : "入门 ", 
"url" : "_svn_first_steps.html", 
"breadcrumbs" : "CODESYS SVN \/ 入门 ", 
"snippet" : "为了开发您的产品，需要执行以下步骤  CODESYS  项目与 CODESYS SVN 和 版本控制 通过 Apache™ Subversion®： 安装 CODESYS SVN 包装在 CODESYS . 安装SVN服务器 . 创建一个 SVN存储库 。 打开你的 CODESYS 项目在 CODESYS . 进口 这 CODESYS 项目到 SVN 存储库。 这 CODESYS 项目保存在 SVN 存储库中。 编辑和进一步开发项目（ 工作副本 ）在SVN版本控制下，项目编辑于 CODESYS  然后提交到SVN项目存储库。 从版本 4.4.0.0 开始，在 存储配置文件不一致 在工作副本和 ...", 
"body" : "为了开发您的产品，需要执行以下步骤  CODESYS  项目与 CODESYS SVN 和 版本控制 通过 Apache™ Subversion®： 安装 CODESYS SVN 包装在 CODESYS . 安装SVN服务器 . 创建一个 SVN存储库 。 打开你的 CODESYS 项目在 CODESYS . 进口 这 CODESYS 项目到 SVN 存储库。 这 CODESYS 项目保存在 SVN 存储库中。 编辑和进一步开发项目（ 工作副本 ）在SVN版本控制下，项目编辑于 CODESYS  然后提交到SVN项目存储库。 从版本 4.4.0.0 开始，在 存储配置文件不一致 在工作副本和 SVN 存储库中的项目之间，相应的说明将进一步指导您。在某些情况下，对象级别的提交操作将不再可能。有关更多信息，请参阅： 检查版本配置文件的一致性" }, 
{ "title" : "版本控制 ", 
"url" : "_svn_version_control.html", 
"breadcrumbs" : "CODESYS SVN \/ 版本控制 ", 
"snippet" : "CODESYS SVN 在里面 CODESYS Test Manager CODESYS SVN 为 CODESYS Test Manager ....", 
"body" : "CODESYS SVN 在里面 CODESYS Test Manager CODESYS SVN 为 CODESYS Test Manager . " }, 
{ "title" : "什么是版本控制？ ", 
"url" : "_svn_version_control.html#UUID-a85b1168-0cc8-32f4-ec49-402107f5c1f6_id_f926176e7145c0a8646351d89897-id-361c3b86acb62b8ac0a864636892b168", 
"breadcrumbs" : "CODESYS SVN \/ 版本控制 \/ 什么是版本控制？ ", 
"snippet" : "Apache™ Subversion® (SVN) 是一种用于对当前和以前版本的文件（例如源代码、网站和文档）进行版本和修订管理的工具。 Apache™ Subversion® 是 Apache Software Foundation 的注册商标。 修订管理（也称为版本控制、版本管理和源代码管理）是对存储为计算机文件的文档、程序和其他信息的更改的管理。当一组员工处理相同的文件时，软件开发中经常使用版本控制。 任务 跟踪修订中的变化 您可以随时显示谁在何时进行了哪些更改。 恢复单个文件的旧版本 您可以随时撤消对文件的意外更改。 归档项目的特殊修订 您可以随时恢复到旧版本。 协调开发人员对数据的共...", 
"body" : "Apache™ Subversion® (SVN) 是一种用于对当前和以前版本的文件（例如源代码、网站和文档）进行版本和修订管理的工具。 Apache™ Subversion® 是 Apache Software Foundation 的注册商标。 修订管理（也称为版本控制、版本管理和源代码管理）是对存储为计算机文件的文档、程序和其他信息的更改的管理。当一组员工处理相同的文件时，软件开发中经常使用版本控制。 任务 跟踪修订中的变化 您可以随时显示谁在何时进行了哪些更改。 恢复单个文件的旧版本 您可以随时撤消对文件的意外更改。 归档项目的特殊修订 您可以随时恢复到旧版本。 协调开发人员对数据的共享访问 多个分支同时开发一个项目 " }, 
{ "title" : "脚本引擎 SVN 附加 API ", 
"url" : "_svn_version_control.html#UUID-a85b1168-0cc8-32f4-ec49-402107f5c1f6_id_f926176e7145c0a8646351d89897-id-e659e72faaaea885c0a8646360ca88f9", 
"breadcrumbs" : "CODESYS SVN \/ 版本控制 \/ 脚本引擎 SVN 附加 API ", 
"snippet" : "CODESYS SVN 为 SVN 提供脚本接口。 有关更多信息，请参阅： 脚本引擎 API 文档...", 
"body" : "CODESYS SVN 为 SVN 提供脚本接口。 有关更多信息，请参阅： 脚本引擎 API 文档 " }, 
{ "title" : "安装 SVN 服务器 ", 
"url" : "_svn_server.html", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "什么是 SVN 服务器？ ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-a83cb18fc8170f40c0a8640e016eeeff", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 什么是 SVN 服务器？ ", 
"snippet" : "Apache™ Subversion® (SVN) 是一个免费的开源版本控制系统，根据客户端\/服务器模型运行。 SVN 服务器通常安装在中央计算机上，它在数据库中管理 SVN 存储库的数据。 SVN 存储库只是包含您的目录树 CODESYS 项目。 SVN 服务器使客户端可以访问存储的数据和 CODESYS 项目。 项目数据可作为您的工作站计算机上的工作副本使用，该计算机充当客户端。当你打开你的项目时， CODESYS SVN 显示对象树中所有对象的SVN状态，并提供SVN命令。然后你可以使用版本控制继续开发你的项目 CODESYS ....", 
"body" : "Apache™ Subversion® (SVN) 是一个免费的开源版本控制系统，根据客户端\/服务器模型运行。 SVN 服务器通常安装在中央计算机上，它在数据库中管理 SVN 存储库的数据。 SVN 存储库只是包含您的目录树 CODESYS 项目。 SVN 服务器使客户端可以访问存储的数据和 CODESYS 项目。 项目数据可作为您的工作站计算机上的工作副本使用，该计算机充当客户端。当你打开你的项目时， CODESYS SVN 显示对象树中所有对象的SVN状态，并提供SVN命令。然后你可以使用版本控制继续开发你的项目 CODESYS . " }, 
{ "title" : "免费文档 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-9607e56ede3d11e69c27d630ebd1b7af", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 免费文档 ", 
"snippet" : "Apache™ Subversion® (SVN) 提供免费文档。我们推荐 SVN 书籍“红豆”中的大量文档。此外，书店也有关于这个主题的书籍。但是，您应该注意书籍对应当前的 SVN 版本。 有关更多信息，请参阅： 使用 Subversion 进行版本控制： http:\/\/svnbook.red-bean.com\/en\/1.8\/ 服务器相关章节： 5. 仓库管理 6.服务器配置 官方常见问题解答： http:\/\/subversion.apache.org\/faq.html （推荐作为补充）...", 
"body" : "Apache™ Subversion® (SVN) 提供免费文档。我们推荐 SVN 书籍“红豆”中的大量文档。此外，书店也有关于这个主题的书籍。但是，您应该注意书籍对应当前的 SVN 版本。 有关更多信息，请参阅： 使用 Subversion 进行版本控制： http:\/\/svnbook.red-bean.com\/en\/1.8\/ 服务器相关章节： 5. 仓库管理 6.服务器配置 官方常见问题解答： http:\/\/subversion.apache.org\/faq.html （推荐作为补充） " }, 
{ "title" : "支持资源 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-93435200b71e8e1ac0a8646304840b83", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 支持资源 ", 
"snippet" : "支持资源 “颠覆用户”邮件列表 http:\/\/subversion.apache.org\/mailing-lists.html 具有大量存档的英语邮件列表 （在发送请求之前检查那里。） IRC 聊天频道#svn http:\/\/en.wikipedia.org\/wiki\/Comparison_of_Subversion_clients freenode 网络上的其他 SVN 客户端列表...", 
"body" : "支持资源 “颠覆用户”邮件列表 http:\/\/subversion.apache.org\/mailing-lists.html 具有大量存档的英语邮件列表 （在发送请求之前检查那里。） IRC 聊天频道#svn http:\/\/en.wikipedia.org\/wiki\/Comparison_of_Subversion_clients freenode 网络上的其他 SVN 客户端列表 " }, 
{ "title" : "公司支持 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-54b6f641c8170f40c0a8640e00888570", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 公司支持 ", 
"snippet" : "一些公司为 SVN 提供商业支持。以下列表绝不是完整的。它绝不表示推荐或什至对质量的保证 CODESYS GmbH . http:\/\/www.collab.net\/ http:\/\/www.wandisco.com\/ http:\/\/www.elegosoft.com\/ （德国公司） http:\/\/www.visualsvn.com\/ http:\/\/www.clearvision-cm.com\/...", 
"body" : "一些公司为 SVN 提供商业支持。以下列表绝不是完整的。它绝不表示推荐或什至对质量的保证 CODESYS GmbH . http:\/\/www.collab.net\/ http:\/\/www.wandisco.com\/ http:\/\/www.elegosoft.com\/ （德国公司） http:\/\/www.visualsvn.com\/ http:\/\/www.clearvision-cm.com\/ " }, 
{ "title" : "SVN 服务器的变种 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-d59dc998ac8c85f2c0a864634702c339", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ SVN 服务器的变种 ", 
"snippet" : "目前有几种 SVN 服务器变体可用。通常可以通过以下几个变体轻松同时启用 SVN 存储库。此外，一台服务器安装可以管理多个 SVN 存储库。 Svnserve 这是安装 SVN 服务器的最简单的变体。访问是通过高效的 svn:\/\/ 协议。它通常在内部应用于公司网络或与 VPN 连接。 Apache + mod_dav_svn 这是集成到 Apache Web 服务器中的 SVN。通过“www 协议”进行访问 http:\/\/ 或其加密变体 https:\/\/ .这种类型的安装经常应用于公共 SVN 服务器或通过 Internet 访问的 SVN 服务器。 Svnserve + ssh 此变体使用 ...", 
"body" : "目前有几种 SVN 服务器变体可用。通常可以通过以下几个变体轻松同时启用 SVN 存储库。此外，一台服务器安装可以管理多个 SVN 存储库。 Svnserve 这是安装 SVN 服务器的最简单的变体。访问是通过高效的 svn:\/\/ 协议。它通常在内部应用于公司网络或与 VPN 连接。 Apache + mod_dav_svn 这是集成到 Apache Web 服务器中的 SVN。通过“www 协议”进行访问 http:\/\/ 或其加密变体 https:\/\/ .这种类型的安装经常应用于公共 SVN 服务器或通过 Internet 访问的 SVN 服务器。 Svnserve + ssh 此变体使用 Linux\/Unix 的“安全外壳”来实现访问控制和加密。当客户端也在 Linux\/Unix 上运行时，这主要是有用的。但是，它在 SVN 存储库中的访问控制功能有限。 使用 SVN 存储库直接访问 file:\/\/ 协议 此变体仅用于测试目的和管理员访问权限。 注意：我们强烈建议您不要通过网络共享的方式使用此变体进行共享访问。 有关更多信息，请参阅： http:\/\/svnbook.red-bean.com\/en\/1.8\/svn.serverconfig.overview.html " }, 
{ "title" : "客户端\/服务器问题 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-e6d1da93c8170f41c0a8640e00272625", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 客户端\/服务器问题 ", 
"snippet" : "SVN服务器的配置问题和 CODESYS SVN 目前发布的 CODESYS SVN 在某些混合 IPv4\/IPv6 环境中存在问题。当 SVN 存储库服务器的主机名成功解析为 IPv4 和 IPv6 地址，但 SVN 服务器本身 ( svnserve 或者 apache mod_svn ) 仅接受通过 IPV4 的请求。这导致访问 SVN 存储库的某些对话框访问异常缓慢。例如，这会影响 SVN 存储库浏览器 , 查看 ， 和 SVN 交换机 对话框。 该问题的最佳解决方案是重新配置服务器，使其也接受通过 IPv6 的请求。另一种选择是通过服务器的 IPv4 地址访问 SVN 存储库，然后在客...", 
"body" : "SVN服务器的配置问题和 CODESYS SVN 目前发布的 CODESYS SVN 在某些混合 IPv4\/IPv6 环境中存在问题。当 SVN 存储库服务器的主机名成功解析为 IPv4 和 IPv6 地址，但 SVN 服务器本身 ( svnserve 或者 apache mod_svn ) 仅接受通过 IPV4 的请求。这导致访问 SVN 存储库的某些对话框访问异常缓慢。例如，这会影响 SVN 存储库浏览器 , 查看 ， 和 SVN 交换机 对话框。 该问题的最佳解决方案是重新配置服务器，使其也接受通过 IPv6 的请求。另一种选择是通过服务器的 IPv4 地址访问 SVN 存储库，然后在客户端计算机上停用 IPv6。您还可以设置仅解析服务器的 IPv4 地址的备用主机名。 " }, 
{ "title" : "安装和配置服务器 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_e0177a8418c0a864630680be79-id-e9eed6afdb29f711c0a8646327eccbca", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 安装和配置服务器 ", 
"snippet" : "我们建议您使用高效的 SVN 服务器作为 IT 基础架构的一部分，由专家监控和维护。确保使用旨在用作服务器的故障安全硬件。定期更新安装的软件并保护服务器免受外部访问。确保您有一个正常工作的备份。 为了 CODESYS SVN 作为 SVN 客户端，服务器运行在哪个操作系统上并不重要。 首次安装 SVN 服务器时选择当前版本（例如：1.9.x 版本）。现有的 1.8 版服务器应该没有任何问题。避免使用服务器版本 1.7.x 及更低版本。我们建议您更新此版本，因为 SVN 开发人员不再提供对此版本及更早版本的支持。 对于 Windows 服务器，从 Internet 下载安装包，例如从 Apach...", 
"body" : "我们建议您使用高效的 SVN 服务器作为 IT 基础架构的一部分，由专家监控和维护。确保使用旨在用作服务器的故障安全硬件。定期更新安装的软件并保护服务器免受外部访问。确保您有一个正常工作的备份。 为了 CODESYS SVN 作为 SVN 客户端，服务器运行在哪个操作系统上并不重要。 首次安装 SVN 服务器时选择当前版本（例如：1.9.x 版本）。现有的 1.8 版服务器应该没有任何问题。避免使用服务器版本 1.7.x 及更低版本。我们建议您更新此版本，因为 SVN 开发人员不再提供对此版本及更早版本的支持。 对于 Windows 服务器，从 Internet 下载安装包，例如从 Apache.org 或者 VisualSVN 服务器 .对于“Apache.org”，图形的当前版本 TortoiseSVN 客户端 提供安装命令行工具的选项，包括“svnserve”。对于 Linux 服务器，SVN 包通常由发行版提供。这可能是更简单的方法。 " }, 
{ "title" : "通过身份验证和证书保护服务器\/客户端连接 ", 
"url" : "_svn_server.html#UUID-f2b63beb-e228-335a-5716-cf2cbbfb2e74_id_index-6", 
"breadcrumbs" : "CODESYS SVN \/ 安装 SVN 服务器 \/ 通过身份验证和证书保护服务器\/客户端连接 ", 
"snippet" : "您可以使用加密连接，以免通过不安全的网络与 SVN 服务器建立连接。可以通过标准程序（例如 SSL 或 SSH）进行加密。服务器必须由管理员配置才能执行此操作。 服务器上的身份验证 您可以通过确认服务器证书在服务器上对自己进行身份验证。 客户端上的身份验证 您可以通过以下选项执行客户端身份验证（权限检查）： 客户证书 密码 用户名和密码 有关更多信息，请参阅： 颠覆认证...", 
"body" : "您可以使用加密连接，以免通过不安全的网络与 SVN 服务器建立连接。可以通过标准程序（例如 SSL 或 SSH）进行加密。服务器必须由管理员配置才能执行此操作。 服务器上的身份验证 您可以通过确认服务器证书在服务器上对自己进行身份验证。 客户端上的身份验证 您可以通过以下选项执行客户端身份验证（权限检查）： 客户证书 密码 用户名和密码 有关更多信息，请参阅： 颠覆认证" }, 
{ "title" : "使用 SVN 存储库 ", 
"url" : "_svn_use_repository.html", 
"breadcrumbs" : "CODESYS SVN \/ 使用 SVN 存储库 ", 
"snippet" : "一个 SVN 存储库 通常将信息保存为文件系统树、文件层次结构和目录。任意数量的客户端连接到 SVN 存储库并读取或写入修订中文件的更改。 将项目导入 SVN 存储库。 打开 CODESYS 要保存在 SVN 存储库中的项目。 例子： A.project 开了。 点击 项目 → SVN → 导入项目 到SVN . 这 浏览 SVN 存储库 对话框打开。 选择目录 file:\/\/\/D:\/SVN repository\/trunk 在目录树中。 点击 . 这 创建远程目录 对话框打开。 指定新目录的 URL。 注意：因为新目录应该包含 CODESYS 项目，请在此处指定带有扩展名的项目名称。 fil...", 
"body" : "一个 SVN 存储库 通常将信息保存为文件系统树、文件层次结构和目录。任意数量的客户端连接到 SVN 存储库并读取或写入修订中文件的更改。 将项目导入 SVN 存储库。 打开 CODESYS 要保存在 SVN 存储库中的项目。 例子： A.project 开了。 点击 项目 → SVN → 导入项目 到SVN . 这 浏览 SVN 存储库 对话框打开。 选择目录 file:\/\/\/D:\/SVN repository\/trunk 在目录树中。 点击 . 这 创建远程目录 对话框打开。 指定新目录的 URL。 注意：因为新目录应该包含 CODESYS 项目，请在此处指定带有扩展名的项目名称。 file:\/\/\/D:\/SVN%20repository\/trunk\/A.project 点击 行 退出对话框。 选择新项目并单击 行 退出 浏览 SVN 存储库 对话。 这 将项目导入 SVN 对话框打开。目录 file:\/\/\/D:\/SVN repository\/trunk\/A.project 指定在 SVN 仓库地址 . 指定导入消息（例如： 客户 A 的项目 ) 并单击 行 . 该项目保存在 SVN 中。 重叠的图标 在对象路径中显示 SVN 状态 CODESYS . " }, 
{ "title" : "创建 SVN 存储库 ", 
"url" : "_svn_use_repository.html#UUID-fd1d8b3c-774e-e9df-a411-28cd0b51a45a_id_c064425ab73f7ab5c0a864632d3e9a2f-id-64289221b75219bfc0a8646358d9080b", 
"breadcrumbs" : "CODESYS SVN \/ 使用 SVN 存储库 \/ 创建 SVN 存储库 ", 
"snippet" : "请咨询您的 IT 专家以获取更多信息（例如，如何创建 SVN 存储库）。出于生产目的，我们建议使用严格专用的管理 SVN 服务器。 我们建议您在 SVN 存储库中创建建议的默认目录结构。 有关更多信息，请参阅： http:\/\/svnbook.red-bean.com\/en\/1.8\/svn.tour.importing.html#svn.tour.importing.layout...", 
"body" : "请咨询您的 IT 专家以获取更多信息（例如，如何创建 SVN 存储库）。出于生产目的，我们建议使用严格专用的管理 SVN 服务器。 我们建议您在 SVN 存储库中创建建议的默认目录结构。 有关更多信息，请参阅： http:\/\/svnbook.red-bean.com\/en\/1.8\/svn.tour.importing.html#svn.tour.importing.layout " }, 
{ "title" : "为测试目的创建 SVN 存储库 ", 
"url" : "_svn_use_repository.html#UUID-fd1d8b3c-774e-e9df-a411-28cd0b51a45a_id_c064425ab73f7ab5c0a864632d3e9a2f-id-30c09bdcb75f8ee5c0a86463473c6532", 
"breadcrumbs" : "CODESYS SVN \/ 使用 SVN 存储库 \/ 为测试目的创建 SVN 存储库 ", 
"snippet" : "使用 file:\/\/ 仅用于测试目的的访问方法。 您可以通过以下方式访问以 1.8 或 1.9 格式创建的 SVN 存储库 file:\/\/ 协议。 出于测试目的，您可以在不安装自己的服务器的情况下创建本地 SVN 存储库。 SVN 存储库可通过以下方式访问 file:\/\/ 并提供与服务器相同的功能。 使用 TortoiseSVN 创建测试仓库 要求：开发系统上安装了SVN客户端TortoiseSVN 1.9。 在本地文件系统上创建一个新的空文件夹。测试存储库在那里创建。 例子： D:\\SVN repository 点击 TortoiseSVN → 在此处创建存储库 . 这 创建存储库 对话框打...", 
"body" : "使用 file:\/\/ 仅用于测试目的的访问方法。 您可以通过以下方式访问以 1.8 或 1.9 格式创建的 SVN 存储库 file:\/\/ 协议。 出于测试目的，您可以在不安装自己的服务器的情况下创建本地 SVN 存储库。 SVN 存储库可通过以下方式访问 file:\/\/ 并提供与服务器相同的功能。 使用 TortoiseSVN 创建测试仓库 要求：开发系统上安装了SVN客户端TortoiseSVN 1.9。 在本地文件系统上创建一个新的空文件夹。测试存储库在那里创建。 例子： D:\\SVN repository 点击 TortoiseSVN → 在此处创建存储库 . 这 创建存储库 对话框打开。 点击 创建目录树 . 这 SVN repository 被建造。 有关更多信息，请参阅： TortoiseSVN 文档 " }, 
{ "title" : "访问 SVN 存储库 ", 
"url" : "_svn_use_repository.html#UUID-fd1d8b3c-774e-e9df-a411-28cd0b51a45a_id_c064425ab73f7ab5c0a864632d3e9a2f-id-11cf553db75219bfc0a864636531644b", 
"breadcrumbs" : "CODESYS SVN \/ 使用 SVN 存储库 \/ 访问 SVN 存储库 ", 
"snippet" : "SVN 存储库 URL file:\/\/\/ 直接访问 SVN 存储库（在本地硬盘上） http:\/\/ 通过WebDAV协议访问SVN支持的Apache服务器 https:\/\/ 作为 http:\/\/ ，但使用 SSL 加密 svn:\/\/ 通过自己的协议访问 svnserve 服务器 svn+ssh:\/\/ 作为 svn:\/\/ ，但通过 SSH 建立隧道...", 
"body" : "SVN 存储库 URL file:\/\/\/ 直接访问 SVN 存储库（在本地硬盘上） http:\/\/ 通过WebDAV协议访问SVN支持的Apache服务器 https:\/\/ 作为 http:\/\/ ，但使用 SSL 加密 svn:\/\/ 通过自己的协议访问 svnserve 服务器 svn+ssh:\/\/ 作为 svn:\/\/ ，但通过 SSH 建立隧道 " }, 
{ "title" : "使用工作副本 ", 
"url" : "_svn_use_working_copy.html", 
"breadcrumbs" : "CODESYS SVN \/ 使用工作副本 ", 
"snippet" : "更改了工作副本格式 CODESYS SVN V4.1.0.0 及更高版本 对于版本中的项目 CODESYS SVN V4.1.0.0 及更高版本，工作目录（工作副本）具有新格式。 如果您打开一个使用 V4.0.4.0 或更低，则项目在打开时会自动更新为新格式。 如果您打开一个使用 V4.0.4.0 或更低，并且该项目基于旧的 SVN 版本 1.7.x 或更低，则提示您是否 CODESYS 应该更新格式。如果您拒绝更新，则项目的 SVN 链接将被停用。您仍然可以加载和编辑项目。 更新对保存到 SVN 服务器没有影响。您还可以使用早期版本的客户端签出项目。新格式仅影响本地工作目录。 有关更多信息，...", 
"body" : "更改了工作副本格式 CODESYS SVN V4.1.0.0 及更高版本 对于版本中的项目 CODESYS SVN V4.1.0.0 及更高版本，工作目录（工作副本）具有新格式。 如果您打开一个使用 V4.0.4.0 或更低，则项目在打开时会自动更新为新格式。 如果您打开一个使用 V4.0.4.0 或更低，并且该项目基于旧的 SVN 版本 1.7.x 或更低，则提示您是否 CODESYS 应该更新格式。如果您拒绝更新，则项目的 SVN 链接将被停用。您仍然可以加载和编辑项目。 更新对保存到 SVN 服务器没有影响。您还可以使用早期版本的客户端签出项目。新格式仅影响本地工作目录。 有关更多信息，请参阅： http:\/\/svnbook.red-bean.com\/en\/1.8\/svn.ref.svn.c.upgrade.html " }, 
{ "title" : "签出一个项目 ", 
"url" : "_svn_use_working_copy.html#UUID-fb4f11dc-5a6b-2f23-98eb-63ccf3a70280_id_beacb74905f4c0a8646371c95208-id-9ba89420de5d11e69c27d630ebd1b7af", 
"breadcrumbs" : "CODESYS SVN \/ 使用工作副本 \/ 签出一个项目 ", 
"snippet" : "你可以复制 CODESYS 项目，保存在 SVN 存储库 , 到你的开发系统进行编辑。 创建工作副本 打开 CODESYS . 点击 项目 → SVN → 查看 . 这 查看 对话框打开。 指定 SVN 存储库的 URL 并在 SVN 存储库树中选择一个项目。 一个 CODESYS 项目由其文件扩展名自动识别（ .project , _project , .library ， 或者 _library ) 在结帐时作为“项目”或“库项目”。 在 结帐至 ，指定开发系统上工作副本的名称和位置。 点击 行 退出对话框。 该项目在 CODESYS .在项目的对象树中，SVN 链接显示为 重叠的图标 ....", 
"body" : "你可以复制 CODESYS 项目，保存在 SVN 存储库 , 到你的开发系统进行编辑。 创建工作副本 打开 CODESYS . 点击 项目 → SVN → 查看 . 这 查看 对话框打开。 指定 SVN 存储库的 URL 并在 SVN 存储库树中选择一个项目。 一个 CODESYS 项目由其文件扩展名自动识别（ .project , _project , .library ， 或者 _library ) 在结帐时作为“项目”或“库项目”。 在 结帐至 ，指定开发系统上工作副本的名称和位置。 点击 行 退出对话框。 该项目在 CODESYS .在项目的对象树中，SVN 链接显示为 重叠的图标 .现在该项目已保存为您的开发系统上的工作副本。 " }, 
{ "title" : "编辑工作副本 ", 
"url" : "_svn_use_working_copy.html#UUID-fb4f11dc-5a6b-2f23-98eb-63ccf3a70280_id_beacb74905f4c0a8646371c95208-id-174f6d6ab56f7432c0a864637e236225", 
"breadcrumbs" : "CODESYS SVN \/ 使用工作副本 \/ 编辑工作副本 ", 
"snippet" : "在开始编辑之前更新工作副本，尤其是在项目由团队修改的情况下。您可以通过这种方式防止冲突。 检查版本配置文件的一致性 从版本 4.4.0.0 开始， CODESYS SVN 检查项目的存储配置文件（ CODESYS 工作副本中保存项目的版本）与 SVN 存储库中的存储配置文件匹配。如果配置文件不同，则注释 存储配置文件更新 以红色显示在 待更改 查看并在 犯罪 对话。此外，对于需要在存储库和工作副本之间提交的操作，消息对话框会通知您不一致的情况。您将获得对存储配置文件进行必要更改的支持。例如，这可能发生在以下 SVN 操作中：提交、恢复、更新和签出。 如果 元配置文件 对象出现更改为 ，那么它也...", 
"body" : "在开始编辑之前更新工作副本，尤其是在项目由团队修改的情况下。您可以通过这种方式防止冲突。 检查版本配置文件的一致性 从版本 4.4.0.0 开始， CODESYS SVN 检查项目的存储配置文件（ CODESYS 工作副本中保存项目的版本）与 SVN 存储库中的存储配置文件匹配。如果配置文件不同，则注释 存储配置文件更新 以红色显示在 待更改 查看并在 犯罪 对话。此外，对于需要在存储库和工作副本之间提交的操作，消息对话框会通知您不一致的情况。您将获得对存储配置文件进行必要更改的支持。例如，这可能发生在以下 SVN 操作中：提交、恢复、更新和签出。 如果 元配置文件 对象出现更改为 ，那么它也必须被提交，因为它包含存储配置文件信息。 在对象级别的不同存储配置文件的情况下，某些操作不再可能，以防止由不一致引起的任何问题。在项目级别，工作副本中至少总有一个选项可以使用 将项目另存为 命令或通过恢复到相应的修订版来重新调整存储格式，即使这可能会导致轻微的数据丢失。 您可以在 项目信息 在 文件 选项卡下 保存为 . 打开工作副本。 点击 项目 → SVN → 更新项目 （象征： ）。 您的工作副本是最新的。 修改你的项目。 点击 项目 → SVN → 编辑 SVN 工作副本 . 对话框打开。在那里您可以浏览您的更改。 退出对话框。 如有需要，您可以点击 SVN → 恢复 在上下文菜单中。因此， CODESYS SVN 首先检查工作副本的存储配置文件是否与 SVN 存储库中项目的存储配置文件匹配。如果存储配置文件不同，则无法在对象级别进行还原（请参阅 笔记 以上）。 该文件将恢复为基本版本，并且您的更改将被丢弃。 如有需要，您可以点击 相比 在已编辑对象的上下文菜单中。 比较对话框打开。您可以在此处解决任何冲突。 关闭比较对话框。 点击  项目 → SVN → 提交项目 （象征 ）。 这 犯罪 对话框打开。 在 信息 ，指定描述您的更改的日志条目。例子： Changes for customer ABC, request 1234. 您的更改作为带有修订号的修订保存在 SVN 存储库中。 " }, 
{ "title" : "参考，用户界面 ", 
"url" : "_svn_f_reference_user_interface.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "叠加图标 ", 
"url" : "_svn_reference_overlay_symbols.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 叠加图标 ", 
"snippet" : "中的每个对象 CODESYS 在 SVN 存储库中有一个状态值。此状态值显示在对象树中（在 POU , 设备 ， 或者 模块 视图）通过覆盖图标为每个对象。 叠加图标 计划添加到 SVN 存储库的对象 对象冲突 对象已删除 对象已修改 元数据中修改的对象 修改了内存格式的对象 对象法线 对象写保护（只读） 对象锁定 具有已删除子对象的对象 提交时忽略的对象 外部的 忽略的对象 未版本化的对象 具有修改的子对象的对象 该对象未保存在 SVN 存储库中。从 SVN 加载时会再次创建。 SVN_VERSION_INFO 暂时不可用，例如接口库 对象的状态未更新。 对象在服务器上被修改（ ü 可用日期...", 
"body" : "中的每个对象 CODESYS 在 SVN 存储库中有一个状态值。此状态值显示在对象树中（在 POU , 设备 ， 或者 模块 视图）通过覆盖图标为每个对象。 叠加图标 计划添加到 SVN 存储库的对象 对象冲突 对象已删除 对象已修改 元数据中修改的对象 修改了内存格式的对象 对象法线 对象写保护（只读） 对象锁定 具有已删除子对象的对象 提交时忽略的对象 外部的 忽略的对象 未版本化的对象 具有修改的子对象的对象 该对象未保存在 SVN 存储库中。从 SVN 加载时会再次创建。 SVN_VERSION_INFO 暂时不可用，例如接口库 对象的状态未更新。 对象在服务器上被修改（ ü 可用日期）。 该对象被另一个用户（或另一个工作目录）锁定在服务器上。 项目结构更改导致的树冲突 " }, 
{ "title" : "命令 ", 
"url" : "_svn_struct_reference_commands.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 ", 
"snippet" : "并非所有命令在登录状态下都可用，因为项目的某些 SVN 命令可能会被更改。 命令的可用性 命令 未登录 登录 SVN 存储库浏览器X X 编辑 SVN 工作副本X 将项目导入 SVNX X 查看X X 提交，提交项目X X 比较X 与 HEAD 修订版比较X 与修订比较X 与远程项目比较X 包括外部项目，包括外部项目X 提交时忽略X X SVN信息X X 显示属性X X 获取锁X X 偷锁X X 释放锁X X 递归释放锁X X 显示日志，显示项目日志X X 还原，还原项目X 恢复到修订版，将项目恢复到修订版X 更新，更新项目X 更新到修订X 只更新这个X 断开项目与 Subversion 的连...", 
"body" : "并非所有命令在登录状态下都可用，因为项目的某些 SVN 命令可能会被更改。 命令的可用性 命令 未登录 登录 SVN 存储库浏览器X X 编辑 SVN 工作副本X 将项目导入 SVNX X 查看X X 提交，提交项目X X 比较X 与 HEAD 修订版比较X 与修订比较X 与远程项目比较X 包括外部项目，包括外部项目X 提交时忽略X X SVN信息X X 显示属性X X 获取锁X X 偷锁X X 释放锁X X 递归释放锁X X 显示日志，显示项目日志X X 还原，还原项目X 恢复到修订版，将项目恢复到修订版X 更新，更新项目X 更新到修订X 只更新这个X 断开项目与 Subversion 的连接X X 切换到X 提交时取消忽略X X SVN 清理X X 清除身份验证数据X X 合并更改X 连接到现有项目X X 解决冲突X 在离线模式下工作X X 复制（分支\/标签）X 待更改X X " }, 
{ "title" : "命令：SVN 存储库浏览器 ", 
"url" : "_svn_cmd_repository_browser.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：SVN 存储库浏览器 ", 
"snippet" : "SVN 存储库浏览器 象征： 功能 ：该命令打开 SVN 存储库浏览器。 SVN 存储库的内容在此处以树状结构显示。您可以在浏览器中搜索存储库。 称呼 ： 项目 → SVN 菜单 根据所选对象，上下文菜单中提供以下命令： 显示日志 查看 创建文件夹 复制到 改名 删除 用鼠标右键双击对象打开日志对话框。...", 
"body" : "SVN 存储库浏览器 象征： 功能 ：该命令打开 SVN 存储库浏览器。 SVN 存储库的内容在此处以树状结构显示。您可以在浏览器中搜索存储库。 称呼 ： 项目 → SVN 菜单 根据所选对象，上下文菜单中提供以下命令： 显示日志 查看 创建文件夹 复制到 改名 删除 用鼠标右键双击对象打开日志对话框。 " }, 
{ "title" : "对话框：SVN 存储库浏览器 ", 
"url" : "_svn_cmd_repository_browser.html#UUID-bde9171a-97f0-6b8b-9305-7392289c4081_section-idm43257678700354", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：SVN 存储库浏览器 \/ 对话框：SVN 存储库浏览器 ", 
"snippet" : "网址 SVN 存储库中的 URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：一旦指定了有效的 SVN 存储库，您可以单击旁边的按钮浏览并选择特定项目。 打开 选择修订该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 3 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 注意：该对话框提供的选项与 修订 团体。 通过重新扫描 SVN 存储库来更新浏览器视图 将 URL 地址向上导航一个文件夹 左侧区域 SVN 存储库中的目录树 项目...", 
"body" : "网址 SVN 存储库中的 URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：一旦指定了有效的 SVN 存储库，您可以单击旁边的按钮浏览并选择特定项目。 打开 选择修订该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 3 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 注意：该对话框提供的选项与 修订 团体。 通过重新扫描 SVN 存储库来更新浏览器视图 将 URL 地址向上导航一个文件夹 左侧区域 SVN 存储库中的目录树 项目节点以粗体显示。 注意：在此视图中，您可以直接编辑项目名称和上级文件夹的名称。 右侧区域 所选目录的对象列表 关闭 关闭对话框 " }, 
{ "title" : "命令：编辑 SVN 工作副本 ", 
"url" : "_svn_cmd_explore_svn_working_copy.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：编辑 SVN 工作副本 ", 
"snippet" : "编辑 SVN 工作副本 象征： 功能 ：该命令打开 编辑 SVN 工作副本 对话框并从 SVN 视图在浏览器中显示工作副本。 称呼 ： 项目 → SVN 菜单 浏览器的功能允许： 对未显示在 设备 看法 对可能导致异常的对象的操作 设备 看法 编辑已修改、冲突或阻止的全局对象...", 
"body" : "编辑 SVN 工作副本 象征： 功能 ：该命令打开 编辑 SVN 工作副本 对话框并从 SVN 视图在浏览器中显示工作副本。 称呼 ： 项目 → SVN 菜单 浏览器的功能允许： 对未显示在 设备 看法 对可能导致异常的对象的操作 设备 看法 编辑已修改、冲突或阻止的全局对象 " }, 
{ "title" : "对话框：编辑 SVN 工作副本 ", 
"url" : "_svn_cmd_explore_svn_working_copy.html#UUID-bba54046-e409-180d-99f6-893aedfefead_id_ade5b225178633f8c0a86463647e344f-id-1dc319b06479d7c2c0a864633757fc71", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：编辑 SVN 工作副本 \/ 对话框：编辑 SVN 工作副本 ", 
"snippet" : "编辑 SVN 工作副本：<项目名称> – <项目 URL> SVN 存储库中的路径 从 SVN 视图显示工作副本 项目中对象的文件和文件夹结构在此处以树视图的形式呈现。结果，对象的递归深度是可见的。 ：为以下菜单命令选择的对象 对象名称 对象的文件名 例子： Application 节点类型 顶部节点是项目根目录。 文本状态 对象状态： 修改的 添加 已删除 非版本化 冲突的 物业状况 SVN 存储库中的状态： 修改的 添加 已删除 冲突的 普通的 修订 修订号 冲突信息 文件冲突、属性冲突或树冲突 锁 对于锁定的对象，会显示应用锁定的用户。 例子： b.mayer 锁定评论 锁定消息 隐式、...", 
"body" : "编辑 SVN 工作副本：<项目名称> – <项目 URL> SVN 存储库中的路径 从 SVN 视图显示工作副本 项目中对象的文件和文件夹结构在此处以树视图的形式呈现。结果，对象的递归深度是可见的。 ：为以下菜单命令选择的对象 对象名称 对象的文件名 例子： Application 节点类型 顶部节点是项目根目录。 文本状态 对象状态： 修改的 添加 已删除 非版本化 冲突的 物业状况 SVN 存储库中的状态： 修改的 添加 已删除 冲突的 普通的 修订 修订号 冲突信息 文件冲突、属性冲突或树冲突 锁 对于锁定的对象，会显示应用锁定的用户。 例子： b.mayer 锁定评论 锁定消息 隐式、正常或被盗锁 网址 对象的 URL 菜单命令 选择 → 全部 选择所有文件 选择 → 无 取消选择所有文件 选择 → 修改 选择修改过的文件 选择 → 冲突 选择冲突的文件 选择 → 锁定 选择锁定的文件 更新工作副本 其他人所做的更改将从 SVN 存储库添加到您的工作副本。 更新 → 项目 更新项目的所有文件 更新→选定节点 仅更新选定的文件 更新→选定的节点和子节点 更新选定的文件和从属文件 清除 放弃对工作副本的更改 之后，该对象对应于存储库中的修订。 删除 → 选定节点 从工作副本中删除选定的对象 犯罪 将您的更改提交到 SVN 存储库 任何锁定的对象都将被解锁。 提交 → 项目 提交项目中的所有文件 提交 → 选定节点 仅提交选定的文件 提交 → 选定的节点和子节点 提交选定的文件和从属文件 管理锁的命令 锁定→重新验证所有 检查工作副本中锁的有效性 任何无效的锁都将被解锁。 锁→释放锁 释放锁 锁 → 获取锁 锁定对象不被其他人编辑 锁→偷锁 为您锁定文件并解除其他用户的锁定 提示：避免窃取锁，因为其他用户所做的更改可能会丢失。 解决冲突的命令 冲突 → 标记为已解决 表示 SVN 存储库中显示的冲突已标记并已解决 注意：如果您编辑并解决了显示的冲突，请选择该命令。之后您可以再次提交更改。 冲突→使用他们的解决 解决冲突 在 SVN 存储库中，接受其他用户提交的更改。您的更改将被丢弃。 冲突→使用我的解决 解决冲突 在 SVN 存储库中，您的工作副本的更改被接受，其他用户的更改被丢弃。 显示日志 打开 日志 - 应用程序 对话 所选节点的历史记录显示在那里。以前的修订与相应的操作一起显示。 换地点 更改工作副本中选定对象的位置 示例：您可以通过将本地对象保存到另一个位置来解决树冲突。然后更新父对象以将其应用于锁定的子对象。 更新 通过重新扫描工作副本来更新浏览器视图 清理 对工作副本执行 SVN 清理操作 " }, 
{ "title" : "命令：将项目导入SVN ", 
"url" : "_svn_cmd_import_project_to_subversion.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：将项目导入SVN ", 
"snippet" : "将项目导入 SVN 象征： 功能 ：该命令打开 将项目导入 SVN 导入对话框 CODESYS 项目到 SVN 存储库。 称呼 ： 项目 → SVN 菜单 要求 您可以访问 SVN 存储库并且知道它的 URL。 您对整个项目具有读取权限。 项目始终未加密地保存在服务器上。因此，请采取适当的安全措施（例如，对 SVN 服务器的相应权限）来保护您的项目。...", 
"body" : "将项目导入 SVN 象征： 功能 ：该命令打开 将项目导入 SVN 导入对话框 CODESYS 项目到 SVN 存储库。 称呼 ： 项目 → SVN 菜单 要求 您可以访问 SVN 存储库并且知道它的 URL。 您对整个项目具有读取权限。 项目始终未加密地保存在服务器上。因此，请采取适当的安全措施（例如，对 SVN 服务器的相应权限）来保护您的项目。 " }, 
{ "title" : "对话框：将项目导入 SVN ", 
"url" : "_svn_cmd_import_project_to_subversion.html#UUID-44f3f7d9-00f6-9d37-1b9e-f32bb786debd_section-idm43285498082810", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：将项目导入SVN \/ 对话框：将项目导入 SVN ", 
"snippet" : "SVN 仓库地址 SVN 存储库的 URL，其中包含导入文件的新项目文件夹 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：导入库时，指定扩展名 .library 或者 _library .对于项目，指定扩展名 .project 或者 _project .然后在结帐时自动识别项目类型，并在 查看 对话。 打开 存储库浏览器 对话 将显示以前的项目结构，您可以在那里对其进行编辑。 导入消息 用作日志消息的文本 例子： Control project for customer A 最近的消息 打开 最近的消息 对话 在那里您...", 
"body" : "SVN 仓库地址 SVN 存储库的 URL，其中包含导入文件的新项目文件夹 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：导入库时，指定扩展名 .library 或者 _library .对于项目，指定扩展名 .project 或者 _project .然后在结帐时自动识别项目类型，并在 查看 对话。 打开 存储库浏览器 对话 将显示以前的项目结构，您可以在那里对其进行编辑。 导入消息 用作日志消息的文本 例子： Control project for customer A 最近的消息 打开 最近的消息 对话 在那里您可以重用最后的日志消息。 生成 SVN_VERSION_INFO ： 物体 SVN_VERSION_INFO 在导入操作期间不会自动创建。因此，项目不会获得项目元数据的任何全局常量或变量。 行 在 SVN 存储库中创建当前项目并导入项目对象 当地项目在 CODESYS Development System 链接到 SVN 存储库。覆盖图标显示在对象树中。 " }, 
{ "title" : "命令：结帐 ", 
"url" : "_svn_cmd_checkout.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：结帐 ", 
"snippet" : "查看 象征： 功能 ：该命令打开 查看 对话。在那里，您可以签出存储在 SVN 存储库中的项目作为工作副本。 称呼 ： 项目 → SVN 菜单...", 
"body" : "查看 象征： 功能 ：该命令打开 查看 对话。在那里，您可以签出存储在 SVN 存储库中的项目作为工作副本。 称呼 ： 项目 → SVN 菜单 " }, 
{ "title" : "对话框：结帐 ", 
"url" : "_svn_cmd_checkout.html#UUID-12bedd2c-8deb-054f-f18b-9fd1540037d6_section-idm43264436228934", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：结帐 \/ 对话框：结帐 ", 
"snippet" : "SVN 仓库的 URL SVN 仓库中项目的 URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：一旦指定了有效的 SVN 存储库，您可以单击相邻的按钮或中的选项 修订 浏览并选择特定项目。 打开 选择存档类别 对话 该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 注意：该对话框提供的选项与 修订 团体。 打开  SVN 存储库浏览器 对话 在那里您可以浏览 SVN 存储库。...", 
"body" : "SVN 仓库的 URL SVN 仓库中项目的 URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：一旦指定了有效的 SVN 存储库，您可以单击相邻的按钮或中的选项 修订 浏览并选择特定项目。 打开 选择存档类别 对话 该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 注意：该对话框提供的选项与 修订 团体。 打开  SVN 存储库浏览器 对话 在那里您可以浏览 SVN 存储库。 结帐至 名称 工作副本的名称 例子： ControlABC.project 地点 工作副本的位置 例子： \/D:\/svn\/repository\/trunk\/ControlABC.project 结帐为 项目 项目保存为 CODESYS 项目 ” <project name>.project ”。 图书馆 项目保存为 CODESYS 库文件“ <project name>.library ”。 自动侦测 CODESYS 尝试通过扩展识别项目类型。当前实现检查项目的 URL 是否以“ _library “ 或者 ” .library \"。在这种情况下，项目被识别为库或项目。 结帐选项 省略外部 ：外部文件不会复制到工作目录。 修订 该组提供与 修订 对话。 行 从 SVN 存储库中签出项目，将其保存到本地指定位置，并在其中打开 CODESYS 作为主要项目 如果文件在导入 SVN 存储库时已加密，或者已提交，请注意以下事项： 提交到 SVN 存储库时，包含有关加密项目文件的信息。但是，不包括加密类型（密码、Wibu 安全密钥、X509 证书）。因此，可能需要在项目设置中再次加密工作副本。在这种情况下，退出命令时会打开一个对话框来通知您。然后您可以直接切换到项目设置。 " }, 
{ "title" : "命令：提交，提交项目 ", 
"url" : "_svn_cmd_commit.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：提交，提交项目 ", 
"snippet" : "提交，提交项目 象征： 功能 ：该命令提交在 CODESYS 到 SVN 存储库。这 犯罪 为此目的打开对话框。 称呼 ： 上下文菜单： SVN 准确地提交这个对象 项目 → SVN → 提交项目 菜单同时提交项目中的所有更改 要求 ：至少一个对象已被修改。其内容已被修改的对象在对象树中覆盖有 , ， 或者 象征。 当您执行该命令时，将自动解除对要提交的对象的锁定。...", 
"body" : "提交，提交项目 象征： 功能 ：该命令提交在 CODESYS 到 SVN 存储库。这 犯罪 为此目的打开对话框。 称呼 ： 上下文菜单： SVN 准确地提交这个对象 项目 → SVN → 提交项目 菜单同时提交项目中的所有更改 要求 ：至少一个对象已被修改。其内容已被修改的对象在对象树中覆盖有 , ， 或者 象征。 当您执行该命令时，将自动解除对要提交的对象的锁定。 " }, 
{ "title" : "对话框：提交 ", 
"url" : "_svn_cmd_commit.html#UUID-89952051-a32d-1684-18ac-9d7cd1f23944_id_d9b0178afa5cc0a8646329298b1e-id-e33556da8efda2b6c0a86463480accfc", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：提交，提交项目 \/ 对话框：提交 ", 
"snippet" : "提交到：<项目\/对象的 URL> SVN 存储库中的 URL 例子： file:\/\/\/D:\/SVN repository\/trunk\/ControlABC.project 日志消息 输入评论您的更改的日志消息。 例子： Bug fix error 123 最近的消息 打开 最近的消息 用于显示最后日志消息的对话框 您可以单击日志消息以接受它。 所做的更改（双击对象进行比较，右键单击对象进行更多操作） 已更改并因此可以提交的对象列表 SVN URL 反映了 SVN 存储库中对象的层次结构。 对象根据对象状态以颜色突出显示： 蓝色：修改 绿色：已添加 深红色：已删除 红色：冲突 黑色：非版本控制（...", 
"body" : "提交到：<项目\/对象的 URL> SVN 存储库中的 URL 例子： file:\/\/\/D:\/SVN repository\/trunk\/ControlABC.project 日志消息 输入评论您的更改的日志消息。 例子： Bug fix error 123 最近的消息 打开 最近的消息 用于显示最后日志消息的对话框 您可以单击日志消息以接受它。 所做的更改（双击对象进行比较，右键单击对象进行更多操作） 已更改并因此可以提交的对象列表 SVN URL 反映了 SVN 存储库中对象的层次结构。 对象根据对象状态以颜色突出显示： 蓝色：修改 绿色：已添加 深红色：已删除 红色：冲突 黑色：非版本控制（不在 SVN 存储库中） 注意：这些对象在 显示非版本化对象 选项被选中。 灰色：从提交中排除 注意：这种情况是当 提交期间忽略 选项被选中。 该列表还包含尚未修改但具有锁定的对象。这有助于防止锁在存储库中被忽视。 双击一个对象以打开比较对话框。将工作副本的修订版与基本修订版进行比较。单击时也会打开比较对话框 比较 在上下文菜单中。 右键单击对象以打开上下文菜单。 注意：当 提交项目 命令已执行，此处显示对象列表。当。。。的时候 犯罪 命令应用于特定对象时，仅显示此对象（如果已修改或锁定）及其修改或锁定的子对象。 目的 ：选择对象进行提交。 例子： 文本状态 对象状态 CODESYS 修改的 添加 已删除 非版本化 冲突的 物业状况 对象元数据的状态： 修改的 添加 已删除 冲突的 普通的 锁 如果对象有锁，则在此处显示应用锁的用户。 例子： b.mayer 描述 显示日志消息 全选\/取消全选 ：选择列表中的所有对象。 保留锁 ：您的锁定对象在提交后仍处于锁定状态。 保留更改列表 ：提交后更改列表也保留。 : 提交后更改列表不会被删除。 提交后更新（推荐） ：提交后更新对象\/项目。选中此复选框以确保项目是最新的并防止由于工作副本的混合修订而导致的冲突。 按钮 更新项目 更新项目 提示：通过提交以前更新的项目\/对象来防止冲突。 存储配置文件更新 请注意，工作副本中存储库的存储配置文件（存储版本）与 SVN 存储库中的不同。在这种情况下，提交将更改存储库中的存储配置文件。 对于需要在工作副本和存储库之间进行交换的操作，您将被相应的消息引导以匹配存储配置文件。有关这方面的更多信息，另请参阅： 检查版本配置文件的一致性行 捷径： Ctrl + 进入 首先检查工作副本 当工作副本是最新的时开始提交更改。 工作副本过期时会打开一个对话框。在那里，您可以从以下选项中进行选择： 中止提交，我想调查这个问题。 是的，我现在想更新这个项目。 继续提交，我知道我在做什么。 注意：提交的历史记录显示在 留言 看法。 消息以颜色突出显示： 蓝色：提交更改 绿色：添加对象 深红色：删除\/替换对象 黑色：其他消息（摘要） 处理外部 如果外部在同一个 SVN 存储库中，则此外部中的更改将在提交对话框中列出并与内部项目一起提交。 如果外部项目位于另一个 SVN 存储库中，则您会收到有关外部项目更改的通知，您必须单独提交这些更改。 外部有 外在 财产。 有关更多信息，请参阅： 颠覆方式的版本控制 " }, 
{ "title" : "上下文菜单（右键单击对象） ", 
"url" : "_svn_cmd_commit.html#UUID-89952051-a32d-1684-18ac-9d7cd1f23944_id_d9b0178afa5cc0a8646329298b1e-id-ad91f3ccff3d11e6a21fe76f89db3f5f", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：提交，提交项目 \/ 上下文菜单（右键单击对象） ", 
"snippet" : "比较 打开比较对话框以将工作副本与顶级修订进行比较 与 HEAD 版本比较 打开比较对话框以将工作副本与 HEAD 修订进行比较 与修订比较 列表条目根据对象状态以颜色突出显示： 蓝色：修改 绿色：已添加 深红色：已删除 红色：冲突 黑色：非版本化（不在 SVN 存储库中） 注意：这些对象在 显示非版本化对象 选项被选中。 灰色：从提交中排除 注意：这种情况是当 提交期间忽略 为对象选择了选项。 清除 放弃对工作副本的更改 之后，该对象对应于 SVN 存储库中的修订。 显示日志 显示所选对象的版本历史 特性 打开 SVN 属性 对话 那里显示属性，您可以编辑它们。 移动到更改列表 注意：该命令...", 
"body" : " 比较 打开比较对话框以将工作副本与顶级修订进行比较 与 HEAD 版本比较 打开比较对话框以将工作副本与 HEAD 修订进行比较 与修订比较 列表条目根据对象状态以颜色突出显示： 蓝色：修改 绿色：已添加 深红色：已删除 红色：冲突 黑色：非版本化（不在 SVN 存储库中） 注意：这些对象在 显示非版本化对象 选项被选中。 灰色：从提交中排除 注意：这种情况是当 提交期间忽略 为对象选择了选项。 清除 放弃对工作副本的更改 之后，该对象对应于 SVN 存储库中的修订。 显示日志 显示所选对象的版本历史 特性 打开 SVN 属性 对话 那里显示属性，您可以编辑它们。 移动到更改列表 注意：该命令尚未执行。 " }, 
{ "title" : "命令：比较 ", 
"url" : "_svn_cmd_compare.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：比较 ", 
"snippet" : "比较 象征： 功能 ：该命令打开一个选项卡，显示您的工作副本和 BASE 版本的比较结果。基础修订版是 SVN 存储库中的顶级修订版。 称呼 ： 项目 → SVN 菜单 上下文菜单 要求 : 对象是版本化的，已经在本地修改过，并且没有冲突。 可以同时打开多个标签，比较不同的对象。 按对象类型比较 比较对话框利用 项目→比较 命令在 CODESYS .因此，对象会根据其对象类型进行比较。...", 
"body" : "比较 象征： 功能 ：该命令打开一个选项卡，显示您的工作副本和 BASE 版本的比较结果。基础修订版是 SVN 存储库中的顶级修订版。 称呼 ： 项目 → SVN 菜单 上下文菜单 要求 : 对象是版本化的，已经在本地修改过，并且没有冲突。 可以同时打开多个标签，比较不同的对象。 按对象类型比较 比较对话框利用 项目→比较 命令在 CODESYS .因此，对象会根据其对象类型进行比较。 " }, 
{ "title" : "命令：与 HEAD 版本比较 ", 
"url" : "_svn_cmd_compare_with_head_revision.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：与 HEAD 版本比较 ", 
"snippet" : "与 HEAD 修订版比较 象征： 功能 ：该命令会打开一个选项卡，显示您的工作副本和 HEAD 修订版的比较结果。 HEAD 版本是分支中的顶级版本。您可以恢复提交到 HEAD 修订版的特定更改。 称呼 ： 上下文菜单： SVN 要求 : 对象是版本化的并且没有冲突。 可以同时打开多个标签，比较不同的对象。 按对象类型比较 比较对话框利用 项目→比较 命令在 CODESYS .因此，对象会根据其对象类型进行比较。...", 
"body" : "与 HEAD 修订版比较 象征： 功能 ：该命令会打开一个选项卡，显示您的工作副本和 HEAD 修订版的比较结果。 HEAD 版本是分支中的顶级版本。您可以恢复提交到 HEAD 修订版的特定更改。 称呼 ： 上下文菜单： SVN 要求 : 对象是版本化的并且没有冲突。 可以同时打开多个标签，比较不同的对象。 按对象类型比较 比较对话框利用 项目→比较 命令在 CODESYS .因此，对象会根据其对象类型进行比较。 " }, 
{ "title" : "命令：与修订比较 ", 
"url" : "_svn_cmd_compare_with_revision.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：与修订比较 ", 
"snippet" : "与修订比较 象征： 功能 ：该命令打开 项目日志 对话框或 日志 - <对象> 从项目或对象中显示版本历史记录的位置 CODESYS 项目。您可以在此处选择修订。将打开一个选项卡并显示您的工作副本和修订版本的比较结果。 称呼 ： 上下文菜单： SVN 要求 : 对象是版本化的并且没有冲突。 可以同时打开多个标签，比较不同的对象。 按对象类型比较 比较对话框利用 项目→比较 命令在 CODESYS .因此，对象会根据其对象类型进行比较。...", 
"body" : "与修订比较 象征： 功能 ：该命令打开 项目日志 对话框或 日志 - <对象> 从项目或对象中显示版本历史记录的位置 CODESYS 项目。您可以在此处选择修订。将打开一个选项卡并显示您的工作副本和修订版本的比较结果。 称呼 ： 上下文菜单： SVN 要求 : 对象是版本化的并且没有冲突。 可以同时打开多个标签，比较不同的对象。 按对象类型比较 比较对话框利用 项目→比较 命令在 CODESYS .因此，对象会根据其对象类型进行比较。 " }, 
{ "title" : "命令：与远程项目比较 ", 
"url" : "_svn_cmd_compare_to_remote_project.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：与远程项目比较 ", 
"snippet" : "与远程项目比较 象征： 功能 ：该命令打开 选择远程项目进行比较 对话。 称呼 ： 项目 → SVN 菜单...", 
"body" : "与远程项目比较 象征： 功能 ：该命令打开 选择远程项目进行比较 对话。 称呼 ： 项目 → SVN 菜单 " }, 
{ "title" : "对话框：选择远程项目进行比较 ", 
"url" : "_svn_cmd_compare_to_remote_project.html#UUID-f7dacea0-4ce3-c665-da9f-5844b3cabdef_id_f1b2d741b82e65ec0a86463067a60fa-id-ceee1711d8bc11e6a4a6ba3288cb52c9", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：与远程项目比较 \/ 对话框：选择远程项目进行比较 ", 
"snippet" : "SVN 仓库地址 被比较的 SVN 仓库中项目的 URL 例子： file:\/\/\/D:\/SVN repository\/trunk\/ControlDEF.project 提示：一旦指定了有效的 SVN 存储库，您可以单击相邻的按钮或中的选项 修订 浏览并选择特定项目。 按钮上的标签对应于选定的修订。 头 : 最新版本（最高版本） 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 点击按钮后， 选择修订 对话框打开。 注意：该对话框提供的选项与 修订 团体。 打开 浏览 SVN 存储库 搜索 SVN 存储库的对话框 结帐...", 
"body" : "SVN 仓库地址 被比较的 SVN 仓库中项目的 URL 例子： file:\/\/\/D:\/SVN repository\/trunk\/ControlDEF.project 提示：一旦指定了有效的 SVN 存储库，您可以单击相邻的按钮或中的选项 修订 浏览并选择特定项目。 按钮上的标签对应于选定的修订。 头 : 最新版本（最高版本） 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 点击按钮后， 选择修订 对话框打开。 注意：该对话框提供的选项与 修订 团体。 打开 浏览 SVN 存储库 搜索 SVN 存储库的对话框 结帐选项 省略外部 : 外部没有比较。 修订 用于选择特定修订的选项 注意：当前有效的选择也会显示在 SVN 存储库 URL 旁边。 头 ：选择了 HEAD 版本。这是分支中的最新版本（最高版本）。 修订 ：通过修订号选择特定修订。 例子： 3 日期 : 以修改日期选择具体版本。 例子： 12\/23\/2016 11:59:59 使用 UTC 时间 : 通用时间的修改日期 比较选项 忽略空格 : 不比较空白字符 无论如何都会比较语义相关的空格，例如字符串中的空格。 忽略评论 : 没有比较评论 忽略属性 : 没有比较属性 文件夹，属性 从构建中排除 , 和 POU 图像不进行比较。 请参阅：“属性”对话框 行 将 SVN 项目与工作副本进行比较 " }, 
{ "title" : "命令：包括外部项目，包括外部项目 ", 
"url" : "_svn_cmd_include_external_objects.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：包括外部项目，包括外部项目 ", 
"snippet" : "包括外部项目，包括外部项目 象征： 功能 ：这些命令打开 包括外部 对话。 称呼 ： 项目 → SVN 菜单 上下文菜单： SVN 要求 ：在对象树中选择了一个对象。外部集成在其下方。如果您没有选择任何内容或项目根目录，则 包括项目的外部 命令可用。如果您选择了一个对象，那么命令 包括外部 可用。 不能在同一项目的不同位置多次集成相同的外部组件。由于与对象的内部标识冲突，这会导致 CODESYS 出现问题。...", 
"body" : "包括外部项目，包括外部项目 象征： 功能 ：这些命令打开 包括外部 对话。 称呼 ： 项目 → SVN 菜单 上下文菜单： SVN 要求 ：在对象树中选择了一个对象。外部集成在其下方。如果您没有选择任何内容或项目根目录，则 包括项目的外部 命令可用。如果您选择了一个对象，那么命令 包括外部 可用。 不能在同一项目的不同位置多次集成相同的外部组件。由于与对象的内部标识冲突，这会导致 CODESYS 出现问题。 " }, 
{ "title" : "对话框：包括外部 ", 
"url" : "_svn_cmd_include_external_objects.html#UUID-06e0b534-536b-8c18-f0ef-15f8d6e1d1a6_id_d937af491b8e5dc9c0a8646303667dc5-id-ceee1711d8bc11e6a4a6ba3288cb52c9", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：包括外部项目，包括外部项目 \/ 对话框：包括外部 ", 
"snippet" : "SVN 仓库的 URL 集成的外部 URL 要集成的对象是版本化的，可以有子对象。 外部项目位于 SVN 存储库中的另一个位置，而不是项目。它甚至可以在另一个 SVN 存储库中。 例子： file:\/\/\/D:\/SVN repo A\/trunk\/DSTest.project\/GlobalTextList 注意：应集成在所选对象下方的对象必须具有匹配的对象类型。例如，只能将一项任务集成到 任务配置 目的。 打开 选择存档类别 对话 您可以在此处选择修订。 该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 ...", 
"body" : "SVN 仓库的 URL 集成的外部 URL 要集成的对象是版本化的，可以有子对象。 外部项目位于 SVN 存储库中的另一个位置，而不是项目。它甚至可以在另一个 SVN 存储库中。 例子： file:\/\/\/D:\/SVN repo A\/trunk\/DSTest.project\/GlobalTextList 注意：应集成在所选对象下方的对象必须具有匹配的对象类型。例如，只能将一项任务集成到 任务配置 目的。 打开 选择存档类别 对话 您可以在此处选择修订。 该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 注意：该对话框提供的选项与 修订 团体。 打开 SVN 存储库浏览器 对话 在那里您可以浏览 SVN 存储库。 修订 选择修订的选项 注意：当前有效的选择也显示在 SVN 存储库 URL 旁边的按钮中。 头 ：在分支中选择的最新版本（最高版本） 修订 ：通过修订号的特定修订 例子： 3 日期 : 修改日期前的具体修改 例子： 12\/23\/2016 11:59:59 使用 UTC 时间 : 通用时间的修改日期 行 使用属性添加外部及其子对象 svn:externals 到您的项目（在所选对象下方） 工作副本已更新，外部覆盖了 象征。 例子： （外接设备 Source ) 注意：如果链接失败（例如在任务配置下添加设备时），则整个操作将失败并恢复。 注意：仅允许在“外部树”内重命名或移动单个外部对象，因此不允许移动顶部对象。 要移动整棵树，您必须将其移除并将其链接到另一个位置。 “......您应该认真考虑在所有外部定义中使用明确的修订号。这样做意味着您可以决定何时拉下外部信息的不同快照，以及确切地拉出哪个快照。除了避免意外对您可能无法控制的第三方存储库进行更改，使用明确的修订号也意味着当您将工作副本回溯到之前的修订时，您的外部定义也将恢复到它们在之前的修订中的样子，这反过来意味着外部工作副本将被更新以匹配它们在您的存储库处于先前版本时回顾的方式。对于软件项目，这可能是您的旧快照的成功和失败构建之间的区别复杂的代码库……” 引用自： http:\/\/svnbook.red-bean.com\/nightly\/en\/svn.advanced.externals.html " }, 
{ "title" : "命令：提交时忽略 ", 
"url" : "_svn_cmd_ignore_on_commit.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：提交时忽略 ", 
"snippet" : "提交时忽略 功能 ：该命令识别一个对象并将其添加到“ignore-on-commit”列表中。然后默认情况下在提交对话框中将其停用。 称呼 ： SVN 菜单 要求 : 至少有一个可用的对象不在更改列表中 ignore-on-comment . “ignore-on-commit”列表的对象覆盖有 对象树中的符号。默认情况下，它们不会在提交对话框中被选中，除非所选对象的依赖项需要它。这些对象始终可以在对话框中手动选择。...", 
"body" : "提交时忽略 功能 ：该命令识别一个对象并将其添加到“ignore-on-commit”列表中。然后默认情况下在提交对话框中将其停用。 称呼 ： SVN 菜单 要求 : 至少有一个可用的对象不在更改列表中 ignore-on-comment . “ignore-on-commit”列表的对象覆盖有 对象树中的符号。默认情况下，它们不会在提交对话框中被选中，除非所选对象的依赖项需要它。这些对象始终可以在对话框中手动选择。 " }, 
{ "title" : "命令：SVN信息 ", 
"url" : "_svn_cmd_svn_info.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：SVN信息 ", 
"snippet" : "SVN信息 功能 ：该命令提供有关 SVN 存储库中选定对象的信息。这 SVN信息 对话框打开以执行此操作。 称呼 ： 上下文菜单： SVN 要求 ：在对象树中选择了版本化对象（带有 SVN 链接）。 对话框：SVN 信息 例子 Name: Device_4\\Plc Logic\\Application\\PLC_PRG URL: file:\/\/\/D:\/SVN repository\/trunk\/ControlABC.project\/Device\/Plc Logic\/Application\/PLC_PRG\/svnobj Repository Root: file:\/\/\/D:\/SVN reposito...", 
"body" : "SVN信息 功能 ：该命令提供有关 SVN 存储库中选定对象的信息。这 SVN信息 对话框打开以执行此操作。 称呼 ： 上下文菜单： SVN 要求 ：在对象树中选择了版本化对象（带有 SVN 链接）。 对话框：SVN 信息 例子 Name: Device_4\\Plc Logic\\Application\\PLC_PRG\nURL: file:\/\/\/D:\/SVN repository\/trunk\/ControlABC.project\/Device\/Plc Logic\/Application\/PLC_PRG\/svnobj\nRepository Root: file:\/\/\/D:\/SVN repository\/\nRepository UUID: 185325d7-73eb-e54b-ab50-206aa23c8b42\nRevision: 29\nNode Kind: File\nSchedule: Normal\nLast Changed Author: a.mayer\nLast Changed Rev: 8\nLast Changed Date: 17.01.2017 12:33:51\nText Last Updated: 17.01.2017 12:33:51\nChecksum: d5fb4d91ebaea06f26bcdb15942724d57932b6a3 " }, 
{ "title" : "命令：显示属性 ", 
"url" : "_svn_cmd_show_properties.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：显示属性 ", 
"snippet" : "显示属性 象征： 功能 ：该命令打开 SVN 属性 对话。您可以在此处编辑版本化对象的属性。 称呼 ： 上下文菜单： SVN 要求 ：选择了一个版本化的、未锁定的对象。...", 
"body" : "显示属性 象征： 功能 ：该命令打开 SVN 属性 对话。您可以在此处编辑版本化对象的属性。 称呼 ： 上下文菜单： SVN 要求 ：选择了一个版本化的、未锁定的对象。 " }, 
{ "title" : "对话框：SVN 属性 ", 
"url" : "_svn_cmd_show_properties.html#UUID-396b58cb-c13c-1d99-1a28-686b7752a816_section-idm43257679000916", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：显示属性 \/ 对话框：SVN 属性 ", 
"snippet" : "属性：<对象名称> 名称 物业名称 例子： myprop:customer-number 注意：SVN 有一些保留属性。例子： svn:mime-type 价值 例子： 1234 双击该字段以编辑该值。 添加 打开一个对话框以定义另一个属性及其值 消除 删除选定的属性 显示二进制属性 : 也显示二进制属性。 重启 还原以绿色显示的更改 行 接受更改...", 
"body" : "属性：<对象名称> 名称 物业名称 例子： myprop:customer-number 注意：SVN 有一些保留属性。例子： svn:mime-type 价值 例子： 1234 双击该字段以编辑该值。 添加 打开一个对话框以定义另一个属性及其值 消除 删除选定的属性 显示二进制属性 : 也显示二进制属性。 重启 还原以绿色显示的更改 行 接受更改 " }, 
{ "title" : "命令：获取锁 ", 
"url" : "_svn_cmd_acquire_lock.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：获取锁 ", 
"snippet" : "获取锁 象征： 功能 ：该命令为您显式锁定对象。这 锁定消息 为此目的打开对话框。 称呼 ： 上下文菜单： SVN 要求 ：版本化对象未锁定（未覆盖 象征）。...", 
"body" : "获取锁 象征： 功能 ：该命令为您显式锁定对象。这 锁定消息 为此目的打开对话框。 称呼 ： 上下文菜单： SVN 要求 ：版本化对象未锁定（未覆盖 象征）。 " }, 
{ "title" : "对话框：锁定消息 ", 
"url" : "_svn_cmd_acquire_lock.html#UUID-fd93cc1d-79d3-ddcc-8502-4fb05e22a3df_id_d0b7e8d91b918818c0a8646373415cd1-id-f3fda65a82afaba0c0a864631f57ae3d", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：获取锁 \/ 对话框：锁定消息 ", 
"snippet" : "输入锁定对象的原因： 锁定消息 例子： Locked for processing task 123 按钮 最近的消息 在对话框中显示已使用的消息 在那里您选择一个以使用锁定消息。 递归的 ：对象和所有从属（子）对象都被锁定。 行 锁定对象 当锁定成功时，对象（在对象树中）被覆盖 象征。...", 
"body" : "输入锁定对象的原因： 锁定消息 例子： Locked for processing task 123 按钮 最近的消息 在对话框中显示已使用的消息 在那里您选择一个以使用锁定消息。 递归的 ：对象和所有从属（子）对象都被锁定。 行 锁定对象 当锁定成功时，对象（在对象树中）被覆盖 象征。 " }, 
{ "title" : "命令：偷锁 ", 
"url" : "_svn_cmd_steal_lock.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：偷锁 ", 
"snippet" : "偷锁 象征： 功能 ：当对象和所有依赖对象也处于锁定状态时，该命令会窃取这些对象的锁定。 锁定消息 为此，将打开一个对话框。但是，依赖对象不会显示在此对话框中。 称呼 ： 上下文菜单： SVN 要求 ：版本化对象被其他人锁定（覆盖有 象征）。...", 
"body" : "偷锁 象征： 功能 ：当对象和所有依赖对象也处于锁定状态时，该命令会窃取这些对象的锁定。 锁定消息 为此，将打开一个对话框。但是，依赖对象不会显示在此对话框中。 称呼 ： 上下文菜单： SVN 要求 ：版本化对象被其他人锁定（覆盖有 象征）。 " }, 
{ "title" : "对话框：锁定消息 ", 
"url" : "_svn_cmd_steal_lock.html#UUID-dd36d897-75aa-c1c7-3c1e-8096218dc820_id_cb38e12b1b92ce18c0a8646371a0c336-id-f3fda65a82afaba0c0a864631f57ae3d", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：偷锁 \/ 对话框：锁定消息 ", 
"snippet" : "输入锁定对象的原因： 锁定消息 例子： a.mayer had to steal the lock because the changes need to be implemented so urgently. 最近的消息 在对话框中显示已使用的消息 在那里您选择一个以使用锁定消息。 递归的 ：从该对象和所有下属（子）对象以及所有依赖对象中窃取锁。 行 偷锁 当被盗锁成功时，对象（在对象树中）与 象征。...", 
"body" : "输入锁定对象的原因： 锁定消息 例子： a.mayer had to steal the lock because the changes need to be implemented so urgently. 最近的消息 在对话框中显示已使用的消息 在那里您选择一个以使用锁定消息。 递归的 ：从该对象和所有下属（子）对象以及所有依赖对象中窃取锁。 行 偷锁 当被盗锁成功时，对象（在对象树中）与 象征。 " }, 
{ "title" : "命令：释放锁定 ", 
"url" : "_svn_cmd_release_lock.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：释放锁定 ", 
"snippet" : "释放锁 象征： 功能 ：该命令释放对象的锁。 称呼 ： 上下文菜单 → SVN 要求 : 对象被锁定。...", 
"body" : "释放锁 象征： 功能 ：该命令释放对象的锁。 称呼 ： 上下文菜单 → SVN 要求 : 对象被锁定。 " }, 
{ "title" : "命令：递归释放锁 ", 
"url" : "_svn_cmd_release_locks_recursively.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：递归释放锁 ", 
"snippet" : "递归释放锁 象征： 功能 ：该命令显式释放对象及其所有从属对象的锁定。 称呼 ： 上下文菜单 → SVN 要求 : 对象被锁定。...", 
"body" : "递归释放锁 象征： 功能 ：该命令显式释放对象及其所有从属对象的锁定。 称呼 ： 上下文菜单 → SVN 要求 : 对象被锁定。 " }, 
{ "title" : "命令：显示日志，显示项目日志 ", 
"url" : "_svn_cmd_show_log.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：显示日志，显示项目日志 ", 
"snippet" : "显示日志，显示项目日志 象征： 功能 ：这些命令打开选项卡 项目日志 或者 日志 - <对象> .项目或对象的版本历史 CODESYS 项目显示在选项卡上。 称呼 ： 项目 → SVN 菜单 上下文菜单 → SVN 如果您在对象树中不选择任何内容或选择基本节点，则会显示整个项目的历史记录（ 显示项目日志 ）。如果您选择一个或多个对象，则会显示这些元素的历史记录 ( 显示日志 ）。 可以同时打开多个选项卡，其中包含不同对象的版本历史记录。...", 
"body" : "显示日志，显示项目日志 象征： 功能 ：这些命令打开选项卡 项目日志 或者 日志 - <对象> .项目或对象的版本历史 CODESYS 项目显示在选项卡上。 称呼 ： 项目 → SVN 菜单 上下文菜单 → SVN 如果您在对象树中不选择任何内容或选择基本节点，则会显示整个项目的历史记录（ 显示项目日志 ）。如果您选择一个或多个对象，则会显示这些元素的历史记录 ( 显示日志 ）。 可以同时打开多个选项卡，其中包含不同对象的版本历史记录。 " }, 
{ "title" : "标签：项目日志；对话框：日志 - <object> ", 
"url" : "_svn_cmd_show_log.html#UUID-367f850e-11b9-b920-8bd8-e3e447c99438_section-idm43257681277688", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：显示日志，显示项目日志 \/ 标签：项目日志；对话框：日志 - <object> ", 
"snippet" : "上部区域 修订 : 修订号 作者 日期 信息 ：提交时输入的消息 项目的所有修订或信息中选定对象的列表 默认情况下，显示前 100 个修订。这 下一个 100 和 全部 提供按钮用于显示更多或所有修订。 每个版本的上下文菜单中都有几个命令可用。这些上下文菜单命令如下所述。 中区 显示的 信息 在上部区域中选择的修订版本 下部区域 行动 小路 : SVN 中的对象路径 从路径复制 从修订中复制 对选定修订中的项目对象执行的操作列表 隐藏不相关的更改路径 ：此修订的所有更改都被隐藏，与对象没有任何关系。 停止复制\/重命名 ：如果对象是从 SVN 存储库中的另一个位置复制的，则不再检索到日志消息。当...", 
"body" : "上部区域 修订 : 修订号 作者 日期 信息 ：提交时输入的消息 项目的所有修订或信息中选定对象的列表 默认情况下，显示前 100 个修订。这 下一个 100 和 全部 提供按钮用于显示更多或所有修订。 每个版本的上下文菜单中都有几个命令可用。这些上下文菜单命令如下所述。 中区 显示的 信息 在上部区域中选择的修订版本 下部区域 行动 小路 : SVN 中的对象路径 从路径复制 从修订中复制 对选定修订中的项目对象执行的操作列表 隐藏不相关的更改路径 ：此修订的所有更改都被隐藏，与对象没有任何关系。 停止复制\/重命名 ：如果对象是从 SVN 存储库中的另一个位置复制的，则不再检索到日志消息。当监控分支或标签并且只有分支内的更改相关时，这尤其有用。 过滤器\/范围 打开 筛选 对话 全部 列出所有修订。 下一个 100 列出了接下来的 100 个修订。 筛选 对话 修订范围 显示的修订可以通过过滤 头 , 修订 ， 或者 日期 . : 选项字段 开始修订 和 结束修订 是可编辑的。 使用 UTC 时间 : 以通用时间显示日期 有关更多信息，请参阅： 选择修订消息包含 显示包含特殊文本的修订日志 信息 作者包含 显示指定作者的修订日志 路径包含 显示指定路径的修订日志 修订的上下文菜单命令 与基本工作副本比较 将对象的选定修订版与基本工作副本进行比较（无本地更改） 与工作副本比较 将对象的选定修订版与工作副本进行比较 与 HEAD 版本比较 将对象的选定版本与 HEAD 版本进行比较 与以前的版本比较 将对象的选定修订版与之前的修订版进行比较 将项目更新为修订 将对象更新到选定的修订版 注意：无法提交通过此命令对项目所做的更改。 对于 VSS 用户：这相当于加载旧版本而不签出。要恢复以前的提交， 恢复到此版本 必须使用命令。 恢复到此版本 将对象还原为选定的修订版 只要未提交更改，此命令就不会对 SVN 存储库产生影响。在内部，SVN 恢复在选定修订之后所做的所有更改的合并，以恢复先前提交的更改。 编辑作者 打开用于更改修订作者的对话框 编辑日志消息 打开用于更改修订日志消息的对话框 修订属性 打开 修订属性 显示属性的对话框 在对话框中，您可以激活 添加 和 消除 属性和 显示二进制属性 选项。 从此版本创建分支\/标签 从选定的修订版创建分支或标签 浏览 SVN 存储库 打开 SVN 存储库浏览器 对话 复制到剪贴板 将所选修订的日志详细信息复制到剪贴板 这是修订号、作者、修订日期、日志消息以及每个修订的更改对象列表。 " }, 
{ "title" : "命令：还原，还原项目 ", 
"url" : "_svn_cmd_revert.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：还原，还原项目 ", 
"snippet" : "还原，还原项目 象征： 功能 ：该命令打开 恢复 对话。在对话框中，选择应恢复其本地更改的对象，以及恢复到工作副本基本修订状态的对象。 称呼 ： 项目 → SVN 菜单 上下文菜单 → SVN 如果您在设备树中未选择任何内容或选择主节点，则所有修改的对象都会在此对话框中列出 ( 还原项目 ）。如果您选择了一个或多个对象，则仅列出对此对象的更改并递归地列出它们的子对象 ( 恢复 ）。...", 
"body" : "还原，还原项目 象征： 功能 ：该命令打开 恢复 对话。在对话框中，选择应恢复其本地更改的对象，以及恢复到工作副本基本修订状态的对象。 称呼 ： 项目 → SVN 菜单 上下文菜单 → SVN 如果您在设备树中未选择任何内容或选择主节点，则所有修改的对象都会在此对话框中列出 ( 还原项目 ）。如果您选择了一个或多个对象，则仅列出对此对象的更改并递归地列出它们的子对象 ( 恢复 ）。 " }, 
{ "title" : "对话框：还原 ", 
"url" : "_svn_cmd_revert.html#UUID-d1578298-5d01-aff6-73fa-7e97396a603c_id_e4362e201ba3d536c0a864632cbebc40-id-96a5b119635a8e3bc0a8640e005df4c1", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：还原，还原项目 \/ 对话框：还原 ", 
"snippet" : "组外部 ：外部定义根据其外部位置分组显示。 保留锁 ：对revert命令修改的所有文件保留锁定。 全选\/取消全选 当外部被删除时， CODESYS SVN 无法在 SVN 离线模式下恢复此数据。提示用户如何继续： 切换回SVN在线模式并调用外部。 现在连接到 SVN 服务器一次以完成当前操作，但之后切换回 SVN 离线模式。 跳过外部的检索。稍后可以通过更新项目来获取它们。...", 
"body" : "组外部 ：外部定义根据其外部位置分组显示。 保留锁 ：对revert命令修改的所有文件保留锁定。 全选\/取消全选 当外部被删除时， CODESYS SVN 无法在 SVN 离线模式下恢复此数据。提示用户如何继续： 切换回SVN在线模式并调用外部。 现在连接到 SVN 服务器一次以完成当前操作，但之后切换回 SVN 离线模式。 跳过外部的检索。稍后可以通过更新项目来获取它们。 " }, 
{ "title" : "命令：恢复到修订版，将项目恢复到修订版 ", 
"url" : "_svn_cmd_revert_to_revision.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：恢复到修订版，将项目恢复到修订版 ", 
"snippet" : "恢复到修订版，将项目恢复到修订版 象征： 功能 ：该命令打开 选择修订 对话。在此对话框中，您可以选择项目或选定对象恢复到的版本。 称呼 ： 项目 → SVN 上下文菜单 → SVN 如果在对象树中未标记任何内容或基本节点，则整个项目将恢复为特定修订版 ( 将项目恢复到修订版 ）。如果选择了一个或多个对象，则这些对象及其子对象将被还原 ( 恢复到修订 ）。 对话框：选择修订 有关对话框的说明，请参见“选择修订版”一章。...", 
"body" : "恢复到修订版，将项目恢复到修订版 象征： 功能 ：该命令打开 选择修订 对话。在此对话框中，您可以选择项目或选定对象恢复到的版本。 称呼 ： 项目 → SVN 上下文菜单 → SVN 如果在对象树中未标记任何内容或基本节点，则整个项目将恢复为特定修订版 ( 将项目恢复到修订版 ）。如果选择了一个或多个对象，则这些对象及其子对象将被还原 ( 恢复到修订 ）。 对话框：选择修订 有关对话框的说明，请参见“选择修订版”一章。 " }, 
{ "title" : "命令：更新，更新项目 ", 
"url" : "_svn_cmd_update.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：更新，更新项目 ", 
"snippet" : "更新，更新项目 象征： 功能 ：该命令将 SVN 存储库中的更改提交到项目。使用 HEAD 修订执行更新。 称呼 ： 项目 → SVN 菜单 上下文菜单 → SVN 如果没有选择或选择主节点，则更新整个项目（ 更新项目 ）。如果选择了一个或多个对象，则更新这些对象及其子对象 ( 更新 SVN ）。 以下情况是可能的： 将项目添加到 SVN 存储库中存在的项目，但不在项目中。在这种情况下，消息视图中会显示消息“已添加 <object>”。 不再存在于 SVN 存储库中但在本地项目中存在（且未标记为“已添加”）的对象，将根据 Subversion 标准过程进行处理：如果存在本地更改，则该对象保留在...", 
"body" : "更新，更新项目 象征： 功能 ：该命令将 SVN 存储库中的更改提交到项目。使用 HEAD 修订执行更新。 称呼 ： 项目 → SVN 菜单 上下文菜单 → SVN 如果没有选择或选择主节点，则更新整个项目（ 更新项目 ）。如果选择了一个或多个对象，则更新这些对象及其子对象 ( 更新 SVN ）。 以下情况是可能的： 将项目添加到 SVN 存储库中存在的项目，但不在项目中。在这种情况下，消息视图中会显示消息“已添加 <object>”。 不再存在于 SVN 存储库中但在本地项目中存在（且未标记为“已添加”）的对象，将根据 Subversion 标准过程进行处理：如果存在本地更改，则该对象保留在项目中未版本化。如果没有本地更改，则对象也会在本地删除，因为用户可以随时从旧版本中检索对象。在这种情况下，消息视图中会显示“已删除对象”。 如果 SVN 存储库和项目中存在的版本化对象不同，则会更新它们。有三种情况需要考虑： 自上次更新以来未进行任何本地更改：在这种情况下，本地对象被 SVN 存储库中的内容覆盖。讯息 对象已更新 显示在消息视图中。 自上次更新以来已进行了本地更改，并且可以合并相应的对象类型。版本合并成功后，消息 合并的对象 显示在消息视图中。如果命令未成功执行，则在对象树中将该对象标记为“冲突对象”，并显示消息 冲突对象 被陈列。 自上次更新以来已进行了本地更改，无法合并相应的对象类型。在这种情况下，对象在对象树和消息中被标记为“冲突对象” 冲突对象 被陈列。 如果只更新了部分对象，则可能是已经存在同名对象。例如，这种情况可能来自将对象移动到文件夹。 对于这种冲突，您可以采取以下措施： 什么也不做，让冲突的对象保持原样。 更新（并删除）冲突对象以解决冲突。 更新整个项目以删除所有冲突对象并解决冲突。 " }, 
{ "title" : "命令：更新到修订 ", 
"url" : "_svn_cmd_update_to_revision.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：更新到修订 ", 
"snippet" : "更新到修订 象征： 功能 ：该命令打开 更新 对话。在对话框中，为更新项目定义了修订。 称呼 ： 项目 → SVN 上下文菜单 → SVN 如果您在对象树中未选择任何内容或选择基本节点，则整个项目将更新为修订版 ( 将项目更新为修订 ）。如果您选择一个或多个对象，则这些对象会被更新，并且它们的子对象会递归更新（ 更新到修订 ）。或者，您可以定义不更新子对象。 更新过程的行为（例如，冲突的合并）类似于 更新项目 和 更新 命令。...", 
"body" : "更新到修订 象征： 功能 ：该命令打开 更新 对话。在对话框中，为更新项目定义了修订。 称呼 ： 项目 → SVN 上下文菜单 → SVN 如果您在对象树中未选择任何内容或选择基本节点，则整个项目将更新为修订版 ( 将项目更新为修订 ）。如果您选择一个或多个对象，则这些对象会被更新，并且它们的子对象会递归更新（ 更新到修订 ）。或者，您可以定义不更新子对象。 更新过程的行为（例如，冲突的合并）类似于 更新项目 和 更新 命令。 " }, 
{ "title" : "对话框：更新 ", 
"url" : "_svn_cmd_update_to_revision.html#UUID-eea3025d-ff0a-e6de-5309-6844a056d7a9_id_b611d1ba55c2ec0a8646350aede38-id-fd1438f792696f39c0a8646335e2b0f0", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：更新到修订 \/ 对话框：更新 ", 
"snippet" : "头 ：该命令的行为与 更新 和 更新项目 命令。 修订 ：最后更新的版本由版本号选择。 : 打开 日志 用于选择修订的对话框 日期 ：最后一次更新的版本，按修改日期选择。 使用 UTC 时间 ： ：日期以通用时间显示。 递归的 ： 默认设置 选定的部分会递归更新。这意味着所选对象下方的所有元素也会更新。 省略外部 : 外部没有更新。...", 
"body" : "头 ：该命令的行为与 更新 和 更新项目 命令。 修订 ：最后更新的版本由版本号选择。 : 打开 日志 用于选择修订的对话框 日期 ：最后一次更新的版本，按修改日期选择。 使用 UTC 时间 ： ：日期以通用时间显示。 递归的 ： 默认设置 选定的部分会递归更新。这意味着所选对象下方的所有元素也会更新。 省略外部 : 外部没有更新。 " }, 
{ "title" : "命令：仅更新此 ", 
"url" : "_svn_cmd_update_only_this.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：仅更新此 ", 
"snippet" : "只更新这个 象征： 功能 ：该命令更新选定的对象。不同于以往 更新 和 更新到修订 命令，子对象不会更新。 称呼 ： 上下文菜单 → SVN...", 
"body" : "只更新这个 象征： 功能 ：该命令更新选定的对象。不同于以往 更新 和 更新到修订 命令，子对象不会更新。 称呼 ： 上下文菜单 → SVN " }, 
{ "title" : "命令：断开项目与 Subversion 的连接 ", 
"url" : "_svn_cmd_disconnect_from_subversion.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：断开项目与 Subversion 的连接 ", 
"snippet" : "断开项目与 Subversion 的连接 象征： 功能 ：该命令通过将项目转换为非版本化项目来删除当前项目与SVN的所有连接。 称呼 ： 项目 → SVN 菜单 由于此操作无法撤消，因此必须在执行命令之前确认该操作。 使用 连接到现有项目 稍后再次连接到 SVN 存储库的命令。...", 
"body" : "断开项目与 Subversion 的连接 象征： 功能 ：该命令通过将项目转换为非版本化项目来删除当前项目与SVN的所有连接。 称呼 ： 项目 → SVN 菜单 由于此操作无法撤消，因此必须在执行命令之前确认该操作。 使用 连接到现有项目 稍后再次连接到 SVN 存储库的命令。 " }, 
{ "title" : "命令：切换到 ", 
"url" : "_svn_cmd_switch.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：切换到 ", 
"snippet" : "切换到 象征： 功能 ：该命令打开 SVN 交换机 对话。在对话框中，您在 SVN 存储库中指定一个 URL，项目的当前工作副本将更新到该 URL。该命令将项目从一个分支或标签切换到另一个。 称呼 ： 项目 → SVN 菜单 要求 : 项目是版本化的。...", 
"body" : "切换到 象征： 功能 ：该命令打开 SVN 交换机 对话。在对话框中，您在 SVN 存储库中指定一个 URL，项目的当前工作副本将更新到该 URL。该命令将项目从一个分支或标签切换到另一个。 称呼 ： 项目 → SVN 菜单 要求 : 项目是版本化的。 " }, 
{ "title" : "对话框：SVN 切换 ", 
"url" : "_svn_cmd_switch.html#UUID-1514a3c4-ac54-7a40-bad7-805828cec6df_section-idm43264436861734", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：切换到 \/ 对话框：SVN 切换 ", 
"snippet" : "从 项目当前SVN URL 到 SVN中目标URL的输入字段 头 ： 这 选择修订 对话框打开。 ： 对话 SVN 存储库浏览器 打开。您可以在此处选择 SVN 项目存档中的目标 URL。...", 
"body" : "从 项目当前SVN URL 到 SVN中目标URL的输入字段 头 ： 这 选择修订 对话框打开。 ： 对话 SVN 存储库浏览器 打开。您可以在此处选择 SVN 项目存档中的目标 URL。 " }, 
{ "title" : "命令：提交时取消忽略 ", 
"url" : "_svn_cmd_unignore_on_commit.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：提交时取消忽略 ", 
"snippet" : "提交时取消忽略 功能 ：该命令从“忽略列表”中删除一个未版本控制的对象，以便在提交时默认检查该对象。 称呼 ： 上下文菜单： SVN 要求 ： 这 提交时忽略 命令已针对该对象执行，并且该对象被标记为 象征。...", 
"body" : "提交时取消忽略 功能 ：该命令从“忽略列表”中删除一个未版本控制的对象，以便在提交时默认检查该对象。 称呼 ： 上下文菜单： SVN 要求 ： 这 提交时忽略 命令已针对该对象执行，并且该对象被标记为 象征。 " }, 
{ "title" : "命令：SVN 清理 ", 
"url" : "_svn_cmd_cleanup.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：SVN 清理 ", 
"snippet" : "SVN 清理 功能 ：该命令打开 SVN 清理 对话。在对话框中，您可以定义清理 SVN 工作副本时执行的操作。 称呼 ： 项目 → SVN 菜单...", 
"body" : "SVN 清理 功能 ：该命令打开 SVN 清理 对话。在对话框中，您可以定义清理 SVN 工作副本时执行的操作。 称呼 ： 项目 → SVN 菜单 " }, 
{ "title" : "对话框：SVN 清理 ", 
"url" : "_svn_cmd_cleanup.html#UUID-83dfea4c-a6ea-677f-9708-1e45c52695f3_id_b54507a1ba97bc0c0a86463026bf32b-id-d3bb2e8597f57b68c0a86463150371fe", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：SVN 清理 \/ 对话框：SVN 清理 ", 
"snippet" : "内部 SVN 工作副本 更新时间戳（加速 SVN 状态显示） ：更正工作目录中未更改文件的记录时间戳，从而减少未来检查的比较时间 在正常工作流程中，无需定期执行此操作。 真空缓存的原始副本（可能会减小项目文件的大小） ：通过删除当前项目不再引用的旧版本来清理原始副本的缓冲区 优点：减小了项目文件的大小。缺点：如果降级到旧版本，或者在不同分支之间切换，则检索到的数据大小会增加。 清除工作队列并强制解锁 SVN 内部数据结构（仅限紧急情况！） : 清理内部 SVN 任务队列并解锁内部 SVN 数据结构 在正常工作期间，这绝不是必要的 CODESYS SVN . 注意：仅当由于锁定的工作副本而导致 ...", 
"body" : "内部 SVN 工作副本 更新时间戳（加速 SVN 状态显示） ：更正工作目录中未更改文件的记录时间戳，从而减少未来检查的比较时间 在正常工作流程中，无需定期执行此操作。 真空缓存的原始副本（可能会减小项目文件的大小） ：通过删除当前项目不再引用的旧版本来清理原始副本的缓冲区 优点：减小了项目文件的大小。缺点：如果降级到旧版本，或者在不同分支之间切换，则检索到的数据大小会增加。 清除工作队列并强制解锁 SVN 内部数据结构（仅限紧急情况！） : 清理内部 SVN 任务队列并解锁内部 SVN 数据结构 在正常工作期间，这绝不是必要的 CODESYS SVN . 注意：仅当由于锁定的工作副本而导致 SVN 命令发生错误时，才使用此选项。在这种情况下，它指的是错误 CODESYS SVN .然后向我们发送错误报告（如果可能，请重复步骤）到 CODESYS 支持。 信息：这些是“管理锁”，它们是 SVN 工作副本中的内部锁。这些锁不是由上下文菜单命令设置的。有关详细信息，请参阅“锁的三种含义”部分： http:\/\/svnbook.red-bean.com\/en\/1.8\/svn.advanced.locking.html 项目内容 还原所有本地更改（小心使用！） 将所有本地更改恢复到 SVN 存储库中的原始状态 释放所有锁 释放项目中的所有“咨询锁”（用户可见的锁） 这些锁被激活 获取锁 和 偷锁 . 重新验证存储库的所有锁（它们可能已被盗） 例如，检查本地可用的咨询锁是否仍然有效或已被其他人窃取 所有无效的锁都被删除。 状态缓存 清除所有缓存并刷新状态图标 删除所有内部缓存 CODESYS SVN 拥有并更新状态图标 仅当它发出错误时才需要 CODESYS SVN 缓存或状态显示不一致 " }, 
{ "title" : "命令：清除认证数据 ", 
"url" : "_svn_cmd_clear_authentication_data.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：清除认证数据 ", 
"snippet" : "清除身份验证数据 功能 ：该命令打开 编码系统 对话。在此对话框中，您定义将被删除的缓存。 称呼 ： 项目 → SVN 菜单...", 
"body" : "清除身份验证数据 功能 ：该命令打开 编码系统 对话。在此对话框中，您定义将被删除的缓存。 称呼 ： 项目 → SVN 菜单 " }, 
{ "title" : "对话： CODESYS ", 
"url" : "_svn_cmd_clear_authentication_data.html#UUID-a5fe54fa-d37c-1282-93bf-710d198db065_id_e82c2b1baa2d9ec0a864630e1d06aa-id-4926fc1b97bb4127c0a864636d0fa58b", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：清除认证数据 \/ 对话： CODESYS ", 
"snippet" : "认证存储器包含用户选择用于保存授权数据的所有SVN存储库的认证数据。该内存被此命令完全删除。 清除共享的磁盘缓存。 : 保存在计算机上的数据被删除。 清除此实例的 RAM 缓存。 : 保存在 RAM 中的数据被删除。 保存在计算机上的认证数据存储在 %APPDATA%\\Subversion\\auth .此内存路径也用于大多数其他 Subversion 客户端应用程序（例如，TortoiseSVN 和 AnkhSVN）。因此，删除身份验证数据也会影响这些应用程序。...", 
"body" : "认证存储器包含用户选择用于保存授权数据的所有SVN存储库的认证数据。该内存被此命令完全删除。 清除共享的磁盘缓存。 : 保存在计算机上的数据被删除。 清除此实例的 RAM 缓存。 : 保存在 RAM 中的数据被删除。 保存在计算机上的认证数据存储在 %APPDATA%\\Subversion\\auth .此内存路径也用于大多数其他 Subversion 客户端应用程序（例如，TortoiseSVN 和 AnkhSVN）。因此，删除身份验证数据也会影响这些应用程序。 " }, 
{ "title" : "命令：合并更改 ", 
"url" : "_svn_cmd_merge_changes.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：合并更改 ", 
"snippet" : "合并更改 象征： 功能 ：该命令打开 合并 对话。在此对话框中，您可以确定要与项目工作副本合并的修订版本。 称呼 ： 项目 → SVN 菜单 要求 ：该项目链接到SVN。...", 
"body" : "合并更改 象征： 功能 ：该命令打开 合并 对话。在此对话框中，您可以确定要与项目工作副本合并的修订版本。 称呼 ： 项目 → SVN 菜单 要求 ：该项目链接到SVN。 " }, 
{ "title" : "对话框：合并 ", 
"url" : "_svn_cmd_merge_changes.html#UUID-137b0e14-b1e7-77f7-0655-8bf46959e238_id_f08d0d1baa842cc0a864634409a406-id-24c1ef4197f5139fc0a864631d9e83a2", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：合并更改 \/ 对话框：合并 ", 
"snippet" : "合并类型 同步\/重新整合\/对称合并 ：主干（或其他分支）中所有丢失的更改都与此分支同步。 樱桃采摘 ：将特定选择的修订从一个分支集成到另一个分支。这是必要的，例如，如果必须将任何错误捕获移植回旧版本。 合并源 SVN 存储库的 SVN URL 输入栏 头 : HEAD 修订 ： 这 SVN 存储库浏览器 对话框打开以选择 SVN 存储库。 定义开始和结束修订 选择此选项可将相关的修订范围与工作副本合并。 开始修订 定义与工作副本合并的修订范围 头 : HEAD 修订 修订 ：范围的开始和结束修订 日期 ：开始和结束修订的日期 结束修订 定义修订范围 当您想要将单个修订与工作副本合并时，请选择此...", 
"body" : "合并类型 同步\/重新整合\/对称合并 ：主干（或其他分支）中所有丢失的更改都与此分支同步。 樱桃采摘 ：将特定选择的修订从一个分支集成到另一个分支。这是必要的，例如，如果必须将任何错误捕获移植回旧版本。 合并源 SVN 存储库的 SVN URL 输入栏 头 : HEAD 修订 ： 这 SVN 存储库浏览器 对话框打开以选择 SVN 存储库。 定义开始和结束修订 选择此选项可将相关的修订范围与工作副本合并。 开始修订 定义与工作副本合并的修订范围 头 : HEAD 修订 修订 ：范围的开始和结束修订 日期 ：开始和结束修订的日期 结束修订 定义修订范围 当您想要将单个修订与工作副本合并时，请选择此选项。您还可以在 日志 对话。 注意：定义范围时， CODESYS SVN 行为类似于其他图形客户端，例如 Tortoise SVN），而不像命令行客户端。示例：对于一个范围 4–7 ，修订版 4、5、6 和 7 被合并。 有关更多信息，请参阅： 合并一系列修订 试运行（模拟） : 执行命令而不更改工作副本。显示在实际合并期间更改的文件以及发生冲突的范围。 只记录 ：修订被标记为“已合并”，但并未实际执行合并。 忽略祖先 : SVN 仅使用基于路径的差异，而不使用基于历史的差异。 " }, 
{ "title" : "命令：连接到现有项目 ", 
"url" : "_svn_cmd_connect_to_existing_project.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：连接到现有项目 ", 
"snippet" : "连接到现有项目 象征： 功能 ：该命令打开 连接到 SVN 存储库 对话。在对话框中，您定义未版本化项目所连接的 SVN 存储库的 URL 和修订版。 称呼 ： 项目 → SVN 菜单 要求 ：项目与SVN断开连接。 只有对整个项目具有读取权限的用户（请参阅 CODESYS 用户和访问管理）可以将项目导入 SVN 存储库，也可以链接到现有的数据库项目。 该命令仅在项目已经导入 SVN 并通过 断开项目与 SVN 的连接 命令。...", 
"body" : "连接到现有项目 象征： 功能 ：该命令打开 连接到 SVN 存储库 对话。在对话框中，您定义未版本化项目所连接的 SVN 存储库的 URL 和修订版。 称呼 ： 项目 → SVN 菜单 要求 ：项目与SVN断开连接。 只有对整个项目具有读取权限的用户（请参阅 CODESYS 用户和访问管理）可以将项目导入 SVN 存储库，也可以链接到现有的数据库项目。 该命令仅在项目已经导入 SVN 并通过 断开项目与 SVN 的连接 命令。 " }, 
{ "title" : "对话框：连接到 SVN 存储库 ", 
"url" : "_svn_cmd_connect_to_existing_project.html#UUID-a3808236-82bd-ced8-225a-3a13dc1cbaaa_id_d49bb61baaeca6c0a864637eb31096-id-beb979e69807e116c0a864632359a493", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：连接到现有项目 \/ 对话框：连接到 SVN 存储库 ", 
"snippet" : "现有项目的网址 SVN 仓库的 URL 头 ：选择中的修订 选择修订 对话 ：选择 SVN 存储库中的 SVN 存储库浏览器 结帐选项 省略外部 : 外部未检出。 修订 头 : HEAD 修订 修订 : 修订号 日期 : 修订日期 使用 UTC 时间 ： : 以通用时间显示日期...", 
"body" : "现有项目的网址 SVN 仓库的 URL 头 ：选择中的修订 选择修订 对话 ：选择 SVN 存储库中的 SVN 存储库浏览器 结帐选项 省略外部 : 外部未检出。 修订 头 : HEAD 修订 修订 : 修订号 日期 : 修订日期 使用 UTC 时间 ： : 以通用时间显示日期 " }, 
{ "title" : "命令：解决冲突 ", 
"url" : "_svn_cmd_resolve_conflict.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：解决冲突 ", 
"snippet" : "解决冲突 象征： 功能 ：该命令打开 <对象> 对话。在对话框中，将显示冲突并准备解决冲突的功能以合并更改。 称呼 : 对象的上下文菜单 要求 ：对象发生冲突，这是通过使用本地更改更新对象而发生的。...", 
"body" : "解决冲突 象征： 功能 ：该命令打开 <对象> 对话。在对话框中，将显示冲突并准备解决冲突的功能以合并更改。 称呼 : 对象的上下文菜单 要求 ：对象发生冲突，这是通过使用本地更改更新对象而发生的。 " }, 
{ "title" : "对话框：<对象> ", 
"url" : "_svn_cmd_resolve_conflict.html#UUID-b2f4758f-5286-61ad-d68a-90fa78a714ba_id_b5223ac1badc49ac0a864630132f04b-id-ceaa58e3a6fb98edc0a864631e18267a", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：解决冲突 \/ 对话框：<对象> ", 
"snippet" : "比较 左侧显示本地对象，右侧显示来自 SVN 存储库的版本。 使用我的 使用本地更改。 使用你的 使用来自 SVN 存储库的版本更改。 申请 接受您在此对话框中所做的所有更改。对象的状态已更改。 取消 取消您在此对话框中所做的所有更改 但是，对象保持“冲突”状态。...", 
"body" : "比较 左侧显示本地对象，右侧显示来自 SVN 存储库的版本。 使用我的 使用本地更改。 使用你的 使用来自 SVN 存储库的版本更改。 申请 接受您在此对话框中所做的所有更改。对象的状态已更改。 取消 取消您在此对话框中所做的所有更改 但是，对象保持“冲突”状态。 " }, 
{ "title" : "命令：离线工作 ", 
"url" : "_svn_cmd_work_in_offline_mode.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：离线工作 ", 
"snippet" : "在离线模式下工作 功能 ：命令切换到SVN离线模式。在 SVN 离线模式下，隐式锁定和访问 SVN 存储库的所有命令都是不可能的。 称呼 ： 项目 → SVN 菜单 上下文菜单： SVN 要求 ：该项目链接到SVN。 切换回 SVN 在线模式时，会针对服务器检查工作副本上的所有现有锁。如果锁无效，则将其释放。 用例 机器上的用户希望在不断开连接的情况下对项目进行更改。当前没有与服务器的连接。尽管如此，当激活自动锁定时，由于 SVN 离线模式会暂时停用自动锁定，因此可以工作。...", 
"body" : "在离线模式下工作 功能 ：命令切换到SVN离线模式。在 SVN 离线模式下，隐式锁定和访问 SVN 存储库的所有命令都是不可能的。 称呼 ： 项目 → SVN 菜单 上下文菜单： SVN 要求 ：该项目链接到SVN。 切换回 SVN 在线模式时，会针对服务器检查工作副本上的所有现有锁。如果锁无效，则将其释放。 用例 机器上的用户希望在不断开连接的情况下对项目进行更改。当前没有与服务器的连接。尽管如此，当激活自动锁定时，由于 SVN 离线模式会暂时停用自动锁定，因此可以工作。 " }, 
{ "title" : "命令：复制（分支\/标签） ", 
"url" : "_svn_cmd_copy.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：复制（分支\/标签） ", 
"snippet" : "复制（分支\/标签） 象征： 功能 ：该命令打开 SVN 复制分支\/标签 对话。在那里你可以 分支 或者 标签 您的项目的修订。您的项目的特定版本保存在此位置。分支通常用于保存在一个版本中隔离的更改。标签用于标记特定状态，例如发货版本。在内部，它实际上并不是抄袭，而是更多地指的是修订。 称呼 ： 项目 → SVN 菜单 要求 : 项目是版本化的。...", 
"body" : "复制（分支\/标签） 象征： 功能 ：该命令打开 SVN 复制分支\/标签 对话。在那里你可以 分支 或者 标签 您的项目的修订。您的项目的特定版本保存在此位置。分支通常用于保存在一个版本中隔离的更改。标签用于标记特定状态，例如发货版本。在内部，它实际上并不是抄袭，而是更多地指的是修订。 称呼 ： 项目 → SVN 菜单 要求 : 项目是版本化的。 " }, 
{ "title" : "对话框：SVN 复制（分支\/标签） ", 
"url" : "_svn_cmd_copy.html#UUID-98856047-8a12-9904-a38b-fc3902173f41_id_de57571bae7870c0a8646357265cc2-id-964e6a8cf81211e6a4faca3c899d2a6b", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：复制（分支\/标签） \/ 对话框：SVN 复制（分支\/标签） ", 
"snippet" : "SVN 存储库 从 当前项目的SVN路径 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 到 用于复制操作的 SVN 存储库中的目标路径 标签示例： https:\/\/svnserver\/repository\/tags\/V4.4.4.4\/ControlABC.project ： 这 SVN 存储库浏览器 对话框打开以选择目标路径。 日志消息 输入栏 输入评论您的更改的日志消息。 例子： Tag for version 4.4.4.4 created. 最近的消息 打开 最近的消息 用于显示最后日志消息的对话框 您可以单击日志消息...", 
"body" : "SVN 存储库 从 当前项目的SVN路径 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 到 用于复制操作的 SVN 存储库中的目标路径 标签示例： https:\/\/svnserver\/repository\/tags\/V4.4.4.4\/ControlABC.project ： 这 SVN 存储库浏览器 对话框打开以选择目标路径。 日志消息 输入栏 输入评论您的更改的日志消息。 例子： Tag for version 4.4.4.4 created. 最近的消息 打开 最近的消息 用于显示最后日志消息的对话框 您可以单击日志消息以接受它。 从创建副本 工作副本（包括本地更改） 新的分支\/标签是指包括所有本地更改的工作副本。本地更改被提交到 SVN 存储库以执行此操作。 工作副本的基本修订版（<修订号>） 新的分支\/标签是指您的工作副本的基本版本，其版本号显示在括号中。如果工作副本已经包含本地更改，则这些更改不会提交到 SVN 存储库。 存储库的 HEAD 修订 新的分支\/标签是指项目的 HEAD 版本。 SVN 存储库中的特定修订 新的分支\/标签是指显示在相邻按钮上的修订。 单击按钮更改修订。这 选择修订 对话框打开。 切换到新位置 ：确认对话框后，工作副本切换到新的分支\/标签。 行 创建目标路径（作为新标签 ..\/repository\/tags\/V4.4.4.4 或作为新分支 ..\/repository\/branches\/new_feature ）。然后在中指定的修订 从创建副本 在那里复制。 " }, 
{ "title" : "命令：待更改 ", 
"url" : "_svn_cmd_pending_changes.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：待更改 ", 
"snippet" : "待更改 象征： 功能 ：该命令打开 待更改 看法。此处列出了从基本修订版更改或已锁定的所有对象。 称呼 ： 查看 → 待更改...", 
"body" : "待更改 象征： 功能 ：该命令打开 待更改 看法。此处列出了从基本修订版更改或已锁定的所有对象。 称呼 ： 查看 → 待更改 " }, 
{ "title" : "查看：待更改 ", 
"url" : "_svn_cmd_pending_changes.html#UUID-aac5868b-0a96-d778-20b5-9bb044e6a575_id_a1ccb2aa34017cac0a8646315d3e199-id-4d4b86cd88a50ce9c0a8646306c8b9b8", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ 命令：待更改 \/ 查看：待更改 ", 
"snippet" : "修改或锁定的对象显示在视图的下半部分。您可以使用 犯罪 , 恢复 ， 和 更新 对单个或多个对象的命令。您将在选定对象的上下文菜单中找到用于比较和显示版本历史记录的命令。 CODESYS SVN 首先检查工作副本的存储格式是否与SVN存储库中项目的存储格式匹配。如果存储格式不同，则不得在对象级别执行还原以防止不一致。在这种情况下，您可以先删除整个项目（工作副本） 另存为 命令作为适当的存储格式，但这会导致较小的数据丢失。选择其中一个还原选项后，您将被相应的对话框提示引导。 双击对象打开项目比较。 选择 选择或清除所有对象 犯罪 将本地更改提交到 SVN 存储库 重启 将本地更改恢复到工作副本的...", 
"body" : "修改或锁定的对象显示在视图的下半部分。您可以使用 犯罪 , 恢复 ， 和 更新 对单个或多个对象的命令。您将在选定对象的上下文菜单中找到用于比较和显示版本历史记录的命令。 CODESYS SVN 首先检查工作副本的存储格式是否与SVN存储库中项目的存储格式匹配。如果存储格式不同，则不得在对象级别执行还原以防止不一致。在这种情况下，您可以先删除整个项目（工作副本） 另存为 命令作为适当的存储格式，但这会导致较小的数据丢失。选择其中一个还原选项后，您将被相应的对话框提示引导。 双击对象打开项目比较。 选择 选择或清除所有对象 犯罪 将本地更改提交到 SVN 存储库 重启 将本地更改恢复到工作副本的基本修订状态 更新 该命令将 SVN 存储库中的更改提交到项目。使用 HEAD 修订执行更新。 保留锁 : 锁在提交后不会自动释放。 存储配置文件更新 请注意，工作副本中存储库的存储配置文件（存储版本）与 SVN 存储库中的不同。在这种情况下，提交将更改存储库中的存储配置文件。 对于需要在工作副本和存储库之间进行交换的操作，您将被相应的消息引导以匹配存储配置文件。有关这方面的更多信息，另请参阅： 检查版本配置文件的一致性最近的消息 显示最后使用的日志消息 您可以单击日志消息以接受它。 留言 输入评论您的更改的日志消息。 例子： Bug fix error 123 " }, 
{ "title" : "Test Manager ", 
"url" : "_svn_f_commands_tm.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager ", 
"snippet" : "这 CODESYS SVN 附加组件提供基本的 SVN 命令 CODESYS Test Manager . 这 CODESYS Test Manager 必须在您的开发系统上安装附加组件才能使用这些命令。 有关详细信息，请参阅 CODESYS Test Manager 添加在。...", 
"body" : "这 CODESYS SVN 附加组件提供基本的 SVN 命令 CODESYS Test Manager . 这 CODESYS Test Manager 必须在您的开发系统上安装附加组件才能使用这些命令。 有关详细信息，请参阅 CODESYS Test Manager 添加在。 " }, 
{ "title" : "命令：CheckForLocalChanges ", 
"url" : "_svn_cmd_tm_svn_checkforlocalchanges.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：CheckForLocalChanges ", 
"snippet" : "CheckForLocalChanges 功能 ：该命令检查是否对项目进行了本地更改。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "CheckForLocalChanges 功能 ：该命令检查是否对项目进行了本地更改。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "配置 ", 
"url" : "_svn_cmd_tm_svn_checkforlocalchanges.html#UUID-cefc29b7-329d-ae6c-3878-8802f0c4232e_id_f8bc1bb082cfc0a864637b1ce38e-id-b7d5ab2be21611e6bfdaf97325861fd8", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：CheckForLocalChanges \/ 配置 ", 
"snippet" : "如果...报告测试失败 该项目有本地修改 ：当相应情况发生时，脚本会返回错误。 该项目有多个修订 否则项目不干净（切换，不完整......） 报告测试报告 修改对象数 ：修改对象的数量或列表包含在测试报告中。 所有修改对象的列表...", 
"body" : "如果...报告测试失败 该项目有本地修改 ：当相应情况发生时，脚本会返回错误。 该项目有多个修订 否则项目不干净（切换，不完整......） 报告测试报告 修改对象数 ：修改对象的数量或列表包含在测试报告中。 所有修改对象的列表 " }, 
{ "title" : "命令：CheckForUpdates ", 
"url" : "_svn_cmd_tm_svn_checkforupdates.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：CheckForUpdates ", 
"snippet" : "CheckForUpdates 功能 ：该命令检查服务器上是否有新版本的项目可用。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "CheckForUpdates 功能 ：该命令检查服务器上是否有新版本的项目可用。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "配置 ", 
"url" : "_svn_cmd_tm_svn_checkforupdates.html#UUID-583745e4-6737-b29e-d50f-207987dc1086_id_ff9602ac1bb0c0d5c0a86463071d6144-id-98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：CheckForUpdates \/ 配置 ", 
"snippet" : "检查当前项目的服务器，然后... 要求有可用的更新 ：当条件不满足时，这些检查会导致测试操作失败。 要求项目是最新的 在此变量中返回一个布尔值 ：如果服务器上有可用的更新，则返回指定的变量 TRUE ;如果不是，则返回 FALSE .这个变量可以在 Choose 语句或其他测试操作中（例如，在脚本中）。 例子： bWorkingCopyNotUpToDate...", 
"body" : "检查当前项目的服务器，然后... 要求有可用的更新 ：当条件不满足时，这些检查会导致测试操作失败。 要求项目是最新的 在此变量中返回一个布尔值 ：如果服务器上有可用的更新，则返回指定的变量 TRUE ;如果不是，则返回 FALSE .这个变量可以在 Choose 语句或其他测试操作中（例如，在脚本中）。 例子： bWorkingCopyNotUpToDate " }, 
{ "title" : "命令: Checkout ", 
"url" : "_svn_cmd_tm_svn_checkout.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令: Checkout ", 
"snippet" : "Checkout 功能 : 该命令检出一个 CODESYS 来自 SVN 存储库的项目。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "Checkout 功能 : 该命令检出一个 CODESYS 来自 SVN 存储库的项目。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "配置 ", 
"url" : "_svn_cmd_tm_svn_checkout.html#UUID-72c95ef3-0278-baac-dafe-6cfb2a606561_id_e0041bb1097dc0a8646306d2da40-id-09770c81e21b11e68250f4b154596578", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令: Checkout \/ 配置 ", 
"snippet" : "SVN 仓库的 URL SVN 仓库中项目的 URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：一旦指定了有效的 SVN 存储库，您可以单击相邻的按钮或 修订 浏览并选择特定项目。 该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 打开 选择存档类别 对话 您可以在此处选择修订。 注意：该对话框提供的选项与 修订 团体。 打开对话框 SVN 存储库浏览器 在那里您可以浏览 S...", 
"body" : "SVN 仓库的 URL SVN 仓库中项目的 URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 提示：一旦指定了有效的 SVN 存储库，您可以单击相邻的按钮或 修订 浏览并选择特定项目。 该按钮标有当前选定的修订： 头 : 最新版本（最高版本） 默认 15 : 所选修订的修订号 2016 年 12 月 23 日 11:59:59 (UTC) : 所选修订的更改日期 (UTC) 打开 选择存档类别 对话 您可以在此处选择修订。 注意：该对话框提供的选项与 修订 团体。 打开对话框 SVN 存储库浏览器 在那里您可以浏览 SVN 存储库。 结帐至 名称 工作副本的名称 例子： ControlABC.project 地点 工作副本的位置 例子： \/D:\/svn\/repository\/trunk\/ControlABC.project 结帐为 项目 项目保存为 CODESYS 项目 ” <project name>.project ”。 图书馆 项目保存为 CODESYS 库文件“ <project name>.library ”。 自动侦测 CODESYS 尝试通过扩展识别项目类型。当前实现检查项目的 URL 是否以“ _library “ 或者 ” .library \"。在这种情况下，项目被识别为库或项目。 结帐选项 省略外部 ：外部文件不会复制到工作目录。 修订 有关说明，请参阅章节 选择修订. " }, 
{ "title" : "命令：CommitAllChanges ", 
"url" : "_svn_cmd_tm_svn_commitallchanges.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：CommitAllChanges ", 
"snippet" : "CommitAllChanges 功能 ：该命令提交所有更改 CODESYS 项目到 SVN 存储库。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "CommitAllChanges 功能 ：该命令提交所有更改 CODESYS 项目到 SVN 存储库。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "配置 ", 
"url" : "_svn_cmd_tm_svn_commitallchanges.html#UUID-3a420290-9faa-ccc9-0ef3-ab67cf8242c9_id_c9ad52881bb15abac0a8646374dff6b5-id-98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：CommitAllChanges \/ 配置 ", 
"snippet" : "提交消息 提交的日志消息 提交选项 保留锁 : 提交后锁不会被移除。 保留更改列表 ：提交后不会删除更改列表。 提交后更新（推荐） ：项目在提交后更新，并防止工作副本中的混合修订。 （有关详细信息，请参阅 svnbook 主页。）...", 
"body" : "提交消息 提交的日志消息 提交选项 保留锁 : 提交后锁不会被移除。 保留更改列表 ：提交后不会删除更改列表。 提交后更新（推荐） ：项目在提交后更新，并防止工作副本中的混合修订。 （有关详细信息，请参阅 svnbook 主页。） " }, 
{ "title" : "命令 ：Disconnect ", 
"url" : "_svn_cmd_tm_svn_disconnect.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令 ：Disconnect ", 
"snippet" : "Disconnect 功能 ：该命令删除当前项目与 Subversion 的所有连接。为此，将项目切换到非版本化项目。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "Disconnect 功能 ：该命令删除当前项目与 Subversion 的所有连接。为此，将项目切换到非版本化项目。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "命令：报告修订信息 ", 
"url" : "_svn_cmd_tm_svn_reportrevisioninformation.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：报告修订信息 ", 
"snippet" : "报告修订信息 功能 ：该命令读取修订信息并提供测试报告。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "报告修订信息 功能 ：该命令读取修订信息并提供测试报告。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "配置 ", 
"url" : "_svn_cmd_tm_svn_reportrevisioninformation.html#UUID-cccdbb8e-32df-f90d-b03e-12a17936fae8_id_b7882a6b1bb1d1b5c0a8646356487d2d-id-98733dd8635a8e3dc0a8640e011b6259", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：报告修订信息 \/ 配置 ", 
"snippet" : "输出到测试报告 包含在“版本信息”标题中 ：版本信息包含在测试报告表头中的上表中；否则它会出现在下面。 报告中的标题 标题表中此信息的标题 如果您不指定标题，则默认标题源自项目名称。 例子： Test report Project1 输出到测试脚本变量 项目网址 ：项目的URL在指定的测试脚本变量（输出变量）中输出。 修订摘要 ：输出修订摘要的标签 SVN_VERSION_INFO.VERSION 或者 svnversion.exe 示例：“12:34M”：混合修订版工作副本，最小修订版 12、最大修订版 34 和本地修改...", 
"body" : "输出到测试报告 包含在“版本信息”标题中 ：版本信息包含在测试报告表头中的上表中；否则它会出现在下面。 报告中的标题 标题表中此信息的标题 如果您不指定标题，则默认标题源自项目名称。 例子： Test report Project1 输出到测试脚本变量 项目网址 ：项目的URL在指定的测试脚本变量（输出变量）中输出。 修订摘要 ：输出修订摘要的标签 SVN_VERSION_INFO.VERSION 或者 svnversion.exe 示例：“12:34M”：混合修订版工作副本，最小修订版 12、最大修订版 34 和本地修改 " }, 
{ "title" : "命令 ：Switch ", 
"url" : "_svn_cmd_tm_svn_switch.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令 ：Switch ", 
"snippet" : "Switch 功能 ：该命令将项目的工作副本更新到另一个 SVN 存储库 URL。因此，您可以使用此命令将项目从一个分支或标签切换到另一个。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "Switch 功能 ：该命令将项目的工作副本更新到另一个 SVN 存储库 URL。因此，您可以使用此命令将项目从一个分支或标签切换到另一个。 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "配置 ", 
"url" : "_svn_cmd_tm_svn_switch.html#UUID-557a7f06-6bf8-91da-b566-6cb95c786bf9_id_cd301bb2161fc0a8646310093ed7-id-98b4bfb19776f63cc0a86463264b07a7", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令 ：Switch \/ 配置 ", 
"snippet" : "切换到 SVN中目标URL的输入字段 头 ： 这 选择修订 对话框打开。 ： 对话 SVN 存储库浏览器 打开。您可以在 SVN 存储库中选择目标 URL。...", 
"body" : "切换到 SVN中目标URL的输入字段 头 ： 这 选择修订 对话框打开。 ： 对话 SVN 存储库浏览器 打开。您可以在 SVN 存储库中选择目标 URL。 " }, 
{ "title" : "命令：UpdateToHeadRevision ", 
"url" : "_svn_cmd_tm_svn_updatetoheadrevision.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 命令 \/ Test Manager \/ 命令：UpdateToHeadRevision ", 
"snippet" : "UpdateToHeadRevision 功能 ：更新 CODESYS 包含来自 SVN 存储库的更改的项目 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。...", 
"body" : "UpdateToHeadRevision 功能 ：更新 CODESYS 包含来自 SVN 存储库的更改的项目 称呼 : 测试管理器中的操作 测试管理器.SVN 要求 ： 这 CODESYS Test Manager 附加组件已安装。 " }, 
{ "title" : "对话框 ", 
"url" : "_svn_struct_reference_dialogs.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对话框：选项 - SVN 设置 ", 
"url" : "_svn_dlg_options.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：选项 - SVN 设置 ", 
"snippet" : "选项 - SVN 设置...", 
"body" : "选项 - SVN 设置 " }, 
{ "title" : "标签：常规 ", 
"url" : "_svn_dlg_options.html#UUID-ba592961-77f4-b2df-ace0-8d5ad01d802a_id_e2a663b177fe2d6c0a8646328e0e623-id-459fe34ad49c957ec0a864630b8968db", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：选项 - SVN 设置 \/ 标签：常规 ", 
"snippet" : "象征： 功能 ：该选项卡包括基本设置 CODESYS SVN . 称呼 ： 工具 → 选项 菜单 自动锁定和合并 合并 命令的行为 更新 , 合并 ， 或者 转变 , 当双方（工作副本和 SVN 存储库）都从基本版本更改时 将所有冲突的更改标记为冲突 ：对象不会自动合并。所有有冲突的更改都被标记为“冲突”，即使其中一些可以自动合并。 合并可合并的更改，将其他更改标记为冲突 ：可以合并的更改会自动合并。所有其他都标记为“冲突”。 合并可合并的更改，向用户询问其他更改 ：可以合并的更改会自动合并。提示用户输入所有其他内容。 始终询问用户，即使是可合并的更改 ：对于所有更改的对象，都会提示用户，即使...", 
"body" : "象征： 功能 ：该选项卡包括基本设置 CODESYS SVN . 称呼 ： 工具 → 选项 菜单 自动锁定和合并 合并 命令的行为 更新 , 合并 ， 或者 转变 , 当双方（工作副本和 SVN 存储库）都从基本版本更改时 将所有冲突的更改标记为冲突 ：对象不会自动合并。所有有冲突的更改都被标记为“冲突”，即使其中一些可以自动合并。 合并可合并的更改，将其他更改标记为冲突 ：可以合并的更改会自动合并。所有其他都标记为“冲突”。 合并可合并的更改，向用户询问其他更改 ：可以合并的更改会自动合并。提示用户输入所有其他内容。 始终询问用户，即使是可合并的更改 ：对于所有更改的对象，都会提示用户，即使其中一些可以自动合并。 锁具 行为方式 CODESYS SVN 在本地更改对象时锁定对象 修改前总是尝试锁定 ：所有对象在更改之前都被锁定，即使它们可以合并。 只锁定不支持合并的对象 : 只有那些不能自动合并的对象才会被锁定。 永远不要自动获取锁 ：没有对象被锁定，即使它们可以自动合并。 标记 合并对象时使用冲突标记 ：如果存在无法合并的冲突对象，则这些冲突在源代码中使用冲突标记进行标记。此外，对象本身被标记为合并成功（无冲突）。 将不可合并的对象保留为“冲突” : 没有设置冲突标记。无法合并的对象仍处于“冲突”状态。 自动锁定失败时提示用户。 ：如果无法锁定对象，则 自动锁定失败 对话框打开（参见对话框描述）。 冲突标记示例 Foo();\n>>>>>>>>>>>>>>>\nI := I + 1;\n===============\nI := I + 2;\n<<<<<<<<<<<<<<< 检查服务器 检查服务器的更新和锁定 ： CODESYS SVN 在指定的时间间隔内检查服务器上的对象是否已更新。此外，它还会检查对象是否被锁定或锁是否被盗。 检查间隔（分钟） 示例：10 忽略比较 忽略空格 ：忽略当前项目和参考项目之间的空白差异。 忽略评论 : 编程代码中的注释被排除在比较之外。 忽略属性 ：从比较中排除对象属性。 某些 SVN 选项可以被项目特定的设置覆盖。 项目特定的设置定义在 项目设置——SVN设置对话。 " }, 
{ "title" : "标签：SSH ", 
"url" : "_svn_dlg_options.html#UUID-ba592961-77f4-b2df-ace0-8d5ad01d802a_id_e2a663b177fe2d6c0a8646328e0e623-id-4633df1dd1bc11e6ba31bbd40a9de94e", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：选项 - SVN 设置 \/ 标签：SSH ", 
"snippet" : "象征： 功能 ：该选项卡包含 SSH 协议的设置。 称呼 ： 工具 → 选项 菜单 SSH客户端实现 libssh2（推荐） CODESYS SVN 使用 Libssh2 通过 SSH 协议建立连接。这是推荐的设置。 SharpPlink（向后兼容） CODESYS SVN 使用 plink.exe 建立与 SSH 服务器的连接。只有与支持已弃用的 SSH-1 协议的过时服务器进行通信时才需要此选项。 SSH配置可以通过环境变量覆盖 SVN_SSH ，或通过 SVN 配置文件特定于服务器。...", 
"body" : "象征： 功能 ：该选项卡包含 SSH 协议的设置。 称呼 ： 工具 → 选项 菜单 SSH客户端实现 libssh2（推荐） CODESYS SVN 使用 Libssh2 通过 SSH 协议建立连接。这是推荐的设置。 SharpPlink（向后兼容） CODESYS SVN 使用 plink.exe 建立与 SSH 服务器的连接。只有与支持已弃用的 SSH-1 协议的过时服务器进行通信时才需要此选项。 SSH配置可以通过环境变量覆盖 SVN_SSH ，或通过 SVN 配置文件特定于服务器。 " }, 
{ "title" : "对话框：项目设置 - SVN 设置 ", 
"url" : "_svn_dlg_project_settings.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：项目设置 - SVN 设置 ", 
"snippet" : "项目设置——SVN设置 象征： 功能 ：在此对话框中配置集成 SVN 版本控制系统的行为。 称呼 ： 项目 → 项目设置 菜单，类别 SVN 设置 要求 : 项目已打开。 自动锁定和合并 使用这些设置，您可以覆盖在 选项 - SVN 设置 对话。 合并 命令的行为 更新 , 合并 ， 或者 转变 , 当双方（工作副本和 SVN 存储库）都从基本版本更改时 锁具 行为方式 CODESYS SVN 在本地更改对象时锁定对象 标记 冲突行为 SVN 版本信息设置 为 IEC 访问创建 SVN_VERSION_INFO 常量 ： 物体 SVN_VERSION_INFO 被创建并包括项目元数据的全局常量...", 
"body" : "项目设置——SVN设置 象征： 功能 ：在此对话框中配置集成 SVN 版本控制系统的行为。 称呼 ： 项目 → 项目设置 菜单，类别 SVN 设置 要求 : 项目已打开。 自动锁定和合并 使用这些设置，您可以覆盖在 选项 - SVN 设置 对话。 合并 命令的行为 更新 , 合并 ， 或者 转变 , 当双方（工作副本和 SVN 存储库）都从基本版本更改时 锁具 行为方式 CODESYS SVN 在本地更改对象时锁定对象 标记 冲突行为 SVN 版本信息设置 为 IEC 访问创建 SVN_VERSION_INFO 常量 ： 物体 SVN_VERSION_INFO 被创建并包括项目元数据的全局常量或变量。 ： 物体 SVN_VERSION_INFO 不可用。 当您选择该选项时，将自动创建对象。当您取消选择该选项时，该对象会自动从项目中移除。 断开项目与 SVN 的连接后保留 SVN_VERSION_INFO 对象 ： 这 SVN_VERSION_INFO 项目断开后对象成为持久对象。用例：在编译的库中提供 SVN 信息。 " }, 
{ "title" : "对话框：选择修订 ", 
"url" : "_svn_dlg_select_revision.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：选择修订 ", 
"snippet" : "选择修订 功能 ：对话框显示当前选择的版本。在那里您可以编辑选择。 修订 头 : 显示分支内的最新版本（最高版本）。 修订 : 特定版本由版本号显示。 例子： 3 提示：点击 显示修订。然后 日志 对话框打开以显示修订和相关操作。您在此处选择的修订将被应用。 日期 : 一个特定的版本在修改日期之前被签出。这是给定时间的最高版本（该时间之前的最后一个版本）。 例子： 12\/23\/2016 11:59:59 提示：请参阅“使用 Subversion 进行版本控制”中的“修订标识符”一章 使用 UTC 时间 : 使用世界时的修改日期。 递归重置 ：所选对象下方的所有对象也将被重置。 动作失败，如果 ...", 
"body" : "选择修订 功能 ：对话框显示当前选择的版本。在那里您可以编辑选择。 修订 头 : 显示分支内的最新版本（最高版本）。 修订 : 特定版本由版本号显示。 例子： 3 提示：点击 显示修订。然后 日志 对话框打开以显示修订和相关操作。您在此处选择的修订将被应用。 日期 : 一个特定的版本在修改日期之前被签出。这是给定时间的最高版本（该时间之前的最后一个版本）。 例子： 12\/23\/2016 11:59:59 提示：请参阅“使用 Subversion 进行版本控制”中的“修订标识符”一章 使用 UTC 时间 : 使用世界时的修改日期。 递归重置 ：所选对象下方的所有对象也将被重置。 动作失败，如果 对象已移入或移出下面的层次结构 层次结构之外的对象会被隐式依赖改变 " }, 
{ "title" : "对话框：颠覆身份验证 ", 
"url" : "_svn_dlg_ssl_authentication.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：颠覆身份验证 ", 
"snippet" : "颠覆认证 这些对话框用于验证服务器\/客户端连接。根据初始情况和协议执行服务器或客户端身份验证。 可能的协议和对话框概述 svn:\/\/ : 原生 SVN 协议，未加密或 SSL\/TLS 加密 可以提示输入用户名和密码（即使是未加密的连接） 如果证书未知、有缺陷或无效（用于 TLS\/SSL 加密），可以从对话框中提示输入服务器证书以进行身份验证以确认服务器 作为替代或除了用户名和密码提示之外，还可以使用“客户端证书”（用于 TLS\/SSL 加密）对客户端进行身份验证。 （用于 TLS\/SSL 加密） 身份验证对话框使用客户端证书打开。 http:\/\/ : 通过 http 的 SVN，未加密 可以提...", 
"body" : "颠覆认证 这些对话框用于验证服务器\/客户端连接。根据初始情况和协议执行服务器或客户端身份验证。 可能的协议和对话框概述 svn:\/\/ : 原生 SVN 协议，未加密或 SSL\/TLS 加密 可以提示输入用户名和密码（即使是未加密的连接） 如果证书未知、有缺陷或无效（用于 TLS\/SSL 加密），可以从对话框中提示输入服务器证书以进行身份验证以确认服务器 作为替代或除了用户名和密码提示之外，还可以使用“客户端证书”（用于 TLS\/SSL 加密）对客户端进行身份验证。 （用于 TLS\/SSL 加密） 身份验证对话框使用客户端证书打开。 http:\/\/ : 通过 http 的 SVN，未加密 可以提示输入用户名和密码 https:\/\/ : SVN 通过 http，SSL\/TLS 加密 可以提示输入用户名和密码 如果证书未知、有缺陷或无效，可以从对话框中提示输入服务器证书以进行身份验证以确认服务器 可替代地或除了用户名和密码之外，还可以使用“客户端证书”对客户端进行身份验证。 身份验证对话框使用客户端证书打开。 svn+ssh:\/\/ : 原生 SVN 协议，通过 SSH 隧道加密 SSH（安全外壳）是 Linux\/Unix 中用于访问其他计算机的常用网络工具。 可以提示输入用户名和密码 在验证对话框中提示输入服务器证书，如果服务器仍然未知，以确保它是正确的服务器 " }, 
{ "title" : "使用服务器证书进行身份验证的对话框 ", 
"url" : "_svn_dlg_ssl_authentication.html#UUID-d9c46dca-175b-acdb-e893-8d39938f315d_id_e39630fcb23a4bcc0a8646368d1ad28-id-f5d210c2d5db69f3c0a8640e00f98114", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：颠覆身份验证 \/ 使用服务器证书进行身份验证的对话框 ", 
"snippet" : "初始情况： CODESYS （作为客户端）收到未知或有缺陷的服务器证书。 此对话框显示有关证书的信息。在那里您可以确认服务器的身份。 认证区 安全的连接 例子： https:\/\/svn repository:443 证书信息（用于 SSL\/TLS 连接） 主机名 例子： svn repository 指纹 有效期自 有效 发行人 例子： CODESYS GmbH 证书 SSH 服务器密钥信息（用于 SSH 连接） 钥匙类型 密钥大小（位） 密钥指纹 将信息保存到 RAM ：证书保存到工作内存中。然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接...", 
"body" : "初始情况： CODESYS （作为客户端）收到未知或有缺陷的服务器证书。 此对话框显示有关证书的信息。在那里您可以确认服务器的身份。 认证区 安全的连接 例子： https:\/\/svn repository:443 证书信息（用于 SSL\/TLS 连接） 主机名 例子： svn repository 指纹 有效期自 有效 发行人 例子： CODESYS GmbH 证书 SSH 服务器密钥信息（用于 SSH 连接） 钥匙类型 密钥大小（位） 密钥指纹 将信息保存到 RAM ：证书保存到工作内存中。然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：证书保存在计算机上，可供将来连接。 当你重新启动 CODESYS ，使用保存的证书。 行 验证并建立连接 证书存储以加密方式保护并与其他 SVN 客户端一起分发。 " }, 
{ "title" : "使用客户端证书进行身份验证的对话框 ", 
"url" : "_svn_dlg_ssl_authentication.html#UUID-d9c46dca-175b-acdb-e893-8d39938f315d_id_e39630fcb23a4bcc0a8646368d1ad28-id-45bbc9a8d5db69f3c0a8640e0092ede9", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：颠覆身份验证 \/ 使用客户端证书进行身份验证的对话框 ", 
"snippet" : "初始情况：SVN服务器需要客户端证书进行认证。 在此对话框中，您选择客户端证书以确认身份。 认证区 安全的连接 例子： https:\/\/svn repository:443 SSL 服务器需要客户端证书文件。 文件 客户证书文件 将信息保存到 RAM ：证书保存到工作内存中。然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：证书保存在计算机上，可供将来连接。 当你重新启动 CODESYS ，使用保存的证书。 行 验证并建立连接...", 
"body" : "初始情况：SVN服务器需要客户端证书进行认证。 在此对话框中，您选择客户端证书以确认身份。 认证区 安全的连接 例子： https:\/\/svn repository:443 SSL 服务器需要客户端证书文件。 文件 客户证书文件 将信息保存到 RAM ：证书保存到工作内存中。然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：证书保存在计算机上，可供将来连接。 当你重新启动 CODESYS ，使用保存的证书。 行 验证并建立连接 " }, 
{ "title" : "使用密码进行身份验证的对话框 ", 
"url" : "_svn_dlg_ssl_authentication.html#UUID-d9c46dca-175b-acdb-e893-8d39938f315d_id_e39630fcb23a4bcc0a8646368d1ad28-id-15eecdcdd5db69f4c0a8640e006e9550", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：颠覆身份验证 \/ 使用密码进行身份验证的对话框 ", 
"snippet" : "初始情况：SVN 服务器配置为需要客户端证书进行身份验证。应用的证书受密码保护。 认证区 安全的连接 例子： https:\/\/svn repository:443 解锁证书需要密码。 密码 例子： *** 将信息保存到 RAM ：密码被保存到工作记忆中。然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：密码保存在计算机上，可供将来连接。 当你重新启动 CODESYS ，使用保存的证书。 行 通过密码短语使用客户端证书进行身份验证并建立连接...", 
"body" : "初始情况：SVN 服务器配置为需要客户端证书进行身份验证。应用的证书受密码保护。 认证区 安全的连接 例子： https:\/\/svn repository:443 解锁证书需要密码。 密码 例子： *** 将信息保存到 RAM ：密码被保存到工作记忆中。然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：密码保存在计算机上，可供将来连接。 当你重新启动 CODESYS ，使用保存的证书。 行 通过密码短语使用客户端证书进行身份验证并建立连接 " }, 
{ "title" : "使用用户名和密码进行身份验证的对话框 ", 
"url" : "_svn_dlg_ssl_authentication.html#UUID-d9c46dca-175b-acdb-e893-8d39938f315d_id_e39630fcb23a4bcc0a8646368d1ad28-id-65bee11ee16a11e68f2abb81d44bf896", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：颠覆身份验证 \/ 使用用户名和密码进行身份验证的对话框 ", 
"snippet" : "初始情况：SVN服务器配置为要求用户名和密码进行认证。 认证区 安全的连接 例子： https:\/\/svn repository:443 用户名 例子： a.mayr 密码 例子： *** 将信息保存到 RAM ：保存到工作内存 然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：保存在计算机上，可用于将来的连接 当你重新启动 CODESYS ，使用保存的证书。 行 建立连接并对其进行身份验证...", 
"body" : "初始情况：SVN服务器配置为要求用户名和密码进行认证。 认证区 安全的连接 例子： https:\/\/svn repository:443 用户名 例子： a.mayr 密码 例子： *** 将信息保存到 RAM ：保存到工作内存 然后客户端在当前识别 CODESYS 未来连接的会话。 当你重新启动 CODESYS ，您必须再次接受证书。 保存到磁盘 ：保存在计算机上，可用于将来的连接 当你重新启动 CODESYS ，使用保存的证书。 行 建立连接并对其进行身份验证 " }, 
{ "title" : "对话框：自动锁定失败 ", 
"url" : "_svn_dlg_automatic_locking_failed.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对话框 \/ 对话框：自动锁定失败 ", 
"snippet" : "自动锁定失败 该对话框显示无法自动锁定的所有对象的列表。在选项中，您定义如何 CODESYS SVN 应该解决冲突。 自动锁定和合并 尝试窃取受影响对象的锁 激活“离线模式”以暂时抑制锁定 当其他用户锁定对象时，将显示这些选项。 将受影响的对象更新到最新版本 将整个项目更新到最新版本 激活“离线模式”以暂时抑制锁定 当服务器上有更新的对象版本时，将显示这些选项。 激活“离线模式”以暂时抑制锁定 当无法建立与服务器的连接时会显示这些选项。 SVN 项目设置 打开对话框 选项 - SVN 设置您可以在此处更改自动锁定的设置。 SVN 设置 打开常规对话框 SVN 设置...", 
"body" : "自动锁定失败 该对话框显示无法自动锁定的所有对象的列表。在选项中，您定义如何 CODESYS SVN 应该解决冲突。 自动锁定和合并 尝试窃取受影响对象的锁 激活“离线模式”以暂时抑制锁定 当其他用户锁定对象时，将显示这些选项。 将受影响的对象更新到最新版本 将整个项目更新到最新版本 激活“离线模式”以暂时抑制锁定 当服务器上有更新的对象版本时，将显示这些选项。 激活“离线模式”以暂时抑制锁定 当无法建立与服务器的连接时会显示这些选项。 SVN 项目设置 打开对话框 选项 - SVN 设置您可以在此处更改自动锁定的设置。 SVN 设置 打开常规对话框 SVN 设置 " }, 
{ "title" : "对象 ", 
"url" : "_svn_struct_reference_objects.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对象 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对象：SVN_VERSION_INFO ", 
"url" : "_svn_obj_version_info.html", 
"breadcrumbs" : "CODESYS SVN \/ 参考，用户界面 \/ 对象 \/ 对象：SVN_VERSION_INFO ", 
"snippet" : "SVN_VERSION_INFO 象征： 该对象包含项目的 SVN 元数据作为变量列表中的全局常量或变量。它位于 POU 看法。您可以从全局常量或变量中调用应用程序中的特定数据。通过调用特定的数据，还可以减少控制器上的内存使用。 为此目的提供了 SVN 元数据，细分为多个全局变量列表 (GVL)： SVN_VERSION_INFO SVN_Info_Summary SVN_Info_SummaryW SVN_Info_URI SVN_Info_Revisions SVN_Info_Flags SVN_info_LastChange SVN_VERSION_INFO 对象是在通过将项目导入 SV...", 
"body" : "SVN_VERSION_INFO 象征： 该对象包含项目的 SVN 元数据作为变量列表中的全局常量或变量。它位于 POU 看法。您可以从全局常量或变量中调用应用程序中的特定数据。通过调用特定的数据，还可以减少控制器上的内存使用。 为此目的提供了 SVN 元数据，细分为多个全局变量列表 (GVL)： SVN_VERSION_INFO SVN_Info_Summary SVN_Info_SummaryW SVN_Info_URI SVN_Info_Revisions SVN_Info_Flags SVN_info_LastChange SVN_VERSION_INFO 对象是在通过将项目导入 SVN 存储库进行版本控制时自动创建的。为此， 创建 SVN_VERSION_INFO 选项必须在 将项目导入SVN 对话。 此外，在  项目设置——SVN设置 对话框，您可以使用  为 IEC Access 生成 SVN_VERSION_INFO 常量  用于创建对象或将其从项目中删除的选项。 全局常量 名称 数据类型 描述 MINREVISION LINT 工作副本的最低修订号 MAXREVISION LINT 工作副本的最高修订号 PARTIAL BOOL TRUE : 工作副本不完整。 示例：由于网络错误或在上次更新期间取消 查看 ) MODIFIED BOOL TRUE : 进行了局部更改。 SWITCHED BOOL TRUE ：项目的部分分支（与 转变 命令）。 VERSION STRING 版本标识，类似于 Apache™ Subversion® ( subversion.exe ) 例子： 12:34M , 表示 MINREVISION = 12, MAXREVISION = 34, MODIFIED = TRUE 有关更多信息，请参阅 Apache™ Subversion® 的文档。 CLEAN BOOL TRUE : 版本很干净。 当 MINREVISION 等于 MAXREVISION 时就是这种情况，工作副本是完整的、非版本控制的，并且没有切换。 URL WSTRING 项目的SVN-URL 例子： https:\/\/svnserver\/repository\/trunk\/ControlABC.project 如果控制器不支持数据类型 WSTRING ，则在访问对象时会发出编译器错误 SVN_VERSION_INFO . " }
]
$(document).trigger('search.ready');
});