$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS Store ", 
"url" : "_sto_start_page.html", 
"breadcrumbs" : "CODESYS Store \/ CODESYS Store ", 
"snippet" : "CODESYS Store International 是一个可以下载的在线平台 CODESYS 支持许可、安装和评级的扩展（购买或免费）。扩展包括两者 CODESYS 产品以及与第三方供应商合作的产品 CODESYS GmbH .对第三方产品的支持由第三方供应商提供。 您可以在网络浏览器中打开商店 ( https:\/\/store.codesys.com 或者 https:\/\/us.store.codesys.com\/ ) 或者在开发系统中点击 查看→ 店铺 .后一种选择的优点是您可以使用包管理器将产品直接从商店安装到您的计算机。...", 
"body" : "CODESYS Store International 是一个可以下载的在线平台 CODESYS 支持许可、安装和评级的扩展（购买或免费）。扩展包括两者 CODESYS 产品以及与第三方供应商合作的产品 CODESYS GmbH .对第三方产品的支持由第三方供应商提供。 您可以在网络浏览器中打开商店 ( https:\/\/store.codesys.com 或者 https:\/\/us.store.codesys.com\/ ) 或者在开发系统中点击 查看→ 店铺 .后一种选择的优点是您可以使用包管理器将产品直接从商店安装到您的计算机。 " }, 
{ "title" : "使用 CODESYS Store International ", 
"url" : "_sto_use_store.html", 
"breadcrumbs" : "CODESYS Store \/ 使用 CODESYS Store International ", 
"snippet" : "您可以在 Web 浏览器中打开商店 ( https:\/\/store.codesys.com 或者 https:\/\/us.store.codesys.com\/ ) 或在开发系统中单击 查看 → 店铺 .后一个选项的优点是您可以使用包管理器将产品直接从商店安装到您的计算机。 有关从商店注册到安装和产品评级的必要步骤的详细说明，请参阅以下商店网站链接： CODESYS 商店的新手？开始使用 .在开发系统中使用集成 Store 的提示： 您可以将凭据保存在 CODESYS 选项。 购买许可产品后，您可以决定立即下载并安装到您的计算机上。如果是这样，那么 立即安装 必须选择选项。 注意：为了在安装过程中...", 
"body" : "您可以在 Web 浏览器中打开商店 ( https:\/\/store.codesys.com 或者 https:\/\/us.store.codesys.com\/ ) 或在开发系统中单击 查看 → 店铺 .后一个选项的优点是您可以使用包管理器将产品直接从商店安装到您的计算机。 有关从商店注册到安装和产品评级的必要步骤的详细说明，请参阅以下商店网站链接： CODESYS 商店的新手？开始使用 .在开发系统中使用集成 Store 的提示： 您可以将凭据保存在 CODESYS 选项。 购买许可产品后，您可以决定立即下载并安装到您的计算机上。如果是这样，那么 立即安装 必须选择选项。 注意：为了在安装过程中注册授权产品，您需要已经连接 CODESYS 计算机的安全密钥。 如果 立即安装 未选择该选项，则您可以稍后下载并安装在商店订购的产品。这是通过使用开发系统的包管理器手动完成的。订购时，您会收到一封包含购买确认的电子邮件并激活 下载 每个产品的直接链接。包管理器已启动，您将被定向到安装。许可证管理器需要在电子邮件中提供的许可信息和票号才能激活或更新产品许可证。 您还可以直接从应用商店执行显式下载。为此，请使用 下载 产品页面上的按钮。对于某些产品，您可以选择特定产品版本（如果存在多个）。您可以将包保存在本地计算机上或直接从包管理器安装。 通过单击包管理器对话框中的按钮，可以找到从商店下载的产品的可用更新。 " }, 
{ "title" : "WebDepot（Wibu 许可证门户） ", 
"url" : "_sto_web_depot-html.html", 
"breadcrumbs" : "CODESYS Store \/ WebDepot（Wibu 许可证门户） ", 
"snippet" : "网络仓库 是一款基于 Web 的应用程序，供您作为用户自行转让许可证。这对于软容器和 CODESYS 钥匙。可以直接传输到本地计算机或本地连接的 CmDongle 务必通过 WebDepot 为本地 CodeMeter 运行时授予许可。 例如，无法使用 SSH 通过 WebDepot 为 PLC 授予许可。你应该使用 许可证管理器 为此。 通过WebDepot下载许可证文件，您可以将许可证离线转移到另一台计算机或另一台CmDongle。 有关更多信息，请参阅： 离线激活 。...", 
"body" : "网络仓库 是一款基于 Web 的应用程序，供您作为用户自行转让许可证。这对于软容器和 CODESYS 钥匙。可以直接传输到本地计算机或本地连接的 CmDongle 务必通过 WebDepot 为本地 CodeMeter 运行时授予许可。 例如，无法使用 SSH 通过 WebDepot 为 PLC 授予许可。你应该使用 许可证管理器 为此。 通过WebDepot下载许可证文件，您可以将许可证离线转移到另一台计算机或另一台CmDongle。 有关更多信息，请参阅： 离线激活 。 " }, 
{ "title" : "参考 ", 
"url" : "_sto_f_reference.html", 
"breadcrumbs" : "CODESYS Store \/ 参考 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令：Store ", 
"url" : "_sto_cmd_store.html", 
"breadcrumbs" : "CODESYS Store \/ 参考 \/ 命令：Store ", 
"snippet" : "象征： 功能 ：该命令打开 店铺 看法。此视图是 CODESYS Store International . 称呼 ： 看法 菜单 您还可以打开 CODESYS Store International 在网络浏览器中（ http:\/\/store.codesys.com ）。 有关更多信息，请参阅： 使用...", 
"body" : "象征： 功能 ：该命令打开 店铺 看法。此视图是 CODESYS Store International . 称呼 ： 看法 菜单 您还可以打开 CODESYS Store International 在网络浏览器中（ http:\/\/store.codesys.com ）。 有关更多信息，请参阅： 使用 " }, 
{ "title" : "对话框：选项 - Store ", 
"url" : "_sto_dlg_options.html", 
"breadcrumbs" : "CODESYS Store \/ 参考 \/ 对话框：选项 - Store ", 
"snippet" : "象征： 功能 ：该对话框用于保存凭据。该对话框包含指向 CODESYS Store International 您可以在其中创建一个新的用户帐户。 称呼 ： 工具 → 选项 命令， 店铺 类别 有关更多信息，请参阅： 使用...", 
"body" : "象征： 功能 ：该对话框用于保存凭据。该对话框包含指向 CODESYS Store International 您可以在其中创建一个新的用户帐户。 称呼 ： 工具 → 选项 命令， 店铺 类别 有关更多信息，请参阅： 使用 " }
]
$(document).trigger('search.ready');
});