$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS File-Based Storage ", 
"url" : "_fbstrge_start_page.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ CODESYS File-Based Storage ", 
"snippet" : "售前赛 0.9.0.0 版本是即将推出的产品的预发布版本。该预发布版本可正常运行，但可能包含错误、功能不完整或未来版本的变更。不保证与未来版本的兼容性。需要特别指出的是，未来版本中可能存在不兼容性、功能变更或功能缺失。对于此预发布版本的错误修复、调整、更新或支持，我们不承担任何责任。 CODESYS File-Based Storage 为 CODESYS Development System (V3)。与普通的二进制项目存储不同，项目以文本形式存储在类似于项目树的文件夹结构中。不支持此格式的对象将像以前一样以 XML 格式存储。 您可以下载 CODESYS File-Based Storag...", 
"body" : "售前赛 0.9.0.0 版本是即将推出的产品的预发布版本。该预发布版本可正常运行，但可能包含错误、功能不完整或未来版本的变更。不保证与未来版本的兼容性。需要特别指出的是，未来版本中可能存在不兼容性、功能变更或功能缺失。对于此预发布版本的错误修复、调整、更新或支持，我们不承担任何责任。 CODESYS File-Based Storage 为 CODESYS Development System (V3)。与普通的二进制项目存储不同，项目以文本形式存储在类似于项目树的文件夹结构中。不支持此格式的对象将像以前一样以 XML 格式存储。 您可以下载 CODESYS File-Based Storage 从 CODESYS 国际商店 或者 CODESYS 北美商店 您还可以在那里找到该产品的数据表。 这 白皮书：CODESYS 基于文件的存储 0.9.0.0 适用于 0.9.0.0 版本。 " }, 
{ "title" : "介绍 ", 
"url" : "_fbstrge_introduction.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 介绍 ", 
"snippet" : "正常 CODESYS 项目存储库创建一个二进制文件，其内容无法被其他工具读取或创建。 CODESYS File-Based Storage 另一方面，它提供了另一种基于文本的存储格式。为项目树中的每个对象创建一个或多个文本文件，这些文本文件可以被其他文本编辑器读取，甚至创建。 使用其他工具创建项目时，必须注意 CODESYS V3 不允许项目存在不一致的情况。状态无效的项目可能无法打开或显示。 基于 XML 的导出格式用于尚无合适格式的对象类型。 CODESYS File-Based Storage 带来了一组新命令，可用于处理基于文件的项目或库。...", 
"body" : "正常 CODESYS 项目存储库创建一个二进制文件，其内容无法被其他工具读取或创建。 CODESYS File-Based Storage 另一方面，它提供了另一种基于文本的存储格式。为项目树中的每个对象创建一个或多个文本文件，这些文本文件可以被其他文本编辑器读取，甚至创建。 使用其他工具创建项目时，必须注意 CODESYS V3 不允许项目存在不一致的情况。状态无效的项目可能无法打开或显示。 基于 XML 的导出格式用于尚无合适格式的对象类型。 CODESYS File-Based Storage 带来了一组新命令，可用于处理基于文件的项目或库。 " }, 
{ "title" : "参考 ", 
"url" : "_fbstrge_reference.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令 ", 
"url" : "_fbstrge_struct_reference_commands.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 \/ 命令 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令：新建项目文件夹 ", 
"url" : "_fbstrge_cmd_new_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 \/ 命令 \/ 命令：新建项目文件夹 ", 
"snippet" : "新建项目文件夹 功能 ：该命令打开 新项目 用于创建新项目并创建文件夹的对话框 <project name>.fbsproj 该项目的存储位置。 .auxiliaries 和 .sidecars 文件夹是在项目文件夹内部创建的。 称呼 ： 胎牛血清 菜单...", 
"body" : "新建项目文件夹 功能 ：该命令打开 新项目 用于创建新项目并创建文件夹的对话框 <project name>.fbsproj 该项目的存储位置。 .auxiliaries 和 .sidecars 文件夹是在项目文件夹内部创建的。 称呼 ： 胎牛血清 菜单 " }, 
{ "title" : "命令：打开项目文件夹 ", 
"url" : "_fbstrge_cmd_open_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 \/ 命令 \/ 命令：打开项目文件夹 ", 
"snippet" : "打开项目文件夹 功能 ：该命令打开文件资源管理器来选择项目文件夹。 称呼 ： 胎牛血清 菜单...", 
"body" : "打开项目文件夹 功能 ：该命令打开文件资源管理器来选择项目文件夹。 称呼 ： 胎牛血清 菜单 " }, 
{ "title" : "命令：转换项目 ", 
"url" : "_fbstrge_cmd_convert_project.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 \/ 命令 \/ 命令：转换项目 ", 
"snippet" : "转换项目 功能 ：该命令将 CODESYS 项目进入 .fbs项目 格式。为此，请先打开 浏览 对话框中选择要存储转换后项目的文件夹。然后 将项目转换为基于文件的存储 对话框打开。此对话框显示项目中将转换为基于文件存储格式的对象和设备，并检查转换是否能够顺利进行。出现警告或无法顺利进行转换的对象和设备将显示在对话框右侧。此外，还会显示相关的警告或错误消息以及修复按钮。 称呼 ： 胎牛血清 菜单 对话： 将项目转换为基于文件的存储 左侧区域 设备 CODESYS 项目在 设备 看法 程序单元 CODESYS 项目 程序单元 看法 右侧区域 目的 转换过程中发生错误或出现警告的对象 错误 显示错误...", 
"body" : "转换项目 功能 ：该命令将 CODESYS 项目进入 .fbs项目 格式。为此，请先打开 浏览 对话框中选择要存储转换后项目的文件夹。然后 将项目转换为基于文件的存储 对话框打开。此对话框显示项目中将转换为基于文件存储格式的对象和设备，并检查转换是否能够顺利进行。出现警告或无法顺利进行转换的对象和设备将显示在对话框右侧。此外，还会显示相关的警告或错误消息以及修复按钮。 称呼 ： 胎牛血清 菜单 对话： 将项目转换为基于文件的存储 左侧区域 设备 CODESYS 项目在 设备 看法 程序单元 CODESYS 项目 程序单元 看法 右侧区域 目的 转换过程中发生错误或出现警告的对象 错误 显示错误和警告 警告仅供参考。例如：用户管理处于活动状态。该状态将在转换过程中丢失。 错误会阻止转换。 可能的错误： 未安装设备描述 在 CODESYS 项目树（ 设备 查看或 程序单元 在“文件夹视图”中，同一层级有两个同名的文件夹。 对象名称长度超过 255 个字符。 该文件夹有 2 个属性。 只要存在一个属性就足够了。 使固定 快速更正错误的按钮。是否可以快速修复取决于具体错误。 " }, 
{ "title" : "命令：最近的项目 ", 
"url" : "_fbstrge_cmd_recent_projects.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 \/ 命令 \/ 命令：最近的项目 ", 
"snippet" : "最近的项目 功能 ：该命令显示最近的项目 *.fbsproj 格式。单击相应的项目即可打开。 称呼 ： 胎牛血清 菜单...", 
"body" : "最近的项目 功能 ：该命令显示最近的项目 *.fbsproj 格式。单击相应的项目即可打开。 称呼 ： 胎牛血清 菜单 " }, 
{ "title" : "命令：在文件资源管理器中打开文件夹 ", 
"url" : "_fbstrge_cmd_open_folder_in_file_explorer.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ 参考 \/ 命令 \/ 命令：在文件资源管理器中打开文件夹 ", 
"snippet" : "在文件资源管理器中打开文件夹 功能 ：该命令打开项目文件夹 *.fbsproj 在文件资源管理器中打开项目。 称呼 ： 胎牛血清 菜单...", 
"body" : "在文件资源管理器中打开文件夹 功能 ：该命令打开项目文件夹 *.fbsproj 在文件资源管理器中打开项目。 称呼 ： 胎牛血清 菜单 " }
]
$(document).trigger('search.ready');
});