$(document).ready(function () {indexDict['en-US'] = [{ "title" : "CODESYS File-Based Storage ", 
"url" : "_fbstrge_start_page.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ CODESYS File-Based Storage ", 
"snippet" : "Prerelease Version 0.9.0.0 is the prerelease of an upcoming product. The prerelease is functional, but may contain errors, incomplete functions, or changes in future versions. Compatibility with future versions is not guaranteed. It is strictly pointed out that incompatibilities, functional changes,...", 
"body" : "Prerelease Version 0.9.0.0 is the prerelease of an upcoming product. The prerelease is functional, but may contain errors, incomplete functions, or changes in future versions. Compatibility with future versions is not guaranteed. It is strictly pointed out that incompatibilities, functional changes, or the loss of functions are possible in future versions. A claim to bug fixes, adaptations, updates, or support for this prerelease is excluded. CODESYS File-Based Storage provides an alternative project storage format for the CODESYS Development System (V3). In contrast to ordinary binary project storage, projects are stored as text-based in a folder structure similar to the project tree. Objects which do not support this format are stored in XML format as before. You can download the CODESYS File-Based Storage from CODESYS Store International or CODESYS Store North America . There you will also find the data sheet for the product. The White paper: CODESYS File-Based Storage 0.9.0.0 is available for version 0.9.0.0. " }, 
{ "title" : "Introduction ", 
"url" : "_fbstrge_introduction.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Introduction ", 
"snippet" : "The normal CODESYS project repository creates a single binary file whose contents cannot be read or created by other tools. CODESYS File-Based Storage , on the other hand, provides another text-based storage format. One or more text files are created for each object in the project tree, and these te...", 
"body" : "The normal CODESYS project repository creates a single binary file whose contents cannot be read or created by other tools. CODESYS File-Based Storage , on the other hand, provides another text-based storage format. One or more text files are created for each object in the project tree, and these text files can be read or even created by other text editors. When creating projects from other tools, it must be noted that CODESYS V3 does not allow inconsistencies in the project. Projects with an invalid status may not be able to be opened or displayed. The XML-based export format is used for object types for which there is not (yet) a suitable format. CODESYS File-Based Storage brings with it a set of new commands which can be used for working with file-based projects or libraries. " }, 
{ "title" : "Reference ", 
"url" : "_fbstrge_reference.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Commands ", 
"url" : "_fbstrge_struct_reference_commands.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference \/ Commands ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Command: New Project Folder ", 
"url" : "_fbstrge_cmd_new_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference \/ Commands \/ Command: New Project Folder ", 
"snippet" : "New Project Folder Function : The command opens the New Project dialog for creating a new project and creates a folder <project name>.fbsproj for this project in the storage location of the project. The .auxiliaries and .sidecars folders are created internally in the project folder. Call : FBS menu...", 
"body" : "New Project Folder Function : The command opens the New Project dialog for creating a new project and creates a folder <project name>.fbsproj for this project in the storage location of the project. The .auxiliaries and .sidecars folders are created internally in the project folder. Call : FBS menu " }, 
{ "title" : "Command: Open Project Folder ", 
"url" : "_fbstrge_cmd_open_project_folder.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference \/ Commands \/ Command: Open Project Folder ", 
"snippet" : "Open Project Folder Function : The command opens the file explorer to select the project folder. Call : FBS menu...", 
"body" : "Open Project Folder Function : The command opens the file explorer to select the project folder. Call : FBS menu " }, 
{ "title" : "Command: Convert Project ", 
"url" : "_fbstrge_cmd_convert_project.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference \/ Commands \/ Command: Convert Project ", 
"snippet" : "Convert Project Function : The command converts a CODESYS project into the .fbsproj format. To do this, first open the Browse dialog to select the folder where the converted project will be stored. Then the Convert project to file-based storage dialog opens. This dialog displays the objects and devi...", 
"body" : "Convert Project Function : The command converts a CODESYS project into the .fbsproj format. To do this, first open the Browse dialog to select the folder where the converted project will be stored. Then the Convert project to file-based storage dialog opens. This dialog displays the objects and devices of the project which will be converted to the file-based storage format and checks whether the conversion is possible without errors. The objects and devices for which there are warnings or for which conversion is not possible without errors are displayed on the right side of the dialog. The relevant warning or error message and a fix button are also displayed. Call : FBS menu Dialog: Convert project to file-based storage Left area Devices CODESYS project in the Devices view POUs CODESYS project in POUs view Right area Object Object for which an error occurs during conversion or for which there is a warning Error Display of errors and warnings Warnings are for information only. Example: A user management is active. This will be lost during the conversion. Errors prevent the conversion. Possible errors: Device description is not installed In the CODESYS project tree ( Devices view or POUs view), there are two folders with the same name at the same level. The name of the object is longer than 255 characters. There are 2 properties for the folder. It would be sufficient if one property exists. Fix Button to quickly correct the error. Whether a quick fix is possible depends on the error in question. " }, 
{ "title" : "Command: Recent Projects ", 
"url" : "_fbstrge_cmd_recent_projects.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference \/ Commands \/ Command: Recent Projects ", 
"snippet" : "Recent Projects Function : The command displays the recent projects in *.fbsproj format. Click the respective project to open it. Call : FBS menu...", 
"body" : "Recent Projects Function : The command displays the recent projects in *.fbsproj format. Click the respective project to open it. Call : FBS menu " }, 
{ "title" : "Command: Open Folder in File Explorer ", 
"url" : "_fbstrge_cmd_open_folder_in_file_explorer.html", 
"breadcrumbs" : "CODESYS File-Based Storage \/ Reference \/ Commands \/ Command: Open Folder in File Explorer ", 
"snippet" : "Open Folder in File Explorer Function : The command opens the project folder *.fbsproj of the open project in the file explorer. Call : FBS menu...", 
"body" : "Open Folder in File Explorer Function : The command opens the project folder *.fbsproj of the open project in the file explorer. Call : FBS menu " }
]
$(document).trigger('search.ready');
});