$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS Redundancy ", 
"url" : "_rdncy_start_page.html", 
"breadcrumbs" : "CODESYS Redundancy \/ CODESYS Redundancy ", 
"snippet" : "CODESYS Redundancy 为您提供为第一个 PLC 冗余运行第二个 PLC 所需的功能。冗余 PLC 能够在运行时接管应用程序的执行。 这使您可以提高控制系统的可靠性并保护您的控制器。例如，这可以防止系统故障。...", 
"body" : "CODESYS Redundancy 为您提供为第一个 PLC 冗余运行第二个 PLC 所需的功能。冗余 PLC 能够在运行时接管应用程序的执行。 这使您可以提高控制系统的可靠性并保护您的控制器。例如，这可以防止系统故障。 " }, 
{ "title" : "冗余 ", 
"url" : "_rtsl_redundancy.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 ", 
"snippet" : "冗余控制系统 您可以通过使用冗余的 PLC 保护您的 PLC 来提高控制系统的可靠性。冗余 PLC 能够在运行时接管应用程序的执行。例如，这可以防止系统故障。 该图显示了冗余控制系统的结构。该应用程序在两个 PLC 上同时运行：一个处于活动状态的 PLC (1) 和第二个处于待机模式 (2) 的 PLC。处于待机模式的 PLC 读取连接的现场总线系统（图中的 EtherCAT）的输入，并通过冗余链路 (3) 与主动 PLC 同步。这允许备用 PLC 在发生故障时立即处于活动状态，并且可以不间断地接管现场总线 (4) 的控制 冗余互连 (3) 使用 TCP 和 UDP 实现，但可以由供应商特定的...", 
"body" : "冗余控制系统 您可以通过使用冗余的 PLC 保护您的 PLC 来提高控制系统的可靠性。冗余 PLC 能够在运行时接管应用程序的执行。例如，这可以防止系统故障。 该图显示了冗余控制系统的结构。该应用程序在两个 PLC 上同时运行：一个处于活动状态的 PLC (1) 和第二个处于待机模式 (2) 的 PLC。处于待机模式的 PLC 读取连接的现场总线系统（图中的 EtherCAT）的输入，并通过冗余链路 (3) 与主动 PLC 同步。这允许备用 PLC 在发生故障时立即处于活动状态，并且可以不间断地接管现场总线 (4) 的控制 冗余互连 (3) 使用 TCP 和 UDP 实现，但可以由供应商特定的组件所取代。 此外，您可以在冗余控制系统运行时使用可视化 CODESYS WebVisu 在浏览器中。如果发生切换，可视化客户端将继续几乎无缝运行。 有关功能的基本信息 应用程序编程人员将应用程序下载到第一个 PLC 并创建启动应用程序。 第二个 PLC 在启动时同步，接收启动应用程序。 启动应用程序已加载并初始化，然后准备执行第一个任务周期。来自寄存器区域的所有数据（所有 IEC 数据）都传输到第二个 PLC。这意味着冗余是有效的，应用程序任务在两个 PLC 上同步执行。任务执行的同步由通过冗余互连发送的消息来实现。这些消息是在执行 IEC 任务之前和之后发送的。 没有首选的主动 PLC。操作模式由启动顺序决定。第一个启动的 PLC 通过冗余互连发送相应的消息。如果它没有收到响应，则会加载启动应用程序并在独立模式下运行。 如果备用 PLC 未在配置的时间内收到来自主动 PLC 的消息，则备用 PLC 会假定主动 PLC 不再工作。结果，备用 PLC 切换到独立模式，现在控制现场总线 I\/O。如果主动 PLC 在配置的时间内没有收到来自备用 PLC 的消息，它也会切换到独立模式。 如果更换第一个 PLC 并重新启动，则它会与当前处于独立模式的另一个 PLC 同步，如上所述，因此进入待机模式。 待机 PLC 可以切换到仿真模式。然后不会激活冗余，但现场总线将保持停用状态，就像待机模式一样。主动 PLC 切换到独立模式。可以通过重新同步或重新启动 PLC 来结束仿真模式。然后，PLC 切换回待机模式，除非在同步或重启期间出现错误。 如果在更新启动应用程序或寄存器区域期间或冗余周期期间发生错误，则 PLC 将切换到错误模式。然后必须对其进行重新同步 \"Redundancy using the example of two Raspberry Pis with CODESYS Control for Raspberry Pi SL\" 该视频旨在向您概述此功能。的功能范围 CODESYS Redundancy 可以看出，可能与当前的功能范围有所不同。 冗余 PLC 的示例项目 " }, 
{ "title" : "用户界面 ", 
"url" : "_rtsl_redundancy_ui.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 用户界面 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CODESYS 功能性 ", 
"url" : "_rtsl_redundancy_ui.html#UUID-689edd71-4337-9ebf-177f-341dad05eddf_id_c5d7e42a9a33ac0a86463419d722f-id-8345c315434f0847c0a8646308a9d491", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 用户界面 \/ CODESYS 功能性 ", 
"snippet" : "目的： 冗余配置选项卡： 冗余设置在这里，您可以配置冗余链路的通信设置并定义相关的任务和监视程序。 选项卡： 可视化在这里，您可以在 PLC 上运行的 Web 服务器之间配置冗余链接。因此，您可以连接可视化，这些可视化以以下方式运行 CODESYS WebVisu 在浏览器中，使用冗余控制系统。 标签： 注册区域在这里，您可以管理应在运行时同步的数据和区域。 标签： 冗余状态在运行时， CODESYS 监控冗余系统并显示那里的当前状态。您还可以在那里访问最重要的冗余命令，例如，命令在状态之间切换 标签： 日志列出来自 PLC 记录器的历史冗余事件 支持以下现场总线： EtherCAT ( CO...", 
"body" : "目的： 冗余配置选项卡： 冗余设置在这里，您可以配置冗余链路的通信设置并定义相关的任务和监视程序。 选项卡： 可视化在这里，您可以在 PLC 上运行的 Web 服务器之间配置冗余链接。因此，您可以连接可视化，这些可视化以以下方式运行 CODESYS WebVisu 在浏览器中，使用冗余控制系统。 标签： 注册区域在这里，您可以管理应在运行时同步的数据和区域。 标签： 冗余状态在运行时， CODESYS 监控冗余系统并显示那里的当前状态。您还可以在那里访问最重要的冗余命令，例如，命令在状态之间切换 标签： 日志列出来自 PLC 记录器的历史冗余事件 支持以下现场总线： EtherCAT ( CODESYS GmbH 堆） PROFINET CANopen 您可以在中配置现场总线 冗余配置 上的对象 将军 的选项卡 冗余设置 选项卡。 有关更多信息，请参阅： 一般的" }, 
{ "title" : "库：Redundancy ", 
"url" : "_rtsl_redundancy_ui.html#UUID-689edd71-4337-9ebf-177f-341dad05eddf_id_c5d7e42a9a33ac0a86463419d722f-id-63b2ef67616e11eb98d8f7694f7eb408", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 用户界面 \/ 库：Redundancy ", 
"snippet" : "这个 Redundancy Implementation 库，其中包括 Redundancy 库，提供 POU，例如 SwitchToActive 或者 SwitchToStandby 这样您就可以以编程方式访问冗余组件。例如，你可以使用 SwitchToActive 在活动模式下对 PLC 的切换进行编程。...", 
"body" : "这个 Redundancy Implementation 库，其中包括 Redundancy 库，提供 POU，例如 SwitchToActive 或者 SwitchToStandby 这样您就可以以编程方式访问冗余组件。例如，你可以使用 SwitchToActive 在活动模式下对 PLC 的切换进行编程。 " }, 
{ "title" : "图书馆：VisuRedundancy ", 
"url" : "_rtsl_redundancy_ui.html#UUID-689edd71-4337-9ebf-177f-341dad05eddf_id_c5d7e42a9a33ac0a86463419d722f-id-8c6792a342bce9e3c0a864637b92e336", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 用户界面 \/ 图书馆：VisuRedundancy ", 
"snippet" : "这个 VisuRedundancy 库实现了可视化的冗余链接，并提供功能块，例如用于监控活动。...", 
"body" : "这个 VisuRedundancy 库实现了可视化的冗余链接，并提供功能块，例如用于监控活动。 " }, 
{ "title" : "运行时系统 ", 
"url" : "_rtsl_redundancy_runtime.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 运行时系统 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "安装 ", 
"url" : "_rtsl_redundancy_runtime.html#UUID-9b35f1a6-51d3-508d-50b3-1db5ff29f1c6_id_da35e42b65f05c0a86463636fb62a-id-3b2fbd4e5bd811ebbc9abec28e249299", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 运行时系统 \/ 安装 ", 
"snippet" : "为了冗余地操作控制系统， CmpRedundancy 冗余组件以及操作冗余链路的附加组件可在 运行时系统 PLC 的数量。这个附加组件是特定于设备的，但 IP 链接是常见的： CmpRedundancyConnectionIP 。...", 
"body" : "为了冗余地操作控制系统， CmpRedundancy 冗余组件以及操作冗余链路的附加组件可在 运行时系统 PLC 的数量。这个附加组件是特定于设备的，但 IP 链接是常见的： CmpRedundancyConnectionIP 。 " }, 
{ "title" : "功能性 ", 
"url" : "_rtsl_redundancy_runtime.html#UUID-9b35f1a6-51d3-508d-50b3-1db5ff29f1c6_id_da35e42b65f05c0a86463636fb62a-id-c3e2e06042bb2255c0a8646334ca8cc0", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 运行时系统 \/ 功能性 ", 
"snippet" : "将两个 PLC 链接到冗余系统 同步冗余数据 切换 PLC 的运行状态 在记录器中记录冗余事件 运行时发生的事件由运行时系统的记录器记录在两个设备上。 例子 配置文件 *.cfg 对于一个运行时 CODESYS Control Win 存储在 ProgramData . [CmpRedundancyConnectionIP] Link1.IpAddressLocal=192.168.56.1 ; IP address of redundancy link of local PLC Link1.IpAddressPeer=192.168.56.101 ; IP address of redund...", 
"body" : "将两个 PLC 链接到冗余系统 同步冗余数据 切换 PLC 的运行状态 在记录器中记录冗余事件 运行时发生的事件由运行时系统的记录器记录在两个设备上。 例子 配置文件 *.cfg 对于一个运行时 CODESYS Control Win 存储在 ProgramData . [CmpRedundancyConnectionIP]\nLink1.IpAddressLocal=192.168.56.1 ; IP address of redundancy link of local PLC\nLink1.IpAddressPeer=192.168.56.101 ; IP address of redundancy link of peer PLC\nLink1.Port=1205\n\n[CmpRedundancy]\nBootupWaitTime=5000\nTcpWaitTime=2000\nStandbyWaitTime=50 ; This timeout depends on the quality of real time task and communication system\nLockTimeout=20 ; Maximum time of timer lock\nBootproject=Application ; Name of your CODESYS application\nRedundancyTaskName=MainTask ; Task name in your CODESYS application\nPlcIdent=1 ; PlcIdent=2 on other PLC\n\n " }, 
{ "title" : "启动应用程序 ", 
"url" : "_rtsl_redundancy_runtime.html#UUID-9b35f1a6-51d3-508d-50b3-1db5ff29f1c6_id_da35e42b65f05c0a86463636fb62a-id-1679b7d142bb2255c0a86463594e956e", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 运行时系统 \/ 启动应用程序 ", 
"snippet" : "引导应用程序以相同方式存储在两个 PLC 上。当您想要更新引导应用程序时，只需将其下载到活动的 PLC 中即可。...", 
"body" : "引导应用程序以相同方式存储在两个 PLC 上。当您想要更新引导应用程序时，只需将其下载到活动的 PLC 中即可。 " }, 
{ "title" : "限制 ", 
"url" : "_rtsl_redundancy_restrictions.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 限制 ", 
"snippet" : "CODESYS 版本 必须在两个设备上安装相同版本的运行时系统，因为引导项目在控制器之间传输，因此必须可在第二个控制器上加载。 实时任务和沟通 只允许循环任务。任务类型 事件 ， 状态 ，或 随心所欲 无法同步。 这 CODESYS Redundancy 功能仅同步一项任务（ 冗余任务 ）。其他任务和应用程序也是可能的，但它们在两个 PLC 上运行不同步。 此外，影响任务执行和通信的冗余系统必须满足一定的实时性要求：冗余通信的消息（请求和响应）的运行时间必须存在于预先定义的时间间隔内，并且任务抖动必须被考虑。 实时任务执行意味着由冗余控制的应用程序任务具有有限的抖动。实时通信意味着通过冗余链接...", 
"body" : "CODESYS 版本 必须在两个设备上安装相同版本的运行时系统，因为引导项目在控制器之间传输，因此必须可在第二个控制器上加载。 实时任务和沟通 只允许循环任务。任务类型 事件 ， 状态 ，或 随心所欲 无法同步。 这 CODESYS Redundancy 功能仅同步一项任务（ 冗余任务 ）。其他任务和应用程序也是可能的，但它们在两个 PLC 上运行不同步。 此外，影响任务执行和通信的冗余系统必须满足一定的实时性要求：冗余通信的消息（请求和响应）的运行时间必须存在于预先定义的时间间隔内，并且任务抖动必须被考虑。 实时任务执行意味着由冗余控制的应用程序任务具有有限的抖动。实时通信意味着通过冗余链接发送的消息必须在特定时间内被其他 PLC 接收。 任务执行时间 消息传递持续时间（请求和响应的时间）增加了任务的执行时间：使用冗余时任务的总执行时间更长。 更改应用程序和任务的名称 更改冗余应用程序或冗余任务的名称是一项重大更改，并且在冗余操作期间是不可能的。这是因为，在更改后，您必须按照“配置冗余系统”下的“入门”中所述重新配置两个 PLC。 超时值 您为超时指定的值必须大于任务抖动时间和最大通信抖动时间之和。这两个时间都是系统特定的。在运行时，当任务抖动高，消息传输延迟时，就会发生超时。在等待来自其他 PLC 的消息时，系统假定其他 PLC 不再运行。结果，等待 PLC 和发送 PLC 切换到独立模式。这会导致同步丢失和现场总线上的通信问题。 您可以定义主动 PLC 切换到独立模式时的超时时间 冗余配置 编辑器，在 将军 的选项卡 冗余设置 选项卡。此外，该值存储在运行时配置文件中（例如： CODESYSControl.cfg ) 带有条目 StandbyWaitTime 。 IEC 定时器 切换 PLC 时，两个 PLC 上不同的执行时间可能会导致“颠簸”（输出值偏离）。为了防止这种情况发生，IEC 定时器值在 IEC 任务执行期间被冻结。来自 IEC 定时器的调用（例如：函数 TON ) 因此，在执行 IEC 任务时始终会导致相同的计时器值，即使物理时间继续运行。因此，实现应该不活动地等待（可能在循环中）。这是因为 IEC 定时器值在当前任务扫描中不会改变。 指针、引用和接口 这个 POINTER TO ， REFERENCE TO ，以及 INTERFACE 用于表达应用程序单元之间关系的语句（和接口实例）不适用于同步的冗余应用程序。 POINTER 变量不得在由冗余控制的数据区域中声明。这是因为在同步期间将冗余控制的数据传输到其他 PLC。但是，指针在另一个 PLC 上无效，因为那里可能有另一个内存布局。 编译时，冗余功能检查指针是否位于冗余控制区域。在那里找到的每个指针都会显示一条警告。可以在设备描述文件中通过以下条目禁用检查： <Device>\n <Custom>\n <Redundancy DisablePointerChecks=\"true\"> EtherCAT 直流 这种冗余扩展更多地用于过程工业而不是工厂自动化。因此，不支持具有分布式时钟的 EtherCAT 驱动器。但是，支持 EtherCAT I\/O。 另请参阅上面的“实时任务和通信”部分。 “现有的映射”：映射到现有变量 不建议使用 I\/O 映射方法“Map on Existing”（将 I\/O 映射到现有变量） CODESYS Redundancy 。这些类型的变量并不存储在输入或输出数据区域中，而是存储在声明它们的位置中。因此，它们在操作期间不同步。 网络变量 不得使用具有写入权限的网络变量，因为同时发送了多个写入电报。允许具有读取权限的网络变量。 文件访问 不能使用文件访问，因为不同的文件数据会在不同的 PLC 切换时造成“碰撞”。 如果使用文件，则必须在不受冗余控制的数据区域中声明文件句柄。这些文件必须在两个 PLC 上分别打开。不得使用其他 PLC 的文件句柄访问本地 PC 上的文件。 编译时， CODESYS Redundancy 检查处理变量（ RTS_IEC_HANDLE , CAA.HANDLE ）位于冗余控制区域。对于在此类区域中检测到的每个句柄变量，都会发出警告。 在线安全用户管理 如果使用在线安全用户管理，则需要使用相同的用户名和密码配置两个 PLC。否则，在线服务，例如 write variable 或者 online change 未传输到备用 PLC。 软运动 CODESYS SoftMotion 和 CODESYS Redundancy 不能合并。 SoftMotion 的时间要求 不能 使用冗余时实现。 " }, 
{ "title" : "入门 ", 
"url" : "_rtsl_redundancy_first_step.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 入门 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "组态冗余系统 ", 
"url" : "_rtsl_redundancy_first_step.html#UUID-1a24f83c-0102-b2a5-8b10-a743eb89a3ca_id_cfffe024edd4487c0a86463419d722f-id-ba49750949672ba3c0a86463623c4dcb", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 入门 \/ 组态冗余系统 ", 
"snippet" : "用户管理 如果在 PLC 上使用用户管理，则必须配置相同的用户名和相同的密码才能访问两个 PLC 设备。否则，在线服务，如 write variable 要么 online change 不会传输到当前不活动的 PLC。 您想要冗余操作的每个设备都需要具有冗余功能的运行系统 CmpRedundancy 和 CmpRedundancyConnectionIP 冗余组件。设备树中的顶层设备通常是主动控制的设备。设备的设置会自动应用为 可编程逻辑控制器1 设置为 冗余配置 。冗余设备配置为 PLC 2 在冗余编辑器中。 这些设备可以交换它们的角色。 要求：设备正在运行。一个标准项目在 CODESYS...", 
"body" : "用户管理 如果在 PLC 上使用用户管理，则必须配置相同的用户名和相同的密码才能访问两个 PLC 设备。否则，在线服务，如 write variable 要么 online change 不会传输到当前不活动的 PLC。 您想要冗余操作的每个设备都需要具有冗余功能的运行系统 CmpRedundancy 和 CmpRedundancyConnectionIP 冗余组件。设备树中的顶层设备通常是主动控制的设备。设备的设置会自动应用为 可编程逻辑控制器1 设置为 冗余配置 。冗余设备配置为 PLC 2 在冗余编辑器中。 这些设备可以交换它们的角色。 要求：设备正在运行。一个标准项目在 CODESYS Development System .通信参数设置为 可编程逻辑控制器 1 . 在设备树中，选择应用程序并添加 冗余配置 目的。 这 冗余配置 编辑器打开。冗余系统以图形方式显示在 冗余状态 标签。当前的通讯设置 可编程逻辑控制器1 已由设备编辑器应用并已显示。 如果 可编程逻辑控制器 1 报告 未加载组件 冗余状态，则冗余组件在其运行时系统中不活动。 点击 设置活动路径 PLC 2 按钮。 这 选择设备 对话框打开。 从检测到的设备列表中，选择一个作为 可编程逻辑控制器 2 . 通信设置应用并显示在下图中 可编程逻辑控制器 2 ( 网关 ）。 选择 冗余设置 选项卡，然后 冗余链路 标签。 点击 浏览 按钮 IP 地址 PLC 1 和 IP 地址 PLC 2 设置。 注意：冗余使用自己的协议，与 CODESYS 通信协议无关。 列出了相应设备的 IP 地址。 选择所需条目并单击 好的 以确认您的选择。 IP 地址已申请。确保配置了两个 IP 地址。 例子： IP Address SPS 1 0001\nIP Address SPS 2 0101\nPort 1205 点击 一般的 标签。 配置您的应用程序和现场总线。 冗余任务名称 ： 例如 MainTask 因为任务是项目中的名称 超时（毫秒） ： 30 为两个控制器之间的超时指定一个实际值。 同步超时（毫秒） ： 0 点击 写 按钮。 冗余设置应用于控制器。但它们尚未写入 CFG 文件。这仅在 PLC 停止时进行。因此，两个 PLC 在下一步中都停止。 点击 在线 → 登录 . 将显示一个消息视图，提示输入所需的登录类型。 选择 登录下载 . 应用程序下载到 可编程逻辑控制器 1 . 关闭两个 PLC。 （这里不是通过命令终止应用程序 在线的 停止 意思是，但运行时系统的终止。） 开始 只要 可编程逻辑控制器 1 . 引导项目下载到 可编程控制器 1 . 可编程控制器 1 处于独立模式。之后，只开始 可编程控制器 2 . 现在开始 可编程逻辑控制器 2 . 启动时，执行同步。应用程序和数据从 可编程逻辑控制器 1 到 可编程逻辑控制器 2 .最后， 可编程逻辑控制器 1 是活跃的并且 可编程逻辑控制器 2 正在待机模式下运行。 " }, 
{ "title" : "使用具有可视化功能的冗余控制系统 ", 
"url" : "_rtsl_redundancy_first_step.html#UUID-1a24f83c-0102-b2a5-8b10-a743eb89a3ca_id_cfffe024edd4487c0a86463419d722f-id-b3b02a00ebe5b55fc0a864634c22e30b", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 入门 \/ 使用具有可视化功能的冗余控制系统 ", 
"snippet" : "您可以连接可视化，这些可视化运行为 CODESYS WebVisu 在浏览器中，带有冗余控制系统。如果发生切换，可视化客户端将继续几乎无缝运行。 类似的配置也可能基于 CODESYS HMI 当这些冗余运行时。 打开冗余编辑器，单击 冗余设置 选项卡，然后单击 可视化 标签。 选择 使能够 选项。 冗余控制系统 CODESYS WebVisu 链接已启用。 选择 使用冗余链路配置 . PLC 之间的冗余链接设置适用于 Web 服务器连接。当 Web 可视化通过也用于冗余链接的同一网络连接进行访问时，这是可能的。 例子：...", 
"body" : "您可以连接可视化，这些可视化运行为 CODESYS WebVisu 在浏览器中，带有冗余控制系统。如果发生切换，可视化客户端将继续几乎无缝运行。 类似的配置也可能基于 CODESYS HMI 当这些冗余运行时。 打开冗余编辑器，单击 冗余设置 选项卡，然后单击 可视化 标签。 选择 使能够 选项。 冗余控制系统 CODESYS WebVisu 链接已启用。 选择 使用冗余链路配置 . PLC 之间的冗余链接设置适用于 Web 服务器连接。当 Web 可视化通过也用于冗余链接的同一网络连接进行访问时，这是可能的。 例子： " }, 
{ "title" : "使用冗余控制系统 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 ", 
"snippet" : "有关更多信息，请参阅： 调用命令时冗余系统的行为...", 
"body" : "有关更多信息，请参阅： 调用命令时冗余系统的行为" }, 
{ "title" : "通过在线更改加载和启动应用程序 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-bdfc47548889fe7bc0a864630bdd6c37", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 通过在线更改加载和启动应用程序 ", 
"snippet" : "要求：配置为 PLC PLC 1 和 PLC 2 正在运行，更新的应用程序已准备就绪，可供下载。 在设备树中选择您的应用程序。 点击 在线 → 登录 . 对话框提示将打开，询问您要如何登录。 选择 使用在线更改登录 . 应用程序更新于 可编程逻辑控制器 1 . PLC 2 切换到模拟模式并在大约 10 秒钟后同步。之后，两个 PLC 再次处于活动\/待机模式 这 启用 , 切换 , 同步 ， 和 模拟 命令在启用 冗余状态 标签。...", 
"body" : "要求：配置为 PLC PLC 1 和 PLC 2 正在运行，更新的应用程序已准备就绪，可供下载。 在设备树中选择您的应用程序。 点击 在线 → 登录 . 对话框提示将打开，询问您要如何登录。 选择 使用在线更改登录 . 应用程序更新于 可编程逻辑控制器 1 . PLC 2 切换到模拟模式并在大约 10 秒钟后同步。之后，两个 PLC 再次处于活动\/待机模式 这 启用 , 切换 , 同步 ， 和 模拟 命令在启用 冗余状态 标签。 " }, 
{ "title" : "仅在 PLC 1 运行时启动 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-9937c23e8889fe7bc0a864630a110c5d", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 仅在 PLC 1 运行时启动 ", 
"snippet" : "要求： 可编程逻辑控制器 1 在跑。一个标准项目在 CODESYS Development System .通信参数设置为 可编程逻辑控制器 1 . 在设备编辑器中，打开 通讯设置 标签并搜索网络。 准备好的设备列在 选择设备 对话。 选择设备 可编程逻辑控制器 1 并点击 好的 确认选择。 设备连接设置已配置。 点击 在线 → 登录 . 应用程序下载到 可编程逻辑控制器 1 . 调试 → 开始 可编程逻辑控制器 1 以独立模式运行。 在上启动运行时系统 PLC 2 。 同步阶段开始：应用应用程序和冗余数据。之后， PLC 1 切换到活动状态并且 PLC 2 切换到待机状态。...", 
"body" : "要求： 可编程逻辑控制器 1 在跑。一个标准项目在 CODESYS Development System .通信参数设置为 可编程逻辑控制器 1 . 在设备编辑器中，打开 通讯设置 标签并搜索网络。 准备好的设备列在 选择设备 对话。 选择设备 可编程逻辑控制器 1 并点击 好的 确认选择。 设备连接设置已配置。 点击 在线 → 登录 . 应用程序下载到 可编程逻辑控制器 1 . 调试 → 开始 可编程逻辑控制器 1 以独立模式运行。 在上启动运行时系统 PLC 2 。 同步阶段开始：应用应用程序和冗余数据。之后， PLC 1 切换到活动状态并且 PLC 2 切换到待机状态。 " }, 
{ "title" : "在活动\/待机模式运行时加载应用程序 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-2abafef13ef863a8c0a86463043b772d", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 在活动\/待机模式运行时加载应用程序 ", 
"snippet" : "下载到激活的 PLC 要求：两个 PLC 都在运行。一个冗余项目在 CODESYS . 在设备编辑器中，打开 通讯设置 标签并搜索网络。 准备好的设备列在 选择设备 对话。 选择设备 可编程逻辑控制器 1 并点击 好的 确认选择。 设备连接设置已配置。 点击 在线的 → 登录 . 在打开的对话框提示中，选择 登录下载 选项。 应用程序停止运行 PLC 1 在单个系统上加载时也是如此。该应用程序被删除，加载新应用程序的操作开始。在这段时间里 PLC 2 切换到冗余仿真模式。一段时间后， PLC 2 尝试再次同步。每 10 秒重复一次尝试。如果时间已经过去了 10 秒以上 PLC 1 开始， PL...", 
"body" : "下载到激活的 PLC 要求：两个 PLC 都在运行。一个冗余项目在 CODESYS . 在设备编辑器中，打开 通讯设置 标签并搜索网络。 准备好的设备列在 选择设备 对话。 选择设备 可编程逻辑控制器 1 并点击 好的 确认选择。 设备连接设置已配置。 点击 在线的 → 登录 . 在打开的对话框提示中，选择 登录下载 选项。 应用程序停止运行 PLC 1 在单个系统上加载时也是如此。该应用程序被删除，加载新应用程序的操作开始。在这段时间里 PLC 2 切换到冗余仿真模式。一段时间后， PLC 2 尝试再次同步。每 10 秒重复一次尝试。如果时间已经过去了 10 秒以上 PLC 1 开始， PLC 2 切换到错误模式，但仍尝试同步。 开始 可编程逻辑控制器 1 . 同步开始，应用程序和冗余数据被传输到 可编程逻辑控制器 2 . 不支持下载到在待机模式下运行的 PLC。错误消息表明您需要登录到活动的 PLC。 " }, 
{ "title" : "实现冗余状态的编程查询 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-e0fa157e4421fe03c0a8640e0155de2a", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 实现冗余状态的编程查询 ", 
"snippet" : "在 POU 中 PLC_PRG ，实现对冗余状态的查询。 PROGRAM PRG_PLC VAR sReduState: RedundancyState; bResult: BOOL; END_VAR bResult := RDCY.GetRedundancyState(ADR(sReduState)); 登录到 可编程逻辑控制器 1 并确认在线更改。 PLC 1 和 PLC 2 连续启动并切换到活动\/待机模式。 state.eRedundancyState 变量获取当前状态，以便您可以对其进行监控。 提示：当前状态也显示在 冗余状态 标签。...", 
"body" : "在 POU 中 PLC_PRG ，实现对冗余状态的查询。 PROGRAM PRG_PLC\nVAR\n sReduState: RedundancyState;\n bResult: BOOL;\nEND_VAR\n\nbResult := RDCY.GetRedundancyState(ADR(sReduState)); 登录到 可编程逻辑控制器 1 并确认在线更改。 PLC 1 和 PLC 2 连续启动并切换到活动\/待机模式。 state.eRedundancyState 变量获取当前状态，以便您可以对其进行监控。 提示：当前状态也显示在 冗余状态 标签。 " }, 
{ "title" : "测试应用程序是否相等 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-23a82ec73ef863a8c0a864631c774924", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 测试应用程序是否相等 ", 
"snippet" : "检查是否在两个 PLC 上执行相同的应用程序。 要求：冗余系统处于活动\/待机模式，应用程序正在运行。 连接至 可编程逻辑控制器 2 . 为此，设置与设备网关的连接。或者，更方便地使用 交换 PLC 路径 中的按钮 冗余配置 。 在线 → 登录 如果没有显示下载消息，则两个应用程序相同。...", 
"body" : "检查是否在两个 PLC 上执行相同的应用程序。 要求：冗余系统处于活动\/待机模式，应用程序正在运行。 连接至 可编程逻辑控制器 2 . 为此，设置与设备网关的连接。或者，更方便地使用 交换 PLC 路径 中的按钮 冗余配置 。 在线 → 登录 如果没有显示下载消息，则两个应用程序相同。 " }, 
{ "title" : "模拟控制器故障 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-6d1046fa49ea1a4cc0a864633fbb5a4b", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 模拟控制器故障 ", 
"snippet" : "停止 可编程逻辑控制器 1 在运行时。 系统图形表示 未知 状态 （ ） 为了 可编程逻辑控制器 1 . 可编程逻辑控制器 2 立即切换到 独立 状态 （ ）。 重新启动 可编程逻辑控制器 1 设备。 PLC 1 切换到 待机 （ ）。 PLC 2 切换到 活跃 （ ）。...", 
"body" : "停止 可编程逻辑控制器 1 在运行时。 系统图形表示 未知 状态 （ ） 为了 可编程逻辑控制器 1 . 可编程逻辑控制器 2 立即切换到 独立 状态 （ ）。 重新启动 可编程逻辑控制器 1 设备。 PLC 1 切换到 待机 （ ）。 PLC 2 切换到 活跃 （ ）。 " }, 
{ "title" : "重新连接控制器 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-5df6373f49ea1a4cc0a864634d6a8c66", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 重新连接控制器 ", 
"snippet" : "没有自动 重新连接 （链路的断开和重新连接）包含在冗余组件的功能范围内。这是因为具体条件是相关的，具体取决于应用程序和设备。但是，您可以使用以下实现对重新连接的触发进行编程 例子 PROGRAM PLC_PRG VAR sReduState: RedundancyState; sSyncInfo: SYNC_INFO; sPlcIdent: PLC_IDENT; xConnectionState: BOOL; xResult: BOOL; END_VAR (* Collect information *) GetRedundancyState(ADR(sReduState)); xConnec...", 
"body" : "没有自动 重新连接 （链路的断开和重新连接）包含在冗余组件的功能范围内。这是因为具体条件是相关的，具体取决于应用程序和设备。但是，您可以使用以下实现对重新连接的触发进行编程 例子 PROGRAM PLC_PRG\nVAR\n sReduState: RedundancyState;\n sSyncInfo: SYNC_INFO;\n sPlcIdent: PLC_IDENT;\n xConnectionState: BOOL;\n xResult: BOOL;\nEND_VAR\n\n(* Collect information *)\nGetRedundancyState(ADR(sReduState));\nxConnectionState := GetConnectionState();\nsPlcIdent := GetPlcIdent();\n\n(* If in standalone mode, and connection is possible, re-synchronize from PLC2 *)\nIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_STANDALONE AND xConnectionState AND xResult = FALSE AND sPlcIdent = RDCY.PLC_IDENT.PLC_ID_2 THEN\n xResult := RDCY.Synchronize();\nEND_IF " }, 
{ "title" : "配置防火墙设置 ", 
"url" : "_rtsl_redundancy_use_redundant_system.html#UUID-03392c8e-b3bc-2cd5-8e91-f316711f9725_id_bf7e6657d4ff2f5c0a8640e016c0eaa-id-b3b02a00ebe5b55fc0a864634c22e30b", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 使用冗余控制系统 \/ 配置防火墙设置 ", 
"snippet" : "TCP 和 UDP 都用于冗余同步。为冗余链路设置了一个 IP 端口。这用于UDP。端口+1 用于 TCP。 例子 端口 1205 设置为默认值。 要解锁的端口 UDP: Port 1205 TCP: Port 1206...", 
"body" : "TCP 和 UDP 都用于冗余同步。为冗余链路设置了一个 IP 端口。这用于UDP。端口+1 用于 TCP。 例子 端口 1205 设置为默认值。 要解锁的端口 UDP: Port 1205\nTCP: Port 1206 " }, 
{ "title" : "同步冗余数据 ", 
"url" : "_rtsl_redundancy_synchronize_data.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 ", 
"snippet" : "基本上，您可以使用冗余区域类型来影响冗余数据是否同步以及何时同步以及数据从何处复制到何处。 当。。。的时候 冗余配置 对象存在于应用程序中，则 AREA_INPUT 冗余区域类型默认分配给所有变量（在所有全局变量列表和用户创建的所有程序中）。如果稍后将对象添加到应用程序，也会发生这种情况。因此，默认情况下会注册所有变量。 这些对象的列表位于 冗余配置 编辑于 注册地区 标签。 有关更多信息，请参阅： 一般的...", 
"body" : "基本上，您可以使用冗余区域类型来影响冗余数据是否同步以及何时同步以及数据从何处复制到何处。 当。。。的时候 冗余配置 对象存在于应用程序中，则 AREA_INPUT 冗余区域类型默认分配给所有变量（在所有全局变量列表和用户创建的所有程序中）。如果稍后将对象添加到应用程序，也会发生这种情况。因此，默认情况下会注册所有变量。 这些对象的列表位于 冗余配置 编辑于 注册地区 标签。 有关更多信息，请参阅： 一般的" }, 
{ "title" : "启动冗余系统时的同步 ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_id_fe9b781ef61cb849c0a86463419d722f-id-da349db2f6767bfcc0a8646327d3b119", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 启动冗余系统时的同步 ", 
"snippet" : "当第二个 PLC 启动时，冗余数据（和 AREA_INPUT 首先将冗余区域类型）从主动 PLC 复制到第二个 PLC，一次性复制。然后 PLC 切换到待机状态。 但是，您可以取消选择默认值 AREA_INPUT 冗余区域类型从同步中排除变量。 从同步中排除对象 在里面 冗余配置 编辑，在 注册区域 选项卡，单击 变量 标签。 对象列表（类型 程序 要么 全局变量列表 ) 显示在下方 目的 .选择激活的对象进行同步，因此获得 AREA_INPUT 冗余区域类型。 停用一个对象。 例子 这对于现场总线的本地诊断数据或本地冗余状态是可取的。...", 
"body" : "当第二个 PLC 启动时，冗余数据（和 AREA_INPUT 首先将冗余区域类型）从主动 PLC 复制到第二个 PLC，一次性复制。然后 PLC 切换到待机状态。 但是，您可以取消选择默认值 AREA_INPUT 冗余区域类型从同步中排除变量。 从同步中排除对象 在里面 冗余配置 编辑，在 注册区域 选项卡，单击 变量 标签。 对象列表（类型 程序 要么 全局变量列表 ) 显示在下方 目的 .选择激活的对象进行同步，因此获得 AREA_INPUT 冗余区域类型。 停用一个对象。 例子 这对于现场总线的本地诊断数据或本地冗余状态是可取的。 " }, 
{ "title" : "在每个任务周期中同步 ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_id_fe9b781ef61cb849c0a86463419d722f-id-5e163f11f6767bfcc0a8646354964d73", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 在每个任务周期中同步 ", 
"snippet" : "当运行系统的配置文件 (*.cfg) 包含以下条目时，每次启动任务循环时都会触发同步。 [CmpRedundancy] DataSyncAlways=1 的变量 PROGRAM 冗余区域类型为的对象和全局变量列表 AREA_INPUT 被影响到的。 例子 PROGRAM PLC_PRG VAR b: INT; END_VAR IF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_ACTIVE THEN b := b + 1; END_IF 这个 b 变量仅在主动 PLC 中递增。由于冗余系统中的数据与每个任务周期同步，因此冗余变量会连续传输到...", 
"body" : "当运行系统的配置文件 (*.cfg) 包含以下条目时，每次启动任务循环时都会触发同步。 [CmpRedundancy]\nDataSyncAlways=1 的变量 PROGRAM 冗余区域类型为的对象和全局变量列表 AREA_INPUT 被影响到的。 例子 PROGRAM PLC_PRG\nVAR\n b: INT;\nEND_VAR\n\nIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_ACTIVE THEN\n b := b + 1;\nEND_IF 这个 b 变量仅在主动 PLC 中递增。由于冗余系统中的数据与每个任务周期同步，因此冗余变量会连续传输到第二个 PLC。 " }, 
{ "title" : "按需同步 ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_id_fe9b781ef61cb849c0a86463419d722f-id-d586c395f6767bfcc0a86463100e4b50", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 按需同步 ", 
"snippet" : "如果運行系統的組態檔案 (<rts name.cfg) 不包含 DataSyncAlways=1 項目，則最好在 IEC 程式碼中以程式方式觸發同步。 为此，请调用 RedundancySynchronizeData() 在您的 IEC 代码中起作用。然后变量与 AREA_INPUT 冗余区域类型是同步的。因此，检查上的设置 注册区域 选项卡上 变量 标签。复制操作在任务循环开始时执行。 例子 在活动\/待机模式下， b 主动 PLC 中，变量递增。什么时候 bUpdateData 设置后，一次触发数据同步，并将值传送到第二个 PLC。 IF bUpdateData THEN bUpdateDa...", 
"body" : "如果運行系統的組態檔案 (<rts name.cfg) 不包含 DataSyncAlways=1 項目，則最好在 IEC 程式碼中以程式方式觸發同步。 为此，请调用 RedundancySynchronizeData() 在您的 IEC 代码中起作用。然后变量与 AREA_INPUT 冗余区域类型是同步的。因此，检查上的设置 注册区域 选项卡上 变量 标签。复制操作在任务循环开始时执行。 例子 在活动\/待机模式下， b 主动 PLC 中，变量递增。什么时候 bUpdateData 设置后，一次触发数据同步，并将值传送到第二个 PLC。 IF bUpdateData THEN\n bUpdateData := FALSE;\n RedundancySynchronizeData();\nEND_IF " }, 
{ "title" : "在每个任务周期中从主动 PLC 同步到备用 PLC ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_id_fe9b781ef61cb849c0a86463419d722f-id-aa03b1ecf6767bfcc0a864630024b7ce", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 在每个任务周期中从主动 PLC 同步到备用 PLC ", 
"snippet" : "这个 AREA_SYNCHRO 每个任务周期的运行过程中，可以将类型的冗余数据从主动 PLC 传输到备用 PLC。为此，数据的大小是有限的。中不支持该类型的分配 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 函数。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。这就是为什么注册是在回调中完成的 cbDownloadDone 系统事件。 例子 FUNCTION cbDownloadDone : DWORD VAR_IN_OUT EventPrm: CmpApp.EVTPARAM_CmpApp; END_VAR (* Register GVL_Sync...", 
"body" : "这个 AREA_SYNCHRO 每个任务周期的运行过程中，可以将类型的冗余数据从主动 PLC 传输到备用 PLC。为此，数据的大小是有限的。中不支持该类型的分配 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 函数。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。这就是为什么注册是在回调中完成的 cbDownloadDone 系统事件。 例子 FUNCTION cbDownloadDone : DWORD\nVAR_IN_OUT\n EventPrm: CmpApp.EVTPARAM_CmpApp;\nEND_VAR\n\n(* Register GVL_Synchro to be synchronized in every task cycle *)\nbAreaRegisterDone := AreaRegister(ADR(iSyncFirst), ADR(iSyncLast) - ADR(iSyncFirst) + sizeof(iSyncLast), AREA_TYPE.AREA_SYNCHRO);\ntNowDownloadDone := TIME(); 的呼唤 cbDownloadDone 当执行 OnlineChangeDone 系统事件发生。系统事件被添加到任务配置中。 请注意， AreaRegister 函数隐藏在冗余库的某些版本中，但仍然可以调用。 " }, 
{ "title" : "在每个任务周期中从备用 PLC 同步到主动 PLC ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_id_fe9b781ef61cb849c0a86463419d722f-id-969e2638f6767bfcc0a8646376775e4b", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 在每个任务周期中从备用 PLC 同步到主动 PLC ", 
"snippet" : "type 的冗余数据 AREA_PASSIVE 可以在每个任务循环的操作期间从被动 PLC 转移到主动 PLC。为此，数据的大小是有限的。不支持类型赋值 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 功能。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。结果，注册是在回调中完成的 cbDownloadDone 系统事件（与 上一章的示例 ）。 例子 FUNCTION cbDownloadDone : DWORD VAR_IN_OUT EventPrm: CmpApp.EVTPARAM_CmpApp; END_VAR (* Register GVL_...", 
"body" : "type 的冗余数据 AREA_PASSIVE 可以在每个任务循环的操作期间从被动 PLC 转移到主动 PLC。为此，数据的大小是有限的。不支持类型赋值 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 功能。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。结果，注册是在回调中完成的 cbDownloadDone 系统事件（与 上一章的示例 ）。 例子 FUNCTION cbDownloadDone : DWORD\nVAR_IN_OUT\n EventPrm: CmpApp.EVTPARAM_CmpApp;\nEND_VAR\n\n(* Register GVL_Synchro to be synchronized in every task cycle *)\nbAreaRegisterDone := AreaRegister(ADR(iSyncFirst), ADR(iSyncLast) - ADR(iSyncFirst) + sizeof(iSyncLast), AREA_TYPE.AREA_PASSIVE);\ntNowDownloadDone := TIME(); 的召唤 cbDownloadDone 执行时 OnlineChangeDone 系统事件发生。系统事件添加到任务配置中。 " }, 
{ "title" : "同步定时器 ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_id_fe9b781ef61cb849c0a86463419d722f-id-f9c262f5f6767bfcc0a864637595681f", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 同步定时器 ", 
"snippet" : "IEC 时基的值在每个 PLC 周期中从主动 PLC 传输到被动 PLC。这影响 TIME , TON ， 和 TOF 。系统时间（例如： SysTimeGetMs ) 不会被传输，并且可作为每个 PLC 上的本地时间。...", 
"body" : "IEC 时基的值在每个 PLC 周期中从主动 PLC 传输到被动 PLC。这影响 TIME , TON ， 和 TOF 。系统时间（例如： SysTimeGetMs ) 不会被传输，并且可作为每个 PLC 上的本地时间。 " }, 
{ "title" : "设置注册区域同步的超时时间 ", 
"url" : "_rtsl_redundancy_synchronize_data.html#UUID-91bace0f-acdc-5194-22dc-807c1c9f7441_section-idm23484572185267", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 设置注册区域同步的超时时间 ", 
"snippet" : "为设置合适的值 同步超时 的注册区域的百分比 冗余设置 ，你可以先使用系统跟踪来确定这一点： 在设备树中，添加 追踪 设备对象下方的对象。 在 冗余设置 在 将军 选项卡，选择 在系统跟踪中记录所需的同步时间 选项。 加载 并开始对系统跟踪进行跟踪记录。 同步期间超时的默认值 SyncWaitTime 的价值是 StandbyWaitTime ，反过来又将其预设为 30 毫秒的值。 如果是套装 SyncWaitTime 太短，则日志中会显示以下消息：“由于同步等待时间，同步在% 之后终止” PRI_UI32 “ms”。 当设定时 同步等待时间 足够长，实际需要的 SyncTime 会记录在系统...", 
"body" : "为设置合适的值 同步超时 的注册区域的百分比 冗余设置 ，你可以先使用系统跟踪来确定这一点： 在设备树中，添加 追踪 设备对象下方的对象。 在 冗余设置 在 将军 选项卡，选择 在系统跟踪中记录所需的同步时间 选项。 加载 并开始对系统跟踪进行跟踪记录。 同步期间超时的默认值 SyncWaitTime 的价值是 StandbyWaitTime ，反过来又将其预设为 30 毫秒的值。 如果是套装 SyncWaitTime 太短，则日志中会显示以下消息：“由于同步等待时间，同步在% 之后终止” PRI_UI32 “ms”。 当设定时 同步等待时间 足够长，实际需要的 SyncTime 会记录在系统跟踪中。你可以尝试优化这个集合 SyncWaitTime 这样它就尽可能接近实际所需的 SyncTime。 " }, 
{ "title" : "同步应用实例 ", 
"url" : "_rtsl_redundancy_example_synchronize_data.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步应用实例 ", 
"snippet" : "关于冗余 PLC 的示例项目 在此示例应用程序中，应用程序控制冗余系统中的数据同步。该示例显示了如何通过库 POU 触发同步阶段以及如何评估冗余系统的状态数据。可视化显示这些状态并提供冗余命令。可视化是用户的界面。 冗余系统包括两个 REDU01 和 REDU01 CODESYS Control Win 控制器。可视化运行在 CODESYS TargetVisu ....", 
"body" : " 关于冗余 PLC 的示例项目 在此示例应用程序中，应用程序控制冗余系统中的数据同步。该示例显示了如何通过库 POU 触发同步阶段以及如何评估冗余系统的状态数据。可视化显示这些状态并提供冗余命令。可视化是用户的界面。 冗余系统包括两个 REDU01 和 REDU01 CODESYS Control Win 控制器。可视化运行在 CODESYS TargetVisu . " }, 
{ "title" : "配置 ", 
"url" : "_rtsl_redundancy_example_synchronize_data.html#UUID-57e04a5b-5d4d-b3f5-3fc4-955224b93717_id_b1dab1628af81611c0a86463509bfa9d-id-91cfe05b8b55a467c0a8646301b9924f", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步应用实例 \/ 配置 ", 
"snippet" : "设备树中的对象 设置 顶层 Device REDU01 任务配置 冗余配置 可编程逻辑控制器 2 REDU02 一般的 冗余链路 可视化 在 注册区域...", 
"body" : "设备树中的对象 设置 顶层 Device REDU01 任务配置 冗余配置 可编程逻辑控制器 2 REDU02 一般的 冗余链路 可视化 在 注册区域 " }, 
{ "title" : "全球数据 ", 
"url" : "_rtsl_redundancy_example_synchronize_data.html#UUID-57e04a5b-5d4d-b3f5-3fc4-955224b93717_id_b1dab1628af81611c0a86463509bfa9d-id-78db838e1e8d4533c0a8640e0162bd7f", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步应用实例 \/ 全球数据 ", 
"snippet" : "GVL (* Variables synchronized at Redundancy synchronization. Synchronization happens - on bootup of the second PLC - on call to RedundancySynchronizeData - in every task cycle if setting is active in cfg file of both PLCs: [CmpRedundancy] DataSyncAlways=1 *) VAR_GLOBAL globalvar1: INT; arr1 : ARRAY ...", 
"body" : "GVL (* Variables synchronized at Redundancy synchronization. Synchronization happens\n- on bootup of the second PLC\n- on call to RedundancySynchronizeData\n- in every task cycle if setting is active in cfg file of both PLCs:\n[CmpRedundancy]\nDataSyncAlways=1\n*)\n\nVAR_GLOBAL\n globalvar1: INT;\n arr1 : ARRAY [0..10000] OF DWORD;\n arr2 : ARRAY [0..10000] OF DWORD;\n arr3 : ARRAY [0..10000] OF DWORD;\n arr4 : ARRAY [0..10000] OF DWORD;\n bSyncDataResult: BOOL;\nEND_VAR GVL_1 VAR_GLOBAL\n sReduState: RedundancyState;\n conni: REDUNDANCY_CONNECTION_INFO;\n sSyncInfo: SYNC_INFO;\n sPlcIdent: PLC_IDENT;\n bConnectionState: BOOL;\n\n tLast: TIME;\n nTimeWarp: INT;\n tDiff: TIME;\n nTimeRun: INT;\n tNow: TIME;\n sState: STRING;\n acopy: INT;\n MB2 AT %MX0.2: BOOL;\n tDiffMax: TIME;\n tNow2: TIME;\n tDiff2: TIME;\n nTimeWarp2: INT;\n tDiffMax2: TIME;\n tLast2: TIME;\n tNowDownloadDone: TIME;\n tNowCodeInitDone: TIME;\n nCycle: INT;\n atNow: ARRAY [0..9] OF TIME;\n nCycle2: INT;\n atNow2: ARRAY [0..9] OF TIME;\n bAreaRegisterDone: BOOL;\n pIB64: POINTER TO BYTE;\n bUpdateData: BOOL;\n bSwitchToStandby: BOOL;\n bSwitchToActive: BOOL;\n bSwitchToSimulation: BOOL;\n bSynchronize: BOOL;\n bSwitchToStandaloneResult: BOOL;\nEND_VAR GVL_Synchro (* Global variables, registered to be synchronized in every task cycle. *)\nVAR_GLOBAL\n iSyncFirst: INT;\n iSyncCount: INT;\n iSyncLast: INT;\nEND_VAR " }, 
{ "title" : "用于控制同步的 POU ", 
"url" : "_rtsl_redundancy_example_synchronize_data.html#UUID-57e04a5b-5d4d-b3f5-3fc4-955224b93717_id_b1dab1628af81611c0a86463509bfa9d-id-299684778b55a467c0a86463491b974f", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步应用实例 \/ 用于控制同步的 POU ", 
"snippet" : "PROGRAM PLC_PRG VAR a: INT; bSyncCalled: BOOL; Timestamp1: systime.SYSTIME; firstcycle: BOOL := TRUE; Timestamp2: systime.SYSTIME; b: INT; sText: STRING; bCopy: BOOL; Blink: TON; bBlink: BOOL; bAutoSync: BOOL := TRUE; \/\/ Flag to enable autosync mechanism xResSync: BOOL; END_VARIF a = 0 THEN Blink(PT...", 
"body" : "PROGRAM PLC_PRG\nVAR\n a: INT;\n bSyncCalled: BOOL;\n Timestamp1: systime.SYSTIME;\n firstcycle: BOOL := TRUE;\n Timestamp2: systime.SYSTIME;\n b: INT;\n sText: STRING;\n bCopy: BOOL;\n Blink: TON;\n bBlink: BOOL;\n bAutoSync: BOOL := TRUE; \/\/ Flag to enable autosync mechanism\n xResSync: BOOL;\nEND_VARIF a = 0 THEN\n Blink(PT := T#1S, IN := TRUE);\nEND_IF\na := a + 6;\nglobalvar1 := globalvar1 + 1;\n\n(* Call functions of redundancy library *)\nGetRedundancyState(ADR(sReduState));\nbConnectionState := GetConnectionState();\nsPlcIdent := GetPlcIdent();\n\n(* Call functions of redundancy connection library *)\nGetConnectionInfo(ADR(conni));\n\nGetSyncInformation(ADR(sSyncInfo));\n\n\/\/ Flag to enable autosync mechanism\nIF bAutoSync THEN\n IF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_STANDALONE AND bConnectionState AND xResSync = FALSE AND sPlcIdent = RDCY.PLC_IDENT.PLC_ID_2 THEN\n \/\/ Call of Synchronize from redundant application. Note, actual synchronisation is executed from background loop with some delay\n xResSync := RDCY.Synchronize();\n END_IF\nEND_IF\n\n\/\/ Recover from error state\n(*IF sReduState.eRedundancyState = RDCY.STATE.RS_SYNCHRO_ERROR THEN\n bSwitchToStandaloneResult := SwitchToStandalone();\nEND_IF\n\nIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_ACTIVE THEN\n bSyncDataResult := RedundancySynchronizeData();\nEND_IF\n*)\n\nIF bUpdateData THEN\n bUpdateData := FALSE;\n RedundancySynchronizeData();\nEND_IF\n\nIF bSwitchToStandby THEN\n bSwitchToStandby := FALSE;\n SwitchToStandby();\nEND_IF\n\nIF bSwitchToActive THEN\n bSwitchToActive := FALSE;\n SwitchToActive();\nEND_IF\n\nIF bSwitchToSimulation THEN\n bSwitchToSimulation := FALSE;\n SwitchToSimulation();\nEND_IF\n\nIF bSynchronize THEN\n bSynchronize := FALSE;\n Synchronize();\nEND_IF\n\nBlink();\nIF Blink.Q THEN\n Blink.IN := FALSE;\n Blink();\n Blink.IN := TRUE;\n bBlink := NOT bBlink;\nEND_IF\n%IB64;\n\nIF bCopy THEN\n bCopy := FALSE;\n acopy := a;\nEND_IF\n\narr2 := arr1;\n\nIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_ACTIVE THEN\n sState := 'Active';\n b := b + 1;\n pIB64 := ADR(%IB64);\n pIB64^ := pIB64^ + 1;\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_STANDBY THEN\n sState := 'Passive';\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_STANDALONE THEN\n sState := 'Standalone';\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_SIMULATION THEN\n sState := 'Simulation';\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_SYNCHRO THEN\n sState := 'Synchro';\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_SYNCHRO_ERROR THEN\n sState := 'SYNCHRO_ERROR';\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_NO_LICENSE THEN\n sState := 'LICENCE EXPIRED';\nELSIF sReduState.eRedundancyState = RDCY.STATE.RS_START THEN\n sState := 'START';\nELSE\n sState := 'Other';\nEND_IF\n\nnCycle := nCycle + 1; PROGRAM POU\nVAR\nEND_VAR\n\ntNow2 := TIME();\ntDiff2 := tNow - tLast;\nIF tDiff2 > T#1D THEN\n nTimeWarp2 := nTimeWarp2 + 1;\n LogAdd(STD_LOGGER, 'IEC', 0, 0, 0, 'Time Warp');\nEND_IF\nIF tDiff2 > tDiffMax2 THEN\n tDiffMax2 := tDiff2;\nEND_IF\ntLast2 := TIME();\n\nIF nCycle2 < 10 THEN\n atNow2[nCycle2] := tNow2;\nEND_IF\n\nnCycle2 := nCycle2 + 1; FUNCTION cdCodeInit : DWORD\nVAR_IN_OUT\n EventPrm: CmpApp.EVTPARAM_CmpApp;\nEND_VAR\nVAR\nEND_VAR\ntNowCodeInitDone := TIME(); FUNCTION cbDownloadDone : DWORD\nVAR_IN_OUT\n EventPrm: CmpApp.EVTPARAM_CmpApp;\nEND_VAR\nVAR\nEND_VAR\n(* Register GVL_Synchro to be synchronized in every task cycle *)\nbAreaRegisterDone := AreaRegister(ADR(iSyncFirst), ADR(iSyncLast) - ADR(iSyncFirst) + sizeof(iSyncLast), AREA_TYPE.AREA_SYNCHRO);\ntNowDownloadDone := TIME(); " }, 
{ "title" : "可视化 ", 
"url" : "_rtsl_redundancy_example_synchronize_data.html#UUID-57e04a5b-5d4d-b3f5-3fc4-955224b93717_id_b1dab1628af81611c0a86463509bfa9d-id-6fbda1af8b6715a4c0a86463391427a4", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步应用实例 \/ 可视化 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "同步冗余数据 ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 ", 
"snippet" : "基本上，您可以使用冗余区域类型来影响冗余数据是否同步以及何时同步以及数据从何处复制到何处。 当。。。的时候 冗余配置 对象存在于应用程序中，则 AREA_INPUT 冗余区域类型默认分配给所有变量（在所有全局变量列表和用户创建的所有程序中）。如果稍后将对象添加到应用程序，也会发生这种情况。因此，默认情况下会注册所有变量。 这些对象的列表位于 冗余配置 编辑于 注册地区 标签。 有关更多信息，请参阅： 一般的...", 
"body" : "基本上，您可以使用冗余区域类型来影响冗余数据是否同步以及何时同步以及数据从何处复制到何处。 当。。。的时候 冗余配置 对象存在于应用程序中，则 AREA_INPUT 冗余区域类型默认分配给所有变量（在所有全局变量列表和用户创建的所有程序中）。如果稍后将对象添加到应用程序，也会发生这种情况。因此，默认情况下会注册所有变量。 这些对象的列表位于 冗余配置 编辑于 注册地区 标签。 有关更多信息，请参阅： 一般的" }, 
{ "title" : "启动冗余系统时的同步 ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_id_fe9b781ef61cb849c0a86463419d722f-id-da349db2f6767bfcc0a8646327d3b119", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 启动冗余系统时的同步 ", 
"snippet" : "当第二个 PLC 启动时，冗余数据（和 AREA_INPUT 首先将冗余区域类型）从主动 PLC 复制到第二个 PLC，一次性复制。然后 PLC 切换到待机状态。 但是，您可以取消选择默认值 AREA_INPUT 冗余区域类型从同步中排除变量。 从同步中排除对象 在里面 冗余配置 编辑，在 注册区域 选项卡，单击 变量 标签。 对象列表（类型 程序 要么 全局变量列表 ) 显示在下方 目的 .选择激活的对象进行同步，因此获得 AREA_INPUT 冗余区域类型。 停用一个对象。 例子 这对于现场总线的本地诊断数据或本地冗余状态是可取的。...", 
"body" : "当第二个 PLC 启动时，冗余数据（和 AREA_INPUT 首先将冗余区域类型）从主动 PLC 复制到第二个 PLC，一次性复制。然后 PLC 切换到待机状态。 但是，您可以取消选择默认值 AREA_INPUT 冗余区域类型从同步中排除变量。 从同步中排除对象 在里面 冗余配置 编辑，在 注册区域 选项卡，单击 变量 标签。 对象列表（类型 程序 要么 全局变量列表 ) 显示在下方 目的 .选择激活的对象进行同步，因此获得 AREA_INPUT 冗余区域类型。 停用一个对象。 例子 这对于现场总线的本地诊断数据或本地冗余状态是可取的。 " }, 
{ "title" : "在每个任务周期中同步 ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_id_fe9b781ef61cb849c0a86463419d722f-id-5e163f11f6767bfcc0a8646354964d73", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 在每个任务周期中同步 ", 
"snippet" : "当运行系统的配置文件 (*.cfg) 包含以下条目时，每次启动任务循环时都会触发同步。 [CmpRedundancy] DataSyncAlways=1 的变量 PROGRAM 冗余区域类型为的对象和全局变量列表 AREA_INPUT 被影响到的。 例子 PROGRAM PLC_PRG VAR b: INT; END_VAR IF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_ACTIVE THEN b := b + 1; END_IF 这个 b 变量仅在主动 PLC 中递增。由于冗余系统中的数据与每个任务周期同步，因此冗余变量会连续传输到...", 
"body" : "当运行系统的配置文件 (*.cfg) 包含以下条目时，每次启动任务循环时都会触发同步。 [CmpRedundancy]\nDataSyncAlways=1 的变量 PROGRAM 冗余区域类型为的对象和全局变量列表 AREA_INPUT 被影响到的。 例子 PROGRAM PLC_PRG\nVAR\n b: INT;\nEND_VAR\n\nIF sReduState.eRedundancyState = RDCY.STATE.RS_CYCLE_ACTIVE THEN\n b := b + 1;\nEND_IF 这个 b 变量仅在主动 PLC 中递增。由于冗余系统中的数据与每个任务周期同步，因此冗余变量会连续传输到第二个 PLC。 " }, 
{ "title" : "按需同步 ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_id_fe9b781ef61cb849c0a86463419d722f-id-d586c395f6767bfcc0a86463100e4b50", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 按需同步 ", 
"snippet" : "如果運行系統的組態檔案 (<rts name.cfg) 不包含 DataSyncAlways=1 項目，則最好在 IEC 程式碼中以程式方式觸發同步。 为此，请调用 RedundancySynchronizeData() 在您的 IEC 代码中起作用。然后变量与 AREA_INPUT 冗余区域类型是同步的。因此，检查上的设置 注册区域 选项卡上 变量 标签。复制操作在任务循环开始时执行。 例子 在活动\/待机模式下， b 主动 PLC 中，变量递增。什么时候 bUpdateData 设置后，一次触发数据同步，并将值传送到第二个 PLC。 IF bUpdateData THEN bUpdateDa...", 
"body" : "如果運行系統的組態檔案 (<rts name.cfg) 不包含 DataSyncAlways=1 項目，則最好在 IEC 程式碼中以程式方式觸發同步。 为此，请调用 RedundancySynchronizeData() 在您的 IEC 代码中起作用。然后变量与 AREA_INPUT 冗余区域类型是同步的。因此，检查上的设置 注册区域 选项卡上 变量 标签。复制操作在任务循环开始时执行。 例子 在活动\/待机模式下， b 主动 PLC 中，变量递增。什么时候 bUpdateData 设置后，一次触发数据同步，并将值传送到第二个 PLC。 IF bUpdateData THEN\n bUpdateData := FALSE;\n RedundancySynchronizeData();\nEND_IF " }, 
{ "title" : "在每个任务周期中从主动 PLC 同步到备用 PLC ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_id_fe9b781ef61cb849c0a86463419d722f-id-aa03b1ecf6767bfcc0a864630024b7ce", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 在每个任务周期中从主动 PLC 同步到备用 PLC ", 
"snippet" : "这个 AREA_SYNCHRO 每个任务周期的运行过程中，可以将类型的冗余数据从主动 PLC 传输到备用 PLC。为此，数据的大小是有限的。中不支持该类型的分配 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 函数。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。这就是为什么注册是在回调中完成的 cbDownloadDone 系统事件。 例子 FUNCTION cbDownloadDone : DWORD VAR_IN_OUT EventPrm: CmpApp.EVTPARAM_CmpApp; END_VAR (* Register GVL_Sync...", 
"body" : "这个 AREA_SYNCHRO 每个任务周期的运行过程中，可以将类型的冗余数据从主动 PLC 传输到备用 PLC。为此，数据的大小是有限的。中不支持该类型的分配 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 函数。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。这就是为什么注册是在回调中完成的 cbDownloadDone 系统事件。 例子 FUNCTION cbDownloadDone : DWORD\nVAR_IN_OUT\n EventPrm: CmpApp.EVTPARAM_CmpApp;\nEND_VAR\n\n(* Register GVL_Synchro to be synchronized in every task cycle *)\nbAreaRegisterDone := AreaRegister(ADR(iSyncFirst), ADR(iSyncLast) - ADR(iSyncFirst) + sizeof(iSyncLast), AREA_TYPE.AREA_SYNCHRO);\ntNowDownloadDone := TIME(); 的呼唤 cbDownloadDone 当执行 OnlineChangeDone 系统事件发生。系统事件被添加到任务配置中。 请注意， AreaRegister 函数隐藏在冗余库的某些版本中，但仍然可以调用。 " }, 
{ "title" : "在每个任务周期中从备用 PLC 同步到主动 PLC ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_id_fe9b781ef61cb849c0a86463419d722f-id-969e2638f6767bfcc0a8646376775e4b", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 在每个任务周期中从备用 PLC 同步到主动 PLC ", 
"snippet" : "type 的冗余数据 AREA_PASSIVE 可以在每个任务循环的操作期间从被动 PLC 转移到主动 PLC。为此，数据的大小是有限的。不支持类型赋值 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 功能。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。结果，注册是在回调中完成的 cbDownloadDone 系统事件（与 上一章的示例 ）。 例子 FUNCTION cbDownloadDone : DWORD VAR_IN_OUT EventPrm: CmpApp.EVTPARAM_CmpApp; END_VAR (* Register GVL_...", 
"body" : "type 的冗余数据 AREA_PASSIVE 可以在每个任务循环的操作期间从被动 PLC 转移到主动 PLC。为此，数据的大小是有限的。不支持类型赋值 CODESYS ，但必须以编程方式作为回调来完成 AreaRegister 功能。 该区域必须在申请开始之前注册。在第一个周期中注册区域为时已晚。结果，注册是在回调中完成的 cbDownloadDone 系统事件（与 上一章的示例 ）。 例子 FUNCTION cbDownloadDone : DWORD\nVAR_IN_OUT\n EventPrm: CmpApp.EVTPARAM_CmpApp;\nEND_VAR\n\n(* Register GVL_Synchro to be synchronized in every task cycle *)\nbAreaRegisterDone := AreaRegister(ADR(iSyncFirst), ADR(iSyncLast) - ADR(iSyncFirst) + sizeof(iSyncLast), AREA_TYPE.AREA_PASSIVE);\ntNowDownloadDone := TIME(); 的召唤 cbDownloadDone 执行时 OnlineChangeDone 系统事件发生。系统事件添加到任务配置中。 " }, 
{ "title" : "同步定时器 ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_id_fe9b781ef61cb849c0a86463419d722f-id-f9c262f5f6767bfcc0a864637595681f", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 同步定时器 ", 
"snippet" : "IEC 时基的值在每个 PLC 周期中从主动 PLC 传输到被动 PLC。这影响 TIME , TON ， 和 TOF 。系统时间（例如： SysTimeGetMs ) 不会被传输，并且可作为每个 PLC 上的本地时间。...", 
"body" : "IEC 时基的值在每个 PLC 周期中从主动 PLC 传输到被动 PLC。这影响 TIME , TON ， 和 TOF 。系统时间（例如： SysTimeGetMs ) 不会被传输，并且可作为每个 PLC 上的本地时间。 " }, 
{ "title" : "设置注册区域同步的超时时间 ", 
"url" : "_rtsl_redundancy_synchronize_data-1848261.html#UUID-d036a004-9999-00b5-5217-acfb8f01f7cd_section-idm23484572185267", 
"breadcrumbs" : "CODESYS Redundancy \/ 冗余 \/ 同步冗余数据 \/ 设置注册区域同步的超时时间 ", 
"snippet" : "为设置合适的值 同步超时 的注册区域的百分比 冗余设置 ，你可以先使用系统跟踪来确定这一点： 在设备树中，添加 追踪 设备对象下方的对象。 在 冗余设置 在 将军 选项卡，选择 在系统跟踪中记录所需的同步时间 选项。 加载 并开始对系统跟踪进行跟踪记录。 同步期间超时的默认值 SyncWaitTime 的价值是 StandbyWaitTime ，反过来又将其预设为 30 毫秒的值。 如果是套装 SyncWaitTime 太短，则日志中会显示以下消息：“由于同步等待时间，同步在% 之后终止” PRI_UI32 “ms”。 当设定时 同步等待时间 足够长，实际需要的 SyncTime 会记录在系统...", 
"body" : "为设置合适的值 同步超时 的注册区域的百分比 冗余设置 ，你可以先使用系统跟踪来确定这一点： 在设备树中，添加 追踪 设备对象下方的对象。 在 冗余设置 在 将军 选项卡，选择 在系统跟踪中记录所需的同步时间 选项。 加载 并开始对系统跟踪进行跟踪记录。 同步期间超时的默认值 SyncWaitTime 的价值是 StandbyWaitTime ，反过来又将其预设为 30 毫秒的值。 如果是套装 SyncWaitTime 太短，则日志中会显示以下消息：“由于同步等待时间，同步在% 之后终止” PRI_UI32 “ms”。 当设定时 同步等待时间 足够长，实际需要的 SyncTime 会记录在系统跟踪中。你可以尝试优化这个集合 SyncWaitTime 这样它就尽可能接近实际所需的 SyncTime。 " }, 
{ "title" : "参考：用户界面 ", 
"url" : "_rtsl_redundancy_reference_ui.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "对象：冗余配置 ", 
"url" : "_rtsl_obj_redundance_configuration.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 ", 
"snippet" : "冗余配置 该对象包含的配置 CmpRedundancy 和 CmpRedundancyConnectionIP 运行时系统组件。在冗余编辑器中为此配置设置。 是否实际提供以下选项卡取决于设备及其设备描述。 有关更多信息，请参阅： 入门冗余状态 标签 以图形方式显示冗余系统 支持设备选择和连接设置（路径选择） 可视化系统的当前状态并显示当前的操作模式 提供冗余命令，以便您可以手动更改设备的操作模式 有关更多信息，请参阅： 冗余状态应用 标签 列出冗余系统加载的应用程序 提供命令以便您可以管理应用程序 对应于 Application 设备编辑器的选项卡 有关更多信息，请参阅： 应用文件 标签 允许...", 
"body" : "冗余配置 该对象包含的配置 CmpRedundancy 和 CmpRedundancyConnectionIP 运行时系统组件。在冗余编辑器中为此配置设置。 是否实际提供以下选项卡取决于设备及其设备描述。 有关更多信息，请参阅： 入门冗余状态 标签 以图形方式显示冗余系统 支持设备选择和连接设置（路径选择） 可视化系统的当前状态并显示当前的操作模式 提供冗余命令，以便您可以手动更改设备的操作模式 有关更多信息，请参阅： 冗余状态应用 标签 列出冗余系统加载的应用程序 提供命令以便您可以管理应用程序 对应于 Application 设备编辑器的选项卡 有关更多信息，请参阅： 应用文件 标签 允许对本地系统和 PLC 的文件系统进行文件访问 对应于 Files 设备编辑器的选项卡 有关更多信息，请参阅： 文件日志 标签 列出已记录其记录器的 PLC 的冗余事件历史 对应于 Log 设备编辑器的选项卡 有关更多信息，请参阅： 日志PLC外壳 标签 提供 PLC shell 以在 PLC 2 上执行命令 对应于 PLC Shell 设备编辑器的选项卡 有关更多信息，请参阅： PLC外壳标签： 冗余设置 有关更多信息，请参阅： 冗余设置标签 冗余链路 配置之间的冗余链接 可编程控制器 1 和 可编程控制器 2 （通讯设置） 有关更多信息，请参阅： 冗余链路标签： 一般的 为冗余操作配置任务、看门狗和现场总线 有关更多信息，请参阅： 一般的标签： 可视化 配置之间的冗余链路 可编程逻辑控制器 1 和 可编程逻辑控制器 2 供可视化的可选使用。 有关更多信息，请参阅： 可视化标签： 注册区域 配置同步的数据区域 有关更多信息，请参阅： 注册区域变量 标签 管理在 POU 和 GVL 中声明的变量，并在两个 PLC 中同步保留 标签 地址 管理在两个 PLC 中同步保留的地址范围 " }, 
{ "title" : "标签：冗余状态 ", 
"url" : "_rtsl_redundancy_reference_tab_status.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：冗余状态 ", 
"snippet" : "冗余状态 冗余系统的拓扑结构以图形方式显示在 冗余配置 编辑器的选项卡。还会显示 PLC 的当前设置，例如网关和通信设置（名称、类型、版本、地址和制造商）。您可以定义 PLC 和冗余 PLC 之间的网络路径，并将角色分配给 PLC。此外，您可以修改设备设置并同步设备。 以下按钮和设置在运行时可用，具体取决于具体情况。 有关更多信息，请参阅： 使用冗余控制系统设置路径 PLC 1 按钮 打开设备编辑器并切换到 沟通 标签 您可以在此处应用 PLC 1 的通讯设置。 当您的设备处于活动状态时，您可以通过 扫描网络 命令。 设置路径 PLC 2 按钮 打开 选择设备 对话 在那里您可以扫描网络并定义...", 
"body" : "冗余状态 冗余系统的拓扑结构以图形方式显示在 冗余配置 编辑器的选项卡。还会显示 PLC 的当前设置，例如网关和通信设置（名称、类型、版本、地址和制造商）。您可以定义 PLC 和冗余 PLC 之间的网络路径，并将角色分配给 PLC。此外，您可以修改设备设置并同步设备。 以下按钮和设置在运行时可用，具体取决于具体情况。 有关更多信息，请参阅： 使用冗余控制系统设置路径 PLC 1 按钮 打开设备编辑器并切换到 沟通 标签 您可以在此处应用 PLC 1 的通讯设置。 当您的设备处于活动状态时，您可以通过 扫描网络 命令。 设置路径 PLC 2 按钮 打开 选择设备 对话 在那里您可以扫描网络并定义冗余设备。为此，设备必须处于运行状态。 交换 PLC 路径 按钮 要求：设备在运行，连接开发系统，下载应用。 交换两个 PLC 的通信设置并将活动通信切换到另一个 PLC 此命令仅更改设备和冗余配置中的通信设置。它不会更改上的任何设置 冗余设置 选项卡。 刷新状态显示（运行状态） PLC 1 \/ PLC 2 冗余状态 两者运行状态的输出（文本） 可编程逻辑控制器 1 和 可编程逻辑控制器 2 例子： 积极的 网关 网关的通讯设置 设备 设备的通讯设置 启用 要求：模拟模式 将 PLC 切换到 积极的 状态 大约 10 秒后，另一台 PLC 将同步。 变量值不同步。 切换 将 PLC 从 活跃 状态为 待机 州 同步 要求：模拟模式或错误状态 使备用 PLC 与当前处于活动状态的 PLC 同步 数据和地址在为冗余注册的区域中同步。 处于仿真模式或错误状态的 PLC 与其他 PLC 同步，应用其数据，然后切换到待机模式。 模拟 将 PLC 从状态切换 待机 到状态 模拟 " }, 
{ "title" : "标签：应用程序 ", 
"url" : "_rtsl_redundancy_reference_tab_application.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：应用程序 ", 
"snippet" : "应用 的选项卡 冗余配置 object 列出冗余系统加载的应用程序并提供命令，以便您可以管理应用程序。...", 
"body" : "应用 的选项卡 冗余配置 object 列出冗余系统加载的应用程序并提供命令，以便您可以管理应用程序。 " }, 
{ "title" : "", 
"url" : "_rtsl_redundancy_reference_tab_application.html#UUID-09f0d006-bfe5-ee0b-101c-a2da9e9ee155_UUID-1280528f-1441-29ae-a09d-d708d41e561a", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：应用程序 \/ ", 
"snippet" : "PLC上的应用 通过以下方式找到的应用程序列表 刷新列表 在控制器的最后一次扫描期间 删除 删除所有 删除列表中选择的应用程序或控制器上所有列出的应用程序 如果在 PLC 下方插入了安全控制器，则该命令可以 永久性 中断安全控制器与其他安全控制器（通过安全网络变量）、现场设备和开发系统的通信链接。安全现场设备或其他安全控制器可以作为反应进入安全状态。只有当安全控制器通过现场总线连接到主控制器时，与开发系统的连接才会受到影响。 有关详细信息，请参阅“从属安全控制器”一章。 细节 打开 细节 对话 它显示了为应用程序定义的信息 信息 对话框的选项卡 特性 . 内容 要求： 下载申请资料 选项被激活...", 
"body" : "PLC上的应用 通过以下方式找到的应用程序列表 刷新列表 在控制器的最后一次扫描期间 删除 删除所有 删除列表中选择的应用程序或控制器上所有列出的应用程序 如果在 PLC 下方插入了安全控制器，则该命令可以 永久性 中断安全控制器与其他安全控制器（通过安全网络变量）、现场设备和开发系统的通信链接。安全现场设备或其他安全控制器可以作为反应进入安全状态。只有当安全控制器通过现场总线连接到主控制器时，与开发系统的连接才会受到影响。 有关详细信息，请参阅“从属安全控制器”一章。 细节 打开 细节 对话 它显示了为应用程序定义的信息 信息 对话框的选项卡 特性 . 内容 要求： 下载申请资料 选项被激活在 特性 应用程序对象的 应用程序生成选项 标签。这会触发有关应用程序内容的信息被额外下载到 PLC。 这 内容 按钮打开一个对话框，其中包含有关最新生成的代码与控制器上存在的应用程序代码之间差异的附加信息。不同的 POU 显示在比较视图中。 刷新列表 扫描控制器以查找应用程序并相应地刷新列表。 您可以配置 从设备中删除应用程序 要么 从设备中删除应用程序 中的命令 工具 → 自定义 对话。这些命令对应于 删除 要么 删除所有 纽扣。 " }, 
{ "title" : "标签：文件 ", 
"url" : "_rtsl_redundancy_reference_tab_files.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：文件 ", 
"snippet" : "文件 选项卡中的 冗余配置 object 允许对本地系统和冗余 PLC 的文件系统进行文件访问。您可以使用它来交换文件。...", 
"body" : "文件 选项卡中的 冗余配置 object 允许对本地系统和冗余 PLC 的文件系统进行文件访问。您可以使用它来交换文件。 " }, 
{ "title" : "", 
"url" : "_rtsl_redundancy_reference_tab_files.html#UUID-46581af3-2151-4b6a-7238-30d969bb809e_UUID-aa1b8515-35d0-1cd1-0849-d17b1439fc52", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：文件 \/ ", 
"snippet" : "主机\/运行时 使用标准文件管理器的功能访问主机的文件系统 地点 主机端文件传输的当前目录 打开一个对话框以在设置的路径中创建一个新目录 删除选定的文件或目录 更新设置位置的文件和目录列表 将选定的文件和目录从主机和运行时系统复制到相应的其他文件系统 如果目标目录中尚无文件可用，则创建该文件。如果它已经可用并且没有写保护，那么它会被覆盖。然后显示相应的消息。 : 对应 将文件写入控制器 命令 : 对应 从控制器写入文件 命令 双击文件 使用其 Windows 默认程序打开所选文件 备选方案：选择文件 + 进入 钥匙 示例：TXT 文件在 Windows 记事本中打开 注意：只能在主机端使用 Wi...", 
"body" : "主机\/运行时 使用标准文件管理器的功能访问主机的文件系统 地点 主机端文件传输的当前目录 打开一个对话框以在设置的路径中创建一个新目录 删除选定的文件或目录 更新设置位置的文件和目录列表 将选定的文件和目录从主机和运行时系统复制到相应的其他文件系统 如果目标目录中尚无文件可用，则创建该文件。如果它已经可用并且没有写保护，那么它会被覆盖。然后显示相应的消息。 : 对应 将文件写入控制器 命令 : 对应 从控制器写入文件 命令 双击文件 使用其 Windows 默认程序打开所选文件 备选方案：选择文件 + 进入 钥匙 示例：TXT 文件在 Windows 记事本中打开 注意：只能在主机端使用 Windows 默认程序打开。 默认情况下， 将文件写入控制器 和 从控制器写入文件 命令不包含在任何菜单中。您可以通过 工具 → 自定义 中的对话框 在线的 命令类别。 " }, 
{ "title" : "标签：日志 ", 
"url" : "_rtsl_redundancy_reference_tab_log.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：日志 ", 
"snippet" : "日志 选项卡中的 冗余配置 对象列出来自记录器的历史冗余事件 可编程逻辑控制器 2 . 您还可以在设备编辑器的同名选项卡上找到这些消息 可编程逻辑控制器 1 ....", 
"body" : "日志 选项卡中的 冗余配置 对象列出来自记录器的历史冗余事件 可编程逻辑控制器 2 . 您还可以在设备编辑器的同名选项卡上找到这些消息 可编程逻辑控制器 1 . " }, 
{ "title" : "", 
"url" : "_rtsl_redundancy_reference_tab_log.html#UUID-de63d712-78c4-997d-937c-d0dddc111156_UUID-f8e0ab33-5cb2-7220-fd3c-9c0abaec2c6a", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：日志 \/ ", 
"snippet" : "菜单栏 刷新所有运行时系统组件的日志事件列表 成分 按列表框中选择的运行时系统组件过滤日志事件的显示 例子： CmpApp 显示这些组件中发生的所有事件，例如“ Application [ <name> ] loaded via [OnlineChange] ”。 <所有组件> ：显示所有组件的上报事件 使用更新的日志消息加载下一页 使用较旧的日志消息加载上一页 加载具有最新日志条目的页面并启用自动滚动 : 表示有新的日志消息尚未显示 这也显示在状态栏上 自动滚动：开 . 加载包含最旧日志消息的页面 过滤具有严重性的事件 警告 并通知有多少 蓝色轮廓按钮：显示警告。 过滤具有严重性的事件 错误...", 
"body" : "菜单栏 刷新所有运行时系统组件的日志事件列表 成分 按列表框中选择的运行时系统组件过滤日志事件的显示 例子： CmpApp 显示这些组件中发生的所有事件，例如“ Application [ <name> ] loaded via [OnlineChange] ”。 <所有组件> ：显示所有组件的上报事件 使用更新的日志消息加载下一页 使用较旧的日志消息加载上一页 加载具有最新日志条目的页面并启用自动滚动 : 表示有新的日志消息尚未显示 这也显示在状态栏上 自动滚动：开 . 加载包含最旧日志消息的页面 过滤具有严重性的事件 警告 并通知有多少 蓝色轮廓按钮：显示警告。 过滤具有严重性的事件 错误 并通知有多少 蓝色轮廓按钮：显示错误。 过滤具有严重性的事件 例外 并通知有多少 蓝色轮廓按钮：显示异常。 过滤具有严重性的事件 信息 并通知有多少 蓝色轮廓按钮：显示信息。 过滤具有严重性的事件 调试 并通知有多少 蓝色轮廓按钮：显示调试消息。 在消息中搜索 搜索文本的输入字段 当您在搜索字段中输入一个或多个字符时，记录器消息将以黄色突出显示命中。 跳到下一个命中 跳到上一个命中 记录器 启用记录器以显示其记录的事件 默认情况下， <default logger> 由系统定义设置。例如，这是记录器 PlcLog 为一个 CODESYS Control Win 运行时系统。 .Audit.log ：此记录器显示用户与控制器的所有交互。用户名也会被记录。这些操作包括下载、启动、停止或设置断点等。如果不允许用户执行某些操作，也会记录失败的尝试。 世界标准时间 ：转换下面显示的时间 时间戳 到开发系统的本地时间 转换基于操作系统所在的时区 CODESYS 在跑。 （默认设置） ：显示运行时系统的原始时间戳 如果您更改选项，则会自动转换显示的时间戳。 将列表内容导出到 xml 文件 您可以选择文件名和位置。 导入带有存储在文件系统中的日志消息的 XML 文件 将打开一个单独的窗口以显示日志消息。 带有日志文件的显示窗口 日志消息的表格显示 每页显示一万条日志消息。 严重性 ： 警告 ： 错误 ： 例外 ： 信息 : 调试信息 时间戳 开发系统或运行时系统的日期和时间） 例子： 1\/12\/2007 9:48 描述 活动说明 例子： PLC started 零件 发生报告事件的运行时组件 状态栏 自动滚屏 显示是否启用自动滚动 ( 在 ) 或禁用 ( 离开 ) 在 ：日志列表在发生更改时自动刷新。 离开 ：当有新的日志事件发生时，显示在旁边 离开 .此外， 按钮装饰有 在菜单栏上。 提示：点击 按钮启用 自动滚屏 . 错误检查 对于例外情况 *SOURCEPOSITION* 描述，受影响的功能在编辑器中通过双击或通过 在编辑器中显示源代码 上下文菜单中的命令。光标跳到导致错误的行。当您有以下情况时，您也可以执行此诊断 CODESYS 项目存档，包括下载信息文件和导出的日志文件。 当受影响的功能受到保护时，会出现以下消息：“ <函数名称> 的源代码不可用。 \" 如果一个 VendorException 被报告，则制造商特定的异常错误发生在 CODESYS 运行。有关详细信息，请联系 PLC 制造商。 " }, 
{ "title" : "记录器消息 ", 
"url" : "_rtsl_redundancy_reference_tab_log.html#UUID-de63d712-78c4-997d-937c-d0dddc111156_id_d1c3547f726c0a8640e012ea8c3-id-a5fcfb5d1a494f2cc0a864633836ea2c", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：日志 \/ 记录器消息 ", 
"snippet" : "No sync telegram RSRV_BootupReply (2) received after 5000 ms PLC 2 未运行或无法通过 UDP 访问。 UDP: Open receive socket 192.168.101.92 failed TCP: Open server socket failed 设备上不存在配置的 IP 地址。 提示：检查冗余链路的设置（ 冗余配置 对象，在 冗余设置 选项卡，在 连接链接 标签）。 Synchronization terminated after 84ms because of SyncWaitTime 首次同步时间超过设置的超时时...", 
"body" : "No sync telegram RSRV_BootupReply (2) received after 5000 ms PLC 2 未运行或无法通过 UDP 访问。 UDP: Open receive socket 192.168.101.92 failed TCP: Open server socket failed 设备上不存在配置的 IP 地址。 提示：检查冗余链路的设置（ 冗余配置 对象，在 冗余设置 选项卡，在 连接链接 标签）。 Synchronization terminated after 84ms because of SyncWaitTime 首次同步时间超过设置的超时时间。 提示：在 冗余配置 对象，在 冗余设置 选项卡，在 一般的 选项卡，增加值 同步超时 .然后将新值写入控制器，启动系统并检查其行为。逐步增加值（例如：10 ms），直到不再出现错误。 No sync telegram RSRV_EndCycleReply (8) received after 10 ms 如果 PLC 2 仍在运行，则 PLC 1 的响应时间比设置的超时时间长。 提示：在 冗余配置 对象，在 冗余设置 选项卡，在 一般的 选项卡，增加值 超时（毫秒） .然后将新值写入控制器，启动系统并检查其行为。逐步增加该值（例如：10 ms），直到不再发生错误。 Demo mode expired 演示模式的时间段已到期。在没有许可证的情况下，冗余功能将运行大约 30 分钟。 Task '%s' not found in application '%s' 找不到冗余配置中指定的任务。这是一个配置错误。结果：同步不起作用。 " }, 
{ "title" : "选项卡：PLC 外壳 ", 
"url" : "_rtsl_redundancy_reference_tab_plc_shell.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 选项卡：PLC 外壳 ", 
"snippet" : "PLC外壳 的选项卡 冗余配置 对话框提供了一个基于文本的 shell 来与 PLC 2 的运行时系统进行交互。 命令行界面的行为类似于顶级设备编辑器的 PLC shell。此选项卡的帮助列出了所有 shell 命令。...", 
"body" : "PLC外壳 的选项卡 冗余配置 对话框提供了一个基于文本的 shell 来与 PLC 2 的运行时系统进行交互。 命令行界面的行为类似于顶级设备编辑器的 PLC shell。此选项卡的帮助列出了所有 shell 命令。 " }, 
{ "title" : "", 
"url" : "_rtsl_redundancy_reference_tab_plc_shell.html#UUID-472650d2-ab6b-4a2b-2d9a-2eb47bcdaf6f_UUID-9403fb45-4885-1a82-e631-65a4038d76bf", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 选项卡：PLC 外壳 \/ ", 
"snippet" : "标准命令 带有可能参数的命令 描述 ? 可用的 PLC shell 命令列表以及可能的参数和简短描述 getcmdlist 可用 PLC shell 命令的名称列表 mem <memory address> [<size>] 提供已定义内存范围的十六进制转储 这 size 参数是可选的，描述了输出的字节数。默认值：16 例子： mem 16x0422139C 8 reflect 重复给定的命令（用于测试连接） applist 提供所有已加载应用程序的列表 列表中的顺序定义以开头的应用程序索引 0 . pid [<application name> | <application index> ]...", 
"body" : "标准命令 带有可能参数的命令 描述 ? 可用的 PLC shell 命令列表以及可能的参数和简短描述 getcmdlist 可用 PLC shell 命令的名称列表 mem <memory address> [<size>] 提供已定义内存范围的十六进制转储 这 size 参数是可选的，描述了输出的字节数。默认值：16 例子： mem 16x0422139C 8 reflect 重复给定的命令（用于测试连接） applist 提供所有已加载应用程序的列表 列表中的顺序定义以开头的应用程序索引 0 . pid [<application name> | <application index> ] * 提供一个或所有已加载应用程序的 GUID（应用程序索引） pinf [<application name> | <application index>] * 提供项目信息中以下字段的内容：标题、版本、作者和描述。 要求：选项 为属性访问自动创建 POU 在里面 项目信息 对话框被激活。 startprg [<application name> | <application index> ] * 启动给定的应用程序，如果没有给定应用程序，则启动所有加载的应用程序 stopprg [<application name> | <applikation index> ] * 如果没有给出应用程序，则停止给定的应用程序或所有加载的应用程序 resetprg [<applikation name> | <application index> ] * 如果没有给出应用程序，则重置给定的应用程序或所有加载的应用程序 resetprgcold [<application name> | <application index> ] * 执行给定应用程序的冷启动，如果没有给定应用程序，则执行所有加载的应用程序 reload [<application name> | <application index>] * 加载给定应用程序的启动应用程序，如果没有给出应用程序，则加载所有已加载应用程序的启动项目 getprgstat [<application name> | <applikationsindex>] * 提供给定应用程序的程序状态，如果没有给出应用程序，则提供所有已加载应用程序的程序状态 plcload 显示控制器的处理器负载（百分比） rtsinfo 提供有关运行时系统的信息，例如运行时系统的处理器和版本 channelinfo 提供有关通信渠道的信息 rtc-get 通过 DataTime 细绳 rtc-set 通过设置世界时 (UTC) DataTime 字符串（参见 ISO 8601） listpcicards [<vendor ID>] 提供所有 PCI 适配器的列表（或按 <vendor ID> ) gettaskgroups 提供所有任务组、它们的任务和 CPU 内核绑定的列表 cert-getapplist 提供所有注册和使用的证书（组件的 ID 和使用情况） cert-genselfsigned [<number for search result by \"cert-getapplist\"> <expdays=>] 生成自签名证书 证书的有效期可以通过以下方式指定 expdays= . 默认值：365 天 cert-gendhparams <length in bits> 为 Diffie-Hellman 密钥交换生成参数 此操作可能需要几分钟才能完成。 cert-getcertlist [<trust level>] 列出指定信任级别的所有证书 如果未给出信任级别，则列出所有证书。 可能的信任级别 untrusted : 不可信证书 trusted : 值得信赖的证书 own : 控制器证书 quarantine ：无法通过验证确定信任级别（可信、不可信）的证书 因此，传入的连接被拒绝。 cert-createcsr [<number for search result by \"cert-getapplist\">] 为所有应用程序生成 CSR 文件 cert-import <trust level> <file name.cer> 导入指定的证书 cert-export <trust level> [<number of search result by \"cert-getcertlist\">] 导出指定的证书 cert-remove <trust level> <number of search result by \"cert-getcertlist\" or \"all\"> 删除指定的证书 cpuload 显示 CPU 的处理器负载（对于多核，每个处理器核心） gettaskgroups 提供已定义任务组的列表 为每个任务组显示分配的任务。 getmulticoreinfo 显示是否支持多核以及可用处理器内核的数量 sessinfo-list 提供所有当前登录的客户\/用户的列表 sessinfo-getcnt 提供当前登录的客户端\/用户的数量 logsetfilter [<CmpName>...] <FilterValue> 使用十六进制值配置日志过滤器的设置。 loggetfilter [<CmpName>...] 获取指定组件的当前日志过滤器设置。 logdelfilter [<CmpName>...] 删除指定组件的日志过滤器设置。 * 应用程序名称：设备树中应用程序的名称 应用程序索引：来自控制器上所有应用程序列表的结果，您可以使用 应用列表 命令。指数 0 代表列表中的第一个应用程序， 1 第二个，依此类推。 " }, 
{ "title" : "标签：冗余设置 ", 
"url" : "_rtsl_redundancy_reference_tab_settings.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：冗余设置 ", 
"snippet" : "冗余设置...", 
"body" : "冗余设置 " }, 
{ "title" : "选项卡：冗余设置 ：冗余链路 ", 
"url" : "_rtsl_redundancy_reference_tab_settings_links.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：冗余设置 \/ 选项卡：冗余设置 ：冗余链路 ", 
"snippet" : "冗余链路 此选项卡在 冗余配置 对话框配置两个 PLC 之间的冗余链接。该链接允许设备之间进行通信，以便它们可以同步操作并可以触发状态切换。 只要有可能，请使用单独的端口，特别是仅用于此通信。 冗余链路\/第一冗余链路 IP 地址 PLC 1 例子： 192.168.101.176 IP 地址 PLC 2 例子： 192.168.101.87 港口 定义两个设备之间连接的 IP 端口 TCP 端口号是 UDP 端口号 + 1。 示例： 1205 ；然后是端口 1205 用于 UDP 和 1206 用于 TCP 使用两个冗余链接 ：两个设备之间的附加网络连接 在第一个网络连接失败的情况下，可以使用...", 
"body" : "冗余链路 此选项卡在 冗余配置 对话框配置两个 PLC 之间的冗余链接。该链接允许设备之间进行通信，以便它们可以同步操作并可以触发状态切换。 只要有可能，请使用单独的端口，特别是仅用于此通信。 冗余链路\/第一冗余链路 IP 地址 PLC 1 例子： 192.168.101.176 IP 地址 PLC 2 例子： 192.168.101.87 港口 定义两个设备之间连接的 IP 端口 TCP 端口号是 UDP 端口号 + 1。 示例： 1205 ；然后是端口 1205 用于 UDP 和 1206 用于 TCP 使用两个冗余链接 ：两个设备之间的附加网络连接 在第一个网络连接失败的情况下，可以使用第二个。 您可以使用获取有关当前连接的信息 GetConnectionInfo 来自的函数 CmpRedundancyConnection 图书馆。 当使用两个冗余连接时，性能会更差。 如果两个连接中的一个断开连接，则这对冗余状态没有影响。 第二冗余链路 IP 地址 PLC 1 例子： 192.168.101.178 IP 地址 PLC 2 例子： 192.168.101.21 港口 定义两个设备之间第二个连接的 IP 端口 TCP 端口号是 UDP 端口号+1。 例子： 1206 读 单击此按钮会将 PLC1 的当前冗余链接设置读入对话框。 写 单击此按钮会将可用的冗余链接设置传输到两个 PLC 设备。 大多数设置只有在运行时系统重新启动后才会生效。这 暂停 和 同步超时 设置立即应用。 " }, 
{ "title" : "选项卡：冗余设置：常规 ", 
"url" : "_rtsl_redundancy_reference_tab_settings_general.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：冗余设置 \/ 选项卡：冗余设置：常规 ", 
"snippet" : "一般的 该选项卡包括看门狗的配置、具有所需服务的任务以及用于冗余的现场总线。 应用 冗余任务名称 两台设备同步的任务名称 只有这一项任务是同步的。 例子： MainTask 当您单击 写 按钮。或者，您也可以手动编辑文件。 超时（毫秒） 等待活动 PLC 响应的时间跨度 之后，被动 PLC 切换到独立模式。在这种情况下，任务执行会延迟到这个时间跨度。 例子： 50 建议：将该值设置为大于最大任务抖动时间加上冗余消息的最大传输时间。 该设置也存储在 RTS 配置文件中（ StandbyWaitTime ）。 部署 CIFX-DP 适配器时，将超时设置为 100 毫秒，以便在重置时保持同步。 同步...", 
"body" : "一般的 该选项卡包括看门狗的配置、具有所需服务的任务以及用于冗余的现场总线。 应用 冗余任务名称 两台设备同步的任务名称 只有这一项任务是同步的。 例子： MainTask 当您单击 写 按钮。或者，您也可以手动编辑文件。 超时（毫秒） 等待活动 PLC 响应的时间跨度 之后，被动 PLC 切换到独立模式。在这种情况下，任务执行会延迟到这个时间跨度。 例子： 50 建议：将该值设置为大于最大任务抖动时间加上冗余消息的最大传输时间。 该设置也存储在 RTS 配置文件中（ StandbyWaitTime ）。 部署 CIFX-DP 适配器时，将超时设置为 100 毫秒，以便在重置时保持同步。 同步超时（毫秒） 同步期间等待的时间跨度 在这段时间之后，待机 PLC 切换到独立模式。 如果您在从 PLC 获得系统跟踪信息后首先确定所需的同步时间，则可以以最佳方式设置该值。参见 在系统跟踪中记录所需的同步时间 选项如下。 例子： 100 如果同步时间超过允许的超时时间 超时 (ms) ，并且 PLC 1 的抖动是可以接受的，那么你可以使用这个设置。然后，该值将延长直到必须接收响应的时间跨度。 当您遇到此类同步问题时，逐步增加此设置。 记录器消息 由于 SyncWaitTime，同步在 x 毫秒后终止 指这种情况。 冗余系统切换到同步阶段以启动冗余 PLC、下载、在线更改以及通过用户命令进行同步。在同步阶段，活动 PLC 的任务循环时间可能会更长。 运行时设置 设置 CmpRedundancy 运行时系统组件 当您单击 写 按钮，在开发系统中设置的值将被传输到运行系统。 自动同步 ：连接失败后恢复连接时同步第二个控制器上的数据 数据始终同步 ：在初始化时以及之后的每个任务周期中同步一次数据 调试消息 ：记录器文件中附加消息的输出 在系统跟踪中记录所需的同步时间 ：在运行时系统中生成系统跟踪，可以将其加载到 CODESYS 项目。您可以使用系统跟踪来确定当前同步所需的值，从而优化同步的值 同步超时 (ms) 。有关说明，请参阅： 同步冗余数据此选项可在对话框中启用，输入于 CODESYSControl.cfg 下面 [CmpRedundancy] 部分作为设置 EnableSyncTimeTrace 。默认值为 0。 现场总线设置 EtherCAT ：EtherCAT 用作现场总线。 源地址 (MAC) PLC1 : 对应 EtherCAT 主站地址 源地址 (MAC) PLC2 : 与上述地址不同，对应PLC 2上用于EtherCAT的适配器 适配器的 NIC 设置必须在两个 PLC 上进行设置。您需要验证这一点。您可以使用 扫描 按钮自动搜索相应的 PLC。 现场总线 ：Profibus 用作现场总线。 读 将 PLC 1 的冗余链路的当前设置读入对话框 写 在两个设备上传输冗余链路的可用设置 " }, 
{ "title" : "选项卡：冗余设置：可视化 ", 
"url" : "_rtsl_redundancy_reference_tab_visualization.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：冗余设置 \/ 选项卡：冗余设置：可视化 ", 
"snippet" : "可视化 该选项卡包含一个或多个连接的配置 CODESYS WebVisu 客户端连接到具有两个 PLC 的冗余控制系统。 如果在运行时活动控制器发生故障，则控制应用程序的执行由先前处于待机模式的控制器接管。切换过程顺利进行，因此连接的可视化客户端几乎不会注意到。 类似的配置也可能基于 CODESYS HMI 当这些冗余运行时。 启用 ：为冗余控制系统启用可视化客户端和同步控制器的网络服务器之间的冗余连接 任务配置由IEC任务扩展 VISU_REDUNDANCY_TASK .这 VisuRedundancy 库集成在库管理器中。 这 切换参考 输入字段可用于通信设置。 切换参考 使用冗余链路配置...", 
"body" : "可视化 该选项卡包含一个或多个连接的配置 CODESYS WebVisu 客户端连接到具有两个 PLC 的冗余控制系统。 如果在运行时活动控制器发生故障，则控制应用程序的执行由先前处于待机模式的控制器接管。切换过程顺利进行，因此连接的可视化客户端几乎不会注意到。 类似的配置也可能基于 CODESYS HMI 当这些冗余运行时。 启用 ：为冗余控制系统启用可视化客户端和同步控制器的网络服务器之间的冗余连接 任务配置由IEC任务扩展 VISU_REDUNDANCY_TASK .这 VisuRedundancy 库集成在库管理器中。 这 切换参考 输入字段可用于通信设置。 切换参考 使用冗余链路配置 ：已配置的通信设置 冗余链路 选项卡被使用。当 Web 客户端通过与冗余链路相同的网络接口访问时，这种配置是可能的。 ：以下（现已启用）输入字段的地址设置用于 Web 客户端的连接。 IP地址：PLC 1上客户端使用的端口 IP 地址和端口的输入字段 可编程逻辑控制器 1 客户 点击 浏览 选择可用的网络地址之一 可编程逻辑控制器 1 .应在此处选择 Web 可视化访问的网络连接。 IP 地址：PLC 2 上客户端使用的端口 IP 地址和端口的输入字段 可编程逻辑控制器 2 客户 点击 浏览 选择可用的网络地址之一 可编程逻辑控制器 2 .应在此处选择 Web 可视化访问的网络连接。 安全 安全通信 ：从可视化客户端到以太网的连接 可编程逻辑控制器 1 和 可编程逻辑控制器 2 使用 TLS 加密。 生成证书 打开 安全屏幕 编辑 您可以在那里创建和管理证书。 查看证书 打开 查看证书 编辑 在那里，您可以获得有关安装在相应 PLC 上的证书的信息。 超时 建议：只要冗余设备之间没有同步问题以实现可视化，就不应更改超时的默认值。如果出现问题，则通信线路可能太慢。然后尝试通过增加超时值来提高稳定性 可视化冗余基于网络连接，该网络连接用于在主动 PLC 和备用 PLC 之间交换数据。此类数据可以是有关创建新 Web 可视化客户端或在 Web 可视化中更改可视化项的通知。为了防止通信出现问题时通信被阻塞，可以配置以下超时 接收超时（毫秒） 在此之后取消数据接收的时间。超过此时间时，传输的数据（例如有关创建新 Webvisu 客户端的通知）可能会被 默认： 5000 传输超时（毫秒） 在此之后取消数据发送的时间。超过此时间时，传输的数据（例如有关创建新 Webvisu 客户端的通知）将被丢 默认： 10000 选项 无缝下载 可为 HMI 设备启用 ：同样在下载后，选定的可视化和框架组合仍保留在 Web 可视化客户端中。因此，该过程不会从开始可视化开始。 先进的 ：启用 高级设置 输入字段 只有在特殊要求的情况下，您才需要更改以下高级设置。 高级设置 命令重复 发生错误时命令的重复次数 默认值为 3。建议使用 >= 2 的值。 心跳时间（毫秒） 确定多久发送一次保持连接处于活动状态的“心跳”命令的时间 0 = 未使用该命令。 如果以太网连接上没有数据传输，则连接终止，第一个 next 命令返回错误。为了防止这种情况，发送“心跳”命令。该命令的资源使用率极低。 仅在错误率较高的情况下使用此功能。 连接超时：检测到断线（毫秒） 连接失败被认为是“换行”的时间 备用设备无法检测数据缺失是由于缺少命令还是连接问题造成的。因此，有必要重新激活连接并在可能的情况下重置连接 默认值为 3000。建议使用 >= 2000 的值。 客户端连接设置超时（毫秒） 活动连接的延迟 这是确定连接是否处于活动状态所花费的时间。 默认值为 2000。500–3000 范围内的值通常是可以的。 WebVisu 连接超时（毫秒） Web 可视化客户端超时，以确定切换到另一个 PLC 该值表示稳定性和直到检测到连接问题的时间之间的平衡。 连接到活动设备的客户端使用此时间来检测设备何时不再活动。如果超过此时间没有接收到数据，则执行到其他设备的切换。这段时间的长短决定了切换的速度：如果值太低，可能会在连接不良的情况下导致不必要的切换尝试。太高的值会延迟客户端对物理真实设备故障的检测。 默认值为 2000。 " }, 
{ "title" : "标签：注册区域 ", 
"url" : "_rtsl_redundancy_reference_tab_registered_areas.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：注册区域 ", 
"snippet" : "注册区域 的选项卡 冗余配置 配置冗余系统中同步的数据和地址范围。 在冗余系统上，使用文件句柄和操作系统句柄时要小心，因为它们会导致每个 PLC 上的数据不同。 不推荐将设备输入映射到现有项目变量的方法。如果您仍然使用它，请记住以这种方式映射的变量不会存储在输入或输出数据区域中。这意味着它们不包括在 PLC 的同步中。 有关更多信息，请参阅： 同步冗余数据...", 
"body" : "注册区域 的选项卡 冗余配置 配置冗余系统中同步的数据和地址范围。 在冗余系统上，使用文件句柄和操作系统句柄时要小心，因为它们会导致每个 PLC 上的数据不同。 不推荐将设备输入映射到现有项目变量的方法。如果您仍然使用它，请记住以这种方式映射的变量不会存储在输入或输出数据区域中。这意味着它们不包括在 PLC 的同步中。 有关更多信息，请参阅： 同步冗余数据" }, 
{ "title" : "标签：变量 ", 
"url" : "_rtsl_redundancy_reference_tab_registered_areas.html#UUID-cc0142e2-e412-360c-52bd-d523dc175730_id_d4fd4e1e354978aac0a8640e004c0a0e-id-2c63b12d2a0b2507c0a8646352106157", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：注册区域 \/ 标签：变量 ", 
"snippet" : "类型 POU 的变量 PROGRAM 或类型 全局变量列表 可以冗余地保留在系统中。您可以在此处选择 POU。 目的 所有类型对象的列表 PROGRAM 或类型 全局变量列表 申请的 ：对象将被同步。 这首先意味着对象的变量已经得到了冗余区域类型 AREA_INPUT 并已注册。在运行时，这些变量在系统中冗余保留并同步。 当。。。的时候 冗余配置 对象存在于应用程序之下，冗余区域类型 AREA_INPUT 在声明中默认分配给变量。如果您稍后将对象添加到应用程序，也会发生这种情况。因此，任何类型的所有变量都默认注册。您可以看到这一点，因为这里选择了这些对象。 启动 PLC 时，系统将首次同步：当...", 
"body" : "类型 POU 的变量 PROGRAM 或类型 全局变量列表 可以冗余地保留在系统中。您可以在此处选择 POU。 目的 所有类型对象的列表 PROGRAM 或类型 全局变量列表 申请的 ：对象将被同步。 这首先意味着对象的变量已经得到了冗余区域类型 AREA_INPUT 并已注册。在运行时，这些变量在系统中冗余保留并同步。 当。。。的时候 冗余配置 对象存在于应用程序之下，冗余区域类型 AREA_INPUT 在声明中默认分配给变量。如果您稍后将对象添加到应用程序，也会发生这种情况。因此，任何类型的所有变量都默认注册。您可以看到这一点，因为这里选择了这些对象。 启动 PLC 时，系统将首次同步：当第二个 PLC 启动时，冗余数据将从第一个处于活动状态的 PLC 复制到备用 PLC。 : 对象不会被同步。 这首先意味着 POU 的变量已经得到了冗余区域类型 AREA_NONE .这意味着在启动第二个 PLC 时这些变量不会同步。 为具有私有或本地引用的数据选择此选项。例如，对于现场总线的诊断数据、文件句柄或仅在本地 PC 上有效的操作系统句柄。 全选\/全部清除 ：选择所有对象 ：清除所有对象 先前的选择被覆盖。 " }, 
{ "title" : "地址 ", 
"url" : "_rtsl_redundancy_reference_tab_registered_areas.html#UUID-cc0142e2-e412-360c-52bd-d523dc175730_id_d4fd4e1e354978aac0a8640e004c0a0e-id-78758e5e2a0b2507c0a86463333041a5", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 对象：冗余配置 \/ 标签：注册区域 \/ 地址 ", 
"snippet" : "地址 选项卡：您可以在此处指定应由以下人员控制的直接地址区域 CODESYS Redundancy .这 添加 按钮打开一个对话框，用于定义一个开始和大小 注册地址范围 .随着 编辑 和 删除 按钮，您可以更改或删除现有条目。 开始 内存区域的起始地址 例子： %MD48 尺寸 示例：256 添加 打开 注册地址范围 对话 在这里您可以指定一个内存区域。 编辑 打开 注册地址范围 要编辑的选定地址范围的对话框 删除 删除选定的地址范围...", 
"body" : "地址 选项卡：您可以在此处指定应由以下人员控制的直接地址区域 CODESYS Redundancy .这 添加 按钮打开一个对话框，用于定义一个开始和大小 注册地址范围 .随着 编辑 和 删除 按钮，您可以更改或删除现有条目。 开始 内存区域的起始地址 例子： %MD48 尺寸 示例：256 添加 打开 注册地址范围 对话 在这里您可以指定一个内存区域。 编辑 打开 注册地址范围 要编辑的选定地址范围的对话框 删除 删除选定的地址范围 " }, 
{ "title" : "调用命令时冗余系统的行为 ", 
"url" : "_rtsl_redundancy_reference_behavior_on_menu_commands.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：用户界面 \/ 调用命令时冗余系统的行为 ", 
"snippet" : "在线的 菜单 菜单命令 描述 登录 命令，然后 使用下载登录 命令 下载应用程序 可编程逻辑控制器 1 开启 PLC 1 ，该应用程序已停止并被删除。然后下载新的应用程序。在这段时间内，待机 PLC 2 切换到冗余仿真模式。一段时间后， PLC 2 尝试触发同步。每 10 秒重复一次尝试。 同步成功后触发 可编程逻辑控制器 1 已启动。 下载应用程序就足够了 可编程逻辑控制器 1 . 登录 命令，然后 使用在线更改登录 命令 执行在线更改 可编程逻辑控制器 1 处于活动状态 PLC 1 ，该应用程序将停止然后被删除。然后下载新的应用程序。在这段时间内，待机 PLC 2 切换到冗余仿真模式。一段...", 
"body" : "在线的 菜单 菜单命令 描述 登录 命令，然后 使用下载登录 命令 下载应用程序 可编程逻辑控制器 1 开启 PLC 1 ，该应用程序已停止并被删除。然后下载新的应用程序。在这段时间内，待机 PLC 2 切换到冗余仿真模式。一段时间后， PLC 2 尝试触发同步。每 10 秒重复一次尝试。 同步成功后触发 可编程逻辑控制器 1 已启动。 下载应用程序就足够了 可编程逻辑控制器 1 . 登录 命令，然后 使用在线更改登录 命令 执行在线更改 可编程逻辑控制器 1 处于活动状态 PLC 1 ，该应用程序将停止然后被删除。然后下载新的应用程序。在这段时间内，待机 PLC 2 切换到冗余仿真模式。一段时间后， PLC 2 尝试触发同步。每 10 秒重复一次尝试。 同步也触发成功 可编程逻辑控制器 1 启动应用程序。同步成功后， 可编程逻辑控制器 2 切换到待机模式。 如果花费的时间超过 10 秒 PLC 1 开始，那么 PLC 2 切换到错误模式。同样在错误模式下， PLC 2 尝试触发同步。 执行在线更改就足够了 可编程逻辑控制器 1 . 命令： 重置暖 在两个 PLC 上同时执行热启动 冗余任务仍处于同步状态。冗余状态活动\/待机保持不变 命令： 重置冷 在两个 PLC 上同时执行冷启动 冗余任务仍处于同步状态。冗余状态活动\/待机保持不变 命令： 重置原点 在两个 PLC 上执行复位原点 冗余任务仍处于同步状态。冗余状态活动\/待机保持不变 命令： 重置原始设备 执行重置原点 可编程逻辑控制器 1 此时，最重要的设置已从运行时配置文件中删除。冗余状态设置为冗余模拟模式。 调试 菜单 开始 命令 启动应用程序 可编程逻辑控制器 1 结果，触发了同步。 同步成功后， 可编程逻辑控制器 2 切换到待机模式和 可编程逻辑控制器 1 活跃。 如果花费的时间超过 10 秒 PLC 1 开始，那么 PLC 2 切换到错误模式。同样在错误模式下， PLC 2 尝试触发同步。 停止 命令 单循环 命令 停止应用程序 可编程逻辑控制器 1 因此， 可编程逻辑控制器 2 切换到冗余仿真模式。一段时间后， 可编程逻辑控制器 2 尝试触发同步。该尝试每 10 秒重复一次。 同步也只有在成功触发后 可编程逻辑控制器 1 启动应用程序。同步成功后， 可编程逻辑控制器 2 切换到待机模式。 断点 不 冗余系统中的支持 命令执行于 可编程逻辑控制器 1 只要。 在两个 PLC 上无法进行调试和使用断点进行步进。 " }, 
{ "title" : "参考：编程 ", 
"url" : "_rtsl_redundancy_reference_programming.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：编程 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "数据类型 ", 
"url" : "_rtsl_redundancy_data_types.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：编程 \/ 数据类型 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "数据类型：冗余区域类型 ", 
"url" : "_rtsl_redundancy_area_types.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：编程 \/ 数据类型 \/ 数据类型：冗余区域类型 ", 
"snippet" : "冗余区类型 通过将冗余区域类型分配给应用程序的对象，您可以影响为同步确定哪些数据。冗余区域类型只能分配给类型为 POU 的变量 PROGRAM 或类型 全局变量列表 , 然后对对象的所有变量都有效。分配是在 IEC 代码中以编程方式完成的。相应的冗余区域类型（同步类型）确定冗余数据是否对齐以及何时对齐。 被激活的对象 冗余配置 上的编辑 注册区域 选项卡自动获取 AREA_INPUT 冗余区域类型。结果，这些对象被注册一次。之后，可以通过函数调用以编程方式更改其同步类型。 有关更多信息，请参阅： 注册区域冗余区类型 描述 AREA_INPUT 启动第二个 PLC 时，这种类型的数据会同步一次。...", 
"body" : "冗余区类型 通过将冗余区域类型分配给应用程序的对象，您可以影响为同步确定哪些数据。冗余区域类型只能分配给类型为 POU 的变量 PROGRAM 或类型 全局变量列表 , 然后对对象的所有变量都有效。分配是在 IEC 代码中以编程方式完成的。相应的冗余区域类型（同步类型）确定冗余数据是否对齐以及何时对齐。 被激活的对象 冗余配置 上的编辑 注册区域 选项卡自动获取 AREA_INPUT 冗余区域类型。结果，这些对象被注册一次。之后，可以通过函数调用以编程方式更改其同步类型。 有关更多信息，请参阅： 注册区域冗余区类型 描述 AREA_INPUT 启动第二个 PLC 时，这种类型的数据会同步一次。对齐这些数据后，第二个 PLC 进入待机模式，第一个 PLC 从独立模式切换到活动模式。 在里面 冗余配置 对象，在 注册区域 选项卡，您可以通过激活变量或地址来分配此冗余区域类型。在那里激活的数据注册为 AREA_INPUT （默认）并在启动时同步。 AREA_NONE 没有同步 由函数调用分配 在里面 冗余配置 对象，在 注册区域 选项卡，您可以通过禁用变量或地址来分配此冗余区域类型。 AREA_OUTPUT 不同步，但执行 CRC。 AREA_PASSIVE 在写入输出之前同步（数据大小有限） 由函数调用分配 AREA_SYNCHRO 在每个任务周期开始时同步（数据大小有限） RTS 的 CFG 文件中的配置 由函数调用分配 " }, 
{ "title" : "数据类型：冗余状态 ", 
"url" : "_rtsl_redundancy_state.html", 
"breadcrumbs" : "CODESYS Redundancy \/ 参考：编程 \/ 数据类型 \/ 数据类型：冗余状态 ", 
"snippet" : "冗余状态 这 Redundancy 图书馆提供 RedundancyState 结构与组件描述如下。 通过调用 GetRedundancyState(ADR(<RedundancyState name>)); ，读取并存储冗余系统的状态。因此，您可以通过编程方式访问冗余状态并可以显示它，例如在可视化中。 冗余状态也会自动显示在 冗余配置 编辑，在 冗余状态 标签。在相应 PLC 右下角的系统图形中，冗余状态通过圆形符号象征性地显示。此外，状态在下面的文本中输出 冗余状态 场地。通过这种方式，您可以监控冗余系统的状态。 下表比较了这两个选项。 圆形符号 在下输出文本 冗余状态 STRUCT Re...", 
"body" : "冗余状态 这 Redundancy 图书馆提供 RedundancyState 结构与组件描述如下。 通过调用 GetRedundancyState(ADR(<RedundancyState name>)); ，读取并存储冗余系统的状态。因此，您可以通过编程方式访问冗余状态并可以显示它，例如在可视化中。 冗余状态也会自动显示在 冗余配置 编辑，在 冗余状态 标签。在相应 PLC 右下角的系统图形中，冗余状态通过圆形符号象征性地显示。此外，状态在下面的文本中输出 冗余状态 场地。通过这种方式，您可以监控冗余系统的状态。 下表比较了这两个选项。 圆形符号 在下输出文本 冗余状态 STRUCT RedundancyState 描述 RS_START 初始状态 尝试（正确配置时）与其他 PLC 同步 如果未正确配置，则状态设置为 RS_SIMULATION_START . RS_SYNCHRO 启动应用程序下载、数据同步和任务启动 现场总线停用 积极的 RS_CYCLE_ACTIVE 在冗余同步模式下作为主动 PLC 工作 现场总线激活 被动的 RS_CYCLE_STANDBY 在冗余同步模式下作为备用 PLC 工作 现场总线停用 独立 RS_CYCLE_STANDALONE 以独立模式工作，不与其他 PLC 同步 现场总线激活 错误 RS_CYCLE_ERROR 现场总线错误，在作为活动 PLC 的冗余同步模式下发生 现场总线停用 模拟 RS_SIMULATION 如果没有配置 以独立模式工作，不与其他 PLC 同步 现场总线停用 RS_BOOTUP_ERROR 如果在状态 RS_CYCLE_ACTIVE 另一个 PLC 将变为活动状态，因为 PROFIBUS 显示活动 PLC (us) 存在问题。 现场总线停用 RS_SHUTDOWN_ACTIVE 以状态结束运行时系统 RS_CYCLE_STANDALONE 让现场总线在下载时保持激活状态。 RS_SHUTDOWN_STANDBY 以状态结束运行时系统 RS_CYCLE_STANDBY 下载时禁用现场总线。 RS_SYNCHRO_ERROR 状态期间发生错误 RS_SYNCHRO 现场总线停用 RS_SIMULATION_START 有设置 Simulation=1 开机后独立工作，不与其他PLC同步 现场总线停用 稍后可以使用库函数触发同步。 RS_NO_LICENCE 如果未安装许可证且演示时间已过 无操作 未知 没有任务 表示与PLC的连接不在线 " }
]
$(document).trigger('search.ready');
});