$(document).ready(function () {indexDict['ja'] = [{ "title" : "CODESYS Modbus ", 
"url" : "_mod_start_page.html", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus ", 
"snippet" : "デバイス エディターの次のタブの詳細については、一般的な説明を参照してください。 タブ: <デバイス名> I\/O マッピング タブ: <デバイス名> IEC オブジェクト タブ: <デバイス名> パラメータ タブ: <デバイス名> ステータス タブ: <デバイス名> 情報 特別な機能の場合にのみ、関連するデバイス エディターの追加の個別のヘルプ ページが利用できます。 「<デバイス名>パラメータ」タブが表示されない場合は、 一般的なデバイス構成ビューを表示する オプションの CODESYS オプションでは、 デバイス エディター カテゴリ。 Modbusネットワークは、Modbusクライアント...", 
"body" : "デバイス エディターの次のタブの詳細については、一般的な説明を参照してください。 タブ: <デバイス名> I\/O マッピング タブ: <デバイス名> IEC オブジェクト タブ: <デバイス名> パラメータ タブ: <デバイス名> ステータス タブ: <デバイス名> 情報 特別な機能の場合にのみ、関連するデバイス エディターの追加の個別のヘルプ ページが利用できます。 「<デバイス名>パラメータ」タブが表示されない場合は、 一般的なデバイス構成ビューを表示する オプションの CODESYS オプションでは、 デバイス エディター カテゴリ。 Modbusネットワークは、Modbusクライアントと1台以上のModbusサーバーで構成されます。クライアントの下には最大64台のサーバーを接続できます。Modbusデバイスは、シリアルポートまたはイーサネット経由で接続できます。 Modbusデバイスは、シリアルポート経由で接続され、 Modbus COMポート デバイス。 （１） CODESYS ランタイムは Modbus クライアントとして機能します。 （２） CODESYS ランタイムはModbusサーバーとして機能します。このModbusサーバーは、以下のテキストでは「Modbusデバイス」と呼ばれます。 Modbus シリアルの場合、動作タイプ「Modbus RTU」がサポートされます。 Modbusデバイスは、イーサネットネットワークでリンクされ、 イーサネットアダプタ デバイス。 （３） CODESYS ランタイムは Modbus クライアントとして機能します。 Modbus TCPサーバーは、シリアル Modbus サーバーのゲートウェイとしても機能します。 （4）： CODESYS ランタイムは Modbus サーバーとして機能します。 Modbus設定ページで通信パラメータを設定し、Modbusチャネルを作成できます。Modbusチャネルには、単一のModbusコマンド（データの読み取り\/書き込み）と、対応するI\/Oチャネルが含まれます。 " }, 
{ "title" : "サポートされている機能コード ", 
"url" : "_mod_start_page.html#UUID-813fc252-d8a4-c4f6-a12e-b9258895f3b0_section-idm4569237926579232594448346888", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus \/ サポートされている機能コード ", 
"snippet" : "特定の PLC 制限がない場合、クライアントは通常、次の機能コードをサポートします。 FC01 Read Coils FC02 Read Discrete Inputs FC03 Read Holding Registers FC04 Read Input Registers FC05 Write Single Coil FC15 Write Multiple Coils FC06 Write Single Register FC16 Write Multiple Registers FC23 Read\/Write Multiple Registers...", 
"body" : "特定の PLC 制限がない場合、クライアントは通常、次の機能コードをサポートします。 FC01 Read Coils FC02 Read Discrete Inputs FC03 Read Holding Registers FC04 Read Input Registers FC05 Write Single Coil FC15 Write Multiple Coils FC06 Write Single Register FC16 Write Multiple Registers FC23 Read\/Write Multiple Registers " }, 
{ "title" : "アプリケーションからModbusデバイスへのアクセス ", 
"url" : "_mod_start_page.html#UUID-813fc252-d8a4-c4f6-a12e-b9258895f3b0_section-idm4679053088411232594449280385", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus \/ アプリケーションからModbusデバイスへのアクセス ", 
"snippet" : "Modbusデバイスをデバイスツリーに挿入すると、対応するファンクションブロックのインスタンスが自動的に作成されます。インスタンスの変数名は、デバイスツリー内のデバイス名に対応します。このファンクションブロックを使用することで、アプリケーションからModbusデバイスの機能にアクセスできます。例えば、このファンクションブロックの出力を介して、最後に実行したModbusコマンドのステータス（成功かどうか）を問い合わせることができます。 デバイスインスタンスは <デバイス名> IEC オブジェクト 対応するデバイスエディタのタブ。このダイアログの説明も参照してください。 Modbusクライアント（...", 
"body" : "Modbusデバイスをデバイスツリーに挿入すると、対応するファンクションブロックのインスタンスが自動的に作成されます。インスタンスの変数名は、デバイスツリー内のデバイス名に対応します。このファンクションブロックを使用することで、アプリケーションからModbusデバイスの機能にアクセスできます。例えば、このファンクションブロックの出力を介して、最後に実行したModbusコマンドのステータス（成功かどうか）を問い合わせることができます。 デバイスインスタンスは <デバイス名> IEC オブジェクト 対応するデバイスエディタのタブ。このダイアログの説明も参照してください。 Modbusクライアント（RTU\/TCP）の場合 コンフィギュレータで定義されたModbusコマンド（および暗黙的に生成されたI\/Oマッピング）に加えて、プログラムされたModbusリクエストもブロックを使用して実行できます。 ModbusRequest 。 " }, 
{ "title" : "", 
"url" : "_mod_start_page.html#UUID-813fc252-d8a4-c4f6-a12e-b9258895f3b0_section-idm4638279676419234110046706628", 
"breadcrumbs" : "CODESYS Modbus \/ CODESYS Modbus \/ ", 
"snippet" : "フィールドバスサポートに関するより一般的な情報については、 CODESYS 、以下を参照してください。 フィールドバスサポート Modbusのサンプルプログラム...", 
"body" : "フィールドバスサポートに関するより一般的な情報については、 CODESYS 、以下を参照してください。 フィールドバスサポート Modbusのサンプルプログラム " }, 
{ "title" : "クライアント ", 
"url" : "_mod_f_master.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "構成 ", 
"url" : "_mod_f_master_configuration.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "タブ: Modbusシリアルポート–全般 ", 
"url" : "_mod_edt_com_port.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbusシリアルポート–全般 ", 
"snippet" : "Modbus シリアルポートのコンフィギュレータのタブには、シリアルポート経由の通信の基本設定が含まれています。 シリアルポート、構成 COM ポート シリアルポート番号 ボーレート シリアルポートのパラメータ パリティ データ ビット ストップ ビット...", 
"body" : "Modbus シリアルポートのコンフィギュレータのタブには、シリアルポート経由の通信の基本設定が含まれています。 シリアルポート、構成 COM ポート シリアルポート番号 ボーレート シリアルポートのパラメータ パリティ データ ビット ストップ ビット " }, 
{ "title" : "タブ: Modbusシリアルクライアント –全般 ", 
"url" : "_mod_edt_master_com.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbusシリアルクライアント –全般 ", 
"snippet" : "このタブには、Modbus 通信の基本設定が含まれています。 Modbus RTU\/ASCII 伝送方式 RTU : バイナリ形式での送信 アスキー : ASCII コードでの送信 (現在すべてのドライバーでサポートされているわけではありません) レスポンス タイムアウト (ms) クライアントがサーバーノードからの応答を待機する時間間隔です。この時間間隔内にノードが応答しない場合、暗黙的なサーバーFBに対してエラーが発行されます。この時間間隔に指定された値は、各ノードのデフォルト値にもなります。各ノードに対して、サーバー設定内で特定の値を設定することは可能です。 フレーム間の時間(ms) フ...", 
"body" : "このタブには、Modbus 通信の基本設定が含まれています。 Modbus RTU\/ASCII 伝送方式 RTU : バイナリ形式での送信 アスキー : ASCII コードでの送信 (現在すべてのドライバーでサポートされているわけではありません) レスポンス タイムアウト (ms) クライアントがサーバーノードからの応答を待機する時間間隔です。この時間間隔内にノードが応答しない場合、暗黙的なサーバーFBに対してエラーが発行されます。この時間間隔に指定された値は、各ノードのデフォルト値にもなります。各ノードに対して、サーバー設定内で特定の値を設定することは可能です。 フレーム間の時間(ms) フレーム間の時間は、クライアントが最後のレスポンス（およびタイムアウト）と次のリクエストの間に送信を一時停止する時間です。このパラメータを使用すると、通信が中断される可能性が低くなります。 通信の自動再開 : 通信エラーが発生した後、 CODESYS 自動的にエラーを確認し、Modbus コマンドの実行を継続しようとします。 : エラーはサーバー機能ブロックで明示的に確認する必要があります。 " }, 
{ "title" : "タブ: Modbus TCPクライアント –全般 ", 
"url" : "_mod_edt_master_tcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbus TCPクライアント –全般 ", 
"snippet" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 Modbus TCP 応答タイムアウト（ミリ秒） クライアントがサーバーノードからの応答を待機する時間間隔（ミリ秒単位）。この時間間隔内にノードが応答しない場合、暗黙的なサーバーFBに対してエラーが発行されます。この時間間隔に指定された値は、各ノードのデフォルト値にもなります。各ノードに対して、 Modbus TCPサーバー設定内で特定の値を設定することは可能です。 自動再接続 : クライアントは中断された接続を常に自動的に再確立しようとします。この際、サーバーのエラーは自動的に確認されます。TCPエラーの場合は、サー...", 
"body" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 Modbus TCP 応答タイムアウト（ミリ秒） クライアントがサーバーノードからの応答を待機する時間間隔（ミリ秒単位）。この時間間隔内にノードが応答しない場合、暗黙的なサーバーFBに対してエラーが発行されます。この時間間隔に指定された値は、各ノードのデフォルト値にもなります。各ノードに対して、 Modbus TCPサーバー設定内で特定の値を設定することは可能です。 自動再接続 : クライアントは中断された接続を常に自動的に再確立しようとします。この際、サーバーのエラーは自動的に確認されます。TCPエラーの場合は、サーバーのサブデバイスのエラーも自動的に確認されます。 " }, 
{ "title" : "タブ: Modbusシリアルサーバー –全般 ", 
"url" : "_mod_edt_slave_com.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbusシリアルサーバー –全般 ", 
"snippet" : "このタブには、シリアルポート経由の通信の基本設定が含まれています。 Modbus RTU\/ASCII サーバー アドレス [1..247] シリアルModbusデバイスのアドレス（1～247の値） レスポンス タイムアウト (ms) クライアントがサーバーノードからの応答を待機する時間間隔。この値は当該サーバーノード専用に設定され、各クライアントの一般的な応答タイムアウト設定を上書きします。...", 
"body" : "このタブには、シリアルポート経由の通信の基本設定が含まれています。 Modbus RTU\/ASCII サーバー アドレス [1..247] シリアルModbusデバイスのアドレス（1～247の値） レスポンス タイムアウト (ms) クライアントがサーバーノードからの応答を待機する時間間隔。この値は当該サーバーノード専用に設定され、各クライアントの一般的な応答タイムアウト設定を上書きします。 " }, 
{ "title" : "タブ: Modbus TCPサーバー –全般 ", 
"url" : "_mod_edt_slave_tcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbus TCPサーバー –全般 ", 
"snippet" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 Modbus TCP サーバー IP アドレス レスポンス タイムアウト (ms) クライアントがこのサーバーからの応答を待機する時間間隔。この値はこのサーバーノード専用に設定され、各クライアントの一般的な応答タイムアウト設定を上書きします。 ポート サーバーのポート番号（TCP\/IP）。Modbusのデフォルトはポート502です。 次のパラメータは、デバイスの説明で定義されている場合にのみ使用できます。 予備 IP を有効化 : 2番目の接続と追加の構成オプションのIPアドレスのロックを解除します 第 2 サーバー ...", 
"body" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 Modbus TCP サーバー IP アドレス レスポンス タイムアウト (ms) クライアントがこのサーバーからの応答を待機する時間間隔。この値はこのサーバーノード専用に設定され、各クライアントの一般的な応答タイムアウト設定を上書きします。 ポート サーバーのポート番号（TCP\/IP）。Modbusのデフォルトはポート502です。 次のパラメータは、デバイスの説明で定義されている場合にのみ使用できます。 予備 IP を有効化 : 2番目の接続と追加の構成オプションのIPアドレスのロックを解除します 第 2 サーバー IP アドレス 2番目の接続のIPアドレス お気に入りのライン なし : アクティブな接続が終了すると、ドライバーは可能であれば非アクティブな接続への切り替えを試みます。元の接続が復元された場合、元の接続への切り替えは行われません。 1行目 、 2行目 : 指定された接続が優先されます。つまり、接続が失われた後、一定の間隔でこの回線への切り替えが試行されます。この間隔はライブラリパラメータで設定できます。 両方の回線を接続しておく : 非アクティブ回線の接続も維持されます。接続の可用性は、読み取りコマンドの送信によって定期的に確認されます。これらの間隔は、ライブラリパラメータで設定できます。 : アクティブな接続のみが維持されるため、回線を変更するときは最初に接続を確立する必要があります。 現在アクティブなラインと CommunicationState 非アクティブラインの usiActiveLine そして ComStateBackup Modbus TCPサーバーの暗黙的に生成された FB インスタンスの出力。 通信設定は実行時に以下の方法で変更することができます。 メソッド: UpdateCommunicationSettingsメソッド。このメソッドは、この Modbus サーバーの暗黙的に生成された FB で使用できます。 いつ 予備 IP を有効化 オプションが選択されている場合、 メソッド: UpdateCommunicationSettingsこの方法は効果がありません。 " }, 
{ "title" : "タブ: Modbus サーバー チャネル ", 
"url" : "_mod_edt_slave_com_channel.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbus サーバー チャネル ", 
"snippet" : "このタブを使用して、サーバー チャネルを定義します。 各チャネルは単一の Modbus 要求を表します。 チャネルの追加 開く Modbus チャネル ダイアログが表示されます。ここで、現在のModbusサーバーに新しいチャンネルを作成できます。Modbusサーバーのデバイス記述ファイルでは、個々のModbusレジスタまたはチャンネル全体の記述を事前に定義できます。...", 
"body" : "このタブを使用して、サーバー チャネルを定義します。 各チャネルは単一の Modbus 要求を表します。 チャネルの追加 開く Modbus チャネル ダイアログが表示されます。ここで、現在のModbusサーバーに新しいチャンネルを作成できます。Modbusサーバーのデバイス記述ファイルでは、個々のModbusレジスタまたはチャンネル全体の記述を事前に定義できます。 " }, 
{ "title" : "ダイアログ: Modbus チャネル ", 
"url" : "_mod_edt_slave_com_channel.html#UUID-99c4b381-a91c-94f1-fef0-ddac4ca2760a_id_e8de9c86ef0c4970c0a8640e0169f254_id_f91c8836fa101007c0a8640e0143e473", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbus サーバー チャネル \/ ダイアログ: Modbus チャネル ", 
"snippet" : "チャネル 名前 チャンネル名を含む文字列 アクセス タイプ Read Coils（機能コード01） Read Discrete Inputs（機能コード 02） Read Holding Registers（機能コード03） Read Input Registers（機能コード04） Read Single Coil（機能コード05） Write Single Register（機能コード06） Write Multiple Coils（機能コード15） Write Multiple Registers（機能コード 16） Read\/Write Multiple Registers（機能コード...", 
"body" : "チャネル 名前 チャンネル名を含む文字列 アクセス タイプ Read Coils（機能コード01） Read Discrete Inputs（機能コード 02） Read Holding Registers（機能コード03） Read Input Registers（機能コード04） Read Single Coil（機能コード05） Write Single Register（機能コード06） Write Multiple Coils（機能コード15） Write Multiple Registers（機能コード 16） Read\/Write Multiple Registers（機能コード 23） トリガ 循環的 : リクエストは定期的に発生します。 ライジングエッジ : リクエストはブールトリガ変数の立ち上がりエッジに反応して発生します。トリガ変数は I\/O マッピング タブ。 応用 ModbusリクエストはPLCアプリケーションによってトリガーされます。これは、 機能ブロック: ModbusChannelは、それぞれのI\/Oドライバライブラリに含まれています。この機能ブロックは、このコマンドの実行に関する完全な制御と情報（開始時刻、処理時間、結果など）を提供します。 サイクルタイム（ミリ秒） トリガの場合 = 循環的 : リクエスト間隔 注: リクエスト間隔は、アプリケーションのサイクル時間と同じかその倍数である必要があります。 コメント チャンネルの説明 READ レジスタ オフセット 読み取りを開始する開始アドレス（値の範囲は0～65535） 長さ 読み取るレジスタの数（ワードアクセスの場合）または読み取る個別入力の数（ビットアクセスの場合） エラー処理 通信エラーが発生した場合にデータに何が起こるかを定義します 最後の値を保持 ゼロに設定 WRITE レジスタ オフセット 書き込むレジスタ番号（値の範囲は0～65535） 長さ 書き込むレジスタの数（=ワード数） パラメータの値の範囲は関数コードによって異なります。 コイルとディスクリート入力の読み取り \/ 重複レジスタメモリへのコイルの書き込み その CODESYS MODBUS I\/Oドライバは、コイルと個別入力の読み取り、および重複レジスタメモリ（ ビット領域をレジスタ領域から分離 （チェックボックスが選択されていない場合）。この場合、読み取られる最初の8ビット（%IB0）または書き込まれる最初の8ビットは、対応するレジスタの上位バイトに揃えられます。読み取られる2番目の8ビット（%IB1）は、対応するレジスタの下位バイト（LSBファースト）に揃えられます。 例 次の例では、最初の行は読み取り\/書き込みの組み合わせ操作（機能コード23）を定義しています。これは、オフセットを持つ保持レジスタから1ワードを読み取ります。 16#0001 オフセットでレジスタに2ワードを書き込む 16#0003 .トリガ変数が定義されたらすぐに操作が実行されます。 I\/O マッピング タブには立ち上がりエッジが表示されます。 " }, 
{ "title" : "タブ: Modbus サーバー初期化 ", 
"url" : "_mod_edt_slave_com_init.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbus サーバー初期化 ", 
"snippet" : "このタブを使用して初期化コマンドを定義します。 初期化コマンドは、バスを起動するとき、またはサーバーをアクティブ化するとき（サーバー インスタンスの「有効」フラグを設定するとき）に 1 回実行されます。 サーバー初期値を設定または編集する場合、それぞれのダイアログで次のパラメータを使用できます。 上に移動 下に移動 チャネルの順序によって初期化の順序も決まります。 新しい 開く 初期値 ダイアログ。初期化コマンドが定義されています。...", 
"body" : "このタブを使用して初期化コマンドを定義します。 初期化コマンドは、バスを起動するとき、またはサーバーをアクティブ化するとき（サーバー インスタンスの「有効」フラグを設定するとき）に 1 回実行されます。 サーバー初期値を設定または編集する場合、それぞれのダイアログで次のパラメータを使用できます。 上に移動 下に移動 チャネルの順序によって初期化の順序も決まります。 新しい 開く 初期値 ダイアログ。初期化コマンドが定義されています。 " }, 
{ "title" : "ダイアログ:初期値 ", 
"url" : "_mod_edt_slave_com_init.html#UUID-858dc378-b63e-7e25-35e5-9fca05de0cb5_id_fa026065ef0c7c92c0a8640e000566e4_id_24182416aaae11e393b286effee11a64", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 構成 \/ タブ: Modbus サーバー初期化 \/ ダイアログ:初期値 ", 
"snippet" : "アクセス タイプ Write Single Coil（機能コード05） Write Single Register（機能コード06） Write Multiple Coils（機能コード15） Write Multiple Registers（機能コード 16） レジスタ オフセット 書き込むレジスタ番号（値の範囲は0～65535） 長さ 書き込むレジスタの数（=ワード数） パラメータの値の範囲は関数コードによって異なります。 初期化 レジスタの初期値 コメント データの簡単な説明...", 
"body" : "アクセス タイプ Write Single Coil（機能コード05） Write Single Register（機能コード06） Write Multiple Coils（機能コード15） Write Multiple Registers（機能コード 16） レジスタ オフセット 書き込むレジスタ番号（値の範囲は0～65535） 長さ 書き込むレジスタの数（=ワード数） パラメータの値の範囲は関数コードによって異なります。 初期化 レジスタの初期値 コメント データの簡単な説明 " }, 
{ "title" : "機能 ", 
"url" : "_mod_client_functions.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 機能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "TCPクライアントの冗長性 ", 
"url" : "_mod_client_redundancy.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 機能 \/ TCPクライアントの冗長性 ", 
"snippet" : "システムの可用性を高めるために、冗長Modbus TCPクライアントと組み合わせた2台目のコントローラを使用することができます。 CODESYS Redundancy 。 CODESYS Redundancy 2つのコントローラ上のアプリケーションを同期させる「バックエンド」として機能します。ネイティブModbusシステム冗長性（SR）により、フィールドデバイスとのスムーズなデータ交換が保証されます。 Modbus TCPクライアントと CODESYS Redundancy は、 冗長マネージャー 機能ブロックから IoDrvModbusTCP 図書館。...", 
"body" : "システムの可用性を高めるために、冗長Modbus TCPクライアントと組み合わせた2台目のコントローラを使用することができます。 CODESYS Redundancy 。 CODESYS Redundancy 2つのコントローラ上のアプリケーションを同期させる「バックエンド」として機能します。ネイティブModbusシステム冗長性（SR）により、フィールドデバイスとのスムーズなデータ交換が保証されます。 Modbus TCPクライアントと CODESYS Redundancy は、 冗長マネージャー 機能ブロックから IoDrvModbusTCP 図書館。 " }, 
{ "title" : "使用法 ", 
"url" : "_mod_client_redundancy.html#UUID-0812546d-012d-898c-c88e-3b900f1eda1d_section-idm4520238175380833428668771124", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 機能 \/ TCPクライアントの冗長性 \/ 使用法 ", 
"snippet" : "使用するTCPクライアントごとに、 RedundancyManager グローバル変数リストなどの非同期データ領域に関数ブロックを配置します。さらに、 DataSyncAlways ランタイムシステムの構成ファイル内のエントリ（ *.cfg ）を使用して、各サイクルの開始時にデータを同期します。 [CmpRedundancy] DataSyncAlways=1...", 
"body" : "使用するTCPクライアントごとに、 RedundancyManager グローバル変数リストなどの非同期データ領域に関数ブロックを配置します。さらに、 DataSyncAlways ランタイムシステムの構成ファイル内のエントリ（ *.cfg ）を使用して、各サイクルの開始時にデータを同期します。 [CmpRedundancy]\nDataSyncAlways=1 " }, 
{ "title" : "行動 ", 
"url" : "_mod_client_redundancy.html#UUID-0812546d-012d-898c-c88e-3b900f1eda1d_section-idm4512096403710433428678152475", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 機能 \/ TCPクライアントの冗長性 \/ 行動 ", 
"snippet" : "たとえ RedundancyManager ファンクションブロックが使用される場合、切り替えや同期アクションは実行されません。 CODESYS Modbus Modbus 通信は、それぞれのコントローラの冗長状態にのみ反応します。 2台のコントローラー間で既存の冗長リンクが動作している場合、Modbus通信はアクティブコントローラー経由でのみ実行されます。アクティブコントローラーが切り替わると、パッシブコントローラーのModbus通信は終了し、アクティブコントローラー上で確立されます。 冗長リンクなしでシステムを最初に起動すると、Modbus 通信は ID 1 のコントローラー経由でのみ確立さ...", 
"body" : "たとえ RedundancyManager ファンクションブロックが使用される場合、切り替えや同期アクションは実行されません。 CODESYS Modbus Modbus 通信は、それぞれのコントローラの冗長状態にのみ反応します。 2台のコントローラー間で既存の冗長リンクが動作している場合、Modbus通信はアクティブコントローラー経由でのみ実行されます。アクティブコントローラーが切り替わると、パッシブコントローラーのModbus通信は終了し、アクティブコントローラー上で確立されます。 冗長リンクなしでシステムを最初に起動すると、Modbus 通信は ID 1 のコントローラー経由でのみ確立されます。 ランタイムモードで冗長リンクが失われた場合、両方のコントローラでModbus通信がアクティブになります。これにより発生する可能性のある問題（通信の重複など）は、このファンクションブロックでは処理されません。 " }, 
{ "title" : "図書館 ", 
"url" : "_mod_f_master_libraries.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "機能ブロック: IoDrvModbusComPort ", 
"url" : "_mod_lib_iodrvmodbuscomport.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: IoDrvModbusComPort ", 
"snippet" : "図書館： IoDrvModbus このブロックは、デバイス ツリー内のシリアル Modbus クライアントごとに生成されます。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xStop Bool FALSE もし TRUE の場合、サーバーへの新しいリクエストはすべて停止されます。 FALSE 、プロセスは続行されます。 xAcknowledge Bool FALSE 立ち上がりエッジでCOM ポートを直ちに閉じて開きます 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 uiNumberOfCommunicatingSlaves int 0 通信サーバーの数を表示し...", 
"body" : "図書館： IoDrvModbus このブロックは、デバイス ツリー内のシリアル Modbus クライアントごとに生成されます。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xStop Bool FALSE もし TRUE の場合、サーバーへの新しいリクエストはすべて停止されます。 FALSE 、プロセスは続行されます。 xAcknowledge Bool FALSE 立ち上がりエッジでCOM ポートを直ちに閉じて開きます 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 uiNumberOfCommunicatingSlaves int 0 通信サーバーの数を表示します xAllSlavesOk Bool FALSE TRUE すべてのサーバーが通信する場合。 FALSE 一部のサーバーにエラーがある場合。 " }, 
{ "title" : "機能ブロック: IoDrvModbusTCP ", 
"url" : "_mod_lib_iodrvmodbustcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: IoDrvModbusTCP ", 
"snippet" : "図書館： IoDrvModbusTCP このブロックは、デバイス ツリー内の各 Modbus クライアント TCP に対して生成されます。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xStop Bool FALSE すべてのTCP\/IP通信を停止します 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xSlaveError Bool FALSE エラーのあるサーバー FB があることを示します。 uiConnectedSlaves UINT 0 TCP\/IPで接続されたサーバーの数...", 
"body" : "図書館： IoDrvModbusTCP このブロックは、デバイス ツリー内の各 Modbus クライアント TCP に対して生成されます。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xStop Bool FALSE すべてのTCP\/IP通信を停止します 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xSlaveError Bool FALSE エラーのあるサーバー FB があることを示します。 uiConnectedSlaves UINT 0 TCP\/IPで接続されたサーバーの数 " }, 
{ "title" : "機能ブロック: ModbusRequest ", 
"url" : "_mod_lib_modbusrequest.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: ModbusRequest ", 
"snippet" : "図書館： IoDrvModbusTCP 定義済みのModbusコマンドに加えて、 Modbus サーバー チャネル タブでは、このファンクションブロックにより、アプリケーション内で追加のコマンドを動的に実行できます。ただし、これらのプログラムで作成されたコマンドにはI\/Oマッピングはなく、以下のタイプの入出力データ範囲のみがあります。 ARRAY OF BYTE または ARRAY OF WORD 。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 Slave ModbusTCPSlave xExecute BOOL 上昇エッジ: アクションが始まります。 立ち下がりエッジ: ファ...", 
"body" : "図書館： IoDrvModbusTCP 定義済みのModbusコマンドに加えて、 Modbus サーバー チャネル タブでは、このファンクションブロックにより、アプリケーション内で追加のコマンドを動的に実行できます。ただし、これらのプログラムで作成されたコマンドにはI\/Oマッピングはなく、以下のタイプの入出力データ範囲のみがあります。 ARRAY OF BYTE または ARRAY OF WORD 。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 Slave ModbusTCPSlave xExecute BOOL 上昇エッジ: アクションが始まります。 立ち下がりエッジ: ファンクションブロックがアクションを終了する前に立ち下がりエッジが発生すると、出力はリセットされます。出力は通常通り動作し、アクションが終了したか中止された場合にのみリセットされます( xAbort ）、またはエラーが発生した場合。この場合、対応する出力値（ xDone 、 xError 、 iError ) は、正確に 1 サイクルの間、出力に存在します。 xAbort BOOL TRUE : アクションは直ちに中止され、すべての出力は初期値に設定されます。 usiUnitID UINT 16#FF ユニット ID は、Modbus シリアル バスへの転送 (ゲートウェイ) にのみ使用されます。 TCP\/IPの場合、MODBUSサーバーはIPアドレスによってアドレス指定されます。この場合、MODBUSユニットIDは使用されません（値0xFFを使用する必要があります）。 シリアル接続の場合、Modbus デバイスは 1 ～ 247 のユニット ID でアドレス指定されます (0 はブロードキャスト アドレスに使用されます)。 ModbusCommand ModbusCommand 実行するModbusコマンド。ビットおよびワードアクセス用のファンクションブロックがサポートされています。 pSendData POINTER TO BYTE サーバーに送信されるデータを含むバッファへのポインタ。 レジスタアクセスの場合、バッファのタイプは Array[0..ModbusCommand.uiWriteLen - 1] OF WORD ビットアクセスの場合、バッファは ARRAY[0..ModbusCommand.uiWriteLen \/ 8] OF BYTE 。 pRecvData POINTER TO BYTE サーバーが受信したデータが書き込まれるバッファへのポインタ。 レジスタアクセスの場合、バッファのタイプは ARRAY[0..ModbusCommand.uiReadLen - 1] OF WORD ビットアクセスの場合、バッファは ARRAY[0..ModbusCommand.uiReadLen \/ 8] OF BYTE 。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xDone BOOL FALSE TRUE リクエストが正常に終了した場合 xBusy BOOL FALSE TRUE リクエストが処理されている間 xError BOOL FALSE TRUE リクエストがエラーで終了した場合 xAborted BOOL FALSE TRUE リクエストがユーザーによって中止された場合 ModbusError MB_ErrorCodes 現在のエラー。 MB_ErrorCodes 列挙。 " }, 
{ "title" : "機能ブロック: ModbusSlaveComPort ", 
"url" : "_mod_lib_modbusslavecomport.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: ModbusSlaveComPort ", 
"snippet" : "図書館： IoDrvModbus このブロックは、デバイスツリー内の各シリアルModbusサーバーに対して生成されます。このファンクションブロックは、個々のModbusシリアルサーバーへの論理接続を表します。このデバイスに定義されたチャンネルはバックグラウンドで処理されます。このブロックの入出力は、ユーザーにステータス情報を提供し、発生したエラーを確認する（処理を続行するため）機能を提供します。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xTrigger Bool FALSE 設定されたすべてのModbusチャネルの送信を立ち上がりエッジでトリガーします。 xReset Bo...", 
"body" : "図書館： IoDrvModbus このブロックは、デバイスツリー内の各シリアルModbusサーバーに対して生成されます。このファンクションブロックは、個々のModbusシリアルサーバーへの論理接続を表します。このデバイスに定義されたチャンネルはバックグラウンドで処理されます。このブロックの入出力は、ユーザーにステータス情報を提供し、発生したエラーを確認する（処理を続行するため）機能を提供します。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xTrigger Bool FALSE 設定されたすべてのModbusチャネルの送信を立ち上がりエッジでトリガーします。 xReset Bool FALSE 通信を再開しリセットする xError そして byModbusError xAcknowledge Bool FALSE 通信を再開し、リセットしない xError そして byModbusError 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xInitDone Bool FALSE すべての初期化コマンドがリセットされました。 xError Bool FALSE TRUE エラーが発生した場合、このサーバーへの通信は中断されます。 byModbusError MB_ErrorCodes 0 現在のエラーは、 MB_ErrorCodes 列挙 " }, 
{ "title" : "機能ブロック: ModbusTCPSlave ", 
"url" : "_mod_lib_modbustcpslave.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: ModbusTCPSlave ", 
"snippet" : "図書館： IoDrvModbusTCP このブロックは、デバイスツリー内の各ModbusサーバーTCPに対して生成されます。このファンクションブロックは、個々のModbus TCPサーバーへのTCP\/IP接続を表します。このデバイスに定義されたチャネルはバックグラウンドで処理されます。このブロックの入出力は、ユーザーにステータス情報を提供し、発生したエラーを確認する（処理を続行するため）機能を提供します。 Enable プロパティは通信を開始および停止するために使用されます。 その Enable プロパティは、 デバイスの診断を有効にする オプションが選択されている場合は PLC設定 タブ。 ...", 
"body" : "図書館： IoDrvModbusTCP このブロックは、デバイスツリー内の各ModbusサーバーTCPに対して生成されます。このファンクションブロックは、個々のModbus TCPサーバーへのTCP\/IP接続を表します。このデバイスに定義されたチャネルはバックグラウンドで処理されます。このブロックの入出力は、ユーザーにステータス情報を提供し、発生したエラーを確認する（処理を続行するため）機能を提供します。 Enable プロパティは通信を開始および停止するために使用されます。 その Enable プロパティは、 デバイスの診断を有効にする オプションが選択されている場合は PLC設定 タブ。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 xConfirmError Bool FALSE このプロセスは立ち上がりエッジで継続されます。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xInitDone Bool FALSE 通信サーバーの数を表示します xBusy Bool FALSE TRUE リクエストが処理されている間 xDone Bool FALSE TRUE リクエストが正常に終了した場合 xError Bool FALSE TRUE リクエストがエラーで終了した場合 byModbusError MB_ErrorCodes 列挙で定義されている現在のエラーを指定します MB_ErrorCodes ComSettings ModbusTCPCommSettings 現在構成されている通信設定 xConfirmError Bool False このプロセスは立ち上がりエッジで継続されます。 " }, 
{ "title" : "メソッド: UpdateCommunicationSettings ", 
"url" : "_mod_lib_modbustcpslave.html#UUID-5feb1626-d39e-e3de-4fd6-695c4e431625_section-idm43285377749268", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: ModbusTCPSlave \/ メソッド: UpdateCommunicationSettings ", 
"snippet" : "通信パラメータは、サーバーが「停止」に設定されている場合にのみ更新できます。 Enable プロパティは、サーバーを停止および起動するために使用されます。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 ipAdress ARRAY [0..3] OF BYTE サーバーのIPアドレス uiPort UINT サーバーのポート 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 UpdateCommunicationSettings UDINT TCP接続が存在する場合、エラーが発生します（戻り値!= 0）。...", 
"body" : "通信パラメータは、サーバーが「停止」に設定されている場合にのみ更新できます。 Enable プロパティは、サーバーを停止および起動するために使用されます。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 ipAdress ARRAY [0..3] OF BYTE サーバーのIPアドレス uiPort UINT サーバーのポート 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 UpdateCommunicationSettings UDINT TCP接続が存在する場合、エラーが発生します（戻り値!= 0）。 " }, 
{ "title" : "機能ブロック: ModbusChannel ", 
"url" : "_mod_lib_modbuschannel.html", 
"breadcrumbs" : "CODESYS Modbus \/ クライアント \/ 図書館 \/ 機能ブロック: ModbusChannel ", 
"snippet" : "図書館： IoDrvModbus この機能ブロックは、構成された単一の Modbus チャネルの実行を開始します。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 Slave ModbusSlaveComPort xExecute BOOL 上昇エッジ: アクションが始まります。 立ち下がりエッジ: ファンクションブロックがアクションを終了する前に立ち下がりエッジが発生すると、出力はリセットされます。出力は通常通り動作し、アクションが終了したか中止された場合にのみリセットされます( xAbort ）、またはエラーが発生した場合。この場合、対応する出力値（ xDone 、 xErro...", 
"body" : "図書館： IoDrvModbus この機能ブロックは、構成された単一の Modbus チャネルの実行を開始します。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 Slave ModbusSlaveComPort xExecute BOOL 上昇エッジ: アクションが始まります。 立ち下がりエッジ: ファンクションブロックがアクションを終了する前に立ち下がりエッジが発生すると、出力はリセットされます。出力は通常通り動作し、アクションが終了したか中止された場合にのみリセットされます( xAbort ）、またはエラーが発生した場合。この場合、対応する出力値（ xDone 、 xError 、 iError ) は、正確に 1 サイクルの間、出力に存在します。 xAbort BOOL TRUE : アクションは直ちに中止され、すべての出力は初期値に設定されます。 iChannelIndex INT 実行するチャネルのインデックス。無効なインデックスの場合は、 xError = TRUE (Modbus 固有のエラー コードなし)。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xDone BOOL FALSE TRUE リクエストが正常に終了した場合 xBusy BOOL FALSE TRUE リクエストが処理されている間 xError BOOL FALSE TRUE リクエストがエラーで終了した場合 xAborted BOOL FALSE TRUE リクエストがユーザーによって中止された場合 ModbusError MB_ErrorCodes 現在のエラー。 MB_ErrorCodes 列挙。 " }, 
{ "title" : "デバイス ", 
"url" : "_mod_f_slave_device.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "構成 ", 
"url" : "_mod_f_device_configuration.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 構成 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "タブ: Modbusシリアルデバイス –全般 ", 
"url" : "_mod_edt_slave_device_com.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 構成 \/ タブ: Modbusシリアルデバイス –全般 ", 
"snippet" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 ユニット サーバーのユニット ウォッチドッグ :ウォッチドッグ機能を有効にします。 Modbus デバイスがクライアントから有効なクエリを受信しない場合、受信データ (保持レジスタ \/ %I 範囲) はゼロに設定されます。 保持レジスタ（%IW） 保持レジスタの数：可能な値：1～4096。デバイスの説明で最大数を制限できます。 書き込み可能 : :保持レジスタについては、読み取り専用I\/Oマッピング（%IWアドレス）ではなく、書き込み可能なI\/Oマッピング（%QWアドレス）が生成されます。これにより、Modbusデバイ...", 
"body" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 ユニット サーバーのユニット ウォッチドッグ :ウォッチドッグ機能を有効にします。 Modbus デバイスがクライアントから有効なクエリを受信しない場合、受信データ (保持レジスタ \/ %I 範囲) はゼロに設定されます。 保持レジスタ（%IW） 保持レジスタの数：可能な値：1～4096。デバイスの説明で最大数を制限できます。 書き込み可能 : :保持レジスタについては、読み取り専用I\/Oマッピング（%IWアドレス）ではなく、書き込み可能なI\/Oマッピング（%QWアドレス）が生成されます。これにより、Modbusデバイスアプリケーション（=サーバーアプリケーション）から通常のI\/Oマッピングを使用して保持レジスタを設定できます。 入力レジスタ（%QW） 入力レジスタの数：可能な値：1～4096。デバイスの説明で最大数を制限することができます。 入出力アセンブリのサイズを変更すると、I\/Oマッピングで構成可能なパラメータの数に直接影響します。 Modbus は、I\/O データに対して 4 つの領域を持つデータ モデルを定義します。 コイル:出力タイプ BIT ディスクリート入力: 入力タイプ BYTE 保持レジスタ:出力タイプ WORD （16ビット） 入力レジスタ: 入力の種類 WORD （16ビット） 入出力は他のフィールドバスと同様に存在しますが、「ホスト」の観点から見ると、入出力はホスト側からのみ存在します。これらのデータ領域には、メーカーが定義した任意の数の論理開始オフセットが存在します。Modbusデータ領域の背後にあるI\/Oデータは、重複することも、互いに独立して存在することもできます。 Modbusデータモデルの詳細については、Modbusプロトコル仕様の第4.3章および第4.4章を参照してください（ www.modbus.org ）。 の場合 CODESYS Modbusデバイスでは、入力レジスタとディスクリート入力、そして保持レジスタとコイルはすべて同じI\/Oデータにマッピングされます。これは、異なる論理開始オフセットでアドレス指定されている場合でも同様です。 開始アドレス コイル それぞれのModbusデータ領域の開始アドレスの定義 ディスクリート入力 保持レジスタ 入力レジスタ " }, 
{ "title" : "タブ: Modbus TCPサーバーデバイス –全般 ", 
"url" : "_mod_edt_slave_device_tcp.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 構成 \/ タブ: Modbus TCPサーバーデバイス –全般 ", 
"snippet" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 設定されたパラメータ ウォッチドッグ :ウォッチドッグ機能を有効にします。 Modbus デバイスがクライアントから有効なクエリを受信しない場合、受信データ (保持レジスタ \/ %I 範囲) はゼロに設定されます。 TCPソケットを閉じる :ウォッチドッグが有効になっていて、設定された時間を超えると、TCP ソケットは閉じられます。 サーバーポート サーバーのポート番号 アダプターにバインド このオプションは、複数のイーサネット アダプタを備えたシステムに関係します。 Modbusサーバーのサーバーソケットは、割り当て...", 
"body" : "このタブには、ネットワーク内のネットワーク通信の基本設定が含まれています。 設定されたパラメータ ウォッチドッグ :ウォッチドッグ機能を有効にします。 Modbus デバイスがクライアントから有効なクエリを受信しない場合、受信データ (保持レジスタ \/ %I 範囲) はゼロに設定されます。 TCPソケットを閉じる :ウォッチドッグが有効になっていて、設定された時間を超えると、TCP ソケットは閉じられます。 サーバーポート サーバーのポート番号 アダプターにバインド このオプションは、複数のイーサネット アダプタを備えたシステムに関係します。 Modbusサーバーのサーバーソケットは、割り当てられたイーサネットアダプターのIPアドレスにバインドされます。このIPアドレスに送信されたModbusリクエストのみが受信されます。 : ModbusサーバーのサーバーソケットはIPアドレスにバインドされていません。システム（Modbusポート）で受信したすべてのModbusリクエストが処理されます。 保持レジスタ（%IW） 保持レジスタの数：可能な値：1～4096。デバイスの説明で最大数を制限できます。 書き込み可能 : :保持レジスタについては、読み取り専用I\/Oマッピング（%IWアドレス）ではなく、書き込み可能なI\/Oマッピング（%QWアドレス）が生成されます。これにより、Modbusデバイスアプリケーション（=サーバーアプリケーション）から通常のI\/Oマッピングを使用して保持レジスタを設定できます。 入力レジスタ（%QW） 入力レジスタの数：可能な値：1～4096。デバイスの説明で最大数を制限することができます。 ビット領域をレジスタ領域から分離 Modbusコイルとディスクリート入力はそれぞれ独自のデータ領域を持ちます。デフォルトでは、レジスタアクセスとビットアクセスは同じModbusデータを使用します。 コイル Modbusコイルの数 ディスクリート入力 Modbusディスクリート入力の数 入出力アセンブリのサイズを変更すると、I\/Oマッピングで構成可能なパラメータの数に直接影響します。 データ モデル Modbus は、I\/O データに対して 4 つの領域を持つデータ モデルを定義します。 コイル：BIT型出力 ディスクリート入力: BYTE型の入力 保持レジスタ：WORD型（16ビット）の出力 入力レジスタ: WORD型（16ビット）の入力 入出力は他のフィールドバスと同様に存在しますが、「ホスト」の観点から見ると、入出力はホスト側からのみ存在します。これらのデータ領域には、メーカーが定義した任意の数の論理開始オフセットが存在します。Modbusデータ領域の背後にあるI\/Oデータは、重複することも、互いに独立して存在することもできます。 Modbusデータモデルの詳細については、Modbusプロトコル仕様の第4.3章および第4.4章を参照してください（ www.modbus.org ）。 の場合 CODESYS Modbusデバイスでは、入力レジスタとディスクリート入力、そして保持レジスタとコイルはすべて同じI\/Oデータにマッピングされます。これは、異なる論理開始オフセットでアドレス指定されている場合でも同様です。 コイル それぞれのModbusデータ領域の開始アドレスの定義 ディスクリート入力 保持レジスタ 入力レジスタ 保持レジスタと入力レジスタのデータ領域のオーバーレイ : 保持および入力レジスタによるプロセス イメージのオーバーレイ。 これは、たとえば、サーバー アプリケーションを使用して保持レジスタに書き込む場合に必要になります。 " }, 
{ "title" : "タブ: Modbus TCPサーバーデバイス –シリアル ゲートウェイ ", 
"url" : "_mod_edt_slave_serial_gateway.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 構成 \/ タブ: Modbus TCPサーバーデバイス –シリアル ゲートウェイ ", 
"snippet" : "この機能はModbus TCPサーバーの標準ライセンスには含まれていません。Modbusシリアルクライアントもライセンスが必要です。 このタブには、デバイスをシリアルModbus TCP\/ RTUゲートウェイに拡張するための設定が含まれています。Modbus Modbus TCPサーバーは、TCPクライアントからのリクエストをPLCのローカルCOM ポートに接続されたModbus RTUサーバーに転送します。 シリアル ゲートウェイアクティブ : デバイスの TCP\/ RTUゲートウェイ機能が有効になっています。 COM ポート 使用されているCOM ポート番号 ボーレート 伝送速度（ボー）...", 
"body" : "この機能はModbus TCPサーバーの標準ライセンスには含まれていません。Modbusシリアルクライアントもライセンスが必要です。 このタブには、デバイスをシリアルModbus TCP\/ RTUゲートウェイに拡張するための設定が含まれています。Modbus Modbus TCPサーバーは、TCPクライアントからのリクエストをPLCのローカルCOM ポートに接続されたModbus RTUサーバーに転送します。 シリアル ゲートウェイアクティブ : デバイスの TCP\/ RTUゲートウェイ機能が有効になっています。 COM ポート 使用されているCOM ポート番号 ボーレート 伝送速度（ボー） " }, 
{ "title" : "図書館 ", 
"url" : "_mod_f_device_libraries.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 図書館 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "機能ブロック: IoDrvModbusSerialSlave ", 
"url" : "_mod_lib_iodrvmodbusserialslave.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 図書館 \/ 機能ブロック: IoDrvModbusSerialSlave ", 
"snippet" : "図書館： IoDrvModbusSerialSlave このブロックは、デバイス ツリー内のシリアル Modbus サーバー デバイスごとに生成されます。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xInternalError Bool FALSE 回復不可能な内部エラー（例えば、 mem-aloc またはライセンスがありません）...", 
"body" : "図書館： IoDrvModbusSerialSlave このブロックは、デバイス ツリー内のシリアル Modbus サーバー デバイスごとに生成されます。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xInternalError Bool FALSE 回復不可能な内部エラー（例えば、 mem-aloc またはライセンスがありません） " }, 
{ "title" : "機能ブロック: IoDrvModbusTCPSlave ", 
"url" : "_mod_lib_iodrvmodbustcpslave.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 図書館 \/ 機能ブロック: IoDrvModbusTCPSlave ", 
"snippet" : "図書館： IoDrvModbusTCPSlave このブロックは、デバイス ツリー内の各Modbus TCPサーバー デバイスに対して生成されます。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xInternalError Bool FALSE 回復不可能な内部エラー（例えば、 mem-aloc またはライセンスがありません） uiClientConnections Bool FALSE 現在確立されているクライアント接続の数（TCP\/IP）...", 
"body" : "図書館： IoDrvModbusTCPSlave このブロックは、デバイス ツリー内の各Modbus TCPサーバー デバイスに対して生成されます。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xInternalError Bool FALSE 回復不可能な内部エラー（例えば、 mem-aloc またはライセンスがありません） uiClientConnections Bool FALSE 現在確立されているクライアント接続の数（TCP\/IP） " }, 
{ "title" : "機能ブロック: ModbusServer ", 
"url" : "_mod_lib_modbusserver.html", 
"breadcrumbs" : "CODESYS Modbus \/ デバイス \/ 図書館 \/ 機能ブロック: ModbusServer ", 
"snippet" : "図書館： ModbusTCP Server 機能ブロックは、Modbus TCPによる最大 16 個の並列クライアント接続要求を処理します。Modbus 要求は、入力レジスタと保持レジスタをマッピングするデータ範囲内で動作します。 次の Modbus 機能コードがサポートされています。 0x01 Read Coils 0x02 Read Discrete Inputs 0x03 Read Holding Registers 0x04 Read Input Registers 0x05 Write Single Coil 0x06 Write Single Register 0x0F Write...", 
"body" : "図書館： ModbusTCP Server 機能ブロックは、Modbus TCPによる最大 16 個の並列クライアント接続要求を処理します。Modbus 要求は、入力レジスタと保持レジスタをマッピングするデータ範囲内で動作します。 次の Modbus 機能コードがサポートされています。 0x01 Read Coils 0x02 Read Discrete Inputs 0x03 Read Holding Registers 0x04 Read Input Registers 0x05 Write Single Coil 0x06 Write Single Register 0x0F Write Multiple Coils 0x10 Write Multiple Registers 0x17 Read\/Write Multiple Registers ModbusServer機能ブロックは、 Modbus TCPサーバーのデバイス エディター タブで設定されたパラメータを使用します。 入力 (VAR_INPUT) 名前 データ型 初期値 説明 wPort WORD 502 サーバーポート（TCP\/IPプロトコルスタック）502はModbusのデフォルトです pInputData POINTER TO WORD ポインタ WORD ; Modbus入力レジスタのマップを指します uiInputDataSize UINT 1024 入力データの配列の長さ（ WORD レジスタあたり）; デフォルト: 1024 pOutputData POINTER TO WORD ポインタ WORD ; Modbus保持レジスタのマップを指します uiOutputDataSize UINT 出力データの配列の長さ（ WORD レジスターあたり tTimeout UDINT タイムアウト（ミリ秒）。ゼロでなく、タイムアウトまでにModbus書き込みエラーが発生していない場合、出力データはゼロに設定されます。 xEnable BOOL FALSE リクエスト処理を開始するためのフラグ xReset BOOL FALSE サーバーとの通常の通信の再開、立ち上がりエッジのステータスワードとエラービットのリセット InterfaceName WSTRING(255) イーサネットインターフェースの名前（オプション）。指定すると、ModbusサーバーはこのインターフェースのIPアドレスにバインドします。 出力 (VAR_OUTPUT) 名前 データ型 初期値 説明 xBusy BOOL FALSE TRUE リクエストが処理されている間 xError BOOL FALSE 見つかったエラーに関する情報 byClientConnections BYTE 0 接続数 xTimeout BOOL タイムアウトが経過しました。保持レジスタとコイルはゼロに設定されます。 " }
]
$(document).trigger('search.ready');
});