$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS SoftMotion Light ", 
"url" : "_sm_light_start_page.html", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ CODESYS SoftMotion Light ", 
"snippet" : "CODESYS SoftMotion Light 是针对单轴运动的功能受限运动解决方案。它允许您使用一个控制器控制大量轴。 由于在轴上执行运动，控制器和现场总线都可以减轻负担。只有状态更新和运动命令通过现场总线发送。为命令和监控轴，实现了熟悉的用于运动控制的 PLCopen 功能块，例如 MC_Home , MC_MoveAbsolute ， 和 MC_ReadStatus .还提供了简化的功能。 下表显示了如何 CODESYS SoftMotion Light 不同于 CODESYS SoftMotion . CODESYS SoftMotion CODESYS SoftMotion Lig...", 
"body" : "CODESYS SoftMotion Light 是针对单轴运动的功能受限运动解决方案。它允许您使用一个控制器控制大量轴。 由于在轴上执行运动，控制器和现场总线都可以减轻负担。只有状态更新和运动命令通过现场总线发送。为命令和监控轴，实现了熟悉的用于运动控制的 PLCopen 功能块，例如 MC_Home , MC_MoveAbsolute ， 和 MC_ReadStatus .还提供了简化的功能。 下表显示了如何 CODESYS SoftMotion Light 不同于 CODESYS SoftMotion . CODESYS SoftMotion CODESYS SoftMotion Light 所需的 CPU 资源 高的 低的 所需的总线带宽\/速度 高的 低的 所需的实时功能（PLC 和现场总线） 高的 低的 新运动命令生效前的延迟 非常低（新命令在同一个 PLC 循环中开始） 中（取决于配置和现场总线） 多轴同步（凸轮、电子齿轮和 CNC）和高级功能，如测头。 支持的 不支持 支持的驱动器 特定驱动器的驱动程序数量庞大且数量不断增加 支持 CiA 402 的驱动器 您可以下载 CODESYS SoftMotion Light 来自 CODESYS Store International  或者 CODESYS Store North America .在那里您还可以找到该产品的数据表。 " }, 
{ "title" : "驱动器的要求 ", 
"url" : "_sm_light_requirements.html", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 驱动器的要求 ", 
"snippet" : "驱动器必须满足以下要求才能与 CODESYS SoftMotion Light ： EtherCAT 或 CAN 支持 CiA 402 支持，尤其是在以下操作模式下： Profile position mode （为了 MC_MoveAbsolute_SML \/ MC_MoveRelative_SML ) Profile velocity mode （为了 MC_MoveVelocity_SML ) Homing mode （为了 MC_Home_SML . 如果驱动器不支持其中一种模式，则不能使用相应的功能块。 支持 CiA 402 定义并在下表中列出的对象： 目的 描述 SML 参数 评论...", 
"body" : "驱动器必须满足以下要求才能与 CODESYS SoftMotion Light ： EtherCAT 或 CAN 支持 CiA 402 支持，尤其是在以下操作模式下： Profile position mode （为了 MC_MoveAbsolute_SML \/ MC_MoveRelative_SML ) Profile velocity mode （为了 MC_MoveVelocity_SML ) Homing mode （为了 MC_Home_SML . 如果驱动器不支持其中一种模式，则不能使用相应的功能块。 支持 CiA 402 定义并在下表中列出的对象： 目的 描述 SML 参数 评论 16#6040 控制字 10064 16#6041 状态字 20065 16#605A 快速停止选项代码 选修的 如果不支持，则假定驱动器保持 CiA 402 状态 Quick Stop Active 快速停止后。 （这对应于 5 到 8 之间的值。） 16#605D 暂停选项代码 选修的 如果不支持，则驱动器应响应停止，如模式 2（“快速停止模式减速”）。如果没有，那么 MC_Stop_SML 将无法正确响应。 16#6060 操作模式 2000 16#6061 操作模式显示。 2001 16#6064\/16#6063 实际位置 1101 使用时需要 MC_MoveAbsolute_SML 或者 MC_MoveRelative_SML 在模数轴上。在这种情况下，您必须通过 PDO 传输。 （注意：或者，您可以转移对象 16#6063 通过 PDO。） 16#607A 目标位置 2030 使用时需要 MC_MoveAbsolute_SML 或者 MC_MoveRelative_SML . 16#607C 原点偏移 1211 使用时需要 MC_Home_SML . 16#6081 速度剖面 2050 使用时需要 MC_MoveAbsolute_SML 或者 MC_MoveRelative_SML . 16#6083 加速度曲线 2060 16#6084 减速曲线 2070 16#6085 减速急停 2090 选修的 如果不支持，则必须专门为驱动器配置快速停止减速度。 16#6086 类型运动曲线 1062 选修的 使用的配置文件类型为 0（线性斜坡）和 1（正弦斜坡）。 16#60FF 目标速度 2040 必须使用时需要 MC_Movevelocity_SML . 您可以将所有这些对象映射为 PDO。但是，建议仅对控制字、状态字和当前位置（如有必要）使用。 " }, 
{ "title" : "驱动器配置 ", 
"url" : "_sm_light_driveconfiguration.html", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 驱动器配置 ", 
"snippet" : "调整速度或加速度单位 如果您无法将驱动器的速度单位设置为 [inc\/s] 或无法将加速度单位设置为 [inc\/s²]），那么您可以调整 fConstVelFactor 和 fConstAccFactor 参数。 您可以在选项中启用通用配置编辑器的显示。 例子 驱动器期望速度以 [inc\/(64*s)] 为单位，而不是 [inc\/s]。 在编辑器中，打开驱动器并切换到 <设备名称>：参数 标签。 在设备编辑器的通用“...配置”选项卡中修改参数： 为此，选择“值”列中的字段并单击它或按下 进入 键打开编辑字段。 双击该值 fConstVelFactor 参数并指定 64 作为值。...", 
"body" : "调整速度或加速度单位 如果您无法将驱动器的速度单位设置为 [inc\/s] 或无法将加速度单位设置为 [inc\/s²]），那么您可以调整 fConstVelFactor 和 fConstAccFactor 参数。 您可以在选项中启用通用配置编辑器的显示。 例子 驱动器期望速度以 [inc\/(64*s)] 为单位，而不是 [inc\/s]。 在编辑器中，打开驱动器并切换到 <设备名称>：参数 标签。 在设备编辑器的通用“...配置”选项卡中修改参数： 为此，选择“值”列中的字段并单击它或按下 进入 键打开编辑字段。 双击该值 fConstVelFactor 参数并指定 64 作为值。 " }, 
{ "title" : "的配置 CODESYS SoftMotion Light 驾驶 ", 
"url" : "_sm_light_driveconfiguration.html#UUID-6d14bc69-35ca-2d41-e329-ff9464a156cc_e9cbf584fcbb189dc0a864632dc38f79_id_37d03894df7f83dfc0a8640e0158186c", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 驱动器配置 \/ 的配置 CODESYS SoftMotion Light 驾驶 ", 
"snippet" : "使用时 CODESYS SoftMotion Light ，建议对驱动器进行以下配置设置： 职位单位 16#607A , 16#607C ， 和 16#6064 对象应对应于编码器增量 ([inc]) 以实现最大精度。您可以在 SoftMotionLight 标签。 速度单位 16#6081 和 16#60FF 对象应配置为每秒编码器增量 ([inc\/s])。 加速度单位 16#6081 和 16#60FF 对象应配置为每秒编码器增量 ([inc\/s])。 驱动器对快速停止命令（控制字中的位 2）的响应应配置为 <Slow down on quick stop ramp and stay in...", 
"body" : "使用时 CODESYS SoftMotion Light ，建议对驱动器进行以下配置设置： 职位单位 16#607A , 16#607C ， 和 16#6064 对象应对应于编码器增量 ([inc]) 以实现最大精度。您可以在 SoftMotionLight 标签。 速度单位 16#6081 和 16#60FF 对象应配置为每秒编码器增量 ([inc\/s])。 加速度单位 16#6081 和 16#60FF 对象应配置为每秒编码器增量 ([inc\/s])。 驱动器对快速停止命令（控制字中的位 2）的响应应配置为 <Slow down on quick stop ramp and stay in \"Quick Stop Active\"> . 驱动器对停止命令（控制字中的第 8 位）的响应应配置为 <Slow down on quick stop ramp and stay in \"Operation Enabled\"> . 注意：如果驱动器支持标准对象 16#605D ，那么这是由 CODESYS SoftMotion Light 通过在初始化期间写入值 2。 应配置合适的快速停止斜坡。 检查包装中包含的测试项目，您的驱动器是否适合与 CODESYS SoftMotion Light . " }, 
{ "title" : "错误诊断 ", 
"url" : "_sm_light_driveconfiguration.html#UUID-6d14bc69-35ca-2d41-e329-ff9464a156cc_e9cbf584fcbb189dc0a864632dc38f79_id_fa8e18d2df7f83dfc0a8640e002f448b", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 驱动器配置 \/ 错误诊断 ", 
"snippet" : "故障分析选项： 控制器日志中的条目。 驱动器现场总线从站的状态：设备树中现场总线设备旁边的红色符号表示驱动器存在非特定于 CODESYS SoftMotion Light .驱动器无法切换到“运行”模式。在这种情况下，请查看详细状态显示或设备显示。 通讯状态 CODESYS SoftMotion Light 设备：显示在编辑器中 CODESYS SoftMotion Light 设备上 SoftMotionLight 选项卡中的 在线的 场地。如果您指定，它也会出现在监控窗口中 <DriveName.wCommunicationState> 那里。状态 <100：驱动器初始化尚未结束；状态 >...", 
"body" : "故障分析选项： 控制器日志中的条目。 驱动器现场总线从站的状态：设备树中现场总线设备旁边的红色符号表示驱动器存在非特定于 CODESYS SoftMotion Light .驱动器无法切换到“运行”模式。在这种情况下，请查看详细状态显示或设备显示。 通讯状态 CODESYS SoftMotion Light 设备：显示在编辑器中 CODESYS SoftMotion Light 设备上 SoftMotionLight 选项卡中的 在线的 场地。如果您指定，它也会出现在监控窗口中 <DriveName.wCommunicationState> 那里。状态 <100：驱动器初始化尚未结束；状态 >= 1000：错误；状态=100：通信已建立。 strDriveInterfaceError 和 uiDriveInterfaceError 变量：这些变量显示在 CODESYS SoftMotion Light 设备上 SoftMotionLight 选项卡中的 在线的 场地。大多数情况下， strDriveInterfaceError 提供有关当前问题的信息。 执行时出错 CODESYS SoftMotion Light 功能块：最后出现的错误 功能块错误 显示在配置编辑器中 CODESYS SoftMotion Light 设备。在 SoftMotionLight 选项卡，在 在线的 场地。 " }, 
{ "title" : "更改原点偏移的符号 (+\/-) ", 
"url" : "_sm_light_driveconfiguration.html#UUID-6d14bc69-35ca-2d41-e329-ff9464a156cc_e9cbf584fcbb189dc0a864632dc38f79_id_01f408d801a6aa94c0a8646314931115", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 驱动器配置 \/ 更改原点偏移的符号 (+\/-) ", 
"snippet" : "如果在回原点后驱动器的当前位置符号不正确，则可以通过参数进行纠正。 要激活通用配置编辑器的显示，您可以使用 显示通用设备配置编辑器 选项中的 设备编辑器 的类别 CODESYS 选项。 例子 你打电话给 MC_Home_SML “位置=100”的功能块。归位成功后，驱动器报告的当前位置为-100。 在编辑器中，打开驱动器并切换到 <设备名称>：参数 标签。 双击该值 bInvertHomeOffset 范围。 参数值从 FALSE 到 TRUE ....", 
"body" : "如果在回原点后驱动器的当前位置符号不正确，则可以通过参数进行纠正。 要激活通用配置编辑器的显示，您可以使用 显示通用设备配置编辑器 选项中的 设备编辑器 的类别 CODESYS 选项。 例子 你打电话给 MC_Home_SML “位置=100”的功能块。归位成功后，驱动器报告的当前位置为-100。 在编辑器中，打开驱动器并切换到 <设备名称>：参数 标签。 双击该值 bInvertHomeOffset 范围。 参数值从 FALSE 到 TRUE . " }, 
{ "title" : "更改操作模式 ", 
"url" : "_sm_light_driveconfiguration.html#UUID-6d14bc69-35ca-2d41-e329-ff9464a156cc_e9cbf584fcbb189dc0a864632dc38f79_id_83f3262801a6aa94c0a864630e7dcaee", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 驱动器配置 \/ 更改操作模式 ", 
"snippet" : "对于某些驱动器，您可以在特定条件下更改操作模式。理想情况下，驱动器应该能够切换操作模式，例如从 Profile position mode 到 Profile velocity mode ，即使正在执行运动。但是，某些驱动器在这种情况下表现不佳；其他人只有在未激活时才能切换操作模式（ MC_Power_SML.bRegulatorOn = FALSE ）。对于这些，您可以使用 SML_SetOpmode 即使在驱动器停用时，也可以设置操作模式的功能块。尽早测试驱动器的行为，以确定可以执行哪些任务以及应如何构建应用程序。...", 
"body" : "对于某些驱动器，您可以在特定条件下更改操作模式。理想情况下，驱动器应该能够切换操作模式，例如从 Profile position mode 到 Profile velocity mode ，即使正在执行运动。但是，某些驱动器在这种情况下表现不佳；其他人只有在未激活时才能切换操作模式（ MC_Power_SML.bRegulatorOn = FALSE ）。对于这些，您可以使用 SML_SetOpmode 即使在驱动器停用时，也可以设置操作模式的功能块。尽早测试驱动器的行为，以确定可以执行哪些任务以及应如何构建应用程序。 " }, 
{ "title" : "配置和调试 ", 
"url" : "_sm_light_config_and_startup.html", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 配置和调试 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CODESYS SoftMotion Light 配置在 CODESYS ", 
"url" : "_sm_light_config_and_startup.html#UUID-f3088292-f480-0701-8106-fce4ccd90ae0_efb79cbefcbbab10c0a864635602952d_id_8a00265cdf7f83dec0a8640e00a4507d", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 配置和调试 \/ CODESYS SoftMotion Light 配置在 CODESYS ", 
"snippet" : "将驱动设备添加到设备树中，例如您自己的 EtherCAT 从站或 CAN 从站设备。 在其下方，插入一个 CODESYS SoftMotion Light 轴。然后点击 项目 → 添加 SoftMotionLight CiA402 轴 . 在编辑器中打开添加的 EtherCAT 或 CAN 设备 ( 加速网 示例中的模块）。 配置 EtherCAT 设备或 CAN 设备的过程数据 (PDO)。 您应该组态过程数据，以便在发生更改时传送“状态字”和可选的“控制字”。如果控制字不是通过 PDO 传输的，那么一旦它发生变化，它就会通过 SDO 传输。对于模块化轴，您必须在使用时传输当前位置 MC_M...", 
"body" : "将驱动设备添加到设备树中，例如您自己的 EtherCAT 从站或 CAN 从站设备。 在其下方，插入一个 CODESYS SoftMotion Light 轴。然后点击 项目 → 添加 SoftMotionLight CiA402 轴 . 在编辑器中打开添加的 EtherCAT 或 CAN 设备 ( 加速网 示例中的模块）。 配置 EtherCAT 设备或 CAN 设备的过程数据 (PDO)。 您应该组态过程数据，以便在发生更改时传送“状态字”和可选的“控制字”。如果控制字不是通过 PDO 传输的，那么一旦它发生变化，它就会通过 SDO 传输。对于模块化轴，您必须在使用时传输当前位置 MC_MoveAbsolute_SML 或者 MC_MoveRelative_SML .您可以同步或在发生变化时传输当前位置。如果位置发生变化时传输，那么你应该配置一个合适的 抑制时间 以防止传播过于频繁。无需通过 PDO 传输其他对象。 EtherCAT 设备编辑器中的 PDO 配置示例： 切换到 EtherCAT I\/O 映射 标签。在 更新变量 , 选择 激活 2（始终在总线循环任务中） 选项。 切换到 一般的 标签。 对于 EtherCAT 驱动器，无需使用分布式时钟。但是，某些驱动器可能需要它们。 对于 CAN 驱动器，您应该激活心跳。或者，如果当前位置被传输，您可以激活 SYNC 报文。在这种情况下，不需要心跳。第三种选择是使用节点保护。对应的配置是在 一般的 CANopen 从站的选项卡。 如果 SYNC 报文、心跳和节点保护均未激活，则 无法确定驱动器是否处于“运行”状态。 打开 CODESYS SoftMotion Light 编辑器中的轴（ SML_Drive_GenericDSP402 在示例中）。 配置类似于 CODESYS SoftMotion Light 轴（参见 SoftMotion 设备编辑器的说明）。 设置以下参数 SoftMotionLight 标签： 常规设置 模数 ： 模值 [u] （模周期）开。 有限 速度斜坡类型 : 确定速度曲线。 梯形 ：导致梯形速度分布（每段加速度恒定） 辛² ：如果驱动器支持，此设置会导致 sin² 函数描述的速度曲线（具有恒定的加速度曲线）。 缩放 ：将增量设置为应用程序中的单位。 在这里，您定义转换整数位置值的因子 ( 增量 ) 转化为技术单位 ( 申请单位 ）。位置值由驱动器接收并发送到设备。技术单位由 IEC 程序使用。通过设置其他参数（ 电机旋转 , 齿轮输入旋转 , 齿轮输出转数 )，您还可以包括一个齿轮箱。 反转方向 ：使电机接收带有反转符号的预定义值，因此以相反的方向旋转。 切换到 EtherCAT I\/O 映射 EtherCAT 从站的选项卡。检查自动生成的映射 CODESYS SoftMotion Light 进程内存中的地址参数。在某些特殊情况下，可以手动调整此映射。 如果 自动映射 启用，然后自动映射 EtherCAT 从站的输入和输出。 " }, 
{ "title" : "调试 ", 
"url" : "_sm_light_config_and_startup.html#UUID-f3088292-f480-0701-8106-fce4ccd90ae0_index_3", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 配置和调试 \/ 调试 ", 
"snippet" : "在联机模式下，有关状态、通信和错误的信息显示在 SoftMotionLight 驱动器的选项卡。 为了支持调试，您可以使用 SML_StartupDrive 功能块（ SML_Basic.library ) 和 VISU_SML_StartupDrive 可视化模板（插入可视化的框架元素）。通过这种方式，您可以轻松访问大部分 CODESYS SoftMotion Light 函数，例如 Power , Home , MoveAbsolute , MoveRelative ， 和 MoveVelocity ，以及读写参数。...", 
"body" : "在联机模式下，有关状态、通信和错误的信息显示在 SoftMotionLight 驱动器的选项卡。 为了支持调试，您可以使用 SML_StartupDrive 功能块（ SML_Basic.library ) 和 VISU_SML_StartupDrive 可视化模板（插入可视化的框架元素）。通过这种方式，您可以轻松访问大部分 CODESYS SoftMotion Light 函数，例如 Power , Home , MoveAbsolute , MoveRelative ， 和 MoveVelocity ，以及读写参数。 " }, 
{ "title" : "兼容性检查 ", 
"url" : "_sm_light_comp_test.html", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 兼容性检查 ", 
"snippet" : "SML_CompatibilityCheck_DS402.project 项目可以帮助您检查您的驱动器是否适合与 0_Global: Product SoftMotionLight 一起使用。该项目位于 0_Global: Brand 的标准安装子目录 CODESYS\/CODESYS SoftMotion\/Examples\/SoftMotionLight 中。该项目包含一个从可视化创建的向导，可指导您完成不同的测试步骤。 测试项目可以使用免费试用版运行 CODESYS SoftMotion Light 它包含在 SoftMotion 包中。请注意使用驱动器的基本要求 CODESYS SoftM...", 
"body" : "SML_CompatibilityCheck_DS402.project 项目可以帮助您检查您的驱动器是否适合与 0_Global: Product SoftMotionLight 一起使用。该项目位于 0_Global: Brand 的标准安装子目录 CODESYS\/CODESYS SoftMotion\/Examples\/SoftMotionLight 中。该项目包含一个从可视化创建的向导，可指导您完成不同的测试步骤。 测试项目可以使用免费试用版运行 CODESYS SoftMotion Light 它包含在 SoftMotion 包中。请注意使用驱动器的基本要求 CODESYS SoftMotion Light . " }, 
{ "title" : "测试执行 ", 
"url" : "_sm_light_comp_test.html#UUID-cc2b5d09-9fde-8a58-a133-0f19747687da__sm_light_comp_test0", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 兼容性检查 \/ 测试执行 ", 
"snippet" : "打开项目 SML_CompatibilityCheck_DS402.project 并将包含的设备树部分（EtherCAT_Master、Accelnet EtherCAT-Panel、SM_Drive_ETC_GenericDSP402）替换为与您的硬件相对应的配置。该轴可以位于 EtherCAT 从站或 CAN 从站下方。 重要的 : 轴还是要命名的 驾驶 为了使测试程序正常工作。 在设备编辑器的对话框中，配置您的设备以使用 CODESYS SoftMotion Light .有关更多信息，请参阅： 配置和调试将项目连接到控制器（在线 - 登录）并启动它。 启动“ 主视觉 \" 可视化（双击...", 
"body" : "打开项目 SML_CompatibilityCheck_DS402.project 并将包含的设备树部分（EtherCAT_Master、Accelnet EtherCAT-Panel、SM_Drive_ETC_GenericDSP402）替换为与您的硬件相对应的配置。该轴可以位于 EtherCAT 从站或 CAN 从站下方。 重要的 : 轴还是要命名的 驾驶 为了使测试程序正常工作。 在设备编辑器的对话框中，配置您的设备以使用 CODESYS SoftMotion Light .有关更多信息，请参阅： 配置和调试将项目连接到控制器（在线 - 登录）并启动它。 启动“ 主视觉 \" 可视化（双击设备树中的项目）。 可视化从一个向导开始，引导您完成各个测试步骤。显示相应的说明、错误消息和解释。 最后，您将看到一个包含测试结果的页面，您将知道您的驱动器是否可以使用 CODESYS SoftMotion Light . " }, 
{ "title" : "命令：添加 SoftMotion CiA402 轴 ", 
"url" : "_sm_cmd_add_softmotion_cia402_axis.html", 
"breadcrumbs" : "CODESYS SoftMotion Light \/ 命令：添加 SoftMotion CiA402 轴 ", 
"snippet" : "添加 SoftMotion CiA402轴 功能 ：该命令添加了一个通用的 SoftMotion 设备树中现场总线从站下方的 CiA402 轴。 称呼 : 项目 菜单;设备树中设备对象的上下文菜单 要求 : 在设备树中，选择支持该驱动器的设备。示例：EtherCAT 从机或 CAN 驱动器的 ESI 文件包含它是 Cia402 轴的条目 ( ProfileNo 402 ）。 该命令会插入一个通用的 Cia402 轴。有关更多信息，请参阅以下内容： 通用 Cia402 轴的配置...", 
"body" : "添加 SoftMotion CiA402轴 功能 ：该命令添加了一个通用的 SoftMotion 设备树中现场总线从站下方的 CiA402 轴。 称呼 : 项目 菜单;设备树中设备对象的上下文菜单 要求 : 在设备树中，选择支持该驱动器的设备。示例：EtherCAT 从机或 CAN 驱动器的 ESI 文件包含它是 Cia402 轴的条目 ( ProfileNo 402 ）。 该命令会插入一个通用的 Cia402 轴。有关更多信息，请参阅以下内容： 通用 Cia402 轴的配置 " }
]
$(document).trigger('search.ready');
});