$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS PROFINET ", 
"url" : "_pnio_start_page.html", 
"breadcrumbs" : "CODESYS PROFINET \/ CODESYS PROFINET ", 
"snippet" : "PROFINET （Process Field Network）是一种工业以太网标准，广泛应用于制造和过程自动化领域。它由用户组织 PI（PROFIBUS&PROFINET International）管理，被认为是 PROFIBUS 的继承者（参见 https:\/\/www.profibus.com\/ ）。 有关现场总线支持的更多一般信息，请参见 CODESYS ， 看： 现场总线支持 您可以下载 CODESYS PROFINET 在里面 CODESYS Store International  或在 CODESYS Store North America ....", 
"body" : "PROFINET （Process Field Network）是一种工业以太网标准，广泛应用于制造和过程自动化领域。它由用户组织 PI（PROFIBUS&PROFINET International）管理，被认为是 PROFIBUS 的继承者（参见 https:\/\/www.profibus.com\/ ）。 有关现场总线支持的更多一般信息，请参见 CODESYS ， 看： 现场总线支持 您可以下载 CODESYS PROFINET 在里面 CODESYS Store International  或在 CODESYS Store North America . " }, 
{ "title" : "PROFINET 协议 ", 
"url" : "_pnio_f_profinet_protocol.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 协议 ", 
"snippet" : "PROFINET 使用基于 IEEE 802.3（以太网）的 PROFINET 用于循环实时 I\/O 通信的 RT 协议和通过 UDP\/IP 的 RPC（远程过程调用）用于非循环服务。任何种类或数量的网络拓扑都是可能的。该网络可以与其他协议（例如 TCP\/IP）并行使用。 DCP（发现和基本配置协议）是 PROFINET RT 用于设备扫描和设置站名或 IP 配置。通讯方式 PROFINET RT 和 DCP 不需要 IP 地址，而是直接使用以太网接口的 MAC 地址。...", 
"body" : "PROFINET 使用基于 IEEE 802.3（以太网）的 PROFINET 用于循环实时 I\/O 通信的 RT 协议和通过 UDP\/IP 的 RPC（远程过程调用）用于非循环服务。任何种类或数量的网络拓扑都是可能的。该网络可以与其他协议（例如 TCP\/IP）并行使用。 DCP（发现和基本配置协议）是 PROFINET RT 用于设备扫描和设置站名或 IP 配置。通讯方式 PROFINET RT 和 DCP 不需要 IP 地址，而是直接使用以太网接口的 MAC 地址。 " }, 
{ "title" : "功能性 ", 
"url" : "_pnio_protocol_fuctionality.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 协议 \/ 功能性 ", 
"snippet" : "一个 PROFINET 控制器为每个人打开一个单独的连接（AR = 应用程序关系） PROFINET 用于数据交换、参数化和诊断的设备。 这些设备由 PROFINET 站名。一个 PROFINET 设备由按插槽\/子插槽寻址的子模块构成。因此，例如具有以太网接口的通信模块为模块0，每个以太网端口包含接口子模块和多个端口子模块。插槽\/模块是子模块的容器，实际 IO 数据和参数（数据记录，通过索引寻址）分配到这些子模块。 在循环数据交换的情况下， PROFINET 遵循提供者-消费者模型。这意味着 IO 控制器和 IO 设备都各自独立地发送循环数据。对发送时钟进行相互监控。超过允许的限制将导致连接终...", 
"body" : "一个 PROFINET 控制器为每个人打开一个单独的连接（AR = 应用程序关系） PROFINET 用于数据交换、参数化和诊断的设备。 这些设备由 PROFINET 站名。一个 PROFINET 设备由按插槽\/子插槽寻址的子模块构成。因此，例如具有以太网接口的通信模块为模块0，每个以太网端口包含接口子模块和多个端口子模块。插槽\/模块是子模块的容器，实际 IO 数据和参数（数据记录，通过索引寻址）分配到这些子模块。 在循环数据交换的情况下， PROFINET 遵循提供者-消费者模型。这意味着 IO 控制器和 IO 设备都各自独立地发送循环数据。对发送时钟进行相互监控。超过允许的限制将导致连接终止。在每种情况下，与子模块的实际 IO 数据一起传输状态信息（提供者和消费者状态）。 一个 PROFINET 设备发送警报到 PROFINET 控制器通知中断的到来和去向。 PROFINET 为此定义了一个全面的诊断模型，其中包括例如硬件缺陷（断线）、网络中断或特定于设备的事件。 非循环服务（通过 UDP\/IP 的 DCE RPC）用于传输配置数据、资产数据和诊断数据。 " }, 
{ "title" : "建立连接 ", 
"url" : "_pnio_protocol_connection.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 协议 \/ 建立连接 ", 
"snippet" : "通过几个步骤建立连接 通过 DCP 识别请求，控制器扫描网络以查找 PROFINET 具有已定义站名的设备。 控制器使用 DCP set 命令设置所需的 IP 地址 PROFINET 设备。 控制器向设备发送连接请求（RPC 协议）。该请求包含控制器想要与之交换数据的子模块列表。 这 PROFINET 设备将预期子模块列表与实际可用子模块进行比较。在出现偏差的情况下，连接响应包含带有不匹配模块的“Module-Diff-Block”。 控制器传输子模块的配置参数\/设置。 这 PROFINET 设备在完整传输到内部逻辑（设备应用程序）和子模块的硬件后应用参数化。配置完成后， PROFINET 设...", 
"body" : "通过几个步骤建立连接 通过 DCP 识别请求，控制器扫描网络以查找 PROFINET 具有已定义站名的设备。 控制器使用 DCP set 命令设置所需的 IP 地址 PROFINET 设备。 控制器向设备发送连接请求（RPC 协议）。该请求包含控制器想要与之交换数据的子模块列表。 这 PROFINET 设备将预期子模块列表与实际可用子模块进行比较。在出现偏差的情况下，连接响应包含带有不匹配模块的“Module-Diff-Block”。 控制器传输子模块的配置参数\/设置。 这 PROFINET 设备在完整传输到内部逻辑（设备应用程序）和子模块的硬件后应用参数化。配置完成后， PROFINET 设备使用应用程序就绪请求向控制器报告数据交换的就绪情况。 如果相应的子模块没有故障，两个参与者都将传输的 IO 数据的状态切换为有效。 " }, 
{ "title" : "PROFINET 诊断 ", 
"url" : "_pnio_f_profinet_diagnosis.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 ", 
"snippet" : "本章描述了诊断机制如何从 PROFINET 可用于 CODESYS . 系统相关故障（例如，由防火墙引起）的检测和纠正在 故障排除 章节。 为了防止工厂运行期间的停机，诊断旨在允许快速检测甚至预防故障。去做这个， PROFINET 提供广泛的诊断机制，提供有关故障来源和位置的信息。因此，可以将设备或模块甚至特定的 I\/O 通道识别为故障的触发器。诊断提供有关错误严重性的附加信息以及有关原因的详细信息。...", 
"body" : "本章描述了诊断机制如何从 PROFINET 可用于 CODESYS . 系统相关故障（例如，由防火墙引起）的检测和纠正在 故障排除 章节。 为了防止工厂运行期间的停机，诊断旨在允许快速检测甚至预防故障。去做这个， PROFINET 提供广泛的诊断机制，提供有关故障来源和位置的信息。因此，可以将设备或模块甚至特定的 I\/O 通道识别为故障的触发器。诊断提供有关错误严重性的附加信息以及有关原因的详细信息。 " }, 
{ "title" : "诊断数据库 ", 
"url" : "_pnio_diagnosis_data_base.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 \/ 诊断数据库 ", 
"snippet" : "发生的每一个错误 PROFINET 设备（例如，“断线”或“电涌”类型）存储在本地诊断数据库中 PROFINET 设备。当错误原因得到纠正时，错误也会从那里再次删除。该诊断存储器中的条目可随时通过非循环服务读取。这可以通过两个来完成 PROFINET 控制器和不与控制器交换数据的“主管”工具 PROFINET 设备。 诊断信息存在两种不同的变体，因此 USI 格式应仅在特殊情况下使用。如果没有相关的 GSDML 文件，则无法评估该格式。 GSDML 文件包含属于单个设备和 USI 的信息。标准格式基本上包括以下内容： 通道错误类型： 主要错误类型。按照标准的预定义，通常的错误类型是例如 1 =...", 
"body" : "发生的每一个错误 PROFINET 设备（例如，“断线”或“电涌”类型）存储在本地诊断数据库中 PROFINET 设备。当错误原因得到纠正时，错误也会从那里再次删除。该诊断存储器中的条目可随时通过非循环服务读取。这可以通过两个来完成 PROFINET 控制器和不与控制器交换数据的“主管”工具 PROFINET 设备。 诊断信息存在两种不同的变体，因此 USI 格式应仅在特殊情况下使用。如果没有相关的 GSDML 文件，则无法评估该格式。 GSDML 文件包含属于单个设备和 USI 的信息。标准格式基本上包括以下内容： 通道错误类型： 主要错误类型。按照标准的预定义，通常的错误类型是例如 1 =“短路”。 有关更多信息，请参阅： ProfinetCommon.ChannelErrorType ExtChannelErrorType（可选）： 有关主要错误的详细信息。值取决于主要错误。 " }, 
{ "title" : "警报 ", 
"url" : "_pnio_diagnosis_alarms.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 \/ 警报 ", 
"snippet" : "在更改诊断数据库条目的情况下， PROFINET 设备发送警报到 PROFINET 控制器。这会立即发出故障发生或发生的信号。报警包含源（槽、子槽、通道）以及诊断信息。 除诊断报警外，还有与诊断条目无关的“PULL”\/“PLUG”报警（如拔出或插入模块时触发PLUG报警）。...", 
"body" : "在更改诊断数据库条目的情况下， PROFINET 设备发送警报到 PROFINET 控制器。这会立即发出故障发生或发生的信号。报警包含源（槽、子槽、通道）以及诊断信息。 除诊断报警外，还有与诊断条目无关的“PULL”\/“PLUG”报警（如拔出或插入模块时触发PLUG报警）。 " }, 
{ "title" : "I\/O 数据的有效性 ", 
"url" : "_pnio_diagnosis_validities_io_data.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 \/ I\/O 数据的有效性 ", 
"snippet" : "对于传入和传出数据， PROFINET 设备（控制器和设备）以子模块粒度形式发送状态字节，将 I\/O 数据标记为有效或无效。从应用程序的角度来看，这个提供者\/消费者状态最终指定了子模块的数据是否有效。消费者状态被理解为确认发送的数据已经被接收者接收。 IO PS\/CS“BAD”的原因可能如下： 不与设备进行数据交换 模块缺失或出现故障...", 
"body" : "对于传入和传出数据， PROFINET 设备（控制器和设备）以子模块粒度形式发送状态字节，将 I\/O 数据标记为有效或无效。从应用程序的角度来看，这个提供者\/消费者状态最终指定了子模块的数据是否有效。消费者状态被理解为确认发送的数据已经被接收者接收。 IO PS\/CS“BAD”的原因可能如下： 不与设备进行数据交换 模块缺失或出现故障 " }, 
{ "title" : "模块\/子模块状态 ", 
"url" : "_pnio_diagnosis_module_submodule_state.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 \/ 模块\/子模块状态 ", 
"snippet" : "这 SubmoduleState 是一个状态字，指示每个单独的子模块是否存在诊断条目或其他故障，例如配置损坏。 这样，当与设备建立连接时，控制器还会发送它将用于数据交换的模块和子模块的列表。如果设备的现有模块与控制器投射的模块之间的指定\/实际状态不同或存在诊断，则相应地在状态中设置标志。...", 
"body" : "这 SubmoduleState 是一个状态字，指示每个单独的子模块是否存在诊断条目或其他故障，例如配置损坏。 这样，当与设备建立连接时，控制器还会发送它将用于数据交换的模块和子模块的列表。如果设备的现有模块与控制器投射的模块之间的指定\/实际状态不同或存在诊断，则相应地在状态中设置标志。 " }, 
{ "title" : "PNIO 状态（错误代码） ", 
"url" : "_pnio_diagnosis_pnio_state.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 \/ PNIO 状态（错误代码） ", 
"snippet" : "这 PNIOStatus 是一个 8 位十六进制代码，它不属于 PROFINET 真正意义上的诊断。这 PNIOStatus 是失败服务的错误\/中止代码，例如在日志错误或连接尝试失败的情况下发出。用户通常只在非循环读\/写服务（ RDREC \/ WRREC ) 或与设备建立连接。 该值被解释为具有以下元素的 4 字节数组： ErrorCode 0x40 编码系统 CODESYS - 特定错误，请参阅： CommFB.ErrorCode 0x81 PNIO 此处未另行说明的错误 0xCF RTA 错误 错误，连接终止 0xDA 警报确认 报警处理错误 0xDB IODConnectRes (RPC...", 
"body" : "这 PNIOStatus 是一个 8 位十六进制代码，它不属于 PROFINET 真正意义上的诊断。这 PNIOStatus 是失败服务的错误\/中止代码，例如在日志错误或连接尝试失败的情况下发出。用户通常只在非循环读\/写服务（ RDREC \/ WRREC ) 或与设备建立连接。 该值被解释为具有以下元素的 4 字节数组： ErrorCode 0x40 编码系统 CODESYS - 特定错误，请参阅： CommFB.ErrorCode 0x81 PNIO 此处未另行说明的错误 0xCF RTA 错误 错误，连接终止 0xDA 警报确认 报警处理错误 0xDB IODConnectRes (RPC-PDU) 0xDC IODR 释放资源 (RPC-PDU) 0xDD IOD 控制资源 IOXControlRes (RPC-PDU) 0xDE IODReadRes 非循环读取错误（RPC，仅在 ErrorDecode=PNIORW 时） 0xDF IODWriteRes 非循环写入错误（RPC，仅在 ErrorDecode=PNIORW 时） ErrorDecode 0x80 PNIORW 在非循环读取中的错误上下文中使用。等效于 IEC 61158-6-3 (DPV1)。 0x81 PNIO 在剩余服务或内部错误（如 RPC 错误）的上下文中。 ErrorCode1 的价值 ErrorCode1 （见表） ErrorCode2 的价值 ErrorCode2 （见表） 错误代码1 为了 ErrorDecode = PNIORW，见 CommFB.ErrorCode_RW . 为了 ErrorDecode = PNIO 0x01–0x0D 连接参数错误 0x14–0x38 其他 PDU 相关错误 0x3D 设备协议机 0x3E 控制器协议机 0x3F 用于发现、IP 和名称分配的控制器协议机器 0x40–0xD3 其他状态机错误 0xFD 协议错误：中止原因 见表 ErrorCode2 错误代码2 为了 ErrorDecode = PNIO 和 ErrorCode1 = 0xFD 0x05 AR消费者DHT过期 0x06 AR CMI 超时 0x0B AR alarm.ind（错误） 0x0D AR abort.req 0x20 DCP，恢复出厂设置或恢复出厂设置 0x28 远程应用程序就绪超时已过期 ErrorCode1 和 ErrorCode2 的列表不完整，仅显示最重要的错误代码。 例子 0x81813F02 DCP 没有 RealStationname 未找到具有指定站名的设备。 0x81813F03 DCP 多个 RealStationName 找到多个具有相同站名的设备。 0x81813F06 DCP 设置错误 DCP 设置命令失败（例如，IP 地址或站名）。 0x81813F07 ARP多个IP地址 IP 地址被多次分配：网络错误。 0xCF81FD05 AR消费者DHT过期 无法维持发送时钟：连接终止。 " }, 
{ "title" : "常问问题 ", 
"url" : "_pnio_diagnosis_faq.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 诊断 \/ 常问问题 ", 
"snippet" : "问题 回答 当一个 PROFINET 设备或模块标记为红色（错误），这会影响其他设备或模块吗？ 不会。它们在数据交换期间不受影响。 当我重置或重新启动应用程序时，现场设备中的诊断是否被删除？ 这会有所不同：硬件问题并不能由此解决，但参数设置错误导致的错误却可以解决。 控制器可以删除或确认诊断 PROFINET 设备？ 不， PROFINET 设备管理诊断条目并设置模块的状态。这 PROFINET 控制器仅在日志级别确认收到传入警报。...", 
"body" : "问题 回答 当一个 PROFINET 设备或模块标记为红色（错误），这会影响其他设备或模块吗？ 不会。它们在数据交换期间不受影响。 当我重置或重新启动应用程序时，现场设备中的诊断是否被删除？ 这会有所不同：硬件问题并不能由此解决，但参数设置错误导致的错误却可以解决。 控制器可以删除或确认诊断 PROFINET 设备？ 不， PROFINET 设备管理诊断条目并设置模块的状态。这 PROFINET 控制器仅在日志级别确认收到传入警报。 " }, 
{ "title" : "PROFINET 控制器 ", 
"url" : "_pnio_f_master.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "一般的 ", 
"url" : "_pnio_f_master_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 一般的 ", 
"snippet" : "的配置 PROFINET 控制器由控制器和 PROFINET 插入其下方的设备（从站）。设备由控制器配置并与之交换数据。 CODESYS 提供两种不同的 PROFINET 控制器： 一种变体，特别适用于 Hilscher CIFX-Karten 一种独立于硬件的变体， CODESYS PROFINET 控制器。此变体可在任意数量的以太网适配器上运行。 插入基于以太网的控制器时，会隐式创建两个任务，这些任务是 PROFINET 通讯栈。 Profinet_CommunicationTask ：此任务包括非循环通信服务，例如建立连接和诊断。由于实时需求非常弱，这些服务对时间要求不高。因此该任务是低...", 
"body" : "的配置 PROFINET 控制器由控制器和 PROFINET 插入其下方的设备（从站）。设备由控制器配置并与之交换数据。 CODESYS 提供两种不同的 PROFINET 控制器： 一种变体，特别适用于 Hilscher CIFX-Karten 一种独立于硬件的变体， CODESYS PROFINET 控制器。此变体可在任意数量的以太网适配器上运行。 插入基于以太网的控制器时，会隐式创建两个任务，这些任务是 PROFINET 通讯栈。 Profinet_CommunicationTask ：此任务包括非循环通信服务，例如建立连接和诊断。由于实时需求非常弱，这些服务对时间要求不高。因此该任务是低优先级的。 Profinet_IOTask : 这才是真正的 PROFINET 实时数据交换发生。在每个周期中处理待处理的 IO 数据包（请参阅从站配置器： 发送时钟 ）。因此，需要 1ms 的周期时间（对于 1ms 发送时钟）。 如果此控制器的从机的最小选定发送器间隔为 2ms、4ms 或更大，则也可以选择 2ms 或 4ms 的循环时间。但是，应该选择尽可能高的任务优先级。 (1) 控制器 – NetX 配置(2) 设备 - 常规(3) 模块 - 通用(4) 以太网适配器 (5) 控制器 - 一般为了在读\/写时以最小的延迟获得最大的 IO 性能，可以在此任务中更新 IO 数据（→ 插入自己的 POU 来更新此任务中的 IO）。 IO 任务中不应执行阻塞或持久化操作，例如可视化或文件访问。如果任务阻塞时间过长，则看门狗取消与从机通信的连接。 我们建议您激活 在停止时刷新 I\/O PLC 设置中的选项。否则，当应用程序在断点处停止时，通信将被取消。 通过扫描功能，您可以轻松确定当前的硬件结构并传输到设备树。 " }, 
{ "title" : "安装和插入 PROFINET 设备 ", 
"url" : "_pnio_f_master_general.html#UUID-d0de8a6e-6453-b5b7-171f-672b1c09a78d_section-idm4664815593304032609752027914", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 一般的 \/ 安装和插入 PROFINET 设备 ", 
"snippet" : "为了让您插入和配置 PROFINET 设备作为项目设备树中的对象，首先必须在本地系统上安装 IO 控制器、I\/O 设备和 IO 模块。如果当前的编程系统安装没有自动发生这种情况，那么您必须在设备存储库对话框中明确执行此操作。与硬件一起提供的 GSDML 设备描述文件是此操作的基础。 在设备树中，插入一个 PROFINET 控制器位于具有 PLC 逻辑节点的设备下方。设备描述文件 PROFINET 控制器定义了哪个 PROFINET 您可以在其下方插入的设备。另一方面，IO 设备的描述定义了哪个 PROFINET 可插入 IO 设备下方的模块。对于位置固定的 IO 模块， CODESYS 自动在...", 
"body" : "为了让您插入和配置 PROFINET 设备作为项目设备树中的对象，首先必须在本地系统上安装 IO 控制器、I\/O 设备和 IO 模块。如果当前的编程系统安装没有自动发生这种情况，那么您必须在设备存储库对话框中明确执行此操作。与硬件一起提供的 GSDML 设备描述文件是此操作的基础。 在设备树中，插入一个 PROFINET 控制器位于具有 PLC 逻辑节点的设备下方。设备描述文件 PROFINET 控制器定义了哪个 PROFINET 您可以在其下方插入的设备。另一方面，IO 设备的描述定义了哪个 PROFINET 可插入 IO 设备下方的模块。对于位置固定的 IO 模块， CODESYS 自动在设备树中提供插槽。这 添加设备 命令用于插入设备。请注意，也可以暂时停用设备以进行网络操作。 " }, 
{ "title" : "配置 ", 
"url" : "_pnio_f_master_configuration.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 " }, 
{ "title" : "控制器 - 一般 ", 
"url" : "_pnio_edt_controller_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 控制器 - 一般 ", 
"snippet" : "目的： PROFINET 控制器 这 PROFINET 控制器和从站一样，由站名标识。对于 CIFX 变体，您还可以在此处配置 IP 设置。否则，将从上级以太网节点应用设置。 站名 设备的站名。它用于网络中设备的唯一标识。 IP参数 IP地址 注意：仅适用于 CIFX PROFINET。 如果将控制器插入以太网适配器下方，则必须在以太网适配器的对话框中定义 IP 参数。 子网掩码 设备使用的子网掩码。 默认网关 设备使用的默认网关。 默认从站 IP 参数 第一个 IP 地址 IP 地址范围 CODESYS 插入时默认使用 PROFINET 设备进入设备树。如果您使用 自动IP 扫描对话框中的功...", 
"body" : "目的： PROFINET 控制器 这 PROFINET 控制器和从站一样，由站名标识。对于 CIFX 变体，您还可以在此处配置 IP 设置。否则，将从上级以太网节点应用设置。 站名 设备的站名。它用于网络中设备的唯一标识。 IP参数 IP地址 注意：仅适用于 CIFX PROFINET。 如果将控制器插入以太网适配器下方，则必须在以太网适配器的对话框中定义 IP 参数。 子网掩码 设备使用的子网掩码。 默认网关 设备使用的默认网关。 默认从站 IP 参数 第一个 IP 地址 IP 地址范围 CODESYS 插入时默认使用 PROFINET 设备进入设备树。如果您使用 自动IP 扫描对话框中的功能，则该范围内的 IP 地址也将被使用。此处选择下一个空闲 IP 地址。 最后一个 IP 地址 子网掩码 新添加的子网掩码 PROFINET 设备。 默认网关 新添加的默认网关 PROFINET 设备。 IO 提供者\/消费者状态 应用程序停止 -> 替换值 当用户停止应用程序时，控制器发送的输出数据的提供者状态被设置为“BAD”。然后从站将输入和输出设置为预定义的替代值。欲了解更多信息，请参阅“ CODESYS 默认值 - PROFINET 本章末尾的替代值”。 添加到 I\/O 映射 ：传入的状态信息被添加到所有模块的I\/O映射中；输入数据的提供者状态和输出数据的消费者状态。 替换输入数据 零 最后一个有效值 如果设备不提供有效的输入数据，则可以选择重置本地控制器应用程序中的值 (%I) 或保留其最后的有效值 端口数据 对等站\/端口 具有连接到此端口的端口的相邻设备。 您可以在 PROFINET 控制器拓扑 标签。 检查电缆长度 网线长度（米） < 10 < 25 < 50 < 100 指定电缆长度时，在控制器上电时进行检查。不正确的电缆长度会导致错误消息。 传输速率 连接的传输速率 禁用固定速率\/自动协商 ：传输速率固定，自动检测（自动协商）禁用。 DCP边界 ：DCP 组播消息（ Identify , Hello ) 不予转发。 点对点边界 ：不发送 LLDP 消息。 禁用端口 ：以太网端口完全禁用。 看门狗 启用 注意：仅适用于 CIFX PROFINET ：如果在给定时间内未设置 CIFX 固件（例如，在应用程序中出现异常错误的情况下），则将其重置。连接终止，从站切换到它们的替代值。 看门狗的默认值源自设备描述。 CODESYS 默认值 - PROFINET 替代值 PROFINET 发生中断时，设备将其输入和输出设置为预定义的替代值。与默认值相比，这些值在现场设备中定义。这些值通常为“0”，但也可以根据设备配置特定的替代值。 在以下情况下设置替代值： 连接中断。 控制器将传入数据的提供者状态设置为“BAD”。 发生其他中断（例如，主机应用程序异常、参数化错误） 如果 应用程序停止 --> 替换值 选项已启用，然后控制器在应用程序停止时将提供程序状态设置为“BAD”。在这种情况下，从站设置它们的替代值。来自控制器的所有传入数据都将被忽略（包括默认值）。 如果应为应用程序停止设置应用程序中定义的默认值，则必须禁用此选项。此外，您应该选择 停止时更新 IO 选项（在 PLC 设置 ）。否则，该 CODESYS PROFINET 控制器停止。 " }, 
{ "title" : "控制器 - 概述 ", 
"url" : "_pnio_edt_controller_overview.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 控制器 - 概述 ", 
"snippet" : "目的： PROFINET 控制器 此选项卡显示所有设备及其通信设置的概览。站名、IP 配置以及为此配置的所有设备的传输速度 PROFINET 控制器可以在列表中集中管理。 （可以多选。） 默认 IP 将所选设备的 IP 地址设置为标准地址范围内的值。该范围在控制器的设置中定义。 该命令在所选行的上下文菜单中也可用。 输入输出性能 打开 通讯设置 对话。这里是为所有选定设备配置 I\/O 数据传输速度的地方。对于单个参数 ( RT类 , 发送时钟 , 减速比 )，可以选择对所有选定设备都有效的值范围。 该命令在所选行的上下文菜单中也可用。 通讯设置 对话 发送时钟（毫秒） 发送时钟（以毫秒为单位）...", 
"body" : "目的： PROFINET 控制器 此选项卡显示所有设备及其通信设置的概览。站名、IP 配置以及为此配置的所有设备的传输速度 PROFINET 控制器可以在列表中集中管理。 （可以多选。） 默认 IP 将所选设备的 IP 地址设置为标准地址范围内的值。该范围在控制器的设置中定义。 该命令在所选行的上下文菜单中也可用。 输入输出性能 打开 通讯设置 对话。这里是为所有选定设备配置 I\/O 数据传输速度的地方。对于单个参数 ( RT类 , 发送时钟 , 减速比 )，可以选择对所有选定设备都有效的值范围。 该命令在所选行的上下文菜单中也可用。 通讯设置 对话 发送时钟（毫秒） 发送时钟（以毫秒为单位）。 减速比 比例因子 发送周期定义为 发送时钟 * 减速比 .因此，一个 发送时钟 1ms和一个 减速比 of 4 表示每 4ms 发送 IO 数据。 阶段 带一个 减速比 的 n ，发送周期分为阶段 1 到 n（其中数据仅在一个阶段发送）。您可以确定在哪个阶段发送数据以进行负载分配。 如果 发送时钟 = 1 和 减速比 = 4（如上例），那么您可以配置阶段 1-4。对于具有此发送时钟和减速比设置的四个从机，您可以将四个相位之一分配给四个从机中的每一个。这样，在发送周期的四个阶段中，每个阶段只发送一个数据包，负载平均分配。 如果没有配置相位，则控制器在考虑负载均衡分布（以太网帧\/PLC 周期）的情况下选择相位。 看门狗（毫秒） 监测时间。发送周期的倍数（发送周期 = 发送时钟 * 减速比 ）。可能的值：3 毫秒 – 1920 毫秒。 当控制器或 PROFINET 设备在此时间段内未收到来自通信对端的 IO 数据。设备进入故障模式并将输出切换为替代值。 VLAN ID VLAN 标识符：VLAN 类型 802.1Q 的 0 到 4095 之间的数字。 注意：对于符合以下要求的较新设备 PROFINET 规范 V2.3，仍然只允许“0”。 RT类 如果可用，您可以从列表中选择所需的 RT 类（实时通信）。 " }, 
{ "title" : "控制器 - 拓扑 ", 
"url" : "_pnio_edt_controller_topology.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 控制器 - 拓扑 ", 
"snippet" : "目的： PROFINET 控制器 此选项卡提供了一个拓扑的概述 PROFINET 每个人的网络和邻里\/对等信息 PROFINET 设备。 PROFINET 设备可以通过以太网端口识别连接的邻居\/对等设备（站名和端口号）。可以读取和配置此信息（实际值和预计值）。以太网网络的整个拓扑可以从这个邻域\/对等信息中创建。例如，可选的拓扑配置可用于设备更换或标准机械的调试。 左侧显示投影数据，右侧检索并导入实际拓扑以进行比较。偏离的端口互连被突出显示。 为了读取拓扑信息，必须事先设置一个有效的 IP 地址。见 自动IP 命令。 仅适用于支持 LLDP 的设备（例如：CC B）和符合 Profinet V2...", 
"body" : "目的： PROFINET 控制器 此选项卡提供了一个拓扑的概述 PROFINET 每个人的网络和邻里\/对等信息 PROFINET 设备。 PROFINET 设备可以通过以太网端口识别连接的邻居\/对等设备（站名和端口号）。可以读取和配置此信息（实际值和预计值）。以太网网络的整个拓扑可以从这个邻域\/对等信息中创建。例如，可选的拓扑配置可用于设备更换或标准机械的调试。 左侧显示投影数据，右侧检索并导入实际拓扑以进行比较。偏离的端口互连被突出显示。 为了读取拓扑信息，必须事先设置一个有效的 IP 地址。见 自动IP 命令。 仅适用于支持 LLDP 的设备（例如：CC B）和符合 Profinet V2.3 标准的所有新设备 如果邻居\/对等信息已配置为 PROFINET 设备（或控制器），然后不断检查这些，当检测到与设定状态有偏差时，会生成相应的诊断条目。 以树形视图查看设备及其端口互连 以列表形式查看设备及其端口互连 港口 本地端口号（从1开始） 邻居 相邻设备的设备名称和端口 单击这些字段会打开一个设备视图，其中选择了连接的端口。 邻港 我是 获取设备的 I&M 数据（识别和维护）并在对话框中查看 自动IP 如果设备扫描的地址无效，则自动设置网络内的有效 IP 地址（主站的网络设置）。 <– 接受\/导入项目中所选设备的邻域信息（在线）。 重启 将所选设备的设备设置重置为默认值 闪烁 LED 要通过硬件识别列出的设备，请选择该设备并单击 闪烁 LED 按钮。设备应通过闪烁响应。 提名 CODESYS 尝试设置为所选从站指定的站名和 IP 地址。 港口国 可能的状态： : 未知或未连接 ： 行 ： 错误 IP地址 设置从机的IP地址 子网掩码 设置从机的子网掩码 线路延迟 线路延迟（以纳秒为单位）。推荐值：1米电缆6ns " }, 
{ "title" : "控制器 - 媒体冗余 ", 
"url" : "_pnio_edt_mrp.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 控制器 - 媒体冗余 ", 
"snippet" : "目的： PROFINET 控制器 此选项卡用于配置介质冗余协议 (MRP) PROFINET 由此寻址的设备 PROFINET 控制器。 <组名> 使能够 ：激活 MRP 域 MRP域 MRP 环配置的名称 设备 设备树中的设备名称或相应功能块的名称 站名 设备的站名 物料需求计划实例 MRP 环的索引（自动分配）。一些设备支持参与多个 MRP 域。 物料需求计划角色 设备在 MRP 环中的作用 离开 客户 经理 经理_汽车 环端口 1 环端口 2 属于 MRP 环的环的端口。相邻端口显示在括号中。 有关更多信息，请参阅： 介质冗余 (MRP)...", 
"body" : "目的： PROFINET 控制器 此选项卡用于配置介质冗余协议 (MRP) PROFINET 由此寻址的设备 PROFINET 控制器。 <组名> 使能够 ：激活 MRP 域 MRP域 MRP 环配置的名称 设备 设备树中的设备名称或相应功能块的名称 站名 设备的站名 物料需求计划实例 MRP 环的索引（自动分配）。一些设备支持参与多个 MRP 域。 物料需求计划角色 设备在 MRP 环中的作用 离开 客户 经理 经理_汽车 环端口 1 环端口 2 属于 MRP 环的环的端口。相邻端口显示在括号中。 有关更多信息，请参阅： 介质冗余 (MRP)" }, 
{ "title" : "控制器 – NetX 配置 ", 
"url" : "_pnio_edt_controller_netx.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 控制器 – NetX 配置 ", 
"snippet" : "目的： PROFINET 控制器 作为一般的替代品 PROFINET 节点，您可以添加 PROFINET 在 NetX 现场总线的情况下，节点 (NetX) 到设备树。为该节点提供了设备编辑器中的 NetX 配置对话框，用于选择 NetX 芯片（适配器插槽）和该芯片上的通信通道。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 NetX 设置 投币口 要使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 要在所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化...", 
"body" : "目的： PROFINET 控制器 作为一般的替代品 PROFINET 节点，您可以添加 PROFINET 在 NetX 现场总线的情况下，节点 (NetX) 到设备树。为该节点提供了设备编辑器中的 NetX 配置对话框，用于选择 NetX 芯片（适配器插槽）和该芯片上的通信通道。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 NetX 设置 投币口 要使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 要在所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：提示用户在下载或重置时是否应重新初始化总线。重新初始化会中断总线并可能导致机器出现意外行为。 " }, 
{ "title" : "控制器 - 状态 ", 
"url" : "_pnio_edt_controller_status.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 控制器 - 状态 ", 
"snippet" : "目的： PROFINET 控制器 该选项卡显示控制器的当前状态，例如在 控制器状态 场上电的阶段。 中的数据 以太网统计 可用于诊断以太网配置。 有关更多信息，请参阅： 设备配置器中的状态对话框...", 
"body" : "目的： PROFINET 控制器 该选项卡显示控制器的当前状态，例如在 控制器状态 场上电的阶段。 中的数据 以太网统计 可用于诊断以太网配置。 有关更多信息，请参阅： 设备配置器中的状态对话框" }, 
{ "title" : "设备 - 常规 ", 
"url" : "_pnio_edt_device_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 设备 - 常规 ", 
"snippet" : "目的： PROFINET 设备 在此对话框中，您可以组态一个通信链接 ( PROFINET : 应用关系) 到 a PROFINET 现场设备。 对于当前对话框中的所有设置，设备描述确定此处的值是否可编辑以及预定义或可能的值。 站名 设备的站名。它用于网络中设备的唯一标识。 车站状态 32 位错误代码符合 PROFINET 规格。如果出现错误，此处会提供状态，例如，当建立连接失败或链路中断时。还会显示说明。 IP参数 IP地址 设备的 IP 设置。在建立与控制器的连接时设置。 子网掩码 设备使用的子网掩码。 默认网关 设备使用的默认网关。 通讯设置 发送时钟（毫秒） 发送时钟（以毫秒为单位）。...", 
"body" : "目的： PROFINET 设备 在此对话框中，您可以组态一个通信链接 ( PROFINET : 应用关系) 到 a PROFINET 现场设备。 对于当前对话框中的所有设置，设备描述确定此处的值是否可编辑以及预定义或可能的值。 站名 设备的站名。它用于网络中设备的唯一标识。 车站状态 32 位错误代码符合 PROFINET 规格。如果出现错误，此处会提供状态，例如，当建立连接失败或链路中断时。还会显示说明。 IP参数 IP地址 设备的 IP 设置。在建立与控制器的连接时设置。 子网掩码 设备使用的子网掩码。 默认网关 设备使用的默认网关。 通讯设置 发送时钟（毫秒） 发送时钟（以毫秒为单位）。 减速比 比例因子 发送周期定义为 发送时钟 * 减速比 .因此，一个 发送时钟 1ms和一个 减速比 of 4 表示每 4ms 发送 IO 数据。 阶段 带一个 减速比 的 n ，发送周期分为阶段 1 到 n（其中数据仅在一个阶段发送）。您可以确定在哪个阶段发送数据以进行负载分配。 如果 发送时钟 = 1 和 减速比 = 4（如上例），那么您可以配置阶段 1-4。对于具有此发送时钟和减速比设置的四个从机，您可以将四个相位之一分配给四个从机中的每一个。这样，在发送周期的四个阶段中，每个阶段只发送一个数据包，负载平均分配。 看门狗（毫秒） 监测时间。发送周期的倍数（发送周期 = 发送时钟 * 减速比 ）。可能的值：3 毫秒 – 1920 毫秒。 当控制器或 PROFINET 设备在此时间段内未收到来自通信对端的 IO 数据。设备进入故障模式并将输出切换为替代值。 VLAN ID VLAN 标识符：VLAN 类型 802.1Q 的 0 到 4095 之间的数字。 注意：对于符合以下要求的较新设备 PROFINET 规范 V2.3，仍然只允许“0”。 RT类 如果可用，您可以从列表中选择所需的 RT 类（实时通信）。 用户参数 设置所有默认值 CODESYS 将 GSDML 文件中的所有设置重置为默认值（请参阅“默认值”列）。 读取所有值 CODESYS 从设备读取当前值并在编辑器中更新它们。 写入所有值 CODESYS 将当前值从编辑器写入 IO 设备。并非所有 IO 设备都支持运行模式下的参数更新。如果不是，则显示错误消息。 选项 快速启动 在不更改设备配置的情况下，此功能可以显着减少设备的启动时间。在最佳条件下，从与网络建立连接的那一刻到进行数据交换，只需几百毫秒。如果可能，应关闭“自动协商”。 共享设备 ：该设备由另一个控制器配置。必须通过设置此选项来停用其他控制器使用的模块。 " }, 
{ "title" : "设备 – 端口数据 ", 
"url" : "_pnio_edt_device_options.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 设备 – 端口数据 ", 
"snippet" : "目的： PROFINET 设备 在该选项卡上，您可以定义端口配置以及相邻设备和连接电缆 共享设备 ：此设备由另一个控制器配置。其他控制器使用的模块必须通过设置此选项来禁用。 对等站\/端口 具有连接到此端口的端口的相邻设备。 您可以在 PROFINET 控制器拓扑 标签。 电缆长度 网线长度（米） < 10 < 25 < 50 < 100 指定电缆长度时，在控制器上电时进行检查。不正确的电缆长度会导致错误消息。 月活类型 网线类型 铜 光纤 指定电缆类型时，在控制器上电时进行检查。不正确的电缆类型会导致错误消息。...", 
"body" : "目的： PROFINET 设备 在该选项卡上，您可以定义端口配置以及相邻设备和连接电缆 共享设备 ：此设备由另一个控制器配置。其他控制器使用的模块必须通过设置此选项来禁用。 对等站\/端口 具有连接到此端口的端口的相邻设备。 您可以在 PROFINET 控制器拓扑 标签。 电缆长度 网线长度（米） < 10 < 25 < 50 < 100 指定电缆长度时，在控制器上电时进行检查。不正确的电缆长度会导致错误消息。 月活类型 网线类型 铜 光纤 指定电缆类型时，在控制器上电时进行检查。不正确的电缆类型会导致错误消息。 " }, 
{ "title" : "设备 – IOxS ", 
"url" : "_pnio_edt_device_ioxs.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 设备 – IOxS ", 
"snippet" : "目的： PROFINET 设备 在此对话框中，您可以启用或禁用各个子模块的 I\/O 提供者数据或 I\/O 使用者状态数据。因此，状态字节也映射到 I\/O 映射中。但是，建议在控制器上进行全局设置。 有关更多信息，请参阅： IO 提供者\/消费者状态 除了实际的输入和输出数据，PROFINET 还发送状态信息（提供者状态）。这些指示值是否有效（PS == 0x80）。例如，如果存在硬件故障，从站的输入值可能无效。同样，如果应用程序某处发生错误，您可以明确声明控制器发送的输出无效。然后从站激活替代值（如果已配置）。 没有自己的 I\/O 的子模块也为输入提供提供者状态。 显示 I\/O 通道 注意：当通...", 
"body" : "目的： PROFINET 设备 在此对话框中，您可以启用或禁用各个子模块的 I\/O 提供者数据或 I\/O 使用者状态数据。因此，状态字节也映射到 I\/O 映射中。但是，建议在控制器上进行全局设置。 有关更多信息，请参阅： IO 提供者\/消费者状态 除了实际的输入和输出数据，PROFINET 还发送状态信息（提供者状态）。这些指示值是否有效（PS == 0x80）。例如，如果存在硬件故障，从站的输入值可能无效。同样，如果应用程序某处发生错误，您可以明确声明控制器发送的输出无效。然后从站激活替代值（如果已配置）。 没有自己的 I\/O 的子模块也为输入提供提供者状态。 显示 I\/O 通道 注意：当通道被禁用时 添加 I\/O 映射 选项被选中 PROFINET 控制器 - 一般 标签。 ：相关模块在 I\/O 映射对话框中提供具有提供程序状态的附加 I\/O。双击地址栏可以打开对应的模块。 子模块 多变的 映射到输入\/输出的 I\/O 变量。 地址 映射此变量的 IEC 地址（I\/O 映射对话框）。 提供者状态字节中的值“hex 80”（位 7）显示状态“OK”。有关此字节定义的详细信息，请参阅技术规范 PROFINET . 在为输出数据映射的 I\/O 提供程序状态的情况下，输出 PS 必须明确设置为“GOOD”(=0x80)。否则，设备将不接受数据。然后从站激活替代值（如果已配置）。 如果应用程序停止，则输出的未映射 I\/O 提供程序状态设置为“坏”。映射的 I\/O 提供程序状态设置为其配置值。 " }, 
{ "title" : "设备 - 状态 ", 
"url" : "_pnio_edt_device_status.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 设备 - 状态 ", 
"snippet" : "目的： PROFINET 设备 该选项卡显示设备的诊断数据和警报。 诊断数据 当前位于设备中的诊断。只要可以与设备建立链接，就会从状态显示重新加载当前诊断数据。 警报 自应用程序启动以来，该设备已上报的该设备的所有警报。警报存储在控制器的环形缓冲区中。 确认 从环形缓冲区中删除警报。...", 
"body" : "目的： PROFINET 设备 该选项卡显示设备的诊断数据和警报。 诊断数据 当前位于设备中的诊断。只要可以与设备建立链接，就会从状态显示重新加载当前诊断数据。 警报 自应用程序启动以来，该设备已上报的该设备的所有警报。警报存储在控制器的环形缓冲区中。 确认 从环形缓冲区中删除警报。 " }, 
{ "title" : "模块 - 通用 ", 
"url" : "_pnio_edt_module_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 模块 - 通用 ", 
"snippet" : "目的： PROFINET 模块 模块信息 身份证号码 模块的标识（来自设备描述）。 插槽号 I\/O 模块在 I\/O 设备下方的位置，从第一个模块的“1”开始，每个附加模块递增。这由设备树中的当前结构自动产生。 用户参数 设置所有默认值 CODESYS 将 GSDML 文件中的所有设置重置为默认值（请参阅“默认值”列）。 读取所有值 CODESYS 从设备读取当前值并在编辑器中更新它们。 写入所有值 CODESYS 将当前值从编辑器写入 I\/O 模块。并非所有 I\/O 模块都支持运行模式下的参数更新。如果不是，则显示错误消息。...", 
"body" : "目的： PROFINET 模块 模块信息 身份证号码 模块的标识（来自设备描述）。 插槽号 I\/O 模块在 I\/O 设备下方的位置，从第一个模块的“1”开始，每个附加模块递增。这由设备树中的当前结构自动产生。 用户参数 设置所有默认值 CODESYS 将 GSDML 文件中的所有设置重置为默认值（请参阅“默认值”列）。 读取所有值 CODESYS 从设备读取当前值并在编辑器中更新它们。 写入所有值 CODESYS 将当前值从编辑器写入 I\/O 模块。并非所有 I\/O 模块都支持运行模式下的参数更新。如果不是，则显示错误消息。 " }, 
{ "title" : "模块 – 状态 ", 
"url" : "_pnio_edt_modul_status.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 配置 \/ 模块 – 状态 ", 
"snippet" : "目的： PROFINET 模块 该选项卡显示模块的诊断数据和警报。 诊断数据 当前位于设备中的诊断。只要可以与设备建立链接，就会从状态显示重新加载当前诊断数据。 警报 自应用程序启动以来，该设备已上报的该模块的所有告警。警报存储在控制器上的环形缓冲区中。 确认 从环形缓冲区中删除警报。...", 
"body" : "目的： PROFINET 模块 该选项卡显示模块的诊断数据和警报。 诊断数据 当前位于设备中的诊断。只要可以与设备建立链接，就会从状态显示重新加载当前诊断数据。 警报 自应用程序启动以来，该设备已上报的该模块的所有告警。警报存储在控制器上的环形缓冲区中。 确认 从环形缓冲区中删除警报。 " }, 
{ "title" : "职能 ", 
"url" : "_pnio_f_master_functions.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "自动分配站名 ", 
"url" : "_pnio_automatic_station_name_assignment.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 自动分配站名 ", 
"snippet" : "一个 PROFINET 可以根据拓扑信息交换设备并自动配置。不需要额外的操作。 要求是您已经配置了对等端口 PROFINET 设备（请参阅拓扑配置）并且设置的设备支持邻域检测（符合 B 类设备或支持 LLDP 和 SNMP 协议）。然后控制器可以自动为设备分配站名。 借助此功能，您可以在没有工程或监督工具的情况下更换设备。您使用未配置的替换设备（“开箱即用”）替换网络中相同位置的故障设备。不需要额外的操作。 当整个网络的要求（拓扑声明，邻域检测）被指定时，整个系统就可以被配置。这对于调试标准机械非常有用。 目前该功能仅支持 CODESYS PROFINET 堆栈和 CIFX 控制器（固件版本 ...", 
"body" : "一个 PROFINET 可以根据拓扑信息交换设备并自动配置。不需要额外的操作。 要求是您已经配置了对等端口 PROFINET 设备（请参阅拓扑配置）并且设置的设备支持邻域检测（符合 B 类设备或支持 LLDP 和 SNMP 协议）。然后控制器可以自动为设备分配站名。 借助此功能，您可以在没有工程或监督工具的情况下更换设备。您使用未配置的替换设备（“开箱即用”）替换网络中相同位置的故障设备。不需要额外的操作。 当整个网络的要求（拓扑声明，邻域检测）被指定时，整个系统就可以被配置。这对于调试标准机械非常有用。 目前该功能仅支持 CODESYS PROFINET 堆栈和 CIFX 控制器（固件版本 3.x 及更高版本）。 " }, 
{ "title" : "控制器冗余 ", 
"url" : "_pnio_controller_redundancy.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 控制器冗余 ", 
"snippet" : "要提高系统的可用性，您可以使用具有冗余的第二个控制器 PROFINET 控制器结合 CODESYS Redundancy . CODESYS Redundancy 充当“后端”以同步两个控制器上的应用程序。土生土长的 PROFINET 系统冗余 (SR) 确保与现场设备的数据交换顺畅。 随着 PROFINET 系统冗余，两个控制器各自保持一个连接（AR = 应用程序关系）到每个 PROFINET 支持S2系统冗余的现场设备。其中一个连接有 PRIMARY 角色，而另一个连接具有 BACKUP 角色。在这里，仅与 PRIMARY 角色传输有效数据。如果与 PRIMARY 角色失败，则可以顺利切换...", 
"body" : "要提高系统的可用性，您可以使用具有冗余的第二个控制器 PROFINET 控制器结合 CODESYS Redundancy . CODESYS Redundancy 充当“后端”以同步两个控制器上的应用程序。土生土长的 PROFINET 系统冗余 (SR) 确保与现场设备的数据交换顺畅。 随着 PROFINET 系统冗余，两个控制器各自保持一个连接（AR = 应用程序关系）到每个 PROFINET 支持S2系统冗余的现场设备。其中一个连接有 PRIMARY 角色，而另一个连接具有 BACKUP 角色。在这里，仅与 PRIMARY 角色传输有效数据。如果与 PRIMARY 角色失败，则可以顺利切换到与 BACKUP 角色，现在成为新角色 PRIMARY 连接，在最短的时间内。混合操作与 PROFINET 不支持 S2 系统冗余的现场设备是可能的。然而，在这种情况下，当连接失败时数据传输会短暂中断，因为建立了一个完整的新连接。 PROFINET 系统冗余可以通过其他冗余机制进行扩展，例如 MRP（“线路冗余”）。 " }, 
{ "title" : "CODESYS 运行时的配置 ", 
"url" : "_pnio_controller_redundancy.html#UUID-b44ffc63-4c90-a3ff-0b33-c11c786d64db_section-idm4520238175380833428668771124", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 控制器冗余 \/ CODESYS 运行时的配置 ", 
"snippet" : "[CmpRedundancyConnectionIP] Link1.IpAddressLocal=192.168.56.1 ; IP address of redundancy link of local PLC Link1.IpAddressPeer=192.168.56.101 ; IP address of redundancy link of peer PLC Link1.Port=1205 [CmpRedundancy] BootupWaitTime=5000 TcpWaitTime=2000 StandbyWaitTime=50 ; This timeout depends on ...", 
"body" : "[CmpRedundancyConnectionIP]\nLink1.IpAddressLocal=192.168.56.1 ; IP address of redundancy link of local PLC\nLink1.IpAddressPeer=192.168.56.101 ; IP address of redundancy link of peer PLC\nLink1.Port=1205\n[CmpRedundancy]\nBootupWaitTime=5000\nTcpWaitTime=2000\nStandbyWaitTime=50 ; This timeout depends on the quality of real time task and communication system\nLockTimeout=20 ; Maximum time of timer lock\nBootproject=Application ; Name of your CODESYS application\nRedundancyTaskName=MainTask ; Task name in your CODESYS application\nDataSyncAlways=1\nPlcIdent=1 ;\/\/ Redundant Controller = 2 !!!\nSyncWaitTime=100;\n " }, 
{ "title" : "项目中的配置 ", 
"url" : "_pnio_controller_redundancy.html#UUID-b44ffc63-4c90-a3ff-0b33-c11c786d64db_section-idm4512096403710433428678152475", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 控制器冗余 \/ 项目中的配置 ", 
"snippet" : "在项目中，IP地址和控制站名称等设置 PROFINET 还需要在第二个控制器 (PLC 2) 上配置控制器。 当。。。的时候 冗余配置 对象被插入到项目中，有额外的设置 EtherNet Adapter 在 PLC 2 上 EtherNet Adapter 设备。 在控制器的配置中，一个额外的 系统冗余 显示应在 PLC 2 上使用的设置选项卡。支持 S2 系统冗余的现场设备自动设置为该模式。 这 CODESYS Redundancy 只允许同步单个任务。在这个任务中，所有 PROFINET 应使用 I\/O 数据，I\/O 映射应仅对现有变量进行。因为只有 PROFINET 控制器与 PRIMA...", 
"body" : "在项目中，IP地址和控制站名称等设置 PROFINET 还需要在第二个控制器 (PLC 2) 上配置控制器。 当。。。的时候 冗余配置 对象被插入到项目中，有额外的设置 EtherNet Adapter 在 PLC 2 上 EtherNet Adapter 设备。 在控制器的配置中，一个额外的 系统冗余 显示应在 PLC 2 上使用的设置选项卡。支持 S2 系统冗余的现场设备自动设置为该模式。 这 CODESYS Redundancy 只允许同步单个任务。在这个任务中，所有 PROFINET 应使用 I\/O 数据，I\/O 映射应仅对现有变量进行。因为只有 PROFINET 控制器与 PRIMARY 连接接收到有效的 I\/O 数据，否 PROFINET I\/O 数据应在 BACKUP 控制器上进行处理。 PROFINET 用于非循环服务的功能块（例如， RDREC , WRREC ）或报警处理（例如， RALARM ) 不得在同步任务或同步数据区域中使用。 冗余任务的优先级必须明显低于 PROFINET 输入\/输出任务。 的标准行为 PROFINET 操作过程中的控制器： 当控制器的角色为“主动”时， PROFINET 控制器（和所有连接）是 PRIMARY . 当控制器的角色为“备用”时， PROFINET 控制器（和所有连接）是 BACKUP . 当启动时控制器的角色为“Standalone”时，只有 PROFINET PLC 1 上的控制器是 PRIMARY 控制器。 当控制器的角色变为“独立”时（冗余连接中断或另一个 PLC 发生故障）， PROFINET 控制器保留其当前角色。 这 冗余管理器 功能块通过有用的错误处理扩展了标准行为： 当一个连接 PRIMARY 控制器终止（完全关闭所有连接或单个连接终止），备用控制器切换到“活动”及其 PROFINET 控制器成为新的 PRIMARY 控制器。 当。。。的时候 PROFINET 两个控制器之一上的控制器发生故障（例如，没有网络），此控制器切换到“模拟”。 注意：RedundancyManager 不能定义在同步区域中，例如全局变量列表中。 " }, 
{ "title" : "介质冗余 (MRP) ", 
"url" : "_pnio_media_redundancy.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 介质冗余 (MRP) ", 
"snippet" : "媒体冗余（基于 MRP – 媒体冗余协议）是一种通过冗余通信路径提高系统可用性的功能。标准以太网只允许到一个网络参与者的单一、唯一的数据路径（线形和星形拓扑）。 MRP 允许将线路拓扑物理关闭到一个环。因此，参与者可以通过两条路径到达。 必须将 MRP 环网（也称为“MRP 域”）的所有参与者配置为介质冗余客户端 (MRC)，并且至少将其中一个配置为介质冗余管理器 (MRM)。如果环没有物理故障，则 MRM 会中断环以防止以太网数据无限循环。当检测到故障时，MRM 会打开环，并且可以重新访问断开的网段中的参与者。 介质冗余可以与系统冗余等其他冗余机制相结合。可以配置多个环，并且（如果设备支持）...", 
"body" : "媒体冗余（基于 MRP – 媒体冗余协议）是一种通过冗余通信路径提高系统可用性的功能。标准以太网只允许到一个网络参与者的单一、唯一的数据路径（线形和星形拓扑）。 MRP 允许将线路拓扑物理关闭到一个环。因此，参与者可以通过两条路径到达。 必须将 MRP 环网（也称为“MRP 域”）的所有参与者配置为介质冗余客户端 (MRC)，并且至少将其中一个配置为介质冗余管理器 (MRM)。如果环没有物理故障，则 MRM 会中断环以防止以太网数据无限循环。当检测到故障时，MRM 会打开环，并且可以重新访问断开的网段中的参与者。 介质冗余可以与系统冗余等其他冗余机制相结合。可以配置多个环，并且（如果设备支持）也可以配置多个环。本身不支持 MRP 的设备可以作为被动参与者（从 MRP 角度）连接到 MRP 环。一个示例是 MRP 交换机环，其余参与者连接到其上，就像在经典星形拓扑中一样。标准以太网协议的介质冗余是可协商的，因此不限于 PROFINET 沟通。 配置\/调试： 在拓扑编辑器中，配置端口切换 PROFINET 设备。 在最简单的情况下，还可以使用导入功能将尚未闭合的真实现有线拓扑导入到项目中。然后在配置中关闭环。 结果： 激活响铃并将参与者配置为 经理 或多个参与者 经理_汽车 . 在 媒体冗余 选项卡，将显示与参与者的闭合环。 将项目下载到控制器。 这 PROFINET 设备在启动时使用 MRP 配置进行参数化。 只要环没有物理闭合，MRM 就会显示诊断“MRP 环打开”。 成功配置后，您现在可以物理关闭环。 在环中断的情况下，环的重新配置可能会导致环的暂时中断 PROFINET 沟通。这是中断时间长于设置的看门狗时间的情况。 PROFINET 联系。此时间取决于设备数量（每个环最多 50 个设备）以及设备类型。总时间始终小于 200 毫秒，也可以显着缩短。 " }, 
{ "title" : "PROFINET IRT ", 
"url" : "_pnio_irt.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ PROFINET IRT ", 
"snippet" : "PROFINET IRT（等时实时）是一种针对最大性能进行优化的时钟通信。它通常用于运动控制应用。 这 PROFINET 通信类目前仅适用于 Hilscher CIFX-Karten 使用 FW > 3.1.xx（在 CODESYS 设置： ..\/GatewayPLC\/HilscherCIFX\/Firmware\/cifxpnm.nxf ）。 为了从应用程序发送时钟 I\/O 数据，中断触发的总线周期是必要的（用于 I\/O 应用程序和 CIFX 硬件之间的同步）。目前这仅适用于 RTE Vx >= V3.5 SP9，以及 Linux 和 Hilscher 内核模块。 配置时需要注意的具体步骤： I...", 
"body" : "PROFINET IRT（等时实时）是一种针对最大性能进行优化的时钟通信。它通常用于运动控制应用。 这 PROFINET 通信类目前仅适用于 Hilscher CIFX-Karten 使用 FW > 3.1.xx（在 CODESYS 设置： ..\/GatewayPLC\/HilscherCIFX\/Firmware\/cifxpnm.nxf ）。 为了从应用程序发送时钟 I\/O 数据，中断触发的总线周期是必要的（用于 I\/O 应用程序和 CIFX 硬件之间的同步）。目前这仅适用于 RTE Vx >= V3.5 SP9，以及 Linux 和 Hilscher 内核模块。 配置时需要注意的具体步骤： IRT 通信是通过设置一个 RT 类来激活的 PROFINET 从属 RTC 3。 对于所有 IRT 设备（“IRT 域”），必须在内部识别网络拓扑（即以太网端口的连接性）。此设置在 拓扑 的选项卡 PROFINET 掌握。 此外，必须定义设备之间的电缆长度。指定默认值 100m。此设置在 选项 的选项卡 PROFINET 设备。 RT 和 IRT 之间的混合操作是可能的。但是，IRT 域不得被 RT 设备或不支持 IRT 的交换机中断。这意味着控制器上的 IRT 设备紧跟在 RT 设备“之后”。 为了从应用程序发送时钟 I\/O 数据，总线周期任务必须设置为 外部的 并且必须在 CFG 文件中激活中断模式（ [CmpHilscherCIFX] InterruptMode=1 )。 " }, 
{ "title" : "重新配置 ", 
"url" : "_pnio_reconfigure.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 重新配置 ", 
"snippet" : "“重新配置”功能允许动态调整 PROFINET 最初下载到控制器的配置，在运行时到应用程序。 这 DED.Reconfigure 功能块可用于启用或禁用设备树中的任何设备配置。为此， 启用设备诊断 需要在 PLC 设置中设置选项。 如果是 PROFINET ，该功能块可以在以下设备上执行： PROFINET 控制器 控制器配置的各个从节点（不是 CIFX） PROFINET 设备 禁用时，可以更改设备的不同配置参数： 站名 IP 地址 模块或子模块的槽位号和子槽位号 设备设置（制造商特定的数据记录） 然后在再次启用设备或重新建立连接时使用这些设置。 有关更多信息，请参阅： IoDrvProfi...", 
"body" : "“重新配置”功能允许动态调整 PROFINET 最初下载到控制器的配置，在运行时到应用程序。 这 DED.Reconfigure 功能块可用于启用或禁用设备树中的任何设备配置。为此， 启用设备诊断 需要在 PLC 设置中设置选项。 如果是 PROFINET ，该功能块可以在以下设备上执行： PROFINET 控制器 控制器配置的各个从节点（不是 CIFX） PROFINET 设备 禁用时，可以更改设备的不同配置参数： 站名 IP 地址 模块或子模块的槽位号和子槽位号 设备设置（制造商特定的数据记录） 然后在再次启用设备或重新建立连接时使用这些设置。 有关更多信息，请参阅： IoDrvProfinetBase.ControllerConfigUtil 和 IoDrvProfinetBase.DeviceConfigUtil " }, 
{ "title" : "命令：扫描设备 ", 
"url" : "_pnio_cmd_scan_devices.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 命令：扫描设备 ", 
"snippet" : "功能 ：该命令与活动的控制器建立临时连接 PROFINET 控制器就可以了，并确定 PROFINET 网络中的设备（设备和控制器）。然后您可以将扫描的设备应用到项目的设备树中。 称呼 ： 项目 菜单;设备树中设备对象的上下文菜单 要求 : 设置到控制器的通信设置。一个应用程序 PROFINET 控制器最初已下载到控制器。 为了还能够读取检测到的模块结构 PROFINET 必须为此配置设备、IP 地址和站名（请参阅 自动IP 功能或 提名 在里面 扫描设备 对话）。要正确显示，设备的 GSDML 还必须安装在 CODESYS .在 I&M 对话框中，一些设备与供应商的相应产品页面链接。在那里你可...", 
"body" : "功能 ：该命令与活动的控制器建立临时连接 PROFINET 控制器就可以了，并确定 PROFINET 网络中的设备（设备和控制器）。然后您可以将扫描的设备应用到项目的设备树中。 称呼 ： 项目 菜单;设备树中设备对象的上下文菜单 要求 : 设置到控制器的通信设置。一个应用程序 PROFINET 控制器最初已下载到控制器。 为了还能够读取检测到的模块结构 PROFINET 必须为此配置设备、IP 地址和站名（请参阅 自动IP 功能或 提名 在里面 扫描设备 对话）。要正确显示，设备的 GSDML 还必须安装在 CODESYS .在 I&M 对话框中，一些设备与供应商的相应产品页面链接。在那里你可以找到 GSDML。 该命令指的是 PROFINET 在设备树中选择的控制器。例如，一个已经插入的 PROFINET 可以选择控制器和用于确定分配给它的 I\/O 设备和 I\/O 模块的命令。 执行扫描操作后， 扫描设备 对话框打开并显示扫描的设备。 " }, 
{ "title" : "“扫描设备”对话框 ", 
"url" : "_pnio_cmd_scan_devices.html#UUID-80036470-f402-7701-f762-0cbca7d9ba0d_UUID-87d819e6-40ac-9a7c-b963-a6e4714caeeb", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 命令：扫描设备 \/ “扫描设备”对话框 ", 
"snippet" : "扫描的设备 设备名称、设备类型、地址、站名等 扫描设备的数据取决于网络类型。 当您更改扫描设备列表中的值时，该值以斜体显示。这表明新值在编辑器中已更改 CODESYS ，但不在设备中。当您将值下载到设备时，它会正常显示。 指示项目和扫描设备之间差异的值以橙色显示。 如果扫描设备有多个设备描述可用，则名称以粗体显示。对于不同的现场总线，匹配设备描述的选择是不同的。更多详细信息，请参见相应的现场总线章节。 如果找不到设备描述，则会显示以下消息：“注意！在存储库中找不到设备。”根据总线系统，会显示附加信息，例如供应商编号和产品编号。如果没有安装的设备描述，则无法将设备插入到项目中。 显示与项目的差异...", 
"body" : "扫描的设备 设备名称、设备类型、地址、站名等 扫描设备的数据取决于网络类型。 当您更改扫描设备列表中的值时，该值以斜体显示。这表明新值在编辑器中已更改 CODESYS ，但不在设备中。当您将值下载到设备时，它会正常显示。 指示项目和扫描设备之间差异的值以橙色显示。 如果扫描设备有多个设备描述可用，则名称以粗体显示。对于不同的现场总线，匹配设备描述的选择是不同的。更多详细信息，请参见相应的现场总线章节。 如果找不到设备描述，则会显示以下消息：“注意！在存储库中找不到设备。”根据总线系统，会显示附加信息，例如供应商编号和产品编号。如果没有安装的设备描述，则无法将设备插入到项目中。 显示与项目的差异 ：对话框中的表格还显示了其他配置的设备（在项目的设备树中）。 ：表格显示所有扫描的设备。未显示配置的设备。 扫描设备 开始新的搜索。 将所有设备复制到项目 在表中选择的设备被插入到项目的设备树中。如果未选择任何内容，则显示所有扫描的设备。 如果你使用 将所有设备复制到项目 要将设备树中可用的设备插入设备树，则应注意以下几点： 处理数据 和 <...> I\/O 映射 现有设备的选项卡可能会被最近插入的设备的数据覆盖。 配置的设备 对话框的这一部分仅在您选择 显示与项目的差异 选项。 扫描设备和配置设备之间的差异是用颜色编码的。两侧显示为绿色的设备相同。以红色显示的设备仅在扫描或配置的设备视图中可用。 如果您在两个视图中都选择了一个设备，则扫描的设备将插入到所选配置设备的上方。 如果您在两个视图中都选择了一个设备，则扫描的设备将插入到所选配置设备的下方。 如果您在两个视图中都选择了一个设备，则配置的设备将替换为选定的扫描设备。 所有扫描的设备都被复制到项目中。 删除选定的已配置设备。 " }, 
{ "title" : "特殊设置 PROFINET ", 
"url" : "_pnio_cmd_scan_devices.html#UUID-80036470-f402-7701-f762-0cbca7d9ba0d_id_aaea3925e1b0c3aec0a8640e019f7ee3_id_1f511facc5732dbec0a864636481989c", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 命令：扫描设备 \/ 特殊设置 PROFINET ", 
"snippet" : "证件号码。 仅在以下情况下显示 IO 设备和 IO 控制器属于同一网络 IO 设备的 IP 地址和网络掩码已设置 站名 站名和IP设置 PROFINET 设备显示在这里。当字段已被编辑并且输入已被确认时 提名 或者 自动IP ，控制器将新值发送到 PROFINET 设备。 IP地址 子网掩码 MAC地址 我是 使用此命令检索设备的 I&M 数据（标识和维护）。数据显示在 I&M 数据 对话。 自动IP 使用此命令，如果设备扫描的地址无效，您将自动设置网络内的有效 IP 地址（主站的网络设置）。 <– 使用此命令分配设置 ( 站名 , IP地址 ) 从配置的设备到扫描的设备。 --> 使用此命令...", 
"body" : "证件号码。 仅在以下情况下显示 IO 设备和 IO 控制器属于同一网络 IO 设备的 IP 地址和网络掩码已设置 站名 站名和IP设置 PROFINET 设备显示在这里。当字段已被编辑并且输入已被确认时 提名 或者 自动IP ，控制器将新值发送到 PROFINET 设备。 IP地址 子网掩码 MAC地址 我是 使用此命令检索设备的 I&M 数据（标识和维护）。数据显示在 I&M 数据 对话。 自动IP 使用此命令，如果设备扫描的地址无效，您将自动设置网络内的有效 IP 地址（主站的网络设置）。 <– 使用此命令分配设置 ( 站名 , IP地址 ) 从配置的设备到扫描的设备。 --> 使用此命令分配设置 ( 站名 , IP地址 ) 从扫描的设备到配置的设备。 重启 将设备设置重置为默认值。 闪烁 LED 在里面 找到的设备 查看，您可以通过选择对话框中的条目并单击 闪烁 LED .设备应通过闪烁响应。 提名 | CODESYS 设置为所选从站指定的站名和 IP 地址（DCP 设置命令）。 仅显示未命名的电台 ：仅列出没有指定站名的设备。 注意选项 对齐 a的配置设置 PROFINET 具有相应硬件设备设置的设备。 " }, 
{ "title" : "对话框：I&M 数据 ", 
"url" : "_pnio_cmd_scan_devices.html#UUID-80036470-f402-7701-f762-0cbca7d9ba0d_id_aaea3925e1b0c3aec0a8640e019f7ee3_id_fe2acc32cad211e782678a1393f62915", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 命令：扫描设备 \/ 对话框：I&M 数据 ", 
"snippet" : "I&M版 I&M 功能的实施版本 供应商编号 子模块的制造商 ID 订单编号 订单号 序列号 子模块的序列号（唯一的生产编号） 硬件版本 子模块的硬件版本 软件版本 子模块的软件版本 地点 设备安装位置（例如，工厂或生产车间） 功能 子模块的功能或任务 日期 设备或模块的安装或调试日期 符合 ISO 8601 的格式：YYYY-MM DD HH:MM 描述 任何个人信息 对于某些设备，参数 功能 , 地点 , 日期 ， 和 描述 可以修改。...", 
"body" : "I&M版 I&M 功能的实施版本 供应商编号 子模块的制造商 ID 订单编号 订单号 序列号 子模块的序列号（唯一的生产编号） 硬件版本 子模块的硬件版本 软件版本 子模块的软件版本 地点 设备安装位置（例如，工厂或生产车间） 功能 子模块的功能或任务 日期 设备或模块的安装或调试日期 符合 ISO 8601 的格式：YYYY-MM DD HH:MM 描述 任何个人信息 对于某些设备，参数 功能 , 地点 , 日期 ， 和 描述 可以修改。 " }, 
{ "title" : "命令：添加 PROFINET 诊断资源 ", 
"url" : "_pnio_cmd_add_diagnosis_ressources.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 命令：添加 PROFINET 诊断资源 ", 
"snippet" : "功能 ：该命令生成一个包含来自 GSDML 文件的诊断消息的文本列表。 称呼 ： 项目 菜单 → 添加对象 ；上下文菜单中 设备 看法 要求 ： 这 应用 已选定对象。 制造商 PROFINET 设备为数字错误代码定义诊断消息和附加帮助文本（ ChannelError ， ExtChannelError ）由 PROFINET 设备中的 GSDML 文件中。该命令可用于在应用程序中提供这些用户友好的帮助文本（例如，在 CODESYS 可视化）。 GSDML 文件中的诊断消息和附加帮助文本存储在生成的文本列表中。应用程序中有各种接口，可以访问 PROFINET 设备诊断和数字错误代码。 这 PV...", 
"body" : "功能 ：该命令生成一个包含来自 GSDML 文件的诊断消息的文本列表。 称呼 ： 项目 菜单 → 添加对象 ；上下文菜单中 设备 看法 要求 ： 这 应用 已选定对象。 制造商 PROFINET 设备为数字错误代码定义诊断消息和附加帮助文本（ ChannelError ， ExtChannelError ）由 PROFINET 设备中的 GSDML 文件中。该命令可用于在应用程序中提供这些用户友好的帮助文本（例如，在 CODESYS 可视化）。 GSDML 文件中的诊断消息和附加帮助文本存储在生成的文本列表中。应用程序中有各种接口，可以访问 PROFINET 设备诊断和数字错误代码。 这 PVU.ProfinetDiagnosisResources 功能块用于将数字错误代码分配给生成的文本列表中的文本。 有关详细信息，请参阅：For more information, see: 应用中的诊断" }, 
{ "title" : "IO-Link 集成 ", 
"url" : "_pnio_iolink_integration.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ IO-Link 集成 ", 
"snippet" : "IO-Link 设备，例如 PROFINET 具有 IO-Link 主站功能 (IOLM) 和连接的 IO-Link 设备（IOLD，例如传感器）的模块或设备原则上无需额外措施即可使用。 PROFINET 为此定义了 IO-Link 配置文件，该配置文件描述了 IO-Link 对象和功能到 PROFINET 子模块： IO-Link 设备的 IO 数据映射到这些代理子模块的 IO 数据。 无环 PROFINET 服务用于发送 IO-Link 命令和传输参数（参见 ProfinetCommon\/IO-Link 中的 FB）。 IO-Link 事件和诊断映射到 PROFINET 报警和诊断数据。 ...", 
"body" : "IO-Link 设备，例如 PROFINET 具有 IO-Link 主站功能 (IOLM) 和连接的 IO-Link 设备（IOLD，例如传感器）的模块或设备原则上无需额外措施即可使用。 PROFINET 为此定义了 IO-Link 配置文件，该配置文件描述了 IO-Link 对象和功能到 PROFINET 子模块： IO-Link 设备的 IO 数据映射到这些代理子模块的 IO 数据。 无环 PROFINET 服务用于发送 IO-Link 命令和传输参数（参见 ProfinetCommon\/IO-Link 中的 FB）。 IO-Link 事件和诊断映射到 PROFINET 报警和诊断数据。 然后必须使用制造商特定的工具（PDCT – 端口和设备配置工具）来执行通常非常复杂的 IO-Link 设备参数化。 CODESYS 还提供单独的许可 IO-Link 插件。该插件包含使用 IO-Link 设备描述 (IODD) 的配置器，以方便进行参数化。此外，IO-Link 设备的通用（即作为字节流传输）IO 数据是使用来自 IODD 的描述数据准备的。另一个优点是备份 IO-Link 设备参数 CODESYS 项目。 对于通过一个配置 CODESYS IO-Link，必须导入 IODD，生成的 IO-Link 设备必须插入到设备树中的 IOLD 代理子模块下方。 当一个 IODD 设备被添加到一个 IOLD 代理子模块下面时，一个 IO-Link 集成 为该对象显示选项卡。那里可以进行更多设置。 下载 IODD-IO 配置 ：IODD设备不仅用于配置（IO-Link参数），还下载到控制器。 生成一个附加的 I\/O 映射，而不是通用字节流，它提供了一个 I\/O 映射，该映射是用来自 IODD 的信息准备的。 通用输入 PROFINET 子模块仍然可用。任何现有的输入 PROFINET 出于一致性的原因，不再评估子模块。 适配提供者 ID 和设备 ID : 中的提供者 ID 和设备 ID PROFINET 子模块设置会自动适应从属 IODD 设备。 " }, 
{ "title" : "设备工具集成 ", 
"url" : "_pnio_device_tool_integration.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 设备工具集成 ", 
"snippet" : "某些 PROFIsafe 设备的参数化需要设备制造商提供的特殊配置工具。这些“设备工具”可直接从 CODESYS ，只要它们符合标准化的TCI接口（TCI = Tool Command Interface）。 当在 PROFIsafe 设备上安装了合适的设备工具后， CODESYS 开发者 PC， 设备工具命令 类别显示在设备的上下文菜单中（在设备树中单击鼠标右键）。 这 设备工具命令 类别包含支持相应设备的命令，通常用于计算 PROFIsafe“i 参数 CRC”。选择子菜单项时，系统上注册的制造商的设备工具将直接从 CODESYS 。...", 
"body" : "某些 PROFIsafe 设备的参数化需要设备制造商提供的特殊配置工具。这些“设备工具”可直接从 CODESYS ，只要它们符合标准化的TCI接口（TCI = Tool Command Interface）。 当在 PROFIsafe 设备上安装了合适的设备工具后， CODESYS 开发者 PC， 设备工具命令 类别显示在设备的上下文菜单中（在设备树中单击鼠标右键）。 这 设备工具命令 类别包含支持相应设备的命令，通常用于计算 PROFIsafe“i 参数 CRC”。选择子菜单项时，系统上注册的制造商的设备工具将直接从 CODESYS 。 " }, 
{ "title" : "具有在线修改功能的新参数化 ", 
"url" : "_pnio_controller_new_parameter_online.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 职能 \/ 具有在线修改功能的新参数化 ", 
"snippet" : "PROFINET 设备设置可以通过在线修改进行更改和更新。对于 PROFINET 支持的设备 Re-parameterization in run 此功能启用后，这些参数将在运行时模式下应用，不会出现任何中断。不支持此功能的设备将断开连接，然后使用新设置重新连接。 只能更改设备设置，而对于通信参数（IP 地址、发送间隔）或设备树结构的更改（例如，通过添加设备），则无法进行在线更改。...", 
"body" : "PROFINET 设备设置可以通过在线修改进行更改和更新。对于 PROFINET 支持的设备 Re-parameterization in run 此功能启用后，这些参数将在运行时模式下应用，不会出现任何中断。不支持此功能的设备将断开连接，然后使用新设置重新连接。 只能更改设备设置，而对于通信参数（IP 地址、发送间隔）或设备树结构的更改（例如，通过添加设备），则无法进行在线更改。 " }, 
{ "title" : "诊断 ", 
"url" : "_pnio_f_master_diagnosis.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "应用中的诊断 ", 
"url" : "_pnio_f_master_diagnosis_application.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 ", 
"snippet" : "这 PROFINET 控制器配备用于诊断数据的内部缓冲区。这个“影子数据库”在后台通过设备发送的警报和用于建立连接的非循环服务不断更新（对用户透明）。通过这种方式，所有设备的实际诊断状态都会以最小的延迟反映在主机应用程序中，并且可以随时在那里进行评估。或者或另外，应用程序可以接收单独的警报（ CommFB.RALARM ) 或重新读取诊断数据 ( CommFB.RDREC ）。 的API ProfinetCommon 和 通讯FB 此处描述的库对于 CODESYS PROFINET 堆栈以及 CIFX 解决方案。但是，CIFX 解决方案并未完全实施个别服务（请参阅数据表）。有关代码示例，请参阅...", 
"body" : "这 PROFINET 控制器配备用于诊断数据的内部缓冲区。这个“影子数据库”在后台通过设备发送的警报和用于建立连接的非循环服务不断更新（对用户透明）。通过这种方式，所有设备的实际诊断状态都会以最小的延迟反映在主机应用程序中，并且可以随时在那里进行评估。或者或另外，应用程序可以接收单独的警报（ CommFB.RALARM ) 或重新读取诊断数据 ( CommFB.RDREC ）。 的API ProfinetCommon 和 通讯FB 此处描述的库对于 CODESYS PROFINET 堆栈以及 CIFX 解决方案。但是，CIFX 解决方案并未完全实施个别服务（请参阅数据表）。有关代码示例，请参阅下面列出的功能块的库文档。 " }, 
{ "title" : "设备功能块 ", 
"url" : "_pnio_f_master_diagnosis_application.html#UUID-a3f59a59-fdf5-e8be-cce5-671ee57b205e_section-idm4527713815736032611709937608", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 \/ 设备功能块 ", 
"snippet" : "对于每个 PROFINET 在设备树中，创建一个功能块，提供有关设备连接或配置状态的基本信息。例如，请求诊断条目或有偏差的模块配置。 同理，也为控制器创建一个功能块实例，提供控制器运行状态的信息。 PROFINET 控制器。 有关更多信息，请参阅： IoDrvProfinet.ProfinetController 和 IoDrvProfinet.PNSlave...", 
"body" : "对于每个 PROFINET 在设备树中，创建一个功能块，提供有关设备连接或配置状态的基本信息。例如，请求诊断条目或有偏差的模块配置。 同理，也为控制器创建一个功能块实例，提供控制器运行状态的信息。 PROFINET 控制器。 有关更多信息，请参阅： IoDrvProfinet.ProfinetController 和 IoDrvProfinet.PNSlave " }, 
{ "title" : "提供者和消费者状态 ", 
"url" : "_pnio_f_master_diagnosis_application.html#UUID-a3f59a59-fdf5-e8be-cce5-671ee57b205e_section-idm4662505410108832611711124777", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 \/ 提供者和消费者状态 ", 
"snippet" : "此状态信息始终与 I\/O 数据一起传输。它可以添加到 CODESYS 相应模块的 I\/O 映射。...", 
"body" : "此状态信息始终与 I\/O 数据一起传输。它可以添加到 CODESYS 相应模块的 I\/O 映射。 " }, 
{ "title" : "警报 ", 
"url" : "_pnio_f_master_diagnosis_application.html#UUID-a3f59a59-fdf5-e8be-cce5-671ee57b205e_section-idm456948400844483261171195355", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 \/ 警报 ", 
"snippet" : "发送的警报 PROFINET 设备可以通过接收 CommFB.RALARM 功能块。有关信息评估的代码示例，请参阅库文档 ProfinetCommon.DiagnosisDataReader ....", 
"body" : "发送的警报 PROFINET 设备可以通过接收 CommFB.RALARM 功能块。有关信息评估的代码示例，请参阅库文档 ProfinetCommon.DiagnosisDataReader . " }, 
{ "title" : "设备和子模块状态 ", 
"url" : "_pnio_f_master_diagnosis_application.html#UUID-a3f59a59-fdf5-e8be-cce5-671ee57b205e_section-idm4582493502046432611712541362", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 \/ 设备和子模块状态 ", 
"snippet" : "除了直接访问输出 设备功能块 ，也可以使用 ProfinetCommon.DeviceIterator POU 迭代为控制器设计的所有设备。 以同样的方式， ProfinetCommon.SubmoduleIterator POU 用于迭代配置为 PROFINET 设备和用于评估个人 ProfinetCommon.SubmoduleState ....", 
"body" : "除了直接访问输出 设备功能块 ，也可以使用 ProfinetCommon.DeviceIterator POU 迭代为控制器设计的所有设备。 以同样的方式， ProfinetCommon.SubmoduleIterator POU 用于迭代配置为 PROFINET 设备和用于评估个人 ProfinetCommon.SubmoduleState . " }, 
{ "title" : "诊断缓冲区（诊断阴影） ", 
"url" : "_pnio_f_master_diagnosis_application.html#UUID-a3f59a59-fdf5-e8be-cce5-671ee57b205e_section-idm4662505450736032611713483331", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 \/ 诊断缓冲区（诊断阴影） ", 
"snippet" : "随着 ProfinetCommon.DiagnosisDataBuffer POU，可以调用本地缓存在控制器“Shadowing Database”中的数据。 或者， ProfinetCommon.获取子模块诊断() 函数还可用于查询单个子模块的所有缓冲诊断条目。...", 
"body" : "随着 ProfinetCommon.DiagnosisDataBuffer POU，可以调用本地缓存在控制器“Shadowing Database”中的数据。 或者， ProfinetCommon.获取子模块诊断() 函数还可用于查询单个子模块的所有缓冲诊断条目。 " }, 
{ "title" : "错误代码和诊断文本 ", 
"url" : "_pnio_f_master_diagnosis_application.html#UUID-a3f59a59-fdf5-e8be-cce5-671ee57b205e_section-idm4572751619779234280718436272", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 应用中的诊断 \/ 错误代码和诊断文本 ", 
"snippet" : "数字 PROFINET 错误代码（ ErrorCode 和 ExtErrorCode ) 可以通过上述函数和功能块来调用。如果应用程序中需要相应的文本描述（例如，在可视化中显示），则需要单独下载这些文本描述。有关更多信息，请参阅： 命令：添加。...", 
"body" : "数字 PROFINET 错误代码（ ErrorCode 和 ExtErrorCode ) 可以通过上述函数和功能块来调用。如果应用程序中需要相应的文本描述（例如，在可视化中显示），则需要单独下载这些文本描述。有关更多信息，请参阅： 命令：添加。 " }, 
{ "title" : "用户界面中的诊断 ", 
"url" : "_pnio_f_master_diagnosis_gui.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 用户界面中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设备树 ", 
"url" : "_pnio_f_master_diagnosis_gui.html#UUID-31b46e5d-63e6-6548-1eba-549331b68b70_section-idm4662505441164832611714595799", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 用户界面中的诊断 \/ 设备树 ", 
"snippet" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色符号）表示硬错误，例如不正确\/缺少模块或连接终止。 相应模块的诊断标志（红色感叹号）表示当前有一个诊断条目可用于该设备。 错误清除标志指示先前未决错误已被纠正。...", 
"body" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色符号）表示硬错误，例如不正确\/缺少模块或连接终止。 相应模块的诊断标志（红色感叹号）表示当前有一个诊断条目可用于该设备。 错误清除标志指示先前未决错误已被纠正。 " }, 
{ "title" : "设备状态 ", 
"url" : "_pnio_f_master_diagnosis_gui.html#UUID-31b46e5d-63e6-6548-1eba-549331b68b70_section-idm4662505313934432611715051039", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 用户界面中的诊断 \/ 设备状态 ", 
"snippet" : "这 诊断数据 视图显示当前未决的诊断 PROFINET 模块。这 警报 视图显示自应用程序启动以来控制器接收到的分配给该模块的警报。控制器将报警数据保存在环形缓冲区中。当你点击 确认 ，警报数据将从环形缓冲区中删除，并且任何挂起的 Diag-Cleared-Flag 都将重置。...", 
"body" : "这 诊断数据 视图显示当前未决的诊断 PROFINET 模块。这 警报 视图显示自应用程序启动以来控制器接收到的分配给该模块的警报。控制器将报警数据保存在环形缓冲区中。当你点击 确认 ，警报数据将从环形缓冲区中删除，并且任何挂起的 Diag-Cleared-Flag 都将重置。 " }, 
{ "title" : "记录器 ", 
"url" : "_pnio_f_master_diagnosis_gui.html#UUID-31b46e5d-63e6-6548-1eba-549331b68b70_section-idm456948345609123261171565542", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 诊断 \/ 用户界面中的诊断 \/ 记录器 ", 
"snippet" : "PLC 记录器的过滤视图显示在控制器级别和设备级别。这仅显示分配给相应设备的条目。 有关更多信息，请参阅： “日志”选项卡...", 
"body" : "PLC 记录器的过滤视图显示在控制器级别和设备级别。这仅显示分配给相应设备的条目。 有关更多信息，请参阅： “日志”选项卡 " }, 
{ "title" : "图书馆： PROFINET 控制器 ", 
"url" : "_pnio_controller_libraries.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 控制器 \/ 图书馆： PROFINET 控制器 ", 
"snippet" : "通讯FB ProfinetCommon IoDrvProfinet IoDrvCIFXProfinetIRT IoDrvProfinetBase ProfinetVisuUtils...", 
"body" : "通讯FB ProfinetCommon IoDrvProfinet IoDrvCIFXProfinetIRT IoDrvProfinetBase ProfinetVisuUtils " }, 
{ "title" : "PROFINET 现场设备 ", 
"url" : "_pnio_f_slave_device.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "一般的 ", 
"url" : "_pnio_f_slave_device_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 一般的 ", 
"snippet" : "的配置 PROFINET 现场设备由设备本身以及下面插入的模块组成。 CODESYS 提供两种不同的 PROFINET 现场设备： 一种变体，特别适用于 Hilscher CIFX-Karten 一种独立于硬件的变体， CODESYS PROFINET 现场设备 该变体可在任意数量的以太网适配器上运行，也可用于纯编程配置变体。 当插入基于以太网的 CODESYS 现场设备，隐式创建了两个任务，这是 PROFINET 通讯栈。 Profinet_CommunicationTask ：此任务包括非循环通信服务，例如建立连接和诊断。由于实时需求非常弱，这些服务对时间要求不高。因此该任务是低优先级的。...", 
"body" : "的配置 PROFINET 现场设备由设备本身以及下面插入的模块组成。 CODESYS 提供两种不同的 PROFINET 现场设备： 一种变体，特别适用于 Hilscher CIFX-Karten 一种独立于硬件的变体， CODESYS PROFINET 现场设备 该变体可在任意数量的以太网适配器上运行，也可用于纯编程配置变体。 当插入基于以太网的 CODESYS 现场设备，隐式创建了两个任务，这是 PROFINET 通讯栈。 Profinet_CommunicationTask ：此任务包括非循环通信服务，例如建立连接和诊断。由于实时需求非常弱，这些服务对时间要求不高。因此该任务是低优先级的。 Profinet_IOTask : 这才是真正的 PROFINET 实时数据交换发生。在每个周期中处理待处理的 IO 数据包（请参阅从站配置器： 发送时钟 )。因此，需要 1ms 的周期时间（对于 1ms 发送时钟）。 (6) 现场设备 NetX – 常规(3) 模块 - 通用(4) 以太网适配器 (7) 现场设备 - 常规为了在读\/写时以最小的延迟获得最大的 IO 性能，可以在此任务中更新 IO 数据（→ 插入自己的 POU 来更新此任务中的 IO）。 IO 任务中不应执行阻塞或持久化操作，例如可视化或文件访问。如果任务被阻塞太久，那么看门狗会取消与从站通信的连接（参见从站配置器： 看门狗 ）。 我们建议您激活 在停止时刷新 I\/O PLC 设置中的选项。否则，当应用程序在断点处停止时，通信将被取消。 " }, 
{ "title" : "配置 ", 
"url" : "_pnio_f_slave_device_configuration.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 配置 ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 " }, 
{ "title" : "现场设备 - 常规 ", 
"url" : "_pnio_edt_slave_device_ethernet_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 配置 \/ 现场设备 - 常规 ", 
"snippet" : "目的： PROFINET 现场设备 该选项卡显示基本通信设置。 根据 PROFINET 标准 PROFINET 设备负责所用适配器的 IP 设置。它必须保存剩余的 IP 设置，并且能够根据控制器的请求进行重置或修改（IP=0.0.0.0）。初始状态（“重置为工厂”）是停用的 IP 套件 (IP=0.0.0.0)。 要允许完全重置 IP 配置，必须在大多数系统上进行一些设置。 有关更多信息，请参阅： 运行时配置但是，如果 PROFINET 设备是一个可编程逻辑控制器，与编程环境相连（ CODESYS ) 通过同一个以太网适配器，然后修改和重置 IP 地址是中断的（IDE 和 PLC 之间的连接终...", 
"body" : "目的： PROFINET 现场设备 该选项卡显示基本通信设置。 根据 PROFINET 标准 PROFINET 设备负责所用适配器的 IP 设置。它必须保存剩余的 IP 设置，并且能够根据控制器的请求进行重置或修改（IP=0.0.0.0）。初始状态（“重置为工厂”）是停用的 IP 套件 (IP=0.0.0.0)。 要允许完全重置 IP 配置，必须在大多数系统上进行一些设置。 有关更多信息，请参阅： 运行时配置但是，如果 PROFINET 设备是一个可编程逻辑控制器，与编程环境相连（ CODESYS ) 通过同一个以太网适配器，然后修改和重置 IP 地址是中断的（IDE 和 PLC 之间的连接终止）。因此，提供了一种偏离标准的模式（ 使用项目参数 ）。 在开发阶段，为了使工作更容易，建议 CODESYS 通信被转发到单独的以太网适配器（请参阅 参考资料）。 有关更多信息，请参阅： 编程配置IP 和名称分配 使用剩余数据 使用文件的 IP 设置和站名。该文件存储在文件系统中。 数据由控制器设置并由设备保存到文件中。 使用项目参数 使用项目的 IP 设置和站名（以太网适配器的设置）。 Windows 和 VxWorks 必须选择此选项，因为这些系统无法更改 IP 地址。 站名 车站名称 PROFINET 设备 IO 提供者\/消费者状态 使用传入 ：生成提供者和消费者状态的 I\/O 数据，由控制器接收。 使用传出 ：生成提供者和消费者状态的 I\/O 数据，并将其发送到控制器。 替代值 当相应的提供者状态（输出数据 PS）设置为 Bad .输出数据由控制器发送并复制到 Profinet 模块的 %I 区域。 以下选项可用于替代值： 不活跃 ：输出设置为“非活动”（例如：0）。 最后一个值 ：输出数据保留最后一个有效值（提供者状态= GOOD ）。即使与控制器的连接中断，该值也会保留。 在线模式下，显示站名和 IP 设置 地位 标签。 " }, 
{ "title" : "现场设备 NetX – 常规 ", 
"url" : "_pnio_edt_slave_device_general.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 配置 \/ 现场设备 NetX – 常规 ", 
"snippet" : "目的： PROFINET 现场设备 该选项卡显示基本通信设置。 使用剩余数据 使用文件的 IP 设置和站名。最初，IP 地址是 0.0.0.0 根据标准，站名为空。当控制器使用“store remanent”选项设置这些值时，它们就会存储在这里。 使用项目参数 启动设备时，最初始终使用项目中为 IP 配置和站名定义的值。 站名 网络中设备的名称。 注意：站名和 IP 设置可以偏离项目中配置的（默认）设置。它们可以由控制器在运行时模式下设置，并且在某些情况下持久存储（这意味着当在 Set IP 或者 Set station name 命令）。重新启动后，只要 使用剩余数据 选项已设置。 IP地址...", 
"body" : "目的： PROFINET 现场设备 该选项卡显示基本通信设置。 使用剩余数据 使用文件的 IP 设置和站名。最初，IP 地址是 0.0.0.0 根据标准，站名为空。当控制器使用“store remanent”选项设置这些值时，它们就会存储在这里。 使用项目参数 启动设备时，最初始终使用项目中为 IP 配置和站名定义的值。 站名 网络中设备的名称。 注意：站名和 IP 设置可以偏离项目中配置的（默认）设置。它们可以由控制器在运行时模式下设置，并且在某些情况下持久存储（这意味着当在 Set IP 或者 Set station name 命令）。重新启动后，只要 使用剩余数据 选项已设置。 IP地址 初始 IP 设置 注意：此数据可以由 PROFINET 控制器。剩余数据存储在控制器的文件系统中。控制器重启后，该存储数据生效。然后忽略此处的设置。 子网掩码 默认网关 在线模式下，显示站名和 IP 设置 地位 标签。 " }, 
{ "title" : "现场设备 NetX – NetX 配置 ", 
"url" : "_pnio_edt_slave_device_netx.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 配置 \/ 现场设备 NetX – NetX 配置 ", 
"snippet" : "目的： PROFINET 现场设备 NetX 设置 投币口 要使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 要在所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：提示用户在下载或重置时是否应重新初始化总线。重新初始化会中断总线并可能导致机器出现意外行为。...", 
"body" : "目的： PROFINET 现场设备 NetX 设置 投币口 要使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 要在所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：提示用户在下载或重置时是否应重新初始化总线。重新初始化会中断总线并可能导致机器出现意外行为。 " }, 
{ "title" : "现场设备 - 状态 ", 
"url" : "_pnio_edt_slave_device_status.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 配置 \/ 现场设备 - 状态 ", 
"snippet" : "目的： PROFINET 现场设备 该选项卡显示设备和从属模块的诊断数据。对于设备，显示有关驱动程序的其他状态信息。 诊断数据 当前在所选模块的设备诊断数据库中的诊断条目。可以通过以下方式从设备应用程序中创建或删除该数据库的条目 ProfinetCommon.UpdateDiagnosisEntry 功能块。这些条目也显示在远程 Profinet 控制器中，并且可以通过 Profinet 服务读取。...", 
"body" : "目的： PROFINET 现场设备 该选项卡显示设备和从属模块的诊断数据。对于设备，显示有关驱动程序的其他状态信息。 诊断数据 当前在所选模块的设备诊断数据库中的诊断条目。可以通过以下方式从设备应用程序中创建或删除该数据库的条目 ProfinetCommon.UpdateDiagnosisEntry 功能块。这些条目也显示在远程 Profinet 控制器中，并且可以通过 Profinet 服务读取。 " }, 
{ "title" : "职能 ", 
"url" : "_pnio_f_slave_device_function.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令：生成 PROFINET 来自 GSDML 的设备 ", 
"url" : "_pnio_cmd_create_pn_device_from_gsdml.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 职能 \/ 命令：生成 PROFINET 来自 GSDML 的设备 ", 
"snippet" : "功能 ：该命令打开 从 GSDML 生成 PROFINET 设备 对话。这允许 CODESYS devdesc.xml 文件从一个自创的 GSDML 文件生成 PROFINET 设备。 称呼 ： 工具 菜单 从 GSDML 生成 PROFINET 设备 源 GSDML 用于生成设备描述的 GSDML 文件 PROFINET 设备 行动党 GSDML 文件中的数据访问点 开发描述 ID 要生成的设备存储库中设备描述的唯一 ID。建议的值可以被覆盖。 开发版本 要生成的设备存储库中设备描述的版本。建议的值可以被覆盖。 设备描述 CODESYS PROFINET 建议将设置中包含的设备作为 GSDM...", 
"body" : "功能 ：该命令打开 从 GSDML 生成 PROFINET 设备 对话。这允许 CODESYS devdesc.xml 文件从一个自创的 GSDML 文件生成 PROFINET 设备。 称呼 ： 工具 菜单 从 GSDML 生成 PROFINET 设备 源 GSDML 用于生成设备描述的 GSDML 文件 PROFINET 设备 行动党 GSDML 文件中的数据访问点 开发描述 ID 要生成的设备存储库中设备描述的唯一 ID。建议的值可以被覆盖。 开发版本 要生成的设备存储库中设备描述的版本。建议的值可以被覆盖。 设备描述 CODESYS PROFINET 建议将设置中包含的设备作为 GSDML 文件的模板。为此，请导出设备描述并使用导出的 zip 文件中的 GSDML 文件。此 GSDML 文件可以通过其自己的模块进行扩展，并适应标识数据（供应商、产品描述）。 " }, 
{ "title" : "编程配置 ", 
"url" : "_pnio_edt_slave_device_programmatic_configuration.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 职能 \/ 编程配置 ", 
"snippet" : "除了通过设备树声明的通常配置之外， PROFINET 设备也可以纯粹以编程方式配置。为此，图书馆 ProfinetDeviceConfig 提供不需要设备对象实例的编程接口。 一方面，这允许非常灵活的模块结构，该模块结构可在运行时进行调整，也可以与在线更改相关联。另一方面，创建 PROFINET 设备应用比较复杂，需要用户有详细的知识 PROFINET 技术。...", 
"body" : "除了通过设备树声明的通常配置之外， PROFINET 设备也可以纯粹以编程方式配置。为此，图书馆 ProfinetDeviceConfig 提供不需要设备对象实例的编程接口。 一方面，这允许非常灵活的模块结构，该模块结构可在运行时进行调整，也可以与在线更改相关联。另一方面，创建 PROFINET 设备应用比较复杂，需要用户有详细的知识 PROFINET 技术。 " }, 
{ "title" : "诊断 ", 
"url" : "_pnio_f_slave_device_diagnosis.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "应用中的诊断 ", 
"url" : "_pnio_f_slave_device_diagnosis_application.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 应用中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设备功能块 ", 
"url" : "_pnio_f_slave_device_diagnosis_application.html#UUID-e6c79478-c46c-62d8-9328-be6c145efe16_section-idm4588692292110432611702418464", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 应用中的诊断 \/ 设备功能块 ", 
"snippet" : "对于每个 PROFINET 在设备树中，创建一个功能块，提供有关设备连接或配置状态的基本信息。例如，请求诊断条目或有偏差的模块配置。 有关更多信息，请参阅： IoDrvProfinet.ProfinetController ....", 
"body" : "对于每个 PROFINET 在设备树中，创建一个功能块，提供有关设备连接或配置状态的基本信息。例如，请求诊断条目或有偏差的模块配置。 有关更多信息，请参阅： IoDrvProfinet.ProfinetController . " }, 
{ "title" : "提供者和消费者状态 ", 
"url" : "_pnio_f_slave_device_diagnosis_application.html#UUID-e6c79478-c46c-62d8-9328-be6c145efe16_section-idm4662505716072032611703371986", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 应用中的诊断 \/ 提供者和消费者状态 ", 
"snippet" : "此状态信息始终与 I\/O 数据一起传输。它可以添加到 CODESYS 相应模块的 I\/O 映射。...", 
"body" : "此状态信息始终与 I\/O 数据一起传输。它可以添加到 CODESYS 相应模块的 I\/O 映射。 " }, 
{ "title" : "PROFINET 设备用户程序 ", 
"url" : "_pnio_f_slave_device_diagnosis_application.html#UUID-e6c79478-c46c-62d8-9328-be6c145efe16_section-idm4662505409446432611704057934", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 应用中的诊断 \/ PROFINET 设备用户程序 ", 
"snippet" : "当 PLC 被配置为角色时 PROFINET 现场设备，在这种情况下 PROFINET 设备应用是诊断和报警的来源。 应用程序可以使用功能块 CommFB.SALARM 向控制器发送特定于应用程序的警报（“过程警报”）。过程报警不需要诊断条目。 设备诊断数据库中的条目是使用 POU 创建的 ProfinetCommon.UpdateDiagnosisEntry 或删除。如果模块正在与控制器交换数据，则相应的诊断警报也会发送到控制器。 对于用户定义的报警和诊断（ ProfinetCommon.ChannelErrorType 范围中 0x0100 – 0x7FFF )，相应的文本可以存储在设备的...", 
"body" : "当 PLC 被配置为角色时 PROFINET 现场设备，在这种情况下 PROFINET 设备应用是诊断和报警的来源。 应用程序可以使用功能块 CommFB.SALARM 向控制器发送特定于应用程序的警报（“过程警报”）。过程报警不需要诊断条目。 设备诊断数据库中的条目是使用 POU 创建的 ProfinetCommon.UpdateDiagnosisEntry 或删除。如果模块正在与控制器交换数据，则相应的诊断警报也会发送到控制器。 对于用户定义的报警和诊断（ ProfinetCommon.ChannelErrorType 范围中 0x0100 – 0x7FFF )，相应的文本可以存储在设备的 GSDML 中。 " }, 
{ "title" : "用户界面中的诊断 ", 
"url" : "_pnio_f_slave_device_diagnosis_gui.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 用户界面中的诊断 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "设备树 ", 
"url" : "_pnio_f_slave_device_diagnosis_gui.html#UUID-b5136c04-40e3-68cd-089a-5bfd0c0c8718_section-idm4582493399476832611697115762", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 用户界面中的诊断 \/ 设备树 ", 
"snippet" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色符号）表示硬错误，例如不正确\/缺少模块或连接终止。 相应模块的诊断标志（红色感叹号）表示当前有一个诊断条目可用于该设备。 错误清除标志指示先前未决错误已被纠正。...", 
"body" : "在在线模式下，设备树允许精确定位待定诊断。 错误标志（红色符号）表示硬错误，例如不正确\/缺少模块或连接终止。 相应模块的诊断标志（红色感叹号）表示当前有一个诊断条目可用于该设备。 错误清除标志指示先前未决错误已被纠正。 " }, 
{ "title" : "设备状态 ", 
"url" : "_pnio_f_slave_device_diagnosis_gui.html#UUID-b5136c04-40e3-68cd-089a-5bfd0c0c8718_section-idm4569483620281632611699182602", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 用户界面中的诊断 \/ 设备状态 ", 
"snippet" : "这 地位 选项卡显示设备的诊断数据。...", 
"body" : "这 地位 选项卡显示设备的诊断数据。 " }, 
{ "title" : "记录器 ", 
"url" : "_pnio_f_slave_device_diagnosis_gui.html#UUID-b5136c04-40e3-68cd-089a-5bfd0c0c8718_section-idm4527713725024032611699804898", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 诊断 \/ 用户界面中的诊断 \/ 记录器 ", 
"snippet" : "PLC 记录器的过滤视图显示在设备级别。这仅显示由相应设备创建的条目。 有关更多信息，请参阅： “日志”选项卡...", 
"body" : "PLC 记录器的过滤视图显示在设备级别。这仅显示由相应设备创建的条目。 有关更多信息，请参阅： “日志”选项卡 " }, 
{ "title" : "图书馆： PROFINET 设备 ", 
"url" : "_pnio_device_libraries.html", 
"breadcrumbs" : "CODESYS PROFINET \/ PROFINET 现场设备 \/ 图书馆： PROFINET 设备 ", 
"snippet" : "ProfinetDeviceConfig 通讯FB ProfinetCommon...", 
"body" : "ProfinetDeviceConfig 通讯FB ProfinetCommon " }, 
{ "title" : "运行时配置 ", 
"url" : "_pnio_f_runtime_configuration.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 ", 
"snippet" : "为了与 PROFINET RT协议， PROFINET IEC 堆栈使用允许传输 RAW 以太网帧的特殊运行时接口 (SysEthernet)。 该运行系统组件必须在 PLC 的配置文件中激活。 [ComponentManager] Component.1=CmpSysEthernet 在 CODESYS Control RTE 运行时，需要 Intel 的“CmpEt1000Drv”组件和 Realtek 的“CmpRTL8169Mpd”组件。 提供的特殊以太网设备驱动程序 CODESYS Control RTE 必须安装在 Windows 设备管理器中。使用制造商提供的标准驱动程序无法进行...", 
"body" : "为了与 PROFINET RT协议， PROFINET IEC 堆栈使用允许传输 RAW 以太网帧的特殊运行时接口 (SysEthernet)。 该运行系统组件必须在 PLC 的配置文件中激活。 [ComponentManager]\nComponent.1=CmpSysEthernet 在 CODESYS Control RTE 运行时，需要 Intel 的“CmpEt1000Drv”组件和 Realtek 的“CmpRTL8169Mpd”组件。 提供的特殊以太网设备驱动程序 CODESYS Control RTE 必须安装在 Windows 设备管理器中。使用制造商提供的标准驱动程序无法进行操作。 " }, 
{ "title" : "防火墙和包过滤器 ", 
"url" : "_pnio_firewall_packagefilter.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 防火墙和包过滤器 ", 
"snippet" : "这 PROFINET 堆栈不会专门使用 PLC 的已配置以太网适配器。这 PROFINET 协议与网络协议（例如 UDP）并行运行，并建立在这些协议之上。这样，这些以太网适配器也可以用于 CODESYS 沟通。但是，必须将防火墙配置（如果处于活动状态）修改为 PROFINET 需要。 使用的网络协议 PROFINET RT（以太网类型 = 0x8892） UDP、端口 0x8894 以及 0xC000 – 0xFFFF 范围内的空闲端口（通常 – 0xC0FF 就足够了）。 也适用于传入的包裹。 LLDP（以太网类型 0x88CC） ARP（以太网类型 0x0806） 通常在防火墙处解除对 U...", 
"body" : "这 PROFINET 堆栈不会专门使用 PLC 的已配置以太网适配器。这 PROFINET 协议与网络协议（例如 UDP）并行运行，并建立在这些协议之上。这样，这些以太网适配器也可以用于 CODESYS 沟通。但是，必须将防火墙配置（如果处于活动状态）修改为 PROFINET 需要。 使用的网络协议 PROFINET RT（以太网类型 = 0x8892） UDP、端口 0x8894 以及 0xC000 – 0xFFFF 范围内的空闲端口（通常 – 0xC0FF 就足够了）。 也适用于传入的包裹。 LLDP（以太网类型 0x88CC） ARP（以太网类型 0x0806） 通常在防火墙处解除对 UDP 端口的阻止就足够了。 这 PROFINET RT 协议不是 IP 协议。它无法路由，并且仅限于本地网络。 注意：如果您怀疑防火墙是导致通信问题的原因，请在隔离环境中暂时停用它。 " }, 
{ "title" : "CODESYS 沟通 ", 
"url" : "_pnio_firewall_codesys_communication.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ CODESYS 沟通 ", 
"snippet" : "只要控制器上存在多个以太网适配器，通常建议将 CODESYS 通信（项目下载、监控等）和现场总线通信（此处： PROFINET ）。特别是，这适用于 PROFINET 设备，它还控制适配器的 IP 设置。更改 IP 地址（例如，通过 DCP 设置命令或在启动应用程序时）会导致不愉快的终止 CODESYS 沟通。之后，IDE 必须重新连接。 分离通信的最简单方法是禁用以太网适配器 CODESYS 现场总线使用的通信。这是通过配置文件中的以下条目完成的（ *.cfg ） 的 CODESYS 运行： [CmpBlkDrvUdp] itf.0.AdapterName=eth0 itf.0.DoNotU...", 
"body" : "只要控制器上存在多个以太网适配器，通常建议将 CODESYS 通信（项目下载、监控等）和现场总线通信（此处： PROFINET ）。特别是，这适用于 PROFINET 设备，它还控制适配器的 IP 设置。更改 IP 地址（例如，通过 DCP 设置命令或在启动应用程序时）会导致不愉快的终止 CODESYS 沟通。之后，IDE 必须重新连接。 分离通信的最简单方法是禁用以太网适配器 CODESYS 现场总线使用的通信。这是通过配置文件中的以下条目完成的（ *.cfg ） 的 CODESYS 运行： [CmpBlkDrvUdp]\nitf.0.AdapterName=eth0\nitf.0.DoNotUse=1 " }, 
{ "title" : "配置 PROFINET 控制器 ", 
"url" : "_pnio_runtime_configuration_controller.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置 PROFINET 控制器 ", 
"snippet" : "我们建议您在操作系统中为使用的以太网适配器配置静态 IP 地址。...", 
"body" : "我们建议您在操作系统中为使用的以太网适配器配置静态 IP 地址。 " }, 
{ "title" : "视窗 ", 
"url" : "_pnio_runtime_configuration_controller.html#UUID-6ada6b0b-af61-baa8-4dc3-572954fbcd2a_id_f826af67d12e06ec0a864637c092b65_id_58a35c317c3124dfc0a864632d1bf27d", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置 PROFINET 控制器 \/ 视窗 ", 
"snippet" : "Windows 中符合标准的行为需要以下配置步骤： 使用时 CODESYS Control Win ： 安装 Npcap 软件（例如包含在 Wireshark 安装程序中）。 本说明仅适用于 CODESYS 通过 SP18 的版本。 安装 WinPCap 软件。 默认情况下，Npcap 也随 Wireshark 安装一起安装。您需要在 Wireshark 设置中禁用此选项，因为 Npcap 不得安装在系统上。 使用时 CODESYS Control RTE ： 也不需要 WinPCap 或 Npcap。在 Windows 设备管理器中安装提供的、专门改编的以太网驱动程序。需要在运行时配置中启用...", 
"body" : "Windows 中符合标准的行为需要以下配置步骤： 使用时 CODESYS Control Win ： 安装 Npcap 软件（例如包含在 Wireshark 安装程序中）。 本说明仅适用于 CODESYS 通过 SP18 的版本。 安装 WinPCap 软件。 默认情况下，Npcap 也随 Wireshark 安装一起安装。您需要在 Wireshark 设置中禁用此选项，因为 Npcap 不得安装在系统上。 使用时 CODESYS Control RTE ： 也不需要 WinPCap 或 Npcap。在 Windows 设备管理器中安装提供的、专门改编的以太网驱动程序。需要在运行时配置中启用相应的运行时组件。 如果您已将新的以太网适配器添加到系统，请重新启动系统。否则可能找不到适配器以太网适配器。在这种情况下，驱动程序显示 ErrorFindEthernet 上的错误 地位 标签。 在 Windows 控制面板中，为要使用的以太网适配器设置一个固定的 IP 地址。 注意：您不得使用地址范围内的 IP 地址进行自动分配 ( 169.254.x.y ）。而是使用本地子网中的 IP 地址（例如， 192.168.0.x \/ 255.255.255.0 ）。 " }, 
{ "title" : "Linux ", 
"url" : "_pnio_runtime_configuration_controller.html#UUID-6ada6b0b-af61-baa8-4dc3-572954fbcd2a_id_f826af67d12e06ec0a864637c092b65_id_312fd8128ac95591c0a864636bd4ace8", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置 PROFINET 控制器 \/ Linux ", 
"snippet" : "Linux 中符合标准的行为需要以下配置步骤： 将以下两个设置添加到您的文件中 CODESYSControl.cfg ： [SysEthernet] Linux.PACKET_QDISC_BYPASS=1 Linux.ProtocolFilter=3 这个设置 Linux.PACKET_QDISC_BYPASS=1 允许绕过 Linux 的队列规则 (QDISC)，这是更好的实时 Profinet 所必需的。注意：如果您的系统 不是 支持绕过 QDISC，则将此选项设置为 0。 附加设置 Linux.ProtocolFilter=3 禁用 EtherCAT 的协议过滤器。启用过滤器后， PRO...", 
"body" : "Linux 中符合标准的行为需要以下配置步骤： 将以下两个设置添加到您的文件中 CODESYSControl.cfg ： [SysEthernet]\nLinux.PACKET_QDISC_BYPASS=1\nLinux.ProtocolFilter=3 这个设置 Linux.PACKET_QDISC_BYPASS=1 允许绕过 Linux 的队列规则 (QDISC)，这是更好的实时 Profinet 所必需的。注意：如果您的系统 不是 支持绕过 QDISC，则将此选项设置为 0。 附加设置 Linux.ProtocolFilter=3 禁用 EtherCAT 的协议过滤器。启用过滤器后， PROFINET 控制器没有收到 PROFINET RT 协议。 配置固定IP地址。 \/etc\/interfaces 中的配置： auto eth0\niface eth0 inet static\naddress 192.168.0.1\nnetmask 255.255.255.0 配置静态 IP 地址 dhcpcd sudo nano \/etc\/dhcpcd.conf ： interface eth0\nstatic ip_address=192.168.0.1 如果 Linux 系统默认没有安装“VLAN”Linux 软件包，则安装该软件包。 sudo apt-get install vlan # VLAN-Paket installieren\nsudo modprobe 8021q # 8021q Kernelmodul laden 模块可以通过命令自动加载 sudo su -c 'echo \"8021q\" >> \/etc\/modules' 因此您不必在每次系统重新启动时手动加载它。 " }, 
{ "title" : "配置一个 PROFINET 设备 ", 
"url" : "_pnio_runtime_configuration_device.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置一个 PROFINET 设备 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Linux ", 
"url" : "_pnio_runtime_configuration_device.html#UUID-2f710297-ee3f-4d0f-27d2-1f003b6e7f39_id_a1ba84127d131ea7c0a864630561cf1f_id_bb68480142ee7108c0a8646315b5134c", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置一个 PROFINET 设备 \/ Linux ", 
"snippet" : "在 Linux 中，为了符合标准的行为，以下配置步骤是必需的（此处为 Debian\/Raspi 示例）： 在里面 CODESYS 项目，清除 调整操作系统设置 以太网适配器设备的选项。 关闭协议过滤器并允许在配置文件 (*.cfg) 中设置 IP 地址 CODESYS 运行： [SysEthernet] Linux.PACKET_QDISC_BYPASS=1 Linux.ProtocolFilter=3 [SysSocket] Adapter.0.Name=\"eth0\" ;name of the ethernet interface that is used for the profinet ...", 
"body" : "在 Linux 中，为了符合标准的行为，以下配置步骤是必需的（此处为 Debian\/Raspi 示例）： 在里面 CODESYS 项目，清除 调整操作系统设置 以太网适配器设备的选项。 关闭协议过滤器并允许在配置文件 (*.cfg) 中设置 IP 地址 CODESYS 运行： [SysEthernet]\nLinux.PACKET_QDISC_BYPASS=1\nLinux.ProtocolFilter=3\n\n[SysSocket]\nAdapter.0.Name=\"eth0\" ;name of the ethernet interface that is used for the profinet device\nAdapter.0.EnableSetIpAndMask=1 配置操作系统，使以太网适配器在“混杂模式”下启动时没有 IP 地址。在 Runtime V3.5 SP13 及更高版本中不再需要“混杂模式”。 根据 Linux 发行版，有不同的方式来配置以太网适配器： 通过 \/etc\/network\/interfaces 进行配置 auto eth0\niface eth0 inet manual\nup ifconfig eth0 0.0.0.0 up\npre-up ifconfig $IFACE promisc up\npost-down ifconfig $IFACE promisc down 如有必要，停用“Zero Conf”服务，例如 avahi 守护程序： update-rc.d -f avahi-daemon remove 通过 dhcpcd 配置 sudo nano \/etc\/dhcpcd.conf 静态 IP 配置示例： interface eth0\nstatic ip_address=0.0.0.0 如果 Linux 系统默认没有安装“VLAN”Linux 软件包，则安装该软件包。 sudo apt-get install vlan # VLAN-Paket installieren\nsudo modprobe 8021q # 8021q Kernelmodul laden 模块可以通过命令自动加载 sudo su -c 'echo \"8021q\" >> \/etc\/modules' 因此您不必在每次系统重新启动时手动加载它。 " }, 
{ "title" : "视窗 ", 
"url" : "_pnio_runtime_configuration_device.html#UUID-2f710297-ee3f-4d0f-27d2-1f003b6e7f39_id_a1ba84127d131ea7c0a864630561cf1f_id_a9f6590ae16511e78424f6360dbb3d25", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置一个 PROFINET 设备 \/ 视窗 ", 
"snippet" : "Windows 中符合标准的行为需要以下配置步骤： 使用时 CODESYS Control Win : 安装 Npcap 软件（例如包含在 Wireshark 安装程序中）。 此备注仅适用于 CODESYS 通过 SP18 的版本。 安装 WinPCap 软件。 默认情况下，Npcap 也随 Wireshark 安装一起安装。您需要在 Wireshark 设置中禁用此选项，因为 Npcap 不得安装在系统上。 使用时 CODESYS Control RTE : 也不需要 WinPCap 或 Npcap。在 Windows 设备管理器中安装提供的、专门改编的以太网驱动程序。需要在运行时配置中启用...", 
"body" : "Windows 中符合标准的行为需要以下配置步骤： 使用时 CODESYS Control Win : 安装 Npcap 软件（例如包含在 Wireshark 安装程序中）。 此备注仅适用于 CODESYS 通过 SP18 的版本。 安装 WinPCap 软件。 默认情况下，Npcap 也随 Wireshark 安装一起安装。您需要在 Wireshark 设置中禁用此选项，因为 Npcap 不得安装在系统上。 使用时 CODESYS Control RTE : 也不需要 WinPCap 或 Npcap。在 Windows 设备管理器中安装提供的、专门改编的以太网驱动程序。需要在运行时配置中启用相应的运行时组件。 如果您已将新的以太网适配器添加到系统，请重新启动系统。否则可能找不到适配器以太网适配器。在这种情况下，驱动程序显示 ErrorFindEthernet 上的错误 地位 标签。 在 Windows 控制面板中，为要使用的以太网适配器设置一个固定的 IP 地址。 注意：您不得使用地址范围内的 IP 地址进行自动分配 ( 169.254.x.y ）。而是使用本地子网中的 IP 地址（例如， 192.168.0.x \/ 255.255.255.0 ）。 在配置文件中设置IP地址 CODESYS 运行时是允许的。 [SysSocket]\nAdapter.0.Name=\"Profinet Adapter\"\nAdapter.0.EnableSetIpAndMask=1\nAdapter.0.ipaddress=\nAdapter.0.subnetmask= 开始 CODESYS Control Win . 在初始启动时，在 Windows 注册表中应用了步骤 3 中指定的以太网适配器的一些设置。这些在系统重新启动后生效。 重新启动系统后，再次在 Windows 控制面板中检查地址范围中的地址是否已用于以太网适配器的自动分配。如果是这种情况，则使用本地子网中的地址。 重新开始 CODESYS Control Win . 在里面 CODESYS 项目，清除 调整操作系统设置 以太网适配器设备的选项。 " }, 
{ "title" : "VxWorks ", 
"url" : "_pnio_runtime_configuration_device.html#UUID-2f710297-ee3f-4d0f-27d2-1f003b6e7f39_id_a1ba84127d131ea7c0a864630561cf1f_id_bd498b0a485a11e88278b942f6aa8725", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 配置一个 PROFINET 设备 \/ VxWorks ", 
"snippet" : "VxWorks 中符合标准的行为需要以下配置步骤： 在里面 CODESYS 项目，清除 调整操作系统设置 以太网适配器设备的选项。 允许在配置文件 (*.cfg) 中设置 IP 地址 CODESYS 运行。最初不应为此以太网适配器设置 IP 地址。 [SysSocket] Adapter.0.Name=\"eth0\" Adapter.0.EnableSetIpAndMask=1 Adapter.0.ipaddress= Adapter.0.subnetmask= 配置操作系统，使以太网适配器在“混杂模式”下启动时没有 IP 地址。为此，您必须将这些条目添加到启动脚本（用于所需的以太网适配器）： ...", 
"body" : "VxWorks 中符合标准的行为需要以下配置步骤： 在里面 CODESYS 项目，清除 调整操作系统设置 以太网适配器设备的选项。 允许在配置文件 (*.cfg) 中设置 IP 地址 CODESYS 运行。最初不应为此以太网适配器设置 IP 地址。 [SysSocket]\nAdapter.0.Name=\"eth0\"\nAdapter.0.EnableSetIpAndMask=1\nAdapter.0.ipaddress=\nAdapter.0.subnetmask= 配置操作系统，使以太网适配器在“混杂模式”下启动时没有 IP 地址。为此，您必须将这些条目添加到启动脚本（用于所需的以太网适配器）： ifconfig (\"gei0 promisc\")\nipAttach 1,\"gei0\" " }, 
{ "title" : "运行时配置 (CIFX) ", 
"url" : "_pnio_runtime_configuration_cifx.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 运行时配置 \/ 运行时配置 (CIFX) ", 
"snippet" : "对于 CIFX 版本，必须在 PROFINET 配置文件 (*.cfg)。在配置文件中，可以配置 CIFX 固件的其他设置，例如加载另一个固件版本（见注释）。 [ComponentManager] ... Component.7=CmpHilscherCIFX [CmpHilscherCIFX] InterruptMode=1 ; available e.g. for RTE or Linux, not for WinPLC ! DMAMode=1 ; increases Performance on RTE DynamicFirmware=1 ; driver loads default f...", 
"body" : "对于 CIFX 版本，必须在 PROFINET 配置文件 (*.cfg)。在配置文件中，可以配置 CIFX 固件的其他设置，例如加载另一个固件版本（见注释）。 [ComponentManager]\n...\nComponent.7=CmpHilscherCIFX\n\n[CmpHilscherCIFX]\nInterruptMode=1 ; available e.g. for RTE or Linux, not for WinPLC !\nDMAMode=1 ; increases Performance on RTE\n\nDynamicFirmware=1 ; driver loads default firmware, for Profinet this is \"cifxpnm.nxf\", which is the V3.x\n…\n;Device.1.BootloaderFilePath=$Firmware$\\HilscherCIFX\\Firmware\\NETX100-BSL.bin\n;Device.1.Channel.0.FirmwareFile=$Firmware$\\HilscherCIFX\\Firmware\\cifxpnm2.nxf ; this is the V2.x firmware for the legacy CIFX controller ! " }, 
{ "title" : "故障排除 ", 
"url" : "_pnio_f_troubleshooting.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 ", 
"snippet" : "本节介绍使用本产品时技术问题的排除方法 CODESYS PROFINET 驱动程序（控制器和现场设备）。特别是，它涵盖了与不同运行时变体相关的问题。本章不提供介绍 PROFINET 诊断。 请注意每个平台的配置步骤。...", 
"body" : "本节介绍使用本产品时技术问题的排除方法 CODESYS PROFINET 驱动程序（控制器和现场设备）。特别是，它涵盖了与不同运行时变体相关的问题。本章不提供介绍 PROFINET 诊断。 请注意每个平台的配置步骤。 " }, 
{ "title" : "连接丢失 (DHT) ", 
"url" : "_pnio_trouble_connection_failure.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 连接丢失 (DHT) ", 
"snippet" : "特别是与 PROFINET 实时能力有限的平台上的控制器，例如 Linux 或 CODESYS Control Win , 选择太低 (< 4 ms) 的发送时钟通常无法维持。这由错误“AR 消费者 DHT 已过期”（PNIOStatus = 0xCF81FD05 ）。 连接丢失的常见原因 电源安全政策 当今的操作系统和 CPU 通常具有许多省电功能，可以“休眠”系统的某些部分（CPU 或网络适配器）。组件可能会以这样的延迟“唤醒”，以至于它们不再能够可靠地发送。奇怪的是，系统上的低负载会导致通信问题。因此，如果出现问题，应禁用这些 Powersafe 功能。 实时补丁 (Linux) 为了确...", 
"body" : "特别是与 PROFINET 实时能力有限的平台上的控制器，例如 Linux 或 CODESYS Control Win , 选择太低 (< 4 ms) 的发送时钟通常无法维持。这由错误“AR 消费者 DHT 已过期”（PNIOStatus = 0xCF81FD05 ）。 连接丢失的常见原因 电源安全政策 当今的操作系统和 CPU 通常具有许多省电功能，可以“休眠”系统的某些部分（CPU 或网络适配器）。组件可能会以这样的延迟“唤醒”，以至于它们不再能够可靠地发送。奇怪的是，系统上的低负载会导致通信问题。因此，如果出现问题，应禁用这些 Powersafe 功能。 实时补丁 (Linux) 为了确保短发送时钟（1 ms 或更短）稳定，通常需要在 Linux 系统上安装实时补丁。这取决于各自平台的性能和负载。可通过“Profinet_IOTask”（在任务监控中）的大抖动来识别。 增加管理网络任务的优先级 PROFINET 网络适配器。 使用 PLC shell 执行这些命令（详情请参见运行时说明）： irq-list\nirq-set prio eth 0 流量调度（Linux） 如果您将 Profinet 网络适配器与生成大量数据流量的其他服务（例如大型 Web 可视化）并行使用，Profinet 实时数据可能会在适配器上移位。这可以通过流量调度来避免，其中 Profinet 数据的优先级更高。 例子： Linux.PACKET_QDISC_BYPASS 在运行时的 *.cfg 文件中设置。所有剩余流量都受到带宽限制并设置为低优先级（ \/etc\/interfaces ): iface eth0 inet static ... #move all outgoing traffic to a default class with low priority pre-up \/sbin\/tc qdisc add dev $IFACE root handle 1:0 htb default 1 pre-up \/sbin\/tc class add dev $IFACE parent 1:0 classid 1:1 htb rate 1Mbps ceil 1Mbps prio 0 " }, 
{ "title" : "诊断方法 ", 
"url" : "_pnio_trouble_diagnosis.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 诊断方法 ", 
"snippet" : "有关故障排除的更多信息，请参见以下视图 CODESYS 或外部软件，具体取决于具体情况：...", 
"body" : "有关故障排除的更多信息，请参见以下视图 CODESYS 或外部软件，具体取决于具体情况： " }, 
{ "title" : "设备配置器中的状态对话框 ", 
"url" : "_pnio_trouble_diagnosis.html#UUID-b7126354-7f96-a498-15a5-8b6708e71ff0_section-idm43261146037984", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 诊断方法 \/ 设备配置器中的状态对话框 ", 
"snippet" : "如果对象 PROFINET 控制器或 PROFINET 设备在设备树中有一个红色符号，或者如果根本没有发生通信，请查看 地位 设备配置对话框中的选项卡。 这里我们只看控制器。这同样适用于设备。 此处显示的诊断结构中最重要的字段如下： 控制器状态 ： 控制器的当前状态；各个值对应于枚举 Profinet.ControllerState ： 通常可以从这些值中得出有关问题来源的具体结论，例如许可证问题或站名加倍。 状态值也可在 PLC 应用程序中使用： 接收帧 \/ 接收到的 RT 帧 ： 在特定条件下，控制器状态切换为“运行”，但仍无法通信。价值 接收帧 \/ 接收到的 RT 帧 可以提供更多信息：...", 
"body" : "如果对象 PROFINET 控制器或 PROFINET 设备在设备树中有一个红色符号，或者如果根本没有发生通信，请查看 地位 设备配置对话框中的选项卡。 这里我们只看控制器。这同样适用于设备。 此处显示的诊断结构中最重要的字段如下： 控制器状态 ： 控制器的当前状态；各个值对应于枚举 Profinet.ControllerState ： 通常可以从这些值中得出有关问题来源的具体结论，例如许可证问题或站名加倍。 状态值也可在 PLC 应用程序中使用： 接收帧 \/ 接收到的 RT 帧 ： 在特定条件下，控制器状态切换为“运行”，但仍无法通信。价值 接收帧 \/ 接收到的 RT 帧 可以提供更多信息： 接收帧 显示通过以太网接口接收的所有以太网帧的数量。 接收到的 RT 帧 显示 PROFINET RT 帧的子集。 如果两个计数器都保持在 0 尽管设备在网络中，但在启动控制器后，这表明运行时组件存在基本问题 SysEthernet . 要是 接收帧 增加但不增加 接收到的 RT 帧 虽然 PROFINET 设备在网络中，但这表明运行时配置（防火墙、包过滤器等）存在问题。 无效的循环帧 ： 当计数器增加时，这表明运行时组件有问题 SysEthernet 或以太网驱动程序。已收到 PROFINET 帧被拒绝为错误。 UDP\/以太网适配器通常是原因。使用系统的内部以太网适配器。 发送错误 ： 计数器显示通过以太网适配器发送数据的失败尝试。当值 > 1 时，这表明运行时组件有问题 SysEthernet 或以太网驱动程序。 接收时间 \/ 发送时间 ： 此处显示以太网帧发送和接收的最大值和平均值。这些值表示到以太网适配器的链路的性能（运行时接口 SysEthernet ）。 非常高的值（> 500 us）表示系统过载或实时行为中断。在某些情况下，这会导致通信不稳定（DHT 错误导致连接中断）。只有非常长的发送间隔 (> 8 ms) 是可能的。例如，典型值 CODESYS Control RTE 10 个从站和 1 毫秒的发送间隔为 20–30 us，对于 Linux \/ARM 为 200–300 us。 " }, 
{ "title" : "PROFINET 从站配置器 ", 
"url" : "_pnio_trouble_diagnosis.html#UUID-b7126354-7f96-a498-15a5-8b6708e71ff0_id_ea0cc114d7b95f1bc0a8646335ee5c1e_id_1ab1badad7c6e46fc0a864634e71fdc2", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 诊断方法 \/ PROFINET 从站配置器 ", 
"snippet" : "在连接失败的情况下（从属符号为红色），原因会显示在 一般的 设备配置对话框的选项卡。 ( PNIOStatus 根据 PI 规范：分散外围技术规范的应用层协议 PROFINET IO，版本 2.3Ed2MU2，日期：2015 年 2 月，订单号：2.722）...", 
"body" : "在连接失败的情况下（从属符号为红色），原因会显示在 一般的 设备配置对话框的选项卡。 ( PNIOStatus 根据 PI 规范：分散外围技术规范的应用层协议 PROFINET IO，版本 2.3Ed2MU2，日期：2015 年 2 月，订单号：2.722） " }, 
{ "title" : "任务监视器（监控） ", 
"url" : "_pnio_trouble_diagnosis.html#UUID-b7126354-7f96-a498-15a5-8b6708e71ff0_id_ea0cc114d7b95f1bc0a8646335ee5c1e_id_65da1d99d7db1a11c0a8646356e2d4d9", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 诊断方法 \/ 任务监视器（监控） ", 
"snippet" : "在弱系统或与以太网组件链接不良的系统上（ SysEthernet )，连接中断可能是由抖动或高循环时间引起的。 这主要影响控制器。在这种情况下，设备并不重要。 这 监控 选项卡中的 任务配置 有助于发现这些问题。 重要的是 Profinet_IOTask 其中 PROFINET RT 数据包以固定的发送时钟发送。如果这个发送时钟不能被维持，那么连接会被通信看门狗“DataHoldTimer”终止。 PROFINET 设备。 作为推荐值，平均循环时间不应超过 250 µs，最大循环时间不应超过 1 ms。 因此， Profinet_IOTask 应以高优先级运行，其他 IEC 任务不应阻塞 Pr...", 
"body" : "在弱系统或与以太网组件链接不良的系统上（ SysEthernet )，连接中断可能是由抖动或高循环时间引起的。 这主要影响控制器。在这种情况下，设备并不重要。 这 监控 选项卡中的 任务配置 有助于发现这些问题。 重要的是 Profinet_IOTask 其中 PROFINET RT 数据包以固定的发送时钟发送。如果这个发送时钟不能被维持，那么连接会被通信看门狗“DataHoldTimer”终止。 PROFINET 设备。 作为推荐值，平均循环时间不应超过 250 µs，最大循环时间不应超过 1 ms。 因此， Profinet_IOTask 应以高优先级运行，其他 IEC 任务不应阻塞 Profinet_IOTask （相同或更高的优先级）。在此任务的上下文中，不应发生阻塞或持久调用。 " }, 
{ "title" : "PLC 的日志视图 ", 
"url" : "_pnio_trouble_diagnosis.html#UUID-b7126354-7f96-a498-15a5-8b6708e71ff0_id_ea0cc114d7b95f1bc0a8646335ee5c1e_id_112144ead7f3a0dec0a864631471afbc", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 诊断方法 \/ PLC 的日志视图 ", 
"snippet" : "如果配置错误或连接中断， PROFINET 驱动程序可能会在 PLC 的设备配置器的日志视图中提供更多信息：...", 
"body" : "如果配置错误或连接中断， PROFINET 驱动程序可能会在 PLC 的设备配置器的日志视图中提供更多信息： " }, 
{ "title" : "线鲨 ", 
"url" : "_pnio_trouble_diagnosis.html#UUID-b7126354-7f96-a498-15a5-8b6708e71ff0_id_ea0cc114d7b95f1bc0a8646335ee5c1e_id_28891bf7b319ddfdc0a864633ce7b039", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 诊断方法 \/ 线鲨 ", 
"snippet" : "一个成熟的网络诊断工具通常是免费软件 (www.wireshark.org)。这可用于记录控制器\/设备端口上的所有网络流量。 Wireshark 也可以安装在另一台设备（例如，Windows PC）上，只要它与 PROFINET 参与者。但是，在这种情况下，交换机必须与镜像端口一起使用。...", 
"body" : "一个成熟的网络诊断工具通常是免费软件 (www.wireshark.org)。这可用于记录控制器\/设备端口上的所有网络流量。 Wireshark 也可以安装在另一台设备（例如，Windows PC）上，只要它与 PROFINET 参与者。但是，在这种情况下，交换机必须与镜像端口一起使用。 " }, 
{ "title" : "表现 ", 
"url" : "_pnio_trouble_performance1.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 表现 ", 
"snippet" : "这 PROFINET RT 数据包以恒定的发送时钟传输到控制器和设备。如果这个发送时钟不能被维持，那么连接会被通信看门狗“DataHoldTimer”终止。 PROFINET 设备，即使在建立连接的阶段。 在弱系统或与以太网组件链接不良的系统上（ SysEthernet )，可能会出现不稳定的数据传输。 然后要么发送时钟必须在 Reduction ratio 设置，否则必须加强通信看门狗。 CPU的性能对处理器的性能不太重要 PROFINET 司机。以太网接口的链接是决定性的。除了硬件之外，特定于软件的链接（操作系统和以太网驱动程序）也起着重要作用。 可能的连接数和发送时钟示例： 操作系统 中...", 
"body" : "这 PROFINET RT 数据包以恒定的发送时钟传输到控制器和设备。如果这个发送时钟不能被维持，那么连接会被通信看门狗“DataHoldTimer”终止。 PROFINET 设备，即使在建立连接的阶段。 在弱系统或与以太网组件链接不良的系统上（ SysEthernet )，可能会出现不稳定的数据传输。 然后要么发送时钟必须在 Reduction ratio 设置，否则必须加强通信看门狗。 CPU的性能对处理器的性能不太重要 PROFINET 司机。以太网接口的链接是决定性的。除了硬件之外，特定于软件的链接（操作系统和以太网驱动程序）也起着重要作用。 可能的连接数和发送时钟示例： 操作系统 中央处理器 连接 * 发送时钟 窗户 (RTE) 原子 50 * 1 毫秒 VxWorks 电源-PC 30 * 4 毫秒 Linux 拉斯皮V3 6 * 1 毫秒 " }, 
{ "title" : "PROFINET 和其他驱动程序 ", 
"url" : "_pnio_trouble_profinet_and_other_drivers.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ PROFINET 和其他驱动程序 ", 
"snippet" : "这 PROFINET 控制器和设备需要独占访问低级以太网组件 (SysEthernet)。因此，例如，它们不能与 EtherCAT 或 EtherNet\/IP 在一个适配器上并行运行。如果有多个以太网适配器可用，则需要单独的 PROFINET 驱动程序（控制器或者设备）可以在每个以太网适配器上运行。 PROFINET 和 RTE 运行时 此时，只有一个实例 PROFINET 驱动程序在项目中是可能的。相反，可以使用 EtherCAT 进行并行操作（在不同的以太网适配器上）。 这适用于 CODESYS 版本 < V3.5 SP11。...", 
"body" : "这 PROFINET 控制器和设备需要独占访问低级以太网组件 (SysEthernet)。因此，例如，它们不能与 EtherCAT 或 EtherNet\/IP 在一个适配器上并行运行。如果有多个以太网适配器可用，则需要单独的 PROFINET 驱动程序（控制器或者设备）可以在每个以太网适配器上运行。 PROFINET 和 RTE 运行时 此时，只有一个实例 PROFINET 驱动程序在项目中是可能的。相反，可以使用 EtherCAT 进行并行操作（在不同的以太网适配器上）。 这适用于 CODESYS 版本 < V3.5 SP11。 " }, 
{ "title" : "PROFINET 和更早的运行时版本 ", 
"url" : "_pnio_trouble_profinet_and_older_rts_version.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ PROFINET 和更早的运行时版本 ", 
"snippet" : "这 PROFINET 驱动程序至少需要一个运行时 V3.5.7.0。 对于 Windows RTE 运行时，建议至少使用 V3.5.10.0（有关保留 UDP 端口的问题） PROFINET 范围）。 根据当前标准（V2.35 或 2.4）的认证要求是 RTE 版本 >= SP16.1 或 Linux > SP15。...", 
"body" : "这 PROFINET 驱动程序至少需要一个运行时 V3.5.7.0。 对于 Windows RTE 运行时，建议至少使用 V3.5.10.0（有关保留 UDP 端口的问题） PROFINET 范围）。 根据当前标准（V2.35 或 2.4）的认证要求是 RTE 版本 >= SP16.1 或 Linux > SP15。 " }, 
{ "title" : "硬件要求 ", 
"url" : "_pnio_trouble_profinet_hardware_requirements.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 硬件要求 ", 
"snippet" : "PROFINET 需要支持至少 100 mbps 全双工的以太网适配器。所有应用的网络组件（交换机）也必须支持这种传输模式。 MAC 地址 对于具有多个以太网适配器的某些控制器，没有分配唯一的 MAC 地址。这可能导致严重的故障。在这种情况下，用户通常可以设置一个 MAC 地址。...", 
"body" : "PROFINET 需要支持至少 100 mbps 全双工的以太网适配器。所有应用的网络组件（交换机）也必须支持这种传输模式。 MAC 地址 对于具有多个以太网适配器的某些控制器，没有分配唯一的 MAC 地址。这可能导致严重的故障。在这种情况下，用户通常可以设置一个 MAC 地址。 " }, 
{ "title" : "影响和原因 ", 
"url" : "_pnio_trouble_effects_and_causes.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 影响和原因 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "控制器 – 设备对象有一个红色符号。 ", 
"url" : "_pnio_trouble_effects_and_causes.html#UUID-601d39e8-eeec-e091-90d2-399b549b1c96_id_a0cdb0d01e3c0a864635ece3c44_id_3be73aaedb1c6b84c0a864637bc1eca1", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 影响和原因 \/ 控制器 – 设备对象有一个红色符号。 ", 
"snippet" : "您必须检查 控制器状态 在 地位 设备的选项卡。 原因 控制器的 IP 地址或站名加倍 固定 IP 地址与配置的 IP 地址有偏差。 司机没有驾照 未安装 winpcap 或 RTE 以太网驱动程序。 未找到指定的以太网适配器。 内部错误...", 
"body" : "您必须检查 控制器状态 在 地位 设备的选项卡。 原因 控制器的 IP 地址或站名加倍 固定 IP 地址与配置的 IP 地址有偏差。 司机没有驾照 未安装 winpcap 或 RTE 以太网驱动程序。 未找到指定的以太网适配器。 内部错误 " }, 
{ "title" : "控制器 – 设备扫描失败 ", 
"url" : "_pnio_trouble_effects_and_causes.html#UUID-601d39e8-eeec-e091-90d2-399b549b1c96_id_a0cdb0d01e3c0a864635ece3c44_id_b5c220d3db1c6b84c0a864634d5583f3", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 影响和原因 \/ 控制器 – 设备扫描失败 ", 
"snippet" : "为了让扫描对话框显示 PROFINET 当前位于 PROFINET 网络中，数据的读取分两个阶段： 首先，所有设备都通过 PROFINET 实时日志。 然后，通过 UDP\/IP 为每个设备读取模块配置。 可能出现的问题： 影响 原因 PROFINET 设备显示在扫描对话框中，但不显示设备的模块。 这 PROFINET 设备没有 IP 地址，或者它位于控制器以外的另一个子网中，因此无法通过 UDP 访问。 防火墙配置不正确。另一个线索是 日志 PLC 的。 有关更多信息，请参阅： 防火墙和包过滤器扫描对话框不显示任何内容。 驱动程序未启动，应用程序已停止。 不 PROFINET 可以接收 RT ...", 
"body" : "为了让扫描对话框显示 PROFINET 当前位于 PROFINET 网络中，数据的读取分两个阶段： 首先，所有设备都通过 PROFINET 实时日志。 然后，通过 UDP\/IP 为每个设备读取模块配置。 可能出现的问题： 影响 原因 PROFINET 设备显示在扫描对话框中，但不显示设备的模块。 这 PROFINET 设备没有 IP 地址，或者它位于控制器以外的另一个子网中，因此无法通过 UDP 访问。 防火墙配置不正确。另一个线索是 日志 PLC 的。 有关更多信息，请参阅： 防火墙和包过滤器扫描对话框不显示任何内容。 驱动程序未启动，应用程序已停止。 不 PROFINET 可以接收 RT 包。 " }, 
{ "title" : "PROFINET 从设备保持红色符号 ", 
"url" : "_pnio_trouble_effects_and_causes.html#UUID-601d39e8-eeec-e091-90d2-399b549b1c96_id_a0cdb0d01e3c0a864635ece3c44_id_b2e6689bb317bf99c0a864630337f3af", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 影响和原因 \/ PROFINET 从设备保持红色符号 ", 
"snippet" : "控制器启动并且呈绿色（大约 3 秒后），但是... 影响 原因\/背景 ...所有配置 PROFINET 奴隶保持红色。 没有连接到网络。 防火墙问题。检查设备扫描功能是否正常。 ...一个 PROFINET 从站保持红色。 设备不在网络中。检查站名是否正确。 从站以错误终止连接。 性能问题；建立连接时通信看门狗启动。 有关更多信息，请参阅： 表现… PROFINET 从站在绿色、红色和橙色之间切换。 建立连接时，从站的符号为橙色三角形。车站状态为 Unknown . 如果 Unknown 状态在符号变为红色（错误）之前持续很长时间，则这意味着来自从站的响应被防火墙阻止。 在红色\/错误状态下，站...", 
"body" : "控制器启动并且呈绿色（大约 3 秒后），但是... 影响 原因\/背景 ...所有配置 PROFINET 奴隶保持红色。 没有连接到网络。 防火墙问题。检查设备扫描功能是否正常。 ...一个 PROFINET 从站保持红色。 设备不在网络中。检查站名是否正确。 从站以错误终止连接。 性能问题；建立连接时通信看门狗启动。 有关更多信息，请参阅： 表现… PROFINET 从站在绿色、红色和橙色之间切换。 建立连接时，从站的符号为橙色三角形。车站状态为 Unknown . 如果 Unknown 状态在符号变为红色（错误）之前持续很长时间，则这意味着来自从站的响应被防火墙阻止。 在红色\/错误状态下，站状态显示原因。典型错误的原因是： 地位： 原因 81813F02 DNS 未知 RealStationName 站名不正确或设备无法通过网络访问 CF81FD05 连接中止：AR 消费者 DHT 已过期 无法维持发送时钟（见 1.4、1.3.3） CF81FD06 AR cmi 超时 无法维持发送时钟。 防火墙阻止来自从站的消息（UDP\/RPC）。 … PROFINET 从属是绿色的，但它有一个红色的感叹号，或者个别模块是红色的。 控制器具有活动连接，因此一切正常。 这 PROFINET 设备报告 PROFINET 仅针对单个模块的诊断消息。 " }, 
{ "title" : "由于多个 IP 地址导致的错误 ", 
"url" : "_pnio_error_ip_addresses.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 故障排除 \/ 由于多个 IP 地址导致的错误 ", 
"snippet" : "当。。。的时候 PROFINET 控制器启动，它检查网络是否有重复的 IP 地址。尽管实际上没有重复的地址，但建立连接的操作可能会因错误消息“ARP 多个 IP 地址”而中止。在同一网络中具有多个以太网端口的 Linux 系统可能会受到这种“ARP 通量”效应的影响。 这可以使用以下命令进行纠正： sysctl -w net.ipv4.conf.all.arp_announce=1 sysctl -w net.ipv4.conf.all.arp_ignore=2...", 
"body" : "当。。。的时候 PROFINET 控制器启动，它检查网络是否有重复的 IP 地址。尽管实际上没有重复的地址，但建立连接的操作可能会因错误消息“ARP 多个 IP 地址”而中止。在同一网络中具有多个以太网端口的 Linux 系统可能会受到这种“ARP 通量”效应的影响。 这可以使用以下命令进行纠正： sysctl -w net.ipv4.conf.all.arp_announce=1\nsysctl -w net.ipv4.conf.all.arp_ignore=2 " }, 
{ "title" : "认证注意事项 ", 
"url" : "_pnio_certification_hints.html", 
"breadcrumbs" : "CODESYS PROFINET \/ 认证注意事项 ", 
"snippet" : "这 CODESYS PROFINET 控制器和 CODESYS PROFINET 根据当前有效的 PI 一致性测试版本持续检查设备。然而，一个 PROFINET 产品认证始终且专门适用于整个系统。整个系统由硬件平台和“固件”组成，“固件”包括操作系统、 CODESYS 运行时系统，以及 PROFINET 成分。 数据表为 PROFINET 控制器和 CODESYS PROFINET 设备列出了支持的 CODESYS 运行时系统版本。 因此，设备制造商有责任满足成功认证的一些要求。其中包括以下内容： 性能\/网络负载： 网络组件（硬件和协议栈）的性能必须满足一些最低要求。在特殊负载测试中，会在生成...", 
"body" : "这 CODESYS PROFINET 控制器和 CODESYS PROFINET 根据当前有效的 PI 一致性测试版本持续检查设备。然而，一个 PROFINET 产品认证始终且专门适用于整个系统。整个系统由硬件平台和“固件”组成，“固件”包括操作系统、 CODESYS 运行时系统，以及 PROFINET 成分。 数据表为 PROFINET 控制器和 CODESYS PROFINET 设备列出了支持的 CODESYS 运行时系统版本。 因此，设备制造商有责任满足成功认证的一些要求。其中包括以下内容： 性能\/网络负载： 网络组件（硬件和协议栈）的性能必须满足一些最低要求。在特殊负载测试中，会在生成的网络流量（例如，支持带宽的 5%）造成有针对性的中断时测试通信的稳健性。对于最大 4 ms 的 I\/O 数据发送时钟，最大偏差可能为 +-10%。 DCP信号： 为了实施 DCP 信号命令，设备必须能够以可视方式向用户发出其接收信号。这通常是通过永久安装在设备上的 LED 闪烁 3 秒来完成的。默认情况下， CODESYS PROFINET 堆栈在接收时触发“Wink”事件（ DEV_ILC_IDENTIFY ;请参阅运行时系统文档），制造商可以注册。 运行时系统函数 SysTargetGetSerialNumber() 应生成唯一的序列号（16 个字符）。 硬件测试： 根据各种以太网组件检查网络组件的正确行为。 有关认证的详细信息，请参阅： www.profibus.com\/products\/product-certification\/ 。在那里您可以找到 PI 的正式有效文档（例如，测试和测试用例的规范）或“测试包”。 " }
]
$(document).trigger('search.ready');
});