$(document).ready(function () {indexDict['ja'] = [{ "title" : "CODESYS トレース ", 
"url" : "_trace_start_page.html", 
"breadcrumbs" : "CODESYS トレース \/ CODESYS トレース ", 
"snippet" : "とともに Trace デジタル サンプリング オシロスコープと同様の方法で、コントローラー上の変数の値曲線を追跡できます。データとその時間経過はトレース エディターに表示できます。 トレースサンプルプロジェクト...", 
"body" : "とともに Trace デジタル サンプリング オシロスコープと同様の方法で、コントローラー上の変数の値曲線を追跡できます。データとその時間経過はトレース エディターに表示できます。 トレースサンプルプロジェクト " }, 
{ "title" : "トレーススクリプトインターフェイスの使用 ", 
"url" : "_trace_script_use_scripting_interface.html", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 ", 
"snippet" : "ザル CODESYS Trace アドオンはスクリプトインターフェイスを提供します。このインターフェースの使用方法の例を以下に示します...", 
"body" : "ザル CODESYS Trace アドオンはスクリプトインターフェイスを提供します。このインターフェースの使用方法の例を以下に示します " }, 
{ "title" : "トレースの作成 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-698d46a3-837f-222a-2594-c7b891d9d1f4", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トレースの作成 ", 
"snippet" : "# a new trace can be created using the toplevel trace api myApplication = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\")[0] traceObject = trace.create(myApplication, \"MyTraceName\") traceObject.task_name = \"Task\" # a task with the name \"Task\" should already exist here. If it does not exi...", 
"body" : "# a new trace can be created using the toplevel trace api\nmyApplication = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\")[0]\ntraceObject = trace.create(myApplication, \"MyTraceName\")\ntraceObject.task_name = \"Task\" # a task with the name \"Task\" should already exist here. If it does not exist, this assignment throws an ValueError. # the task of the trace can be set during creation\nmyApplication = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\")[0]\ntraceObjectWithTaskSet = trace.create(myApplication, \"NameOfMySecondTrace\", \"MainTask\")\nassert traceObjectWithTaskSet.task_name == \"MainTask\" " }, 
{ "title" : "既存のトレースの検索と検証 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-4f30c66c-f683-740b-5346-2912ac88f465", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 既存のトレースの検索と検証 ", 
"snippet" : "# finding an existing trace can be done via the project.find method foundObjects = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\") expectedTraceObject = foundObjects[0] assert expectedTraceObject.is_trace_object, \"Could not find trace object with the expected name\" # .is...", 
"body" : "# finding an existing trace can be done via the project.find method\nfoundObjects = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\")\nexpectedTraceObject = foundObjects[0]\nassert expectedTraceObject.is_trace_object, \"Could not find trace object with the expected name\" # .is_trace_object is False for all other objects of type IScriptObject " }, 
{ "title" : "トレース変数の追加と変更 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-8bd43b1c-6343-ac35-d7f3-df547d6050cc", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トレース変数の追加と変更 ", 
"snippet" : "myTrace = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\")[0] # add_variable() is a convenience method to add a new ScriptTraceVariable and set its properties during creation addedVariable = myTrace.add_trace_variable(variableName=\"PLC_PRG.a1\", graphColor= 0xff000000, gra...", 
"body" : "myTrace = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"MyTraceObject\")[0]\n\n# add_variable() is a convenience method to add a new ScriptTraceVariable and set its properties during creation\naddedVariable = myTrace.add_trace_variable(variableName=\"PLC_PRG.a1\",\n graphColor= 0xff000000,\n graphType=GraphType.LINES,\n activateMaxWarning=True,\n maxWarningArea=9.0,\n maxColor= 0xffff0000)\n\naddedVariable.enabled = False\n\nfor i in range(2,11):\n newVariable = myTrace.variable_list.add()\n newVariable.variable_name = \"PLC_PRG.a\"+str(i)\n newVariable.graph_type = GraphType.LINES_CROSSES\n\nassert len(myTrace.variable_list) == 10 " }, 
{ "title" : "の変更 ScriptTrace 変数リスト ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-b1ed5b03-c620-077c-2f62-acfd84e810f5", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ の変更 ScriptTrace 変数リスト ", 
"snippet" : "特定のものを削除する ScriptTrace 変数 次のコードスニペットは、指定された名前の変数を検索し、から削除します。 ScriptTrace 変数リスト。 def remove_variable_by_name(traceObject, variableName): index_to_remove = -1 for variable in traceObject.variable_list: if variable.variable_name == variableName: index_to_remove = traceObject.variable_list.index_of(var...", 
"body" : "特定のものを削除する ScriptTrace 変数 次のコードスニペットは、指定された名前の変数を検索し、から削除します。 ScriptTrace 変数リスト。 def remove_variable_by_name(traceObject, variableName):\n index_to_remove = -1\n for variable in traceObject.variable_list:\n if variable.variable_name == variableName:\n index_to_remove = traceObject.variable_list.index_of(variable)\n break\n if index_to_remove != -1:\n traceObject.variable_list.remove(index_to_remove) " }, 
{ "title" : "録音設定の変更 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-c9a5ef6d-6d81-7926-9538-b2249d53bb6a", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 録音設定の変更 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "トレース記録の解像度 (ms\/µs) の設定 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737059980421", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 録音設定の変更 \/ トレース記録の解像度 (ms\/µs) の設定 ", 
"snippet" : "次のコードスニペットは、 ??? スニペット。 traceObject.resolution = Resolution.MicroSeconds # Use Resolution.MilliSeconds if you want to have a trace recording based on milliseconds...", 
"body" : "次のコードスニペットは、 ??? スニペット。 traceObject.resolution = Resolution.MicroSeconds\n# Use Resolution.MilliSeconds if you want to have a trace recording based on milliseconds " }, 
{ "title" : "記録条件を設定する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737059249726", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 録音設定の変更 \/ 記録条件を設定する ", 
"snippet" : "次のコードスニペットは、 ??? スニペット。 traceObject.record_condition = \"PLC_PRG.bDoRecord\"...", 
"body" : "次のコードスニペットは、 ??? スニペット。 traceObject.record_condition = \"PLC_PRG.bDoRecord\" " }, 
{ "title" : "コメントを設定する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737061351582", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 録音設定の変更 \/ コメントを設定する ", 
"snippet" : "次のコードスニペットは、 ??? スニペット。 traceObject.comment = \"This trace records the ...\"...", 
"body" : "次のコードスニペットは、 ??? スニペット。 traceObject.comment = \"This trace records the ...\" " }, 
{ "title" : "自動起動オプションの設定 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737062520065", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 録音設定の変更 \/ 自動起動オプションの設定 ", 
"snippet" : "次のコードスニペットは、 ??? スニペット。 traceObject.auto_start = True...", 
"body" : "次のコードスニペットは、 ??? スニペット。 traceObject.auto_start = True " }, 
{ "title" : "n サイクルごとにのみ記録するようにオプションを設定する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737065791034", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ 録音設定の変更 \/ n サイクルごとにのみ記録するようにオプションを設定する ", 
"snippet" : "次のコードスニペットは、 ??? スニペット。 traceObject.every_n_cycles = 10...", 
"body" : "次のコードスニペットは、 ??? スニペット。 traceObject.every_n_cycles = 10 " }, 
{ "title" : "ダイアグラムとその変数 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-d5a33595-77ec-1fc8-237c-1153a9fda9ec", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ ダイアグラムとその変数 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "の作成 ScriptTrace すべてを含むグラフ ScriptTrace 変数 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737073150269", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ ダイアグラムとその変数 \/ の作成 ScriptTrace すべてを含むグラフ ScriptTrace 変数 ", 
"snippet" : "次のスクリプトは、簡単な図とその変数を作成する方法を示しています。 # first we need a ScriptTraceObject and some ScriptTraceVariables traceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0] assert traceObject.is_trace_object for i in range(5): traceObject.add_trace_variable(variableName=\"PLC_PRG.a\"+str(i))...", 
"body" : "次のスクリプトは、簡単な図とその変数を作成する方法を示しています。 # first we need a ScriptTraceObject and some ScriptTraceVariables\ntraceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0]\nassert traceObject.is_trace_object\nfor i in range(5):\n traceObject.add_trace_variable(variableName=\"PLC_PRG.a\"+str(i))\n\n# create one ScriptTraceDiagram and add all ScriptTraceVariables to it\ntraceDiagram = traceObject.diagrams.add()\nfor traceVar in traceObject.variable_list:\n traceDiagram.add_diagram_variable(traceVar) " }, 
{ "title" : "の作成 ScriptTrace 1 つあたりのダイアグラム ScriptTrace 変数 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737077515554", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ ダイアグラムとその変数 \/ の作成 ScriptTrace 1 つあたりのダイアグラム ScriptTrace 変数 ", 
"snippet" : "次の Python メソッドには 1 つ必要です。 ScriptTrace オブジェクトを作成し、次のダイアグラムを追加します。 ScriptTrace 変数。 def one_diagram_per_variable(traceObject): assert traceObject.is_trace_object for traceVar in traceObject.variable_list: diagram = traceObject.diagrams.add(traceVar) diagram.name = traceVar.variable_name...", 
"body" : "次の Python メソッドには 1 つ必要です。 ScriptTrace オブジェクトを作成し、次のダイアグラムを追加します。 ScriptTrace 変数。 def one_diagram_per_variable(traceObject):\n assert traceObject.is_trace_object\n for traceVar in traceObject.variable_list:\n diagram = traceObject.diagrams.add(traceVar)\n diagram.name = traceVar.variable_name " }, 
{ "title" : "の設定のコピー ScriptTrace ダイアグラム ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-8a9f24ff-4056-39eb-4996-c2e4c45b98e2", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ の設定のコピー ScriptTrace ダイアグラム ", 
"snippet" : "次のスクリプトは、の設定を変更およびコピーする方法を示しています ScriptTrace ダイアグラム。 # we assume, that the traceObject already has multiple diagrams traceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0] assert traceObject.is_trace_object # apply settings for the first diagram traceObject.diagrams[0].y_...", 
"body" : "次のスクリプトは、の設定を変更およびコピーする方法を示しています ScriptTrace ダイアグラム。 # we assume, that the traceObject already has multiple diagrams\ntraceObject = projects.primary.find(\"Device\",\"PLC Logic\",\"Application\",\"Trace\")[0]\nassert traceObject.is_trace_object\n\n# apply settings for the first diagram\ntraceObject.diagrams[0].y_axis.mode = AxisScaleMode.FixedLength\ntraceObject.diagrams[0].y_axis.range = 10.0\ntraceObject.diagrams[0].y_axis.color = 0xffee0000\ntraceObject.diagrams[0].y_axis.draw_grid = True\ntraceObject.diagrams[0].y_axis.grid_color = 0xffee0000\ntraceObject.diagrams[0].tickmark_fixed_spacing = True\ntraceObject.diagrams[0].tickmark_fixed_distance = 5.0\ntraceObject.diagrams[0].tickmark_fixed_subdivisions = 4\n\n# copy the settings from the first diagrams to all other diagrams\nfor i in range(1,len(traceObject.diagrams))    \n traceObject.diagrams[i].y_axis.copy_from(traceObject.diagrams[0]) " }, 
{ "title" : "トレースのオンライン処理 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-b432ef0d-fb60-07d4-552a-2c91ddb4f1f7", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トレースのオンライン処理 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "トレースのダウンロードと開始 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737089222798", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トレースのオンライン処理 \/ トレースのダウンロードと開始 ", 
"snippet" : "次のコードスニペットは Trace のトレース Application アプリケーションをダウンロードし、起動します。 proj = projects.open(r\"<Path to the project file>\") app = proj.find(\"Device\", \"PLC Logic\", \"Application\")[0] with online.create_online_application(app) as onlineapp: traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] ...", 
"body" : "次のコードスニペットは Trace のトレース Application アプリケーションをダウンロードし、起動します。 proj = projects.open(r\"<Path to the project file>\")\napp = proj.find(\"Device\", \"PLC Logic\", \"Application\")[0]\nwith online.create_online_application(app) as onlineapp:\n traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\n onlineapp.login(OnlineChangeOption.Never, True)\n onlineapp.start()\n editor = traceObject.open_editor()\n editor.download()\n editor.start() " }, 
{ "title" : "トレースをファイルに保存する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737181972189", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トレースのオンライン処理 \/ トレースをファイルに保存する ", 
"snippet" : "次のコードスニペットは、 トレースのダウンロードと開始 スニペット。トレースは保存する前に停止する必要があります。そのためには、トリガー条件に達するか、明示的に以下を呼び出します stop() 。 # We assume, that we have an already running trace editor.stop() editor.save(r\"<File path to csv file>\")...", 
"body" : "次のコードスニペットは、 トレースのダウンロードと開始 スニペット。トレースは保存する前に停止する必要があります。そのためには、トリガー条件に達するか、明示的に以下を呼び出します stop() 。 # We assume, that we have an already running trace\neditor.stop()\neditor.save(r\"<File path to csv file>\") " }, 
{ "title" : "トレース記録のためのさまざまな情報のクエリ ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737189210837", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トレースのオンライン処理 \/ トレース記録のためのさまざまな情報のクエリ ", 
"snippet" : "次のコードスニペットは、 トレースのダウンロードと開始 スニペット。 # We assume, that we have an already running trace print(\"Packet State: {}\".format(editor.get_packet_state())) print(\"Trace started at {} (absolute timestamp)\".format(editor.get_trace_start_timetamp()))...", 
"body" : "次のコードスニペットは、 トレースのダウンロードと開始 スニペット。 # We assume, that we have an already running trace\nprint(\"Packet State: {}\".format(editor.get_packet_state()))\nprint(\"Trace started at {} (absolute timestamp)\".format(editor.get_trace_start_timetamp())) " }, 
{ "title" : "トリガーハンドリング ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-223bf514-9693-ae47-273f-2222b07b3394", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トリガーハンドリング ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "の設定中 BOOL トリガー ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737222218896", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トリガーハンドリング \/ の設定中 BOOL トリガー ", 
"snippet" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] traceObject.trigger_variable = \"PLC_PRG.bVar\" traceObject.trigger_edge = TriggerEdge.Positive traceObject.post_trigger_samples = 20 # The trigger level is only needed for numeric trigger variables. It is a good coding style to...", 
"body" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\ntraceObject.trigger_variable = \"PLC_PRG.bVar\"\ntraceObject.trigger_edge = TriggerEdge.Positive\ntraceObject.post_trigger_samples = 20\n\n# The trigger level is only needed for numeric trigger variables. It is a good coding style to set the trigger explicitly to \"None\"\ntraceObject.trigger_level = None " }, 
{ "title" : "数値トリガーの設定 ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737226322301", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トリガーハンドリング \/ 数値トリガーの設定 ", 
"snippet" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0] traceObject.trigger_variable = \"PLC_PRG.iTemperature\" traceObject.trigger_edge = TriggerEdge.PositivetraceObject.post_trigger_samples = 20 # In case of a trigger variable of REAL or LREAL type it is also possible to specify fl...", 
"body" : "traceObject = proj.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\ntraceObject.trigger_variable = \"PLC_PRG.iTemperature\"\ntraceObject.trigger_edge = TriggerEdge.PositivetraceObject.post_trigger_samples = 20\n\n# In case of a trigger variable of REAL or LREAL type it is also possible to specify floating point trigger levels, e.g. 80.5\ntraceObject.trigger_level = 80 " }, 
{ "title" : "トリガーを待って記録されたデータを保存する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737227937476", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トリガーハンドリング \/ トリガーを待って記録されたデータを保存する ", 
"snippet" : "次のコードスニペットは、「Configuring a」に基づいています。 BOOL -triggers」および「* トリガーの設定」スニペット。 triggerstate = editor.get_trigger_state() while triggerstate != TriggerState.TriggerReached: system.delay(200) triggerstate = editor.get_trigger_state() editor.save(r\"<File path to csv file>\")...", 
"body" : "次のコードスニペットは、「Configuring a」に基づいています。 BOOL -triggers」および「* トリガーの設定」スニペット。 triggerstate = editor.get_trigger_state()\nwhile triggerstate != TriggerState.TriggerReached:\n system.delay(200)\n triggerstate = editor.get_trigger_state()\n editor.save(r\"<File path to csv file>\") " }, 
{ "title" : "トリガーに到達した後のタイムスタンプ情報のクエリ ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737235318186", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トリガーハンドリング \/ トリガーに到達した後のタイムスタンプ情報のクエリ ", 
"snippet" : "次のコードスニペットは、「Configuring a」に基づいています。 BOOL -トリガー」と「* トリガーの設定」スニペット。 print(\"Trigger reached at {} (absolute timestamp)\".format(editor.get_trigger_timetamp())) print(\"Trigger reached at {}\".format(editor.get_trigger_startdate())) print(\"Trace was running {}ms until trigger has been reached\".format(edit...", 
"body" : "次のコードスニペットは、「Configuring a」に基づいています。 BOOL -トリガー」と「* トリガーの設定」スニペット。 print(\"Trigger reached at {} (absolute timestamp)\".format(editor.get_trigger_timetamp()))\nprint(\"Trigger reached at {}\".format(editor.get_trigger_startdate()))\nprint(\"Trace was running {}ms until trigger has been reached\".format(editor.get_trigger_timetamp() - editor.get_trace_start_timetamp())) " }, 
{ "title" : "トリガーに到達した後にトレースの記録を再開する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737241377252", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ トリガーハンドリング \/ トリガーに到達した後にトレースの記録を再開する ", 
"snippet" : "次のコードスニペットは、「Configuring a」に基づいています。 BOOL -トリガー」と「* トリガーの設定」スニペット。 editor.reset_trigger()...", 
"body" : "次のコードスニペットは、「Configuring a」に基づいています。 BOOL -トリガー」と「* トリガーの設定」スニペット。 editor.reset_trigger() " }, 
{ "title" : "デバイストレース ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_UUID-fb2803e2-9aa1-edc1-bfbe-5d0d052f53f0", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ デバイストレース ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "の作成 DeviceTrace ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737244690592", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ デバイストレース \/ の作成 DeviceTrace ", 
"snippet" : "myDevice = projects.primary.find(\"Device\")[0] devicetrace = trace.create(myDevice, \"DeviceTrace\")...", 
"body" : "myDevice = projects.primary.find(\"Device\")[0]\ndevicetrace = trace.create(myDevice, \"DeviceTrace\") " }, 
{ "title" : "デバイスの現在のトレース記録を照会する ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737246350891", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ デバイストレース \/ デバイスの現在のトレース記録を照会する ", 
"snippet" : "次のコードスニペットは、「Create a」に基づいています。 DeviceTrace 「スニペット。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0] # for application traces the result of get_online_traces contains only the traces of the application # traceObject = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\"...", 
"body" : "次のコードスニペットは、「Create a」に基づいています。 DeviceTrace 「スニペット。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0]\n\n# for application traces the result of get_online_traces contains only the traces of the application\n# traceObject = projects.primary.find(\"Device\", \"PLC Logic\", \"Application\", \"Trace\")[0]\neditor = traceObject.open_editor()\nfor tracepacket in editor.get_online_traces():\n print(tracepacket) " }, 
{ "title" : "既存のレコーディングをにダウンロードする DeviceTrace ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737250094566", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ デバイストレース \/ 既存のレコーディングをにダウンロードする DeviceTrace ", 
"snippet" : "次のコードスニペットは、「Create a」に基づいています。 DeviceTrace 「スニペット。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0] editor = traceObject.open_editor() editor.upload_to_device_trace(\"CpuCoreLoad\")...", 
"body" : "次のコードスニペットは、「Create a」に基づいています。 DeviceTrace 「スニペット。 traceObject = projects.primary.find(\"Device\", \"DeviceTrace\")[0]\neditor = traceObject.open_editor()\neditor.upload_to_device_trace(\"CpuCoreLoad\") " }, 
{ "title" : "で機能しないもの DeviceTrace ", 
"url" : "_trace_script_use_scripting_interface.html#UUID-8e241e83-fddc-67c5-15e4-8436a5cb79cc_section-idm234737269513402", 
"breadcrumbs" : "CODESYS トレース \/ トレーススクリプトインターフェイスの使用 \/ デバイストレース \/ で機能しないもの DeviceTrace ", 
"snippet" : "へのアクセス traceobject.variable_list を使用したトレース変数の作成 traceobject.add_variable()) へのアクセス  traceobject.diagrams...", 
"body" : "へのアクセス traceobject.variable_list を使用したトレース変数の作成 traceobject.add_variable()) へのアクセス  traceobject.diagrams " }, 
{ "title" : "トレースによるデータサンプリング ", 
"url" : "_cds_f_data_acquiring_with_trace.html", 
"breadcrumbs" : "CODESYS トレース \/ トレースによるデータサンプリング ", 
"snippet" : "とともに 痕跡 デジタルサンプリングオシロスコープと同様に、コントローラの変数の値の経過をたどることができます。トレースを使用するアプリケーションの実行時に、すべての命令がタスクサイクル内で最初に実行されます。次に、データの取得とタイムスタンプ付きの値の保存が開始されます。タイムスタンプは相対的であり、データ収集の開始時刻を参照します。データは時間離散信号になり、そのコースは CODESYS トレースエディタに表示されます。 値とタイムスタンプは「サンプル」、つまりデータレコードを形成します。ランタイムシステムは、サンプルを調整可能なサイズのバッファに書き込みます。 CODESYS データを要...", 
"body" : "とともに 痕跡 デジタルサンプリングオシロスコープと同様に、コントローラの変数の値の経過をたどることができます。トレースを使用するアプリケーションの実行時に、すべての命令がタスクサイクル内で最初に実行されます。次に、データの取得とタイムスタンプ付きの値の保存が開始されます。タイムスタンプは相対的であり、データ収集の開始時刻を参照します。データは時間離散信号になり、そのコースは CODESYS トレースエディタに表示されます。 値とタイムスタンプは「サンプル」、つまりデータレコードを形成します。ランタイムシステムは、サンプルを調整可能なサイズのバッファに書き込みます。 CODESYS データを要求し、トレースエディタのバッファに保存して、トレース図に時間の経過とともに関数として表示します CODESYS 最新のデータを表示できます。 データのサンプリングにトリガーを与えることができます。トリガを離すと、データのサンプリングが停止し、トリガ時刻付近のデータが表示されます。 トレースの構成と表示は、 CODESYS -トレースエディタのトレースオブジェクトを介して可能な投影。次の2つのオブジェクトタイプがあります。 痕跡 ：IECアプリケーションの下のデバイスツリーに添付されています。このようなオブジェクトには、常に純粋にアプリケーション固有のトレース構成が含まれています。次に、このトレース構成をコントローラーにロードして、アプリケーションで実行できます。 DeviceTrace ：デバイスオブジェクトの下のデバイスツリーにアタッチされます。制御デバイスが「トレースマネージャー」をサポートしている場合は、1つ以上を使用できます DeviceTrace -オブジェクトは、コントローラーで現在実行されている1つ以上のトレースにアクセスします。これらはアプリケーション関連である可能性がありますが、コントローラー固有のトレースでもあります。たとえば、コントローラーは、プロセッサー使用率を記録するためのトレースをサポートできます。メニューコマンドにより、 CODESYS デバイスのトレースマネージャーでプロジェクトを実行します。 IECコードからトレースマネージャにアクセスするには、ライブラリ関数を使用します CmpTraceMgr.library 可能。ライブラリのドキュメントも参照してください。 トレースを使用した継続的なデータ取得は、IECタスクのサイクルタイムの大幅な増加につながる可能性があります。 デバイスからログアウトした後も、トレースによるデータ取得は続行されます。 " }, 
{ "title" : "ランタイムシステムコンポーネントCmpTraceMgr、トレースマネージャー ", 
"url" : "_cds_f_data_acquiring_with_trace.html#UUID-1a20cc11-9b69-5f7f-6e67-22845545c8e9_section-idm4654689515584032658315282356", 
"breadcrumbs" : "CODESYS トレース \/ トレースによるデータサンプリング \/ ランタイムシステムコンポーネントCmpTraceMgr、トレースマネージャー ", 
"snippet" : "トレースマネージャを備えたLZSのデバイスの説明は、セクションに含まれています TargetSettings エントリ tracemanager 。 この場合、転送 CODESYS アプリケーションをコントローラーにロードするときのトレース構成のみ。トレースを開始すると、LZS上のアプリケーションは、トレースマネージャーを使用して構成を解釈し、データ取得を実行して、コントローラー上のデータレコードをバッファリングします。 ランタイムシステムコンポーネント CmpTraceMgr IECコードによるデータ取得と比較して拡張機能を提供します。 このようにして、次の値のデータ取得が可能です： プロセ...", 
"body" : "トレースマネージャを備えたLZSのデバイスの説明は、セクションに含まれています TargetSettings エントリ tracemanager 。 この場合、転送 CODESYS アプリケーションをコントローラーにロードするときのトレース構成のみ。トレースを開始すると、LZS上のアプリケーションは、トレースマネージャーを使用して構成を解釈し、データ取得を実行して、コントローラー上のデータレコードをバッファリングします。 ランタイムシステムコンポーネント CmpTraceMgr IECコードによるデータ取得と比較して拡張機能を提供します。 このようにして、次の値のデータ取得が可能です： プロセッサー負荷（cpuload、plcload）、CPUまたはバッテリーの温度曲線などのコントローラーのパラメーター マルチコアコントローラーでは、プロセッサーコア（cpuload）ごとのプロセッサー使用率を測定することが重要です。 ドライブの電流曲線などのデバイス信号 別のランタイムシステムコンポーネントのシステム変数 ダイアログでパラメータとIEC変数を設定できます トレース構成 下 可変設定 構成、設定。 コントローラで実行されているトレースは、DeviceTraceオブジェクトのトレースエディタで表示できます。 " }, 
{ "title" : "トリガー後のデータ取得 ", 
"url" : "_cds_f_data_acquiring_with_trace.html#UUID-1a20cc11-9b69-5f7f-6e67-22845545c8e9_section-idm453808684926243265831687739", 
"breadcrumbs" : "CODESYS トレース \/ トレースによるデータサンプリング \/ トリガー後のデータ取得 ", 
"snippet" : "イベントまたは条件に依存するデータを監視する場合は、トリガーに応じてデータ収集を有効にできます。実行時にアプリケーションは、イベントが発生したかどうか、または条件が満たされているかどうかを確認し、それに応じてデータをバッファリングします。 トレース構成により、以下を介してトリガーを起動できます。 イベントを表すトリガー変数 式としての条件 トリガー変数と条件の組み合わせ...", 
"body" : "イベントまたは条件に依存するデータを監視する場合は、トリガーに応じてデータ収集を有効にできます。実行時にアプリケーションは、イベントが発生したかどうか、または条件が満たされているかどうかを確認し、それに応じてデータをバッファリングします。 トレース構成により、以下を介してトリガーを起動できます。 イベントを表すトリガー変数 式としての条件 トリガー変数と条件の組み合わせ " }, 
{ "title" : "サンプルをファイルに保存 ", 
"url" : "_cds_f_data_acquiring_with_trace.html#UUID-1a20cc11-9b69-5f7f-6e67-22845545c8e9_section-idm4654689527510432658318271731", 
"breadcrumbs" : "CODESYS トレース \/ トレースによるデータサンプリング \/ サンプルをファイルに保存 ", 
"snippet" : "サンプルは、開発システムのファイルシステムにファイルとして保存できます。このファイルには、トレース構成を含めることもできます。 可能なファイル形式 ファイル拡張子 ファイルの種類 説明 *.trace ： トレースファイル XMLベースのストレージ形式のサンプルとトレース構成が含まれています コマンドでファイルをダウンロードできます ロードトレース オフラインでトレースエディタにロードし、コントローラを操作せずにサンプルを分析します。 *.txt テキストファイル ASCII形式のサンプルが含まれています 外部ツールを使用してファイルをさらに処理できます。 *.trace.csv トレースダン...", 
"body" : "サンプルは、開発システムのファイルシステムにファイルとして保存できます。このファイルには、トレース構成を含めることもできます。 可能なファイル形式 ファイル拡張子 ファイルの種類 説明 *.trace ： トレースファイル XMLベースのストレージ形式のサンプルとトレース構成が含まれています コマンドでファイルをダウンロードできます ロードトレース オフラインでトレースエディタにロードし、コントローラを操作せずにサンプルを分析します。 *.txt テキストファイル ASCII形式のサンプルが含まれています 外部ツールを使用してファイルをさらに処理できます。 *.trace.csv トレースダンプファイル トレース構成とオプションでサンプルを含むCSV形式のファイル コマンドを使用してファイルを作成できます シンボリックトレース構成のエクスポート 選択する。このファイルをコントローラーに転送して、アプリケーションにロードできます。その後、あなたは入ることができます CODESYS コマンドで ロードトレース それらをトレースエディタに表示します。 ただし、コマンドを使用することもできます トレース→トレースの保存 そしてそこにファイルタイプ *.trace.csv 選択する。このファイルをコントローラーに転送し、HMIを使用してロードおよび分析できます。 *.traceconfig シンボリックトレース構成 CSV形式のトレース構成が含まれています コマンドを使用してファイルを作成できます シンボリックトレース構成のエクスポート 選択する。ランタイムシステムコンポーネント CmpTraceMgr ファイルを読み取ることができます。 詳細については、以下を参照してください。 痕跡" }, 
{ "title" : "最初のステップ ", 
"url" : "_cds_trace_getting_started.html", 
"breadcrumbs" : "CODESYS トレース \/ 最初のステップ ", 
"snippet" : "プログラム PLC_PRG PROGRAM PLC_PRG VAR iVar : INT; rSin : REAL; rVar : REAL; END_VAR iVar := iVar + 1; iVar := iVar MOD 33; rVar := rVar + 0.1; rSin := 30 * SIN(rVar); 要件：アプリケーションはプログラムで実行されます PLC_PRG コントローラー上。 デバイスツリーでアプリケーションを選択し、コマンドで追加します プロジェクト→オブジェクトの追加 新しいトレースオブジェクトを追加します。 関連するトレースエディタが開き、メニューコマンド...", 
"body" : "プログラム PLC_PRG PROGRAM PLC_PRG\nVAR\n iVar : INT;\n rSin : REAL;\n rVar : REAL;\nEND_VAR\n\niVar := iVar + 1;\niVar := iVar MOD 33;\n\nrVar := rVar + 0.1;\nrSin := 30 * SIN(rVar); 要件：アプリケーションはプログラムで実行されます PLC_PRG コントローラー上。 デバイスツリーでアプリケーションを選択し、コマンドで追加します プロジェクト→オブジェクトの追加 新しいトレースオブジェクトを追加します。 関連するトレースエディタが開き、メニューコマンドが表示されます 痕跡 利用可能です。 コマンドを選択します トレース→構成 。 対話 トレース構成 が表示されます。 トレース機能を実行するタスクを選択します。通常、これはPLC_PRGが実行されているのと同じタスクです。 含む 変数を追加 トレース構成のツリービューにエントリを追加し、IEC変数を割り当てます。 例： PLC_PRG.rSin コマンドを選択します トレース→トレースダウンロード 。 CODESYS トレース構成をコントローラーにロードします。アプリケーションはデータ取得を開始し、データを送信します CODESYS 。そこで、それらはグラフとしてトレース図に表示されます。これで、サンプルをナビゲートし、データ収集を制御するためのコマンドができました。 " }, 
{ "title" : "例 ", 
"url" : "_cds_trace_getting_started.html#UUID-aa78deb4-8651-3794-2c7e-8126bafa7518_id_b64f3dddb917bc0a8640e01d1209e_id_1ecec4e8ed18f2ddc0a8655f018aaa35", 
"breadcrumbs" : "CODESYS トレース \/ 最初のステップ \/ 例 ", 
"snippet" : "IEC変数の正弦波の累積帰納法 PLC_PRG.rSin 痕跡 プログラム PLC_PRG コントローラ上で実行されます。スタートガイドに従うと、 CODESYS 次のトレース図。 （1）： 構成 （2）： 変数を追加...", 
"body" : "IEC変数の正弦波の累積帰納法 PLC_PRG.rSin 痕跡 プログラム PLC_PRG コントローラ上で実行されます。スタートガイドに従うと、 CODESYS 次のトレース図。 （1）： 構成 （2）： 変数を追加 " }, 
{ "title" : "トレース構成を作成する ", 
"url" : "_cds_trace_configuring.html", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する ", 
"snippet" : "完全なトレース構成には、少なくとも1つのタスクと1つの変数を指定してください。データ取得をトリガーするには、トリガーオプションを有効にしてトリガー変数を選択するか、記録条件を指定します。 実行時にトレース構成を編集する 要件：アプリケーションはコントローラー上で実行されており、トレース構成がロードされています。 トレース記録ツリーで変数をダブルクリックします。 ダイアログ トレース構成 開きます。 たとえば、色を変更します。 変数は、アプリケーションの実行を中断することなく、影響を受ける図に新しい色で表示されます。 トレース変数などの重要な設定を変更する場合は、トレース構成をコントローラーに再...", 
"body" : "完全なトレース構成には、少なくとも1つのタスクと1つの変数を指定してください。データ取得をトリガーするには、トリガーオプションを有効にしてトリガー変数を選択するか、記録条件を指定します。 実行時にトレース構成を編集する 要件：アプリケーションはコントローラー上で実行されており、トレース構成がロードされています。 トレース記録ツリーで変数をダブルクリックします。 ダイアログ トレース構成 開きます。 たとえば、色を変更します。 変数は、アプリケーションの実行を中断することなく、影響を受ける図に新しい色で表示されます。 トレース変数などの重要な設定を変更する場合は、トレース構成をコントローラーに再ロードする必要があります。 " }, 
{ "title" : "タスクを割り当てる ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_ea9cb39d8cc911e3bb368b4e89ceab52", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ タスクを割り当てる ", 
"snippet" : "このタスクでは、データ収集は実行時に実行されます。通常、変数が書き込まれるのと同じタスクが選択されます。 トレースオブジェクトをダブルクリックします。 トレースエディタが開き、メニューコマンドが表示されます 痕跡 自由に使用できます。 コマンドを選択します トレース→構成 。 対話 トレース構成 開きます。ツリービューで トレース記録 一番上のエントリが選択され、部分的なダイアログが右側にあります 録音設定 アクセス可能。 からの入力フィールドをクリックします タスク の上 。 アプリケーション全体で利用可能なすべてのタスクを含む選択リストが表示されます。 トレースのタスクを選択します。...", 
"body" : "このタスクでは、データ収集は実行時に実行されます。通常、変数が書き込まれるのと同じタスクが選択されます。 トレースオブジェクトをダブルクリックします。 トレースエディタが開き、メニューコマンドが表示されます 痕跡 自由に使用できます。 コマンドを選択します トレース→構成 。 対話 トレース構成 開きます。ツリービューで トレース記録 一番上のエントリが選択され、部分的なダイアログが右側にあります 録音設定 アクセス可能。 からの入力フィールドをクリックします タスク の上 。 アプリケーション全体で利用可能なすべてのタスクを含む選択リストが表示されます。 トレースのタスクを選択します。 " }, 
{ "title" : "トレース変数を構成する ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_8fd85a9b8cca11e3bb368b4e89ceab52", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ トレース変数を構成する ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 トレースエディタが開きます。メニューコマンド 痕跡 利用可能です。 コマンドを選択します 変数を追加 。 対話 トレース構成 開きます。右側は部分的なダイアログです 可変設定 アクセス可能。 設定の入力フィールドをクリックします 変数 の上 ダイアログで選択します 入力ヘルプ トレース変数。 変数はデータ収集用に構成されています。トレース記録ツリーと表示ツリーは、変数によって拡張されています。 リンクを選択してください 変数を追加 。 トレース記録ツリーと表示ツリーには、別の新しい変数が含まれています。変数の設定は右側にあります。 トレース変数を選...", 
"body" : "トレースオブジェクトをダブルクリックします。 トレースエディタが開きます。メニューコマンド 痕跡 利用可能です。 コマンドを選択します 変数を追加 。 対話 トレース構成 開きます。右側は部分的なダイアログです 可変設定 アクセス可能。 設定の入力フィールドをクリックします 変数 の上 ダイアログで選択します 入力ヘルプ トレース変数。 変数はデータ収集用に構成されています。トレース記録ツリーと表示ツリーは、変数によって拡張されています。 リンクを選択してください 変数を追加 。 トレース記録ツリーと表示ツリーには、別の新しい変数が含まれています。変数の設定は右側にあります。 トレース変数を選択します。 でダイアログを終了します わかった 。 変数はトレース変数であり、トレース変数リストに表示されます。 " }, 
{ "title" : "トレース変数を削除します ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_a2de7471341611e4aaeacbabfc46bd6b", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ トレース変数を削除します ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 トレース記録ツリーの変数をクリックします。 リンクをクリックしてください 変数を削除します または使用する 距離 。 でダイアログを終了します わかった 。 変数はトレース変数リストから削除されます。...", 
"body" : "トレースオブジェクトをダブルクリックします。 トレース記録ツリーの変数をクリックします。 リンクをクリックしてください 変数を削除します または使用する 距離 。 でダイアログを終了します わかった 。 変数はトレース変数リストから削除されます。 " }, 
{ "title" : "トレースパラメータ ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_24994be39fc411e4ac0cf998f94f5673", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ トレースパラメータ ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 コマンドを選択します 変数を追加 。 対話 トレース構成 開きます。右側は部分的なダイアログです 可変設定 アクセス可能。 クリック （設定の右側 変数 、入力フィールドの左側）。 ドロップダウンリストからオプションを選択します パラメータ 。 クリック ダイアログで選択します 入力ヘルプ パラメータ。 パラメータの表現を設定します。 でダイアログを終了します わかった 。 パラメータがトレースされ、トレース変数リストに表示されます。...", 
"body" : "トレースオブジェクトをダブルクリックします。 コマンドを選択します 変数を追加 。 対話 トレース構成 開きます。右側は部分的なダイアログです 可変設定 アクセス可能。 クリック （設定の右側 変数 、入力フィールドの左側）。 ドロップダウンリストからオプションを選択します パラメータ 。 クリック ダイアログで選択します 入力ヘルプ パラメータ。 パラメータの表現を設定します。 でダイアログを終了します わかった 。 パラメータがトレースされ、トレース変数リストに表示されます。 " }, 
{ "title" : "トリガートリガーを構成する ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_f9249f7c1ba811e49e4c9341d3e603a5", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ トリガートリガーを構成する ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 トレースエディタが開き、メニューコマンドが表示されます 痕跡 利用可能です。 コマンドを選択します トレース→構成 。 対話 トレース構成 が表示されます。右側は部分的なダイアログです 録音設定 アクセス可能。 オプションを有効にする トリガーをアクティブにする 。 データ収集を実行するタスクを選択します。 入力フィールドで次から選択します トリガー変数 変数。 でダイアログを終了します わかった 。 データ取得がトリガーされます。 トリガー時間は、ランタイム図で黒い線でマークされています。 アプリケーションをロードして起動します。 選ぶ トレース...", 
"body" : "トレースオブジェクトをダブルクリックします。 トレースエディタが開き、メニューコマンドが表示されます 痕跡 利用可能です。 コマンドを選択します トレース→構成 。 対話 トレース構成 が表示されます。右側は部分的なダイアログです 録音設定 アクセス可能。 オプションを有効にする トリガーをアクティブにする 。 データ収集を実行するタスクを選択します。 入力フィールドで次から選択します トリガー変数 変数。 でダイアログを終了します わかった 。 データ取得がトリガーされます。 トリガー時間は、ランタイム図で黒い線でマークされています。 アプリケーションをロードして起動します。 選ぶ トレース→トレースのダウンロード 。 トレース構成がロードされます。トリガーがトリガーされた後、ランタイムシステムはトレース変数の値の履歴を保存します。データはトレースエディタに表示されます。トリガーがトリガーされた時刻は、図に黒い線で示されています。 " }, 
{ "title" : "タイムライン表示を構成する ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_b54f86141bac11e49e4c9341d3e603a5", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ タイムライン表示を構成する ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 リンクをクリックしてください 構成 、構成ツリーの上にあります。 対話 トレース構成 開きます。 表現ツリーで選択します（下 表現（図） ）エントリ タイムライン 。 タイムライン表示設定は右側に表示されます。 設定を変更して、リンクをクリックします プレビュー 。 変更は、座標系のプレビューで視覚化されます。 表現ツリーでエントリを選択します Y軸 。エントリ Y軸 構成された各チャートの下にあります。したがって、値軸の表示は、ダイアグラムごとに個別に設定できます。 右側は部分的なダイアログです ディスプレイの設定 選択した軸の。 設定を変更しま...", 
"body" : "トレースオブジェクトをダブルクリックします。 リンクをクリックしてください 構成 、構成ツリーの上にあります。 対話 トレース構成 開きます。 表現ツリーで選択します（下 表現（図） ）エントリ タイムライン 。 タイムライン表示設定は右側に表示されます。 設定を変更して、リンクをクリックします プレビュー 。 変更は、座標系のプレビューで視覚化されます。 表現ツリーでエントリを選択します Y軸 。エントリ Y軸 構成された各チャートの下にあります。したがって、値軸の表示は、ダイアグラムごとに個別に設定できます。 右側は部分的なダイアログです ディスプレイの設定 選択した軸の。 設定を変更します。 変更は、座標系プレビューに適用されます。 対話を終了する トレース構成 OKで。 表示の変更は、影響を受けるチャートに反映されます。 " }, 
{ "title" : "トレース変数の表示を構成する ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_df387bd88cca11e3bb368b4e89ceab52", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ トレース変数の表示を構成する ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 リンクをクリックしてください 構成 。 対話 トレース構成 開きます。 下から選択 トレース記録 変数。 右側は部分的なダイアログです 可変設定 選択した変数の。 設定などの設定を変更する 線種 。 でダイアログを終了します わかった 。 表示の変更は、影響を受けるチャートに反映されます。...", 
"body" : "トレースオブジェクトをダブルクリックします。 リンクをクリックしてください 構成 。 対話 トレース構成 開きます。 下から選択 トレース記録 変数。 右側は部分的なダイアログです 可変設定 選択した変数の。 設定などの設定を変更する 線種 。 でダイアログを終了します わかった 。 表示の変更は、影響を受けるチャートに反映されます。 " }, 
{ "title" : "LZS上のデータ用のバッファーを構成します ", 
"url" : "_cds_trace_configuring.html#UUID-3419c5f6-ccd8-e055-28dc-0294c52b660d_id_f531a75433cf4db9c0a8640e01896e65_id_30b2fca40b4611e48be4a888be20ac74", 
"breadcrumbs" : "CODESYS トレース \/ トレース構成を作成する \/ LZS上のデータ用のバッファーを構成します ", 
"snippet" : "トレースオブジェクトをダブルクリックします。 コマンドを選択します トレース→構成 。 対話 トレース構成 開きます。右側は部分的なダイアログです 録音設定 アクセス可能。 ボタンをクリックします 高度 。 対話 高度なトレース設定 開きます。 設定を変更する nサイクルごとの測定 また サンプルの推奨LZSバッファサイズ 。 でダイアログを終了します わかった 。 バッファ設定が再構成されます。これらは、次にトレース構成がLZSにロードされるときに適用されます。...", 
"body" : "トレースオブジェクトをダブルクリックします。 コマンドを選択します トレース→構成 。 対話 トレース構成 開きます。右側は部分的なダイアログです 録音設定 アクセス可能。 ボタンをクリックします 高度 。 対話 高度なトレース設定 開きます。 設定を変更する nサイクルごとの測定 また サンプルの推奨LZSバッファサイズ 。 でダイアログを終了します わかった 。 バッファ設定が再構成されます。これらは、次にトレース構成がLZSにロードされるときに適用されます。 " }, 
{ "title" : "制御データ収集 ", 
"url" : "_cds_trace_controlling_the_data_acquiring.html", 
"breadcrumbs" : "CODESYS トレース \/ 制御データ収集 ", 
"snippet" : "メニューコマンドを使用してデータ収集を制御できます。 要件：アプリケーションがランタイムシステムにロードされ、トレースが構成されている。 メニューコマンド トレース→ トレースをダウンロード トレース→ トレースを開始 トレース→ トレースを停止します トレース→ トリガーをリセット...", 
"body" : "メニューコマンドを使用してデータ収集を制御できます。 要件：アプリケーションがランタイムシステムにロードされ、トレースが構成されている。 メニューコマンド トレース→ トレースをダウンロード トレース→ トレースを開始 トレース→ トレースを停止します トレース→ トリガーをリセット " }, 
{ "title" : "コントローラのすべてのトレースへのアクセス ", 
"url" : "_cds_trace_accessing_them_all_on_the_control.html", 
"breadcrumbs" : "CODESYS トレース \/ コントローラのすべてのトレースへのアクセス ", 
"snippet" : "コントローラがランタイムシステムコンポーネントの場合 CmpTraceMgr （Tracemanager）サポートされています。 CODESYS 現在コントローラーで実行されているすべてのトレースにアクセスするプロジェクト。 IEC変数の値を記録するアプリケーション関連のトレースに加えて、これらは、たとえばデバイスの信号値やプロセッサの使用率を記録するために、純粋にコントローラー固有のトレースにすることもできます。 コントローラで実行され、プロジェクトに表示するトレースごとに個別のトレースを作成する必要があります DeviceTrace -デバイスツリーにオブジェクトを挿入します。 このオブジ...", 
"body" : "コントローラがランタイムシステムコンポーネントの場合 CmpTraceMgr （Tracemanager）サポートされています。 CODESYS 現在コントローラーで実行されているすべてのトレースにアクセスするプロジェクト。 IEC変数の値を記録するアプリケーション関連のトレースに加えて、これらは、たとえばデバイスの信号値やプロセッサの使用率を記録するために、純粋にコントローラー固有のトレースにすることもできます。 コントローラで実行され、プロジェクトに表示するトレースごとに個別のトレースを作成する必要があります DeviceTrace -デバイスツリーにオブジェクトを挿入します。 このオブジェクトにデバイスからのトレースを表示するには、PLCへの接続が正しく構成されている必要があります（ 通信設定 ）。次に、次のメニューコマンドのいずれかを使用します。 トレース→ トレースをアップロード ：PLCデバイスへの接続を確立し、ダイアログを開きます オンラインリスト コントローラからトレースを選択するには トレース→ オンラインリスト ：オンラインモードでのみ使用可能：ダイアログも開きます オンラインリスト これで、コントローラーからアップロードされたトレースを開始して、DeviceTraceオブジェクトのエディターで追跡できます。表示の視覚的構成（色、ラベル付けなど）は、プロジェクトでアプリケーション変数用に構成されたトレースの場合と同じです。 DeviceTrace Editorを閉じると、コントローラーへの接続が終了します。 最後に開いたものを閉じると注意してください DeviceTrace -エディタは、コントローラへの接続も終了します！プロジェクトにデバイストレースを再度表示するには、デバイストレースをプロジェクトに再入力する必要があります。 DeviceTrace -オブジェクトをロードします。 現在、エディターを閉じることは、コントローラーへの接続を意識的に終了するための推奨手順でもあります。これにはログアウトだけでは不十分です。 のDeviceTraceオブジェクトでのCPU使用率 CODESYS -プロジェクトを表示（例） 要件：トレースマネージャをサポートするPLCデバイスを使用している。ここで説明する例では、 CODESYS Control Win 。このデバイスは、個々のプロセッサコアの使用率のトレースを提供します（ CpuLoad ）、およびランタイムシステムによって引き起こされたプロセッサ負荷のトレース（ PlcLoad ）。マルチコア機能を使用する場合、プロジェクトでのプロセッサコア使用率の可能な表現が役立つ場合があります。 プロジェクトで、 通信設定 制御装置に。 デバイスツリーでPLCエントリを選択し、オブジェクトを追加します DeviceTrace に。 名前 DeviceTrace 彼の中で プロパティ 「Trace_PlcLoad」に。 トレースエディタにフォーカスを置き、コマンドを選択します トレース→トレースのアップロード 。 コントローラへの接続が確立され、ダイアログが表示されます オンラインリスト 開きます。 ダイアログでエントリを選択します PlcLoad ダイアログでコマンドを選択します アップロード 。 [OK]をクリックしてダイアログを閉じます。 ランタイムシステムでのプロセッサ使用率のいくつかのトレースウィンドウがトレースエディタに表示されます。これらは、個々のコアのトレースと平均値のトレースです。いずれの場合も、「サンプルは記録されていません。」というテキストが表示されます。 コマンドを選択します トレース→トレース開始 。 4つのパラメータのトレース記録が表示されます。 のトレースも使用する場合 CpuLoad プロセッサコアごとに、プロジェクトでの平均値を表示したい場合は、別の値を追加します DeviceTrace デバイスツリー内のオブジェクト。たとえば、「Trace_CpuLoad」という名前を付けます。そのエディターで、上記のようにトレースをロードして開始します CPULoad 。 これで、プロジェクト内のすべてのトレースをたどることができます。 表示を光学的に変更する場合は、関連するトレースエディタウィンドウでコマンドを選択します 構成 構成ダイアログにアクセスします。プロジェクトで作成されたIEC変数トレースの場合と同様に、変数の割り当てを除いて、これらのダイアログを使用できます。 コントローラへの接続を終了するには、開いているすべてのDeviceTraceエディタウィンドウを閉じます。デバイスにログインしている場合は、ログアウトして接続を終了するだけでは不十分です。 " }, 
{ "title" : "トレースデータのナビゲート ", 
"url" : "_cds_trace_navigating_in_the_data.html", 
"breadcrumbs" : "CODESYS トレース \/ トレースデータのナビゲート ", 
"snippet" : "メニューコマンドを使用して、トレースチャートデータをナビゲートできます。 要件：アプリケーションはオンラインモードです。 メニューコマンド トレース→ カーソル トレース→ マウスでズーム トレース→ 表示方法をリセットする トレース→ 自動スケール トレース→ 圧縮 トレース→ ストレッチ トレース→ シングルチャンネルに変換 トレース→ マルチチャネルに変換...", 
"body" : "メニューコマンドを使用して、トレースチャートデータをナビゲートできます。 要件：アプリケーションはオンラインモードです。 メニューコマンド トレース→ カーソル トレース→ マウスでズーム トレース→ 表示方法をリセットする トレース→ 自動スケール トレース→ 圧縮 トレース→ ストレッチ トレース→ シングルチャンネルに変換 トレース→ マルチチャネルに変換 " }, 
{ "title" : "トレースを管理する ", 
"url" : "_cds_trace_managing_data.html", 
"breadcrumbs" : "CODESYS トレース \/ トレースを管理する ", 
"snippet" : "メニューコマンドを使用して、さまざまな形式でトレースをロードおよび保存できます。 メニューコマンド トレース→ トレースを保存 トレース→ ロードトレース トレース→ シンボリックトレース構成のエクスポート...", 
"body" : "メニューコマンドを使用して、さまざまな形式でトレースをロードおよび保存できます。 メニューコマンド トレース→ トレースを保存 トレース→ ロードトレース トレース→ シンボリックトレース構成のエクスポート " }, 
{ "title" : "統計を表示 ", 
"url" : "_cds_trace_displaying_statistic.html", 
"breadcrumbs" : "CODESYS トレース \/ 統計を表示 ", 
"snippet" : "CODESYS 記録されたデータを統計的に評価して表示し、キャッシュに保存できるようにします。あなたはそのためのコマンドを持っています トレース→ 統計学 処分する。...", 
"body" : "CODESYS 記録されたデータを統計的に評価して表示し、キャッシュに保存できるようにします。あなたはそのためのコマンドを持っています トレース→ 統計学 処分する。 " }, 
{ "title" : "参考: ユーザーインターフェース ", 
"url" : "_trace_reference_user_interface.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "オブジェクト ", 
"url" : "_trace_objects.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "オブジェクト: トレース ", 
"url" : "_cds_obj_trace.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト \/ オブジェクト: トレース ", 
"snippet" : "痕跡 シンボル： タイプのオブジェクト 痕跡 1つ以上のチャートでアプリケーション固有のトレースデータを構成および表示するために使用されます。アプリケーションの実行時に、トレース変数の値曲線。これは、のトレースエディタで監視できます。 CODESYS この間、コントローラーに記録されます。要件は、トレース構成が構成されてコントローラーに転送され、トレース記録が開始されていることです。サンプリングされたデータは開発システムに送信され、構成に応じてチャートに表示されます。トレースするときにデータをナビゲートできます。 詳細については、以下を参照してください。 トレースによるデータサンプリングコント...", 
"body" : "痕跡 シンボル： タイプのオブジェクト 痕跡 1つ以上のチャートでアプリケーション固有のトレースデータを構成および表示するために使用されます。アプリケーションの実行時に、トレース変数の値曲線。これは、のトレースエディタで監視できます。 CODESYS この間、コントローラーに記録されます。要件は、トレース構成が構成されてコントローラーに転送され、トレース記録が開始されていることです。サンプリングされたデータは開発システムに送信され、構成に応じてチャートに表示されます。トレースするときにデータをナビゲートできます。 詳細については、以下を参照してください。 トレースによるデータサンプリングコントローラがトレースマネージャをサポートしている場合は、 'を使用できます。 DeviceTrace 'コントローラーで実行されているすべてのトレースにアクセスするには、トレースマネージャーでオブジェクトタイプを入力します。 トレースオブジェクトをダブルクリックすると、トレースエディタが開きます。対応するツールバーには、最も重要なトレースコマンドが含まれています。トレース変数リストには、値曲線が記録されている変数が表示されます。 （1）：トレースエディタのツールバー （2）：トレースエディタ （3）：トレース変数リスト （4）：トレース構成へのリンク 構成 変数を追加 " }, 
{ "title" : "トレースエディタのツールバー ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_9c96894e3a54c71fc0a8653601c0734d", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト \/ オブジェクト: トレース \/ トレースエディタのツールバー ", 
"snippet" : "： トレースをダウンロード： トレースを開始： トレースを停止します： トリガーをリセット： マウスでズーム ： 表示方法をリセットする： 自動スケール： カーソル： 圧縮： ストレッチ...", 
"body" : "： トレースをダウンロード： トレースを開始： トレースを停止します： トリガーをリセット： マウスでズーム ： 表示方法をリセットする： 自動スケール： カーソル： 圧縮： ストレッチ" }, 
{ "title" : "トレースエディタ ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_1e6f1b31635a8e3ac0a8640e016cc6dd", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト \/ オブジェクト: トレース \/ トレースエディタ ", 
"snippet" : "アプリケーションの実行時に、トレースコンポーネントの実行時システムバッファは記録されたサンプルで満たされます。データは開発システムに送信され、そのトレースエディタバッファに保存されます。トレースエディタはこのデータにアクセスし、時間の経過とともにグラフとしてグラフに表示します。トレースエディタを閉じると、トレースエディタのバッファが再び解放されます。 詳細については、以下を参照してください。 制御データ収集メニューコマンドを使用して、トレースを制御します。さらに、メニューコマンド、キーボードショートカット、およびマウス入力を使用して、データ内を移動できます。 詳細については、以下を参照してくだ...", 
"body" : "アプリケーションの実行時に、トレースコンポーネントの実行時システムバッファは記録されたサンプルで満たされます。データは開発システムに送信され、そのトレースエディタバッファに保存されます。トレースエディタはこのデータにアクセスし、時間の経過とともにグラフとしてグラフに表示します。トレースエディタを閉じると、トレースエディタのバッファが再び解放されます。 詳細については、以下を参照してください。 制御データ収集メニューコマンドを使用して、トレースを制御します。さらに、メニューコマンド、キーボードショートカット、およびマウス入力を使用して、データ内を移動できます。 詳細については、以下を参照してください。 トレースデータのナビゲート" }, 
{ "title" : "トレース変数リスト ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_330149a30c689227c0a864631a27b88d", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト \/ オブジェクト: トレース \/ トレース変数リスト ", 
"snippet" : "トレース変数リストは、現在のトレース構成の概要を提供します。リストには、それぞれのトレース変数を持つすべてのチャートがテーブルに表示されます。トレース変数をダブルクリックすると、 トレース構成 ダイアログも開き、変数設定が表示されます。 リストボックスは、 インスタンスパスを非表示にする 指図。 インスタンスパスを非表示にする リスト内の変数名の表示 ：フルインスタンスパスを持つ変数名 例： PLC_PRG.iCounter チャート チャートの表形式の表示 名前 それぞれの変数を持つチャートのリスト チャート<n> ：チャートが表示されます。 選択した名前をクリックすると、チャート名を変更で...", 
"body" : "トレース変数リストは、現在のトレース構成の概要を提供します。リストには、それぞれのトレース変数を持つすべてのチャートがテーブルに表示されます。トレース変数をダブルクリックすると、 トレース構成 ダイアログも開き、変数設定が表示されます。 リストボックスは、 インスタンスパスを非表示にする 指図。 インスタンスパスを非表示にする リスト内の変数名の表示 ：フルインスタンスパスを持つ変数名 例： PLC_PRG.iCounter チャート チャートの表形式の表示 名前 それぞれの変数を持つチャートのリスト チャート<n> ：チャートが表示されます。 選択した名前をクリックすると、チャート名を変更できます。 <変数> ：変数が表示されます。 ラインエディタで選択した名前をクリックすると、変数名を変更できます。 を選択すると チャート<n> 表では、対応するチャートもエディターで選択されています。これも逆に機能します。 カーソル<n> カーソル位置のY値 デルタ からのY値のデルタ カーソル2 に カーソル1 マルチセレクション 複数選択では、テンキーを使用できます * と \/ 選択したグラフを展開および折りたたむ。 チャートと変数をドラッグして並べ替えたり、他のチャートに移動したりできます。いつ Ctrl キーを押すと、変数がコピーされます。これはオンラインモードでも可能です。 トレース変数リストのコンテキストメニュー 変数を追加 新しいトレース変数を追加し、 トレース構成 可変設定のダイアログ の入力フィールドで変数を選択します 変数 その値曲線をトレースするための設定。 見える 対応する図のグラフ（値曲線またはトレース変数）の表示を切り替えます。 ： 見える ： 隠れた 複数選択によってトレース変数リストで複数のチャートまたは変数が選択されている場合、これらのグラフの表示を切り替えることができます。 ディスプレイモード を開きます トレース構成 ダイアログ で構成アイテムを選択します トレースレコード ツリービューまたは プレゼンテーション（図） 。 構成 を開きます トレース構成 ダイアログ The 可変設定 右側に表示されます。 " }, 
{ "title" : "トレース図でのナビゲート ", 
"url" : "_cds_obj_trace.html#UUID-67c980c3-c641-1595-adc7-5a23733b101d_id_aa1ac80902c0a8640e00008c23_id_816e2c47117e11e49907a46cfb48b36f", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト \/ オブジェクト: トレース \/ トレース図でのナビゲート ", 
"snippet" : "マウス入力あり マウスによるユーザー入力 ユーザー入力中のマウスカーソル記号 効果 X軸に沿ってグラフをドラッグします。 時間軸（X軸）に沿ってすべてのチャートのトレースグラフを同時にスクロールします を押し続けます Ctrl キーを押して、グラフをY軸に沿ってドラッグします。 選択したチャートのトレースグラフをY軸に沿ってスクロールします マウスホイールを後方に回転させます。 時間軸を圧縮します（ シンボル） マウスホイールを前方に回転させます。 時間軸をストレッチします（ シンボル） を長押しします Ctrl キーを押して、マウスホイールを後方に回します。 Y軸を圧縮します を長押しします...", 
"body" : "マウス入力あり マウスによるユーザー入力 ユーザー入力中のマウスカーソル記号 効果 X軸に沿ってグラフをドラッグします。 時間軸（X軸）に沿ってすべてのチャートのトレースグラフを同時にスクロールします を押し続けます Ctrl キーを押して、グラフをY軸に沿ってドラッグします。 選択したチャートのトレースグラフをY軸に沿ってスクロールします マウスホイールを後方に回転させます。 時間軸を圧縮します（ シンボル） マウスホイールを前方に回転させます。 時間軸をストレッチします（ シンボル） を長押しします Ctrl キーを押して、マウスホイールを後方に回します。 Y軸を圧縮します を長押しします Ctrl キーを押して、マウスホイールを前方に回します。 Y軸を伸ばします 要件：1つまたは2つのトレースカーソルがアクティブになっています。 トレースカーソルの三角形を時間軸に沿った別の位置にドラッグします。 トレース変数リストのY値を同時に更新します 最初の値：左カーソルの位置のY値 2番目の値：右カーソルの位置のY値 3番目の値：両方の値の差 要件： マウスズーム がアクティブになります（ ）。 長方形を伸ばします。 すべてのグラフのトレースグラフを長方形にズームします キーボードショートカット付き キーボードショートカット 効果 要件：トレースカーソルモードがアクティブ化されていません。 左矢印 右矢印 時間軸に沿って同時にすべてのチャートのトレースグラフをスクロールします 上矢印 下矢印 選択したチャートのトレースグラフをY軸に沿ってスクロールします 要件：1つまたは2つのトレースカーソルがアクティブになっています。 Alt + 左矢印 Alt + 右矢印 時間軸に沿って同時にすべてのチャートのトレースグラフをスクロールします - 時間軸を圧縮します（ シンボル） + X軸を伸ばします（ シンボル） Ctrl + - 選択したチャートのY軸を圧縮します Ctrl + + 選択したチャートのY軸を引き伸ばします タブ 次に下のグラフを選択します 要件：1つまたは2つのトレースカーソルがアクティブになっています。 左矢印 右矢印 黒のトレースカーソルを移動します 要件：2つのトレースカーソルがアクティブになっています。 シフト + 左矢印 シフト + 右矢印 灰色のトレースカーソルを移動します " }, 
{ "title" : "オブジェクト：DeviceTrace ", 
"url" : "_cds_obj_devicetrace.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ オブジェクト \/ オブジェクト：DeviceTrace ", 
"snippet" : "DeviceTrace シンボル： A DeviceTrace オブジェクトは、1つまたは複数の図にトレースデータを表示します。 痕跡 物体。 違いは、 DeviceTrace 直接 アクセス コントローラで実行されているトレース。オブジェクトは、デバイスツリーのデバイスの下に挿入されます。したがって、アプリケーションに直接依存することはありません。 CODESYS 事業。 DeviceTrace を使用すると、「マルチコア」コントローラーのプロセッサー負荷を視覚化して表示できます。 「マルチコア」の詳細については、以下を参照してください。 マルチコア エディターとその操作の詳細については、エ...", 
"body" : "DeviceTrace シンボル： A DeviceTrace オブジェクトは、1つまたは複数の図にトレースデータを表示します。 痕跡 物体。 違いは、 DeviceTrace 直接 アクセス コントローラで実行されているトレース。オブジェクトは、デバイスツリーのデバイスの下に挿入されます。したがって、アプリケーションに直接依存することはありません。 CODESYS 事業。 DeviceTrace を使用すると、「マルチコア」コントローラーのプロセッサー負荷を視覚化して表示できます。 「マルチコア」の詳細については、以下を参照してください。 マルチコア エディターとその操作の詳細については、エディターのヘルプ ページを参照してください。 痕跡 物体。 " }, 
{ "title" : "ダイアログ ", 
"url" : "_trace_dialogs.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "ダイアログ：トレース構成 ", 
"url" : "_cds_dlg_trace_configuration.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 ", 
"snippet" : "トレース構成 シンボル： 関数 : ダイアログには、 データサンプリング 。 電話 トレース→構成 指図;コンテキストメニュー 構成 トレースエディタのリンク 変数を追加 トレースエディタのリンク 要件 ：トレースオブジェクトのエディタが開いていてアクティブです。 詳細については、以下を参照してください。 トレース構成を作成する...", 
"body" : "トレース構成 シンボル： 関数 : ダイアログには、 データサンプリング 。 電話 トレース→構成 指図;コンテキストメニュー 構成 トレースエディタのリンク 変数を追加 トレースエディタのリンク 要件 ：トレースオブジェクトのエディタが開いていてアクティブです。 詳細については、以下を参照してください。 トレース構成を作成する" }, 
{ "title" : "トレースレコード ツリー表示 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_2d26d5993a2511e7a72e97101ee2f5a3", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 \/ トレースレコード ツリー表示 ", 
"snippet" : "ツリービューには、トレースされる変数が一覧表示され、変数設定にアクセスできます。 選択したトレース名 The 記録設定 サブダイアログが右側に表示されます。 選択したトレース変数 The 変数設定 サブダイアログが右側に表示されます。 コンテキストメニューコマンド ： 変数を追加 新しいトレース変数を追加します The 変数設定 サブダイアログが右側に開き、部分的に構成されています。の入力フィールドで変数を選択します 変数 その値曲線をトレースするための設定。 ダイアグラムに割り当てる 選択した変数が現在表示されていない図（右側のサブメニュー）を一覧表示します ダイアグラムを選択して、そこに変...", 
"body" : "ツリービューには、トレースされる変数が一覧表示され、変数設定にアクセスできます。 選択したトレース名 The 記録設定 サブダイアログが右側に表示されます。 選択したトレース変数 The 変数設定 サブダイアログが右側に表示されます。 コンテキストメニューコマンド ： 変数を追加 新しいトレース変数を追加します The 変数設定 サブダイアログが右側に開き、部分的に構成されています。の入力フィールドで変数を選択します 変数 その値曲線をトレースするための設定。 ダイアグラムに割り当てる 選択した変数が現在表示されていない図（右側のサブメニュー）を一覧表示します ダイアグラムを選択して、そこに変数を表示します。 このコマンドは、ツリービューで変数が選択されている場合に使用できます。 ヒント：コマンドを無効にすると、変数はすでにすべての図に表示されています。 有効 デフォルトで有効 無効にされた変数は灰色で表示されます。それらは表示も記録もされません。 " }, 
{ "title" : "プレゼンテーション（図） ツリー表示 ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_e90b0fb3635a8e3bc0a8640e00f68bf2", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 \/ プレゼンテーション（図） ツリー表示 ", 
"snippet" : "ツリービューには、トレースエディタに表示される図が一覧表示され、表示モードにアクセスできます。 選択したノード： 時間軸 The ディスプレイモード 時間軸のサブダイアログが右側に表示されます。時間軸の表示を指定できます。下記参照。 選択した図の名前 ダイアグラムの座標系とプレビューの設定が右側に表示されます。下記参照。 選択したノード： Y軸 The ディスプレイモード サブダイアログが右側に表示されます。軸表示を指定できます。下記参照。 変数を表示する 選択したトレース変数 The 変数設定 サブダイアログが右側に表示されます。トレース変数を構成できます。下記参照。 注：これらは、でアクセ...", 
"body" : "ツリービューには、トレースエディタに表示される図が一覧表示され、表示モードにアクセスできます。 選択したノード： 時間軸 The ディスプレイモード 時間軸のサブダイアログが右側に表示されます。時間軸の表示を指定できます。下記参照。 選択した図の名前 ダイアグラムの座標系とプレビューの設定が右側に表示されます。下記参照。 選択したノード： Y軸 The ディスプレイモード サブダイアログが右側に表示されます。軸表示を指定できます。下記参照。 変数を表示する 選択したトレース変数 The 変数設定 サブダイアログが右側に表示されます。トレース変数を構成できます。下記参照。 注：これらは、でアクセスできる設定と同じです。 トレースレコード ツリー表示。 コンテキストメニューコマンド ： ダイアグラムを追加 以下に新しい図を追加し、 プレゼンテーション（図） ツリー表示 ： 新しい変数を追加する 新しいトレース変数を追加します The 変数設定 サブダイアログが右側に開き、部分的に構成されています。の入力フィールドで変数を選択します 変数 その値曲線をトレースするための設定。その表示を指定します。さらに、変数は選択したダイアグラムに割り当てられます。 既存の変数を追加する 選択した図が現在表示されていないすべてのトレース変数（右側のサブメニュー）を一覧表示します 選択した図に表示するには、変数を選択します。 ヒント：コマンドを無効にすると、選択した図にすべてのトレース変数がすでに表示されています。 " }, 
{ "title" : "記録設定 サブダイアログ ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_565148569fb211e4ac0cf998f94f5673", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 \/ 記録設定 サブダイアログ ", 
"snippet" : "要件：最上位ノードが選択されている トレースレコード ツリー表示。 トリガーを有効にする ：トリガーが有効になっています。トレースデータは、トリガー信号が送信された場合にのみ実行時にバッファリングされます。トリガー信号がどのように送信されるかを決定します トリガー変数 、 トリガーパラメーター 、 トリガーエッジ 、 ポストトリガー（サンプル） 、 と トリガーレベル 設定。 ：現在のデータセットの連続表示 トリガー変数 トリガーとして使用されるシグナル 完全なインスタンスパスが必要です。 有効なトリガー信号は、IEC変数、プロパティ、参照、ポインター、アプリケーションの配列要素、または式です...", 
"body" : "要件：最上位ノードが選択されている トレースレコード ツリー表示。 トリガーを有効にする ：トリガーが有効になっています。トレースデータは、トリガー信号が送信された場合にのみ実行時にバッファリングされます。トリガー信号がどのように送信されるかを決定します トリガー変数 、 トリガーパラメーター 、 トリガーエッジ 、 ポストトリガー（サンプル） 、 と トリガーレベル 設定。 ：現在のデータセットの連続表示 トリガー変数 トリガーとして使用されるシグナル 完全なインスタンスパスが必要です。 有効なトリガー信号は、IEC変数、プロパティ、参照、ポインター、アプリケーションの配列要素、または式です。許可されるタイプはすべてIECベースのタイプです それ外 STRING 、 WSTRING 、 と ARRAY 。基本型がそうでない場合、列挙は許可されます STRING 、 WSTRING 、 また ARRAY 。ポインタの内容は有効なシグナルではありません。 ランタイムシステムが CmpTraceMgr コンポーネント、にリンクされているプロパティ 'monitoring' その後、属性を変数としてサンプリングできます。 トリガーパラメーター トリガーとして使用されるシステムパラメータ The 入力アシスタント ダイアログには、有効なシステムパラメータがすべて一覧表示されます。 パラメーター のカテゴリ カテゴリ タブ。 の選択を可能にします トリガー変数 また トリガーパラメーター トリガーエッジ トリガーのエッジ検出を定義します ： ポジティブ ブールトリガー変数の場合、トリガーは値がから変更されたときに発生します FALSE に TRUE 。 アナログトリガー変数の場合、トリガーは、 トリガーレベル 「下から」到達します。 ： ネガティブ ブールトリガー変数の場合、トリガーは値がから変更されたときに発生します TRUE に FALSE 。 アナログトリガー変数の場合、トリガーは、 トリガーレベル 「上から」到達します。 ： どちらも ブールトリガー変数の場合、値が変更されるとトリガーが発生します。 アナログトリガー変数の場合、トリガーは、 トリガーレベル が達成された。 ポストトリガー（サンプル） トリガー後にバッファリングされるトレース変数ごとのサンプル数 ディフォルト： 50 値の範囲： 0 に 2 32 -1 トリガーレベル トリガーを開始するために到達する値 仕事 データが記録されるタスク 記録条件 実行時に、アプリケーションはレコード条件をチェックします。それが満たされると、トレースデータがバッファリングされます。 でデータサンプリングの条件を記録する CmpTraceMgr ランタイムシステムコンポーネント 許可された演算子とオペランドのみを含む式として ネストすることもできる許可された演算子:(論理） AND 、 NOT と OR 、および比較演算子 < 、 <= 、 > 、 >= 、 = と <> 許可されるオペランド：トレースに有効な変数 変数として 許可されるタイプ： BOOL 、ビットアクセス、プロパティ 条件が満たされている TRUE また 1 。ポインタの内容は許可されていません。 IECコードを使用してデータサンプルの条件を記録する ブール値を返す式として コメント コメント（たとえば、レコード条件から） 解決 データセットごとに記録されるタイムスタンプの測定単位 MS ：タイムスタンプ（ミリ秒単位） µs ：1ミリ秒以下のタスクサイクルタイムのタイムスタンプ（マイクロ秒単位） 自動再起動 ：トレース構成とランタイムバッファの最後の内容をターゲットデバイスに永続的に保存します デバイスが再起動された後、トリガーがまだ発生していない場合は、トレースが自動的に開始されます。 高度 を開きます 高度なトレース設定 ダイアログ 詳細については、以下を参照してください。 トレンド設定の詳細" }, 
{ "title" : "変数設定 サブダイアログ ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_1ca9d7ba3a3511e7a72e97101ee2f5a3", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 \/ 変数設定 サブダイアログ ", 
"snippet" : "要件：トレース変数がで選択されている トレースレコード また プレゼンテーション（図） ツリー表示。 変数 有効な変数変数;フルインスタンスパスで記録された値 有効 IEC変数 財産 リファレンス ポインタの内容 配列要素 許可されるデータ型 IECベースタイプ それ外 STRING 、 WSTRING 、 また ARRAY 基本型がない場合の列挙 STRING 、 WSTRING 、 また ARRAY ランタイムシステムが CmpTraceMgr コンポーネント、にリンクされているプロパティ 'monitoring' その後、属性を変数として記録できます。 パラメーター データが記録されてい...", 
"body" : "要件：トレース変数がで選択されている トレースレコード また プレゼンテーション（図） ツリー表示。 変数 有効な変数変数;フルインスタンスパスで記録された値 有効 IEC変数 財産 リファレンス ポインタの内容 配列要素 許可されるデータ型 IECベースタイプ それ外 STRING 、 WSTRING 、 また ARRAY 基本型がない場合の列挙 STRING 、 WSTRING 、 また ARRAY ランタイムシステムが CmpTraceMgr コンポーネント、にリンクされているプロパティ 'monitoring' その後、属性を変数として記録できます。 パラメーター データが記録されているパラメータ 要件：ランタイムシステム CmpTraceMgr 成分 The 入力アシスタント ダイアログには、有効なシステムパラメータがすべて一覧表示されます。 パラメーター のカテゴリ カテゴリ タブ。 間で切り替えることができます 変数 と パラメータ 色 トレース図の変数の色 線種 折れ線グラフとして表示 ライン ：値は線を形成するために接続されます。 ステップ ：値は階段の形で接続されています。 なし ：値は接続されていません。 ポイントタイプ 散布図として表示する ドット ：値はドットで表示されます。 クロス ：値は十字で表示されます。 なし ：値は表示されません。 最小限の警告を有効にする ：下限値未満の場合の警告 重要な下限 トレース変数の値が制限を下回ると、変数は警告色で表示されます。 色 値が制限を下回ったときの警告色 最大警告を有効にする ：上限を超えた場合の警告 重要な上限 トレース変数の値が上限を超えると、変数は警告色で表示されます。 色 値が制限を超えた場合の警告色 " }, 
{ "title" : "ディスプレイモード サブダイアログ ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_67f1bc9d70b311e4ba1694269eca8f43", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 \/ ディスプレイモード サブダイアログ ", 
"snippet" : "要件：軸が選択されている プレゼンテーション（図） ツリー表示。 ディスプレイモード スケーリング 自動 自動的にスケーリングされた時間軸 固定長 時間軸セグメント 長さ 絶え間ない 修理済み からの時間軸セグメント 最小 に 最大 最小 リテラル、変数（整数データ型）、または定数変数（整数データ型） セグメントの初期値が含まれています。要件： ディスプレイモード は 修理済み 。 例： 20,PLC_PRG.iLimit_Min, GVL.c_iLimit_Min 注：変数には初期値が必要です。これは、オフライン表示とスケーリングの細分化にとって重要です。 例： iLimit_Min : I...", 
"body" : "要件：軸が選択されている プレゼンテーション（図） ツリー表示。 ディスプレイモード スケーリング 自動 自動的にスケーリングされた時間軸 固定長 時間軸セグメント 長さ 絶え間ない 修理済み からの時間軸セグメント 最小 に 最大 最小 リテラル、変数（整数データ型）、または定数変数（整数データ型） セグメントの初期値が含まれています。要件： ディスプレイモード は 修理済み 。 例： 20,PLC_PRG.iLimit_Min, GVL.c_iLimit_Min 注：変数には初期値が必要です。これは、オフライン表示とスケーリングの細分化にとって重要です。 例： iLimit_Min : INT := 20 最大 リテラル、変数（整数データ型）、または定数変数（整数データ型） セグメントの終了値が含まれます。 要件： ディスプレイモード は 修理済み 。 例： 80,PLC_PRG.iLimit_Max, GVL.c_iLimit_Max 注：変数には初期値が必要です。これは、オフライン表示とスケーリングの細分化にとって重要です。 例： iLimit_Max : INT := 80 長さ セグメントの一定の長さ 初期値は自動的に調整されます。 グリッド ：X方向にグリッド線がある図 色のリストボックスからグリッド線の色を選択します。 ティックマーク 固定間隔 ：目盛りの表示 距離 と サブディビジョン 距離 目盛り間の距離 サブディビジョン 2つの目盛りの間の細分化の数 フォント 時間軸に使用されるフォント プレビュー リンク ダイアグラムのプレビューを表示します " }, 
{ "title" : "ダイアグラムのプレビュー ", 
"url" : "_cds_dlg_trace_configuration.html#UUID-1fdcc72c-3887-a60f-ee64-c68bdcb32ab3_id_a50fc41aaa89d2c0a8640e017dd825_id_8a982960451f11e7a93feabaeb321a5e", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレース構成 \/ ダイアグラムのプレビュー ", 
"snippet" : "要件：図が選択されている プレゼンテーション（図） ツリー表示。 背景色 図の背景色 The シンボルは色のリストボックスを開きます。 選択時の背景色 選択した図の背景色 変数を追加 リンク 新しいトレース変数を追加します（ トレースレコード ツリー表示） 変数を削除 リンク 選択したトレース変数を削除します（ トレースレコード ツリー表示） ダイアグラムを追加 リンク 新しい図を追加します（ プレゼンテーション ツリー表示） ダイアグラムの削除 リンク 選択した図を削除します（ プレゼンテーション ツリー表示） 表示設定のリセット リンク 選択した図またはY軸の表示設定をデフォルト値にリセッ...", 
"body" : "要件：図が選択されている プレゼンテーション（図） ツリー表示。 背景色 図の背景色 The シンボルは色のリストボックスを開きます。 選択時の背景色 選択した図の背景色 変数を追加 リンク 新しいトレース変数を追加します（ トレースレコード ツリー表示） 変数を削除 リンク 選択したトレース変数を削除します（ トレースレコード ツリー表示） ダイアグラムを追加 リンク 新しい図を追加します（ プレゼンテーション ツリー表示） ダイアグラムの削除 リンク 選択した図を削除します（ プレゼンテーション ツリー表示） 表示設定のリセット リンク 選択した図またはY軸の表示設定をデフォルト値にリセットします わかった 構成の変更を適用し、トレース構成を保存します " }, 
{ "title" : "ダイアログ：トレンド設定の詳細 ", 
"url" : "_cds_dlg_trace_advanced_settings.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ ダイアログ \/ ダイアログ：トレンド設定の詳細 ", 
"snippet" : "トレンド設定の詳細 関数 ：ダイアログには、データサンプリングの詳細設定が表示されます。 電話 ： トレース構成 ダイアログ、 記録設定 サブダイアログ、 高度 ボタン 要件 ：トレースエディタが開いていてアクティブです。 The トレース構成 ダイアログが開き、トレースレコードツリーの最上位ノードが選択され、 記録設定 サブダイアログが利用可能です。 値の計算には、でタスクを選択する必要があります トレース構成 ダイアログ。 ユーザーインターフェイスのオプション 説明 各オプションの右側に計算結果を表示 n番目のサイクルごとの測定 nタスクサイクルごとのデータサンプリング ディフォルト： 1...", 
"body" : "トレンド設定の詳細 関数 ：ダイアログには、データサンプリングの詳細設定が表示されます。 電話 ： トレース構成 ダイアログ、 記録設定 サブダイアログ、 高度 ボタン 要件 ：トレースエディタが開いていてアクティブです。 The トレース構成 ダイアログが開き、トレースレコードツリーの最上位ノードが選択され、 記録設定 サブダイアログが利用可能です。 値の計算には、でタスクを選択する必要があります トレース構成 ダイアログ。 ユーザーインターフェイスのオプション 説明 各オプションの右側に計算結果を表示 n番目のサイクルごとの測定 nタスクサイクルごとのデータサンプリング ディフォルト： 1 ;次に、アプリケーションは各タスクサイクルでデータサンプリングを実行します。 で指定された値から自動的に計算されるサンプリング間隔 n番目のサイクルごとの測定 オプション 例： 100ms 推奨されるランタイムバッファサイズ（サンプル） 自動的に計算されるため、アプリケーションが実行時にトレース変数ごとに保存できるサンプルの推奨数 この値は、ランタイムシステムの最大リングバッファサイズを決定します。このバッファサイズは、タスクサイクルタイムとの値から自動的に計算されます。 n番目のサイクルごとに測定 オプション、およびが表示されます。 このバッファサイズは、 ランタイムバッファサイズを上書きする オプションは 無効 。 アプリケーションがランタイムシステムでデータをサンプリングする時間間隔の最大長 例： 2s 注：計算は、トレース構成の設定がで設定されている場合にのみ可能です。 トレース構成 ダイアログ、したがってタスクサイクルタイムがわかっています。 ランタイムバッファサイズを上書きする ：入力フィールドで、独自に定義したバッファサイズを指定できるようにします 実行時には、ここで指定した値が使用され、に表示される値は使用されません。 推奨されるランタイムバッファサイズ（サンプル） オプション。 例： 100 少なくとも 10 ：アプリケーションは、によって計算された値ではなく、この値を使用します CODESYS から 推奨されるランタイムバッファサイズ（サンプル） オプション。 アプリケーションがランタイムシステム上のデータを上書きせずにサンプリングする時間間隔の最大長 例： 6s 変数ごとのトレースエディタのバッファサイズ（サンプル） トレースエディタで変数ごとに保存できる値の数 例： 10000 トレースエディタに表示される最大期間は、データサンプリングの最大数とサンプリング間隔によって決まります。トレースエディタで、この時間の最大値までスクロールバックできます。 例 列（1）は、サンプル数を通知します。その隣の列（2）には、結果として計算された時間間隔が表示されます。 この例に表示されている情報は、ランタイムシステムのタスクサイクルごとに1つのサンプルが取得され、最大201サンプルを保持できるリングバッファに継続的にキャッシュされることを意味します。有効 ランタイムバッファサイズを上書きする オプションには、リングバッファが原因で、最初にキャッシュされた値が100サンプル後に最初に上書きされるという効果があります。この間、10000サンプルがトレースエディタに継続的に表示されるため、1分40秒近くの間隔で値曲線を表示できます。 詳細については、以下を参照してください。 トレース構成を作成する" }, 
{ "title" : "メニューコマンド ", 
"url" : "_trace_menu_commands.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "コマンド：変数を追加 ", 
"url" : "_cds_cmd_trace_add_variable.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：変数を追加 ", 
"snippet" : "変数を追加 関数 ：このコマンドは、構成にトレース変数を追加します。 電話 ：メニュー 痕跡 トレース構成のツリービューに新しい変数が表示されます。関連する変数構成は、右下に表示されます 変数設定 。 詳細については、以下を参照してください。 トレース構成を作成する...", 
"body" : "変数を追加 関数 ：このコマンドは、構成にトレース変数を追加します。 電話 ：メニュー 痕跡 トレース構成のツリービューに新しい変数が表示されます。関連する変数構成は、右下に表示されます 変数設定 。 詳細については、以下を参照してください。 トレース構成を作成する" }, 
{ "title" : "コマンド：トレースをダウンロード ", 
"url" : "_cds_cmd_trace_download.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースをダウンロード ", 
"snippet" : "トレースをダウンロード シンボル： 関数 ：コマンドは、トレース設定をコントローラから割り当てられたアプリケーションに転送し、データ取得を開始します。記録されたデータは開発システムに転送されます。次に、トレース図に現在のサンプルと実行が表示されます。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：このコマンドは、関連するアプリケーションがオンラインのときに使用できます。 詳細については、以下を参照してください。 制御データ収集...", 
"body" : "トレースをダウンロード シンボル： 関数 ：コマンドは、トレース設定をコントローラから割り当てられたアプリケーションに転送し、データ取得を開始します。記録されたデータは開発システムに転送されます。次に、トレース図に現在のサンプルと実行が表示されます。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：このコマンドは、関連するアプリケーションがオンラインのときに使用できます。 詳細については、以下を参照してください。 制御データ収集" }, 
{ "title" : "コマンド：トレースを開始 ", 
"url" : "_cds_cmd_trace_start.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースを開始 ", 
"snippet" : "トレースを開始 シンボル： 関数 ：コントローラが停止すると、コントローラでのデータ取得の実行を開始します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：割り当てられたアプリケーションはランタイムシステムで実行されており、トレース構成がロードされています。 詳細については、以下を参照してください。 制御データ収集...", 
"body" : "トレースを開始 シンボル： 関数 ：コントローラが停止すると、コントローラでのデータ取得の実行を開始します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：割り当てられたアプリケーションはランタイムシステムで実行されており、トレース構成がロードされています。 詳細については、以下を参照してください。 制御データ収集" }, 
{ "title" : "コマンド：トレースを停止します ", 
"url" : "_cds_cmd_trace_stop.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースを停止します ", 
"snippet" : "トレースを停止します シンボル： 関数 ：コマンドは、トレースのデータ取得を停止します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：割り当てられたアプリケーションはランタイムシステムで実行され、トレースを実行します。 詳細については、以下を参照してください。 制御データ収集...", 
"body" : "トレースを停止します シンボル： 関数 ：コマンドは、トレースのデータ取得を停止します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：割り当てられたアプリケーションはランタイムシステムで実行され、トレースを実行します。 詳細については、以下を参照してください。 制御データ収集" }, 
{ "title" : "コマンド：トリガーをリセット ", 
"url" : "_cds_cmd_trace_reset_trigger.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トリガーをリセット ", 
"snippet" : "トリガーをリセット シンボル： 関数 ：コマンドは、トリガーされたデータ取得後にトレース構成をリセットします。その後、アプリケーションは新しいデータを取得し、トリガーに再度反応することができます。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：トリガーをトリガーした後、データは完全に開発システムのバッファーにあります。 詳細については、以下を参照してください。 制御データ収集...", 
"body" : "トリガーをリセット シンボル： 関数 ：コマンドは、トリガーされたデータ取得後にトレース構成をリセットします。その後、アプリケーションは新しいデータを取得し、トリガーに再度反応することができます。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：トリガーをトリガーした後、データは完全に開発システムのバッファーにあります。 詳細については、以下を参照してください。 制御データ収集" }, 
{ "title" : "コマンド：カーソル ", 
"url" : "_cds_cmd_trace_cursor.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：カーソル ", 
"snippet" : "カーソル シンボル： 関数 ： コマンドは次のように機能します。 次の場合は、トレースカーソルをトレース図に挿入します。 いいえ トレースカーソルが存在します。 次の場合、2番目のトレースカーソルがトレース図に挿入されます。 1 トレースカーソルが存在します。 トレースカーソルを削除すると 2 トレースカーソルがあります。 電話 ：メニュー 痕跡 、 コンテキストメニュー トレースカーソルは、Y軸に平行な垂直の黒い線が付いた小さな黒い三角形です。...", 
"body" : "カーソル シンボル： 関数 ： コマンドは次のように機能します。 次の場合は、トレースカーソルをトレース図に挿入します。 いいえ トレースカーソルが存在します。 次の場合、2番目のトレースカーソルがトレース図に挿入されます。 1 トレースカーソルが存在します。 トレースカーソルを削除すると 2 トレースカーソルがあります。 電話 ：メニュー 痕跡 、 コンテキストメニュー トレースカーソルは、Y軸に平行な垂直の黒い線が付いた小さな黒い三角形です。 " }, 
{ "title" : "トレースカーソルなしのトレース図 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_3bb4368090b42c23c0a8640e00510814", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：カーソル \/ トレースカーソルなしのトレース図 ", 
"snippet" : "この状態では、カーソル、つまりマウスポインタを使用してトレース図を実行できます。カーソルでピントを合わせたX値は、ステータスバーに標準表記で出力されます。例： 時間：1m23s456ms値：1...", 
"body" : "この状態では、カーソル、つまりマウスポインタを使用してトレース図を実行できます。カーソルでピントを合わせたX値は、ステータスバーに標準表記で出力されます。例： 時間：1m23s456ms値：1 " }, 
{ "title" : "トレースカーソル付きのトレース図 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_4e02c9b290b42c23c0a8640e01e9fd26", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：カーソル \/ トレースカーソル付きのトレース図 ", 
"snippet" : "CODESYS ステータスバーのトレースカーソルとY値でマークされた時点を出力します。例： 時間：1分23秒456分...", 
"body" : "CODESYS ステータスバーのトレースカーソルとY値でマークされた時点を出力します。例： 時間：1分23秒456分 " }, 
{ "title" : "2つのトレースカーソルを使用したトレース図 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_53d5619790b42c23c0a8640e009c07ca", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：カーソル \/ 2つのトレースカーソルを使用したトレース図 ", 
"snippet" : "CODESYS ステータスバーの2つのトレースカーソルでマークされた2つの時点と時間間隔を出力します。例： 時間：1m23s456ms-時間：1m24s456ms（∆ 1s） 。...", 
"body" : "CODESYS ステータスバーの2つのトレースカーソルでマークされた2つの時点と時間間隔を出力します。例： 時間：1m23s456ms-時間：1m24s456ms（∆ 1s） 。 " }, 
{ "title" : "トレースグラフでのユーザー入力 ", 
"url" : "_cds_cmd_trace_cursor.html#UUID-96194fae-7bca-6e7f-73e5-9b31838a3e0f_id_b813d538b86c5cc0a8640e01176df2_id_725ebfbf07220da4c0a8640e012a61b4", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：カーソル \/ トレースグラフでのユーザー入力 ", 
"snippet" : "トレースカーソルが1つまたは2つある場合は、X軸に沿って移動できます。 マウスによるユーザー入力 シンボル 影響 トレースカーソルの三角形を別の場所にドラッグします。 マウスボタンを押している間は、カーソルを自由に動かすことができます。現在のY値は常にステータスバーに表示されます。マウスボタンを離すとすぐに、カーソルが最も近い測定ポイントにスナップします。 キーボードショートカットを使用したユーザー入力 影響 左矢印 右矢印 CODESYS 黒のトレースカーソルを次の測定ポイントに移動します。 トグル + 左矢印 トグル + 右矢印 CODESYS 灰色のトレースカーソルを次の測定ポイントに移...", 
"body" : "トレースカーソルが1つまたは2つある場合は、X軸に沿って移動できます。 マウスによるユーザー入力 シンボル 影響 トレースカーソルの三角形を別の場所にドラッグします。 マウスボタンを押している間は、カーソルを自由に動かすことができます。現在のY値は常にステータスバーに表示されます。マウスボタンを離すとすぐに、カーソルが最も近い測定ポイントにスナップします。 キーボードショートカットを使用したユーザー入力 影響 左矢印 右矢印 CODESYS 黒のトレースカーソルを次の測定ポイントに移動します。 トグル + 左矢印 トグル + 右矢印 CODESYS 灰色のトレースカーソルを次の測定ポイントに移動します。 詳細については、以下を参照してください。 トレースデータのナビゲート" }, 
{ "title" : "コマンド：マウスでズーム ", 
"url" : "_cds_cmd_trace_mouse_zooming.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：マウスでズーム ", 
"snippet" : "マウスでズーム シンボル： （コマンド無効） シンボル： （コマンド有効） 関数 ：このコマンドは、トレース図でのマウスズームを有効または無効にします。 電話 ：メニュー 痕跡 、 コンテキストメニュー...", 
"body" : "マウスでズーム シンボル： （コマンド無効） シンボル： （コマンド有効） 関数 ：このコマンドは、トレース図でのマウスズームを有効または無効にします。 電話 ：メニュー 痕跡 、 コンテキストメニュー " }, 
{ "title" : "トレースグラフでのユーザー入力 ", 
"url" : "_cds_cmd_trace_mouse_zooming.html#UUID-168f2e36-4edc-93e4-08cc-43a7cdc175b0_id_d2d238b90e93c0a8640e00458ec9_id_80aeaddbce7e5d84c0a8640e0036c6d9", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：マウスでズーム \/ トレースグラフでのユーザー入力 ", 
"snippet" : "コマンドがアクティブになっている場合は、マウスで長方形を開くことができます。マウスボタンを離すと、長方形が拡大され、データが拡大されます。 詳細については、以下を参照してください。 トレースデータのナビゲート...", 
"body" : "コマンドがアクティブになっている場合は、マウスで長方形を開くことができます。マウスボタンを離すと、長方形が拡大され、データが拡大されます。 詳細については、以下を参照してください。 トレースデータのナビゲート" }, 
{ "title" : "コマンド：ビューをリセット ", 
"url" : "_cds_cmd_trace_reset_view.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：ビューをリセット ", 
"snippet" : "表示方法をリセットする シンボル： 関数 ：このコマンドは、トレース図の表示をデフォルトにリセットします。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：ズーム、スクロール、またはコマンドにより、トレース図に表示されます。 自動スケール かわった。 詳細については、以下を参照してください。 自動スケール...", 
"body" : "表示方法をリセットする シンボル： 関数 ：このコマンドは、トレース図の表示をデフォルトにリセットします。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：ズーム、スクロール、またはコマンドにより、トレース図に表示されます。 自動スケール かわった。 詳細については、以下を参照してください。 自動スケール" }, 
{ "title" : "コマンド：オートスケール ", 
"url" : "_cds_cmd_trace_auto_fit.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：オートスケール ", 
"snippet" : "自動スケール シンボル： 関数 : このコマンドが呼び出されると、後ですべてのグラフが最適に表示されるように、トレース ダイアグラムの Y 軸が自動的にスケーリングされます。 Y 値は、図の表示領域に収まります。すると、コマンドがメニューで選択された状態で表示されます (チェック マークが付いたコマンド)。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 : トレースが実行中です。このために、事前にトレースを作成し、Y 軸の固定スケールを指定して、 トレースをダウンロード 指図。 コマンドは切り替えることができます。メニューの有効なコマンドをクリックすると、Y 軸に自動的に調整された表...", 
"body" : "自動スケール シンボル： 関数 : このコマンドが呼び出されると、後ですべてのグラフが最適に表示されるように、トレース ダイアグラムの Y 軸が自動的にスケーリングされます。 Y 値は、図の表示領域に収まります。すると、コマンドがメニューで選択された状態で表示されます (チェック マークが付いたコマンド)。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 : トレースが実行中です。このために、事前にトレースを作成し、Y 軸の固定スケールを指定して、 トレースをダウンロード 指図。 コマンドは切り替えることができます。メニューの有効なコマンドをクリックすると、Y 軸に自動的に調整された表示が、以前に設定された固定表示に戻ります。 関数 : このコマンドが呼び出されると、後ですべてのグラフが最適に表示されるように、トレース ダイアグラムの Y 軸が自動的にスケーリングされます。 Y 値は、図の表示領域に収まります。すると、コマンドがメニューで選択された状態で表示されます (チェック マークが付いたコマンド)。 " }, 
{ "title" : "シングルチャンネルディスプレイのトレース ", 
"url" : "_cds_cmd_trace_auto_fit.html#UUID-d4fafa55-c8c6-3865-1d6d-31d31577c463_id_c7d5cbf38bedbacc0a8640e0100667c_id_4c29461991206663c0a8640e01dfc836", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：オートスケール \/ シングルチャンネルディスプレイのトレース ", 
"snippet" : "すべてのトレース変数が1つの図に表示されている場合、トレースは単一チャネル表現になっています。...", 
"body" : "すべてのトレース変数が1つの図に表示されている場合、トレースは単一チャネル表現になっています。 " }, 
{ "title" : "マルチチャンネルディスプレイのトレース ", 
"url" : "_cds_cmd_trace_auto_fit.html#UUID-d4fafa55-c8c6-3865-1d6d-31d31577c463_id_c7d5cbf38bedbacc0a8640e0100667c_id_6dbf5d2c071fc814c0a8640e01ac9307", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：オートスケール \/ マルチチャンネルディスプレイのトレース ", 
"snippet" : "トレース変数が複数の図に表示されている場合、トレースはマルチチャネル表現になっています。 詳細については、以下を参照してください。 トレース構成 と トレースデータのナビゲート...", 
"body" : "トレース変数が複数の図に表示されている場合、トレースはマルチチャネル表現になっています。 詳細については、以下を参照してください。 トレース構成 と トレースデータのナビゲート" }, 
{ "title" : "コマンド：圧縮 ", 
"url" : "_cds_cmd_trace_compress.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：圧縮 ", 
"snippet" : "圧縮 シンボル： 関数 ：このコマンドは、表示される時間範囲を一定の割合で増やすことにより、トレースグラフを圧縮します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 詳細については、以下を参照してください。 ストレッチ と トレースデータのナビゲート...", 
"body" : "圧縮 シンボル： 関数 ：このコマンドは、表示される時間範囲を一定の割合で増やすことにより、トレースグラフを圧縮します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 詳細については、以下を参照してください。 ストレッチ と トレースデータのナビゲート" }, 
{ "title" : "コマンド：ストレッチ ", 
"url" : "_cds_cmd_trace_stretch.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：ストレッチ ", 
"snippet" : "ストレッチ シンボル： 関数 ：このコマンドは、表示される時間範囲を一定の割合で縮小することにより、トレースグラフを拡大します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 詳細については、以下を参照してください。 トレースデータのナビゲート...", 
"body" : "ストレッチ シンボル： 関数 ：このコマンドは、表示される時間範囲を一定の割合で縮小することにより、トレースグラフを拡大します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 詳細については、以下を参照してください。 トレースデータのナビゲート" }, 
{ "title" : "コマンド：オンラインリスト ", 
"url" : "_cds_cmd_trace_online_list.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：オンラインリスト ", 
"snippet" : "オンラインリスト 関数 ：コマンドはダイアログを開きます オンラインリスト 。のトレースエディタだけなら DeviceTrace オブジェクトがアクティブである場合、コントローラーで実行されているすべてのトレースがツリービューに表示されます。アプリケーション関連のトレースオブジェクトのトレースエディタが現在アクティブである場合、コントローラで実行されていると、このトレースのみが表示されます。 電話 ：メニュー 痕跡 、トレースエディタのコンテキストメニュー 要件 ：ランタイムシステムはコンポーネントを使用します CmpTraceMgr 。デバイスに属するアプリケーションはオンラインモードです。...", 
"body" : "オンラインリスト 関数 ：コマンドはダイアログを開きます オンラインリスト 。のトレースエディタだけなら DeviceTrace オブジェクトがアクティブである場合、コントローラーで実行されているすべてのトレースがツリービューに表示されます。アプリケーション関連のトレースオブジェクトのトレースエディタが現在アクティブである場合、コントローラで実行されていると、このトレースのみが表示されます。 電話 ：メニュー 痕跡 、トレースエディタのコンテキストメニュー 要件 ：ランタイムシステムはコンポーネントを使用します CmpTraceMgr 。デバイスに属するアプリケーションはオンラインモードです。 を閉じる DeviceTrace -エディタはコントローラへの接続を終了します。 最後に開いたものを閉じると注意してください DeviceTrace -エディターはコントローラーへの接続も終了します！プロジェクトにデバイストレースを再度表示するには、デバイストレースをプロジェクトに再入力する必要があります。 DeviceTrace -オブジェクトをロードします。 現在、エディターを閉じることは、コントローラーへの接続を意識的に終了するための推奨手順でもあります。これにはログアウトだけでは不十分です。 " }, 
{ "title" : "対話：オンラインリスト ", 
"url" : "_cds_cmd_trace_online_list.html#UUID-ce19611c-72af-217d-a4a2-3770090dbf4b_id_d2f3bea38c0e862c0a8640e01adb3d6_id_0387599e07259231c0a8640e01b92b5a", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：オンラインリスト \/ 対話：オンラインリスト ", 
"snippet" : "LZSから削除 選択したトレースを停止して、実行中のアプリケーションから削除します アップロード コマンドは、トレースエディタで表示されます DeviceTrace がロードされます。 A DeviceTrace コントローラ上で実行されるトレースです。デバイスツリーでは、次のコマンドでアクセスできます。 DeviceTrace -オブジェクトは、デバイスのすぐ下に表示できます。 コマンドを選択すると、ツリービューで選択されたトレースがランタイムシステムからトレースエディタにロードされます。プロジェクト内の既存の構成はすべて上書きされます。たとえば、デバイスはプロセッサ使用率データのトレースを...", 
"body" : "LZSから削除 選択したトレースを停止して、実行中のアプリケーションから削除します アップロード コマンドは、トレースエディタで表示されます DeviceTrace がロードされます。 A DeviceTrace コントローラ上で実行されるトレースです。デバイスツリーでは、次のコマンドでアクセスできます。 DeviceTrace -オブジェクトは、デバイスのすぐ下に表示できます。 コマンドを選択すると、ツリービューで選択されたトレースがランタイムシステムからトレースエディタにロードされます。プロジェクト内の既存の構成はすべて上書きされます。たとえば、デバイスはプロセッサ使用率データのトレースを提供できます（ cpuload 、 plcload ）、これをトレースエディタで使用できます CODESYS 追跡できます。 プロジェクトに表示されるデバイストレースごとに個別のトレースがあります DeviceTrace -デバイスツリーに必要なオブジェクト。 詳細については、以下を参照してください。 コントローラのすべてのトレースへのアクセス と DeviceTrace" }, 
{ "title" : "コマンド：トレースをアップロード ", 
"url" : "_cds_cmd_trace_upload.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースをアップロード ", 
"snippet" : "トレースをアップロード 関数 ：PLCデバイスがまだ存在しない場合、コマンドは最初にPLCデバイスへの接続を確立します。次に、彼はダイアログを開きます オンラインリスト コントローラで現在実行されているトレースのリストが表示されます。選択したトレースは、ダイアログで使用可能なコマンドを使用して実行されます アップロード トレースエディタにロードされます。 電話 ：メニュー 痕跡 、トレースエディタのコンテキストメニュー 要件 ：の編集者 DeviceTrace オブジェクトが開いています。ランタイムシステムはコンポーネントを使用します CmpTraceMgr （トレースマネージャー）。ランタイ...", 
"body" : "トレースをアップロード 関数 ：PLCデバイスがまだ存在しない場合、コマンドは最初にPLCデバイスへの接続を確立します。次に、彼はダイアログを開きます オンラインリスト コントローラで現在実行されているトレースのリストが表示されます。選択したトレースは、ダイアログで使用可能なコマンドを使用して実行されます アップロード トレースエディタにロードされます。 電話 ：メニュー 痕跡 、トレースエディタのコンテキストメニュー 要件 ：の編集者 DeviceTrace オブジェクトが開いています。ランタイムシステムはコンポーネントを使用します CmpTraceMgr （トレースマネージャー）。ランタイムシステム上の少なくとも1つのアプリケーションが実行されています。の中に CODESYS プロジェクトでは、PLCの通信設定が正しく構成されています。 を閉じる DeviceTrace -エディタはコントローラへの接続を終了します。 最後に開いたときに、コントローラへの接続も終了されることに注意してください。 デバイストレース エディターは閉じています。デバイス トレースをプロジェクトに再度表示するには、デバイス トレースをプロジェクトに再ロードする必要があります。 デバイストレース オブジェクト。 現在、コントローラーへの接続を意図的に終了するには、エディターを閉じることも推奨される方法です。これには、ログアウトするだけでは十分ではありません。 詳細については、以下を参照してください。 コントローラのすべてのトレースへのアクセス" }, 
{ "title" : "コマンド：構成 ", 
"url" : "_cds_cmd_trace_configuration.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：構成 ", 
"snippet" : "構成 関数 ：コマンドはダイアログを開きます トレース構成 、データ収集の構成を可能にします。 電話 ：メニュー 痕跡 、 コンテキストメニュー 詳細については、以下を参照してください。 トレース構成...", 
"body" : "構成 関数 ：コマンドはダイアログを開きます トレース構成 、データ収集の構成を可能にします。 電話 ：メニュー 痕跡 、 コンテキストメニュー 詳細については、以下を参照してください。 トレース構成" }, 
{ "title" : "コマンド：トレースをロード ", 
"url" : "_cds_cmd_trace_load.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースをロード ", 
"snippet" : "ロードトレース 関数 ：このコマンドを使用すると、開発システムのファイルシステムに保存されている構成とデータを含むファイルをロードできます。対話 ロードトレース が表示されます。 電話 ：メニュー 痕跡 、 コンテキストメニュー...", 
"body" : "ロードトレース 関数 ：このコマンドを使用すると、開発システムのファイルシステムに保存されている構成とデータを含むファイルをロードできます。対話 ロードトレース が表示されます。 電話 ：メニュー 痕跡 、 コンテキストメニュー " }, 
{ "title" : "ダイアログ：ロードトレース ", 
"url" : "_cds_cmd_trace_load.html#UUID-e47e8db6-406e-9b94-bae0-f820c9689058_id_b399f38c246edc0a8640e00a7659a_id_26f9ba38ce7e8813c0a8640e00e3eaf1", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースをロード \/ ダイアログ：ロードトレース ", 
"snippet" : "ファイル名 ロードされているファイルの名前 ファイルの種類 ファイル形式 *.trace ： トレースファイル 、トレース構成とサンプルが含まれています *.csv ：トレース構成を含むCSVファイル形式のテキストファイル 詳細については、以下を参照してください。 トレースを管理する...", 
"body" : "ファイル名 ロードされているファイルの名前 ファイルの種類 ファイル形式 *.trace ： トレースファイル 、トレース構成とサンプルが含まれています *.csv ：トレース構成を含むCSVファイル形式のテキストファイル 詳細については、以下を参照してください。 トレースを管理する" }, 
{ "title" : "コマンド：トレースを保存 ", 
"url" : "_cds_cmd_trace_save.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースを保存 ", 
"snippet" : "トレースを保存 関数 ：このコマンドを使用すると、データを開発システム上のファイルに保存できます。ファイル形式に応じて、構成も保存されます。対話 トレースを保存 が表示されます。 電話 ：メニュー 痕跡 、 コンテキストメニュー...", 
"body" : "トレースを保存 関数 ：このコマンドを使用すると、データを開発システム上のファイルに保存できます。ファイル形式に応じて、構成も保存されます。対話 トレースを保存 が表示されます。 電話 ：メニュー 痕跡 、 コンテキストメニュー " }, 
{ "title" : "ダイアログ：トレースを保存 ", 
"url" : "_cds_cmd_trace_save.html#UUID-d3c7c9ff-690d-2549-e2d2-897be7c0f07e_id_adda054938c2b695c0a8640e00c67eff_id_67a9c8bece907839c0a8640e0039fb47", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：トレースを保存 \/ ダイアログ：トレースを保存 ", 
"snippet" : "ファイル名 トレースファイルの名前と場所 ファイルの種類 ファイルの種類 *.trace ： トレースファイル 、データと構成が含まれています このようなファイルは、次のコマンドで作成できます ロードトレース トレースエディタでオフラインでロードします。 *.txt ： テキストファイル 、収集されたデータが含まれています CSV形式をサポートするツールを使用して、このようなファイルを読み込んで処理できます。 トレースエディタはこの形式を読み取ることができないため、オフラインでトレースエディタにロードすることはできません。 *.trace.csv トレースcsvファイル（データのみ） 、収集さ...", 
"body" : "ファイル名 トレースファイルの名前と場所 ファイルの種類 ファイルの種類 *.trace ： トレースファイル 、データと構成が含まれています このようなファイルは、次のコマンドで作成できます ロードトレース トレースエディタでオフラインでロードします。 *.txt ： テキストファイル 、収集されたデータが含まれています CSV形式をサポートするツールを使用して、このようなファイルを読み込んで処理できます。 トレースエディタはこの形式を読み取ることができないため、オフラインでトレースエディタにロードすることはできません。 *.trace.csv トレースcsvファイル（データのみ） 、収集されたデータが含まれています トレース変数ごとにアドレス情報が提供されます。生成されたファイルは、ランタイムシステムに読み込むことができます。データはインポートされますが、変数のアドレスが保存されていないため、トレースを開始できません。 詳細については、以下を参照してください。 トレースを管理する" }, 
{ "title" : "コマンド：シンボリックトレース設定をエクスポートする ", 
"url" : "_cds_cmd_trace_export_symbolic_trace_config.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：シンボリックトレース設定をエクスポートする ", 
"snippet" : "シンボリックトレース構成のエクスポート 関数 ：このコマンドは、トレース構成を次の形式のファイルとしてエクスポートします *.traceconfig 。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：元のアプリケーションには、構成されたトレース変数をシンボルとして定義するシンボル構成が含まれています。したがって、データが記録されているIEC変数へのアクセスはシンボリックであり、トレース構成をさまざまな同様のアプリケーションに使用できます。...", 
"body" : "シンボリックトレース構成のエクスポート 関数 ：このコマンドは、トレース構成を次の形式のファイルとしてエクスポートします *.traceconfig 。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：元のアプリケーションには、構成されたトレース変数をシンボルとして定義するシンボル構成が含まれています。したがって、データが記録されているIEC変数へのアクセスはシンボリックであり、トレース構成をさまざまな同様のアプリケーションに使用できます。 " }, 
{ "title" : "構成ファイルの使用 ", 
"url" : "_cds_cmd_trace_export_symbolic_trace_config.html#UUID-19273690-813e-4c38-271a-86ac0cece2ec_id_b493e438c3b197c0a8640e00f0260c_id_16116f1397ea11e482dcec1a7d15e9dd", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：シンボリックトレース設定をエクスポートする \/ 構成ファイルの使用 ", 
"snippet" : "このファイルは任意のランタイムシステムに転送できます。実行時に、そのランタイムシステムコンポーネント CmpTraceMgr アクセスし、それに基づいてデータ収集を実行します。構成データに加えて、構成ファイルには、アプリケーションのコンテキストに関する情報も含まれています。 構成ファイルは、次のコンテキストを定義します。 アプリケーション名 トレース名 タスク名 実行時に実行されるアプリケーションは、次の条件を満たす必要があります。 アプリケーションの名前は元のアプリケーションと同じです。 アプリケーションで構成されたトレースは、ソースアプリケーションで構成されたトレースと同じ名前になります。...", 
"body" : "このファイルは任意のランタイムシステムに転送できます。実行時に、そのランタイムシステムコンポーネント CmpTraceMgr アクセスし、それに基づいてデータ収集を実行します。構成データに加えて、構成ファイルには、アプリケーションのコンテキストに関する情報も含まれています。 構成ファイルは、次のコンテキストを定義します。 アプリケーション名 トレース名 タスク名 実行時に実行されるアプリケーションは、次の条件を満たす必要があります。 アプリケーションの名前は元のアプリケーションと同じです。 アプリケーションで構成されたトレースは、ソースアプリケーションで構成されたトレースと同じ名前になります。 データ収集が実行されるタスクは、ソースアプリケーションで構成されたタスクと同じ名前です。 構成のロードは自動ではないため、コマンドを実行する必要があります。 次のことができます。 ライブラリインターフェイスを使用して、IECコードを介してプログラムでトレースマネージャにアクセスします。 構成ファイルをトレースマネージャに登録します。次に、アプリケーションの起動時にトレースマネージャが設定ファイルをロードします。 トレースマネージャの機能の詳細については、次のURLを参照してください。 「TraceManagerランタイムシステムコンポーネントの説明」 。 " }, 
{ "title" : "構成ファイルの例 ", 
"url" : "_cds_cmd_trace_export_symbolic_trace_config.html#UUID-19273690-813e-4c38-271a-86ac0cece2ec_id_b493e438c3b197c0a8640e00f0260c_id_d27cec580724ef6fc0a8640e00c884c4", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：シンボリックトレース設定をエクスポートする \/ 構成ファイルの例 ", 
"snippet" : "構成ファイル Trace_Trigger.traceconfig [key]; [value] Version; 0x03050000 Name; Application.Trace_Trigger ApplicationName; Application ApplicationDataGuid; 00000000-0000-0000-0000-000000000000 IecTaskName; MainTask Comment; Trigger.Flags; 5 Trigger.Edge; 2 Trigger.Position; 0 Trigger.UpdatesAfterTrigger; ...", 
"body" : "構成ファイル Trace_Trigger.traceconfig [key]; [value]\nVersion; 0x03050000\nName; Application.Trace_Trigger\nApplicationName; Application\nApplicationDataGuid; 00000000-0000-0000-0000-000000000000\nIecTaskName; MainTask\nComment;\nTrigger.Flags; 5\nTrigger.Edge; 2\nTrigger.Position; 0\nTrigger.UpdatesAfterTrigger; 50\nTrigger.Variable.Name; PLC_PRG.B.OUT\nTrigger.Variable.AddrFlags; 0x00000101\nTrigger.Variable.Class; 0\nTrigger.Variable.Size; 1\nTrigger.Level;\nCondition.Name;\nCondition.AddrFlags; 0x00000000\nCondition.Class; 0\nCondition.Size; 0\nEveryNCycles; 1\nBufferEntries; 100\nFlags; 16\n0.Variable; PLC_PRG.S5.OUT\n0.Address.AddrFlags; 0x00000101\n0.Class; 7\n0.Size; 2\n0.GraphColor; 4278190335\n0.GraphType; 3\n0.MinWarningColor; 4278190080\n0.MaxWarningColor; 4294901760\n0.CriticalLowerLimit; 0\n0.CriticalUpperLimit; 0\n0.ActivateMinWarning; 0\n0.ActivateMaxWarning; 0\n0.YAxis; 0\n0.Data;\n1.Variable; PLC_PRG.B.OUT\n1.Address.AddrFlags; 0x00000101\n1.Class; 0\n1.Size; 1\n1.GraphColor; 4278222848\n1.GraphType; 1\n1.MinWarningColor; 4278190080\n1.MaxWarningColor; 4294901760\n1.CriticalLowerLimit; 0\n1.CriticalUpperLimit; 0\n1.ActivateMinWarning; 0\n1.ActivateMaxWarning; 0\n1.YAxis; 0\n1.Data; " }, 
{ "title" : "コマンド：統計 ", 
"url" : "_cds_cmd_trace_statistics.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：統計 ", 
"snippet" : "統計学 関数 ：コマンドはダイアログを開きます トレース統計 、各トレース変数の統計を表示します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：トレースエディタにはサンプルが含まれています。...", 
"body" : "統計学 関数 ：コマンドはダイアログを開きます トレース統計 、各トレース変数の統計を表示します。 電話 ：メニュー 痕跡 、 コンテキストメニュー 要件 ：トレースエディタにはサンプルが含まれています。 " }, 
{ "title" : "ダイアログ：トレース統計 ", 
"url" : "_cds_cmd_trace_statistics.html#UUID-94109e40-6e95-52d2-5a16-fea5d8126e79_id_e33f54672d980a83c0a8640e00b10ad6_id_0387599e07259231c0a8640e01b92b5a", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド：統計 \/ ダイアログ：トレース統計 ", 
"snippet" : "分析された期間とその期間は、タイトルに示されています。 この表には、信号ごとに1行が含まれています。 信号 トレース変数名 例： PLC_PRG.S1 索引 信号の順序の0ベースのインデックス N 計算の基礎となる測定値の数 分 最小値 平均 平均 中央値 サイズで値を並べ替えるときに中央にある値 RMS 二乗平均平方根 StdDev 標準偏差 マックス 最大値 積分 積分 最小Δt[s] 連続する値の時間間隔の最小値 平均Δt[s] 連続する値の時間間隔の平均 中央値Δt[s] 連続する値の時間間隔の中央値 StdDevΔt[s] 連続する値の時間間隔の標準偏差 最大Δt[s] 連続する値の...", 
"body" : "分析された期間とその期間は、タイトルに示されています。 この表には、信号ごとに1行が含まれています。 信号 トレース変数名 例： PLC_PRG.S1 索引 信号の順序の0ベースのインデックス N 計算の基礎となる測定値の数 分 最小値 平均 平均 中央値 サイズで値を並べ替えるときに中央にある値 RMS 二乗平均平方根 StdDev 標準偏差 マックス 最大値 積分 積分 最小Δt[s] 連続する値の時間間隔の最小値 平均Δt[s] 連続する値の時間間隔の平均 中央値Δt[s] 連続する値の時間間隔の中央値 StdDevΔt[s] 連続する値の時間間隔の標準偏差 最大Δt[s] 連続する値の時間間隔の最大値 特定の列のテーブルヘッダーをクリックします CODESYS テーブルを列ごとに並べ替え、昇順から降順、またはその逆の順序に変更します。 デフォルト：テーブルは列で昇順です 索引 並べ替え。したがって、信号は、信号ツリーに表示されるのと同じ順序で並べ替えられます。 行をクリックします 線が選択されます。あなたは私と一緒に来ることができます トグル + 矢印 他の行を選択し、それらの選択を再度解除します。 ctrl + C CODESYS 選択した行をテキストとしてクリップボードにコピーします。個々の列の値はタブで区切られ、行は制御文字で区切られます CR また LF 分離。 要件：1つ以上の行を選択している。 詳細については、以下を参照してください。 トレースによるデータサンプリング" }, 
{ "title" : "コマンド: すべての変数を個別のダイアグラムに移動する ", 
"url" : "_trace_cmd_move_all_variables_to_individual_diagrams.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド: すべての変数を個別のダイアグラムに移動する ", 
"snippet" : "すべての変数を個別の図に移動する 関数 : このコマンドにより、1 つの図に一緒に表示される変数が、それぞれ別の図に個別に表示されます。 電話 : 痕跡 メニュー; コンテキスト メニュー...", 
"body" : "すべての変数を個別の図に移動する 関数 : このコマンドにより、1 つの図に一緒に表示される変数が、それぞれ別の図に個別に表示されます。 電話 : 痕跡 メニュー; コンテキスト メニュー " }, 
{ "title" : "変数は別々の図に個別に表示されます ", 
"url" : "_trace_cmd_move_all_variables_to_individual_diagrams.html#UUID-b7f34b19-d3a2-7fbd-613f-d026d48b35fd_id_f7ca90b1752d0c0a8646378d1567c_id_56c6a1781bacfff0c0a86463414b8c43", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド: すべての変数を個別のダイアグラムに移動する \/ 変数は別々の図に個別に表示されます ", 
"snippet" : "詳細については、以下を参照してください。 トレースデータのナビゲート そして トレース構成...", 
"body" : "詳細については、以下を参照してください。 トレースデータのナビゲート そして トレース構成" }, 
{ "title" : "コマンド: すべての変数を最初の図に移動する ", 
"url" : "_trace_cmd_move_all_variables_to_first_diagram.html", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド: すべての変数を最初の図に移動する ", 
"snippet" : "すべての変数を最初の図に移動する 関数 : このコマンドにより、1 つの図に個別に表示されている変数が、最初の図にまとめて表示されます。 電話 : 痕跡 メニュー; コンテキスト メニュー...", 
"body" : "すべての変数を最初の図に移動する 関数 : このコマンドにより、1 つの図に個別に表示されている変数が、最初の図にまとめて表示されます。 電話 : 痕跡 メニュー; コンテキスト メニュー " }, 
{ "title" : "変数を1つの図にまとめて表示 ", 
"url" : "_trace_cmd_move_all_variables_to_first_diagram.html#UUID-309629ae-966c-e6d9-be01-d05f9c097269_id_adcc80b17bb78c0a86463003afb08_id_cdb4c9e31bac8664c0a864632f0c6643", 
"breadcrumbs" : "CODESYS トレース \/ 参考: ユーザーインターフェース \/ メニューコマンド \/ コマンド: すべての変数を最初の図に移動する \/ 変数を1つの図にまとめて表示 ", 
"snippet" : "詳細については、以下を参照してください。 トレースデータのナビゲート そして トレース構成...", 
"body" : "詳細については、以下を参照してください。 トレースデータのナビゲート そして トレース構成" }
]
$(document).trigger('search.ready');
});