$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS String Libraries ", 
"url" : "_iiotlib_start_page.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "一般说明 ", 
"url" : "_iiotlib_start_page.html#UUID-335b8917-a56d-c735-099c-f2acedfdcb66_section-idm4563869800648033733012917566", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 一般说明 ", 
"snippet" : "这 CODESYS IIoT Libraries SL 软件包包含许多用于工业物联网环境中通信的库。支持不同的协议，例如 MQTT 和 HTTPS。该软件包还提供了用于编码和解码数据结构（例如 INI、CSV、JSON 和 XML）的工具以及用于与各个提供商的云服务（例如 AWS 和 Azure）直接通信的功能块。 您可以下载 CODESYS IIoT Libraries SL 从 CODESYS 国际商店 或者 CODESYS 北美商店 。您还可以在那里找到该产品的数据表。 安装包后，您将在安装目录中找到使用库的示例项目 IIoT Libraries SL\\Examples 。 有关所有示例...", 
"body" : "这 CODESYS IIoT Libraries SL 软件包包含许多用于工业物联网环境中通信的库。支持不同的协议，例如 MQTT 和 HTTPS。该软件包还提供了用于编码和解码数据结构（例如 INI、CSV、JSON 和 XML）的工具以及用于与各个提供商的云服务（例如 AWS 和 Azure）直接通信的功能块。 您可以下载 CODESYS IIoT Libraries SL 从 CODESYS 国际商店 或者 CODESYS 北美商店 。您还可以在那里找到该产品的数据表。 安装包后，您将在安装目录中找到使用库的示例项目 IIoT Libraries SL\\Examples 。 有关所有示例的详细描述，请参阅： CODESYS IIoT 库 SL 示例 " }, 
{ "title" : "软件包中提供了以下库： ", 
"url" : "_iiotlib_start_page.html#UUID-335b8917-a56d-c735-099c-f2acedfdcb66_section-idm4617612702576033867952037642", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 软件包中提供了以下库： ", 
"snippet" : "用于通信的库： Web Client SL : 通过 http 或 https 与 Web 服务器通 MQTT Client SL : 支持 MQTT（消息队列遥测传输）协议，用于在设备之间将遥测数据作为消息传输 Mail Service SL : 通过SMTP和POP3协议发送、接收和删除电子邮件。 SNMP Service SL : 支持以下功能：SNMP GET、SNMP GET_NEXT、SNMP Agent、SNMP TRAP、SNMP SET SNTP Service SL : 构建SNTP客户端和服务器应用程序（SNTP V3、SNTP V4）。 AWS IoT Core Cli...", 
"body" : "用于通信的库： Web Client SL : 通过 http 或 https 与 Web 服务器通 MQTT Client SL : 支持 MQTT（消息队列遥测传输）协议，用于在设备之间将遥测数据作为消息传输 Mail Service SL : 通过SMTP和POP3协议发送、接收和删除电子邮件。 SNMP Service SL : 支持以下功能：SNMP GET、SNMP GET_NEXT、SNMP Agent、SNMP TRAP、SNMP SET SNTP Service SL : 构建SNTP客户端和服务器应用程序（SNTP V3、SNTP V4）。 AWS IoT Core Client SL : 与亚马逊的“AWS IoT Core”云平台交换消息发送和接收 Azure IoT Hub Client SL : 将 IoT 设备连接到 Microsoft 的“Azure IOT Hub”云服务时发送和接收消息的功能块。 JSON Web Token SL : 在控制器上创建JWT（JSON Web Token）。为此，支持 HS256、HS384、HS512und 和 RS256 算法。 Web Socket Client SL : 通过 Internet 上的客户端和 Web Socket 服务器之间的 WebSocket 协议进行通信。 OpenWeather Client SL : 通过 OpenWeather API 查询天气数据。 用于读取和写入数据结构的库： CSV Utility SL : 读取和写入CSV文件 INI File Utility SL : 读写INI文件 JSON Utilities SL : 创建、读取和写入复杂的 JSON 文件（UTF-8、UTF-16）；读取和写入 JSON 字节数组并搜索键、值、子元素和父元素 XML Utility SL : 在控制器上读写XML文件或XML字符串并搜索XML元素 " }, 
{ "title" : "库：AWS IoT 核心客户端 SL ", 
"url" : "_iiot_lib_aws_core_client.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 库：AWS IoT 核心客户端 SL ", 
"snippet" : "“AWS IoT Core” 是亚马逊推出的管理云平台，联网设备可以在其中轻松安全地与云应用程序和其他设备协同工作。这个 AWS IoT 核心客户端 SL 库提供用于发送和接收消息的功能块。通信经过加密并通过 MQTT 协议进行。在 AWS 环境中，消息通常以 JSON 格式发送。这个 JSON Utilities 库可用于解析和创建 JSON 文件。 库的功能块： AWSIoTClient ：建立与“AWS IoT Core”的连接 AWSIoTPublish ：发布消息（Publish） AWSIoTSubscribe ：订阅主题（Subscribe） AWSIoTGetDeviceSha...", 
"body" : "“AWS IoT Core” 是亚马逊推出的管理云平台，联网设备可以在其中轻松安全地与云应用程序和其他设备协同工作。这个 AWS IoT 核心客户端 SL 库提供用于发送和接收消息的功能块。通信经过加密并通过 MQTT 协议进行。在 AWS 环境中，消息通常以 JSON 格式发送。这个 JSON Utilities 库可用于解析和创建 JSON 文件。 库的功能块： AWSIoTClient ：建立与“AWS IoT Core”的连接 AWSIoTPublish ：发布消息（Publish） AWSIoTSubscribe ：订阅主题（Subscribe） AWSIoTGetDeviceShadow ：读取“设备影子” AWSIoTUpdateDeviceShadow ：更新“设备影子”数据 AWSIoTSubscribeDeviceShadow ：订阅“设备影子”的更改 功能： 基于MQTT V3.1.1发布和订阅消息 TLS 加密 通过客户端证书进行身份验证 支持“服务质量”：0 和 1（QoS0、QoS1） 数据类型主题： WSTRING 主题最大大小：1024 最大包大小和有效负载大小，可通过参数列表进行配置 多任务和多核支持 支持“Last Will”消息（QoS0、QoS1） 通配符支持（# 和 +） 参见示例： 使用 AWS IoT Core 客户端 SL 库 。 " }, 
{ "title" : "库：Azure IoT 中心客户端 SL ", 
"url" : "_iiot_lib_azure_hub_client.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 库：Azure IoT 中心客户端 SL ", 
"snippet" : "这 Azure IoT 中心客户端 SL 该库提供了通过 Microsoft 的“Azure IoT Hub”云服务交换（发送和接收）消息的功能块。该库包含用于通过 HTTPS 和 MQTT 进行通信的单独功能块。 微软的“Azure IOT Hub”云服务是直接链接物联网设备的服务。 有关更多信息，请参阅： https:\/\/azure.microsoft.com\/en-us\/products\/iot-hub\/ 功能： 发送“设备到云 (D2C)”消息（遥测数据） 接收“云到设备（C2D）”消息 读取设备孪生（Device Twin） 更新设备孪生 订阅设备孪生（所需属性，仅通过 MQTT） ...", 
"body" : "这 Azure IoT 中心客户端 SL 该库提供了通过 Microsoft 的“Azure IoT Hub”云服务交换（发送和接收）消息的功能块。该库包含用于通过 HTTPS 和 MQTT 进行通信的单独功能块。 微软的“Azure IOT Hub”云服务是直接链接物联网设备的服务。 有关更多信息，请参阅： https:\/\/azure.microsoft.com\/en-us\/products\/iot-hub\/ 功能： 发送“设备到云 (D2C)”消息（遥测数据） 接收“云到设备（C2D）”消息 读取设备孪生（Device Twin） 更新设备孪生 订阅设备孪生（所需属性，仅通过 MQTT） 直接方法调用（云→设备，仅通过MQTT） 创建新的 Azure SAS 令牌（共享访问签名） 参见示例： 使用 Azure IoT 中心客户端 SL 库 。 " }, 
{ "title" : "图书馆： CSV Utility SL ", 
"url" : "_iiot_lib_csv_utility.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： CSV Utility SL ", 
"snippet" : "这 CSV 实用程序 SL 库提供读取和写入 CSV 文件的函数块。 该库由以下组件组成 CSVReader （读取 CSV 文件）和 CSVWriter （写入 CSV 文件）。所有功能块均可用于经典过程编程或面向对象编程。 参见示例： 使用 CSV 实用工具 SL 库 。...", 
"body" : "这 CSV 实用程序 SL 库提供读取和写入 CSV 文件的函数块。 该库由以下组件组成 CSVReader （读取 CSV 文件）和 CSVWriter （写入 CSV 文件）。所有功能块均可用于经典过程编程或面向对象编程。 参见示例： 使用 CSV 实用工具 SL 库 。 " }, 
{ "title" : "图书馆： INI File Utility SL ", 
"url" : "_iiot_lib_ini_file_utility.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： INI File Utility SL ", 
"snippet" : "这 INI 文件实用程序 SL 库提供用于读取、写入和查找 INI 文件中的值的函数块。 功能性 通过以下方式读取 INI 文件 INI_Reader 功能块 通过以下方式写入 INI 文件 INI_Writer 功能块 通过以下方式查找值 INI_Get 功能块...", 
"body" : "这 INI 文件实用程序 SL 库提供用于读取、写入和查找 INI 文件中的值的函数块。 功能性 通过以下方式读取 INI 文件 INI_Reader 功能块 通过以下方式写入 INI 文件 INI_Writer 功能块 通过以下方式查找值 INI_Get 功能块 " }, 
{ "title" : "描述 ", 
"url" : "_iiot_lib_ini_file_utility.html#UUID-dbf4b422-1186-cdeb-2171-77fc16d32635_section-idm4597881866457633093814221779", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： INI File Utility SL \/ 描述 ", 
"snippet" : "各个值映射到一个数组中 IniFileEntry 类型结构。该结构包含部分、键、值和注释字段。 支持的数据结构： ;Kommentar [Sektion] ;Kommentar Schlüssel=Wert 最大字段长度 部分：100 个字符 密钥：100 个字符 值：255 个字符 评论：2555 个字符 参见示例： 使用 INI 文件实用程序 SL 库 。...", 
"body" : "各个值映射到一个数组中 IniFileEntry 类型结构。该结构包含部分、键、值和注释字段。 支持的数据结构： ;Kommentar\n[Sektion]\n;Kommentar\nSchlüssel=Wert 最大字段长度 部分：100 个字符 密钥：100 个字符 值：255 个字符 评论：2555 个字符 参见示例： 使用 INI 文件实用程序 SL 库 。 " }, 
{ "title" : "图书馆： JSON Utilities SL ", 
"url" : "_iiot_lib_json_utilities.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： JSON Utilities SL ", 
"snippet" : "这个 JSON Utilities SL 库提供以下功能： 读取 JSON 文件（UTF-8 和 UTF-16） 读取 JSON 字节数组 写入 JSON 文件（UTF-8 和 UTF-16） 写入 JSON 字节数组 搜索键、值、子元素和父元素 一个简单的 REST 客户端可以轻松地与 Web Client SL 库（包含在包中）。 参见示例： 使用 JSON 实用工具 SL 库...", 
"body" : "这个 JSON Utilities SL 库提供以下功能： 读取 JSON 文件（UTF-8 和 UTF-16） 读取 JSON 字节数组 写入 JSON 文件（UTF-8 和 UTF-16） 写入 JSON 字节数组 搜索键、值、子元素和父元素 一个简单的 REST 客户端可以轻松地与 Web Client SL 库（包含在包中）。 参见示例： 使用 JSON 实用工具 SL 库 " }, 
{ "title" : "图书馆： JSON Web Token SL ", 
"url" : "_iiot_lib_json_web_token.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： JSON Web Token SL ", 
"snippet" : "这个 JSON Web Token SL 库包含一个用于在控制器上创建 JWT（JSON 网络令牌）的功能块。此处支持以下算法： HS256 HS384 HS512 RS256 参见示例： 使用 JSON Web 代币 SL 库 。...", 
"body" : "这个 JSON Web Token SL 库包含一个用于在控制器上创建 JWT（JSON 网络令牌）的功能块。此处支持以下算法： HS256 HS384 HS512 RS256 参见示例： 使用 JSON Web 代币 SL 库 。 " }, 
{ "title" : "图书馆： Mail Service SL ", 
"url" : "_iiot_lib_mail_service.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： Mail Service SL ", 
"snippet" : "这 邮件服务 SL 库包含通过 SMTP 和 POP3 协议发送、接收和删除电子邮件的功能块。与邮件服务器的通信可以加密（TLS）或不加密。 功能块： ServerFB SMTP 和 POP3 连接的基本功能块 可以建立与邮件服务器的加密 (TLS) 和未加密连接 (SMTPS)。 SendMail 通过 SMTP 发送电子邮件的功能块 ReceiveMail 通过 POP3 接收电子邮件的功能块 始终从服务器检索最旧的邮件。 DeleteMail 通过 POP3 删除电子邮件的功能块 邮件服务器必须支持“唯一邮件 ID”，以便可以从服务器接收或删除电子邮件。 参见示例： 使用邮件服务 SL ...", 
"body" : "这 邮件服务 SL 库包含通过 SMTP 和 POP3 协议发送、接收和删除电子邮件的功能块。与邮件服务器的通信可以加密（TLS）或不加密。 功能块： ServerFB SMTP 和 POP3 连接的基本功能块 可以建立与邮件服务器的加密 (TLS) 和未加密连接 (SMTPS)。 SendMail 通过 SMTP 发送电子邮件的功能块 ReceiveMail 通过 POP3 接收电子邮件的功能块 始终从服务器检索最旧的邮件。 DeleteMail 通过 POP3 删除电子邮件的功能块 邮件服务器必须支持“唯一邮件 ID”，以便可以从服务器接收或删除电子邮件。 参见示例： 使用邮件服务 SL 库 。 " }, 
{ "title" : "图书馆： MQTT Client SL ", 
"url" : "_iiot_lib_mqtt_client.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： MQTT Client SL ", 
"snippet" : "MQTT（消息队列遥测传输）是一种开源物联网协议，它允许遥测数据作为消息在设备之间传输。因此，您可以从发送消息 CODESYS 控制器到 MQTT 代理并根据主题订阅消息。 设备始终通过 MQTT 代理进行通信。 例子： 日食蚊子 消息根据主题发送和订阅。一个主题对应一个路径。 例子： device1\/temperature 订阅消息是通过指定主题过滤器来完成的。还允许使用通配符 ( + 对于一个级别， # 对于多个级别）。 消息的格式不固定。可以传输 JSON 字符串或任何数据结构。 的功能块 MQTT Client SL 图书馆： 用于建立 MQTT 链接的功能块（ MQTTClient ...", 
"body" : "MQTT（消息队列遥测传输）是一种开源物联网协议，它允许遥测数据作为消息在设备之间传输。因此，您可以从发送消息 CODESYS 控制器到 MQTT 代理并根据主题订阅消息。 设备始终通过 MQTT 代理进行通信。 例子： 日食蚊子 消息根据主题发送和订阅。一个主题对应一个路径。 例子： device1\/temperature 订阅消息是通过指定主题过滤器来完成的。还允许使用通配符 ( + 对于一个级别， # 对于多个级别）。 消息的格式不固定。可以传输 JSON 字符串或任何数据结构。 的功能块 MQTT Client SL 图书馆： 用于建立 MQTT 链接的功能块（ MQTTClient ） 用于发送消息的功能块（ MQTTPublish ） 用于订阅消息的功能块（ MQTTSubscribe ） 支持的功能： 基于MQTT V3.1.1和MQTT V5.0的消息发布和订阅 TLS 加密 支持客户端证书（证书句柄的传输） “服务质量”的支持： 0、1 和 2（QoS0、QoS1、QoS2）用于最后意愿、发布者和订阅者 主题的数据类型： WSTRING 主题最大大小：1024 最大包大小和有效负载大小可以通过参数列表进行配置。 多任务和多核支持 MQTTClient、MQTTPublish 和 MQTTSubscribe 各自可以在不同的任务或 CPU 内核上运行。 “最后遗嘱”消息（ QoS0 , QoS1 , QoS2 ） 通配符 ( # 和 + ） MQTT 或 WebSocket 支持的MQTT V5功能： Session Expiry Message Expiry Reason Code on All ACKs Server Disconnect Payload Format and Content Type Request \/ Response Shared Subscriptions Subscription ID Topic Alias Flow Control User Properties Maximum Packet Size Optional Server Feature Availability Enhanced Authentication Subscription Options Will Delay Server Keep Alive Assigned ClientID Server Reference " }, 
{ "title" : "消息吞吐量 ", 
"url" : "_iiot_lib_mqtt_client.html#UUID-51d354bd-4917-4dcc-438d-13a40e4cf002_section-idm4646452096859233781752769169", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： MQTT Client SL \/ 消息吞吐量 ", 
"snippet" : "最大消息吞吐量（消息数\/秒，mps）取决于所使用的硬件、消息大小、QoS 设置和配置（参数列表 MQTTParam、循环时间）。 测量示例 配置： 当地 Mosquito 经纪人 当地的 CODESYS Control (1 出版商) 当地的 CODESYS Control (1 位订户) MQTTParam （默认设置） 消息大小：1024字节 循环时间：1毫秒 结果： QoS0 => 大约190 英里\/秒 QoS1 => 大约130 英里\/秒 QoS2 => 大约90 英里\/秒 参见示例： 使用 MQTT 客户端 SL 库 。...", 
"body" : "最大消息吞吐量（消息数\/秒，mps）取决于所使用的硬件、消息大小、QoS 设置和配置（参数列表 MQTTParam、循环时间）。 测量示例 配置： 当地 Mosquito 经纪人 当地的 CODESYS Control (1 出版商) 当地的 CODESYS Control (1 位订户) MQTTParam （默认设置） 消息大小：1024字节 循环时间：1毫秒 结果： QoS0 => 大约190 英里\/秒 QoS1 => 大约130 英里\/秒 QoS2 => 大约90 英里\/秒 参见示例： 使用 MQTT 客户端 SL 库 。 " }, 
{ "title" : "图书馆： SNMP Service SL ", 
"url" : "_iiot_lib_snmp_service.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： SNMP Service SL ", 
"snippet" : "该库支持以下 SNMP 功能： SNMP GET 请求一个值（控制器是管理者） SNMP GET_NEXT 查询表（控制器是管理器） SNMP Agent: 查询控制器的值（控制器为代理） SNMP TRAP 发送和接收 TRAP\/INFORM 电报 SNMP SET 设定值 支持的 SNMP 版本：SNMP V1、SNMP V2c、SNMP V3 这 CreateRWUser 和 CreateUser 函数可用于创建 SNMP V3 用户。 这个 SNMP Service SL 库分为四个类别，存储在 Function Blocks 文件夹： Agent SNMP 代理的功能块 GET 用于...", 
"body" : "该库支持以下 SNMP 功能： SNMP GET 请求一个值（控制器是管理者） SNMP GET_NEXT 查询表（控制器是管理器） SNMP Agent: 查询控制器的值（控制器为代理） SNMP TRAP 发送和接收 TRAP\/INFORM 电报 SNMP SET 设定值 支持的 SNMP 版本：SNMP V1、SNMP V2c、SNMP V3 这 CreateRWUser 和 CreateUser 函数可用于创建 SNMP V3 用户。 这个 SNMP Service SL 库分为四个类别，存储在 Function Blocks 文件夹： Agent SNMP 代理的功能块 GET 用于查询值的功能块 Trap 用于发送和接收 TRAP 报文的功能块 SET 用于设置值的功能块 参见示例： 使用 SNMP 服务 SL 库 。 " }, 
{ "title" : "图书馆： SNTP Service SL ", 
"url" : "_iiot_lib_sntp_service.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： SNTP Service SL ", 
"snippet" : "这 SNTP Service SL 库包含用于构建 SNTP 客户端和服务器应用程序（SNTP V3、SNTP V4）的功能块。 SNTPGetUTCTime 通过 SNTP 请求时间的功能块（SNTP 客户端） 这 SNTPGetUTCTime 功能块可用于从 NTP\/SNTP 服务器请求 UTC 时间。 SNTPServer 通过 SNTP（SNTP 服务器）发送本地时间的功能块 SNTPServer 功能块充当简单的 SNTP 服务器 CODESYS 控制器。 参见示例： 使用 SNTP 服务 SL 库 。...", 
"body" : "这 SNTP Service SL 库包含用于构建 SNTP 客户端和服务器应用程序（SNTP V3、SNTP V4）的功能块。 SNTPGetUTCTime 通过 SNTP 请求时间的功能块（SNTP 客户端） 这 SNTPGetUTCTime 功能块可用于从 NTP\/SNTP 服务器请求 UTC 时间。 SNTPServer 通过 SNTP（SNTP 服务器）发送本地时间的功能块 SNTPServer 功能块充当简单的 SNTP 服务器 CODESYS 控制器。 参见示例： 使用 SNTP 服务 SL 库 。 " }, 
{ "title" : "图书馆： Web Client SL ", 
"url" : "_iiot_lib_web_client.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： Web Client SL ", 
"snippet" : "这个 Web Client SL 库包含用于通过以下方式与 Web 服务器通信的功能块 http https 。 使用时 http-GET ，可以从网络服务器请求数据。 使用时 http-POST 和 http-PUT ，数据可以从控制器发送到网络服务器。 使用时 http-DELETE ，可以在网络服务器上删除数据。 和 http-HEAD 可以请求http标头。 请求的 HTTP 标头可以根据需要进行扩展。此外，还包括用于 HTTP 基本身份验证和通过 OAuth（版本 1a 和 2）进行身份验证的功能块。 库功能块 WebClient 用于发送 HTTP 或 HTTPS 请求的功能块 这...", 
"body" : "这个 Web Client SL 库包含用于通过以下方式与 Web 服务器通信的功能块 http https 。 使用时 http-GET ，可以从网络服务器请求数据。 使用时 http-POST 和 http-PUT ，数据可以从控制器发送到网络服务器。 使用时 http-DELETE ，可以在网络服务器上删除数据。 和 http-HEAD 可以请求http标头。 请求的 HTTP 标头可以根据需要进行扩展。此外，还包括用于 HTTP 基本身份验证和通过 OAuth（版本 1a 和 2）进行身份验证的功能块。 库功能块 WebClient 用于发送 HTTP 或 HTTPS 请求的功能块 这 Web Client SL Example.project 示例项目展示了如何使用此功能块。 BasicAuthWebClient 具有 HTTP 基本身份验证的功能块，用于发送 HTTP 或 HTTPS 请求 OAuth1WebClient 具有 OAuth 身份验证（版本 1a）的功能块，用于发送 HTTP 或 HTTPS 请求 OAuth2WebClient 具有 OAuth 身份验证（版本 2）的功能块，用于发送 HTTP 或 HTTPS 请求 DigestAuthWebClient 具有摘要访问身份验证的功能块，用于发送 HTTP 或 HTTPS 请求 编码\/解码函数 BASE64_DECODE ：Base64 解码器 STRING BASE64_ENCODE ：Base64 编码器 STRING URL_ENCODE_WSTRING : URL 编码器 WSTRING URL_ENCODE_STRING : URL 编码器 STRING 参见示例： 使用 Web 客户端 SL 库 。 " }, 
{ "title" : "图书馆： Web Socket Client SL ", 
"url" : "_iiot_lib_web_socket_clinet.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： Web Socket Client SL ", 
"snippet" : "图书馆 Web Socket Client SL 提供通过Web Socket协议进行通信的功能模块。 成分 WebSocketClient 与功能块 WebSocketClient 可以建立与 Web 套接字服务器的连接。未加密（ ws:\/\/ ）和加密的（ wss:\/\/ ) 支持连接。 关于方法 Write 和 Read 可以发送和接收消息。 WebSocketRead 功能块 WebSocketRead 封装了 Read - 功能块的方法 WebSocketClient 用于图形实现语言（例如 CFC）。 WebSocketWrite 功能块 WebSocketWrite 封装了 Writ...", 
"body" : "图书馆 Web Socket Client SL 提供通过Web Socket协议进行通信的功能模块。 成分 WebSocketClient 与功能块 WebSocketClient 可以建立与 Web 套接字服务器的连接。未加密（ ws:\/\/ ）和加密的（ wss:\/\/ ) 支持连接。 关于方法 Write 和 Read 可以发送和接收消息。 WebSocketRead 功能块 WebSocketRead 封装了 Read - 功能块的方法 WebSocketClient 用于图形实现语言（例如 CFC）。 WebSocketWrite 功能块 WebSocketWrite 封装了 Write - 功能模块的方法 WebSocketClient 用于图形实现语言（例如 CFC）。 支持的功能 未加密的连接 (ws) 加密连接（wss、可配置的 TLS 设置） 可配置 ping 间隔 通过 HTTP 代理服务器进行通信 数据包碎片 可以通过“WebSocket Extensions”进行扩展（不包含在此库中） 任何子协议 参见示例： 使用 Web 套接字客户端 SL 库 。 " }, 
{ "title" : "图书馆： XML Utility SL ", 
"url" : "_iiot_lib_xml_utility.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： XML Utility SL ", 
"snippet" : "该库包含用于在控制器上读写 XML 文件和 XML 字符串的功能块。各个元素存储在结构数组中。 此外，该库还包含用于搜索 XML 元素的功能块。 该库可以使用 UTF-8 或 UTF-16 编码读取和写入“格式正确”的 XML 文件。 支持以下 XML 元素： 标准元件： <xxx>aaa<\/xxx> 或者 <xxx \/> 样式中的属性： yyy=\"zzz\" 评论： <!-- Comment --> CDATA元素 XML文件的每个元素对应一个类型的结构 XMLElement 。该类型的结构体数组 XMLElement 用于表示部分或整个 XML 文件。 结构 XMLElement 数据结构：...", 
"body" : "该库包含用于在控制器上读写 XML 文件和 XML 字符串的功能块。各个元素存储在结构数组中。 此外，该库还包含用于搜索 XML 元素的功能块。 该库可以使用 UTF-8 或 UTF-16 编码读取和写入“格式正确”的 XML 文件。 支持以下 XML 元素： 标准元件： <xxx>aaa<\/xxx> 或者 <xxx \/> 样式中的属性： yyy=\"zzz\" 评论： <!-- Comment --> CDATA元素 XML文件的每个元素对应一个类型的结构 XMLElement 。该类型的结构体数组 XMLElement 用于表示部分或整个 XML 文件。 结构 XMLElement 数据结构： diParentIndex : 父元素在数据数组中的位置 wsName ：元素名称 wsValue ：元素的值 udiPosition : 元素在文件中的位置 elementType ：元素类型（元素、属性、CDATA 元素、注释） 功能块： XMLGetElement 读取 XML 元素 读取选项 读取一个元素 读取某个元素的所有子元素 读取元素（子树）的所有组件 读取是基于文件的。这意味着可以通过单个元素在文件中的位置来读取它们，而无需将整个文档保留在内存中。 功能块： XMLGetElementAsync 异步读取 XML 元素 功能块： XMLFindElement 搜索文件中基于文件的 XML 元素 搜索选项： 搜索元素名称 搜索具有特定值的属性 读取找到的元素的所有子元素 读取找到的元素的所有组件（树结构） 可配置的搜索起始位置 功能块： XMLFindElementAsync 异步搜索 XML 元素（异步搜索查询） 功能块： XMLFindElementByStringAsync 异步搜索，工作原理如下 XMLFindElementAsync 但与 STRING 搜索输入 功能块： XMLWrite 写入 XML 文件 不支持元素的部分写入。所有元素及其依赖项始终加载到内存中（数组 XMLElement ）。 功能块： XMLWriteAsync 异步写入 XML 文件，工作方式如下 XMLWrite " }, 
{ "title" : "范围 ", 
"url" : "_iiot_lib_xml_utility.html#UUID-ef437133-40ff-afec-5303-bad595551d0c_section-idm4620348797614433793341355288", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： XML Utility SL \/ 范围 ", 
"snippet" : "元素的读取被缓冲。读取缓冲区必须至少与最大的 XML 元素一样大。可以通过库的参数列表在库管理器中更改最大大小。 这同样适用于字符串的大小 WSTRING 输入 XMLElement 数据结构。结果数组是在功能块外部生成的，因此可以单独配置大小。 参见示例： 使用 XML 实用工具 SL 库 。...", 
"body" : "元素的读取被缓冲。读取缓冲区必须至少与最大的 XML 元素一样大。可以通过库的参数列表在库管理器中更改最大大小。 这同样适用于字符串的大小 WSTRING 输入 XMLElement 数据结构。结果数组是在功能块外部生成的，因此可以单独配置大小。 参见示例： 使用 XML 实用工具 SL 库 。 " }, 
{ "title" : "图书馆： ", 
"url" : "_iiot_lib_open_weather.html", 
"breadcrumbs" : "CODESYS IIoT Libraries SL \/ CODESYS String Libraries \/ 图书馆： ", 
"snippet" : "随着 OpenWeather 客户端 库可以从 OpenWeather 提供的 API 服务器请求天气数据。 该库可以使用 UTF-8 或 UTF-16 编码读取和写入“格式正确”的 XML 文件。 目前支持以下服务： 查询特定地点的当前天气 查询特定地点未来 48 小时的每小时天气预报 通过以下方式查询位置信息 城市名称 邮政编码 GPS 坐标 要使用该库，你需要来自OpenWeather的API密钥。 参见示例： 使用 OpenWeather 客户端 SL 库 。...", 
"body" : "随着 OpenWeather 客户端 库可以从 OpenWeather 提供的 API 服务器请求天气数据。 该库可以使用 UTF-8 或 UTF-16 编码读取和写入“格式正确”的 XML 文件。 目前支持以下服务： 查询特定地点的当前天气 查询特定地点未来 48 小时的每小时天气预报 通过以下方式查询位置信息 城市名称 邮政编码 GPS 坐标 要使用该库，你需要来自OpenWeather的API密钥。 参见示例： 使用 OpenWeather 客户端 SL 库 。 " }
]
$(document).trigger('search.ready');
});