$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS PROFIBUS ", 
"url" : "_pbdp_start_page.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ CODESYS PROFIBUS ", 
"snippet" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 一个 PROFIBUS 网络由一个或多个主站和多个带模块的从站组成。在这个网络中， CODESYS 运行时系统可以用作主设备或从设备。 在主站 (1) 下方，您可以插入一个或多个带模块的从站 (2...", 
"body" : "有关设备编辑器的以下选项卡的信息，请参阅一般说明。 “<设备名称> I\/O 映射”选项卡 “<设备名称> IEC 对象”选项卡 “<设备名称> 参数”选项卡 “<设备名称> 状态”选项卡 “<设备名称> 信息”选项卡 相关设备编辑器的附加单独帮助页面仅在特殊功能的情况下可用。 如果未显示“<设备名称>参数”选项卡，则选择 显示通用设备配置编辑器 中的选项 CODESYS 选项，在 设备编辑器 类别。 一个 PROFIBUS 网络由一个或多个主站和多个带模块的从站组成。在这个网络中， CODESYS 运行时系统可以用作主设备或从设备。 在主站 (1) 下方，您可以插入一个或多个带模块的从站 (2)。在从设备 (3) 下方，您可以插入 I\/O 模块 (4)。 PROFIBUS 设备被导入 CODESYS 通过设备描述文件 (GSD)。这些文件随硬件提供。 在 CODESYS ，可以在设备树中插入一个USB接口用于 PROFIBUS .此接口（“Softing”公司的 PROFIusb）连接到计算机的 USB 端口，在网络中用作 PROFIBUS 掌握。它提供了一个完整的功能 PROFIBUS 掌握。 (1) PROFIBUS(2) PROFIBUS(3) PROFIBUS(4) PROFIBUS有关现场总线支持的更多一般信息，请参见 CODESYS ， 看： 现场总线支持 " }, 
{ "title" : "PROFIBUS 掌握 ", 
"url" : "_pbdp_f_master.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "配置 ", 
"url" : "_pbdp_f_master_configuration.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "PROFIBUS 大师 – NetX 配置 ", 
"url" : "_pbdp_edt_master_netx_configuration.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 大师 – NetX 配置 ", 
"snippet" : "作为一般的替代品 PROFIBUS 节点，您可以添加 PROFIBUS 在 NetX 现场总线的情况下，节点 (NetX) 到设备树。为该节点提供了设备编辑器中的 NetX 配置对话框，用于选择 NetX 芯片（适配器插槽）和该芯片上的通信通道。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 NetX 设置 投币口 要使用的插槽。对于带有 netX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 netX Com 频道 要在所选适配器上使用的通信通道。一个 netX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：下载或复位时，总线自动初始化，...", 
"body" : "作为一般的替代品 PROFIBUS 节点，您可以添加 PROFIBUS 在 NetX 现场总线的情况下，节点 (NetX) 到设备树。为该节点提供了设备编辑器中的 NetX 配置对话框，用于选择 NetX 芯片（适配器插槽）和该芯片上的通信通道。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 NetX 设置 投币口 要使用的插槽。对于带有 netX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 netX Com 频道 要在所选适配器上使用的通信通道。一个 netX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 ：下载或复位时，总线自动初始化，无需用户提示。 ：提示用户在下载或重置时是否应重新初始化总线。重新初始化会中断总线并可能导致机器出现意外行为。 为了 PROFIBUS NetX 配置，您可以使用 GetLiveList 检查连接硬件中可用的总线设备的方法。该方法包含在自动集成库中 IoDrvCifXProfibus .对于上升沿 xEnable 输入，该方法需要连接到 PROFIBUS 的所有设备的当前列表。操作完成时 wOpState 输出取值 HIL_DONE 或者 HIL_ERROR .该方法可以返回以下值： 00 = 电台不可用， 01 = 非活动站， 03 = 活动站 " }, 
{ "title" : "PROFIBUS 硕士 - 一般 ", 
"url" : "_pbdp_edt_master_general.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 硕士 - 一般 ", 
"snippet" : "你定义的参数 PROFIBUS 掌握此选项卡。参数在设备描述文件中定义，但可以在此对话框中编辑。 地址 车站地址 允许的范围为 0 到 126。 每个插入总线的新设备都会自动分配一个递增的地址。 注意：地址 126 是默认的 DP 从站地址。检查地址是否重复。 最高车站地址 总线上的最高站地址 (HSA)。要获得更严格的 GAP 范围，您可以在此处指定较低的地址。 GAP 范围：为新的活动设备扫描的地址范围。 模式 自动清除模式 : 如果出现错误，主站从 Operate 状态为 Clear 状态，并在从站未在 数据控制时间 .数字输出设置为 0，模拟输出设置为配置的替代值 (FailSave)...", 
"body" : "你定义的参数 PROFIBUS 掌握此选项卡。参数在设备描述文件中定义，但可以在此对话框中编辑。 地址 车站地址 允许的范围为 0 到 126。 每个插入总线的新设备都会自动分配一个递增的地址。 注意：地址 126 是默认的 DP 从站地址。检查地址是否重复。 最高车站地址 总线上的最高站地址 (HSA)。要获得更严格的 GAP 范围，您可以在此处指定较低的地址。 GAP 范围：为新的活动设备扫描的地址范围。 模式 自动清除模式 : 如果出现错误，主站从 Operate 状态为 Clear 状态，并在从站未在 数据控制时间 .数字输出设置为 0，模拟输出设置为配置的替代值 (FailSave)。必须重置主站才能重新启动通信。 ：万一出错，主控留在 Operate 状态和与所有从站的通信继续。 自动启动 : master 自己启动。 : master 必须手动启动。 注意：是否评估设置取决于驱动程序。 团体 打开 团体 对话。请参阅说明 团体 对话。 看门狗 NetX 固件的看门狗功能 ：如果驱动程序未在指定时间段内对其进行更新，则固件将停止运行。 这样可以确保固件无法继续运行，以防万一 CODESYS 应用程序因异常或类似情况而崩溃。 此选项不是 PROFIBUS 选项，但是一个 NetX 特定的功能。 范围 这些参数定义了通信的时间响应 PROFIBUS . 波特率 [kBits\/s]： 设备描述文件（GSD 文件）中定义的波特率。但是，您只能设置所有从站支持的波特率。 使用默认值 ：参数表中的值根据设置的波特率重置为默认值。 ：您可以更改参数表中的值。 T_SL “时隙时间”[Tbit]：主机在发送请求后等待从机响应的第一个迹象的最大时间跨度。 分钟。 T_SDR 最小“站延迟响应时间”[Tbit]：设备可以在总线上响应的最小响应时间（最小 11 Tbit） 最大限度。 T_SDR 最大“站延迟响应时间”[Tbit]：从站必须响应的最大时间跨度。 T_QUI 在将 NRZ（不归零）信号转换为其他编码（中继器的切换时间）期间必须考虑的空闲时间 T_SET “设置时间”[Tbit]：设置时间 T_TR “旋转目标时间”[Tbit]；主机应该接收令牌的预计时间间隔。总线上所有主设备的令牌停止时间总和的结果。 差距 GAP 更新因子 G：在主站 GAP（地址范围从它自己的总线地址到下一个活动站的地址）之后搜索一个附加的、最近插入的活动站的总线周期数。 重试限制 主站未收到从站有效响应时重复请求的最大尝试次数 从站间隔 从机可以处理来自主机的请求时的两个总线周期之间的时间（时基：100µs）。此处的值必须与从站的 GSD 文件中的规范一致。 轮询超时 在主站-主站通信（DP_Master 2 类）中，请求者必须接收主站响应的最长时间（时基：1ms）。 数据控制时间 主站与分配的从站通信其运行状态的时间 [ms]。同时，主站监控在此期间是否与从站分别发生了至少一次有效载荷交换，并更新Data_Transfer_List。 位 : 传输位的时间单位 PROFIBUS ;传输速率的倒数（例如，1 Tbit at 12 Mbaud = 1\/12,000,000 bps = 83 ns）。 " }, 
{ "title" : "对话：组 ", 
"url" : "_pbdp_edt_master_general.html#UUID-f1460cd2-489a-ac09-ebea-36b9b48be24d_id_ae41e6225ba076c0a8640e019a56ec_id_b909183dba6911e3b236e719d9984998", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 硕士 - 一般 \/ 对话：组 ", 
"snippet" : "在此对话框中，您可以将从站分配到八个可能组中的一个或多个。这些组用于同步主从之间的数据交换。您可以双击组名进行编辑。 同步 ：主站指示从站或组将所有输入值冻结在瞬间状态，并在下一次数据交换中传输此数据。 冻结 : 从站被指示同步转发所有数据，它们将在下一次数据交换中从主站接收。...", 
"body" : "在此对话框中，您可以将从站分配到八个可能组中的一个或多个。这些组用于同步主从之间的数据交换。您可以双击组名进行编辑。 同步 ：主站指示从站或组将所有输入值冻结在瞬间状态，并在下一次数据交换中传输此数据。 冻结 : 从站被指示同步转发所有数据，它们将在下一次数据交换中从主站接收。 " }, 
{ "title" : "PROFIBUS 奴隶 - 一般 ", 
"url" : "_pbdp_edt_slave_general.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 奴隶 - 一般 ", 
"snippet" : "的参数 PROFIBUS 从站在此选项卡上定义。参数在设备描述文件中定义，但可以在此对话框中进行编辑。 鉴别 车站地址 允许的范围为 0 到 126。 每个插入总线的新设备都会自动分配一个递增的地址。 注意：地址 126 是默认的 DP 从站地址。检查地址是否重复。 身份证号码 从 PNO 分配给此设备类型的唯一编号。这允许 DP 从站和 GSD 文件之间的唯一引用。 范围 TSDR (Tbit)： “时间站延迟响应者”。从机可以响应主机的最早响应时间（最小 11 Tbit） 锁定\/解锁： slave 被其他 master 阻塞或释放 0（TSDR 解锁） : min.TSDR 和从站特定的参...", 
"body" : "的参数 PROFIBUS 从站在此选项卡上定义。参数在设备描述文件中定义，但可以在此对话框中进行编辑。 鉴别 车站地址 允许的范围为 0 到 126。 每个插入总线的新设备都会自动分配一个递增的地址。 注意：地址 126 是默认的 DP 从站地址。检查地址是否重复。 身份证号码 从 PNO 分配给此设备类型的唯一编号。这允许 DP 从站和 GSD 文件之间的唯一引用。 范围 TSDR (Tbit)： “时间站延迟响应者”。从机可以响应主机的最早响应时间（最小 11 Tbit） 锁定\/解锁： slave 被其他 master 阻塞或释放 0（TSDR 解锁） : min.TSDR 和从站特定的参数可以被覆盖。 1（将解锁） ：奴隶被释放给其他主人。 2（锁定） ：slave被其他master阻塞，所有参数都被接受。 3（解锁） : 从站再次从主站释放。 * TBit：传输位的时间单位 PROFIBUS ;传输速率的倒数；例如 1 Tbit 在 12MBaud = 1\/12,000,000 bps=83ns 监控 看门狗控制 ： ：应用定义的监控时间（看门狗、阈值监控和以 10 毫秒为基准）。如果在这段时间内从站没有被主站访问，则将其重置为其初始化状态。 时间（毫秒） ：监控时间，与“看门狗控制”选项激活时的情况有关。 监测时间，与案件相关的时间 看门狗控制 选项处于活动状态。 团体 打开 团体 对话。 用户参数 除基本 DP 参数外，用户参数是 DP 从站的各个参数。当它们在设备描述文件（GSD 文件）中定义时，它们会显示在此处。参数值可以通过点击相应的字段来编辑 价值 柱子。 符号值 ：当在设备描述文件（GSD文件）中指定时，也可以显示参数的符号名称 用户参数长度（字节） 添加了由设备描述文件定义的用户参数。 默认值 将值恢复为默认设置。 " }, 
{ "title" : "对话：组 ", 
"url" : "_pbdp_edt_slave_general.html#UUID-e202dcf2-9dff-25e9-8597-6d3ac8d70578_id_f3e8684522a4fbe3c0a8640e01189575_id_b909183dba6911e3b236e719d9984998", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 奴隶 - 一般 \/ 对话：组 ", 
"snippet" : "在此对话框中，您可以将从站分配到八个可能组中的一个或多个。这些组用于同步主从之间的数据交换。您可以双击组名进行编辑。 同步 ：主站指示从站或组将所有输入值冻结在瞬间状态，并在下一次数据交换中传输此数据。 冻结 : 从站被指示同步转发所有数据，它们将在下一次数据交换中从主站接收。...", 
"body" : "在此对话框中，您可以将从站分配到八个可能组中的一个或多个。这些组用于同步主从之间的数据交换。您可以双击组名进行编辑。 同步 ：主站指示从站或组将所有输入值冻结在瞬间状态，并在下一次数据交换中传输此数据。 冻结 : 从站被指示同步转发所有数据，它们将在下一次数据交换中从主站接收。 " }, 
{ "title" : "PROFIBUS 从站 – 诊断 ", 
"url" : "_pbdp_edt_slave_diagnosis.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 从站 – 诊断 ", 
"snippet" : "从站的诊断数据显示在选项卡上。此信息对于错误检查很有用。 车站状态 DP_StationStatus 1-3 根据 PROFIBUS 规格 主地址 地址的站地址 PROFIBUS 主控（如果已连接）；否则为 0xFF 身份证号码 从站的 ID 号（在相关 GSD 文件中定义） 扩展诊断 扩展诊断数据根据 PROFIBUS 规范（IEC 61158-6）。通道特定的诊断使用 GSD 文件逐项列出并显示为文本。...", 
"body" : "从站的诊断数据显示在选项卡上。此信息对于错误检查很有用。 车站状态 DP_StationStatus 1-3 根据 PROFIBUS 规格 主地址 地址的站地址 PROFIBUS 主控（如果已连接）；否则为 0xFF 身份证号码 从站的 ID 号（在相关 GSD 文件中定义） 扩展诊断 扩展诊断数据根据 PROFIBUS 规范（IEC 61158-6）。通道特定的诊断使用 GSD 文件逐项列出并显示为文本。 " }, 
{ "title" : "PROFIBUS 模块 - 通用 ", 
"url" : "_pbdp_edt_module_general.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 配置 \/ PROFIBUS 模块 - 通用 ", 
"snippet" : "的参数 PROFIBUS 模块在此选项卡上定义。参数在设备描述文件中定义，但可以在此对话框中编辑。 模块信息 配置 从站的 I\/O 配置 输入长度 设备描述文件（GSD 文件）中定义的输入数据的长度（以字节为单位）。 输出长度 设备描述文件（GSD 文件）中定义的输出数据长度（以字节为单位）。 用户参数 符号值 ：当在设备描述文件（GSD文件）中指定时，也可以显示参数的符号名称 用户参数长度（字节） 添加了由设备描述文件定义的用户参数。 默认值 将值恢复为默认设置。 位 : 传输位的时间单位 PROFIBUS ;传输速率的倒数（例如，1 Tbit at 12 Mbaud = 1\/12,000,...", 
"body" : "的参数 PROFIBUS 模块在此选项卡上定义。参数在设备描述文件中定义，但可以在此对话框中编辑。 模块信息 配置 从站的 I\/O 配置 输入长度 设备描述文件（GSD 文件）中定义的输入数据的长度（以字节为单位）。 输出长度 设备描述文件（GSD 文件）中定义的输出数据长度（以字节为单位）。 用户参数 符号值 ：当在设备描述文件（GSD文件）中指定时，也可以显示参数的符号名称 用户参数长度（字节） 添加了由设备描述文件定义的用户参数。 默认值 将值恢复为默认设置。 位 : 传输位的时间单位 PROFIBUS ;传输速率的倒数（例如，1 Tbit at 12 Mbaud = 1\/12,000,000 bps = 83 ns）。 " }, 
{ "title" : "职能 ", 
"url" : "_pbdp_f_master_functions.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "入门 - 调试 NetX 适配器 ", 
"url" : "_pbdp_netx_first_steps.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 入门 - 调试 NetX 适配器 ", 
"snippet" : "要求：将 NetX 适配器插入计算机的插槽中。...", 
"body" : "要求：将 NetX 适配器插入计算机的插槽中。 " }, 
{ "title" : "1.安装Windows驱动 ", 
"url" : "_pbdp_netx_first_steps.html#UUID-71c5ad6a-0f38-6f46-9704-23113b136942_id_c36b769c094a0331c0a8640e0179d67d_id_56bc7eca00ab11e6a73efe9f2c37d211", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 入门 - 调试 NetX 适配器 \/ 1.安装Windows驱动 ", 
"snippet" : "如果您想将 NetX 适配器与 CODESYS 运行时，那么您必须安装以下驱动程序： 为了 CODESYS Control Win ： SysDrv3s.sys 司机 为了 CODESYS Control RTE ： RTIOwdmGenericc.sys 司机或 SysDrv3s.sys 司机 注意：安装的驱动程序必须是被动的。使用时 CODESYS Control RTE ，也可以根本不安装特定的驱动程序。 安装时 CODESYS Control Win ， 这 SysDrv3s.sys 驱动程序保存在程序文件夹中 ..\/GatewayPLC\/Driver ;为了 CODESYS Cont...", 
"body" : "如果您想将 NetX 适配器与 CODESYS 运行时，那么您必须安装以下驱动程序： 为了 CODESYS Control Win ： SysDrv3s.sys 司机 为了 CODESYS Control RTE ： RTIOwdmGenericc.sys 司机或 SysDrv3s.sys 司机 注意：安装的驱动程序必须是被动的。使用时 CODESYS Control RTE ，也可以根本不安装特定的驱动程序。 安装时 CODESYS Control Win ， 这 SysDrv3s.sys 驱动程序保存在程序文件夹中 ..\/GatewayPLC\/Driver ;为了 CODESYS Control RTE ， 在里面 ..\/SysDrv3s 文件夹。 NetX 固件和 NetX 引导加载程序位于 HilscherCIFX 两个运行时的文件夹。 NetX 固件和 NetX Second Stage Boot Loader 的版本必须相同。否则，NetX 固件和现场总线将无法工作。 每次启动运行时，都会将 NetX Second Stage Boot Loader 和 NetX 固件重新加载到 NetX 芯片中。 " }, 
{ "title" : "2. 编辑文件“CODESYSControl.cfg” CODESYS 运行时系统文件夹 ", 
"url" : "_pbdp_netx_first_steps.html#UUID-71c5ad6a-0f38-6f46-9704-23113b136942_id_c36b769c094a0331c0a8640e0179d67d_id_56a8cf9c00ab11e6a73efe9f2c37d211", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 入门 - 调试 NetX 适配器 \/ 2. 编辑文件“CODESYSControl.cfg” CODESYS 运行时系统文件夹 ", 
"snippet" : "打开文件 CODESYSControl.cfg 文本编辑器中的相应运行时系统目录。 删除部分中的分号 [ComponentManager] 在条目的开头 CmpHilscherCIFX 以便不再注释掉该条目。 在那个地区 [CmpHilscherCIFX] ，请按照以下步骤编辑 NetX 适配器和 NetX 配置的条目。 固件和引导加载程序必须存在以下条目： DynamicFirmware=1 BootloaderFile=.\/HilscherCIFX\/Firmware\/NETX100-BSL.bin FirmwareFilePath=.\/HilscherCIFX\/Firmware 如果输入 ...", 
"body" : "打开文件 CODESYSControl.cfg 文本编辑器中的相应运行时系统目录。 删除部分中的分号 [ComponentManager] 在条目的开头 CmpHilscherCIFX 以便不再注释掉该条目。 在那个地区 [CmpHilscherCIFX] ，请按照以下步骤编辑 NetX 适配器和 NetX 配置的条目。 固件和引导加载程序必须存在以下条目： DynamicFirmware=1 BootloaderFile=.\/HilscherCIFX\/Firmware\/NETX100-BSL.bin FirmwareFilePath=.\/HilscherCIFX\/Firmware 如果输入 DMAMode=1 被注释掉，然后去掉分号 ( ; ) 在行首。 删除以下条目前面的分号： Device.0.BootloaderFilePath=.\\HilscherCIFX\\Firmware\\NETX100-BSL.bin Device.0.Channel.0.FirmwareFile=.\\.\\HilscherCIFX\\Firmware\\cifxcom.nxf 描述： Device.X.BootloaderFilePath ：指定每个 NetX 芯片的 NetX 引导加载程序的文件路径和文件名。 （相对路径从安装文件夹开始，绝对路径也可以。）如果使用多个NetX芯片，还必须指定多个文件路径： Device.0.BootloaderFilePath=.\\HilscherCIFX\\Firmware\\NETX100-BSL.bin Device.1.BootloaderFilePath=.\\HilscherCIFX\\Firmware\\NETX100-BSL.bin Device.X.Channel.X.FirmwareFile ：指定每个 NetX 芯片和每个通道的 NetX 固件的文件路径和文件名。 （相对路径从安装文件夹开始。绝对路径也可以。）在大多数情况下，只使用通道 0。如果使用多个 NetX 芯片，还必须指定多个文件路径： Device.0.Channel.0.FirmwareFile=.\\HilscherCIFX\\Firmware\\cifxcom.nxf Device.1.Channel.0.FirmwareFile=.\\HilscherCIFX\\Firmware\\cifxcom.nxf 如果您想从您的控制器（控制器的设备编辑器， 日志 选项卡），然后删除分号（ ; ) 在以下位置：在该地区 [CmpHilscherCIFX] 进入前 TraceLevel=0xffffffff ，并且在该区域 [CmpLog] 在条目之前： Logger.0.Name=PlcLog Logger.0.Filter=0xFFFFFFFF 保存文件 CODESYSControl.cfg . " }, 
{ "title" : "3. 为项目创建 NetX 配置 ", 
"url" : "_pbdp_netx_first_steps.html#UUID-71c5ad6a-0f38-6f46-9704-23113b136942_id_c36b769c094a0331c0a8640e0179d67d_id_fbc81bc514a08d38c0a8640e00b9b921", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 入门 - 调试 NetX 适配器 \/ 3. 为项目创建 NetX 配置 ", 
"snippet" : "在 CODESYS ， 点击 文件 → 新项目 创建一个新的标准项目。在里面 新项目 对话框，选择 标准项目 模板。 在 标准对话框 ，选择控制器（例如： CODESYS Control Win ) 并单击 行 . 新的标准项目显示在设备树中。 点击 添加设备 在控制器的上下文菜单中。 在里面 添加设备 的对话 Profibus → DP 主站 ，选择一个 NetX 现场总线主站（例如： CIFX-PB ) 并单击 添加设备 . 双击设备树中的 NetX 现场总线主站（例如： CIFX-PB ) 并选择 PROFIBUS 编辑器中的选项卡。 选择 插槽 0 来自 投币口 列表框和 NetXCo...", 
"body" : "在 CODESYS ， 点击 文件 → 新项目 创建一个新的标准项目。在里面 新项目 对话框，选择 标准项目 模板。 在 标准对话框 ，选择控制器（例如： CODESYS Control Win ) 并单击 行 . 新的标准项目显示在设备树中。 点击 添加设备 在控制器的上下文菜单中。 在里面 添加设备 的对话 Profibus → DP 主站 ，选择一个 NetX 现场总线主站（例如： CIFX-PB ) 并单击 添加设备 . 双击设备树中的 NetX 现场总线主站（例如： CIFX-PB ) 并选择 PROFIBUS 编辑器中的选项卡。 选择 插槽 0 来自 投币口 列表框和 NetXComChannel0 从 NetX 通讯频道 . 注意：所选插槽的编号（例如： 插槽 0 ) 必须与文件中的设备编号相对应 CODESYSControl.cfg （例子： Device.0 ）。同样，被选中的数量 NetX 通讯频道 （例子： NetX Com 频道 0 ) 必须与文件中的条目相对应 CODESYSControl.cfg （例子： Channel.0 ）。 登录控制器并单击 调试 → 开始 启动应用程序。 如果没有错误消息，则说明 NetX 适配器已正确配置，您现在可以继续开发项目。 " }, 
{ "title" : "添加 USB 接口 PROFIBUS ", 
"url" : "_pbdp_adding_usb_interface.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 添加 USB 接口 PROFIBUS ", 
"snippet" : "PROFIusb 接口仅在 Windows 操作系统中起作用，它不是实时的。 要求：驱动程序必须安装在 Windows 中。驱动程序和手册包含在适配器的标准交付范围内，也可以从 Softing 网站下载。 将“PROFIusb”对象插入到 PLC 下方的设备树中。 在编辑器中，从安装路径的“GatewayPLC”子目录中打开“CoDeSysControl.cfg”文件。 转到“[ComponentManager]”部分。 在第一个空闲位置，输入“CmpSoftingProfibus”。 保存文件并关闭编辑器。 重新启动运行时系统。 检查组件是否已加载。通过打开 PLC 配置器并选择 日志 标签...", 
"body" : "PROFIusb 接口仅在 Windows 操作系统中起作用，它不是实时的。 要求：驱动程序必须安装在 Windows 中。驱动程序和手册包含在适配器的标准交付范围内，也可以从 Softing 网站下载。 将“PROFIusb”对象插入到 PLC 下方的设备树中。 在编辑器中，从安装路径的“GatewayPLC”子目录中打开“CoDeSysControl.cfg”文件。 转到“[ComponentManager]”部分。 在第一个空闲位置，输入“CmpSoftingProfibus”。 保存文件并关闭编辑器。 重新启动运行时系统。 检查组件是否已加载。通过打开 PLC 配置器并选择 日志 标签。 来自 动态： cmpSoftingProfibus 初始化 入口，可以看到组件已经加载完毕。 " }, 
{ "title" : "PROFIBUS – 总线循环任务 ", 
"url" : "_pbdp_buscycle_task.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ PROFIBUS – 总线循环任务 ", 
"snippet" : "有关更多信息，请参阅： 任务配置 PROFIBUS 不提供任何附加设置。它的功能对应于一般描述。...", 
"body" : "有关更多信息，请参阅： 任务配置 PROFIBUS 不提供任何附加设置。它的功能对应于一般描述。 " }, 
{ "title" : "一般信息 ", 
"url" : "_pbdp_buscycle_task.html#UUID-5a2fbbf8-6908-f377-cf77-ba76c0bb0901_UUID-9ddb6f66-1968-0a0f-3ec1-3510b0816b2e", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ PROFIBUS – 总线循环任务 \/ 一般信息 ", 
"snippet" : "通常，对于每个 IEC 任务，在每个任务开始时读取使用的输入数据 (1)，并在任务结束时将写入的输出数据传输到 I\/O 驱动程序 (3)。 I\/O 驱动程序中的实现对于 I\/O 数据的额外传输具有决定性意义。它负责实际传输到相应总线系统的时间范围和时间点。 PLC 的总线循环任务可以在 PLC 设置中为所有现场总线全局定义。但是，对于某些现场总线，您可以独立于全局设置进行更改。循环时间最短的任务用作总线循环任务（设置： 未指定 在 PLC 设置中）。在此任务中，消息通常在总线上发送。 其他任务仅从内部缓冲区复制 I\/O 数据，该缓冲区仅与总线周期任务中的物理硬件交换。 (1) 从输入缓冲区读取...", 
"body" : "通常，对于每个 IEC 任务，在每个任务开始时读取使用的输入数据 (1)，并在任务结束时将写入的输出数据传输到 I\/O 驱动程序 (3)。 I\/O 驱动程序中的实现对于 I\/O 数据的额外传输具有决定性意义。它负责实际传输到相应总线系统的时间范围和时间点。 PLC 的总线循环任务可以在 PLC 设置中为所有现场总线全局定义。但是，对于某些现场总线，您可以独立于全局设置进行更改。循环时间最短的任务用作总线循环任务（设置： 未指定 在 PLC 设置中）。在此任务中，消息通常在总线上发送。 其他任务仅从内部缓冲区复制 I\/O 数据，该缓冲区仅与总线周期任务中的物理硬件交换。 (1) 从输入缓冲区读取输入 (2) IEC 任务 (3) 将输出写入输出缓冲区 (4) 总线周期 (5) 输入缓冲器 (6) 输出缓冲器 (7) 向\/从总线复制数据 (9) 总线循环任务，优先级 1，1 ms (10) 总线循环任务，优先级 5 (11) 总线循环任务，优先级 10，被任务 5 中断 任务使用 这 任务部署 选项卡提供已用 I\/O 通道、设置总线周期任务和通道使用情况的概览。 如果在各种任务中写入输出，则状态未定义，因为在每种情况下都可以覆盖。 如果在不同的任务中使用相同的输入，那么输入可能会在任务处理过程中发生变化。当任务被具有更高优先级的任务中断并导致再次读取过程映像时，会发生这种情况。解决方案：在 IEC 任务开始时，将输入变量复制到变量中，然后在其余代码中仅使用局部变量。 结论：在多个任务中使用相同的输入和输出没有任何意义，并且在某些情况下会导致意外反应。 " }, 
{ "title" : "命令：扫描设备 ", 
"url" : "_pbdp_cmd_scan_devices.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 命令：扫描设备 ", 
"snippet" : "功能 ：该命令建立与硬件的临时连接并检测网络中的设备。然后您可以将扫描的设备应用到项目的设备树中。 称呼 ： 项目 菜单;设备树中设备对象的上下文菜单 要求 ：与控制器的通信设置正确。网关和 PLC 启动。设备支持扫描功能。 以下设备提供扫描功能：EtherCAT Master、EtherNet\/IP Scanner (IEC)、Sercos Master、CANopen Manager、CANopen Manager SIL2、Profinet Controller 和 Profibus DP Master。 如果扫描功能在 PLC 中永久实现，您可以立即执行设备扫描。在库中实现扫描功能时，...", 
"body" : "功能 ：该命令建立与硬件的临时连接并检测网络中的设备。然后您可以将扫描的设备应用到项目的设备树中。 称呼 ： 项目 菜单;设备树中设备对象的上下文菜单 要求 ：与控制器的通信设置正确。网关和 PLC 启动。设备支持扫描功能。 以下设备提供扫描功能：EtherCAT Master、EtherNet\/IP Scanner (IEC)、Sercos Master、CANopen Manager、CANopen Manager SIL2、Profinet Controller 和 Profibus DP Master。 如果扫描功能在 PLC 中永久实现，您可以立即执行设备扫描。在库中实现扫描功能时，只需登录一次即可将库下载到控制器。 该命令适用于在设备树中选择的主控制器。例如，一个已经插入的 PROFINET 可以选择控制器和用于确定分配给它的 I\/O 设备和 I\/O 模块的命令。 执行扫描操作后， 扫描设备 对话框打开并显示扫描的设备。 " }, 
{ "title" : "“扫描设备”对话框 ", 
"url" : "_pbdp_cmd_scan_devices.html#UUID-f23d5d86-b381-153c-4923-d77dfd416c36_UUID-87d819e6-40ac-9a7c-b963-a6e4714caeeb", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 命令：扫描设备 \/ “扫描设备”对话框 ", 
"snippet" : "扫描的设备 设备名称、设备类型、地址、站名等 扫描设备的数据取决于网络类型。 当您更改扫描设备列表中的值时，该值以斜体显示。这表明新值在编辑器中已更改 CODESYS ，但不在设备中。当您将值下载到设备时，它会正常显示。 指示项目和扫描设备之间差异的值以橙色显示。 如果扫描设备有多个设备描述可用，则名称以粗体显示。对于不同的现场总线，匹配设备描述的选择是不同的。更多详细信息，请参见相应的现场总线章节。 如果找不到设备描述，则会显示以下消息：“注意！在存储库中找不到设备。”根据总线系统，会显示附加信息，例如供应商编号和产品编号。如果没有安装的设备描述，则无法将设备插入到项目中。 显示与项目的差异...", 
"body" : "扫描的设备 设备名称、设备类型、地址、站名等 扫描设备的数据取决于网络类型。 当您更改扫描设备列表中的值时，该值以斜体显示。这表明新值在编辑器中已更改 CODESYS ，但不在设备中。当您将值下载到设备时，它会正常显示。 指示项目和扫描设备之间差异的值以橙色显示。 如果扫描设备有多个设备描述可用，则名称以粗体显示。对于不同的现场总线，匹配设备描述的选择是不同的。更多详细信息，请参见相应的现场总线章节。 如果找不到设备描述，则会显示以下消息：“注意！在存储库中找不到设备。”根据总线系统，会显示附加信息，例如供应商编号和产品编号。如果没有安装的设备描述，则无法将设备插入到项目中。 显示与项目的差异 ：对话框中的表格还显示了其他配置的设备（在项目的设备树中）。 ：表格显示所有扫描的设备。未显示配置的设备。 扫描设备 开始新的搜索。 将所有设备复制到项目 在表中选择的设备被插入到项目的设备树中。如果未选择任何内容，则显示所有扫描的设备。 如果你使用 将所有设备复制到项目 要将设备树中可用的设备插入设备树，则应注意以下几点： 处理数据 和 <...> I\/O 映射 现有设备的选项卡可能会被最近插入的设备的数据覆盖。 配置的设备 对话框的这一部分仅在您选择 显示与项目的差异 选项。 扫描设备和配置设备之间的差异是用颜色编码的。两侧显示为绿色的设备相同。以红色显示的设备仅在扫描或配置的设备视图中可用。 如果您在两个视图中都选择了一个设备，则扫描的设备将插入到所选配置设备的上方。 如果您在两个视图中都选择了一个设备，则扫描的设备将插入到所选配置设备的下方。 如果您在两个视图中都选择了一个设备，则配置的设备将替换为选定的扫描设备。 所有扫描的设备都被复制到项目中。 删除选定的已配置设备。 " }, 
{ "title" : "特殊设置 PROFIBUS ", 
"url" : "_pbdp_cmd_scan_devices.html#UUID-f23d5d86-b381-153c-4923-d77dfd416c36_id_b77ccdcdd2b37a5c0a8640e00c2ece5_id_e048493f007711e5a751897176b6e942", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ 命令：扫描设备 \/ 特殊设置 PROFIBUS ", 
"snippet" : "扫描设备 新的设备搜索 PROFIBUS 主网。 将所有设备复制到项目 将所有选定的从站复制到项目中。具有相同地址的现有从站将被覆盖。 状态 扫描和投影的从站由站地址分配。 ：检测到的设备与配置的设备匹配。 : 未检测到具有相同站地址的设备。 ：可以将检测到的设备分配给配置的设备，但模块配置不同。 使用可用信息（从站的 ID 号、模块的 I\/O 配置）无法对特定制造商的设备进行唯一分配。这 添加设备 对话框打开，您可以在其中手动将扫描的设备分配给项目中可用的设备。...", 
"body" : "扫描设备 新的设备搜索 PROFIBUS 主网。 将所有设备复制到项目 将所有选定的从站复制到项目中。具有相同地址的现有从站将被覆盖。 状态 扫描和投影的从站由站地址分配。 ：检测到的设备与配置的设备匹配。 : 未检测到具有相同站地址的设备。 ：可以将检测到的设备分配给配置的设备，但模块配置不同。 使用可用信息（从站的 ID 号、模块的 I\/O 配置）无法对特定制造商的设备进行唯一分配。这 添加设备 对话框打开，您可以在其中手动将扫描的设备分配给项目中可用的设备。 " }, 
{ "title" : "CIFX-PB – PROFIBUS 掌握 ", 
"url" : "_pbdp_cifx.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 掌握 \/ 职能 \/ CIFX-PB – PROFIBUS 掌握 ", 
"snippet" : "CODESYS 支持 Hilscher 的 CIFX-PB PC 卡。 以下 PROFIBUS 大师，插入 PROFIBUS 您通过 GSD 导入安装到设备存储库的从站和模块。在编辑器对话框中，您设置典型的 PROFIBUS 参数和 I\/O 通道。 点击 扫描设备 添加 PROFIBUS 设备自动低于 PROFIBUS 设备树中的主控。 CIFX PROFIBUS 主固件（版本 V2.8.0.0 及更高版本）支持 CODESYS 冗余。在里面 冗余配置 编辑，在 冗余设置 选项卡，在 一般的 子选项卡，选择 现场总线 选项。 此外，在 冗余配置 编辑，在 注册区域 选项卡，添加输出数据区域（ ...", 
"body" : "CODESYS 支持 Hilscher 的 CIFX-PB PC 卡。 以下 PROFIBUS 大师，插入 PROFIBUS 您通过 GSD 导入安装到设备存储库的从站和模块。在编辑器对话框中，您设置典型的 PROFIBUS 参数和 I\/O 通道。 点击 扫描设备 添加 PROFIBUS 设备自动低于 PROFIBUS 设备树中的主控。 CIFX PROFIBUS 主固件（版本 V2.8.0.0 及更高版本）支持 CODESYS 冗余。在里面 冗余配置 编辑，在 冗余设置 选项卡，在 一般的 子选项卡，选择 现场总线 选项。 此外，在 冗余配置 编辑，在 注册区域 选项卡，添加输出数据区域（ %Q ) 到同步数据区。 " }, 
{ "title" : "PROFIBUS 从设备 ", 
"url" : "_pbdp_f_slave_device.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 从设备 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "配置 ", 
"url" : "_pbdp_f_slave_device_configuration.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 从设备 \/ 配置 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "PROFIBUS 从设备 – NetX 配置 ", 
"url" : "_pbdp_edt_slavedevice_netx_configuration.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 从设备 \/ 配置 \/ PROFIBUS 从设备 – NetX 配置 ", 
"snippet" : "该选项卡用于设置 NetX 参数。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 目的： PROFIBUS 从设备 (NetX) NetX 设置 投币口 要使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 要在所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 默认情况下启用此选项。当它被停用时，系统会提示用户是否应该在下载或重置时重新初始化总线。重新初始化会中断总线并可能导致机器出现意外行为。...", 
"body" : "该选项卡用于设置 NetX 参数。对话框中设置的名称以及列表框中已存在的任何可能设置由设备描述定义。 目的： PROFIBUS 从设备 (NetX) NetX 设置 投币口 要使用的插槽。对于带有 NetX 芯片的 PCI 适配器，插槽编号通常与适配器编号相对应。 NetX Com 频道 要在所选适配器上使用的通信通道。一个 NetX 适配器最多可以有四个通向不同现场总线的通信通道。 自动总线初始化 默认情况下启用此选项。当它被停用时，系统会提示用户是否应该在下载或重置时重新初始化总线。重新初始化会中断总线并可能导致机器出现意外行为。 " }, 
{ "title" : "PROFIBUS 从设备 – 常规 ", 
"url" : "_pbdp_edt_slavedevice_general.html", 
"breadcrumbs" : "CODESYS PROFIBUS \/ PROFIBUS 从设备 \/ 配置 \/ PROFIBUS 从设备 – 常规 ", 
"snippet" : "该选项卡用于配置 DP 从站的主要设置以在网络中进行数据交换。 设置 地址 从站的站地址在 PROFIBUS 网络。可能的值：1–126。默认值：126 波特率 数据交换的波特率。可能的设置：自动（默认；从总线主控器预定义的波特率）、9,600 \/ 19,200 \/ 31,250 \/ 45,450 \/ 93,750 \/ 18,750 \/ 500 \/ 1500 \/ 300 \/ 600 \/ 12000）...", 
"body" : "该选项卡用于配置 DP 从站的主要设置以在网络中进行数据交换。 设置 地址 从站的站地址在 PROFIBUS 网络。可能的值：1–126。默认值：126 波特率 数据交换的波特率。可能的设置：自动（默认；从总线主控器预定义的波特率）、9,600 \/ 19,200 \/ 31,250 \/ 45,450 \/ 93,750 \/ 18,750 \/ 500 \/ 1500 \/ 300 \/ 600 \/ 12000） " }
]
$(document).trigger('search.ready');
});