$(document).ready(function () {indexDict['ja'] = [{ "title" : "CODESYS SoftMotion Stäubli Support ", 
"url" : "_smstbli_start_page.html", 
"breadcrumbs" : "CODESYS SoftMotion Stäubli Support \/ CODESYS SoftMotion Stäubli Support ", 
"snippet" : "制限事項 CODESYS EtherCAT バージョン 4.10.0.0 には、「デバイスから PDO 情報を読み込む」機能に関する既知の問題があり、これにより、正常に動作しなくなる CODESYS SoftMotion Stäubli Support パッケージ。 以前のバージョンまたは新しいバージョンのいずれかを使用してください CODESYS EtherCAT 代わりに。 ザル CODESYS SoftMotion Stäubli Support アドオンにより制御が可能になります Stäubli TS2およびTX2シリーズのロボットは、UniValドライブインターフェースを介して使用で...", 
"body" : "制限事項 CODESYS EtherCAT バージョン 4.10.0.0 には、「デバイスから PDO 情報を読み込む」機能に関する既知の問題があり、これにより、正常に動作しなくなる CODESYS SoftMotion Stäubli Support パッケージ。 以前のバージョンまたは新しいバージョンのいずれかを使用してください CODESYS EtherCAT 代わりに。 ザル CODESYS SoftMotion Stäubli Support アドオンにより制御が可能になります Stäubli TS2およびTX2シリーズのロボットは、UniValドライブインターフェースを介して使用できます。 CODESYS SoftMotion 。ロボットは、適切なデバイス記述とキネマティック変換という形でサポートされています 必要条件 コントローラはリアルタイム対応で、 EtherCAT 。 ザル CODESYS SoftMotion パッケージがインストールされます。 A Stäubli CS9 コントローラが利用可能です。 ダウンロードできます CODESYS SoftMotion Stäubli Support から コーデシス・ストア・インターナショナル または コーデシスストア北米 。そこには、製品のデータシートもあります。 " }, 
{ "title" : "ロボットモデル ", 
"url" : "_smstbli_start_page.html#UUID-4cb6a3d0-e63a-1bf9-f7a7-5ecc9915cfe0_section-idm235098272785514", 
"breadcrumbs" : "CODESYS SoftMotion Stäubli Support \/ CODESYS SoftMotion Stäubli Support \/ ロボットモデル ", 
"snippet" : "このアドオンは、次のロボットモデルをサポートします。 ts2_40-S1-D25-L200-ceiling-R4-V8 ts2_40-S1-D25-L200-floor-R4-V7 ts2_40-S1-D25-L400-ceiling-R1-V9 ts2_40-S1-D25-L400-floor-R1-V8 ts2_60-S1-D25-L200-ceiling-R4-V7 ts2_60-S1-D25-L200-floor-R4-V7 ts2_60-S1-D25-L400-ceiling-R1-V8 ts2_60-S1-D25-L400-floor-R1-V8 ts2_80-S1-D25-L20...", 
"body" : "このアドオンは、次のロボットモデルをサポートします。 ts2_40-S1-D25-L200-ceiling-R4-V8 ts2_40-S1-D25-L200-floor-R4-V7 ts2_40-S1-D25-L400-ceiling-R1-V9 ts2_40-S1-D25-L400-floor-R1-V8 ts2_60-S1-D25-L200-ceiling-R4-V7 ts2_60-S1-D25-L200-floor-R4-V7 ts2_60-S1-D25-L400-ceiling-R1-V8 ts2_60-S1-D25-L400-floor-R1-V8 ts2_80-S1-D25-L200-ceiling-R4-V7 ts2_80-S1-D25-L200-floor-R4-V7 ts2_80-S1-D25-L400-ceiling-R1-V8 ts2_80-S1-D25-L400-floor-R1-V8 ts2_100-S1-D25-L200-ceiling-R4-V7 ts2_100-S1-D25-L200-floor-R4-V7 ts2_100-S1-D25-L400-ceiling-R1-V9 ts2_100-S1-D25-L400-floor-R1-V9 tx2_40-S3-R2 tx2_60l-S2-R2 tx2_60-S2-R3 tx2_90l-S2-R4 tx2_90-S2-R3 tx2_90xl-S2-R4-V1 tx2_140-S3-R1 tx2_160l-S3-R1 tx2_160-S3-R1 tx2_200l-S3-R1-V6 tx2_200-S3-R1-V6 " }, 
{ "title" : "使い方 ", 
"url" : "_smstbli_using_roboter.html", 
"breadcrumbs" : "CODESYS SoftMotion Stäubli Support \/ 使い方 ", 
"snippet" : "制限事項 CODESYS EtherCAT バージョン 4.10.0.0 には、「デバイスから PDO 情報を読み込む」機能に関する既知の問題があり、これにより、正常に動作しなくなる CODESYS SoftMotion Stäubli Support パッケージ。 以前のバージョンまたは新しいバージョンのいずれかを使用してください CODESYS EtherCAT 代わりに。 次の説明では、の設定について説明します。 Stäubli のロボット CODESYS Development System 開発環境。 コントローラーを使用して新しい標準プロジェクトを作成します。 お好みの実装言語を選...", 
"body" : "制限事項 CODESYS EtherCAT バージョン 4.10.0.0 には、「デバイスから PDO 情報を読み込む」機能に関する既知の問題があり、これにより、正常に動作しなくなる CODESYS SoftMotion Stäubli Support パッケージ。 以前のバージョンまたは新しいバージョンのいずれかを使用してください CODESYS EtherCAT 代わりに。 次の説明では、の設定について説明します。 Stäubli のロボット CODESYS Development System 開発環境。 コントローラーを使用して新しい標準プロジェクトを作成します。 お好みの実装言語を選択してください。 コントローラーのデバイス説明を選択します。 を追加 EtherCAT ドライブ: デバイスツリーで、のコンテキストメニューを開きます Device ノードを選択し、 [デバイスを追加] コマンド。 ダイアログが開きます。 アンダー フィールドバス → EtherCAT → マスター 、フィールドバスを選択してください。 EtherCAT Master SoftMotion 。をクリックします。 [デバイスを追加] コマンドを使用して選択を確定しますが、ダイアログは開いたままにします。 新しいノード EtherCAT_Master_SoftMotion デバイスツリーに表示されます。 プロジェクトツリーでこのノードをクリックします。 オプションはで変わります [デバイスを追加] ダイアログ。 あなたのものを選択してください Stäubli ロボット。以下にあります フィールドバス → EtherCAT → スレーブ → ストーブリ・ロボティクス 。 [デバイスを追加] 選択を確定し、ダイアログを閉じます。 の下に EtherCAT_Master_SoftMotion ノード (ロボットの別のノード) が作成され、そのドライブ用のノードが増えました。 のエキスパート設定を有効にする EtherCAT ロボットのノード: デバイスツリーの下にある EtherCAT_Master_SoftMotion ノードで、ロボットをダブルクリックします。 エディターが開きます。 を有効にする エキスパート設定 オプションはそこにあります。 詳細については、以下を参照してください。 タブ:EtherCAT スレーブ — 一般 での I\/O が既に設定されていることを確認してください Stäubli CS 9 コントローラ。 I\/O が設定されていない場合は、ロボットのプロダクト ID チェックを無効にする必要があります。 ザル Stäubli CS9 コントローラの製品 ID は、I\/O なしに設定した場合と I\/O を使用して構成した場合とでは異なります。 デバイスツリーの下にある EtherCAT_Master_SoftMotion ノードで、ロボットノードをダブルクリックします。 エディターが開きます。 の中に スタートアップチェック グループ化、無効化 プロダクト ID を確認 オプション。 では次の設定が使用されました ts2_100_S1_D25_L200_ceiling_R4 ロボット。 I\/O がすでに設定されている場合は、他に何もする必要はありません。次のステップに進んでください PDO 構成をプロジェクトに転送します。 の下に EtherCAT_Master_SoftMotion ノードで、ロボットのエディターを開きます。 を開きます エキスパート・プロセス・データ タブをクリックして無効にします PDO コンフィグレーション のオプション ダウンロード グループ。 では次の設定が使用されました ts2_100_S1_D25_L200_ceiling_R4 ロボット。 コントローラにログインし、アプリケーションを起動し、終了するまで待ちます EtherCAT スレッドが起動しました。 次に、をクリックします デバイスから PDO 情報を読み込む ボタン。 ロボットのPDO構成がプロジェクトに適用されます。 コントローラからログアウトします。 を追加 Staubli_Transformation プロジェクトへのライブラリ。 プロジェクトのライブラリマネージャーを開きます。 左上の [] をクリックします。 [ライブラリを追加] ボタン。 ダイアログが開きます。 検索バーに「Staubli_Transformation」というテキストを入力し、見つけたライブラリを追加します。 軸グループを挿入します。 デバイスツリーで、 Application ノードを作成し、コンテキストメニューを開きます。をクリックします。 [オブジェクトを追加] → アクシスグループ コマンド。 ザル [軸グループの追加] ダイアログが開きます。 お好みの名前を入力し、をクリックします [追加] ボタンをクリックして確定します。 軸グループがアプリケーションの下に挿入されます。軸グループコンフィギュレーターが開きます をクリックします キネマティクスを選択 ボタン。 ザル キネマティクスを選択 ダイアログが開き、使用可能なすべてのキネマティック設定とその説明のリストが表示されます。 このリストからロボットのタイプを選択します。 の中に 座標軸へのマッピング パラメータグループ。ステップ 2 で追加したドライブに座標軸をマップします。 のドライブ用 Stäubli ロボットでは、一部の入力フィールドが意図的に非表示になっています。これらはすでに事前設定されています。これらには、たとえば、軸のダイナミックリミットやスケーリングの入力フィールドなどが含まれます " }
]
$(document).trigger('search.ready');
});