$(document).ready(function () {indexDict['en-US'] = [{ "title" : "CODESYS Store ", 
"url" : "_sto_start_page.html", 
"breadcrumbs" : "CODESYS Store \/ CODESYS Store ", 
"snippet" : "CODESYS Store International is an online platform where you can download CODESYS extensions (purchased or free of charge) with support for licensing, installation, and ratings. Extensions include both CODESYS products as well as products from third-party vendors in cooperation with CODESYS GmbH . Su...", 
"body" : "CODESYS Store International is an online platform where you can download CODESYS extensions (purchased or free of charge) with support for licensing, installation, and ratings. Extensions include both CODESYS products as well as products from third-party vendors in cooperation with CODESYS GmbH . Support for third-party products is provided by the third-party vendor. You can open the Store either in a web browser ( https:\/\/store.codesys.com or https:\/\/us.store.codesys.com\/ ) or in the development system by clicking View → Store . The advantage of the latter option is that you can use the Package Manager to install products directly from the Store to your computer. " }, 
{ "title" : "Using the CODESYS Store International ", 
"url" : "_sto_use_store.html", 
"breadcrumbs" : "CODESYS Store \/ Using the CODESYS Store International ", 
"snippet" : "You can open the Store either in a web browser ( https:\/\/store.codesys.com or https:\/\/us.store.codesys.com\/ ) or in the development system by clicking View → Store . The advantage of the latter option is that you can use the Package Manager to install products directly from the Store to your compute...", 
"body" : "You can open the Store either in a web browser ( https:\/\/store.codesys.com or https:\/\/us.store.codesys.com\/ ) or in the development system by clicking View → Store . The advantage of the latter option is that you can use the Package Manager to install products directly from the Store to your computer. For a detailed description of the necessary steps from registration in the Store to installation and product rating, see the following the link to the Store website: New to the CODESYS Store? Get started . Tips for using the integrated Store in the development system: You can save your credentials in the CODESYS options. After purchasing a licensed product, you can decide to download and install immediately to your computer. If so, then the Install Immediately option has to be selected. Note: In order to register licensed products during installation, you need to have already connected the CODESYS Security Key to your computer. If the Install Immediately option is not selected, then you can download and install a product ordered in the Store later. This is done manually by using the Package Manager of the development system. When you order, you receive an email with the purchase confirmation and activate the Download link directly for each product. The Package Manager is started and you are directed to the installation. The licensing information and ticket numbers which are also provided in the email are required for the License Manager to activate or update the product license. You can also perform an explicit download directly from the Store. To do this, use the Download button on the product page. For some products, you have the option of selecting a specific product version if several exist. You can save the package on your local machine or install it directly from the Package Manager. Available updates for products downloaded from the Store are found by clicking a button in the dialog of the Package Manager. " }, 
{ "title" : "WebDepot (Wibu License Portal) ", 
"url" : "_sto_web_depot-html.html", 
"breadcrumbs" : "CODESYS Store \/ WebDepot (Wibu License Portal) ", 
"snippet" : "WebDepot is a web-based application for you as a user to transfer licenses by yourself. This is possible for both a SoftContainer and the CODESYS key. A direct transfer is available either to the local computer or to a CmDongle which is connected locally. Always license your local CodeMeter runtime ...", 
"body" : "WebDepot is a web-based application for you as a user to transfer licenses by yourself. This is possible for both a SoftContainer and the CODESYS key. A direct transfer is available either to the local computer or to a CmDongle which is connected locally. Always license your local CodeMeter runtime via the WebDepot. It is not possible to license a PLC via the WebDepot using SSH, for example. You should use the License Manager for this. By downloading a license file via the WebDepot, you can transfer the license offline to another computer or to another CmDongle. For more information, see: Offline activation . " }, 
{ "title" : "Reference ", 
"url" : "_sto_f_reference.html", 
"breadcrumbs" : "CODESYS Store \/ Reference ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Command: Store ", 
"url" : "_sto_cmd_store.html", 
"breadcrumbs" : "CODESYS Store \/ Reference \/ Command: Store ", 
"snippet" : "Symbol: Function : The command opens the Store view. This view is the start page of the CODESYS Store International . Call : View menu You can also open the CODESYS Store International in a web browser ( http:\/\/store.codesys.com ). For more information, see: Using the...", 
"body" : "Symbol: Function : The command opens the Store view. This view is the start page of the CODESYS Store International . Call : View menu You can also open the CODESYS Store International in a web browser ( http:\/\/store.codesys.com ). For more information, see: Using the " }, 
{ "title" : "Dialog: Options – Store ", 
"url" : "_sto_dlg_options.html", 
"breadcrumbs" : "CODESYS Store \/ Reference \/ Dialog: Options – Store ", 
"snippet" : "Symbol: Function : The dialog is used to save the credentials. The dialog includes a link to the CODESYS Store International where you can create a new user account. Call : Tools → Options command, Store category For more information, see: Using the...", 
"body" : "Symbol: Function : The dialog is used to save the credentials. The dialog includes a link to the CODESYS Store International where you can create a new user account. Call : Tools → Options command, Store category For more information, see: Using the " }
]
$(document).trigger('search.ready');
});