$(document).ready(function () {indexDict['zh-CHS'] = [{ "title" : "CODESYS Installer ", 
"url" : "_inst_start_page.html", 
"breadcrumbs" : "CODESYS Installer \/ CODESYS Installer ", 
"snippet" : "的 CODESYS Installer 管理各种本地安装 CODESYS 部署和更新中的版本和支持。 你可以下载 CODESYS Installer 来自 CODESYS 商店 .您还可以在此处找到产品的数据表。...", 
"body" : "的 CODESYS Installer 管理各种本地安装 CODESYS 部署和更新中的版本和支持。 你可以下载 CODESYS Installer 来自 CODESYS 商店 .您还可以在此处找到产品的数据表。 " }, 
{ "title" : "概述 ", 
"url" : "_inst_what_it_is.html", 
"breadcrumbs" : "CODESYS Installer \/ 概述 ", 
"snippet" : "该工具可帮助您管理软件更新 CODESYS Development System .此外，您可以使用按钮开始运行特殊 CODESYS 安装。 有关现有安装的信息 CODESYS 及其附加组件 安装比较 通知新的更新 期间支持 安装 以及更新设置和附加组件 附加期间的支持 配置 提供按钮 CODESYS 在特殊版本和附加配置中执行 创建和注册沙盒 创建安装配置文件...", 
"body" : "该工具可帮助您管理软件更新 CODESYS Development System .此外，您可以使用按钮开始运行特殊 CODESYS 安装。 有关现有安装的信息 CODESYS 及其附加组件 安装比较 通知新的更新 期间支持 安装 以及更新设置和附加组件 附加期间的支持 配置 提供按钮 CODESYS 在特殊版本和附加配置中执行 创建和注册沙盒 创建安装配置文件 " }, 
{ "title" : "用户界面 ", 
"url" : "_inst_what_it_is.html#UUID-9d4e7ca3-b622-400c-0b39-85288bd83a85_id_b600c10d8445e64c0a8646376a7c4cc_id_ca7cfdb9da147976c0a864634c509226", 
"breadcrumbs" : "CODESYS Installer \/ 概述 \/ 用户界面 ", 
"snippet" : "该工具的起始视图 ( 装置 查看) 在图块视图中提供有关 CODESYS 您的系统上当前可用的安装。 您可以点击 开始 （2）开始一个 CODESYS 每个安装的实例 (1)，然后单击 改变 （3）更改安装配置和管理附加组件。此外，您还可以单击 创建沙盒 来自安装（4）。 使用 按钮（5）获取包含以下命令的菜单： 修复、卸载、启动控制\/网关服务和 HMI 冻结更新请求 为桌面上的安装创建一个链接 要添加新安装，请点击 添加安装 按钮（6）。 点击 旁边是 添加安装 按钮打开菜单，其中包含用于创建和注册 沙箱 。 新安装的默认设置可以在 设置 在 右上角的菜单（7）。 以红色字体启用的按钮会通知...", 
"body" : "该工具的起始视图 ( 装置 查看) 在图块视图中提供有关 CODESYS 您的系统上当前可用的安装。 您可以点击 开始 （2）开始一个 CODESYS 每个安装的实例 (1)，然后单击 改变 （3）更改安装配置和管理附加组件。此外，您还可以单击 创建沙盒 来自安装（4）。 使用 按钮（5）获取包含以下命令的菜单： 修复、卸载、启动控制\/网关服务和 HMI 冻结更新请求 为桌面上的安装创建一个链接 要添加新安装，请点击 添加安装 按钮（6）。 点击 旁边是 添加安装 按钮打开菜单，其中包含用于创建和注册 沙箱 。 新安装的默认设置可以在 设置 在 右上角的菜单（7）。 以红色字体启用的按钮会通知您最近提供的更新。 更新 CODESYS (5) 表示最新的服务包 CODESYS .这 按钮表示一个新的补丁。单击按钮时，安装操作将自动开始。 旁边的红色数字 改变 显示可以更新多少已安装的附加组件。当你点击 改变 ，将打开一个对话框以帮助您管理插件。 点击 图标打开 通知日志 ，其中列出了有关安装程序中操作的最近 20 条通知，包括时间戳。您可以在钟形符号旁边的蓝色圆圈中看到未读消息的 " }, 
{ "title" : "安装和启动 ", 
"url" : "_inst_install_setups_and_addons.html", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 ", 
"snippet" : "您可以访问 CODESYS Installer 从 Windows 开始菜单中的 CODESYS 文件夹。 象征：...", 
"body" : "您可以访问 CODESYS Installer 从 Windows 开始菜单中的 CODESYS 文件夹。 象征： " }, 
{ "title" : "添加安装 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_id_b6eefcd84607dec0a8646316b49624_id_6b88d883ddde1fecc0a86463717cb451", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 添加安装 ", 
"snippet" : "要添加（注册）您收到的沙盒安装，请参阅： 创建和使用沙箱在 Windows 开始菜单中，在 CODESYS 文件夹，单击安装程序图标。 工具启动。风景 装置 出现。 点击 添加安装 按钮。 这个 全新安装 对话框打开。 选择任一项 快递 选项或 手册 选项，然后按照向导进行操作： 快递 ：安装是根据现有的安装配置文件创建的。这个 下一步 按钮打开一个对话框，在文件系统中搜索配置文件 *.installation-config 。上传完成后，安装将包含中描述的配置文件 CODESYS 安装和附加版本。 创建单独的存储库 选项已启用，一个” 全新安装 “已完成。 现在继续执行步骤 7。 手册 ：安...", 
"body" : "要添加（注册）您收到的沙盒安装，请参阅： 创建和使用沙箱在 Windows 开始菜单中，在 CODESYS 文件夹，单击安装程序图标。 工具启动。风景 装置 出现。 点击 添加安装 按钮。 这个 全新安装 对话框打开。 选择任一项 快递 选项或 手册 选项，然后按照向导进行操作： 快递 ：安装是根据现有的安装配置文件创建的。这个 下一步 按钮打开一个对话框，在文件系统中搜索配置文件 *.installation-config 。上传完成后，安装将包含中描述的配置文件 CODESYS 安装和附加版本。 创建单独的存储库 选项已启用，一个” 全新安装 “已完成。 现在继续执行步骤 7。 手册 ：安装是手动配置的。在这种情况下，请继续执行步骤 4。 使用 平台 , 设置 ， 和 版本 列表框以选择所需的安装。 例子： CODESYS 3.5 SP16（64 位）补丁 3 来自 从现有安装 列表框中，选择其附加配置尽可能符合您所需配置的安装。 选择所需的 更新模式 。有关各个模式的更多信息，请参阅以下内容： 设置点击 好的 确认您的设置。 这个 需要确认 对话框打开。如果应按所示进行安装，则单击 好吧 来启动它。下载安装程序，然后启动 InstallShield 向导 执行以下步骤： 接受许可协议。 授予信息的读取权限。 确认位置。 选择安装类型。 关闭 InstallShield 向导。 这 “软件安装”任务完成 消息显示在 CODESYS Installer .最近创建的安装的附加磁贴显示在 安装 看法。 " }, 
{ "title" : "更新安装 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_id_b6eefcd84607dec0a8646316b49624_id_684f2123fdb759f6c0a864633b4a45aa", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 更新安装 ", 
"snippet" : "要求：有更新的补丁可用于安装。然后是一个带有红色加载符号和红色补丁号的按钮（ ) 显示在磁贴中。 单击按钮时，您可以统计更新的安装操作。...", 
"body" : "要求：有更新的补丁可用于安装。然后是一个带有红色加载符号和红色补丁号的按钮（ ) 显示在磁贴中。 单击按钮时，您可以统计更新的安装操作。 " }, 
{ "title" : "删除安装 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_id_b6eefcd84607dec0a8646316b49624_id_eb57bd21fdb759f6c0a86463005d32bf", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 删除安装 ", 
"snippet" : "在平铺视图中，选择要删除的安装，然后在平铺中单击 卸载 按钮 菜单。...", 
"body" : "在平铺视图中，选择要删除的安装，然后在平铺中单击 卸载 按钮 菜单。 " }, 
{ "title" : "开始安装 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_id_b6eefcd84607dec0a8646316b49624_id_36b5954bfdb759f6c0a8646363c8f687", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 开始安装 ", 
"snippet" : "在磁贴视图中，选择要执行的安装，然后在图块中单击 开始 按钮。 CODESYS 以设置中指定的语言启动。 有关更多信息，请参阅： 设置...", 
"body" : "在磁贴视图中，选择要执行的安装，然后在图块中单击 开始 按钮。 CODESYS 以设置中指定的语言启动。 有关更多信息，请参阅： 设置" }, 
{ "title" : "控制提供哪些更新 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_section-idm4575816630556833684401698869", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 控制提供哪些更新 ", 
"snippet" : "通过以下方式添加安装时 添加安装 按钮，您可以指定 更新模式 在里面 新安装 对话。您使用它来决定是否应提供更新类别以及应提供哪种类别的更新 CODESYS Installer .更新模式的默认设置位于 设置 对话。 此外，您可以指定暂时不再为现有安装提供更新。为此，打开 主窗口 安装程序在安装的磁贴中 菜单并选择 冻结 命令。...", 
"body" : "通过以下方式添加安装时 添加安装 按钮，您可以指定 更新模式 在里面 新安装 对话。您使用它来决定是否应提供更新类别以及应提供哪种类别的更新 CODESYS Installer .更新模式的默认设置位于 设置 对话。 此外，您可以指定暂时不再为现有安装提供更新。为此，打开 主窗口 安装程序在安装的磁贴中 菜单并选择 冻结 命令。 " }, 
{ "title" : "管理加载项 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_id_b6eefcd84607dec0a8646316b49624_id_b6a1825b827e11ebb7e98151df535f63", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 管理加载项 ", 
"snippet" : "当有新的附加版本可供安装时，带有更新数量的红色数字将显示在旁边的磁贴中 改变 按钮。该按钮打开安装的配置视图。在那里，您可以获得有关已安装和可用的附加组件和可用更新的更多详细信息。 当有新的附加版本可供安装时，带有更新数量的红色数字将显示在旁边的磁贴中 改变 按钮。该按钮打开安装的配置视图。在那里，您可以获得有关已安装和可用的附加组件和可用更新的更多详细信息。 在磁贴视图中，选择应安装、更新或删除附加组件的安装。 单击磁贴中的按钮 改变 . 安装的配置视图打开。安装名称显示在下方 版本 .您可以更改选择的默认设置 地点 , 设置通道 ， 和 插件频道 . 当前安装的附加组件列在 附加组件 查看...", 
"body" : "当有新的附加版本可供安装时，带有更新数量的红色数字将显示在旁边的磁贴中 改变 按钮。该按钮打开安装的配置视图。在那里，您可以获得有关已安装和可用的附加组件和可用更新的更多详细信息。 当有新的附加版本可供安装时，带有更新数量的红色数字将显示在旁边的磁贴中 改变 按钮。该按钮打开安装的配置视图。在那里，您可以获得有关已安装和可用的附加组件和可用更新的更多详细信息。 在磁贴视图中，选择应安装、更新或删除附加组件的安装。 单击磁贴中的按钮 改变 . 安装的配置视图打开。安装名称显示在下方 版本 .您可以更改选择的默认设置 地点 , 设置通道 ， 和 插件频道 . 当前安装的附加组件列在 附加组件 查看下 已安装 .当您单击其中一个加载项时，相应的说明会显示在右侧。如果列表比视图长，则显示用于滚动的导航符号。 点击 浏览 . 过滤器列出了插件频道上提供的所有尚未安装的插件。 点击 更新 . 过滤器列出了所有具有可用更新的附加组件。 选择一个附加组件。 有关加载项的信息（例如，名称或 所需的安装程序版本 ) 显示在它的右侧。 可用版本列在 版本 列表框。 这 安装 按钮显示在旁边。 在里面 版本 列表框中，选择所需的版本。 点击 安装 按钮并单击 好的 确认有关安装操作的消息。 附加包的安装操作开始。 这 安装包 对话框打开并提供有关许可协议和签名的信息。 选中许可协议和签名信息的复选框。 点击 继续 按钮。 该软件包已下载然后安装。将显示一个进度条。当消息更新已完成 插件安装成功 被展示。 点击 好的 确认这一点。 讯息 任务“插件安装”完成 显示在配置视图中。 " }, 
{ "title" : "安装附加包 ", 
"url" : "_inst_install_setups_and_addons.html#UUID-b8ba0e18-c9a8-56ce-2932-c4981f2cbc49_id_b6eefcd84607dec0a8646316b49624_id_1ca30162223d47b0c0a864637f9545c0", 
"breadcrumbs" : "CODESYS Installer \/ 安装和启动 \/ 安装附加包 ", 
"snippet" : "您可以安装已保存在文件系统中的软件包。 在平铺视图中，选择应为其安装附加组件的安装。 在磁贴中，单击 改变 按钮。 安装的配置视图打开。 点击 安装文件 按钮。 文件选择对话框打开。 选择所需的包。 安装操作开始。 这 安装包 对话框打开并提供有关许可协议和签名的信息。 选中许可协议和签名信息的复选框。 点击 继续 按钮。 包被加载然后安装。将显示一个进度条。当消息更新已完成 插件安装成功 被展示。 点击 好的 确认这一点。 讯息 任务“包安装”完成 显示在配置视图中。最近安装的软件包列在 已安装 筛选。...", 
"body" : "您可以安装已保存在文件系统中的软件包。 在平铺视图中，选择应为其安装附加组件的安装。 在磁贴中，单击 改变 按钮。 安装的配置视图打开。 点击 安装文件 按钮。 文件选择对话框打开。 选择所需的包。 安装操作开始。 这 安装包 对话框打开并提供有关许可协议和签名的信息。 选中许可协议和签名信息的复选框。 点击 继续 按钮。 包被加载然后安装。将显示一个进度条。当消息更新已完成 插件安装成功 被展示。 点击 好的 确认这一点。 讯息 任务“包安装”完成 显示在配置视图中。最近安装的软件包列在 已安装 筛选。 " }, 
{ "title" : "创建和使用沙箱 ", 
"url" : "_inst_create_sandbox.html", 
"breadcrumbs" : "CODESYS Installer \/ 创建和使用沙箱 ", 
"snippet" : "什么是 CODESYS 沙盒？ 一个 CODESYS -Sandbox 是一个独立的实例 CODESYS 这不会改变或影响它运行的环境\/机器。属于此实例的所有内容，所有设置和存储库，都位于计算机上沙箱的定义的 “根目录” 中。通过移动\/复制此根目录，可以简单地将沙箱移动到新计算机上并在那里用作安装。无需重新安装。 沙箱对以下方面很有用 CODESYS --“冻结” 并存档已完成项目的环境，这样以后可以轻松地再次对项目进行更改。由于沙箱中的版本不会更改，因此始终可以在不进行在线更改的情况下登录 当多个开发人员需要继续开发同一个项目时，使用沙箱也很有用。使用的版本 ( CODESYS 和软件包）在...", 
"body" : "什么是 CODESYS 沙盒？ 一个 CODESYS -Sandbox 是一个独立的实例 CODESYS 这不会改变或影响它运行的环境\/机器。属于此实例的所有内容，所有设置和存储库，都位于计算机上沙箱的定义的 “根目录” 中。通过移动\/复制此根目录，可以简单地将沙箱移动到新计算机上并在那里用作安装。无需重新安装。 沙箱对以下方面很有用 CODESYS --“冻结” 并存档已完成项目的环境，这样以后可以轻松地再次对项目进行更改。由于沙箱中的版本不会更改，因此始终可以在不进行在线更改的情况下登录 当多个开发人员需要继续开发同一个项目时，使用沙箱也很有用。使用的版本 ( CODESYS 和软件包）在这种情况下，必须在项目开始时定义。然后可以创建沙箱并将其分发给开发人员 沙箱的缺点包括所需的额外存储空间和管理开销。 什么是 “干净” 的沙箱？ 干净的沙箱仅包含与之配套的设备\/库\/样式的版本 CODESYS -用作沙盒起源的版本适合。另一方面，“简单” 沙箱在大多数情况下已经包含同一设备\/库的多个版本，因为它们也位于 CODESYS -版本已经包括在内。为了防止这种版本混用，你可以 CODESYS Installer 这个函数 通过安装程序创建一个干净的沙箱 使用。 “干净的沙箱” 只能通过以下方式实现 CODESYS -版本 >= SP19 补丁 6 已创建。 一个 CODESYS -沙盒无法升级到更新的补丁版本。 先决条件 和 网关设置 要运行沙箱，沙箱目录中必须有一些文件形式的 “先决条件”，因为 CODESYS 否则无法启动。这些文件是在创建沙箱时创建的。还有的设置 CODESYS 网关存储在沙箱目录中。就在那一刻 CODESYS 网关和 “先决条件” 安装在计算机上，它们可以在任何沙箱中相同 CODESYS 计算机上使用的版本。 从现有沙箱中创建沙箱 CODESYS -在本地计算机上安装 是的 CODESYS 不完全支持长文件系统路径，请为沙箱根目录使用尽可能短的路径。 打开视图 装置 的 CODESYS Installer 。 要为现有安装创建沙箱，请选择此安装文件中的命令 创建沙箱 。注意：在这种情况下，不会创建 “干净的沙箱”。你只有在命令的帮助下才能得到一个干净的沙箱 从设置中创建干净的沙盒。 用于在本地文件系统中为沙箱选择根目录的对话框打开。 选择根目录。尽量缩短路径。 创建沙箱时，安装程序会为文件做贡献 RepositoryLocations.ini 自动设置相对路径，这样当您在另一台计算机上注册沙箱时，不再需要调整这些路径。 但是，如果出现以下情况，则不适用 CODESYS 安装版本早于 3.5.20.30 版，安装程序包括以下附加版本之一： CODESYS Visualization 早于 4.6.0.0 CODESYS SoftMotion 早于 4.17.0.0 CODESYS PROFINET 早于 4.6.0.0 CODESYS J1939 Manager SL 早于 4.2.0.0 CODESYS CANopen Manager SL 早于 4.3.0.0 CODESYS Communication 早于 4.5.2.0 在这种情况下，您将收到相应的消息 确认选择后，沙箱的创建将立即开始。将打开一个消息框，其中显示生成过程和取消选项 如果出现安装不支持相对路径的警告，请参阅上面的注释，必须使用文件中的路径 RepositoryLocations.ini 调整。参见上面的注释。 沙箱完成后，您将收到一条消息，提示对沙箱的访问不受限制，并且必须确保只有经过授权的人员才能访问沙箱目录。 沙箱显示为另一个图块，采用颜色编码，并带有图标 在视野中 装置 。 关于按钮 复制沙箱 现在，您可以复制沙箱根目录以进行再分发，并将其存储在文件系统中 在本地计算机上注册来自其他来源的沙箱 您可以注册沙箱中的安装。这将用作计算机上的进一步安装，并附上磁贴 CODESYS Installer 已添加。 打开视图 装置 的 CODESYS Installer 。 从下拉菜单中选择 命令按钮 添加安装 这个命令 注册沙盒 。 对话 注册沙盒 打开。 输入本地文件系统上应用作沙箱根目录的目录。 如果沙箱中尚未提供网关服务，请决定是否还应下载并安装这些服务。注意：如果网关的服务相同 CODESYS 沙箱中已经存在的版本，也可以由待注册的新沙箱使用。 在报告潜在安全风险之前，请激活该复选框。只有这样，您才能注册 好吧 完成。 如果已经进行了网关安装，您将首先收到一个对话框，您必须在其中进行确认。然后将沙箱视为图块 装置 已添加。 管理沙箱 在... 的设置中 CODESYS Installer 您还可以管理沙箱安装。您可以查看当前注册了哪些沙箱，可以进行新的注册，也可以将沙盒目录排除在可能的注册范围之外 打开视图 装置 的 CODESYS Installer 。 在安装程序窗口中，从菜单中选择 在右上角，命令 设置 。 对话 设置 打开。 选择 沙箱 。 沙箱下的部分显示了哪些沙箱当前已在计算机上注册，哪些不包括在内。 如果您在安全通知中确认该选项，则可以使用该按钮注册更多沙箱。 在下面 排除的沙箱目录 您可以输入不应在安装程序中显示的根目录。如果在添加沙箱时指定了父目录，但您不想看到该目录中的所有沙箱，则此功能可能很有用 " }, 
{ "title" : "比较安装 ", 
"url" : "inst_compare_installations.html", 
"breadcrumbs" : "CODESYS Installer \/ 比较安装 ", 
"snippet" : "要比较两个安装的内容，请转到 装置 观点。 添加安装 按钮，单击 选择菜单，然后选择 比较安装情况 命令。您可以选择要比较的安装并比较检测到的插件版本。 有关更多信息，请参阅以下内容： 命令：比较安装情况...", 
"body" : "要比较两个安装的内容，请转到 装置 观点。 添加安装 按钮，单击 选择菜单，然后选择 比较安装情况 命令。您可以选择要比较的安装并比较检测到的插件版本。 有关更多信息，请参阅以下内容： 命令：比较安装情况" }, 
{ "title" : "创建或编辑安装配置文件 ", 
"url" : "inst_create_setup_configuration_file.html", 
"breadcrumbs" : "CODESYS Installer \/ 创建或编辑安装配置文件 ", 
"snippet" : "你可以创建一个 CODESYS 在安装配置文件中安装。该文件采用文本格式，文件扩展名为 .installation-config 。文件条目描述了应用的 CODESYS 版本和随附的附加版本。 要创建或修改安装配置文件，请选择 创建安装配置文件 命令并跟随向导。你可以在主窗口中使用该命令 CODESYS Installer 在 下方的菜单 装置 或者在现有安装的磁贴中，在下方的菜单中 按钮。 有关步骤的描述 创建安装配置文件 向导，请参见以下内容： 命令：创建安装配置文件什么时候 修改 现有安装，您也可以使用 导出配置 命令创建安装配置文件或使用 导入配置 命令从文件系统加载现有文件。...", 
"body" : "你可以创建一个 CODESYS 在安装配置文件中安装。该文件采用文本格式，文件扩展名为 .installation-config 。文件条目描述了应用的 CODESYS 版本和随附的附加版本。 要创建或修改安装配置文件，请选择 创建安装配置文件 命令并跟随向导。你可以在主窗口中使用该命令 CODESYS Installer 在 下方的菜单 装置 或者在现有安装的磁贴中，在下方的菜单中 按钮。 有关步骤的描述 创建安装配置文件 向导，请参见以下内容： 命令：创建安装配置文件什么时候 修改 现有安装，您也可以使用 导出配置 命令创建安装配置文件或使用 导入配置 命令从文件系统加载现有文件。 " }, 
{ "title" : "参考 ", 
"url" : "_inst_f_reference.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "观点 ", 
"url" : "_inst_f_reference_views.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 观点 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "查看：设置 ", 
"url" : "_inst_view_settings.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 观点 \/ 查看：设置 ", 
"snippet" : "设置 函数 : 定义新安装的默认设置 称呼 ： 主窗口中的菜单 CODESYS Installer 默认存储库 设置通道 \/ 附加组件频道 附加组件的服务渠道（新安装的默认设置） [无] : 没有连接 如果您不希望收到有关新插件版本的任何通知，则可以取消与附加组件门户的连接。您不会收到有关新版本的通知。例如，您可以冻结插件的版本状态，而不会出现不必要的更新提醒。 发行 ：已发布的插件可在此频道上找到。 售前赛 ：此频道提供预发布版本的附加组件。选择此频道在预发行版中进行实验性使用 更新模式 要提供的更新类型的过滤器： 全部 无 代码相同的安全相关 : 仅使用不会导致代码更改的安全相关内容进行更...", 
"body" : "设置 函数 : 定义新安装的默认设置 称呼 ： 主窗口中的菜单 CODESYS Installer 默认存储库 设置通道 \/ 附加组件频道 附加组件的服务渠道（新安装的默认设置） [无] : 没有连接 如果您不希望收到有关新插件版本的任何通知，则可以取消与附加组件门户的连接。您不会收到有关新版本的通知。例如，您可以冻结插件的版本状态，而不会出现不必要的更新提醒。 发行 ：已发布的插件可在此频道上找到。 售前赛 ：此频道提供预发布版本的附加组件。选择此频道在预发行版中进行实验性使用 更新模式 要提供的更新类型的过滤器： 全部 无 代码相同的安全相关 : 仅使用不会导致代码更改的安全相关内容进行更新。 与安全相关 ：所有包含安全相关内容的更新。也会导致代码更改的更新由带有感叹号的黄色三角形表示 代码相同更新 : 仅限不会导致代码更改的更新。 服务 默认网关服务 列出所有当前安装的网关服务 您可以选择要在 Windows 任务栏的信息区域中显示的网关服务。 控制 Win 服务 列出所有当前安装的 Control Win 服务 你可以选择在 Windows 任务栏信息区域显示的 Control Win 服务。 自动更新 新安装后自动检查更新 ：全新安装后，系统会自动检查更新。 代理 代理地址 代理服务器的地址 使用系统代理 ：使用Windows系统代理服务器。 国际 语言 为用户界面选择语言 CODESYS Installer 。更改只有在重启后才会生效。 当你开始的时候 CODESYS 通过 CODESYS Installer ， CODESYS 使用此处设置的语言打开。 当你开始的时候 CODESYS 通过桌面上的快捷方式，在桌面上设置的语言 CODESYS 使用选项。 沙箱 沙箱目录 计算机上沙箱根目录的路径。 点击 打开在本地文件系统中搜索的对话框。 和 ，您可以从列表中删除已进入的沙盒。 更多信息请参阅： 创建和使用沙箱我明白... 潜在的安全风险 ：点击后 按钮，您可以在文件系统中搜索沙盒目录并将沙盒添加到列表中。然后，此沙盒即可使用，就像 注册沙箱 命令，用于在计算机上安装。 排除的沙箱目录 点击 按钮，您可以选择本地文件系统中的沙盒根目录并在此处输入。排除的沙盒不会显示在安装程序中。 您可以为现有安装单独自定义频道。要执行此操作，请单击 改变 相应图块中的按钮。 " }, 
{ "title" : "视图：安装 ", 
"url" : "_inst_view_installations.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 观点 \/ 视图：安装 ", 
"snippet" : "安装...", 
"body" : "安装 " }, 
{ "title" : "CODESYS Installer ", 
"url" : "_inst_view_installations.html#UUID-8fb4991a-b55d-831f-0485-e10646b9365f_id_de387b7ddd1d34bc0a86463377e6be2_id_d77f64a1167085c8c0a864632e982e60", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 观点 \/ 视图：安装 \/ CODESYS Installer ", 
"snippet" : "功能 ：该视图提供有关安装的信息 CODESYS Development System 它们在您的系统上可用，并有助于安装和更新。 挂号的 沙箱 装置也以图块形式显示。它们以颜色突出显示，并标有 图标。 称呼 ： 主窗口中的菜单 CODESYS Installer 按钮 更新 CODESYS 表示一个新的服务包 CODESYS 可用 点击按钮时，最新版的安装操作 CODESYS 自动开始。 按钮 添加安装 打开 全新安装 对话 ：选择菜单 添加安装 按钮 打开包含以下命令的菜单： 注册沙箱 从设置中创建干净的沙盒 创建安装配置文件 比较安装情况 安装的平铺视图 安装名称 CODESYS <se...", 
"body" : "功能 ：该视图提供有关安装的信息 CODESYS Development System 它们在您的系统上可用，并有助于安装和更新。 挂号的 沙箱 装置也以图块形式显示。它们以颜色突出显示，并标有 图标。 称呼 ： 主窗口中的菜单 CODESYS Installer 按钮 更新 CODESYS 表示一个新的服务包 CODESYS 可用 点击按钮时，最新版的安装操作 CODESYS 自动开始。 按钮 添加安装 打开 全新安装 对话 ：选择菜单 添加安装 按钮 打开包含以下命令的菜单： 注册沙箱 从设置中创建干净的沙盒 创建安装配置文件 比较安装情况 安装的平铺视图 安装名称 CODESYS <service pack> ( <platform> ) 提供有关为哪个处理器体系结构安装哪个服务包的信息 例子： CODESYS 3.5 SP17（64 位） 已安装补丁数 提供有关安装了哪个补丁的信息 例子： Patch 3 带有红色数字补丁的按钮 提供有关可用的新补丁的信息 例子： 当您点击按钮时，您可以统计安装操作。 按钮 开始 开始执行这个 CODESYS 安装 按钮 改变 打开此安装的附加组件的配置视图 在那里，您可以管理位置、设置和附加组件的通道以及附加配置。 按钮： 创建沙盒 打开对话框，选择本地文件系统中的目录，该目录将用作新 沙箱 。一旦确认选择，沙盒创建将自动开始，并且 创建沙盒 对话框打开。您可以在框中看到创建进度。 取消 是可能的。注意：该命令不会创建“干净的沙盒”。 按钮： 重复沙盒 仅适用于沙盒瓷砖 打开对话框以选择本地文件系统中应存储沙箱副本的目录。 按钮： 维修 ：启动 InstallShield Wizard 以重新安装 卸载 ：启动 InstallShield Wizard 进行卸载 创建桌面快捷方式 ：在计算机桌面上创建一个快捷方式，用于快速访问已安装的产品。 设置控制服务 ：启动控制服务并将其添加到自动启动中。 设置网关服务 ：启动网关并将其添加到自动启动中。 启动 HMI : 启动可用的 CODESYS HMI 。 冻结 \/ 解冻 ：不再为安装提供更新。冻结安装由蓝色“冻结”标签表示。 Packages Download : Opens the dialog for specifying a directory in the local file system. When the directory is selected, the download of the package files starts <add-on> <version> .package for all add-ons included in the installation. 浏览 : 打开文件资源管理器，其目录为 CODESYS 安装。 比较安装情况 ：启动向导以比较两个安装。有关更多信息，请参阅以下内容： 比较安装创建安装配置文件 ：启动向导，为<name>安装程序创建文本配置文件 “.installation-config”。它可以自定义。有关更多信息，请参阅以下内容： 创建或编辑安装配置文件" }, 
{ "title" : "命令 ", 
"url" : "_inst_f_reference_commands.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "命令：改变 ", 
"url" : "_inst_cmd_change.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：改变 ", 
"snippet" : "改变 函数 ：该命令使用安装的特定设置打开视图。 打电话 : 装置 观点。每个安装都有自己的 改变 命令在那里。...", 
"body" : "改变 函数 ：该命令使用安装的特定设置打开视图。 打电话 : 装置 观点。每个安装都有自己的 改变 命令在那里。 " }, 
{ "title" : "安装的特殊设置 ", 
"url" : "_inst_cmd_change.html#UUID-77f33790-26ed-2cea-e612-76cf7c385fee_id_a7993c0a864632fa1ad58_id_436afb9c80c111ebaba48bede1cc8ce2", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：改变 \/ 安装的特殊设置 ", 
"snippet" : "版本 包含版本号和平台信息的安装名称 地点 安装位置 你可以在资源管理器中打开该位置。点击 浏览 去做这个。 设置通道 设置服务通道 [没有] 无连接 如果你不想收到任何关于新品的通知 CODESYS 版本，则可以取消与安装门户的连接。您不会收到有关新版本的通知，因此，例如，您可以保持安装版本状态不变，而不会出现任何不必要的更新提醒 发布 此频道提供已发布的版本。 预发行 此频道提供预发布版本。 选择此频道用于预发布版本的实验性使用。 插件频道 插件服务渠道 [没有] 无连接 如果您不希望收到有关新插件版本的任何通知，则可以取消与附加组件门户的连接。你不会收到有关新版本的通知，因此，例如，你可...", 
"body" : "版本 包含版本号和平台信息的安装名称 地点 安装位置 你可以在资源管理器中打开该位置。点击 浏览 去做这个。 设置通道 设置服务通道 [没有] 无连接 如果你不想收到任何关于新品的通知 CODESYS 版本，则可以取消与安装门户的连接。您不会收到有关新版本的通知，因此，例如，您可以保持安装版本状态不变，而不会出现任何不必要的更新提醒 发布 此频道提供已发布的版本。 预发行 此频道提供预发布版本。 选择此频道用于预发布版本的实验性使用。 插件频道 插件服务渠道 [没有] 无连接 如果您不希望收到有关新插件版本的任何通知，则可以取消与附加组件门户的连接。你不会收到有关新版本的通知，因此，例如，你可以保持插件的版本状态不变，而不会有任何刺激性的更新 发布 此频道上提供已发布的附加组件。 预发行 此频道提供预发布版本的附加组件。 选择此频道以用于预发布版本的实验性用途。 更新模式 定义应提供哪些更新类别。有关此的更多信息，请参阅： 设置" }, 
{ "title" : "附加组件 ", 
"url" : "_inst_cmd_change.html#UUID-77f33790-26ed-2cea-e612-76cf7c385fee_id_a7993c0a864632fa1ad58_id_ed137dc08677ccfcc0a8646377f9bf87", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：改变 \/ 附加组件 ", 
"snippet" : "<Search> 搜索词的输入字段。插件列表会相应地过滤。 打开一个包含类别的列表框（例如 示例 ) ：仅显示该类别中的插件。 ：该类别中的插件处于隐藏状态。 已安装 列出所有当前安装的附加组件 您可以选择一个加载项，然后选择描述和 卸载 命令显示在右侧。 卸载 命令 卸载在 已安装 列表。 浏览 列出尚未安装的所有可用和兼容的附加组件 您可以选择一个附加组件，然后选择描述和 安装 命令显示在右侧。 更新 列出所有当前安装的至少有一个更新可用的附加组件。 您可以选择一个附加组件，然后选择描述和 安装 命令显示在右侧。 安装 命令 安装在 浏览 列出或 更新 列表。 安装文件 打开一个文件选择器...", 
"body" : "<Search> 搜索词的输入字段。插件列表会相应地过滤。 打开一个包含类别的列表框（例如 示例 ) ：仅显示该类别中的插件。 ：该类别中的插件处于隐藏状态。 已安装 列出所有当前安装的附加组件 您可以选择一个加载项，然后选择描述和 卸载 命令显示在右侧。 卸载 命令 卸载在 已安装 列表。 浏览 列出尚未安装的所有可用和兼容的附加组件 您可以选择一个附加组件，然后选择描述和 安装 命令显示在右侧。 更新 列出所有当前安装的至少有一个更新可用的附加组件。 您可以选择一个附加组件，然后选择描述和 安装 命令显示在右侧。 安装 命令 安装在 浏览 列出或 更新 列表。 安装文件 打开一个文件选择器对话框，以便您可以选择一个包 当您确认对话框时，程序包的安装开始。确认许可协议和签名信息。在安装过程中，您可以通知进度。安装完成时出现提示信息 任务“包安装”完成 被展示。 导出配置 打开文件选择器对话框，以便您可以创建和保存安装配置文件。该文件包含有关此对话框所有设置的信息。 或者，也可以使用向导显式编译安装配置文件。看这里： 创建或编辑安装配置文件。 导入配置 打开文件选择器对话框，以便您可以选择先前存储的安装配置文件。该文件包含用于在对话框中预设所有其他设置的信息。 " }, 
{ "title" : "命令：添加安装 ", 
"url" : "_inst_cmd_add_installation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：添加安装 ", 
"snippet" : "添加安装 函数 ：该命令配置并开始安装自包含的 CODESYS 版本包括您选择的插件。这个 全新安装 对话框为此打开。您可以在现有配置文件中的快速安装和手动配置的安装之间进行选择。 打电话 : 按钮输入 装置 查看和 设置 观点 安装不会相互影响。 有关安装说明，请参阅以下内容： 安装和启动全新安装 对话 快递 快递 ：安装是根据现有的安装配置文件创建的。 这个 下一步 按钮打开一个对话框，在文件系统中搜索配置文件 *.installation-config 。上传完成后，安装将包含中描述的配置文件 CODESYS 安装和附加版本。 创建单独的存储库 选项已启用，一个” 全新安装 “已完成。 ...", 
"body" : "添加安装 函数 ：该命令配置并开始安装自包含的 CODESYS 版本包括您选择的插件。这个 全新安装 对话框为此打开。您可以在现有配置文件中的快速安装和手动配置的安装之间进行选择。 打电话 : 按钮输入 装置 查看和 设置 观点 安装不会相互影响。 有关安装说明，请参阅以下内容： 安装和启动全新安装 对话 快递 快递 ：安装是根据现有的安装配置文件创建的。 这个 下一步 按钮打开一个对话框，在文件系统中搜索配置文件 *.installation-config 。上传完成后，安装将包含中描述的配置文件 CODESYS 安装和附加版本。 创建单独的存储库 选项已启用，一个” 全新安装 “已完成。 手册 您可以手动配置安装。点击后 下一步 按钮，配置对话框打开。您可以在此处选择如下所述的安装参数： 平台 处理器架构 x64 ：64位架构 x86 ：32位架构 设置 可用于所选平台的服务包列表 例子： CODESYS V3.5 SP17（64 位） 版本 可用于所选平台和所选设置的补丁列表 CODESYS V3.5 SP17（64 位）补丁 2 总功能的很大一部分 CODESYS 由附加组件提供。附加组件可以单独组合，可以相互依赖，并且有自己的版本周期。 导入插件 更新模式 有关更多信息，请参阅以下内容： 设置从现有安装 打开一个列表框，其中包含系统上存在的安装。您可以选择一个安装来读取其附加配置。 取消 拒绝设置并关闭对话框 好的 打开对话框 需要确认 。如果要按配置进行安装，请单击 好吧 确认。 安装程序调用安装向导。在这里，您可以确认许可协议和阅读信息。选择目标文件夹和安装类型。安装已开始。 " }, 
{ "title" : "命令：注册沙箱 ", 
"url" : "_inst_cmd_register_sandbox.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：注册沙箱 ", 
"snippet" : "注册沙盒 图标： 函数 : 打开对话框 注册沙盒 。在其中，你可以创建一个名为 “clean” 的安装 沙箱 可在计算机的目录中找到，将其添加到可用安装列表中。 申诉 : 选择菜单 按钮 添加安装 在视野中 装置 。 对话框 注册沙盒 目录 本地文件系统中沙箱根目录路径的输入字段。 关于按钮 搜索文件系统的对话框打开。 安装网关服务（需要时下载） ：创建沙箱时，必要的 “先决条件” 也会复制到沙箱中（目前是 2 个文件）。当您注册时，这些文件将启动。如果这两个文件仍然缺失，您将使用此选项明确下载它们。 我知道附上来自未知来源的沙箱会带来潜在的安全风险 。 只有激活此选项后才能完成注册。...", 
"body" : "注册沙盒 图标： 函数 : 打开对话框 注册沙盒 。在其中，你可以创建一个名为 “clean” 的安装 沙箱 可在计算机的目录中找到，将其添加到可用安装列表中。 申诉 : 选择菜单 按钮 添加安装 在视野中 装置 。 对话框 注册沙盒 目录 本地文件系统中沙箱根目录路径的输入字段。 关于按钮 搜索文件系统的对话框打开。 安装网关服务（需要时下载） ：创建沙箱时，必要的 “先决条件” 也会复制到沙箱中（目前是 2 个文件）。当您注册时，这些文件将启动。如果这两个文件仍然缺失，您将使用此选项明确下载它们。 我知道附上来自未知来源的沙箱会带来潜在的安全风险 。 只有激活此选项后才能完成注册。 " }, 
{ "title" : "命令：从设置中创建干净的沙盒 ", 
"url" : "_inst_cmd_create_clean_sandbox_from_setup.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：从设置中创建干净的沙盒 ", 
"snippet" : "从设置中创建干净的沙盒 象征： 功能 ：该命令打开 从设置中创建干净的沙盒 对话框。您可以配置哪些安装（可用安装）应存储为干净的 沙箱 在本地沙盒根目录中。干净的沙盒仅包含所用组件（设备、库、样式等）的精确匹配版本。 称呼 ： 列表框 添加安装 按钮 安装 看法 对话： 从设置中创建干净的沙盒 平台 列表框（x86、x64） 设置通道 包含可用设置的可能通道的列表框（ 发行 ， 预发布版 ） 设置 包含现有安装（设置）的列表框 版本 包含上面所选安装版本的列表框 沙箱目录 按钮 按钮打开对话框以在本地文件系统中搜索。在此选择要创建的沙箱的根目录。 沙箱名称 要创建的沙箱名称的输入字段 导入附加...", 
"body" : "从设置中创建干净的沙盒 象征： 功能 ：该命令打开 从设置中创建干净的沙盒 对话框。您可以配置哪些安装（可用安装）应存储为干净的 沙箱 在本地沙盒根目录中。干净的沙盒仅包含所用组件（设备、库、样式等）的精确匹配版本。 称呼 ： 列表框 添加安装 按钮 安装 看法 对话： 从设置中创建干净的沙盒 平台 列表框（x86、x64） 设置通道 包含可用设置的可能通道的列表框（ 发行 ， 预发布版 ） 设置 包含现有安装（设置）的列表框 版本 包含上面所选安装版本的列表框 沙箱目录 按钮 按钮打开对话框以在本地文件系统中搜索。在此选择要创建的沙箱的根目录。 沙箱名称 要创建的沙箱名称的输入字段 导入附加组件 应为沙盒导入哪些附加组件的配置选项 " }, 
{ "title" : "命令：比较安装情况 ", 
"url" : "inst_cmd_compare_installations.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：比较安装情况 ", 
"snippet" : "函数 : 该命令会打开 比较安装情况 对话框。在这里，您可以选择两个安装来比较它们包含的附加版本。然后，将在所选安装的下方列出检测到的插件及其版本并进行比较。 打电话 : 的列表框 添加安装 中的按钮 装置 观点。 对话框 : 比较安装情况 比较的两个安装的列表框。除了直接选择列出的安装之外，您还可以使用 按钮以在本地文件系统中选择安装配置文件。 “左侧安装”-“右侧安装” 的比较结果显示在所选安装的下方。已找到的插件之间的以下差异以颜色突出显示： 绿色：仅在左侧安装中 蓝色：仅在正确的安装中 黑色：安装在两个装置中 红色：安装在不同的版本中...", 
"body" : "函数 : 该命令会打开 比较安装情况 对话框。在这里，您可以选择两个安装来比较它们包含的附加版本。然后，将在所选安装的下方列出检测到的插件及其版本并进行比较。 打电话 : 的列表框 添加安装 中的按钮 装置 观点。 对话框 : 比较安装情况 比较的两个安装的列表框。除了直接选择列出的安装之外，您还可以使用 按钮以在本地文件系统中选择安装配置文件。 “左侧安装”-“右侧安装” 的比较结果显示在所选安装的下方。已找到的插件之间的以下差异以颜色突出显示： 绿色：仅在左侧安装中 蓝色：仅在正确的安装中 黑色：安装在两个装置中 红色：安装在不同的版本中 " }, 
{ "title" : "命令：创建安装配置文件 ", 
"url" : "inst_cmd_create_setup_configuration_file.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令 \/ 命令：创建安装配置文件 ", 
"snippet" : "函数 : 该命令会打开 创建安装配置文件 巫师。该向导用于 创建或编辑 iSetup 安装配置文件 。 配置文件是扩展名的文本文件 *.installation-config 。它定义了特定版本中可用的附加版本 CODESYS 安装。如果需要在中选择安装 CODESYS Installer ，则也可以从文件系统加载安装配置文件，作为直接在安装程序中选择的替代方案。 打电话 : 案例 1：应为新设置创建配置文件： 装置 菜单， 添加安装 视图， 按钮，选择菜单 案例 2：应为现有设置或安装创建配置文件： 在现有安装的磁贴中，菜单下方 按钮。 还使用创建了安装配置文件 导出配置 该命令在您修改现有...", 
"body" : "函数 : 该命令会打开 创建安装配置文件 巫师。该向导用于 创建或编辑 iSetup 安装配置文件 。 配置文件是扩展名的文本文件 *.installation-config 。它定义了特定版本中可用的附加版本 CODESYS 安装。如果需要在中选择安装 CODESYS Installer ，则也可以从文件系统加载安装配置文件，作为直接在安装程序中选择的替代方案。 打电话 : 案例 1：应为新设置创建配置文件： 装置 菜单， 添加安装 视图， 按钮，选择菜单 案例 2：应为现有设置或安装创建配置文件： 在现有安装的磁贴中，菜单下方 按钮。 还使用创建了安装配置文件 导出配置 该命令在您修改现有安装时可用。有关更多信息，请参阅以下内容： 改变。 巫师 创建安装配置文件 : 对话框： 配置您的设置 ：在这里，您可以选择要为其创建配置文件的设置（安装）。定义底层股份 CODESYS 包含以下信息 平台 ， 设置 ，以及 版本 ，也可以从文件系统导入现有的配置文件。为此，请使用 从文件加载 按钮。 当您直接从现有安装图块调用向导时，将省略此步骤。 对话框： 配置您的插件 ：在这里，您可以选择应包含在中的附加版本 CODESYS 设置。所有可用的插件及其相应版本都显示在左侧窗口中。随着 按钮，您可以按类别对选择列表进行排序（例如 Example 或者 Security ）。在旁边的搜索字段中 符号，您可以使用字符串按插件名称进行过滤。这个 按钮用于按字母顺序对列表进行排序。 当前选择的附加版本显示在 预览 窗口。 在任何时候，你可以使用 解析参考文献 按钮以检查此选择是否满足插件安装之间的所有现有依赖关系。当您单击 下一步 按钮。如果依赖关系未得到满足，则您将获得详细信息，并且可以相应地修改选择。 对话框： 需要确认 将显示安装程序的当前配置，您可以通过以下方式进行确认 创建 按钮。对话框打开，用于保存新的安装配置文件 *.installation-config 在本地文件系统中。您可以保存该文件并将其加载回到 CODESYS Installer 稍后在需要选择设置的时候。 " }, 
{ "title" : "命令行界面 ", 
"url" : "_inst_commandline_interface.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "CLI 命令 ", 
"url" : "_inst_cli_commands.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 ", 
"snippet" : "这个 CODESYS Installer 具有命令行界面，可以在其中执行各种命令及其选项。该接口与 CODESYS Installer 包。 语法： APInstaller.CLI <command> <option1> <option2> ......", 
"body" : "这个 CODESYS Installer 具有命令行界面，可以在其中执行各种命令及其选项。该接口与 CODESYS Installer 包。 语法： APInstaller.CLI <command> <option1> <option2> ... " }, 
{ "title" : "命令：--addSandbox ", 
"url" : "_inst_cli_cmd_addsandbox.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--addSandbox ", 
"snippet" : "--addSandbox 函数 ：该命令在设置中添加了一个沙箱。 打电话 : APInstaller.CLI 选项 --targetDirectory <string> 必填项 沙箱所在的目录 也可以指定更高级别的目录。在这种情况下，然后在父目录中搜索沙箱...", 
"body" : "--addSandbox 函数 ：该命令在设置中添加了一个沙箱。 打电话 : APInstaller.CLI 选项 --targetDirectory <string> 必填项 沙箱所在的目录 也可以指定更高级别的目录。在这种情况下，然后在父目录中搜索沙箱 " }, 
{ "title" : "命令：--canCreateInstall ", 
"url" : "_inst_cli_cmd_cancreateinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--canCreateInstall ", 
"snippet" : "--canCreateInstallation 函数 ：该命令检查是否可以使用指定版本创建安装。 打电话 : APInstaller.CLI 选项 --version <version> 必填项 Setup version in the format \"<product> 64 3.5.18.1\" or \"<product> 3.5.18.1\" (for 32 bit) Product ID string which can be parsed by the assigned installation vendor. Example: \"CODESYS 64 3.5.18.1\" 或者 \"COD...", 
"body" : "--canCreateInstallation 函数 ：该命令检查是否可以使用指定版本创建安装。 打电话 : APInstaller.CLI 选项 --version <version> 必填项 Setup version in the format \"<product> 64 3.5.18.1\" or \"<product> 3.5.18.1\" (for 32 bit) Product ID string which can be parsed by the assigned installation vendor. Example: \"CODESYS 64 3.5.18.1\" 或者 \"CODESYS 3.5.18.1\" （用于 32 位）。 --channel <channel> Name of the repository channel for the setup Default setting: The setup channel configured in the installer settings Mutually exclusive with --channelFile --channelFile <channel file> Fully qualified path to a file containing the channel information. Mutually exclusive with --channel Examples APInstaller.CLI --canCreateInstallation --version \"CODESYS 64 3.5.18.0\" APInstaller.CLI --canCreateInstallation --version \"CODESYS 3.5.18.0\" --channel \"Releases\" APInstaller.CLI --canCreateInstallation --version \"CODESYS 3.5.18.0\" --channelFile \"D:\\channelFile.txt\" " }, 
{ "title" : "命令：--creatFixedInstallation ", 
"url" : "_inst_cli_cmd_createfixedinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--creatFixedInstallation ", 
"snippet" : "--createFixedInstallation 函数 ：该命令会创建与指定版本和插件完全对应的固定安装，不检查更新。 打电话 : APInstaller.CLI 选项 --version <version> 必填项 可由指定的安装供应商解析的安装版本。示例：“CODESYS 64 3.5.18.1” 或 “CODESYS 3.5.18.1”（用于 32) --channel <channel> 设置频道的名称 默认值：安装程序设置中配置的安装频道 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径。 与互不相容...", 
"body" : "--createFixedInstallation 函数 ：该命令会创建与指定版本和插件完全对应的固定安装，不检查更新。 打电话 : APInstaller.CLI 选项 --version <version> 必填项 可由指定的安装供应商解析的安装版本。示例：“CODESYS 64 3.5.18.1” 或 “CODESYS 3.5.18.1”（用于 32) --channel <channel> 设置频道的名称 默认值：安装程序设置中配置的安装频道 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径。 与互不相容 --channel --plugins <plugins> 插件 GUID 和版本元组的 JSON 序列化、以逗号分隔的列表 --pluginFile <plugin file> 包含插件 GUID 和版本元组的 JSON 序列化列表的文件的完全限定路径 --destinationFolder <destination folder> 要安装的安装目录的完全限定路径（在交互式安装中是可选的） --installationName <installation name> 安装名称（如果安装是交互式的，则为可选） --startArgs <start args> 应该用来开始安装的参数 --bit <bit> 描述设置架构的值（32 或 64） --interactive 如果设置，则可能会显示供用户输入的对话框。 默认情况下，命令以静默方式执行。 --installReferences 如果设置，则安装指定插件的所有引用 --updateMode <update mode> 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant --updatePackages 如果设置，则安装兼容更新。 --packageFile <package file path> 包含 JSON 格式的要安装的软件包列表的文件路径 与互不相容 --packages --packages <json formatted list> json 格式的要安装的软件包列表 与互不相容 --packageFile --addOnChannel <channel name> 要使用的附加频道的名称。 覆盖 --channel 如果设置了这个值。 --setupChannel <channel name> 要使用的设置频道的名称。 覆盖 --channel 如果设置了这个值。 例子 APInstaller.CLI --createFixedInstallation --version \"CODESYS 64 3.5.18.0\" --interactive --plugins \"[]\" --channel \"Releases\" APInstaller.CLI --createFixedInstallation --version \"CODESYS 64 3.5.18.0\" --interactive  --plugins \"[{\\\"Guid\\\":\\\"2b7e9a81-f3f3-4ad2-96d5-35d1af40c03c\\\",\\\"Version\\\":\\\"1.2.3.4\\\"}]\" APInstaller.CLI --createFixedInstallation --version \"CODESYS 64 3.5.18.0\" --pluginFile \"C:\\Temp\\plugins.json\"  --destinationFolder \"C:\\Program Files\\CODESYS 64 3.5.18.0\" --installReferences APInstaller.CLI --createFixedInstallation --version \"CODESYS 64 3.5.18.0\" --interactive --plugins \"[]\" --updatePackages     --addOnChannel \"Releases\" --setupChannel \"Local\" --updateMode=\"None\" APInstaller.CLI.exe --createFixedInstallation --version=\"CODESYS V3.5 SP19\"  --packages \"[{\\\"Key\\\":{\\\"Id2\\\":null,\\\"Id\\\":\\\"D1BA94E0-9823-4A49-9CE6-7B424A652307\\\"},\\\"Version\":\\\"4.3.0.0\\\"}]\" --channel \"Releases\" --interactive --updateMode=\"All\" APInstaller.CLI.exe --createFixedInstallation --version \"CODESYS V3.5 SP19\" --packages \"[{\\\"Key\\\":{\\\"Id2\\\":null,\\\"Id\\\":\\\"D1BA94E0-9823-4A49-9CE6-7B424A652307\\\"},\\\"Version\\\":\\\"4.3.0.0\\\"}]\" --channel \"Releases\" --interactive --updateMode=\"All\" " }, 
{ "title" : "命令：--createInstallation ", 
"url" : "_inst_cli_cmd_createinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--createInstallation ", 
"snippet" : "--createInstallation 函数 ：该命令根据命令行选项创建新的安装。 打电话 : APInstaller.CLI 选项 --channel <channel> 设置频道的名称 默认值：安装程序设置中配置的安装频道 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --productID <product id> 产品 ID 可由供应商解析以进行自定义安装。 --product <product> 待安装的产品 只有 CODESYS 目前可在此处获得。 --gener...", 
"body" : "--createInstallation 函数 ：该命令根据命令行选项创建新的安装。 打电话 : APInstaller.CLI 选项 --channel <channel> 设置频道的名称 默认值：安装程序设置中配置的安装频道 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --productID <product id> 产品 ID 可由供应商解析以进行自定义安装。 --product <product> 待安装的产品 只有 CODESYS 目前可在此处获得。 --generation<generation> 生成要安装的安装程序（示例： 3.5.16.0 或者 2021 ) --bit <bit> 描述设置架构的值（32 或 64） --patch <patch> 要安装的版本的补丁 --build <build> 要安装的版本的编译信息 --hotfix <hotfix> 要安装的版本的修补程序信息 --installationName <installation name> 安装名称（如果安装是交互式的，则为可选） --destinationFolder <destination folder> 要安装的安装目录的完全限定路径（在交互式安装中是可选的） --interactive 如果设置，则可能会显示供用户输入的对话框。 默认情况下，命令以静默方式执行。 --updateMode <update mode> 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant 例子 APInstaller.CLI --createInstallation --productId \"CODESYS 64 3.5.18.0\" --interactive APInstaller.CLI --createInstallation --productId \"CODESYS 64 3.5.18.0\" --destinationFolder \"C:\\Program Files\\CODESYS 64 3.5.18.0\" --installationName \"Default\" APInstaller.CLI --createInstallation --product \"CODESYS\" --generation \"3.5.18\" --bit 64 --patch 0 --hotfix 0 --build 0 --interactive " }, 
{ "title" : "命令：--createInstallationFromFile ", 
"url" : "_inst_cli_cmd_createinstallationfromfile.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--createInstallationFromFile ", 
"snippet" : "--createInstallationFromFile 函数 ：该命令会创建新的安装。 打电话 : APInstaller.CLI 选项 --sourcefile <source file> 必填项 安装文件的完全限定路径 --destinationFolder <destination folder> 要安装的安装目录的完全限定路径（在交互式安装中是可选的） --interactive 如果设置，则可能会显示供用户输入的对话框。默认情况下，命令以静默方式执行。 --noadditionalfolder 如果已设置，则不会为安装创建其他目录。 必须针对非模块化安装（3.5 SP16 及更低版...", 
"body" : "--createInstallationFromFile 函数 ：该命令会创建新的安装。 打电话 : APInstaller.CLI 选项 --sourcefile <source file> 必填项 安装文件的完全限定路径 --destinationFolder <destination folder> 要安装的安装目录的完全限定路径（在交互式安装中是可选的） --interactive 如果设置，则可能会显示供用户输入的对话框。默认情况下，命令以静默方式执行。 --noadditionalfolder 如果已设置，则不会为安装创建其他目录。 必须针对非模块化安装（3.5 SP16 及更低版本）进行设置 例子 APInstaller.CLI --createInstallationFromFile --sourcefile \"C:\\Temp\\CODESYS 3.5.18.0.exe\" --interactive APInstaller.CLI --createInstallationFromFile --sourcefile \"C:\\Temp\\CODESYS 3.5.16.0.exe\" --destinationFolder \"C:\\Program Files\\CODESYS 3.5.16.0\" --noadditionalfolder " }, 
{ "title" : "命令：--createSuitableInstallation ", 
"url" : "_inst_cli_cmd_createsuitableinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--createSuitableInstallation ", 
"snippet" : "--createSuitableInstallation 函数 : 该命令使用最新的版本创建安装 CODESYS 版本，它对应于指定类型，并打开指定的项目。 打电话 : APInstaller.CLI 选项 --types <types> 插件 GUID 和版本元组的 json 序列化列表 --typeFile <type file> 包含 JSON 序列化插件 GUID 列表的文件的完全限定路径 --startArgs <start args> 应该用来开始安装的参数 --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile ...", 
"body" : "--createSuitableInstallation 函数 : 该命令使用最新的版本创建安装 CODESYS 版本，它对应于指定类型，并打开指定的项目。 打电话 : APInstaller.CLI 选项 --types <types> 插件 GUID 和版本元组的 json 序列化列表 --typeFile <type file> 包含 JSON 序列化插件 GUID 列表的文件的完全限定路径 --startArgs <start args> 应该用来开始安装的参数 --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --installationName <installation name> 安装名称（如果安装是交互式的，则为可选） --destinationFolder <destination folder> 要安装的安装目录的完全限定路径（在交互式安装中是可选的） --bit <bit> 描述设置架构的值（32 或 64） --interactive 如果设置，则可能会显示供用户输入的对话框。默认情况下，命令以静默方式执行。 --installReferences 如果已设置，则将安装所需插件的所有可选和必需引用 --updateMode <update mode> 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant --updatePackages 如果设置，则安装兼容更新。 --addOnChannel <channel name> 要使用的附加频道。 --setupChannel <channel name> 设置要使用的频道。 例子 APInstaller.CLI --createSuitableInstallation --types \"[{\\\"Guid\\\":\\\"80e2b23c-0232-4b04-8934-1e3d659c7182\\\",\\\"Version\\\":\\\"1.2.3.4\\\"}]\" --interactive  --destinationFolder \"C:\\Program Files (x86)\\CODESYS\"  --installationName TestName --bit 32 --installReferences APInstaller.CLI --createSuitableInstallation --types \"[{\\\"Guid\\\":\\\"80e2b23c-0232-4b04-8934-1e3d659c7182\\\",\\\"Version\\\":\\\"1.2.3.4\\\"}]\"  --destinationFolder \"C:\\Program Files (x86)\\CODESYS\"  --installationName TestName --bit 64               --addOnChannel \"Releases\" --setupChannel \"Local\" --updateMode \"None\" --updatePackages " }, 
{ "title" : "命令：--discoverAddons ", 
"url" : "_inst_cli_cmd_discoveraddons.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--discoverAddons ", 
"snippet" : "--discoverAddOns 函数 ：该命令查找指定频道中满足指定搜索条件的所有插件。 打电话 : APInstaller.CLI 选项 --searchCriteria <search criteria> 序列化搜索条件的序列化列表 --serarchCriteriaFile <search criteria file> 包含序列化搜索条件列表的文件的完全限定路径 --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径。 与互不相容 --channel --...", 
"body" : "--discoverAddOns 函数 ：该命令查找指定频道中满足指定搜索条件的所有插件。 打电话 : APInstaller.CLI 选项 --searchCriteria <search criteria> 序列化搜索条件的序列化列表 --serarchCriteriaFile <search criteria file> 包含序列化搜索条件列表的文件的完全限定路径 --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径。 与互不相容 --channel --outputfile <output file> 写入命令结果的文件的完全限定路径。 如果未指定该选项，则结果将写入控制台。 --complete 如果设置，则返回为每个搜索条件找到的第一个结果。这允许直接分配搜索标准和结果。如果未找到任何符合搜索条件的内容，则此时将返回一个空条目（空 GUID） 例子 APInstaller.CLI --discoverAddOns --searchCriteria \"[{\\\"id\\\":\\\"Test.Id.1\\\"},{\\\"id\\\":\\\"c55fcb5d-3ba7-4f72-b4f9-5a02b501ee7a\\\"}]\"  --outputfile \"C:\\Temp\\out.json\" --complete APInstaller.CLI --discoverAddOns --searchCriteria \"[{\\\"id\\\":\\\"IdOrId2\\\",\\\"versionRangeFrom\\\":\\\"1.0.0\\\",\\\"versionRangeTo\\\":\\\"5.0.0.0\\\"}]\\\"  描述：搜索 ID 或 ID2 “IDoriD2” 且版本介于 1.0.0 和 5.0.0.0 之间的插件 APInstaller.CLI --discoverAddOns --searchCriteria \\\"[{\\\"id\\\":\\\"IdOrId2\\\",\\\"versionRangeFrom\\\":\\\"1.0.0\\\",\\\"versionRangeTo\\\":\\\"5.0.0.0\\\",\\\"requiredInstallerVersionRangeFrom\\\":\\\"6.0.0.0\\\",\\\"requiredInstallerVersionRangeTo\\\":\\\"7.0.0.0\\\",\\\"etag\\\":\\\"MyFancyEtag\\\",\\\"name\\\":\\\"PackageName\\\",\\\"vendor\\\":\\\"AnyVendorName\\\",\\\"copyright\\\":\\\"anyCopyrightText\\\",\\\"description\\\":\\\"anyDescriptionText\\\",\\\"plugIn\\\":\\\"{\\\"AssemblyName\\\":\\\"PlugInAssemblyName\\\",\\\"ProcessorArchitecture\\\":1,\\\"Title\\\":\\\"PlugInTitle\\\",\\\"Description\\\":\\\"PlugInDescription\\\",\\\"Company\\\":\\\"PlugInCompanyName\\\",\\\"Product\\\":\\\"PlugInProductName\\\",\\\"Copyright\\\":\\\"pluginCopyright\\\",\\\"Trademark\\\":\\\"PlugInTrademarkText\\\",\\\"LicenseProtectionData\\\":\\\"CodeMeter;101597;602009;http:\/\/license.codesys.com;support@3s-software.com;AllowNetwork\\\",\\\"Guid\\\":\\\"606bd719-1aa9-425a-9fbd-c0ec2ab48d17\\\",\\\"Version\\\":\\\"1.2.3.4\\\",}\\\",\\\"tag\\\":\\\"['ThisIsATag']\\\"}]\\\" 描述：使用所有可能的搜索字段进行搜索 \"[\n   { \n     \"id\":\"IdOrId2\",\n      \"versionRangeFrom\":\"1.0.0\",\n      \"versionRangeTo\":\"5.0.0.0\",\n      \"requiredInstallerVersionRangeFrom\":\"6.0.0.0\",\n      \"requiredInstallerVersionRangeTo\":\"7.0.0.0\",\n      \"etag\":\"MyFancyEtag\",\n      \"name\":\"PackageName\",\n      \"vendor\":\"AnyVendorName\",\n      \"copyright\":\"anyCopyrightText\",\n      \"description\":\"anyDescriptionText\",\n      \"plugIn\":\"{ \n        \"AssemblyName\":\"PlugInAssemblyName\", \n        \"ProcessorArchitecture\":1, \n        \"Title\":\"PlugInTitle\",\n         \"Description\":\"PlugInDescription\", \n        \"Company\":\"PlugInCompanyName\", \n        \"Product\":\"PlugInProductName\",\n         \"Copyright\":\"pluginCopyright\", \n        \"Trademark\":\"PlugInTrademarkText\", \n        \"LicenseProtectionData\":\"CodeMeter;101597;602009;http:\/\/license.codesys.com;support@3s-software.com;AllowNetwork\",   \n       \"Guid\":\"606bd719-1aa9-425a-9fbd-c0ec2ab48d17\", \n        \"Version\":\"1.2.3.4\",\n      }\",\n      \"tag\":\"['ThisIsATag']\"   \n }\n]\" " }, 
{ "title" : "命令：--discoverAddOnUpdates ", 
"url" : "_inst_cli_cmd_discoveraddonupdates.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--discoverAddOnUpdates ", 
"snippet" : "--discoverAddOnUpdates 函数 ：该命令查找指定频道中已安装插件的所有更新。除非使用 “--force” 选项，否则此功能每天只能使用一次 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --channel <channel> 包含频道信息的字符串 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --outputfile <output file> 写入命令结果的文件的完全限定路径。...", 
"body" : "--discoverAddOnUpdates 函数 ：该命令查找指定频道中已安装插件的所有更新。除非使用 “--force” 选项，否则此功能每天只能使用一次 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --channel <channel> 包含频道信息的字符串 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --outputfile <output file> 写入命令结果的文件的完全限定路径。 如果未指定该选项，则结果将写入控制台。 --updateMode <update mode> 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant --force 强制执行命令 例子 APInstaller.CLI --discoverAddOnUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" APInstaller.CLI --discoverAddOnUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --channel \"Releases\" APInstaller.CLI --discoverAddOnUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --channelFile \"C:\\channel.txt\" APInstaller.CLI --discoverAddOnUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --updateMode \"All\" --force " }, 
{ "title" : "命令：--discoverSetupDates ", 
"url" : "_inst_cli_cmd_discoversetupupdates.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--discoverSetupDates ", 
"snippet" : "--discoverSetupUpdates 函数 ：该命令查找指定频道中已安装设置的所有更新。除非使用 “--force” 选项，否则此功能每天只能使用一次 打电话 : APInstaller.CLI 选项 --location <location> 安装目录的完全限定路径 必填项 --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --outputfile <output file> 写入命令结果的文件的完全限定路径。如果未...", 
"body" : "--discoverSetupUpdates 函数 ：该命令查找指定频道中已安装设置的所有更新。除非使用 “--force” 选项，否则此功能每天只能使用一次 打电话 : APInstaller.CLI 选项 --location <location> 安装目录的完全限定路径 必填项 --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径 与互不相容 --channel --outputfile <output file> 写入命令结果的文件的完全限定路径。如果未指定，则结果将写入控制台。 --updateMode <update mode> 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant --force 强制执行命令 例子 APInstaller.CLI --discoverSetupUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" APInstaller.CLI --discoverSetupUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --channel=\"Releases\" APInstaller.CLI --discoverSetupUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --channelFile=\"C:\\channel.txt\" APInstaller.CLI --discoverSetupUpdates --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --updateMode=\"All\" --force " }, 
{ "title" : "命令：--downloadAddon ", 
"url" : "_inst_cli_cmd_downloadaddon.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--downloadAddon ", 
"snippet" : "--downloadAddOn 函数 ：该命令将指定的插件下载到指定的目标目录。 打电话 : APInstaller.CLI 选项 --targetDirectory <target directory> 必填项 存储下载内容的目标目录 --location <location> 安装目录的完全限定路径 如果已设置，则安装的所有插件都存储在目标目录中。指定的软件包 GUID 将被忽略 --packageIds <packages> 包 GUID 和版本元组的 json 序列化列表 --channel <channel> 设置频道的名称。 如果不使用此选项，则只要指定了安装的附加频道，就会使用它...", 
"body" : "--downloadAddOn 函数 ：该命令将指定的插件下载到指定的目标目录。 打电话 : APInstaller.CLI 选项 --targetDirectory <target directory> 必填项 存储下载内容的目标目录 --location <location> 安装目录的完全限定路径 如果已设置，则安装的所有插件都存储在目标目录中。指定的软件包 GUID 将被忽略 --packageIds <packages> 包 GUID 和版本元组的 json 序列化列表 --channel <channel> 设置频道的名称。 如果不使用此选项，则只要指定了安装的附加频道，就会使用它。默认设置：“发布” 例子 APInstaller.CLI.exe --downloadAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --targetDirectory=\"C:\\temp\\sandbox\" APInstaller.CLI.exe --downloadAddOn --packageIds \"[{\\\"Guid\\\":\\\"2b7e9a81-f3f3-4ad2-96d5-35d1af40c03c\\\",\\\"Version\\\":\\\"1.2.3.4\\\"}]\" --targetDirectory=\"C:\\temp\\sandbox\" --channel=\"CustomRepo\" " }, 
{ "title" : "命令：--getAddon ", 
"url" : "_inst_cli_cmd_getaddon.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--getAddon ", 
"snippet" : "--getAddOn 函数 : 如果指定插件安装在指定安装中，则返回有关该插件的信息 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --id <id> 必填项 ID (Guid) or ID2 (String). Individually or both; separated by a semicolon. Example: \"<Guid>;<Id2>\" --outputfile <output file> Fully qualified path to a file where the result of the...", 
"body" : "--getAddOn 函数 : 如果指定插件安装在指定安装中，则返回有关该插件的信息 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --id <id> 必填项 ID (Guid) or ID2 (String). Individually or both; separated by a semicolon. Example: \"<Guid>;<Id2>\" --outputfile <output file> Fully qualified path to a file where the result of the command is to be written. 如果未指定此选项，则结果将写入控制台。 Examples APInstaller.CLI --getAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \"test.package.id\" APInstaller.CLI --getAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \"f22b01fc-ccbb-40ba-97f0-35d2648dc17e\" --outputfile=\"C:\\outFile.txt\" " }, 
{ "title" : "命令：--getAddons ", 
"url" : "_inst_cli_cmd_getaddons.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--getAddons ", 
"snippet" : "--getAddOns 函数 ：该命令返回有关当前在指定安装中安装的所有插件的信息。 打电话 : APInstaller.CLI 选项 --location <location> Fully qualified path to the installation directory --outputfile <output file> Fully qualified path to a file where the result of the command is to be written 如果未指定此选项，则结果将写入控制台。 --export Use installation config...", 
"body" : "--getAddOns 函数 ：该命令返回有关当前在指定安装中安装的所有插件的信息。 打电话 : APInstaller.CLI 选项 --location <location> Fully qualified path to the installation directory --outputfile <output file> Fully qualified path to a file where the result of the command is to be written 如果未指定此选项，则结果将写入控制台。 --export Use installation configuration format 例子 APInstaller.CLI --getAddOns --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" APInstaller.CLI --getAddOns --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --export " }, 
{ "title" : "命令：--getInstallation ", 
"url" : "_inst_cli_cmd_getinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--getInstallation ", 
"snippet" : "--getInstallation 函数 ：该命令返回有关指定安装的信息。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --outputfile <output file> 写入命令结果的文件的完全限定路径 如果未指定此选项，则结果将写入控制台。 示例 APInstaller.CLI --getInstallation --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --outputfile \"C:\\...", 
"body" : "--getInstallation 函数 ：该命令返回有关指定安装的信息。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --outputfile <output file> 写入命令结果的文件的完全限定路径 如果未指定此选项，则结果将写入控制台。 示例 APInstaller.CLI --getInstallation --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --outputfile \"C:\\outFile.txt\" " }, 
{ "title" : "命令：--getInstallations ", 
"url" : "_inst_cli_cmd_getinstallations.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--getInstallations ", 
"snippet" : "--getInstallations 函数 ：该命令返回有关所有当前已安装的安装的信息。 打电话 : APInstaller.CLI 选项 --outputfile <output file> 写入命令结果的文件的完全限定路径 如果未指定此选项，则结果将写入控制台。 --minimal 如果已设置，则仅返回有关每次安装的基本信息（不返回插件或设置） 示例 APInstaller.CLI --getInstallations --minimal --outputfile=\"C:\\outFile.txt\"...", 
"body" : "--getInstallations 函数 ：该命令返回有关所有当前已安装的安装的信息。 打电话 : APInstaller.CLI 选项 --outputfile <output file> 写入命令结果的文件的完全限定路径 如果未指定此选项，则结果将写入控制台。 --minimal 如果已设置，则仅返回有关每次安装的基本信息（不返回插件或设置） 示例 APInstaller.CLI --getInstallations --minimal --outputfile=\"C:\\outFile.txt\" " }, 
{ "title" : "命令：--installAddon ", 
"url" : "_inst_cli_cmd_installaddon.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--installAddon ", 
"snippet" : "--installAddOn 函数 ：该命令会在指定的安装中安装插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --id <id> ID（GUID）和\/或 ID2（字符串）。可单独使用或同时使用，用分号分隔。示例： \"<Guid>;<ID2>\" --version <version> 必填项 插件的版本（示例： \"1.0.0.0\" ) --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完...", 
"body" : "--installAddOn 函数 ：该命令会在指定的安装中安装插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --id <id> ID（GUID）和\/或 ID2（字符串）。可单独使用或同时使用，用分号分隔。示例： \"<Guid>;<ID2>\" --version <version> 必填项 插件的版本（示例： \"1.0.0.0\" ) --channel <channel> 设置频道的名称 与互不相容 --channelFile --channelFile <channel file> 包含频道信息的文件的完全限定路径。 与互不相容 --channel --updateMode <update mode> 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant --interactive 如果设置，则可能会显示供用户输入的对话框。默认情况下，命令以静默方式执行。 例子 APInstaller.CLI --installAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \" test.package.id \" --version \"1.2.3.4\" APInstaller.CLI --installAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \"f22b01fc-ccbb-40ba-97f0-35d2648dc17e\" --version \"1.2.3.4\" --channel \"Releases\" --updateMode=\"All\" " }, 
{ "title" : "命令：--installAddons ", 
"url" : "_inst_cli_cmd_installaddons.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--installAddons ", 
"snippet" : "--installAddOns 函数 ：该命令使用文件夹或 *.installation-config 文件安装所有指定的插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --folder <folder> 安装目录中的所有插件 与互不相容 --file 要么 --folder 或者 --file 必须指定。 --channel <channel> 必填项 设置频道的名称 --file <file> *.installation-config file 要从哪些插件中安装 与互不相容 --folder 要么 -...", 
"body" : "--installAddOns 函数 ：该命令使用文件夹或 *.installation-config 文件安装所有指定的插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --folder <folder> 安装目录中的所有插件 与互不相容 --file 要么 --folder 或者 --file 必须指定。 --channel <channel> 必填项 设置频道的名称 --file <file> *.installation-config file 要从哪些插件中安装 与互不相容 --folder 要么 --folder 或者 --file 必须指定。 例子 APInstaller.CLI --installAddOns --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --channel \"Releases\" --file \"C:\\test.installation-config\" APInstaller.CLI --installAddOns --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --channel \"Releases\" --folder \"C:\\packages\\\" " }, 
{ "title" : "命令：--installAddOnFromFile ", 
"url" : "_inst_cli_cmd_installaddonfromfile.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--installAddOnFromFile ", 
"snippet" : "--installAddOnFromFile 函数 ：该命令使用指定安装中的指定软件包文件安装插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --sourcefile <source file> 必填项 包文件的完全限定路径 --interactive 如果设置，则可能会显示供用户输入的对话框。默认情况下，命令以静默方式执行。 --updateMode 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant...", 
"body" : "--installAddOnFromFile 函数 ：该命令使用指定安装中的指定软件包文件安装插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --sourcefile <source file> 必填项 包文件的完全限定路径 --interactive 如果设置，则可能会显示供用户输入的对话框。默认情况下，命令以静默方式执行。 --updateMode 指明应检索哪种类型的更新： All ， None ， SafeUpdate ， SecurityRelevant ， SafeSecurityRelevant --channel <channel> 设置频道的名称 示例 APInstaller.CLI --installAddOnFromFile --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --sourcefile \"C:\\Temp test.package\" --interactive --updateMode=\"All\" --channel\"LocalRepo\" " }, 
{ "title" : "命令：--removeAllInstallations ", 
"url" : "_inst_cli_cmd_removeallinstallations.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--removeAllInstallations ", 
"snippet" : "--removeAllInstallations 函数 ：该命令将卸载所有当前已安装的安装。 打电话 : APInstaller.CLI 选项 --interactive 如果设置，则可能会显示供用户输入的对话框 默认情况下，命令以静默方式执行。 示例 APInstaller.CLI --removeAllInstallations --interactive...", 
"body" : "--removeAllInstallations 函数 ：该命令将卸载所有当前已安装的安装。 打电话 : APInstaller.CLI 选项 --interactive 如果设置，则可能会显示供用户输入的对话框 默认情况下，命令以静默方式执行。 示例 APInstaller.CLI --removeAllInstallations --interactive " }, 
{ "title" : "命令：--removeInstallation ", 
"url" : "_inst_cli_cmd_removeinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--removeInstallation ", 
"snippet" : "--removeInstallation 函数 ：该命令会卸载指定的安装程序。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --interactive 如果设置，则可能会显示供用户输入的对话框 默认情况下，命令以静默方式执行。 示例 APInstaller.CLI --removeInstallation --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\"...", 
"body" : "--removeInstallation 函数 ：该命令会卸载指定的安装程序。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --interactive 如果设置，则可能会显示供用户输入的对话框 默认情况下，命令以静默方式执行。 示例 APInstaller.CLI --removeInstallation --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" " }, 
{ "title" : "命令：--removeSandbox ", 
"url" : "_inst_cli_cmd_removesandbox.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--removeSandbox ", 
"snippet" : "--removeSandbox 命令 ：该命令将沙箱从设置中移除。 打电话 : APInstaller.CLI 选项 --targetDirectory <target directory> 必填项 目录的完全限定路径 示例 APInstaller.CLI --removeSandbox --targetDirectory \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\"...", 
"body" : "--removeSandbox 命令 ：该命令将沙箱从设置中移除。 打电话 : APInstaller.CLI 选项 --targetDirectory <target directory> 必填项 目录的完全限定路径 示例 APInstaller.CLI --removeSandbox --targetDirectory \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" " }, 
{ "title" : "命令：--searchInstallation ", 
"url" : "_inst_cli_cmd_searchinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--searchInstallation ", 
"snippet" : "--searchInstallation 函数 ：该命令搜索符合指定条件的已安装的安装。 打电话 : APInstaller.CLI 选项 --types <types> 插件 GUID 和版本元组的 json 序列化列表。与互不相容 --typeFile 。 --typeFile <type file> 包含插件 GUID 和版本元组的 json 序列化列表的文件的完全限定路径。与互不相容 --types 。 --plugins <plugins> 插件 GUID 和版本元组的 json 序列化列表 与互不相容 --pluginFile 。 --pluginFile <plugin file...", 
"body" : "--searchInstallation 函数 ：该命令搜索符合指定条件的已安装的安装。 打电话 : APInstaller.CLI 选项 --types <types> 插件 GUID 和版本元组的 json 序列化列表。与互不相容 --typeFile 。 --typeFile <type file> 包含插件 GUID 和版本元组的 json 序列化列表的文件的完全限定路径。与互不相容 --types 。 --plugins <plugins> 插件 GUID 和版本元组的 json 序列化列表 与互不相容 --pluginFile 。 --pluginFile <plugin file> 包含插件 GUID 和版本元组的 json 序列化列表的文件的完全限定路径 与互不相容 --plugins 。 --outputfile <output file> 写入命令结果的文件的完全限定路径 如果未指定，则结果将改为写入控制台。 示例 APInstaller.CLI --searchInstallation --types \"[{\\\"Guid\\\":\\\"d1a449f0-21c2-471d-b02a-79af0fa4a974\\\",\\\"Version\\\":\\\"1.2.3.4\\\"}]\" APInstaller.CLI --searchInstallation --typesFile \"C:\\typeFile.json\" --outputfile \"C:\\outFile.txt\" APInstaller.CLI --searchInstallation --plugins \"[{\\\"Guid\\\":\\\"2b7e9a81-f3f3-4ad2-96d5-35d1af40c03c\\\",\\\"Version\\\":\\\"1.2.3.4\\\"}]\" APInstaller.CLI --searchInstallation --pluginFile \"C:\\pluginFile.json\" " }, 
{ "title" : "命令：--selfUpdate ", 
"url" : "_inst_cli_cmd_installaddon-1766836.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--selfUpdate ", 
"snippet" : "--selfUpdate 函数 ：该命令更新安装程序。 打电话 : APInstaller.CLI 选项 --thumbprint <thumbprint> 用于验证更新的指纹 --skipCertValidation 如果设置，则跳过更新文件的证书验证。 设置此标志可能会导致安全问题。 --interactive 如果设置，则可以打开供用户输入的对话框 默认情况下，命令以静默方式执行。 示例 APInstaller.CLI --selfUpdate --skipCertValidation ...", 
"body" : "--selfUpdate 函数 ：该命令更新安装程序。 打电话 : APInstaller.CLI 选项 --thumbprint <thumbprint> 用于验证更新的指纹 --skipCertValidation 如果设置，则跳过更新文件的证书验证。 设置此标志可能会导致安全问题。 --interactive 如果设置，则可以打开供用户输入的对话框 默认情况下，命令以静默方式执行。 示例 APInstaller.CLI --selfUpdate --skipCertValidation  " }, 
{ "title" : "命令：--startInstallation ", 
"url" : "_inst_cli_cmd_startinstallation.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--startInstallation ", 
"snippet" : "--startInstallation 函数 ：该命令启动指定的安装。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --startArgs <start args> 应该用来开始安装的参数 示例 APInstaller.CLI --startInstallation --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --startArgs \"--project=\\\"C:\\Temp\\test.projec...", 
"body" : "--startInstallation 函数 ：该命令启动指定的安装。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --startArgs <start args> 应该用来开始安装的参数 示例 APInstaller.CLI --startInstallation --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --startArgs \"--project=\\\"C:\\Temp\\test.project\\\"\" " }, 
{ "title" : "命令：--uninstallAddon ", 
"url" : "_inst_cli_cmd_uninstalladdon.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ CLI 命令 \/ 命令：--uninstallAddon ", 
"snippet" : "--uninstallAddOn 函数 ：该命令将从指定安装中卸载指定的插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --id <id> 必填项 ID (GUID) 或 ID2 (字符串)；可为单一或同时使用两者；以分号分隔。示例: \"<Guid>;<ID2>\" 示例 APInstaller.CLI --uninstallAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \" ...", 
"body" : "--uninstallAddOn 函数 ：该命令将从指定安装中卸载指定的插件。 打电话 : APInstaller.CLI 选项 --location <location> 必填项 安装目录的完全限定路径 --id <id> 必填项 ID (GUID) 或 ID2 (字符串)；可为单一或同时使用两者；以分号分隔。示例: \"<Guid>;<ID2>\" 示例 APInstaller.CLI --uninstallAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \" test.package.id APInstaller.CLI --uninstallAddOn --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --id \"f22b01fc-ccbb-40ba-97f0-35d2648dc17e --version \"1.0.0.0\" " }, 
{ "title" : "GUI 命令 ", 
"url" : "_inst_gui_commands.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ GUI 命令 ", 
"snippet" : "这个 APInstaller.GUI 提供使用预定义行为直接打开用户界面 (GUI) 的命令。 语法 APInstaller.GUI <command> <option1> <option2> ......", 
"body" : "这个 APInstaller.GUI 提供使用预定义行为直接打开用户界面 (GUI) 的命令。 语法 APInstaller.GUI <command> <option1> <option2> ... " }, 
{ "title" : "命令：--view ", 
"url" : "_inst_gui_cmd_view.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ GUI 命令 \/ 命令：--view ", 
"snippet" : "--view 函数 ：该命令将在中打开指定安装的详细视图 CODESYS Installer 。 打电话 : APInstaller.GUI 选项 --location <location> 必填项 要显示安装的根目录 --perspective <perspective> 要显示的详细视图的透视图： installed : 视角 已安装 browse : 视角 浏览 updates : 视角 更新 示例 APInstaller.GUI --view --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\...", 
"body" : "--view 函数 ：该命令将在中打开指定安装的详细视图 CODESYS Installer 。 打电话 : APInstaller.GUI 选项 --location <location> 必填项 要显示安装的根目录 --perspective <perspective> 要显示的详细视图的透视图： installed : 视角 已安装 browse : 视角 浏览 updates : 视角 更新 示例 APInstaller.GUI --view --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\" --perspective \"updates\" " }, 
{ "title" : "命令：--open ", 
"url" : "_inst_gui_cmd_open.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ GUI 命令 \/ 命令：--open ", 
"snippet" : "--open 函数 : 该命令打开一个项目并使用匹配项 CODESYS 安装。如果找到多个匹配的安装，则会打开一个对话框供选择。该命令支持项目、库和项目存档。如果找不到匹配的安装，则会提供一个按钮来创建安装。 打电话 : APInstaller.GUI 选项 --project <project path> 必填项 项目文件、库文件或项目存档文件的路径 示例 APInstaller.GUI --open --project \"C:\\Users\\XYZ\\Documents\\MyProject.project\"...", 
"body" : "--open 函数 : 该命令打开一个项目并使用匹配项 CODESYS 安装。如果找到多个匹配的安装，则会打开一个对话框供选择。该命令支持项目、库和项目存档。如果找不到匹配的安装，则会提供一个按钮来创建安装。 打电话 : APInstaller.GUI 选项 --project <project path> 必填项 项目文件、库文件或项目存档文件的路径 示例 APInstaller.GUI --open --project \"C:\\Users\\XYZ\\Documents\\MyProject.project\" " }, 
{ "title" : "命令 (Gui):--installPackageFile ", 
"url" : "_inst_gui_cmd_installpackagefile.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ GUI 命令 \/ 命令 (Gui):--installPackageFile ", 
"snippet" : "--installPackageFile 函数 ：该命令会打开一个对话框，供用户选择安装插件的安装位置。 打电话 : APInstaller.GUI 选项 --packageFilePath <package file path> 必填项 通往之路 *.package 要安装的文件。 示例 APInstaller.GUI --installPackageFile --packageFilePath \"C:\\Temp\\test.package\"...", 
"body" : "--installPackageFile 函数 ：该命令会打开一个对话框，供用户选择安装插件的安装位置。 打电话 : APInstaller.GUI 选项 --packageFilePath <package file path> 必填项 通往之路 *.package 要安装的文件。 示例 APInstaller.GUI --installPackageFile --packageFilePath \"C:\\Temp\\test.package\" " }, 
{ "title" : "命令：--installPackages ", 
"url" : "_inst_gui_cmd_installpackages.html", 
"breadcrumbs" : "CODESYS Installer \/ 参考 \/ 命令行界面 \/ GUI 命令 \/ 命令：--installPackages ", 
"snippet" : "--installPackages 函数 ：该命令将指定的软件包安装到指定的安装中。 打电话 : APInstaller.GUI 选项 --packages <packages> JSON 格式的要安装的软件包列表。与互不相容 --packageFile 其中一个选项 --packages ， --packageFile ，或 --packageFilePath 必须设置。 --packageFile <package file> 含 JSON 格式的要安装的软件包列表的文件路径。与互不相容 --packages 。其中一个选项 --packages ， --packageFile ，或 --...", 
"body" : "--installPackages 函数 ：该命令将指定的软件包安装到指定的安装中。 打电话 : APInstaller.GUI 选项 --packages <packages> JSON 格式的要安装的软件包列表。与互不相容 --packageFile 其中一个选项 --packages ， --packageFile ，或 --packageFilePath 必须设置。 --packageFile <package file> 含 JSON 格式的要安装的软件包列表的文件路径。与互不相容 --packages 。其中一个选项 --packages ， --packageFile ，或 --packageFilePath 必须设置。 --location <location> 必填项 要安装软件包的安装根目录 --packageFilePath <package file path> 通往之路 *.package file 待安装。如果已设置，那么 --packages 和 --packageFile 被忽略。其中一个选项 --packages ， --packageFile ，或 --packageFilePath 必须设置。 --channel <channel> 搜索包裹的频道。默认设置：安装程序设置中配置的安装频道。 --startArgs <start args> 用于在软件包安装完成后开始安装的参数。 如果省略此选项，则无法开始安装。 例子 APInstaller.GUI --installPackages --location \"C:\\Program Files\\CODESYS 3.5.18.0\\CODESYS\\AdditionalFolders\\Default\"         --packages \"[{\\\"Key\\\":{\\\"Id2\\\":\\\"CODESYS.SFC\\\",\\\"Id\\\":\\\"39c4804e-d000-4f42-8774-cba1c1401aea\\\"},\\\"Version\\\":\\\"4.1.0.0\\\"}]\"   --channel \"Releases\" --startArgs \"--project \\\"C:\\Temp\\test.project\\\"\" " }
]
$(document).trigger('search.ready');
});